import "server-only";

import { loadElectionPlanSnapshotFromDisk } from "./election-plan-snapshot-disk";
import type { ElectionPlanWorkbenchSnapshot } from "./types";

export { ELECTION_PLAN_SNAPSHOT_PATH } from "./election-plan-snapshot-disk";

/** Minimal fallback when snapshot has not been built yet — no unsourced plan numbers. */
export function fallbackElectionPlanSnapshot(): ElectionPlanWorkbenchSnapshot {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    classification: "Internal campaign strategy presentation — not for public distribution.",
    hero: {
      title: "Arkansas Plurality Victory Plan",
      subtitle: "Kelly Grappe for Secretary of State",
      tagline:
        "The 20-week campaign operating plan to win a three-candidate race by building the largest coalition in Arkansas.",
      metrics: [
        { label: "Expected projection", value: "—" },
        { label: "Plurality win range", value: "—" },
        { label: "Democratic drop-off pool", value: "—" },
        { label: "Lane 2 @ 50% recovery", value: "—" },
        { label: "Registration goal", value: "—" },
        { label: "Top 125 city target", value: "—" },
        { label: "Verified events", value: "— / —", detail: "Run npm run election-plan:build" },
      ],
    },
    executive: {
      summary: "Run npm run election-plan:build to load live campaign data from the strategic plan pipeline.",
      constraints: ["Snapshot not found — build pipeline has not run."],
      cards: [],
      brainStatus: "Pending snapshot build",
      calendarTruthRequirement: "Do not lock the 20-week calendar until Calendar Truth exit criteria are met.",
    },
    theoryOfVictory: { lanes: [], doctrine: { title: "Big Table Democrat Doctrine", pillars: [], tableBeliefs: [] } },
    electoralMath: {
      baselineD: 0,
      traditionalMajorityTarget: 0,
      pluralityRange: { low: 0, high: 0 },
      scenarios: [],
      dropOff: {
        presidential2024Dem: 0,
        midterm2022Dem: 0,
        rawDropOff: 0,
        recovery50: 0,
        recovery75: 0,
      },
      explanation: "Run npm run election-plan:build to load SOS-derived electoral math.",
    },
    lanesOverview: {
      expectedProjection: 0,
      pluralityRange: { low: 0, high: 0 },
      achievementRates: { lane2: 0, lane3: 0, lane4: 0 },
      lanes: [],
      scenarios: [],
      topCounties: [],
      clusterContribution: [],
      explanation: "Run npm run election-plan:build to load lane overview from the strategic plan.",
    },
    counties: [],
    cities: [],
    top10TargetVotes: 0,
    top40TargetVotes: 0,
    top125TargetVotes: 0,
    top100TargetVotes: 0,
    top75TargetVotes: 0,
    campaignBrain: { flow: "Strategic Plan → Campaign Brain → Weekly Execution", modules: [] },
    calendarTruth: {
      verifiedEvents: 0,
      verifiedGoal: 300,
      tentativeEvents: 0,
      missingDates: 0,
      countyFairsVerified: "0 / 75",
      tierAEventsVerified: "0 / 62",
      countyContactOwners: "0 / 75",
      outcomeReportPct: 0,
      phase9Ready: false,
      warning:
        "The Campaign Brain is ready. The data supply chain is not. Do not lock the 20-week calendar until Calendar Truth exit criteria are met.",
      exitCriteria: [],
    },
    relationshipCapital: {
      doctrine: "Relationships create trust. Trust creates turnout. Turnout creates victory.",
      index: 0,
      assets: [],
      programs: [],
      channels: [],
    },
    execution: {
      lockNotice:
        "Week plans remain candidate schedules until event dates are verified and leadership approves lock.",
      clusters: [],
      weekCandidates: [],
    },
    architecture: [],
    peoplePower: {
      foundingVolunteersGoal: 20,
      foundingVolunteersCurrent: 0,
      foundingVolunteers: [],
      launchLabel: "June 28 · 6 PM · Zoom",
      retreatLocation: "Forevermost Farms",
      monthlyCalls: "Last Sunday · 6 PM",
      mobilizeEventsLinked: 0,
      mobilizeRsvpTotal: 0,
      substackStoriesPublished: 0,
      strikeTeamCoveragePct: 0,
      powerOf5Commitments: 0,
      storyWorkflow: [
        "Campaign Brain",
        "Mobilize Event",
        "Volunteer Recruitment",
        "Event",
        "Substack Story",
        "Email",
        "Social Media",
        "Local Sharing",
        "Relationship Growth",
      ],
      communityRelationshipIndex: [],
      sections: [],
    },
    citizenVoices: {
      networkName: "Citizen Voices Network",
      programName: "Arkansas Citizen Voices Project",
      positioning: "Not a Kelly promotion team — authentic community voices",
      doctrine: "Earned media · local validation · meaningful volunteer role without canvassing",
      laborDayDeadline: "2026-09-07",
      foundingWritersGoal: 20,
      foundingWritersCurrent: 0,
      activeWritersGoal: 50,
      activeWritersCurrent: 0,
      lettersSubmitted: 0,
      lettersSubmittedGoal: 200,
      lettersPublished: 0,
      guestColumnsPublished: 0,
      countiesRepresented: 0,
      countiesGoal: 75,
      outletsInInventory: 34,
      weeklyTargets: {
        lettersSubmitted: 25,
        lettersPublished: 10,
        guestColumnsSubmitted: 5,
        guestColumnsPublished: 2,
      },
      editorialRhythm: [
        { day: "Monday", activity: "Issue brief to writers" },
        { day: "Thursday", activity: "Submission day" },
        { day: "Friday", activity: "Publication tracking" },
      ],
      contentCategories: [],
      docPath: "docs/campaign-brain/citizen-voices/CITIZEN-VOICES-NETWORK.md",
    },
    studentsForArkansas: {
      programName: "Kelly Grappe Students for Arkansas",
      doctrine: "Statewide student movement — survives beyond Election Day",
      laborDayDeadline: "2026-09-07",
      coChairsConfirmed: 2,
      coChairsGoal: 5,
      coChairsOpen: 3,
      foundingCoChairs: [],
      campusLeaders: 0,
      campusLeadersLaborDayGoal: 25,
      studentVolunteers: 0,
      studentVolunteersLaborDayGoal: 100,
      voterRegistrations: 0,
      voterRegistrationsLaborDayGoal: 500,
      voterRegistrationsOctoberGoal: 2500,
      voterRegistrationsElectionGoal: 5000,
      activeCampuses: 0,
      activeCampusesOctoberGoal: 10,
      campusesInInventory: 14,
      campusRoles: [],
      internshipTracks: [],
      fundraisingCommissionPercent: 15,
      powerOf5Integration: "",
      monthlyRequirements: [],
      semesterRequirements: [],
      docPath: "docs/campaign-brain/students-for-arkansas/STUDENTS-FOR-ARKANSAS.md",
      june28BriefPath: "docs/campaign-brain/students-for-arkansas/JUNE-28-LAUNCH-BRIEF.md",
      executiveBookHref: "/election-plan/executive-book/students-for-arkansas",
    },
    motionPresence: {
      doctrine:
        "The Arkansas Presence Strategy — visible statewide motion. When voters ask 'Has Kelly been to my area?' the answer should almost always be yes.",
      goal: "1000 Arkansas Stories",
      arkansasPresenceScore: 0,
      septemberPersuasionReadiness: 0,
      countiesVisited: 0,
      countiesTotal: 75,
      citiesVisited: 0,
      stopsCompleted: 0,
      milesTraveled: 0,
      eventsAttended: 0,
      storiesPublished: 0,
      storiesPending: 0,
      storiesShared: 0,
      substackPublished: 0,
      videosPublished: 0,
      socialPostsPublished: 0,
      localBusinessesHighlighted: 0,
      churchesHighlighted: 0,
      schoolsHighlighted: 0,
      mediaMentions: 0,
      peopleSpotlighted: 0,
      contentPyramidCompletionPct: 0,
      storyCategories: [],
      countyMap: [],
      recentStops: [],
      cadence: [],
      storyWorkflow: [
        "Campaign Brain",
        "Mobilize",
        "Event",
        "Content Capture",
        "Story Publication",
        "Email",
        "Social",
        "Community Sharing",
        "Volunteer Recruitment",
      ],
      components: [],
    },
    forwardMotion: {
      heroLine:
        "Showing where Kelly is going next is as important as proving where she has already been.",
      upcomingCount: 0,
      nextWeekCount: 0,
      priorityWindowCount: 0,
      avgActivationReadiness: 0,
      explanation:
        "Scored field opportunities from the Forward Motion activation queue. Run npm run election-plan:build to load live data.",
      stops: [],
      stopsNext7Days: [],
      stopsNext21Days: [],
      stopsThroughElection: [],
      throughElectionCount: 0,
      missingPieces: [],
      components: [],
    },
    mediaOutreach: {
      heroLine: "Rural credibility runs through local papers and radio — APA coordinates statewide LTE and visit-adjacent print.",
      disclaimer: "Run npm run campaign-brain:apa-media:build to load live APA media queue.",
      partner: { name: "Arkansas Press Association", shortName: "APA", relationshipStatus: "active_negotiation" },
      summary: {
        ruralVisitCount: 0,
        printUrgentCount: 0,
        radioResearchCount: 0,
        lteDraftNeeded: 0,
        statewideLteMonthlyCost: 300,
        statewideLteCampaignTotal: 1800,
      },
      monthlyLte: [],
      visitPlacements: [],
      programs: [],
    },
    coalitionPowerMap: {
      heroLine: "Move from opportunity to organized relationships.",
      naacp: { branchesTotal: 0, called: 0, meetingsRequested: 0, speakingScheduled: 0 },
      aea: { countiesActive: 0, teacherSupporters: 0, meetingsCompleted: 0 },
      muslim: { contactsTotal: 0, meetingsOpen: 0, meetingsRequested: 0 },
      hispanic: { frameworkStatus: "pending_jasmine_review", lead: "Jasmine Serano", pendingJasmineReview: true },
      labor: { unionsTotal: 0, contacted: 0, meetingsCompleted: 0, endorsementsInProgress: 0 },
      electedOfficials: { contacted: 0, total: 0, meetingsCompleted: 0, introductionsRequested: 0 },
      candidates: { activePartnerships: 0, sharedEvents: 0, jointMobilize: 0 },
      pastOfficials: { engaged: 0, total: 0 },
      sherwood: { goal: "—", vipTablesSold: 0, vipTablesGoal: 0, ticketsSold: 0, status: "planning", onTrack: false },
      cityForums: { planned: 0, booked: 0, total: 20, fortSmithBooked: false },
      ruralTownhalls: { planned: 0, total: 10 },
      standardAskPackage: [],
      components: [],
    },
    endorsementAcquisition: {
      heroLine: "Endorsements are validators — measure activation, not vanity.",
      requested: 0,
      meetingsScheduled: 0,
      presentationsGiven: 0,
      endorsed: 0,
      pending: 0,
      declined: 0,
      activated: 0,
      volunteerLeadsGenerated: 0,
      donorLeadsGenerated: 0,
      institutional: { labor: 0, teacher: 0, civilRights: 0, total: 0 },
      currentOfficialsEndorsed: 0,
      formerOfficialsEndorsed: 0,
      communityLeadersEndorsed: 0,
      candidatePartnerships: 0,
      byTier: { tier1: 0, tier2: 0, tier3: 0, tier4: 0, tier5: 0 },
      valueCriteria: [],
      activationChecklist: [],
      pendingTargets: [],
      components: [],
    },
    voterContact: {
      heroLine: "Human Contact Index — direct Arkansans reached by the campaign.",
      doctrine: "Volunteer → Voter Contact → Commitment → Turnout.",
      humanContactIndex: {
        total: 0,
        goal: 0,
        completionPct: 0,
        components: {
          phoneCalls: 0,
          postcards: 0,
          doorsKnocked: 0,
          housePartyAttendees: 0,
          powerOf5Conversations: 0,
          volunteerRecruits: 0,
          eventAttendees: 0,
        },
      },
      tracks: {
        lane2Reactivation: { contacted: 0, engaged: 0, committed: 0, turnoutTarget: 0, completionPct: 0 },
        lane3Registration: {
          registrationsStarted: 0,
          registrationsCompleted: 0,
          registrationEvents: 0,
          volunteerRegistrars: 0,
          goal: 0,
          completionPct: 0,
        },
        lane4Persuasion: { conversations: 0, followUps: 0, eventAttendance: 0, endorsementsGenerated: 0 },
      },
      funnel: { volunteersActive: 0, voterContacts: 0, commitments: 0, turnoutTargets: 0 },
      channels: [],
      components: [],
    },
    candidateDashboard: {
      weeksRemaining: 0,
      projectedVotes: 0,
      lane2Potential: 0,
      registrationGoal: 0,
      countiesCovered: 0,
      countiesTotal: 75,
      upcomingStops: 0,
      volunteerLeadersGoal: 0,
      volunteerLeadersCurrent: 0,
      sherwoodGoal: "—",
      sherwoodVipSold: 0,
      sherwoodVipGoal: 0,
      topPrioritiesThisWeek: ["Run npm run election-plan:build"],
      currentWeek: 1,
      weekRange: "2026-06-15 → 2026-06-21",
    },
    weekPlans: [],
    eventApprovals: {
      approvalWeekStart: "2026-06-15",
      approvalWeekEnd: "2026-06-21",
      electionDay: "2026-11-03",
      explanation: "Run npm run election-plan:build to load event approval queue.",
      weekCalendar: [],
      items: [],
      pendingItems: [],
      pendingCount: 0,
      verifiedCount: 0,
      declinedCount: 0,
      decidedCount: 0,
      throughElectionCount: 0,
    },
    warRoom: {
      weeksRemaining: 0,
      currentWeek: 0,
      weekRange: "—",
      projectedVotes: 0,
      lane2Potential: 0,
      registrationGoal: 0,
      registrationProgress: 0,
      endorsementsRequested: 0,
      endorsementsEndorsed: 0,
      endorsementsGoal: 0,
      fundraisingRaised: 0,
      fundraisingGoal: 0,
      fundraisingNote: "Run npm run election-plan:build",
      volunteerLeadersGoal: 0,
      volunteerLeadersCurrent: 0,
      volunteerLeaders: [],
      upcomingEvents: 0,
      countiesCovered: 0,
      countiesTotal: 75,
      hciTotal: 0,
      hciGoal: 0,
      hciCompletionPct: 0,
      calendarTruthVerified: 0,
      calendarTruthPending: 0,
      calendarTruthGoal: 0,
      calendarTruthPct: 0,
      phase9Ready: false,
      sherwoodGoal: "—",
      sherwoodHostsCurrent: 0,
      sherwoodHostsGoal: 0,
      sherwoodHostDonation: 0,
      sherwoodVipSold: 0,
      sherwoodVipGoal: 0,
      sherwoodTicketsSold: 0,
      sherwoodVolunteers: 0,
      sherwoodVolunteersRoster: [],
      topPrioritiesThisWeek: ["Run npm run election-plan:build"],
    },
    campaignTimeline: [],
    coverageReality: {
      disclaimer:
        "Leadership-confirmed coverage includes counties with uncertain exact visit dates. Use this as strategic coverage reality, not a verified calendar log.",
      referenceDate: new Date().toISOString().slice(0, 10),
      doctrine: "Run npm run campaign-brain:coverage-audit:build",
      visitedCount: 43,
      neverVisitedCount: 32,
      deltaGapCount: 8,
      tier1RevisitDue: 7,
      brainPreviouslyReported: 31,
      reconciliationDelta: 12,
      visitedCounties: [],
      neverVisitedCounties: [],
      deltaGapCounties: [],
      tier1RevisitQueue: [],
      priorityQueue: [],
    },
    calendarSettlement: {
      windowStart: "2026-06-15",
      windowEnd: "2026-10-19",
      earlyVotingStart: "2026-10-20",
      lockedEventCount: 0,
      openDayCount: 0,
      protectedWorkDayCount: 0,
      projectedCountiesAfterLocked: 43,
      stillMissingCount: 32,
      stillMissingCounties: [],
      visitedBaseline: 43,
      lockedBackbone: [],
      topOpenRecommendations: [],
      tier1RevisitStatus: [],
      deltaGapCountiesOpen: [],
    },
    calendarFillPhaseA: {
      disclaimer:
        "Calendar Fill Phase A shows route choices and tradeoffs. It does not assign dates or create Kelly's final calendar.",
      datesAssigned: false,
      corridorCount: 0,
      remainingCountyCount: 25,
      openWeekendCount: 0,
      corridors: [],
      topTradeoffConflicts: [],
      septemberGaps: [],
      topWeekendTradeoffs: [],
      septemberGate: [],
    },
    calendarFillPhaseB: {
      disclaimer: "Proposed — leadership approval required. Not Kelly's final calendar.",
      status: "not_built",
      strategyLabel: "Option C — Balanced Delta + Tier 1 reinforcement",
      leadershipApprovalRequired: true,
      proposedBlockCount: 0,
      proposedTotalAfterFill: 50,
      stillMissingAfterFill: 25,
      deltaCountiesScheduled: 0,
      proposedBlocks: [],
      tier1RevisitsProposed: [],
    },
    calendarFillPhaseC: {
      disclaimer:
        "Operational Lock Review (Phase C). Not Kelly's final calendar. Leadership sign-off required.",
      status: "not_built",
      strategyLabel: "Option C — Balanced Delta + Tier 1 reinforcement",
      leadershipSignOffRequired: true,
      conditionalBlocksResolved: 0,
      protectedBlocks: 0,
      mustHitCountyCount: 0,
      bonusCountyCount: 0,
      leadershipDecisionsPending: 4,
      pathwayMustHit: "50 locked + 0 must-hit",
      pathwayFull: "50 locked + 25 fill = 75/75 if all bonus executed",
      refinedBlocks: [],
      timeAudits: [],
    },
    executiveBookV1: {
      version: "1.0",
      status: "not_built",
      laborDayDeadline: "2026-09-07",
      unassignedOwners: 11,
      weeklyScorecard: [],
      campaignBudget: {
        disclaimer:
          "Planning targets only — not guaranteed costs or fundraising outcomes.",
        salaryFloor: 72000,
        salaryMonthly: 12000,
        workingCampaignTarget: 232053,
        monthlyBurnWorking: 38676,
        bareMinimumTotal: 181783,
        aggressiveStatewideTotal: 339123,
        workingCampaignRangeLow: 225000,
        workingCampaignRangeHigh: 250000,
        fieldStrategyTotal: 43500,
        digitalProgramTotal: 42000,
        travelConservative: 31533,
        travelAggressive: 46783,
        materialsMid: 13500,
        postcardMid: 27840,
        sherwoodNetMid: 11500,
        chapterHref: "/election-plan/executive-book/budget",
      },
    },
    executiveCalendar: {
      disclaimer:
        "Internal leadership calendar. Run npm run campaign-brain:executive-calendar:build to generate.",
      referenceDate: "2026-06-15",
      summary: {
        pastVisitCount: 0,
        lockedCount: 0,
        scheduledCount: 0,
        proposedCount: 0,
        totalEntries: 0,
        countiesVisited: 0,
        countiesScheduled: 0,
      },
      entries: [],
    },
    executiveBookHub: {
      version: "1.1",
      edition: "1.1",
      status: "not_built",
      laborDayDeadline: "2026-09-07",
      completenessEstimate: "—",
      readOrderNote: "",
      companionPillars: [],
      pillars: [],
      chapters: [],
    },
  };
}

export function loadElectionPlanSnapshot(): ElectionPlanWorkbenchSnapshot {
  try {
    return loadElectionPlanSnapshotFromDisk();
  } catch {
    return fallbackElectionPlanSnapshot();
  }
}

/** @deprecated Use loadElectionPlanSnapshot */
export const loadElectionPlanWorkbench = loadElectionPlanSnapshot;
