import type { DashboardBlockId } from "@/lib/agents/dashboard-builder/dashboard-component-registry";
import type { TrainingModule } from "./training-types";

/** Initial Kelly OS training catalog (V1 data). */
export const TRAINING_MODULES_DATA: TrainingModule[] = [
  mod("tr-os-navigation-101", "Navigate the Campaign OS", "campaign_os", ["new_admin", "intern", "campaign_manager"], "intro", 20, "/admin/ai-command-center", ["Know admin home", "Use Ctrl+K palette"], ["Open command center", "Run palette search"], "Visited 3 core routes", [], ["command_palette"]),
  mod("tr-ai-command-center-101", "AI command center tour", "ai_command_center", ["new_admin", "operator", "campaign_manager"], "intro", 15, "/admin/ai-command-center", ["Read summary panels", "Collapse advanced sections"], ["Open each Kelly panel once"], "All panels viewed", ["tr-os-navigation-101"], ["ai_next_actions"]),
  mod("tr-safety-gates-101", "Human gates & do-not-touch", "campaign_basics", ["new_admin", "intern", "volunteer"], "intro", 10, "/admin/training", ["List gated actions"], ["Review copilot do-not-touch"], "Quiz checklist complete", [], []),
  mod("tr-dashboard-builder-101", "Dashboard builder basics", "dashboard_builder", ["campaign_manager", "operator", "treasurer"], "core", 25, "/admin/ai-command-center/dashboard-builder", ["Build a blueprint", "Save locally"], ["Build treasurer blueprint"], "Blueprint saved", ["tr-os-navigation-101"], ["executive_summary"]),
  mod("tr-onboarding-users-101", "Onboard a new helper", "onboarding_users", ["campaign_manager", "volunteer_coordinator", "operator"], "core", 20, "/admin/onboarding", ["Run wizard", "Assign training path"], ["Complete wizard for test role"], "Wizard output reviewed", ["tr-os-navigation-101"], ["onboarding_checklist"]),
  mod("tr-candidate-approvals-101", "Candidate approvals 101", "candidate_approvals", ["candidate"], "intro", 20, "/admin/candidate-dashboard", ["Approval queue", "Hold vs deny"], ["Review one package read-only"], "Understand queue", [], ["approval_queue"]),
  mod("tr-calendar-truth-101", "Calendar truth for candidates", "candidate_approvals", ["candidate"], "intro", 15, "/admin/campaign-calendar/timeline", ["Timeline vs GCal"], ["Compare one week"], "No mystery events", ["tr-candidate-approvals-101"], ["upcoming_events"]),
  mod("tr-reimbursement-candidate-101", "Candidate reimbursement view", "travel_reimbursement", ["candidate"], "intro", 15, "/admin/campaign-events/reimbursement", ["Totals only", "No line edits"], ["Open reimbursement month"], "Totals match briefing", [], ["travel_reimbursement_summary"]),
  mod("tr-workbench-101", "Events workbench", "event_planning", ["campaign_manager", "event_planner"], "core", 30, "/admin/campaign-events/workbench", ["Triage cards", "Fact card edits"], ["Open 3 events"], "Cards understood", ["tr-os-navigation-101"], ["event_planning_checklist"]),
  mod("tr-month-review-101", "Month review wizard", "campaign_os", ["campaign_manager"], "core", 35, "/admin/campaign-events/review", ["Chronological mode", "Blockers"], ["Walk one month"], "Blocker list exported", ["tr-workbench-101"], ["approval_queue"]),
  mod("tr-calendar-sync-101", "Calendar sync health", "campaign_os", ["campaign_manager"], "core", 20, "/admin/campaign-events/calendar-sync", ["Stale detection", "Promotion gates"], ["Read sync panel"], "Know when to escalate", ["tr-month-review-101"], ["calendar_sync_health"]),
  mod("tr-reimbursement-treasurer-101", "Treasurer reimbursement", "travel_reimbursement", ["treasurer", "finance_helper"], "core", 40, "/admin/campaign-events/reimbursement", ["Packet structure", "Print gates"], ["Review April sample"], "Blockers documented", [], ["travel_reimbursement_summary", "finance_readiness"]),
  mod("tr-mileage-101", "Missing mileage workflow", "travel_reimbursement", ["treasurer", "finance_helper", "intern"], "core", 25, "/admin/campaign-events/reimbursement", ["Mileage gaps", "Exceptions"], ["Clear one gap flag"], "Gap queue understood", ["tr-reimbursement-treasurer-101"], ["missing_mileage"]),
  mod("tr-finance-readiness-101", "Finance readiness score", "finance_receipts", ["treasurer", "campaign_manager"], "core", 20, "/admin/campaign-events/reimbursement", ["Readiness panel", "Handoff"], ["Read readiness for month"], "Score explained to CM", ["tr-reimbursement-treasurer-101"], ["finance_readiness"]),
  mod("tr-receipt-basics-101", "Receipt upload basics", "finance_receipts", ["intern", "finance_helper"], "intro", 20, "/admin/campaign-events/reimbursement", ["Metadata only", "No PII in chat"], ["Stage one receipt"], "Supervisor sign-off", [], ["receipt_gaps"]),
  mod("tr-receipt-upload-101", "Intern receipt assist", "finance_receipts", ["intern"], "intro", 25, "/admin/campaign-events/reimbursement", ["Upload flow", "Flag gaps"], ["Upload test receipt"], "Treasurer notified", ["tr-receipt-basics-101"], ["receipt_gaps"]),
  mod("tr-compliance-intro-101", "Compliance intro", "compliance", ["treasurer", "finance_helper", "operator"], "intro", 30, "/admin/compliance", ["Read-only first", "Counsel handoff"], ["Open compliance home"], "Know escalation", [], []),
  mod("tr-event-planning-101", "Event planning foundations", "event_planning", ["event_planner", "campaign_manager"], "core", 35, "/admin/campaign-events/workbench", ["Planning workbook", "Readiness"], ["Complete one section"], "Readiness improved", ["tr-workbench-101"], ["event_planning_checklist"]),
  mod("tr-run-of-show-101", "Run of show", "event_planning", ["event_planner", "volunteer"], "core", 20, "/admin/campaign-events/workbench", ["Timeline", "Roles"], ["Draft run of show"], "Supervisor approved", ["tr-event-planning-101"], ["upcoming_events"]),
  mod("tr-host-support-101", "Host support", "host_support", ["host", "event_planner", "communications_lead"], "core", 25, "/admin/communications", ["Host intake", "Follow-up drafts"], ["Draft follow-up"], "No send clicked", [], ["host_follow_up"]),
  mod("tr-host-basics-101", "Host basics", "host_support", ["host"], "intro", 15, "/get-involved", ["Intake form", "Expectations"], ["Read host FAQ"], "Intake complete", [], ["host_follow_up"]),
  mod("tr-intake-bridge-101", "Intake → workbench bridge", "host_support", ["host", "campaign_manager"], "core", 20, "/admin/campaign-events/intake", ["WorkflowIntake", "Conflict flags"], ["Trace one intake"], "Path understood", ["tr-host-basics-101"], []),
  mod("tr-volunteer-mgmt-101", "Volunteer management", "volunteer_management", ["volunteer_coordinator"], "core", 30, "/admin/volunteers", ["Profiles", "Assignments"], ["Match one volunteer"], "Assignment recommended", [], ["volunteer_needs"]),
  mod("tr-event-volunteer-planning-101", "Event volunteer planning", "volunteer_management", ["volunteer_coordinator", "event_planner"], "core", 25, "/admin/volunteers", ["Slots", "No-shows"], ["Fill one event"], "Slots documented", ["tr-volunteer-mgmt-101"], ["volunteer_needs"]),
  mod("tr-volunteer-basics-101", "Volunteer basics", "volunteer_management", ["volunteer"], "intro", 15, "/admin/training", ["Check-in", "Safety"], ["Read code of conduct"], "Training signed", [], ["role_training"]),
  mod("tr-check-in-101", "Event check-in", "volunteer_management", ["volunteer"], "intro", 10, "/volunteer/resources", ["Check-in flow"], ["Practice check-in"], "Coordinator confirmed", ["tr-volunteer-basics-101"], []),
  mod("tr-photo-metadata-101", "Photo metadata only", "data_privacy", ["volunteer", "social_media_lead"], "intro", 15, "/admin/campaign-events/media-approval", ["No faces without consent", "Metadata"], ["Upload test metadata"], "Privacy checklist", [], ["hot_wash_queue"]),
  mod("tr-intern-basics-101", "Intern orientation", "campaign_basics", ["intern"], "intro", 20, "/admin/onboarding", ["Supervisor", "Tasks"], ["Meet supervisor"], "First tasks assigned", [], ["onboarding_checklist"]),
  mod("tr-event-detail-draft-101", "Event detail drafts", "event_planning", ["intern"], "intro", 25, "/admin/campaign-events/workbench", ["Draft only", "Save"], ["Draft one field"], "CM reviewed", ["tr-intern-basics-101"], []),
  mod("tr-county-dashboard-101", "County dashboard", "county_intelligence", ["county_lead", "field_manager"], "core", 25, "/admin/counties", ["County bridge", "Priorities"], ["Open home county"], "Priorities listed", [], ["county_memory"]),
  mod("tr-county-lead-101", "County lead role", "county_intelligence", ["county_lead"], "intro", 20, "/admin/counties", ["Local events", "Contacts"], ["Add one note"], "CM synced", ["tr-county-dashboard-101"], ["county_memory"]),
  mod("tr-power-of-five-101", "Power of 5", "power_of_five", ["field_manager", "county_lead"], "core", 25, "/admin/county-intelligence", ["PO5 tracking", "Gaps"], ["Review PO5 panel"], "Gap tool ticket optional", ["tr-county-dashboard-101"], []),
  mod("tr-hot-wash-county-101", "County hot wash", "hot_wash", ["field_manager", "campaign_manager"], "core", 20, "/admin/campaign-events/media-approval", ["Post-event learning", "Memory"], ["File one hot wash"], "Memory updated", [], ["hot_wash_queue"]),
  mod("tr-hot-wash-101", "Hot wash fundamentals", "hot_wash", ["campaign_manager", "social_media_lead"], "intro", 15, "/admin/campaign-events/media-approval", ["Capture lessons", "Media picks"], ["Read hot wash queue"], "One entry drafted", [], ["hot_wash_queue"]),
  mod("tr-field-organizing-101", "Field organizing", "field_organizing", ["field_manager"], "core", 30, "/admin/county-intelligence", ["Field notes", "Priorities"], ["Log field note"], "County lead notified", ["tr-county-dashboard-101"], ["volunteer_needs"]),
  mod("tr-comms-center-101", "Communications center", "communications", ["communications_lead"], "core", 30, "/admin/communications", ["Draft lanes", "Queues"], ["Open comms center"], "Lanes mapped", [], ["host_follow_up"]),
  mod("tr-email-safety-101", "Email audience safety", "communications", ["communications_lead", "operator"], "advanced", 25, "/admin/workbench/email-command-center", ["Send gates", "Preview"], ["Verify gate off"], "Zero test sends", ["tr-comms-center-101"], []),
  mod("tr-host-comms-101", "Host communications", "communications", ["communications_lead", "host"], "core", 20, "/admin/communications", ["Templates", "Draft"], ["Draft host email"], "Human send only", ["tr-host-support-101"], []),
  mod("tr-social-basics-101", "Social media basics", "social_media", ["social_media_lead"], "intro", 20, "/admin/workbench/social", ["Draft only", "Approval"], ["Create draft"], "CM approval path", [], []),
  mod("tr-owned-media-101", "Owned media library", "social_media", ["social_media_lead"], "core", 25, "/admin/owned-media", ["Assets", "Rights"], ["Tag one asset"], "Rights noted", ["tr-social-basics-101"], []),
  mod("tr-data-privacy-101", "Data privacy", "data_privacy", ["volunteer_coordinator", "intern", "new_admin"], "intro", 15, "/admin/training", ["PII rules", "Exports"], ["Read privacy checklist"], "No export attempted", [], []),
  mod("tr-operator-command-101", "Operator command discipline", "ai_command_center", ["operator"], "advanced", 30, "/admin/ai-command-center", ["OS control", "Tool queue"], ["Review tool queue"], "Tickets triaged", ["tr-ai-command-center-101"], ["command_palette"]),
  mod("tr-tool-builder-101", "Tool builder queue", "ai_command_center", ["operator", "campaign_manager"], "advanced", 25, "/admin/ai-command-center/tool-builder", ["Specs not code", "Risk"], ["Accept one ticket"], "Reviewer notes added", ["tr-operator-command-101"], []),
  mod("tr-promotion-readiness-101", "Promotion readiness", "campaign_os", ["campaign_manager"], "advanced", 20, "/admin/campaign-events/calendar-sync", ["GCal gates", "Human promote"], ["Read promotion panel"], "Know gate env vars", ["tr-calendar-sync-101"], ["promotion_readiness"]),
  mod("tr-campaign-basics-101", "Kelly campaign basics", "campaign_basics", ["new_admin", "intern", "volunteer"], "intro", 15, "/admin/training", ["Mission", "Roles"], ["Read mission doc"], "Can name 3 roles", [], []),
  mod("tr-volunteer-power-user-201", "Volunteer outreach helper", "volunteer_management", ["volunteer"], "core", 25, "/admin/training", ["Outreach scripts", "Supervisor"], ["Shadow outreach"], "Coordinator approved", ["tr-volunteer-basics-101", "tr-check-in-101"], ["volunteer_needs"]),
  mod("tr-cm-ops-dashboard-201", "CM ops dashboard power", "campaign_os", ["campaign_manager"], "advanced", 30, "/admin/campaign-manager-dashboard", ["Executive summary", "Next actions"], ["Customize blueprint"], "Blueprint pinned", ["tr-month-review-101", "tr-dashboard-builder-101"], ["executive_summary", "ai_next_actions"]),
  mod("tr-treasurer-close-201", "Month close with treasurer", "travel_reimbursement", ["treasurer"], "advanced", 45, "/admin/campaign-events/reimbursement", ["Print packet", "Exceptions"], ["Walk close checklist"], "CM sign-off", ["tr-finance-readiness-101"], ["print_download_actions"]),
];

function mod(
  id: string,
  title: string,
  category: TrainingModule["category"],
  roleTargets: TrainingModule["roleTargets"],
  level: TrainingModule["level"],
  minutes: number,
  linkedRoute: string,
  objectives: string[],
  checklist: string[],
  handsOn: string,
  completion: string | string[],
  prereqs: string[],
  unlocks: DashboardBlockId[] = [],
  unlocksModules: string[] = [],
): TrainingModule {
  const completionCriteria = Array.isArray(completion) ? completion : [completion];
  return {
    id,
    title,
    category,
    roleTargets,
    level,
    estimatedMinutes: minutes,
    description: `${title} — Kelly SOS guided module.`,
    learningObjectives: objectives,
    checklist,
    handsOnTask: handsOn,
    completionCriteria,
    prerequisiteModuleIds: prereqs,
    unlocksModuleIds: unlocksModules,
    unlocksDashboardModules: unlocks,
    humanSupervisorRequired: level === "intro" && roleTargets.includes("intern"),
    safetyNotes: ["No autonomous email, calendar write, or finance post."],
    linkedRoute,
    linkedToolIds: ["training-path-builder", "ai-tutor-router"],
  };
}
