#!/usr/bin/env python3
from pathlib import Path
import re, hashlib, json

ROOT = Path(__file__).resolve().parents[1]
MAN = ROOT / 'manuscript'
BASE = MAN / 'BOOK-ONE-READER-MATERIALIZED-v0.3.md'
OUT = MAN / 'BOOK-ONE-READER-MATERIALIZED-v0.4.md'
REPORT = MAN / 'PASS-18I-E-FINAL-SURGICAL-COMPRESSION-REPORT.json'

text = BASE.read_text(encoding='utf-8')
original = text

# PASS 18I-E is deliberately narrow. Chapters 1–8 are byte-preserved.
ch9 = text.index('## Chapter 9 — The Anticipation')
notes = text.index('\n# NOTES\n')
prefix, late, back = text[:ch9], text[ch9:notes], text[notes:]

repls = {
"Now we can return to the forest.\n\n## The Forest Before the Drought\n\nImagine a forest entering a period that historically preceded severe drought. Several measured variables begin changing before the most damaging conditions arrive. Seen from above and across time, the forest appears to be reorganizing early. This is a composite hypothetical experiment, not a claim that one established forest dataset has already demonstrated the sequence described here.":
"Now return to the forest we have been testing and give its history a new burden.\n\n## The Forest Before the Drought\n\nAfter years of measurement, several variables begin changing before a period that historically preceded severe drought. Seen across space and time, the same candidate forest appears to reorganize before the most damaging conditions arrive. The experiment remains composite and hypothetical; the continuity belongs to our investigation, not to a claim that one real forest dataset has already demonstrated this sequence.",

"The experimental logic is simple enough to remember.\n\nFirst, establish what normally predicts what.\n\nSecond, break or shift the relationship.\n\nThird, ask what the system follows—and whether it updates.\n\nA clock model may follow phase. A cue-response model may follow the immediate cue. A lower-level mechanistic model must be allowed interactions among components, nonlinear dynamics, spatial coupling, environmental forcing, and relevant history; it cannot be crippled into a simple sum merely so the higher-level model can win. A flexible statistical rival may also predict behavior from allowed present and past variables without positing a distinct higher-level forecast state.\n\nThe stronger model does not get weaker opponents. Fair Rival Resource still applies: competing models receive comparable data quality, relevant causal variables, model capacity, tuning opportunity, and held-out validation.\n\nThe candidate higher-level state must also be protected from hindsight. Discover the variable and boundary in one dataset or regime, freeze their definitions, and test them prospectively in held-out times, sites, or altered temporal regimes. Failed candidate states and null results belong in the record. A composite variable invented after seeing the outcome is a discovery tool, not confirmation.":
"The experimental logic is simple: establish what normally predicts what, break or shift that relationship, then ask what the system follows and whether it updates. A clock may follow phase; a cue-response system may follow the immediate cue; a rich lower-level model may reproduce the pattern through interactions, history, spatial coupling, and environmental forcing. Those rivals receive the same fair treatment established earlier. The candidate higher-level state and boundary must also be fixed before confirmation and survive genuinely new times, sites, or altered temporal regimes; a variable invented after the outcome remains discovery, not confirmation.",

"This is project synthesis, not a standard field equation. `PA_anticipation > 0` establishes predictive utility under that comparison. It does not establish individuality, agency, consciousness, subjective expectation, foresight, representation in every philosophical sense, or ontological independence. Intervention evidence must be assessed separately.\n\nThe canonical outcomes remain available. Lower-level sufficiency is a legitimate result. A higher-level future-sensitive variable may earn Model B by improving scientific work without earning a stronger property claim. A property-specific Model C result for anticipation would require the independently specified property to survive boundary competition, strong lower-level interaction models, changed cue relations, causal testing, prospective confirmation, and replication.\n\nAnd Model B is still a discovery, not a consolation prize.":
"This is project synthesis, not a standard field equation. `PA_anticipation > 0` earns predictive utility for this comparison, not individuality, agency, consciousness, or foresight. Lower-level sufficiency remains a legitimate result; higher-level predictive utility can matter without establishing anticipation ownership; and the stronger property-specific result must survive the changed cue relations, causal tests, boundary competition, prospective confirmation, and replication already demanded by the experiment. Model B remains a discovery rather than a consolation prize.",

"Return to our hypothetical forest.\n\nA severe disturbance pushes it away from a familiar regime.":
"Return to the forest, now carrying the history of the drought experiment forward. A severe disturbance pushes it away from a familiar regime.",

"The target is chosen prospectively. H and B receive fair informational and statistical resources. Evaluation occurs in held-out or genuinely new conditions, with uncertainty and calibration visible.\n\nA higher-level reproduction model must predict something the best reconstruction model does not. Positive Prediction Advantage shows that H adds predictive value; it does not by itself certify reproduction.\n\nThe stronger property claim still requires independent individuation, causal lineage, fair rival comparison, and the strongest evidence routes available. Intervention is especially valuable where feasible, but historical lineage evidence, provenance, natural experiments, and convergent triangulation can carry more weight where manipulation is impossible.":
"The established Prediction Advantage discipline applies. H must predict something the best reconstruction model does not, but positive advantage alone cannot certify reproduction. The stronger claim still requires independently justified parent and offspring units and causal lineage, using intervention where feasible and provenance, natural experiments, historical evidence, or convergent triangulation where it is not.",

"Suppose the forest loses.\n\nModel A may explain the important results through component reproduction, dispersal, environmental filtering, ecological inheritance, and local history. No forest-level reproduction is required. That is a scientific result.\n\nModel B may show that forest-level organization improves prediction or intervention while evidence remains insufficient to call P and O parent and offspring at that level. That is also a scientific result.\n\n**MODEL B IS A DISCOVERY, NOT A CONSOLATION PRIZE.**\n\nModel C requires the stronger property-specific result: P and O qualify as relevant units under an explicit framework, a causal generative lineage connects them, and the higher-level account survives the best fair rivals through evidence appropriate to the system.":
"Suppose the forest loses. Component reproduction, dispersal, environmental filtering, ecological inheritance, and local history may explain the result without forest-level reproduction: Model A. Forest-level organization may improve prediction or intervention while parent–offspring status remains unearned: Model B. **MODEL B IS A DISCOVERY, NOT A CONSOLATION PRIZE.** Model C requires the stronger property-specific result: P and O qualify as relevant units under an explicit framework, a causal generative lineage connects them, and the higher-level account survives the best fair rivals through evidence appropriate to the system.",

"The parent and offspring units must already be independently justified. D must be prospectively specified. Lineage must be established without using D itself as the proof. Plausible causal pathways and rivals must be identified. Where informative and feasible, descendant states should be measured before and after strong filtering.\n\nThen make the higher level compete.":
"The parent and offspring units must already be independently justified, D specified before the outcome, and lineage established without using D itself as proof. Then make the higher level compete.",

"The established Prediction Advantage discipline still applies: prospective target, fair rival resources, genuinely new evaluation, and visible uncertainty.\n\nIf H does not outperform B, higher-level Prediction Advantage has not been demonstrated. If H does outperform B, the result is evidence that the higher-level variable is doing scientific work—not a definition of heredity by equation. We still need the lineage, the level, a defensible causal architecture or set of pathways, and the strongest replication or triangulation the system permits.":
"The established Prediction Advantage discipline applies. If H wins, the higher-level variable is doing scientific work; the equation does not define heredity. Lineage, level, causal architecture, and the strongest replication or triangulation the system permits remain independent burdens.",

"Suppose the forest loses again.\n\nModel A says descendant differences are adequately explained by component inheritance, present environment, ecological inheritance, developmental reconstruction, ecological/developmental filtering, or lower-level differential survival and reproduction. No forest-level inherited property is needed.\n\nThat is an answer.\n\nModel B says a higher-level lineage variable improves prospective prediction or explanation of descendant organization, but the evidence remains insufficient to establish inheritance owned by the proposed whole.\n\nModel B remains a discovery rather than a consolation prize.\n\nPerhaps knowing which prior forest organized the source community improves forecasts even after component ancestry and site variables are included. Perhaps a network-level historical variable compresses many lower-level interactions into a useful predictor. That would matter even if we never call the property hereditary at the forest level.\n\nModel C requires more. Under an explicit framework, independently justified parent and offspring units must show prospective lineage-dependent continuity in an independently justified D that survives the strongest fair component, environmental, reconstructive, filtering, and classification rivals, followed by appropriate replication or triangulation.":
"Suppose the forest loses again. Component inheritance, present or inherited environment, reconstruction, filtering, or lower-level survival and reproduction may explain descendant differences without a forest-level inherited property: Model A. A higher-level lineage variable may still improve prediction or explanation without establishing inheritance owned by the whole: Model B, still a discovery. Model C requires independently justified parent and offspring units plus prospective lineage-dependent continuity in D that survives the strongest component, environmental, reconstructive, filtering, and classification rivals and appropriate replication or triangulation.",

"The test inherits earlier requirements: higher-level individuals and lineages must already be justified; D must have survived the heredity problem; the success currency must be fixed prospectively; component success and composition should be measured where possible; environment, assortment, mixing, drift, and plausible alternative boundaries must remain live rivals; and the causal property cannot be selected after outcome inspection.\n\nThen make the models compete.\n\nLet H be the higher-level selection model and B the strongest fair lower-level or contextual rival.":
"The test inherits the earlier gates: individuals and lineages are already justified, D has survived heredity, the success currency is fixed before the outcome, and component, environmental, assortment, mixing, drift, boundary, and post-hoc rivals remain live. Let H be the higher-level selection model and B the strongest fair lower-level or contextual rival.",

"The established Prediction Advantage discipline applies. Positive PA means higher-level variables improve prediction on that task; it does not prove causal ownership. A stable proxy for environment, composition, or linked property E can also predict. Stronger evidence asks whether intervention, natural experiment, mechanistic constraint, counterfactual variation, temporal ordering, or converging analyses support the expectation that changing D—or changing the causal architecture represented by D—changes higher-level reproductive success under the specified conditions.\n\nNo single method is mandatory in every system. The causal claim simply has to become stronger than the covariance that first suggested it.":
"The established Prediction Advantage discipline applies. Positive PA is predictive evidence, not causal ownership; environment, composition, or linked property E can also predict. The stronger claim therefore needs converging causal evidence that changing D, or the architecture D represents, changes higher-level reproductive success under the specified conditions. The causal claim must become stronger than the covariance that first suggested it.",

"Model A says component selection, assortment, environmental sorting, local competition, migration, drift, demographic structure, linked traits, or grouping adequately explains the apparent higher-level pattern. No selection owned by the higher-level whole is required.\n\nThat is an answer.\n\nModel B says higher-level organization contributes useful prospective information or causal structure to differential lineage outcomes, but the evidence remains insufficient to establish higher-level selection under the stronger property claim.\n\nModel B remains a discovery rather than a consolation prize.\n\nModel C is harder. Under an explicit multilevel or evolutionary framework, independently justified higher-level individuals possess heritable higher-level differences that, under specified conditions, causally contribute to differential higher-level reproductive success, survive the strongest fair rivals, and generalize or replicate appropriately.":
"If component selection, assortment, environment, local competition, migration, drift, demography, linked traits, or grouping explain the pattern, Model A wins. If higher-level organization adds prospective information or causal structure while higher-level selection remains unearned, Model B wins—and remains a discovery. Model C requires independently justified higher-level individuals whose heritable higher-level differences causally contribute to differential higher-level reproductive success under specified conditions, survive the strongest fair rivals, and generalize or replicate appropriately.",

"Earth contains evolution and countless lineages undergoing selection. None of that establishes selection among Earths.\n\nOne observed Earth is not a demonstrated population of planetary parent-offspring lineages. Selection among genes, organisms, colonies, species, ecosystems, or civilizations within Earth cannot silently become selection of Earth itself.\n\nPanspermia, artificial colonization, or hypothetical cosmic populations may generate interesting questions. They do not by themselves establish planetary reproduction, planetary heredity, or differential reproductive success among planetary individuals.\n\nSelection needs a defensible lineage or population structure at the level claimed. Scale cannot manufacture the missing comparison.":
"Earth contains evolution and countless selected lineages, but Chapter 15 needs something more specific: a defensible population or lineage of planetary individuals. One observed Earth does not supply it. Panspermia, artificial colonization, or hypothetical cosmic populations may motivate questions, but they do not establish planetary parent–offspring lineages, heredity, or differential planetary reproductive success. Scale cannot manufacture the missing comparison.",

"Model A is **Association Sufficiency**. Lower-level evolution, mutualism, ecology, composition, environmental filtering, and ordinary selection adequately explain the organization. No transition at the proposed level is required. That is a legitimate result.\n\nModel B is **Higher-Level Organizational Utility**. Higher-level variables improve prediction, explanation, or intervention, but the historical evidence is insufficient to establish a transition to a new evolutionary individual.\n\nModel B remains a discovery rather than a consolation prize.\n\nA system's current higher-level organization can be scientifically important even when its origin cannot be reconstructed confidently.\n\nModel C is a **Property-Specific Evolutionary Transition**. Under an explicit framework, converging evidence supports an S0→S1 historical shift in which inherited organizational changes altered specified dimensions of reproduction, heredity, conflict, dependence, selection, and lineage structure, and the derived higher-level unit gains causal or evolutionary leverage relevant to those dimensions. Model C must identify what changed and what was actually demonstrated. There is no permission to turn individuality into a hidden essence.\n\nThe models remain reversible as evidence changes. None establishes progress.":
"Association Sufficiency remains Model A: lower-level evolution, mutualism, ecology, composition, environmental filtering, and ordinary selection explain the organization without a transition at the proposed level. Model B is Higher-Level Organizational Utility: the higher level does scientific work now while the historical transition remains unearned—and that is still a discovery. Model C is the property-specific historical claim: converging evidence supports an S0→S1 shift in which inherited organizational changes altered specified dimensions of reproduction, heredity, conflict, dependence, selection, and lineage structure, while the derived higher-level unit gains relevant causal or evolutionary leverage. The models remain reversible, and none establishes progress.",

"The mind wants to draw a staircase: cell, organism, society, ecosystem, planet. Do not draw it. Every arrow would have to earn its own evidence. A society does not become an evolutionary individual because multicellular organisms emerged from cellular ancestors. An ecosystem does not become one because some colonies qualify under some organismality frameworks. Earth does not inherit individuality from the systems it contains.\n\nEarth contains major evolutionary transitions. That is not evidence that Earth itself underwent one. Planetary regulation or Gaia-style life–environment feedbacks, where empirically supported, would still not automatically establish planetary parent–offspring reproduction, heredity among planetary lineages, or selection among planets. Regulation and coupling are different questions from evolutionary individuality.[10]":
"The mind wants to draw a staircase: cell, organism, society, ecosystem, planet. Do not draw it. Every arrow must earn its own evidence; individuality at one level cannot be inherited by the level above. Earth contains major evolutionary transitions, but that is not evidence that Earth underwent one. Even empirically supported planetary regulation or Gaia-style life–environment feedbacks address regulation and coupling, not the lineage architecture required for evolutionary individuality.[10]"
}

applied=[]
for old,new in repls.items():
    if old not in late:
        raise SystemExit('Missing expected passage: '+old[:120])
    late=late.replace(old,new,1); applied.append(old[:90])

text=prefix+late+back

# Structural/scientific gates
assert text[:ch9] == original[:ch9]
assert [int(x) for x in re.findall(r'(?m)^## Chapter (\d+) — ',text)] == list(range(1,17))
assert '## Chapter 4 — The Verb' in text and '## Chapter 11 — The Choice' in text
assert 'Chapter 17' not in text
assert '**If individuality can be reorganized across levels, what determines where a new individual can—and cannot—emerge?**' in text
for sig in [
'THE FUTURE CAN BE THE TARGET OF CONTROL WITHOUT BEING THE SOURCE OF THE SIGNAL.',
'RETURN IS NOT YET A GOAL.',
'THE QUESTION IS NOT WHETHER A DECISION OCCURRED. THE QUESTION IS WHERE THE DECISION BELONGS.',
'Evidence for one kind of individuality cannot silently substitute for evidence for another.',
'RECURRENCE IS NOT REPRODUCTION.',
'HEREDITY DOES NOT REQUIRE PERFECT COPYING. IT REQUIRES LINEAGE-DEPENDENT CAUSAL CONTINUITY.',
'A PARTITION CAN LOCATE CHANGE WITHOUT SETTLING WHAT CAUSED IT.',
'EVOLUTION HAS NO UPWARD DIRECTION. LEVELS CAN CHANGE WITHOUT BECOMING A LADDER.',
'Nesting is not a ladder.'
]: assert sig in text, sig

OUT.write_text(text,encoding='utf-8')
words=lambda s:len(re.findall(r"\b[\w’'-]+\b",s))
report={
 'status':'PASS','base':BASE.name,'output':OUT.name,
 'base_sha256':hashlib.sha256(original.encode()).hexdigest(),
 'output_sha256':hashlib.sha256(text.encode()).hexdigest(),
 'base_words':words(original),'output_words':words(text),
 'additional_words_removed':words(original)-words(text),
 'additional_reduction_pct':round((words(original)-words(text))*100/words(original),3),
 'replacements_applied':len(applied),
 'chapters_1_8_byte_preserved':True,
 'gates':{'chapters_1_16':True,'no_ch17':True,'titles':True,'final_aperture':True,'protected_late_signatures':True}
}
REPORT.write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps(report,indent=2))
