import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdminPage } from "@/lib/admin/require-admin";
import { getCampaignMediaByYoutubeId } from "@/content/media/campaign-media-registry";
import { loadWorkspaceRecord } from "@/lib/media/youtube-transcripts/workspace-store";
import {
  generateAiAdvisoryAction,
  publishTranscriptAction,
  restoreTranscriptRevisionAction,
  saveTranscriptEditorAction,
  setTranscriptStatusAction,
  uploadCaptionsToYouTubeAction,
} from "@/app/admin/youtube-transcript-actions";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { AI_ADVISORY_DIR, WORKSPACE_REL } from "@/lib/media/youtube-transcripts/workspace-store";

type Props = { params: Promise<{ videoId: string }> };

export default async function AdminYouTubeTranscriptEditorPage({ params }: Props) {
  await requireAdminPage();
  const { videoId } = await params;
  const ws = loadWorkspaceRecord(videoId);
  const media = getCampaignMediaByYoutubeId(videoId);
  if (!ws && !media) notFound();

  const record = ws ?? {
    youtubeVideoId: videoId,
    title: media?.title,
    status: "NOT_REQUESTED" as const,
    source: "UNKNOWN" as const,
    language: "en-US",
    isAutoGenerated: false,
    plainText: "",
    segments: [] as { id: string; text: string; startSeconds?: number; endSeconds?: number; speaker?: string; chapter?: string }[],
    caption: {},
    flags: [],
    chapters: [],
    revisions: [],
    createdAt: "",
    updatedAt: "",
  };

  const advisoryPath = path.join(process.cwd(), WORKSPACE_REL, AI_ADVISORY_DIR, `${videoId}.json`);
  const advisory = existsSync(advisoryPath) ? JSON.parse(readFileSync(advisoryPath, "utf8")) : null;

  return (
    <div className="mx-auto max-w-5xl">
      <Link href="/admin/media/youtube" className="font-body text-sm underline">
        ← YouTube pipeline
      </Link>
      <h1 className="mt-3 font-heading text-3xl font-bold text-kelly-text">
        Transcript editor · {record.title ?? videoId}
      </h1>
      <p className="mt-2 font-body text-sm text-kelly-text/75">
        Status: <strong>{record.status}</strong> · Source: {record.source} · Language: {record.language}
      </p>
      <p className="mt-1 font-body text-xs text-kelly-muted">
        Publishing is never automatic. Approve, then publish explicitly. Caption upload to YouTube is optional and manual.
      </p>

      {media ? (
        <p className="mt-3 font-body text-sm">
          Registry:{" "}
          <Link className="underline" href={`/kelly-speaks/${media.slug}`}>
            /kelly-speaks/{media.slug}
          </Link>{" "}
          ({media.publicationStatus})
        </p>
      ) : (
        <p className="mt-3 font-body text-sm text-amber-800">
          Not in campaign media registry yet — sync metadata only. Add to registry before public publish.
        </p>
      )}

      <form action={saveTranscriptEditorAction} className="mt-8 space-y-4 rounded-card border border-kelly-text/10 bg-kelly-page p-6">
        <input type="hidden" name="youtubeVideoId" value={videoId} />
        <input type="hidden" name="segmentsJson" value={JSON.stringify(record.segments)} />
        <label className="block">
          <span className="font-body text-xs font-semibold uppercase tracking-wider text-kelly-muted">Bulk transcript</span>
          <textarea
            name="plainText"
            defaultValue={record.plainText}
            rows={18}
            className="mt-1 w-full rounded-md border border-kelly-text/15 bg-white px-3 py-2 font-body text-sm leading-relaxed"
          />
        </label>
        <button type="submit" className="rounded-md bg-kelly-text px-4 py-2 font-body text-sm font-semibold text-kelly-page">
          Save draft revision
        </button>
      </form>

      {record.flags?.length ? (
        <section className="mt-6">
          <h2 className="font-heading text-lg font-bold">Proper-noun flags (review)</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 font-body text-sm">
            {record.flags.map((f) => (
              <li key={`${f.category}-${f.term}`}>
                {f.term} · {f.category} · confidence {(f.confidence * 100).toFixed(0)}%
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <section className="mt-6 flex flex-wrap gap-3">
        <StatusForm videoId={videoId} status="REVIEW_REQUIRED" label="Mark review required" />
        <StatusForm videoId={videoId} status="APPROVED" label="Approve" />
        <StatusForm videoId={videoId} status="ARCHIVED" label="Archive" />
        <form action={publishTranscriptAction}>
          <input type="hidden" name="youtubeVideoId" value={videoId} />
          <button type="submit" className="rounded-md bg-emerald-800 px-4 py-2 font-body text-sm font-semibold text-white">
            Publish (explicit)
          </button>
        </form>
        <form action={uploadCaptionsToYouTubeAction}>
          <input type="hidden" name="youtubeVideoId" value={videoId} />
          <button type="submit" className="rounded-md border border-kelly-text/20 px-4 py-2 font-body text-sm font-semibold">
            Upload corrected captions to YouTube
          </button>
        </form>
        <form action={generateAiAdvisoryAction}>
          <input type="hidden" name="youtubeVideoId" value={videoId} />
          <button type="submit" className="rounded-md border border-kelly-text/20 px-4 py-2 font-body text-sm font-semibold">
            Generate internal AI advisory
          </button>
        </form>
      </section>

      {record.segments?.length ? (
        <section className="mt-8">
          <h2 className="font-heading text-lg font-bold">Segments / timeline</h2>
          <ol className="mt-3 space-y-3 font-body text-sm">
            {record.segments.map((seg) => (
              <li key={seg.id} className="rounded-md border border-kelly-text/10 px-3 py-2">
                <p className="text-xs text-kelly-muted">
                  {seg.startSeconds != null ? `${seg.startSeconds}s` : "—"}
                  {seg.chapter ? ` · ${seg.chapter}` : ""}
                  {seg.speaker ? ` · ${seg.speaker}` : ""}
                </p>
                <p className="mt-1">{seg.text}</p>
              </li>
            ))}
          </ol>
        </section>
      ) : null}

      <section className="mt-8">
        <h2 className="font-heading text-lg font-bold">Version history</h2>
        <ul className="mt-3 space-y-2 font-body text-sm">
          {(record.revisions ?? []).slice().reverse().map((rev) => (
            <li key={rev.revisionId} className="flex flex-wrap items-center gap-3 rounded-md border border-kelly-text/10 px-3 py-2">
              <span className="font-mono text-xs">{rev.revisionId}</span>
              <span>{rev.date}</span>
              <span>{rev.author}</span>
              <span className="text-kelly-muted">{rev.reason}</span>
              <form action={restoreTranscriptRevisionAction}>
                <input type="hidden" name="youtubeVideoId" value={videoId} />
                <input type="hidden" name="revisionId" value={rev.revisionId} />
                <button type="submit" className="underline">
                  Restore
                </button>
              </form>
            </li>
          ))}
          {!(record.revisions ?? []).length ? <li className="text-kelly-muted">No revisions yet.</li> : null}
        </ul>
      </section>

      {advisory ? (
        <section className="mt-8 rounded-card border border-amber-700/20 bg-amber-50/60 p-5">
          <h2 className="font-heading text-lg font-bold text-amber-950">Internal AI advisory (not public)</h2>
          <p className="mt-2 font-body text-sm">{advisory.summary}</p>
          {Array.isArray(advisory.keyQuotes) && advisory.keyQuotes.length ? (
            <ul className="mt-3 list-disc pl-5 font-body text-sm">
              {advisory.keyQuotes.map((q: string) => (
                <li key={q.slice(0, 40)}>{q}</li>
              ))}
            </ul>
          ) : null}
        </section>
      ) : null}
    </div>
  );
}

function StatusForm({ videoId, status, label }: { videoId: string; status: string; label: string }) {
  return (
    <form action={setTranscriptStatusAction}>
      <input type="hidden" name="youtubeVideoId" value={videoId} />
      <input type="hidden" name="status" value={status} />
      <button type="submit" className="rounded-md border border-kelly-text/20 px-4 py-2 font-body text-sm font-semibold">
        {label}
      </button>
    </form>
  );
}
