import {
  CampaignEventStatus,
  CampaignTaskOpsSourceType,
  CampaignTaskOpsVisibility,
  CampaignTaskPriority,
  CampaignTaskType,
  Prisma,
} from "@prisma/client";
import { prisma } from "@/lib/db";
import { initializeTaskPackageMetadata, writeTaskPackageMetadata } from "@/lib/campaign-ops/task-packages";

export const LAUNCH_OPERATIONS_VERSION = 1 as const;
export type OperationsWorkstream = "PROJECT_MANAGEMENT" | "COMMUNICATIONS" | "EVENT_OPERATIONS";

type TaskBlueprint = {
  key: string;
  workstream: OperationsWorkstream;
  title: string;
  objective: string;
  taskType: CampaignTaskType;
  priority: CampaignTaskPriority;
  daysBefore: number;
  blocksReadiness: boolean;
  assignedRole: string;
  instructions: string[];
  acceptanceCriteria: string[];
  dependsOn?: string[];
};

function bp(input: TaskBlueprint): TaskBlueprint { return input; }

const BLUEPRINTS: TaskBlueprint[] = [
  bp({ key: "pm.complete-event-record", workstream: "PROJECT_MANAGEMENT", title: "Complete and verify master event record", objective: "Make the event record complete enough that downstream teams can work without chasing routine details.", taskType: "ADMIN", priority: "URGENT", daysBefore: 21, blocksReadiness: true, assignedRole: "event_project_manager", instructions: ["Open the canonical event record.", "Verify date, time, venue, address, city, county, host and on-site contacts.", "Confirm Kelly's role, speaking expectations and why the campaign is attending.", "Flag missing information and assign an owner for each gap."], acceptanceCriteria: ["Core event details are verified.", "Missing information is explicitly identified and assigned.", "Downstream teams have one source of truth."] }),
  bp({ key: "pm.72-hour-verification", workstream: "PROJECT_MANAGEMENT", title: "Run 72-hour event verification", objective: "Reconfirm the event shortly before execution so stale details do not surprise the campaign.", taskType: "PREP", priority: "URGENT", daysBefore: 3, blocksReadiness: true, assignedRole: "event_project_manager", instructions: ["Contact the host or venue.", "Reconfirm time, address, parking, arrival instructions and on-site contact.", "Confirm speaking expectations and schedule changes.", "Confirm indoor/outdoor status and weather contingency.", "Update the canonical event record immediately."], acceptanceCriteria: ["Host or venue is reconfirmed.", "Arrival instructions are current.", "Changes are reflected in the event record."], dependsOn: ["pm.complete-event-record"] }),
  bp({ key: "comms.graphics", workstream: "COMMUNICATIONS", title: "Prepare event graphics package", objective: "Create the approved visual assets downstream communications channels need.", taskType: "COMMS", priority: "HIGH", daysBefore: 18, blocksReadiness: true, assignedRole: "communications_graphics", instructions: ["Use the canonical event record for all event details.", "Create the standard event graphic variants.", "Check campaign disclaimer and website treatment.", "Record final approved asset links."], acceptanceCriteria: ["Required graphic variants exist.", "Details match the event record.", "Approved asset location is recorded."], dependsOn: ["pm.complete-event-record"] }),
  bp({ key: "comms.facebook-event", workstream: "COMMUNICATIONS", title: "Create Facebook event", objective: "Give the community a shareable event destination with accurate details.", taskType: "COMMS", priority: "HIGH", daysBefore: 16, blocksReadiness: false, assignedRole: "social_media", instructions: ["Open the event record and approved graphic.", "Create the Facebook event using approved naming/copy.", "Confirm date, time, venue and campaign links.", "Record the live event URL."], acceptanceCriteria: ["Facebook event is live or ready under campaign approval rules.", "Details match the event record.", "URL is recorded."], dependsOn: ["pm.complete-event-record", "comms.graphics"] }),
  bp({ key: "comms.announcement-email", workstream: "COMMUNICATIONS", title: "Prepare event announcement email", objective: "Tell the initial qualified local audience that Kelly is coming to their community.", taskType: "COMMS", priority: "HIGH", daysBefore: 14, blocksReadiness: false, assignedRole: "email", instructions: ["Use approved event details and audience plan.", "Prepare the event-announcement template.", "Position the stop as Kelly coming to listen.", "Route through existing approval/send controls.", "Record the draft/send artifact."], acceptanceCriteria: ["Announcement is prepared for the approved audience.", "Copy uses verified event information.", "Approval/send controls are respected."], dependsOn: ["pm.complete-event-record", "comms.graphics"] }),
  bp({ key: "comms.kelly-video", workstream: "COMMUNICATIONS", title: "Produce Kelly direct-to-camera invitation", objective: "Create one authentic invitation asset that can be reused across channels.", taskType: "MEDIA", priority: "HIGH", daysBefore: 10, blocksReadiness: false, assignedRole: "content", instructions: ["Prepare short talking points covering place, purpose, date/time and invitation.", "Keep the message focused on listening to the community.", "Record the direct-to-camera video.", "Store the approved source asset and record its location."], acceptanceCriteria: ["Usable invitation video exists.", "Event details are accurate.", "Source asset is available to downstream teams."], dependsOn: ["pm.complete-event-record"] }),
  bp({ key: "comms.local-media", workstream: "COMMUNICATIONS", title: "Personally invite local media", objective: "Contact relevant local media outlets directly and invite them to Kelly's stop.", taskType: "MEDIA", priority: "HIGH", daysBefore: 9, blocksReadiness: false, assignedRole: "media_outreach", instructions: ["Open the approved local media list.", "Call every relevant outlet.", "Invite the outlet and explain Kelly is coming to listen.", "Collect/confirm the best email when possible.", "Email approved event information.", "Record a disposition and follow-up for every outlet."], acceptanceCriteria: ["Every listed outlet has a disposition.", "Available email contacts received approved information.", "Follow-ups are recorded."], dependsOn: ["pm.complete-event-record", "comms.graphics"] }),
  bp({ key: "comms.invitation-email", workstream: "COMMUNICATIONS", title: "Prepare one-week event invitation email", objective: "Send the detailed event invitation approximately one week before the stop.", taskType: "COMMS", priority: "HIGH", daysBefore: 7, blocksReadiness: false, assignedRole: "email", instructions: ["Use verified event details.", "Prepare the full invitation with date, time, venue and why Kelly wants the community there.", "Use the approved audience universe.", "Route through existing approval/send controls.", "Record the draft/send artifact."], acceptanceCriteria: ["Detailed invitation is prepared.", "Logistics match the event record.", "Approval/send controls are respected."], dependsOn: ["pm.complete-event-record", "comms.graphics"] }),
  bp({ key: "comms.power-of-five", workstream: "COMMUNICATIONS", title: "Run local Power of Five invitation push", objective: "Turn strong local supporters and local campaign helpers into personal invitation multipliers.", taskType: "VOLUNTEER", priority: "HIGH", daysBefore: 6, blocksReadiness: false, assignedRole: "relational_organizing", instructions: ["Start with the strongest available supporter universe and local team.", "Personally invite each contact to meet Kelly.", "Ask each willing person to invite five people.", "Explain that Kelly is coming to listen.", "Send the approved forwardable email/text kit.", "Record asks, commitments and kits delivered."], acceptanceCriteria: ["Power of Five asks are recorded.", "Willing participants received the forwardable kit.", "Results are available for follow-up."], dependsOn: ["pm.complete-event-record"] }),
  bp({ key: "comms.door-hangers", workstream: "COMMUNICATIONS", title: "Order and distribute 200 event door hangers", objective: "Put the standard Secretary of State explainer and event invitation into the immediate event area.", taskType: "FIELD", priority: "HIGH", daysBefore: 5, blocksReadiness: false, assignedRole: "field", instructions: ["Send verified event variables to the approved printer using the standard template.", "Approve the proof under campaign procedure.", "Confirm 200 copies.", "Assign immediate-radius distribution turf.", "Record number distributed and area covered."], acceptanceCriteria: ["200 door hangers are produced or accounted for.", "Event information is accurate.", "Distribution result is recorded."], dependsOn: ["pm.complete-event-record"] }),
  bp({ key: "comms.day-before-text", workstream: "COMMUNICATIONS", title: "Prepare day-before radius text", objective: "Remind the approved local SMS universe that Kelly will be nearby tomorrow.", taskType: "COMMS", priority: "URGENT", daysBefore: 1, blocksReadiness: false, assignedRole: "sms", instructions: ["Use the approved radius/audience universe.", "Prepare a concise invitation with verified time/location.", "Route through existing SMS consent, approval and send controls.", "Record the campaign artifact/result."], acceptanceCriteria: ["Text is prepared for the approved universe.", "Details are verified.", "Consent/send controls are respected."], dependsOn: ["pm.72-hour-verification"] }),
  bp({ key: "comms.follow-up", workstream: "COMMUNICATIONS", title: "Complete attendee communications follow-up", objective: "Thank attendees and carry the relationship forward after the event.", taskType: "FOLLOW_UP", priority: "HIGH", daysBefore: -1, blocksReadiness: false, assignedRole: "email", instructions: ["Use captured attendance/contact information under consent rules.", "Prepare the thank-you/follow-up message.", "Include an appropriate next action.", "Route through existing approval/send controls.", "Record the result."], acceptanceCriteria: ["Follow-up is prepared/completed for eligible contacts.", "Next action is clear.", "Campaign controls are respected."], dependsOn: ["ops.closeout"] }),
  bp({ key: "ops.candidate-brief", workstream: "EVENT_OPERATIONS", title: "Prepare Kelly event brief", objective: "Give Kelly a concise briefing with people, purpose, logistics and local context.", taskType: "PREP", priority: "HIGH", daysBefore: 3, blocksReadiness: true, assignedRole: "candidate_prep", instructions: ["Summarize where Kelly is going and why.", "List host/on-site contacts and people Kelly should meet.", "Record Kelly's role, speaking expectations and timing.", "Include arrival, parking and departure instructions.", "Add concise verified local/listening context."], acceptanceCriteria: ["Kelly can understand the stop from one brief.", "Logistics and contacts are current.", "No unverified claims are stated as fact."], dependsOn: ["pm.complete-event-record"] }),
  bp({ key: "ops.staffing", workstream: "EVENT_OPERATIONS", title: "Fill event volunteer roles", objective: "Make sure the stop has enough people to execute setup, welcome, candidate support, capture and breakdown.", taskType: "VOLUNTEER", priority: "HIGH", daysBefore: 5, blocksReadiness: true, assignedRole: "event_project_manager", instructions: ["Review event size/type and required roles.", "Assign or recruit setup, welcome/check-in, Kelly arrival support, contact/listening capture, photo/video and breakdown coverage.", "Combine roles for small events when practical.", "Record names, arrival times and gaps."], acceptanceCriteria: ["Required roles have owners or explicit gaps.", "Volunteers know arrival time and meeting point.", "Critical gaps are escalated."], dependsOn: ["pm.complete-event-record"] }),
  bp({ key: "ops.materials", workstream: "EVENT_OPERATIONS", title: "Prepare event materials kit", objective: "Have campaign materials packed, accounted for and ready to travel.", taskType: "PREP", priority: "HIGH", daysBefore: 2, blocksReadiness: true, assignedRole: "event_materials", instructions: ["Review the event materials checklist.", "Pack signs, literature, voter/SOS information, QR materials, shirts and setup items as applicable.", "Record quantities leaving campaign custody.", "Flag missing items immediately."], acceptanceCriteria: ["Required materials are packed or exceptions recorded.", "Quantities are documented.", "Kit is assigned to a person/vehicle."], dependsOn: ["pm.72-hour-verification"] }),
  bp({ key: "ops.setup", workstream: "EVENT_OPERATIONS", title: "Set up campaign presence", objective: "Create a professional, welcoming campaign footprint before Kelly arrives.", taskType: "PREP", priority: "URGENT", daysBefore: 0, blocksReadiness: true, assignedRole: "event_setup", instructions: ["Find the approved campaign location.", "Set up table/banner/signage and approved materials.", "Place contact/QR materials for volunteer use.", "Check the area is clean, accessible and ready.", "Record setup proof."], acceptanceCriteria: ["Campaign area is ready before Kelly arrives.", "Required materials are usable.", "Setup proof is recorded."], dependsOn: ["ops.materials", "ops.staffing"] }),
  bp({ key: "ops.kelly-arrival", workstream: "EVENT_OPERATIONS", title: "Manage Kelly arrival and handoff", objective: "Meet Kelly, get her to the right people and protect the event timeline.", taskType: "PREP", priority: "URGENT", daysBefore: 0, blocksReadiness: true, assignedRole: "candidate_handler", instructions: ["Be at the agreed meeting point before Kelly arrives.", "Know parking, entrance, host and first interaction.", "Brief Kelly on last-minute changes.", "Connect Kelly to host/key people.", "Track required departure time."], acceptanceCriteria: ["Kelly is met and handed off cleanly.", "Changes are communicated.", "Departure timing is protected."], dependsOn: ["pm.72-hour-verification", "ops.candidate-brief", "ops.staffing"] }),
  bp({ key: "ops.listening-capture", workstream: "EVENT_OPERATIONS", title: "Capture what the community tells Kelly", objective: "Turn the campaign promise to listen into structured community learning and follow-up.", taskType: "DATA", priority: "HIGH", daysBefore: 0, blocksReadiness: false, assignedRole: "listening_capture", instructions: ["Capture community issues and themes without unnecessary sensitive personal detail.", "Record useful stories/context and location.", "Flag specific follow-up Kelly or the campaign committed to.", "Submit notes against the event."], acceptanceCriteria: ["Major themes are recorded.", "Commitments/follow-ups are identifiable.", "Notes avoid unnecessary sensitive information."], dependsOn: ["ops.staffing"] }),
  bp({ key: "ops.contact-capture", workstream: "EVENT_OPERATIONS", title: "Capture event contacts and attendance", objective: "Make sure people met at the event can appropriately remain connected to the campaign.", taskType: "DATA", priority: "HIGH", daysBefore: 0, blocksReadiness: false, assignedRole: "contact_capture", instructions: ["Use the approved contact/attendance capture method.", "Collect only appropriate information and consent.", "Record attendance estimate.", "Route contacts into the existing data process."], acceptanceCriteria: ["Attendance estimate is recorded.", "Contacts enter the approved data process.", "Consent rules are respected."], dependsOn: ["ops.staffing"] }),
  bp({ key: "ops.content-capture", workstream: "EVENT_OPERATIONS", title: "Capture required event photo and video", objective: "Create usable proof of Kelly listening, engaging and showing up in the community.", taskType: "MEDIA", priority: "HIGH", daysBefore: 0, blocksReadiness: false, assignedRole: "event_content", instructions: ["Capture Kelly interacting and listening.", "Capture a wide event/environment image and local context.", "Capture Kelly with the host and speaking if applicable.", "Capture useful vertical video.", "Record context and upload assets to the approved location."], acceptanceCriteria: ["Required shot categories are represented where possible.", "Assets are uploaded/linked.", "Useful context is recorded."], dependsOn: ["ops.staffing"] }),
  bp({ key: "ops.breakdown", workstream: "EVENT_OPERATIONS", title: "Break down and account for campaign materials", objective: "Leave the venue clean, thank the host and return campaign property with exceptions documented.", taskType: "PREP", priority: "HIGH", daysBefore: 0, blocksReadiness: false, assignedRole: "event_setup", instructions: ["Collect campaign signs, literature and equipment.", "Restore/clean the campaign area.", "Thank the host or designated contact.", "Record returned quantities and missing/damaged items.", "Confirm transport back."], acceptanceCriteria: ["Campaign area is left clean.", "Host is thanked.", "Materials are accounted for."], dependsOn: ["ops.setup"] }),
  bp({ key: "ops.closeout", workstream: "EVENT_OPERATIONS", title: "Close out event operations", objective: "Return the event's results, assets, follow-ups and lessons to the campaign system.", taskType: "FOLLOW_UP", priority: "HIGH", daysBefore: -1, blocksReadiness: true, assignedRole: "event_project_manager", instructions: ["Record final attendance and volunteer participation/hours when available.", "Confirm contacts and listening notes were submitted.", "Confirm photos/video were uploaded.", "Record host/candidate follow-ups and commitments.", "Record materials exceptions, media outcomes, problems and lessons.", "Assign any critical missing outputs before closing."], acceptanceCriteria: ["Required event outputs are accounted for.", "Follow-ups have owners.", "Lessons/problems are recorded.", "The event can be reviewed without reconstructing it from memory."], dependsOn: ["ops.listening-capture", "ops.contact-capture", "ops.content-capture", "ops.breakdown"] }),
];

function dueAt(startAt: Date, daysBefore: number): Date { const due = new Date(startAt); due.setUTCDate(due.getUTCDate() - daysBefore); return due; }
function json(value: unknown): Prisma.InputJsonValue { return value as Prisma.InputJsonValue; }

export async function launchEventOperations(input: { eventId: string; actorUserId?: string | null }) {
  const event = await prisma.campaignEvent.findUnique({ where: { id: input.eventId }, select: { id: true, title: true, startAt: true, countyId: true, isTravelLeg: true, status: true } });
  if (!event) throw new Error("Event not found");
  if (event.isTravelLeg) throw new Error("Travel legs do not receive first-class event operations packages");
  if (event.status === CampaignEventStatus.CANCELLED) throw new Error("Cancelled events cannot launch operations");
  const sourceKeys = BLUEPRINTS.map((item) => `campaign-ops-v${LAUNCH_OPERATIONS_VERSION}:${item.key}`);
  const existing = await prisma.campaignTask.findMany({ where: { eventId: event.id, sourceTemplateTaskKey: { in: sourceKeys } }, select: { id: true, sourceTemplateTaskKey: true } });
  const existingByKey = new Map(existing.filter((row) => row.sourceTemplateTaskKey).map((row) => [row.sourceTemplateTaskKey as string, row.id]));
  const createdByBlueprintKey = new Map<string, string>();
  const createdTaskIds: string[] = [];
  for (const blueprint of BLUEPRINTS) {
    const sourceTemplateTaskKey = `campaign-ops-v${LAUNCH_OPERATIONS_VERSION}:${blueprint.key}`;
    if (existingByKey.has(sourceTemplateTaskKey)) continue;
    const dependencyTaskIds = (blueprint.dependsOn ?? []).flatMap((dependencyKey) => {
      const created = createdByBlueprintKey.get(dependencyKey);
      if (created) return [created];
      const existingId = existingByKey.get(`campaign-ops-v${LAUNCH_OPERATIONS_VERSION}:${dependencyKey}`);
      return existingId ? [existingId] : [];
    });
    const taskPackage = initializeTaskPackageMetadata({ objective: blueprint.objective, instructions: blueprint.instructions, acceptanceCriteria: blueprint.acceptanceCriteria, dependencyTaskIds });
    const opsMetadataJson = writeTaskPackageMetadata({ launchOperations: { version: LAUNCH_OPERATIONS_VERSION, workstream: blueprint.workstream, blueprintKey: blueprint.key, launchedAt: new Date().toISOString() } }, taskPackage);
    const task = await prisma.campaignTask.create({ data: { title: blueprint.title, description: blueprint.objective, taskType: blueprint.taskType, priority: blueprint.priority, dueAt: dueAt(event.startAt, blueprint.daysBefore), assignedRole: blueprint.assignedRole, blocksReadiness: blueprint.blocksReadiness, sourceTemplateTaskKey, countyId: event.countyId, eventId: event.id, createdByUserId: input.actorUserId ?? null, opsSourceType: CampaignTaskOpsSourceType.event_template, opsVisibility: CampaignTaskOpsVisibility.operators, opsMetadataJson: json(opsMetadataJson) }, select: { id: true } });
    createdByBlueprintKey.set(blueprint.key, task.id);
    existingByKey.set(sourceTemplateTaskKey, task.id);
    createdTaskIds.push(task.id);
  }
  const allTasks = await prisma.campaignTask.findMany({ where: { eventId: event.id, sourceTemplateTaskKey: { startsWith: `campaign-ops-v${LAUNCH_OPERATIONS_VERSION}:` } }, select: { status: true, blocksReadiness: true } });
  return { eventId: event.id, eventTitle: event.title, createdTaskIds, createdCount: createdTaskIds.length, totalOperationalTasks: allTasks.length, readinessBlockers: allTasks.filter((task) => task.blocksReadiness && task.status !== "DONE").length };
}

export async function listLaunchableEvents(take = 100) {
  const events = await prisma.campaignEvent.findMany({ where: { isTravelLeg: false, status: { not: CampaignEventStatus.CANCELLED }, startAt: { gte: new Date(Date.now() - 24 * 60 * 60 * 1000) } }, orderBy: { startAt: "asc" }, take, select: { id: true, title: true, startAt: true, city: true, locationName: true, ownerUserId: true } });
  const taskCounts = await prisma.campaignTask.groupBy({ by: ["eventId"], where: { eventId: { in: events.map((event) => event.id) }, sourceTemplateTaskKey: { startsWith: `campaign-ops-v${LAUNCH_OPERATIONS_VERSION}:` } }, _count: { _all: true } });
  const counts = new Map(taskCounts.map((row) => [row.eventId, row._count._all]));
  return events.map((event) => ({ ...event, operationsTaskCount: counts.get(event.id) ?? 0, expectedOperationsTaskCount: BLUEPRINTS.length, operationsLaunched: (counts.get(event.id) ?? 0) > 0, operationsComplete: (counts.get(event.id) ?? 0) >= BLUEPRINTS.length }));
}

export function launchOperationsBlueprintSummary() { return BLUEPRINTS.map(({ key, workstream, title, daysBefore, assignedRole, blocksReadiness }) => ({ key, workstream, title, daysBefore, assignedRole, blocksReadiness })); }
