/**
 * Operations Lock Pass — Campaign Operations Mode.
 * Converts systems into weekly human action lists. NOT calendar operational lock.
 * NOT Google Calendar. NOT /events publish.
 *
 * Usage: npm run campaign-brain:operations-lock:build
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import { BRAIN_DATA, BRAIN_ROOT, readJson } from "./lib/inputs";

const OPS_OUT = path.join(BRAIN_ROOT, "operations");
const PACKETS_OUT = path.join(OPS_OUT, "weekly-packets");
const SHERWOOD_OUT = path.join(OPS_OUT, "sherwood-60");
const OPS_DATA = path.join(BRAIN_DATA, "operations");
const TWENTY_WEEK = path.join(process.cwd(), "data/election-plan/twenty-week-plan.json");

const DISCLAIMER =
  "Campaign Operations Mode. Weekly action lists for named owners. Calendar Phase C sign-off still required before calendar operational lock. Not Kelly's final Google Calendar.";

const LABOR_DAY = "2026-09-07";

type OwnershipRow = {
  id: string;
  function: string;
  owner: string;
  backup: string;
  status: string;
  nextAction: string;
  dueDate: string;
  weeklyDeliverable: string;
};

type WeekPlan = {
  weekNumber: number;
  range: string;
  status: string;
  cluster: string;
  clusterFocus?: string;
  cities: string[];
  counties?: string[];
  focus: string;
  events?: string[];
  volunteerGoals?: string[];
  coalitionGoals?: string[];
  storytellingGoals?: string[];
  endorsementGoals?: string[];
  gotvGoals?: string[];
  metrics?: Array<{ label: string; target: number | string }>;
};

type EndorsementTarget = {
  id: string;
  organization: string;
  tier: number;
  owner: string;
  askDate: string;
  status: string;
  nextAction: string;
};

function ensureDir(p: string) {
  mkdirSync(p, { recursive: true });
}

function padWeek(n: number) {
  return `week-${String(n).padStart(2, "0")}`;
}

function bulletList(items: string[] | undefined, fallback = "- _None assigned_") {
  if (!items?.length) return fallback;
  return items.map((i) => `- ${i}`).join("\n");
}

function metricsTable(metrics: WeekPlan["metrics"]) {
  if (!metrics?.length) return "_No metrics defined._";
  return `| Metric | Target |\n|--------|--------|\n${metrics.map((m) => `| ${m.label} | ${m.target} |`).join("\n")}`;
}

function buildCandidatePacket(week: WeekPlan): string {
  return `# Candidate Packet — Week ${week.weekNumber}

> ${week.range} · ${week.cluster}

## This week's focus

${week.focus}

## Where Kelly should be

**Cities:** ${week.cities.join(" · ")}

**Counties:** ${(week.counties ?? []).join(" · ") || "—"}

## Events & stops

${bulletList(week.events)}

## Kelly's non-negotiables this week

- Attend every scheduled stop with relationship meetings booked (not drive-by only)
- Recruit volunteers at every public event
- Capture contacts → Power of 5 pipeline
- One local media touch or civic club where possible
- Review weekly packet Sunday night · confirm next week

## Success metrics

${metricsTable(week.metrics)}

---
*Generated by Operations Lock Pass · ${DISCLAIMER}*
`;
}

function buildVolunteerPacket(week: WeekPlan, peoplePower: { foundingTeamGoal?: number; foundingTeamCurrent?: number; launchCall?: { date: string; time: string } }): string {
  return `# Volunteer Packet — Week ${week.weekNumber}

> ${week.range}

## Volunteer goals

${bulletList(week.volunteerGoals)}

## Founding team status

| Metric | Value |
|--------|------:|
| Goal | ${peoplePower.foundingTeamGoal ?? 20} |
| Current | ${peoplePower.foundingTeamCurrent ?? 0} |
| Launch call | ${peoplePower.launchCall ? `${peoplePower.launchCall.date} · ${peoplePower.launchCall.time}` : "Jun 28 · 6 PM"} |

## GOTV / field goals

${bulletList(week.gotvGoals)}

## Owner actions

1. Confirm county captains for this week's cluster
2. Log Power of 5 conversations daily
3. Update Mobilize RSVPs before Monday leadership call
4. Assign shift leads for any major event this week

---
*Owner: Volunteer Leadership Launch · Operations Lock Pass*
`;
}

function buildCoalitionPacket(week: WeekPlan): string {
  return `# Coalition Packet — Week ${week.weekNumber}

> ${week.range}

## Coalition goals

${bulletList(week.coalitionGoals)}

## Conversation target

Track **meaningful coalition conversations** — not endorsements yet. Relationships before endorsements.

| Track | Owner function |
|-------|----------------|
| NAACP branches | NAACP Program |
| Labor halls | Labor Program |
| Educators | AEA Program |
| Faith leaders | Coalition & Endorsements |
| County clerks | County Completion Routing |
| Elected / former officials | Coalition & Endorsements |
| Hispanic community | Jasmine Serano |
| Muslim community | Ali Khan / Ebrahim |

## This week's coalition actions

${bulletList(week.coalitionGoals)}

---
*Owner: Coalition & Endorsements · Operations Lock Pass*
`;
}

function buildEndorsementPacket(week: WeekPlan, targets: EndorsementTarget[]): string {
  const weekTargets = week.weekNumber === 1 ? targets : [];
  const targetTable =
    weekTargets.length > 0
      ? `| Organization | Owner | Ask date | Status | Next action |\n|--------------|-------|----------|--------|-------------|\n${weekTargets.map((t) => `| ${t.organization} | ${t.owner} | ${t.askDate} | ${t.status} | ${t.nextAction} |`).join("\n")}`
      : "_See endorsement-strike-team.md for full target list._";

  return `# Endorsement Packet — Week ${week.weekNumber}

> ${week.range}

## Endorsement goals

${bulletList(week.endorsementGoals)}

## Strike targets (Week ${week.weekNumber})

${targetTable}

## Rules

- Endorsement opportunities may override **bonus-tier** county completion — not must-hit Delta or Tier 1 revisits without leadership call
- Calendar remains **15–20% flexible** for AEA, labor, NAACP, clerk, and media opportunities
- Log every ask: date · owner · status · next action

---
*Owner: Coalition & Endorsements · Operations Lock Pass*
`;
}

function buildSocialMediaPacket(week: WeekPlan): string {
  return `# Social Media / Motion Packet — Week ${week.weekNumber}

> ${week.range}

## Storytelling goals

${bulletList(week.storytellingGoals)}

## Mandatory per stop (no exceptions)

Every Kelly stop this week produces:

| Asset | Owner | Due |
|-------|-------|-----|
| 1 Reel | Social Media / Motion | Same day |
| 1 Photo Album | Social Media / Motion | Same day |
| 1 Community Story (Substack-ready) | Social Media / Motion | Within 48h |
| 1 Local Spotlight | Social Media / Motion | Within 48h |
| 1 Upcoming Stop Post | Social Media / Motion | Before next stop |

## Low-value pattern to reject

Drive in → single photo → leave with no story pipeline.

## Week ${week.weekNumber} content backlog target

${bulletList(week.storytellingGoals)}

---
*Owner: Social Media / Motion · Operations Lock Pass*
`;
}

function buildOwnershipDashboard(assignments: OwnershipRow[], generatedAt: string): string {
  const unassigned = assignments.filter((a) => {
    const o = a.owner.trim().toLowerCase();
    return !o || o === "unassigned" || o === "tbd" || o.startsWith("tbd");
  }).length;
  return `# Ownership Dashboard

> ${DISCLAIMER}

**Generated:** ${generatedAt.slice(0, 10)}

| Status | Count |
|--------|------:|
| Functions defined | ${assignments.length} |
| **Unassigned — assign before lunch** | **${unassigned}** |
| Critical path | ${assignments.filter((a) => a.status === "critical").length} |

## Assignments

| Function | Owner | Backup | Status | Next action | Due |
|----------|-------|--------|--------|-------------|-----|
${assignments.map((a) => `| ${a.function} | **${a.owner}** | ${a.backup || "—"} | ${a.status} | ${a.nextAction} | ${a.dueDate} |`).join("\n")}

## Rule

No shared ownership. No committees. **One name beside every box.**

Edit \`data/campaign-brain/operations/ownership-registry.source.json\` and re-run \`npm run campaign-brain:operations-lock:build\`.
`;
}

function buildPerfectWeekDoctrine(): string {
  return `# What Does a Perfect Week Look Like?

> One-page operational doctrine · Campaign Operations Mode

The calendar serves this philosophy — not the other way around.

---

## Every week we:

1. **Attend events** — county fairs, diners, school events, civic clubs, Democratic meetings, small businesses
2. **Recruit volunteers** — Power of 5 · county captains · founding team growth
3. **Build endorsements** — asks logged · meetings scheduled · validators identified
4. **Tell stories** — Reel · album · community story · local spotlight · upcoming stop (every stop)
5. **Capture contacts** — sign-in → Po5 → Mobilize → human contact index
6. **Schedule future visits** — relationship density over county-box checking
7. **Generate local media** — advisories · clerk intros · civic club coverage
8. **Build relationships** — NAACP · labor · AEA · clerks · faith · business validators

---

## Three jobs (Kelly's lens)

### Job 1 — Build visible momentum

People should see the campaign everywhere: fairs, diners, schools, Juneteenth, volunteer meetings, county Dem meetings, civic clubs, small businesses.

### Job 2 — Build validators

NAACP branches · AEA leaders · labor leaders · county clerks · former and current elected officials · faith leaders. These people create permission structures for voters.

### Job 3 — Build the volunteer machine

June 28 founding volunteer launch is one of the most important dates remaining. Without the network, systems remain theoretical.

---

## Coverage standard (leadership default)

| Level | Counties |
|-------|---------:|
| Locked schedule | 50 |
| Must-hit execution | 72 |
| Stretch (all bonus) | 75 |

**72 = operational requirement · 75 = stretch goal**

---

## Labor Day readiness gate

By Labor Day (${LABOR_DAY}):

- [ ] All Top 10 cities revisited
- [ ] Founding 20 volunteer leaders launched
- [ ] Sherwood event executed
- [ ] Endorsement pipeline active
- [ ] Delta proof established
- [ ] County completion path clearly visible
- [ ] 100 meaningful coalition conversations logged

---

## Calendar flexibility

Reserve **15–20%** of the schedule for:

- AEA opportunities
- Labor endorsements
- NAACP invitations
- County clerk invitations
- Media opportunities
- Candidate forums

A rigid calendar becomes a liability in the final 20 weeks.

---
*Operations Lock Pass · Not a strategy document — an execution doctrine*
`;
}

function buildSherwoodCommandCenter(sherwood: Record<string, unknown>, coalitionSherwood: Record<string, unknown>) {
  const tracking = (sherwood.tracking ?? {}) as Record<string, number | string>;
  const event = (sherwood.event ?? {}) as Record<string, unknown>;

  return {
    generatedAt: new Date().toISOString(),
    goal: sherwood.goal ?? "Win Sherwood outright with 60%+",
    eventName: (event.name as string) ?? "Sherwood GOTV Kickoff",
    status: coalitionSherwood.status ?? tracking.staffing ?? "planning",
    metrics: {
      vipTablesSold: coalitionSherwood.vipTablesSold ?? tracking.vipTablesSold ?? 0,
      vipTablesGoal: coalitionSherwood.vipTablesGoal ?? tracking.vipTablesGoal ?? 20,
      ticketsSold: coalitionSherwood.ticketsSold ?? tracking.ticketsSold ?? 0,
      volunteerSignups: tracking.volunteerSignups ?? 0,
      sponsorLeads: tracking.sponsorLeads ?? 0,
      donorConversions: tracking.donorConversions ?? 0,
    },
    tracks: {
      vipTables: { sold: coalitionSherwood.vipTablesSold ?? 0, goal: 20, owner: "Sherwood Event lead" },
      sponsors: { leads: tracking.sponsorLeads ?? 0, goal: 10, owner: "Sherwood Event lead" },
      candidatesInvited: { confirmed: 0, goal: 15, owner: "Candidate Partnerships lead" },
      laborInvited: { confirmed: 0, goal: 5, owner: "Labor Program owner" },
      naacpInvited: { confirmed: 0, goal: 3, owner: "NAACP Program owner" },
      volunteerRecruitment: { signups: tracking.volunteerSignups ?? 0, goal: 50, owner: "Volunteer Leadership Launch" },
      mediaOutreach: { advisoriesSent: 0, pickups: 0, owner: "Social Media / Motion" },
      mobilizeRegistration: { rsvps: 0, goal: 300, owner: "Mobilize Operations" },
    },
    compliance: {
      legalComplianceReview: tracking.legalComplianceReview ?? "pending",
      permits: tracking.permits ?? "pending",
      security: tracking.security ?? "pending",
      alcoholCompliance: tracking.alcoholCompliance ?? "pending",
    },
    keyDates: [
      { date: "2026-07-03", label: "Sherwood Fireworks & Food Trucks" },
      { date: "2026-07-04", label: "Pops on the River · Little Rock" },
    ],
    note: "GOTV kickoff — too important to bury. Daily metric update required.",
  };
}

function buildSherwoodMd(cmd: ReturnType<typeof buildSherwoodCommandCenter>): string {
  return `# Sherwood Command Center

> ${cmd.goal} · ${cmd.eventName}

**Status:** ${cmd.status}

## Metrics

| Track | Current | Goal | Owner |
|-------|--------:|-----:|-------|
| VIP tables sold | ${cmd.metrics.vipTablesSold} | ${cmd.metrics.vipTablesGoal} | Sherwood Event lead |
| Show tickets | ${cmd.metrics.ticketsSold} | 700+ | Sherwood Event lead |
| Volunteer signups | ${cmd.metrics.volunteerSignups} | 50 | Volunteer Leadership Launch |
| Sponsor leads | ${cmd.metrics.sponsorLeads} | 10 | Sherwood Event lead |
| Mobilize RSVPs | ${cmd.tracks.mobilizeRegistration.rsvps} | ${cmd.tracks.mobilizeRegistration.goal} | Mobilize Operations |

## Invitation tracks

| Track | Confirmed | Goal | Owner |
|-------|----------:|-----:|-------|
| Running candidates | ${cmd.tracks.candidatesInvited.confirmed} | ${cmd.tracks.candidatesInvited.goal} | Candidate Partnerships |
| Labor leaders | ${cmd.tracks.laborInvited.confirmed} | ${cmd.tracks.laborInvited.goal} | Labor Program |
| NAACP leaders | ${cmd.tracks.naacpInvited.confirmed} | ${cmd.tracks.naacpInvited.goal} | NAACP Program |

## Compliance checklist

| Item | Status |
|------|--------|
| Legal compliance review | ${cmd.compliance.legalComplianceReview} |
| Permits | ${cmd.compliance.permits} |
| Security | ${cmd.compliance.security} |
| Alcohol compliance | ${cmd.compliance.alcoholCompliance} |

## Key dates

${cmd.keyDates.map((d) => `- **${d.date}** — ${d.label}`).join("\n")}

---
*Update metrics daily · Owner: Sherwood Event lead*
`;
}

function buildCoalitionSprint() {
  const categories = [
    { id: "naacp", label: "NAACP branches", goal: 20, owner: "NAACP Program" },
    { id: "labor", label: "Labor halls / union leadership", goal: 15, owner: "Labor Program" },
    { id: "educators", label: "Educators (AEA pathway)", goal: 15, owner: "AEA Program" },
    { id: "faith", label: "Faith leaders", goal: 15, owner: "Coalition & Endorsements" },
    { id: "clerks", label: "County clerks", goal: 10, owner: "County Completion Routing" },
    { id: "current-officials", label: "Current elected officials", goal: 10, owner: "Coalition & Endorsements" },
    { id: "former-officials", label: "Former elected officials", goal: 15, owner: "Coalition & Endorsements" },
  ];
  const totalGoal = categories.reduce((s, c) => s + c.goal, 0);

  return {
    generatedAt: new Date().toISOString(),
    campaignGoal: "100 meaningful coalition conversations by Labor Day",
    deadline: LABOR_DAY,
    totalGoal,
    currentTotal: 0,
    trackConversationsNotEndorsements: true,
    categories: categories.map((c) => ({ ...c, current: 0 })),
  };
}

function buildCoalitionSprintMd(sprint: ReturnType<typeof buildCoalitionSprint>): string {
  return `# Coalition Contact Sprint

> **${sprint.campaignGoal}** · Deadline: ${sprint.deadline}

Track **conversations**, not endorsements. Relationships come before endorsements.

| Category | Goal | Current | Owner |
|----------|-----:|--------:|-------|
${sprint.categories.map((c) => `| ${c.label} | ${c.goal} | ${c.current} | ${c.owner} |`).join("\n")}
| **Total** | **${sprint.totalGoal}** | **${sprint.currentTotal}** | |

## Definition: meaningful conversation

- Scheduled meeting completed, OR
- 15+ minute relationship call with follow-up logged, OR
- In-person intro at event with contact captured

## Not counted

- Voicemail with no callback
- Email with no response
- Drive-by photo op with no meeting
`;
}

function buildMotionSchedule() {
  return {
    generatedAt: new Date().toISOString(),
    rule: "Every stop · no exceptions",
    perStopDeliverables: [
      { id: "reel", label: "1 Reel", due: "same_day", owner: "Social Media / Motion" },
      { id: "album", label: "1 Photo Album", due: "same_day", owner: "Social Media / Motion" },
      { id: "story", label: "1 Community Story", due: "within_48h", owner: "Social Media / Motion" },
      { id: "spotlight", label: "1 Local Spotlight", due: "within_48h", owner: "Social Media / Motion" },
      { id: "upcoming", label: "1 Upcoming Stop Post", due: "before_next_stop", owner: "Social Media / Motion" },
    ],
    septemberTarget: "Hundreds of pieces of Arkansas content by September forums",
    currentStopsCompleted: 0,
    currentContentPieces: 0,
  };
}

function buildMotionScheduleMd(motion: ReturnType<typeof buildMotionSchedule>): string {
  return `# Motion & Storytelling Production Schedule

> ${motion.rule}

By September the campaign should have **hundreds of pieces of Arkansas content**.

## Per-stop deliverables

| Asset | Due | Owner |
|-------|-----|-------|
${motion.perStopDeliverables.map((d) => `| ${d.label} | ${d.due.replace(/_/g, " ")} | ${d.owner} |`).join("\n")}

## Production workflow

1. Stop confirmed in Calendar Truth
2. Mobilize event created (if public)
3. Kelly executes stop with relationship meetings
4. Same-day: Reel + photo album
5. Within 48h: Community story + local spotlight
6. Before next stop: Upcoming stop post
7. Log in content inventory · feed Human Contact Index

## Reject

Drive in → photo → leave → no content pipeline.
`;
}

function main() {
  ensureDir(OPS_OUT);
  ensureDir(PACKETS_OUT);
  ensureDir(SHERWOOD_OUT);

  const generatedAt = new Date().toISOString();

  const ownershipSource = readJson<{
    mode?: string;
    calendarFlexPct?: string;
    coverageStandard?: Record<string, unknown>;
    assignments: OwnershipRow[];
  }>(path.join(OPS_DATA, "ownership-registry.source.json"));

  const endorsementSource = readJson<{ weekOneTargets: EndorsementTarget[] }>(
    path.join(OPS_DATA, "endorsement-strike-targets.source.json"),
  );

  const twentyWeek = readJson<{ weeks: WeekPlan[] }>(TWENTY_WEEK);
  const peoplePower = readJson<{ volunteerLeadership?: { foundingTeamGoal?: number; foundingTeamCurrent?: number; launchCall?: { date: string; time: string } } }>(
    path.join(BRAIN_DATA, "people-power-network.json"),
  );
  const sherwood = readJson<Record<string, unknown>>(path.join(BRAIN_DATA, "win-sherwood-operation.json")) ?? {};
  const coalition = readJson<{ sherwood?: Record<string, unknown> }>(path.join(BRAIN_DATA, "coalition-power-map-summary.json")) ?? {};

  const assignments = ownershipSource?.assignments ?? [];
  const weekOneTargets = endorsementSource?.weekOneTargets ?? [];
  const weeks30Day = (twentyWeek?.weeks ?? []).filter((w) => w.weekNumber >= 1 && w.weekNumber <= 4);

  const registry = {
    generatedAt,
    mode: "campaign_operations",
    disclaimer: DISCLAIMER,
    calendarFlexPct: ownershipSource?.calendarFlexPct ?? "15-20",
    coverageStandard: ownershipSource?.coverageStandard,
    unassignedCount: assignments.filter((a) => {
      const o = a.owner.trim().toLowerCase();
      return !o || o === "unassigned" || o === "tbd" || o.startsWith("tbd");
    }).length,
    assignments,
  };

  writeFileSync(path.join(OPS_OUT, "ownership-registry.json"), JSON.stringify(registry, null, 2));
  writeFileSync(path.join(OPS_OUT, "ownership-dashboard.md"), buildOwnershipDashboard(assignments, generatedAt));
  writeFileSync(path.join(OPS_OUT, "perfect-week-doctrine.md"), buildPerfectWeekDoctrine());

  for (const week of weeks30Day) {
    const dir = path.join(PACKETS_OUT, padWeek(week.weekNumber));
    ensureDir(dir);
    const pp = peoplePower?.volunteerLeadership ?? {};
    writeFileSync(path.join(dir, "candidate-packet.md"), buildCandidatePacket(week));
    writeFileSync(path.join(dir, "volunteer-packet.md"), buildVolunteerPacket(week, pp));
    writeFileSync(path.join(dir, "coalition-packet.md"), buildCoalitionPacket(week));
    writeFileSync(path.join(dir, "endorsement-packet.md"), buildEndorsementPacket(week, weekOneTargets));
    writeFileSync(path.join(dir, "social-media-packet.md"), buildSocialMediaPacket(week));
  }

  const sherwoodCmd = buildSherwoodCommandCenter(sherwood, coalition.sherwood ?? {});
  writeFileSync(path.join(SHERWOOD_OUT, "command-center.json"), JSON.stringify(sherwoodCmd, null, 2));
  writeFileSync(path.join(SHERWOOD_OUT, "command-center.md"), buildSherwoodMd(sherwoodCmd));
  writeFileSync(
    path.join(SHERWOOD_OUT, "checklist.md"),
    `# Sherwood Daily Checklist

- [ ] VIP table sales call block (owner: Sherwood Event lead)
- [ ] Sponsor outreach (1 contact minimum)
- [ ] Mobilize RSVP check
- [ ] Volunteer shift coverage confirmed
- [ ] Candidate invitation follow-ups
- [ ] Labor + NAACP invitation status
- [ ] Media advisory / pickup tracking
- [ ] Compliance items advancing (permits · security · alcohol review)

**Target before July 3:** ${sherwoodCmd.metrics.vipTablesGoal} VIP tables · 50 volunteers · 300 Mobilize RSVPs
`,
  );

  const strikeTeam = {
    generatedAt,
    weekOneTargets,
    rules: [
      "Log every ask: date · owner · status · next action",
      "Endorsement opportunities override bonus-tier county completion",
      "15-20% calendar flex reserved for coalition opportunities",
    ],
  };
  writeFileSync(path.join(OPS_OUT, "endorsement-strike-team.json"), JSON.stringify(strikeTeam, null, 2));
  writeFileSync(
    path.join(OPS_OUT, "endorsement-strike-team.md"),
    `# Endorsement Strike Team — Week One

| Organization | Owner | Ask date | Status | Next action |
|--------------|-------|----------|--------|-------------|
${weekOneTargets.map((t) => `| ${t.organization} | ${t.owner} | ${t.askDate} | ${t.status} | ${t.nextAction} |`).join("\n")}
`,
  );

  const coalitionSprint = buildCoalitionSprint();
  writeFileSync(path.join(OPS_OUT, "coalition-contact-sprint.json"), JSON.stringify(coalitionSprint, null, 2));
  writeFileSync(path.join(OPS_OUT, "coalition-contact-sprint.md"), buildCoalitionSprintMd(coalitionSprint));

  const motion = buildMotionSchedule();
  writeFileSync(path.join(OPS_OUT, "motion-production-schedule.json"), JSON.stringify(motion, null, 2));
  writeFileSync(path.join(OPS_OUT, "motion-production-schedule.md"), buildMotionScheduleMd(motion));

  writeFileSync(
    path.join(OPS_OUT, "operations-lock-pass.summary.json"),
    JSON.stringify(
      {
        generatedAt,
        disclaimer: DISCLAIMER,
        mode: "campaign_operations",
        ownershipFunctions: assignments.length,
        unassignedOwners: registry.unassignedCount,
        weeklyPacketWeeks: weeks30Day.length,
        sherwoodCommandCenter: true,
        endorsementWeekOneTargets: weekOneTargets.length,
        coalitionSprintGoal: coalitionSprint.totalGoal,
        coalitionSprintDeadline: LABOR_DAY,
        motionPerStopDeliverables: motion.perStopDeliverables.length,
      },
      null,
      2,
    ),
  );

  writeFileSync(
    path.join(OPS_OUT, "CAMPAIGN-OPERATIONS-MODE.md"),
    `# Campaign Operations Mode

> ${DISCLAIMER}

The project has crossed from planning into **leadership decision-making and field execution**.

The biggest risk is no longer the calendar — it is that a statewide operating system exists and **nobody owns enough pieces of it**.

## Start here

| Document | Purpose |
|----------|---------|
| [Ownership dashboard](./ownership-dashboard.md) | **Assign names before lunch** |
| [Perfect week doctrine](./perfect-week-doctrine.md) | What a perfect week looks like |
| [Weekly packets](./weekly-packets/week-01/candidate-packet.md) | Week 1 candidate · volunteer · coalition · endorsement · social |
| [Sherwood command center](./sherwood-60/command-center.md) | GOTV kickoff tracking |
| [Endorsement strike team](./endorsement-strike-team.md) | Week One targets |
| [Coalition contact sprint](./coalition-contact-sprint.md) | 100 conversations by Labor Day |
| [Motion production schedule](./motion-production-schedule.md) | 5 assets per stop |

## 30-day command structure

Weekly packets generated for weeks **1–4** (${weeks30Day.map((w) => w.range).join(" · ")}).

## Rebuild

\`\`\`bash
npm run campaign-brain:operations-lock:build
\`\`\`

Edit owners in \`data/campaign-brain/operations/ownership-registry.source.json\`.

## Not included (by design)

- Google Calendar write
- /events publish
- New election-plan dashboard sections
- Calendar operational lock (requires Phase C sign-off first)
`,
  );

  console.log(
    `Operations Lock Pass: ${assignments.length} functions · ${registry.unassignedCount} unassigned · ${weeks30Day.length} weekly packet sets · Sherwood command center ready`,
  );
}

main();
