import { contractToCatalogEntry, type CampaignAiToolContract } from "../ai-tools/tool-contract";

const LIFECYCLE = "sprint5_calendar_promotion" as const;
const SPRINT = 5;

function t(p: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: LIFECYCLE, version: "v1", ...p };
}

export const SPRINT5_PROMOTION_TOOL_CONTRACTS: CampaignAiToolContract[] = [
  t({
    id: "promotion-readiness-checker",
    name: "Promotion readiness checker",
    purpose: "Deterministic READY/WARNING/BLOCKED checks before any Google write.",
    trigger: "Promotion workbench · promote modal",
    inputs: "Ledger record + workbench row + target lane",
    outputs: "PromotionReadinessResult",
    readsFrom: "promotion-readiness.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Never auto-promote",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/promotion-readiness.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["promotion_blocked", "ai_tool_invoked"],
    futureAutomationPath: "V2: ML risk score from observation history",
    testChecklist: ["Blocked when not approved", "WARNING when conflicts"],
    priority: "P0",
  }),
  t({
    id: "tentative-calendar-router",
    name: "Tentative calendar router",
    purpose: "Route approved events to Kelly Tentative Google CalendarSource.",
    trigger: "Promote to tentative click",
    inputs: "targetLane=tentative",
    outputs: "CalendarSource + payload",
    readsFrom: "kelly-google-calendar-policy.ts",
    writesTo: "Google Calendar tentative lane",
    humanApprovalRequired: true,
    riskLevel: "high",
    guardrails: "Human must click Promote",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/calendar/kelly-google-calendar-policy.ts#findKellyTentativeCalendarSource",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["tentative_promoted", "promotion_attempted"],
    futureAutomationPath: "V2: staged queue with CM co-sign",
    testChecklist: ["Uses tentative source only"],
    priority: "P0",
  }),
  t({
    id: "official-calendar-router",
    name: "Official calendar router",
    purpose: "Route approved events to Kelly Confirmed/Official Google calendar.",
    trigger: "Promote to official click",
    inputs: "targetLane=official",
    outputs: "CalendarSource + payload",
    readsFrom: "kelly-google-calendar-policy.ts",
    writesTo: "Google Calendar official lane",
    humanApprovalRequired: true,
    riskLevel: "high",
    guardrails: "Requires explicit human confirmation",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/calendar/kelly-google-calendar-policy.ts#findKellyConfirmedCalendarSource",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["official_promoted", "promotion_attempted"],
    futureAutomationPath: "V2: dual approval for official lane",
    testChecklist: ["Official lane OAuth required"],
    priority: "P0",
  }),
  t({
    id: "promotion-conflict-scanner",
    name: "Promotion conflict scanner",
    purpose: "Flag schedule conflicts and work-hours before promotion.",
    trigger: "Readiness assess",
    inputs: "conflicts.ts · row warnings",
    outputs: "warnings / blockers",
    readsFrom: "conflicts.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "medium",
    guardrails: "Flag only",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/conflicts.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["duplicate_detected", "promotion_blocked"],
    futureAutomationPath: "V2: predict conflict resolution",
    testChecklist: ["Conflict blocks official by default"],
    priority: "P0",
  }),
  t({
    id: "google-payload-builder",
    name: "Google payload builder",
    purpose: "Build exact Google Calendar API event body preview.",
    trigger: "Preview payload · pre-write",
    inputs: "Ledger row",
    outputs: "GooglePayloadPreview + Schema$Event",
    readsFrom: "build-google-payload.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Preview before write",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/build-google-payload.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["payload_edited", "ai_tool_invoked"],
    futureAutomationPath: "V2: learn from operator-edited payloads",
    testChecklist: ["Title/location/datetime present"],
    priority: "P0",
  }),
  t({
    id: "google-write-guard",
    name: "Google write guard",
    purpose: "Block writes when GOOGLE_CALENDAR_WRITE_ENABLED or OAuth lanes missing.",
    trigger: "Promote click",
    inputs: "promotion-config.ts",
    outputs: "skipped_disabled | proceed",
    readsFrom: "promotion-config.ts",
    writesTo: "audit log",
    humanApprovalRequired: true,
    riskLevel: "blocked",
    guardrails: "No write without env + human",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/promotion-config.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["promotion_blocked"],
    futureAutomationPath: "V2: deploy-time preflight webhook",
    testChecklist: ["Disabled when env false"],
    priority: "P0",
  }),
  t({
    id: "promotion-audit-logger",
    name: "Promotion audit logger",
    purpose: "Append promotion attempts to factCard._calendarPromotionLog.",
    trigger: "Every promote path",
    inputs: "action + actor + lane",
    outputs: "PromotionAuditEntry",
    readsFrom: "promotion-audit.ts",
    writesTo: "factCard._calendarPromotionLog",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No secrets in log",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/promotion-audit.ts",
    routesUsingTool: ["/admin/campaign-events/[recordId]"],
    observationEvents: ["promotion_succeeded", "promotion_failed"],
    futureAutomationPath: "V2: export to compliance archive",
    testChecklist: ["Dry-run logs without Google call"],
    priority: "P0",
  }),
  t({
    id: "promotion-risk-summary-writer",
    name: "Promotion risk summary writer",
    purpose: "Plain-English promotion summary for operators.",
    trigger: "Payload preview",
    inputs: "PromotionReadinessResult",
    outputs: "summary string",
    readsFrom: "sprint5-tool-helpers.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Suggestions only",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/sprint5-tool-helpers.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: candidate-facing promotion brief",
    testChecklist: ["Matches readiness level"],
    priority: "P1",
  }),
  t({
    id: "promotion-retry-handler",
    name: "Promotion retry handler",
    purpose: "Retry failed promotions with same readiness + payload flow.",
    trigger: "Retry button on failed row",
    inputs: "failed meta.promotionError",
    outputs: "new attempt result",
    readsFrom: "promote-ledger-event.ts",
    writesTo: "ledger + Google",
    humanApprovalRequired: true,
    riskLevel: "high",
    guardrails: "Human must click Retry",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/promote-ledger-event.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["promotion_attempted", "promotion_failed"],
    futureAutomationPath: "V2: exponential backoff suggestions",
    testChecklist: ["Increments promotionAttemptCount"],
    priority: "P1",
  }),
  t({
    id: "promotion-human-review-gate",
    name: "Promotion human review gate",
    purpose: "Enforce explicit human promote — no autonomous writes.",
    trigger: "All promotion UI",
    inputs: "operator session",
    outputs: "UI enabled state",
    readsFrom: "tool-contract CAMPAIGN_AI_HUMAN_CONTROL_RULES",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "blocked",
    guardrails: "AI may not promote",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/tool-contract.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["promotion_blocked"],
    futureAutomationPath: "V2: role-based dual control",
    testChecklist: ["No cron auto-promote"],
    priority: "P0",
  }),
  t({
    id: "duplicate-google-event-detector",
    name: "Duplicate Google event detector",
    purpose: "Detect duplicate googleEventId across ledger rows.",
    trigger: "Workbench load",
    inputs: "ledger googleEventId",
    outputs: "duplicate warning",
    readsFrom: "prisma ledger peers",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "medium",
    guardrails: "Warn only",
    currentStatus: "partial",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/promotion-readiness.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["duplicate_detected"],
    futureAutomationPath: "V2: cross-check GoogleCalendarEventRecord",
    testChecklist: ["duplicateRisk surfaces in queue"],
    priority: "P1",
  }),
  t({
    id: "calendar-lane-health-checker",
    name: "Calendar lane health checker",
    purpose: "Verify tentative/official CalendarSource OAuth + sync enabled.",
    trigger: "Promotion workbench load",
    inputs: "CalendarSource table",
    outputs: "config.tentativeSourceReady / officialSourceReady",
    readsFrom: "promotion-config.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/promotion-config.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion", "/admin/campaign-events/calendar-sync"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: auto-refresh token health",
    testChecklist: ["Shows lane not ready in UI"],
    priority: "P0",
  }),
  t({
    id: "promotion-observation-recorder",
    name: "Promotion observation recorder",
    purpose: "Record promotion workflow observations for V2 learning.",
    trigger: "Promote / block / succeed / fail",
    inputs: "toolId + event",
    outputs: "AiObservationEntry",
    readsFrom: "record-promotion-observation.ts",
    writesTo: "factCard._aiObservations",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Append-only",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/record-promotion-observation.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["promotion_attempted", "promotion_succeeded", "promotion_failed"],
    futureAutomationPath: "V2: analytics warehouse export",
    testChecklist: ["Observations on drilldown"],
    priority: "P0",
  }),
  t({
    id: "official-calendar-safety-blocker",
    name: "Official calendar safety blocker",
    purpose: "Hard guard: Sprint 5 writes only via human promotion flow.",
    trigger: "promote-ledger-event entry",
    inputs: "code path name",
    outputs: "assertion ok",
    readsFrom: "sprint5-tool-helpers.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "blocked",
    guardrails: "No background promotion",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/sprint5-tool-helpers.ts#assertOfficialCalendarSafetyBlocker",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: CI static analysis",
    testChecklist: ["Approval email path does not call upsertGoogleEvent"],
    priority: "P0",
  }),
  t({
    id: "google-write-status-summarizer",
    name: "Google write status summarizer",
    purpose: "Summarize promotion + sync status for dashboards.",
    trigger: "Dashboard / workbench badges",
    inputs: "meta + config",
    outputs: "short status line",
    readsFrom: "sprint5-tool-helpers.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Display only",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/sprint5-tool-helpers.ts",
    routesUsingTool: ["/admin/candidate-dashboard", "/admin/campaign-manager-dashboard"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: CM daily digest",
    testChecklist: ["Shows promoted/blocked/failed"],
    priority: "P1",
  }),
];

export const SPRINT5_PROMOTION_CATALOG_ENTRIES = SPRINT5_PROMOTION_TOOL_CONTRACTS.map(contractToCatalogEntry);
