import type { VoterAudienceProfile } from "../../src/lib/election-plan/voter-audience-models/types";

/** Named fictional personas — Kelly's big-tent audience cast. */
export const VOTER_AUDIENCE_SEEDS: VoterAudienceProfile[] = [
  {
    id: "marcia-truman",
    displayName: "Marcia T.",
    initials: "MT",
    avatarColor: "bg-blue-700",
    segment: "lane2_democrat",
    segmentLabel: "Lane 2 recovery Democrat",
    tagline: "Voted before, drifted — needs competence, not slogans",
    demographicSketch: "Late 50s · suburban Little Rock · college-educated · voted in 2020, sat out 2022",
    geographySketch: "Pulaski, Saline, Faulkner suburbs; Central Metro cluster",
    estimatedShareNote: "Planning est. 8–12% of statewide persuadable pool in Tier A counties",
    whatTheyFear: ["Another chaotic election cycle", "Being lectured", "Candidates who only attack"],
    whatTheyNeedToHear: [
      "Kelly has run things — SOS is operations, not performance",
      "Clerks will get clear rules and respect",
      "Democratic recovery is practical access, not Twitter fights",
    ],
    kellyTone: "Warm executive — short sentences, zero condescension",
    doNotSay: ["Republicans are evil", "Stolen election", "You must turn out or democracy dies"],
    debatePrepHooks: ["author-vs-administrator", "county-champion", "lane-2"],
    homeCounties: ["pulaski", "saline", "faulkner", "lonoke"],
    homeCities: ["little-rock", "north-little-rock", "benton", "bryant", "conway"],
  },
  {
    id: "rev-james-holloway",
    displayName: "Rev. James H.",
    initials: "JH",
    avatarColor: "bg-indigo-800",
    segment: "faith_community",
    segmentLabel: "Faith & community anchor",
    tagline: "Pastor who moves souls and precincts",
    demographicSketch: "60s · Jefferson County · lifelong church leader · trusted validator",
    geographySketch: "Pine Bluff, Delta, southeast Black belt counties",
    estimatedShareNote: "Validator network — influence outweighs raw vote share",
    whatTheyFear: ["Voter suppression dressed as reform", "Candidates who disrespect congregations", "Cynicism in young voters"],
    whatTheyNeedToHear: [
      "Respect for faith community without pandering",
      "SOS protects access — Sunday souls need Tuesday ballots",
      "Kelly partners with churches on registration, not photo ops",
    ],
    kellyTone: "Pastoral respect — listen first, promise only what SOS can deliver",
    doNotSay: ["Weaponize scripture", "Attack Hammer's ministry", "Assume automatic turnout"],
    debatePrepHooks: ["voter-access", "faith-organizing", "delta"],
    homeCounties: ["jefferson", "phillips", "crittenden", "st-francis", "lee"],
    homeCities: ["pine-bluff", "west-memphis", "helena-west-helena", "forrest-city"],
  },
  {
    id: "carol-whitfield",
    displayName: "Carol W.",
    initials: "CW",
    avatarColor: "bg-slate-700",
    segment: "election_professional",
    segmentLabel: "County election professional",
    tagline: "The clerk room is her jury",
    demographicSketch: "50s · county clerk staff · nonpartisan professional identity",
    geographySketch: "Every county — especially understaffed rural offices",
    estimatedShareNote: "75 county ecosystems — clerks repeat your tone in courthouse hallways",
    whatTheyFear: ["Unfunded mandates", "Friday rule drops", "Candidates who've never run a polling site"],
    whatTheyNeedToHear: [
      "Implementation dollars and training timelines",
      "SOS as service desk — calls returned, guidance published",
      "Security and access are not opposites",
    ],
    kellyTone: "Peer professional — specifics over slogans",
    doNotSay: ["Clerks are failing", "Just follow the law", "I wrote the bill"],
    debatePrepHooks: ["county-champion", "integrity-without-participation", "acca"],
    homeCounties: ["pope", "white", "sebastian", "garland", "benton"],
    homeCities: ["russellville", "fort-smith", "hot-springs", "fayetteville"],
  },
  {
    id: "tyler-martinez",
    displayName: "Tyler M.",
    initials: "TM",
    avatarColor: "bg-cyan-700",
    segment: "young_voter",
    segmentLabel: "Young voter / campus",
    tagline: "First or second statewide vote — digital native",
    demographicSketch: "22 · UA student · works part-time · registers online",
    geographySketch: "Fayetteville, Conway, Jonesboro, Little Rock colleges",
    estimatedShareNote: "High mobility — registration churn is the story",
    whatTheyFear: ["Process confusion", "Being ignored", "Cringe politicians on TikTok"],
    whatTheyNeedToHear: [
      "How to register and vote in plain steps",
      "SOS modernizes — not their parents' paperwork maze",
      "Ballot measures matter to their future",
    ],
    kellyTone: "Direct, unpatronizing — policy in one breath, invite in the next",
    doNotSay: ["Kids these days", "Mandatory civics lecture", "Fake slang"],
    debatePrepHooks: ["registration", "direct-democracy", "digital"],
    homeCounties: ["washington", "pulaski", "faulkner", "craighead"],
    homeCities: ["fayetteville", "conway", "jonesboro", "little-rock"],
  },
  {
    id: "linda-sutton",
    displayName: "Linda S.",
    initials: "LS",
    avatarColor: "bg-amber-700",
    segment: "rural_independent",
    segmentLabel: "Rural independent mom",
    tagline: "Votes the person, not the party",
    demographicSketch: "40s · Johnson County · school board follower · drives 25 min to vote",
    geographySketch: "River Valley, south Arkansas timber counties",
    estimatedShareNote: "Classic swing temperament — low party registration, high local trust",
    whatTheyFear: ["Little Rock ignoring small towns", "Culture-war noise", "Long lines with kids in the car"],
    whatTheyNeedToHear: [
      "Kelly shows up — fair rules for every county",
      "Schools and clerks supported, not used as props",
      "Respect for gun-country independence without baiting",
    ],
    kellyTone: "Neighborly competence — Ozark/Valley plain speech",
    doNotSay: ["Coastal elite", "Deplorables", "Nationalize every answer"],
    debatePrepHooks: ["persuasion", "rural", "county-champion"],
    homeCounties: ["johnson", "logan", "scott", "polk", "howard"],
    homeCities: ["clarksville", "magnolia", "arkadelphia"],
  },
  {
    id: "robert-kessler",
    displayName: "Robert K.",
    initials: "RK",
    avatarColor: "bg-red-800",
    segment: "moderate_republican",
    segmentLabel: "Moderate Republican open door",
    tagline: "Chamber Republican who hates chaos",
    demographicSketch: "55 · Bentonville business owner · voted R but tired of drama",
    geographySketch: "Northwest Arkansas corporate corridor",
    estimatedShareNote: "NWA persuasion lane — business services frame lands here",
    whatTheyFear: ["Partisan SOS", "Ballot chaos hurting recruitment", "Hammer's legislature-only record"],
    whatTheyNeedToHear: [
      "SOS runs business services too — competent administration",
      "Election security with implementation funding",
      "Not asking him to leave his party — asking for steady hands",
    ],
    kellyTone: "Boardroom calm — agree on security, add operations proof",
    doNotSay: ["Republicans are fascists", "Trump bait", "Shame his vote history"],
    debatePrepHooks: ["business-services", "nwa-persuasion", "integrity"],
    homeCounties: ["benton", "washington", "sebastian"],
    homeCities: ["bentonville", "rogers", "springdale", "fort-smith"],
  },
  {
    id: "diane-porter",
    displayName: "Diane P.",
    initials: "DP",
    avatarColor: "bg-emerald-800",
    segment: "direct_democracy",
    segmentLabel: "Direct democracy defender",
    tagline: "Signed petitions since the Ozarks populist tradition",
    demographicSketch: "48 · Madison County · initiative veteran · distrusts Little Rock",
    geographySketch: "Ozarks, petition culture counties, issue campaigns",
    estimatedShareNote: "Cross-partisan — cares about ballot access for measures",
    whatTheyFear: ["Hammer's 2025 petition friction", "SOS used to kill initiatives", "Opaque ballot titles"],
    whatTheyNeedToHear: [
      "Kelly honors Arkansas ballot-measure tradition",
      "Transparent rules for petitioners and clerks",
      "Courts decide fights — SOS administers fairly",
    ],
    kellyTone: "Civic pride — populist respect without anti-government rage",
    doNotSay: ["Anti-petition", "Only Democrats use initiatives", "Hammer is evil"],
    debatePrepHooks: ["direct-democracy", "2025-petitions", "ozarks"],
    homeCounties: ["madison", "newton", "searcy", "boone", "marion"],
    homeCities: ["harrison", "mountain-home", "berryville"],
  },
  {
    id: "frank-donnelly",
    displayName: "Frank D.",
    initials: "FD",
    avatarColor: "bg-stone-600",
    segment: "election_skeptic",
    segmentLabel: "Skeptical election watcher",
    tagline: "Wants proof, not promises",
    demographicSketch: "62 · Garland County · consumes cable news · voted every general",
    geographySketch: "Retiree-heavy tourism counties, mail-in worriers",
    estimatedShareNote: "Anxiety voter — wins with process transparency, not dunks",
    whatTheyFear: ["Fraud and suppression simultaneously", "Machines and mail distrust", "Candidates who dodge specifics"],
    whatTheyNeedToHear: [
      "Show the process — observers, audits, public checks",
      "Prosecute real fraud; protect lawful voters",
      "Clerks are heroes when funded",
    ],
    kellyTone: "Calm forensic — slow down, reassure, cite process",
    doNotSay: ["Nothing to see here", "Deny all fraud concerns", "Mock worry"],
    debatePrepHooks: ["integrity", "anxious-audience", "show-process"],
    homeCounties: ["garland", "baxter", "carroll", "hot-spring"],
    homeCities: ["hot-springs", "mountain-home", "bella-vista"],
  },
  {
    id: "maria-gutierrez",
    displayName: "Maria G.",
    initials: "MG",
    avatarColor: "bg-orange-700",
    segment: "community_organizer",
    segmentLabel: "Community organizer",
    tagline: "Registers neighbors — bilingual bridge",
    demographicSketch: "35 · Springdale · nonprofit organizer · church + school networks",
    geographySketch: "NWA poultry corridor, growing Latino communities statewide",
    estimatedShareNote: "High growth communities — registration drives are relational",
    whatTheyFear: ["Language barriers at SOS", "ICE-politicized election talk", "Being invisible in campaigns"],
    whatTheyNeedToHear: [
      "Spanish-accessible SOS materials",
      "Partnership with community orgs — not last-minute outreach",
      "Safe registration events",
    ],
    kellyTone: "Organizer respect — credit community leaders",
    doNotSay: ["Outreach starts in September", "Token photo", "English-only framing"],
    debatePrepHooks: ["registration", "nwa", "community"],
    homeCounties: ["washington", "sebastian", "pulaski"],
    homeCities: ["springdale", "rogers", "fort-smith", "little-rock"],
  },
  {
    id: "bill-jennings",
    displayName: "Bill J.",
    initials: "BJ",
    avatarColor: "bg-neutral-600",
    segment: "senior_veteran",
    segmentLabel: "Senior veteran",
    tagline: "Votes every November — expects dignity",
    demographicSketch: "71 · Miller County · VFW member · absentee voter",
    geographySketch: "Southwest border counties, veteran-heavy communities",
    estimatedShareNote: "Reliable turnout — persuasion is respect and clarity",
    whatTheyFear: ["Mail ballot confusion", "Disrespect for service", "Rapid rule changes"],
    whatTheyNeedToHear: [
      "Absentee process explained clearly",
      "SOS honors veterans as voters, not props",
      "Stable rules with lead time for clerks",
    ],
    kellyTone: "Dignified — never performative patriotism",
    doNotSay: ["Stolen valor themes", "Mock older voters", "Complex jargon"],
    debatePrepHooks: ["absentee", "southwest", "senior"],
    homeCounties: ["miller", "lafayette", "hempstead", "little-river"],
    homeCities: ["texarkana", "hope", "ashdown"],
  },
  {
    id: "aisha-reed",
    displayName: "Aisha R.",
    initials: "AR",
    avatarColor: "bg-violet-800",
    segment: "delta_base",
    segmentLabel: "Delta base mobilizer",
    tagline: "Turnout is the mission",
    demographicSketch: "38 · Phillips County · Democratic county chair volunteer",
    geographySketch: "Delta — Phillips, Desha, Chicot, Lee",
    estimatedShareNote: "Base mobilization — energy + access stories",
    whatTheyFear: ["Drop-off after presidential years", "Underfunded Black counties", "National Democrats who disappear"],
    whatTheyNeedToHear: [
      "Kelly invests in Delta clerks and registration",
      "Lane 2 recovery with receipts",
      "Statewide campaign that doesn't skip east Arkansas",
    ],
    kellyTone: "Coalition partner — name counties, name partners",
    doNotSay: ["Take Black vote for granted", "Only visit in October", "Poverty tourism"],
    debatePrepHooks: ["delta", "turnout", "lane-2"],
    homeCounties: ["phillips", "desha", "chicot", "lee", "monroe"],
    homeCities: ["helena-west-helena", "stuttgart", "lake-village"],
  },
  {
    id: "coach-pat-nolan",
    displayName: "Coach Pat N.",
    initials: "PN",
    avatarColor: "bg-green-800",
    segment: "small_town_validator",
    segmentLabel: "Small-town validator",
    tagline: "Friday night lights to Tuesday ballots",
    demographicSketch: "50s · Pope County · retired coach · everyone knows his number",
    geographySketch: "County seats, high school hubs — Russellville, Searcy, Batesville",
    estimatedShareNote: "Validator multiplier — one Pat moves fifty voters",
    whatTheyFear: ["Candidates who fly in and fly out", "Talking down to towns", "Ignoring schools"],
    whatTheyNeedToHear: [
      "Kelly keeps coming back",
      "Fair rules for small counties with small staffs",
      "Student registration as civic pride",
    ],
    kellyTone: "Locker-room direct — handshake energy",
    doNotSay: ["Flyover country", "Only care about Little Rock", "Edgy attacks"],
    debatePrepHooks: ["validators", "schools", "pope"],
    homeCounties: ["pope", "white", "independence", "lawrence"],
    homeCities: ["russellville", "searcy", "batesville", "paragould"],
  },
  {
    id: "susan-ellis",
    displayName: "Susan E.",
    initials: "SE",
    avatarColor: "bg-pink-800",
    segment: "suburban_persuadable",
    segmentLabel: "Suburban persuadable woman",
    tagline: "Schools + safety + sanity",
    demographicSketch: "44 · Saline County · PTA · voted split ticket",
    geographySketch: "Bryant/Benton suburbs, Cabot, Fayetteville suburbs",
    estimatedShareNote: "National bellwether temperament — tone wins",
    whatTheyFear: ["Extremism on both sides", "Schools politicized", "Election chaos affecting kids"],
    whatTheyNeedToHear: [
      "Steady mom-executive energy",
      "Elections boring in the good way — well-run",
      "Clerks supported so lines stay short",
    ],
    kellyTone: "Kelly archetype — competent warmth",
    doNotSay: ["Culture war bait", "Mansplaining", "Panic"],
    debatePrepHooks: ["suburban", "schools", "kelly-archetype"],
    homeCounties: ["saline", "lonoke", "benton", "faulkner"],
    homeCities: ["bryant", "benton", "cabot", "conway"],
  },
  {
    id: "tom-rutherford",
    displayName: "Tom R.",
    initials: "TR",
    avatarColor: "bg-teal-800",
    segment: "ozarks_retiree",
    segmentLabel: "Ozarks retiree civic",
    tagline: "Moved here for peace — votes for competence",
    demographicSketch: "67 · Baxter County · retired teacher from Missouri",
    geographySketch: "Retiree Ozarks — lakes, tourism, part-time residency",
    estimatedShareNote: "High civic participation rate per capita",
    whatTheyFear: ["Growth overwhelming clerks", "Partisan SOS", "Being dismissed as transplant"],
    whatTheyNeedToHear: [
      "Retiree-friendly voting info",
      "Growth managed with clerk funding",
      "Respect for local Ozarks identity",
    ],
    kellyTone: "Teacher respect — clear explanations",
    doNotSay: ["Go back where you came from", "Dismiss retirees", "Overpromise growth"],
    debatePrepHooks: ["ozarks", "retiree", "civic"],
    homeCounties: ["baxter", "boone", "carroll", "marion", "newton"],
    homeCities: ["mountain-home", "harrison", "eureka-springs", "berryville"],
  },
  {
    id: "keisha-lyons",
    displayName: "Keisha L.",
    initials: "KL",
    avatarColor: "bg-rose-800",
    segment: "working_parent",
    segmentLabel: "Working shift parent",
    tagline: "Votes after second shift",
    demographicSketch: "34 · Pulaski · hospital CNA · childcare juggle",
    geographySketch: "Service workers statewide — Little Rock, Jonesboro, Fort Smith",
    estimatedShareNote: "Access story — hours, ID, childcare, early vote",
    whatTheyFear: ["Missing work to vote", "Rules changing", "No one explains deadlines"],
    whatTheyNeedToHear: [
      "Early vote and absentee spelled out",
      "SOS meets people where they are",
      "No shame for asking how",
    ],
    kellyTone: "Practical empathy — steps, dates, places",
    doNotSay: ["Just vote harder", "Assume flexible schedule", "Jargon"],
    debatePrepHooks: ["voter-access", "working-families", "practical"],
    homeCounties: ["pulaski", "craighead", "sebastian", "jefferson"],
    homeCities: ["little-rock", "jonesboro", "fort-smith", "pine-bluff"],
  },
  {
    id: "paul-listener",
    displayName: "Paul L.",
    initials: "PL",
    avatarColor: "bg-purple-700",
    segment: "reform_curious",
    segmentLabel: "Reform-curious independent",
    tagline: "Listens to Pakko — open to Kelly's competence",
    demographicSketch: "52 · Conway · likes third-way ideas · distrusts parties",
    geographySketch: "College towns, ACCA-adjacent policy literates",
    estimatedShareNote: "Three-way geometry — agree-add without insulting Pakko",
    whatTheyFear: ["Duopoly forever", "Chaos candidates", "No real reform"],
    whatTheyNeedToHear: [
      "Respect Pakko's reform themes",
      "Kelly is the one who can implement Monday morning",
      "Transparency plus operations",
    ],
    kellyTone: "Intellectual calm — bridge, don't bulldoze",
    doNotSay: ["Waste your vote", "Attack Pakko personally", "Ignore reform"],
    debatePrepHooks: ["three-way", "pakko", "reform"],
    homeCounties: ["faulkner", "pulaski", "washington"],
    homeCities: ["conway", "fayetteville", "little-rock"],
  },
];
