import type { MasterAuthorStudioState, TransformOutput } from "./masterAuthorTypes";

const defaultTransforms: TransformOutput[] = [
  { kind: "facebook", label: "Facebook post", body: "", refined: false },
  { kind: "instagram", label: "Instagram caption", body: "", refined: false },
  { kind: "x_thread", label: "X post / thread", body: "", refined: false },
  { kind: "tiktok", label: "TikTok script", body: "", refined: false },
  { kind: "yt_shorts", label: "YouTube Shorts (title + description)", body: "", refined: false },
  { kind: "email", label: "Email intro", body: "", refined: false },
  { kind: "sms", label: "SMS teaser", body: "", refined: false },
  { kind: "press", label: "Press statement", body: "", refined: false },
  { kind: "stump", label: "Stump paragraph", body: "", refined: false },
  { kind: "volunteer_cta", label: "Volunteer CTA", body: "", refined: false },
  { kind: "county_localized", label: "County-specific localized", body: "", refined: false },
];

export function createInitialMasterAuthorState(): MasterAuthorStudioState {
  return {
    brief: {
      title: "Ballot rights rapid response",
      campaignGoal: "Defend direct democracy; contrast with insider politics.",
      messageType: "RAPID_RESPONSE",
      urgency: "urgent",
      audience: "Persuadable + base in Arkansas",
      tone: "Clear, direct, hopeful",
      voiceMode: "campaign",
      countyOrRegion: "Statewide (Pulaski focus)",
      issueTags: "ballot access, SoS, transparency",
      eventLink: "",
      cta: "Sign up to volunteer for voter outreach.",
      oppositionContext: "Petition process framed as 'special interests'.",
      mustInclude: "People over politics; ballot rights belong to voters.",
      mustAvoid: "Personal attacks; unverified legal claims.",
      sourceAssets: "kelly-remarks-owned-media-0422 (mock ref)",
      notes: "Coordinate with comms on legal review for any statutory references.",
    },
    research: {
      fileContext: [
        { id: "f1", name: "DNC field messaging — democracy", snippet: "Frame access as foundation of participation…", pinned: false },
        { id: "f2", name: "Internal issue brief: ballot process", snippet: "Initiative timeline, signature thresholds…", pinned: true },
      ],
      webPanel: [
        { id: "w1", title: "AP — Arkansas ballot access", url: "https://example.com/ap", note: "Recent procedural coverage (mock).", pinned: false },
      ],
      sourceNotes: "Pull official SoS page language when generating external-facing copy.",
      citations: [{ id: "c1", text: "Statutory cite placeholder — replace with research memo.", source: "File search (TODO API)" }],
      researchMemo: "",
      rebuttalContext: "",
      countyContext: "",
      priorSaid: "",
      summaryMemo: "",
    },
    compose: {
      master:
        "Arkansans deserve a Secretary of State who protects the people’s right to act when politicians stop listening. Kelly Grappe stands for people over politics, transparent elections, and full respect for the ballot initiative process.",
      alternates: [
        { id: "a1", label: "Warmer", body: "Your voice in Arkansas shouldn’t depend on who holds office…", createdAt: "—" },
        { id: "a2", label: "Sharper contrast", body: "Insiders can delay and confuse — voters deserve clarity…", createdAt: "—" },
      ],
      compareLeftId: "master",
      compareRightId: "a1",
      compareMode: false,
      length: "standard",
    },
    transforms: defaultTransforms,
    visual: {
      imagePrompt: "Civic sunrise over Arkansas, voter-centered, no faces, people-over-politics mood.",
      promptVersions: [
        { id: "v1", label: "v1", prompt: "…" },
        { id: "v2", label: "v2 — higher contrast", prompt: "…" },
      ],
      styleNotes: "Campaign palette, high legibility, no stock clichés.",
      quoteCardHeadline: "The ballot belongs to the people.",
      quoteCardAttribution: "— Kelly Grappe",
      thumbnailConcept: "Big type + subtle map silhouette",
      flyerConcept: "Event + CTA; QR to volunteer (placeholder)",
      beforeAfterNotes: "Before: cluttered; after: one hero line + one proof point.",
      generatedPlaceholders: [
        { id: "g1", label: "Concept A (placeholder)" },
        { id: "g2", label: "Concept B (placeholder)" },
      ],
    },
    video: {
      transcript: "[00:00] … speaking at the courthouse about ballot access and trust…",
      sourceClipLabel: "courthouse-visit-15s.mp4 (upload via Owned Media / asset pipeline)",
      clipSuggestions: ["0:03–0:12 — strong line on transparency", "0:12–0:20 — CTA to volunteer"],
      hooks: "",
      coldOpen: "",
      subtitles: "",
      lowerThird: "Kelly Grappe · For Secretary of State",
      broll: "Courthouse steps, county signage, crowd texture (B-roll from library)",
      cutPlan: "1) Hook 2) Proof 3) CTA 4) End card",
      packaging: "tiktok",
      editInstructionMemo: "Export to editor as EDL/JSON + shot list; rendering via external tool or service job.",
    },
    platformPack: [
      {
        id: "p1",
        platform: "Facebook",
        targetAccount: "Kelly Grappe Campaign (main)",
        objective: "Persuasion + share",
        scheduleAt: "",
        copy: "Arkansans deserve…",
        cta: "Share + volunteer",
        hashtags: "#arpx #SOS",
        notes: "Pair with image concept A",
        assetNote: "Image TBD (designer task)",
        readiness: "draft",
      },
      {
        id: "p2",
        platform: "X",
        targetAccount: "@KellyGrappeAR",
        objective: "Rapid reframe",
        scheduleAt: "",
        copy: "Direct democracy belongs to the people.",
        cta: "Link in bio",
        hashtags: "#arpx",
        notes: "Thread: 2–3 posts",
        assetNote: "",
        readiness: "ready",
      },
    ],
    approval: {
      checklist: [
        { id: "k1", label: "Legal / factual review", done: false },
        { id: "k2", label: "Comms sign-off", done: false },
        { id: "k3", label: "Accessibility (alt text / captions plan)", done: false },
        { id: "k4", label: "Schedule + owner assigned", done: false },
      ],
      linkedTasks: [{ id: "t1", label: "Approve master copy (mock)", type: "task" }],
      linkedAssets: [{ id: "as1", label: "courthouse clip (mock)", type: "asset" }],
      linkedEvent: "— (link CampaignEvent in DB)",
      linkedIntake: "— (link WorkflowIntake in DB)",
      exportNotes: "",
    },
  };
}
