/**
 * Official YouTube Data API captions + video discovery (OAuth bearer).
 */

import { getValidYouTubeAccessToken } from "./oauth-client";
import { getYouTubeOAuthEnv } from "./oauth-config";

const API = "https://www.googleapis.com/youtube/v3";

export type YouTubeCaptionTrack = {
  id: string;
  videoId: string;
  language: string;
  name: string;
  trackKind: string;
  isAutoGenerated: boolean;
  isDraft: boolean;
  lastUpdated?: string;
};

export type DiscoveredYouTubeVideo = {
  videoId: string;
  title: string;
  description: string;
  publishedAt: string | null;
  thumbnailUrl: string | null;
  durationIso8601: string | null;
  privacyStatus: string | null;
  isShortHeuristic: boolean;
  isLive: boolean;
};

async function authHeaders(repoRoot?: string): Promise<HeadersInit> {
  const { accessToken } = await getValidYouTubeAccessToken(repoRoot);
  return { Authorization: `Bearer ${accessToken}` };
}

export async function listCaptionTracks(
  videoId: string,
  repoRoot?: string,
): Promise<YouTubeCaptionTrack[]> {
  const headers = await authHeaders(repoRoot);
  const url = `${API}/captions?part=snippet&videoId=${encodeURIComponent(videoId)}`;
  const res = await fetch(url, { headers, cache: "no-store" });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`captions.list failed ${res.status}: ${text.slice(0, 200)}`);
  }
  const json = (await res.json()) as {
    items?: Array<{
      id?: string;
      snippet?: {
        videoId?: string;
        language?: string;
        name?: string;
        trackKind?: string;
        status?: string;
        lastUpdated?: string;
      };
    }>;
  };
  return (json.items ?? [])
    .filter((i) => i.id)
    .map((i) => {
      const kind = (i.snippet?.trackKind ?? "standard").toLowerCase();
      return {
        id: i.id!,
        videoId: i.snippet?.videoId ?? videoId,
        language: i.snippet?.language ?? "en",
        name: i.snippet?.name ?? "",
        trackKind: kind,
        isAutoGenerated: kind === "asr",
        isDraft: (i.snippet?.status ?? "").toLowerCase() === "draft",
        lastUpdated: i.snippet?.lastUpdated,
      };
    });
}

/** Prefer creator (non-ASR) English track, else any creator, else ASR English, else first. */
export function pickPreferredCaptionTrack(tracks: YouTubeCaptionTrack[]): YouTubeCaptionTrack | null {
  if (!tracks.length) return null;
  const en = (t: YouTubeCaptionTrack) => t.language.toLowerCase().startsWith("en");
  return (
    tracks.find((t) => !t.isAutoGenerated && en(t)) ??
    tracks.find((t) => !t.isAutoGenerated) ??
    tracks.find((t) => t.isAutoGenerated && en(t)) ??
    tracks[0] ??
    null
  );
}

export async function downloadCaptionTrack(
  captionId: string,
  opts?: { tfmt?: "srt" | "vtt" | "ttml"; repoRoot?: string },
): Promise<string> {
  const headers = await authHeaders(opts?.repoRoot);
  const tfmt = opts?.tfmt ?? "vtt";
  const url = `${API}/captions/${encodeURIComponent(captionId)}?tfmt=${encodeURIComponent(tfmt)}`;
  const res = await fetch(url, { headers, cache: "no-store" });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`captions.download failed ${res.status}: ${text.slice(0, 200)}`);
  }
  return await res.text();
}

export async function uploadCaptionTrack(opts: {
  videoId: string;
  language: string;
  name: string;
  captionBody: string;
  /** MIME for body — SRT recommended */
  mimeType?: string;
  repoRoot?: string;
}): Promise<{ id: string | null }> {
  const { accessToken } = await getValidYouTubeAccessToken(opts.repoRoot);
  const metadata = {
    snippet: {
      videoId: opts.videoId,
      language: opts.language,
      name: opts.name,
    },
  };
  const boundary = `reddirt_${Date.now()}`;
  const body =
    `--${boundary}\r\n` +
    `Content-Type: application/json; charset=UTF-8\r\n\r\n` +
    `${JSON.stringify(metadata)}\r\n` +
    `--${boundary}\r\n` +
    `Content-Type: ${opts.mimeType ?? "application/octet-stream"}\r\n\r\n` +
    `${opts.captionBody}\r\n` +
    `--${boundary}--`;

  const res = await fetch(`${API}/captions?part=snippet`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": `multipart/related; boundary=${boundary}`,
    },
    body,
    cache: "no-store",
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`captions.insert failed ${res.status}: ${text.slice(0, 200)}`);
  }
  const json = (await res.json()) as { id?: string };
  return { id: json.id ?? null };
}

function parseIsoDurationToSeconds(iso: string | null | undefined): number | null {
  if (!iso) return null;
  const m = iso.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!m) return null;
  const h = Number(m[1] ?? 0);
  const min = Number(m[2] ?? 0);
  const s = Number(m[3] ?? 0);
  return h * 3600 + min * 60 + s;
}

export async function discoverChannelUploads(opts?: {
  maxResults?: number;
  repoRoot?: string;
}): Promise<DiscoveredYouTubeVideo[]> {
  const headers = await authHeaders(opts?.repoRoot);
  const channelId = getYouTubeOAuthEnv().channelId;
  let uploadsPlaylistId: string | null = null;

  if (channelId) {
    const chRes = await fetch(
      `${API}/channels?part=contentDetails&id=${encodeURIComponent(channelId)}`,
      { headers, cache: "no-store" },
    );
    if (chRes.ok) {
      const ch = (await chRes.json()) as {
        items?: Array<{ contentDetails?: { relatedPlaylists?: { uploads?: string } } }>;
      };
      uploadsPlaylistId = ch.items?.[0]?.contentDetails?.relatedPlaylists?.uploads ?? null;
    }
  }

  if (!uploadsPlaylistId) {
    const mine = await fetch(`${API}/channels?part=contentDetails&mine=true`, {
      headers,
      cache: "no-store",
    });
    if (!mine.ok) {
      const text = await mine.text();
      throw new Error(`channels.list failed ${mine.status}: ${text.slice(0, 200)}`);
    }
    const ch = (await mine.json()) as {
      items?: Array<{ contentDetails?: { relatedPlaylists?: { uploads?: string } } }>;
    };
    uploadsPlaylistId = ch.items?.[0]?.contentDetails?.relatedPlaylists?.uploads ?? null;
  }

  if (!uploadsPlaylistId) throw new Error("Could not resolve uploads playlist for channel.");

  const maxResults = Math.min(opts?.maxResults ?? 25, 50);
  const plRes = await fetch(
    `${API}/playlistItems?part=snippet,contentDetails&playlistId=${encodeURIComponent(uploadsPlaylistId)}&maxResults=${maxResults}`,
    { headers, cache: "no-store" },
  );
  if (!plRes.ok) {
    const text = await plRes.text();
    throw new Error(`playlistItems.list failed ${plRes.status}: ${text.slice(0, 200)}`);
  }
  const pl = (await plRes.json()) as {
    items?: Array<{
      contentDetails?: { videoId?: string };
      snippet?: {
        title?: string;
        description?: string;
        publishedAt?: string;
        thumbnails?: { high?: { url?: string }; medium?: { url?: string } };
      };
    }>;
  };

  const ids = (pl.items ?? [])
    .map((i) => i.contentDetails?.videoId)
    .filter((id): id is string => Boolean(id));
  if (!ids.length) return [];

  const vRes = await fetch(
    `${API}/videos?part=snippet,contentDetails,status,liveStreamingDetails&id=${ids.map(encodeURIComponent).join(",")}`,
    { headers, cache: "no-store" },
  );
  if (!vRes.ok) {
    const text = await vRes.text();
    throw new Error(`videos.list failed ${vRes.status}: ${text.slice(0, 200)}`);
  }
  const vj = (await vRes.json()) as {
    items?: Array<{
      id?: string;
      snippet?: {
        title?: string;
        description?: string;
        publishedAt?: string;
        thumbnails?: { high?: { url?: string }; medium?: { url?: string } };
        liveBroadcastContent?: string;
      };
      contentDetails?: { duration?: string };
      status?: { privacyStatus?: string };
      liveStreamingDetails?: unknown;
    }>;
  };

  return (vj.items ?? [])
    .filter((i) => i.id)
    .map((i) => {
      const durationIso8601 = i.contentDetails?.duration ?? null;
      const seconds = parseIsoDurationToSeconds(durationIso8601);
      const title = i.snippet?.title ?? "";
      const isShortHeuristic =
        /#shorts/i.test(title) || /#shorts/i.test(i.snippet?.description ?? "") || (seconds != null && seconds > 0 && seconds <= 60);
      return {
        videoId: i.id!,
        title,
        description: i.snippet?.description ?? "",
        publishedAt: i.snippet?.publishedAt ?? null,
        thumbnailUrl: i.snippet?.thumbnails?.high?.url ?? i.snippet?.thumbnails?.medium?.url ?? null,
        durationIso8601,
        privacyStatus: i.status?.privacyStatus ?? null,
        isShortHeuristic,
        isLive: (i.snippet?.liveBroadcastContent ?? "none") !== "none" || Boolean(i.liveStreamingDetails),
      };
    });
}
