/**
 * OpenAI Whisper fallback — only when no YouTube captions exist.
 * Always stores AI_GENERATED + REVIEW_REQUIRED. Never publishes.
 */

import { createReadStream, existsSync } from "node:fs";
import { formatOpenAIErrorForClient, getOpenAIClient, isOpenAIConfigured } from "@/lib/openai/client";
import { normalizeWhitespaceAndPunctuation } from "./normalize-transcript";
import {
  emptyWorkspace,
  loadWorkspaceRecord,
  saveWorkspaceRecord,
  type TranscriptWorkspaceRecord,
} from "./workspace-store";
import { flagProperNouns } from "./proper-noun-flags";
import { appendNotification } from "./notifications";

export async function transcribeAudioWithWhisper(absoluteAudioPath: string): Promise<
  { ok: true; text: string } | { ok: false; error: string }
> {
  if (!isOpenAIConfigured()) {
    return { ok: false, error: "OPENAI_API_KEY not configured." };
  }
  if (!existsSync(absoluteAudioPath)) {
    return { ok: false, error: "Audio file not found." };
  }
  try {
    const openai = getOpenAIClient();
    const result = await openai.audio.transcriptions.create({
      file: createReadStream(absoluteAudioPath),
      model: "whisper-1",
      response_format: "text",
    });
    const text = typeof result === "string" ? result : String(result);
    if (!text.trim()) return { ok: false, error: "Whisper returned empty transcript." };
    return { ok: true, text: text.trim() };
  } catch (err) {
    return { ok: false, error: formatOpenAIErrorForClient(err) };
  }
}

export async function applyAiFallbackTranscript(opts: {
  youtubeVideoId: string;
  absoluteAudioPath: string;
  author: string;
  repoRoot?: string;
}): Promise<TranscriptWorkspaceRecord> {
  const repoRoot = opts.repoRoot ?? process.cwd();
  const existing = loadWorkspaceRecord(opts.youtubeVideoId, repoRoot) ?? emptyWorkspace(opts.youtubeVideoId);
  if (existing.caption.downloadStatus === "DOWNLOADED" && existing.rawCaptionText?.trim()) {
    throw new Error("Captions already downloaded — AI fallback is only for videos with no captions.");
  }

  const result = await transcribeAudioWithWhisper(opts.absoluteAudioPath);
  if (!result.ok) {
    const failed = saveWorkspaceRecord(
      {
        ...existing,
        status: "FAILED",
        lastError: result.error,
      },
      { author: opts.author, reason: "AI fallback failed" },
      repoRoot,
    );
    appendNotification(
      {
        type: "CAPTION_FAILURE",
        youtubeVideoId: opts.youtubeVideoId,
        message: result.error,
      },
      repoRoot,
    );
    return failed;
  }

  const plainText = normalizeWhitespaceAndPunctuation(result.text);
  const segments = plainText
    .split(/\n{2,}/)
    .map((t, i) => ({ id: `seg-${i + 1}`, text: t.trim() }))
    .filter((s) => s.text);

  const next = saveWorkspaceRecord(
    {
      ...existing,
      status: "REVIEW_REQUIRED",
      source: "AI_GENERATED",
      isAutoGenerated: true,
      plainText,
      segments,
      flags: flagProperNouns(plainText),
      lastError: null,
      caption: {
        ...existing.caption,
        downloadStatus: existing.caption.downloadStatus === "FOUND" ? "FOUND" : "NONE",
        lastChecked: new Date().toISOString(),
      },
    },
    { author: opts.author, reason: "AI_GENERATED Whisper draft (requires human review)" },
    repoRoot,
  );

  appendNotification(
    {
      type: "AI_TRANSCRIPT_READY",
      youtubeVideoId: opts.youtubeVideoId,
      message: "AI draft ready for editorial review — not published.",
    },
    repoRoot,
  );

  return next;
}
