/**
 * YouTube → workspace sync pipeline.
 * Discovers videos, caption tracks, downloads + normalizes drafts.
 * NEVER publishes. NEVER overwrites editorial APPROVED/PUBLISHED workspace text without force.
 */

import {
  discoverChannelUploads,
  downloadCaptionTrack,
  listCaptionTracks,
  pickPreferredCaptionTrack,
} from "./captions-api";
import { normalizeCaptionToTranscript } from "./normalize-transcript";
import { flagProperNouns } from "./proper-noun-flags";
import { appendNotification } from "./notifications";
import { mapPipelineSourceKind } from "@/content/media/campaign-media-types";
import { getCampaignMediaByYoutubeId } from "@/content/media/campaign-media-registry";
import {
  emptyWorkspace,
  loadDiscoveredVideos,
  loadWorkspaceRecord,
  saveDiscoveredVideos,
  saveWorkspaceRecord,
  type DiscoveredVideosFile,
  type TranscriptWorkspaceRecord,
} from "./workspace-store";

export type SyncResult = {
  discovered: number;
  captionChecked: number;
  downloaded: number;
  missingCaptions: number;
  needingReview: number;
  errors: string[];
  lastSyncAt: string;
};

function editorialLocked(ws: TranscriptWorkspaceRecord | null): boolean {
  if (!ws) return false;
  return ws.status === "APPROVED" || ws.status === "PUBLISHED" || Boolean(ws.reviewedAt);
}

export async function syncYouTubeTranscriptPipeline(opts?: {
  maxVideos?: number;
  downloadCaptions?: boolean;
  author?: string;
  repoRoot?: string;
}): Promise<SyncResult> {
  const repoRoot = opts?.repoRoot ?? process.cwd();
  const author = opts?.author ?? "system:youtube-sync";
  const downloadCaptions = opts?.downloadCaptions !== false;
  const errors: string[] = [];
  let downloaded = 0;
  let captionChecked = 0;
  let missingCaptions = 0;

  const uploads = await discoverChannelUploads({
    maxResults: opts?.maxVideos ?? 25,
    repoRoot,
  });

  const prior = loadDiscoveredVideos(repoRoot);
  const byId = new Map(prior.videos.map((v) => [v.videoId, v]));

  for (const v of uploads) {
    const existing = byId.get(v.videoId);
    const registry = getCampaignMediaByYoutubeId(v.videoId);
    byId.set(v.videoId, {
      videoId: v.videoId,
      title: existing?.editorialLockedTitle ? existing.title : v.title,
      description: existing?.editorialLockedTitle ? existing.description : v.description,
      publishedAt: v.publishedAt,
      thumbnailUrl: v.thumbnailUrl,
      durationIso8601: v.durationIso8601,
      privacyStatus: v.privacyStatus,
      isShort: v.isShortHeuristic,
      isLive: v.isLive,
      playlist: existing?.playlist ?? null,
      transcriptState: existing?.transcriptState ?? "NOT_REQUESTED",
      captionStatus: existing?.captionStatus ?? "NOT_CHECKED",
      editorialLockedTitle: existing?.editorialLockedTitle ?? Boolean(registry),
    });
  }

  for (const v of byId.values()) {
    if (!downloadCaptions) continue;
    captionChecked += 1;
    try {
      let ws = loadWorkspaceRecord(v.videoId, repoRoot) ?? emptyWorkspace(v.videoId, v.title);
      if (editorialLocked(ws) && ws.plainText.trim()) {
        v.transcriptState = ws.status;
        v.captionStatus = ws.caption.downloadStatus ?? "DOWNLOADED";
        continue;
      }

      ws = saveWorkspaceRecord(
        {
          ...ws,
          title: ws.title ?? v.title,
          status: ws.status === "NOT_REQUESTED" ? "DISCOVERED" : ws.status,
          caption: { ...ws.caption, lastChecked: new Date().toISOString(), downloadStatus: "NOT_CHECKED" },
        },
        { author, reason: "Discovery sync", createRevision: false },
        repoRoot,
      );

      const tracks = await listCaptionTracks(v.videoId, repoRoot);
      const preferred = pickPreferredCaptionTrack(tracks);
      if (!preferred) {
        missingCaptions += 1;
        ws = saveWorkspaceRecord(
          {
            ...ws,
            status: "UNAVAILABLE",
            caption: {
              ...ws.caption,
              downloadStatus: "NONE",
              lastChecked: new Date().toISOString(),
            },
            lastError: null,
          },
          { author, reason: "No captions found" },
          repoRoot,
        );
        v.transcriptState = ws.status;
        v.captionStatus = "NONE";
        continue;
      }

      ws = saveWorkspaceRecord(
        {
          ...ws,
          status: "DOWNLOADING",
          caption: {
            captionTrackId: preferred.id,
            captionLanguage: preferred.language,
            captionKind: preferred.trackKind,
            isAutoGenerated: preferred.isAutoGenerated,
            lastChecked: new Date().toISOString(),
            downloadStatus: "FOUND",
          },
        },
        { author, reason: "Caption track discovered", createRevision: false },
        repoRoot,
      );

      const raw = await downloadCaptionTrack(preferred.id, { tfmt: "vtt", repoRoot });
      const { segments, plainText } = normalizeCaptionToTranscript(raw);
      const source = preferred.isAutoGenerated
        ? mapPipelineSourceKind("YOUTUBE_AUTO")
        : mapPipelineSourceKind("CREATOR");

      ws = saveWorkspaceRecord(
        {
          ...ws,
          status: "REVIEW_REQUIRED",
          source,
          isAutoGenerated: preferred.isAutoGenerated,
          language: preferred.language.startsWith("en") ? "en-US" : preferred.language,
          plainText,
          segments,
          rawCaptionText: raw,
          flags: flagProperNouns(plainText),
          lastError: null,
          caption: {
            ...ws.caption,
            downloadStatus: "DOWNLOADED",
            lastChecked: new Date().toISOString(),
          },
        },
        { author, reason: "Downloaded + normalized captions (draft — not published)" },
        repoRoot,
      );
      downloaded += 1;
      v.transcriptState = ws.status;
      v.captionStatus = "DOWNLOADED";
      appendNotification(
        {
          type: "NEW_TRANSCRIPT",
          youtubeVideoId: v.videoId,
          message: `Draft transcript ready for review (${preferred.isAutoGenerated ? "auto" : "creator"} captions).`,
        },
        repoRoot,
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`${v.videoId}: ${msg}`);
      const ws = loadWorkspaceRecord(v.videoId, repoRoot) ?? emptyWorkspace(v.videoId, v.title);
      saveWorkspaceRecord(
        {
          ...ws,
          status: "FAILED",
          lastError: msg,
          caption: { ...ws.caption, downloadStatus: "FAILED", lastChecked: new Date().toISOString() },
        },
        { author, reason: "Caption sync failure" },
        repoRoot,
      );
      v.transcriptState = "FAILED";
      v.captionStatus = "FAILED";
      appendNotification(
        { type: "CAPTION_FAILURE", youtubeVideoId: v.videoId, message: msg },
        repoRoot,
      );
    }
  }

  const lastSyncAt = new Date().toISOString();
  const file: DiscoveredVideosFile = {
    version: 1,
    lastSyncAt,
    videos: [...byId.values()],
  };
  saveDiscoveredVideos(file, repoRoot);

  const needingReview = file.videos.filter((v) => v.transcriptState === "REVIEW_REQUIRED").length;
  appendNotification(
    {
      type: "SYNC_COMPLETE",
      message: `Sync complete: ${uploads.length} discovered, ${downloaded} downloaded, ${needingReview} need review.`,
    },
    repoRoot,
  );

  return {
    discovered: uploads.length,
    captionChecked,
    downloaded,
    missingCaptions,
    needingReview,
    errors,
    lastSyncAt,
  };
}
