/**
 * File-backed transcript workspace + version history (Pass 2).
 * Never auto-publishes. Public overlays are written only via explicit publish().
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type {
  CampaignTranscript,
  TranscriptSegment,
  TranscriptSource,
  TranscriptStatus,
} from "@/content/media/campaign-media-types";
import type { ProperNounFlag } from "./proper-noun-flags";

export const WORKSPACE_REL = "data/campaign-media/transcript-pipeline";
export const VERSIONS_DIR = "versions";
export const DISCOVERY_FILE = "discovered-videos.json";
export const NOTIFICATIONS_FILE = "notifications.json";
export const ANALYTICS_FILE = "analytics-events.jsonl";
export const SEARCH_INDEX_FILE = "search-index.json";
export const AI_ADVISORY_DIR = "ai-advisory";

export type CaptionDiscoveryMeta = {
  captionLanguage?: string;
  captionTrackId?: string;
  captionKind?: string;
  isAutoGenerated?: boolean;
  lastChecked?: string;
  downloadStatus?: "NOT_CHECKED" | "FOUND" | "DOWNLOADED" | "FAILED" | "NONE";
};

export type TranscriptRevision = {
  revisionId: string;
  author: string;
  date: string;
  reason: string;
  plainText: string;
  segments: TranscriptSegment[];
  status: TranscriptStatus;
  source: TranscriptSource;
};

export type TranscriptWorkspaceRecord = {
  youtubeVideoId: string;
  mediaId?: string;
  title?: string;
  status: TranscriptStatus;
  source: TranscriptSource;
  language: string;
  isAutoGenerated: boolean;
  plainText: string;
  segments: TranscriptSegment[];
  rawCaptionText?: string;
  caption: CaptionDiscoveryMeta;
  flags: ProperNounFlag[];
  chapters: Array<{ id: string; title: string; startSeconds: number }>;
  editorialNotes?: string;
  lastError?: string | null;
  createdAt: string;
  updatedAt: string;
  reviewedAt?: string;
  reviewedBy?: string;
  approvedAt?: string;
  approvedBy?: string;
  revisions: TranscriptRevision[];
};

export type DiscoveredVideosFile = {
  version: number;
  lastSyncAt: string | null;
  videos: Array<{
    videoId: string;
    title: string;
    description: string;
    publishedAt: string | null;
    thumbnailUrl: string | null;
    durationIso8601: string | null;
    privacyStatus: string | null;
    isShort: boolean;
    isLive: boolean;
    playlist?: string | null;
    transcriptState: TranscriptStatus;
    captionStatus: CaptionDiscoveryMeta["downloadStatus"];
    editorialLockedTitle?: boolean;
  }>;
};

function rootAbs(repoRoot: string): string {
  return path.join(repoRoot, WORKSPACE_REL);
}

function workspacePath(youtubeVideoId: string, repoRoot: string): string {
  return path.join(rootAbs(repoRoot), "workspace", `${youtubeVideoId}.json`);
}

function ensureDir(p: string): void {
  mkdirSync(p, { recursive: true });
}

export function loadDiscoveredVideos(repoRoot: string = process.cwd()): DiscoveredVideosFile {
  const abs = path.join(rootAbs(repoRoot), DISCOVERY_FILE);
  if (!existsSync(abs)) {
    return { version: 1, lastSyncAt: null, videos: [] };
  }
  return JSON.parse(readFileSync(abs, "utf8")) as DiscoveredVideosFile;
}

export function saveDiscoveredVideos(file: DiscoveredVideosFile, repoRoot: string = process.cwd()): void {
  const abs = path.join(rootAbs(repoRoot), DISCOVERY_FILE);
  ensureDir(path.dirname(abs));
  writeFileSync(abs, `${JSON.stringify(file, null, 2)}\n`, "utf8");
}

export function loadWorkspaceRecord(
  youtubeVideoId: string,
  repoRoot: string = process.cwd(),
): TranscriptWorkspaceRecord | null {
  const abs = workspacePath(youtubeVideoId, repoRoot);
  if (!existsSync(abs)) return null;
  return JSON.parse(readFileSync(abs, "utf8")) as TranscriptWorkspaceRecord;
}

export function listWorkspaceRecords(repoRoot: string = process.cwd()): TranscriptWorkspaceRecord[] {
  const dir = path.join(rootAbs(repoRoot), "workspace");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(path.join(dir, f), "utf8")) as TranscriptWorkspaceRecord);
}

export function saveWorkspaceRecord(
  record: TranscriptWorkspaceRecord,
  opts: { author: string; reason: string; createRevision?: boolean },
  repoRoot: string = process.cwd(),
): TranscriptWorkspaceRecord {
  const now = new Date().toISOString();
  const createRevision = opts.createRevision !== false;
  const next: TranscriptWorkspaceRecord = {
    ...record,
    updatedAt: now,
  };
  if (createRevision) {
    const revision: TranscriptRevision = {
      revisionId: `rev-${Date.now()}`,
      author: opts.author,
      date: now,
      reason: opts.reason,
      plainText: next.plainText,
      segments: next.segments,
      status: next.status,
      source: next.source,
    };
    next.revisions = [...(next.revisions ?? []), revision].slice(-50);
    const verDir = path.join(rootAbs(repoRoot), VERSIONS_DIR, next.youtubeVideoId);
    ensureDir(verDir);
    writeFileSync(path.join(verDir, `${revision.revisionId}.json`), `${JSON.stringify(revision, null, 2)}\n`, "utf8");
  }
  const abs = workspacePath(next.youtubeVideoId, repoRoot);
  ensureDir(path.dirname(abs));
  writeFileSync(abs, `${JSON.stringify(next, null, 2)}\n`, "utf8");
  return next;
}

export function restoreRevision(
  youtubeVideoId: string,
  revisionId: string,
  author: string,
  repoRoot: string = process.cwd(),
): TranscriptWorkspaceRecord {
  const current = loadWorkspaceRecord(youtubeVideoId, repoRoot);
  if (!current) throw new Error(`No workspace record for ${youtubeVideoId}`);
  const rev =
    current.revisions.find((r) => r.revisionId === revisionId) ??
    (() => {
      const abs = path.join(rootAbs(repoRoot), VERSIONS_DIR, youtubeVideoId, `${revisionId}.json`);
      if (!existsSync(abs)) return null;
      return JSON.parse(readFileSync(abs, "utf8")) as TranscriptRevision;
    })();
  if (!rev) throw new Error(`Revision not found: ${revisionId}`);
  return saveWorkspaceRecord(
    {
      ...current,
      plainText: rev.plainText,
      segments: rev.segments,
      status: "DRAFT",
      source: rev.source,
    },
    { author, reason: `Restored ${revisionId}` },
    repoRoot,
  );
}

export function workspaceToCampaignTranscript(ws: TranscriptWorkspaceRecord): CampaignTranscript {
  return {
    status: ws.status,
    source: ws.source,
    language: ws.language,
    isAutoGenerated: ws.isAutoGenerated,
    reviewedAt: ws.reviewedAt,
    reviewedBy: ws.reviewedBy,
    approvedAt: ws.approvedAt,
    approvedBy: ws.approvedBy,
    lastUpdatedAt: ws.updatedAt,
    plainText: ws.plainText,
    segments: ws.segments,
  };
}

export function emptyWorkspace(youtubeVideoId: string, title?: string): TranscriptWorkspaceRecord {
  const now = new Date().toISOString();
  return {
    youtubeVideoId,
    title,
    status: "NOT_REQUESTED",
    source: "UNKNOWN",
    language: "en-US",
    isAutoGenerated: false,
    plainText: "",
    segments: [],
    caption: { downloadStatus: "NOT_CHECKED" },
    flags: [],
    chapters: [],
    createdAt: now,
    updatedAt: now,
    revisions: [],
    lastError: null,
  };
}
