/**
 * Development/test-only transcript fixture — NOT Kelly’s words.
 * Never import into the production registry. Used only by Pass 1 tests.
 */
import type { CampaignMediaRecord } from "@/content/media/campaign-media-types";

export const TRANSCRIPT_SYSTEM_DEMO_FIXTURE: CampaignMediaRecord = {
  id: "__transcript_system_demo__",
  slug: "__transcript-system-demo__",
  provider: "YOUTUBE",
  youtubeVideoId: "dQw4w9WgXcQ",
  format: "FULL_VIDEO",
  title: "Transcript System Demo (Not Campaign Content)",
  description: "Synthetic fixture for validating transcript disclosure and VideoObject wiring.",
  summary: "Test fixture only — excluded from public registry.",
  topics: ["Accessibility", "Transcripts"],
  relatedPagePaths: ["/kelly-speaks"],
  featured: false,
  homepageEligible: false,
  publicationStatus: "PUBLISHED",
  thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
  transcript: {
    status: "PUBLISHED",
    source: "MANUAL",
    language: "en-US",
    isAutoGenerated: false,
    reviewedAt: "2026-07-28T00:00:00.000Z",
    reviewedBy: "pass1-test-fixture",
    approvedAt: "2026-07-28T00:00:00.000Z",
    approvedBy: "pass1-test-fixture",
    plainText:
      "This is a synthetic transcript used only to prove the transcript disclosure renders server-side text. It is not a campaign speech.",
    segments: [
      {
        id: "seg-1",
        startSeconds: 0,
        speaker: "System",
        text: "This is a synthetic transcript used only to prove the transcript disclosure renders server-side text.",
      },
      {
        id: "seg-2",
        startSeconds: 12,
        speaker: "System",
        text: "It is not a campaign speech and must never be published as Kelly Grappe content.",
      },
    ],
  },
};
