import type { CampaignSection, CampaignSectionId } from "./cross-domain-orchestrator-types";

const noAutoComms = ["auto_send_email", "auto_send_sms", "contact_export"];
const noFinance = ["finance_post", "reimbursement_submit"];

export const CAMPAIGN_SECTION_MAP: CampaignSection[] = [
  {
    id: "executive_command",
    label: "Executive Command",
    mission: "Keep the campaign manager focused on blockers, opportunities, safety gates, and daily cross-domain priorities.",
    ownedDomains: ["campaign_management", "approvals", "dashboard_ux"],
    routePaths: ["/admin/orchestration", "/admin/ai-command-center"],
    apiPaths: ["/api/agents/orchestration-state"],
    sourcePaths: ["src/lib/agents/orchestration/build-orchestration-payload.ts"],
    primaryTools: ["campaign-state-loader", "orchestration-reasoning-engine", "orchestration-workflow-planner"],
    relatedTools: ["campaign-manager-daily", "orchestration-tooling-state"],
    upstreamDependencies: ["memory_observations", "deployment_readiness"],
    downstreamDependencies: ["county_intelligence", "communications", "finance_reimbursement", "tool_builder"],
    sourceHealthIds: ["os_control", "campaign_knowledge", "agent_tooling"],
    campaignStateFields: ["overallHealth", "activeBlockers", "topMoves", "recommendedWorkflows"],
    knowledgeGraphEntityTypes: ["domain", "blocker", "opportunity", "workflow"],
    humanOwners: ["campaign_manager"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Synthesizes the full map so the AI knows which section deserves attention first.",
  },
  {
    id: "county_intelligence",
    label: "County Intelligence",
    mission: "Turn county posture into field, event, comms, content, and fundraising decisions.",
    ownedDomains: ["county", "field"],
    routePaths: ["/admin/county-intelligence"],
    apiPaths: [],
    sourcePaths: ["src/lib/agents/county-intelligence"],
    primaryTools: ["county-intelligence-bridge", "county-action-package-builder"],
    relatedTools: ["campaign-knowledge-graph-builder", "county-memory-enricher"],
    upstreamDependencies: ["memory_observations", "research_strategy"],
    downstreamDependencies: ["events_calendar", "volunteer_field", "communications", "content_media", "donor_fundraising"],
    sourceHealthIds: ["county_intelligence"],
    campaignStateFields: ["countyHealth", "countyIntelligenceSummary", "countyActions"],
    knowledgeGraphEntityTypes: ["county", "person", "organization", "event", "lesson"],
    humanOwners: ["field_manager", "campaign_manager"],
    restrictedActions: ["voter_export", "contact_export", "sensitive_memory_auto_store"],
    improvesCampaignUnderstandingHow: "Explains where the campaign has traction or gaps by place, which unlocks every local action.",
  },
  {
    id: "communications",
    label: "Communications",
    mission: "Convert campaign intelligence into safe, audience-aware messaging plans.",
    ownedDomains: ["communications", "social_media"],
    routePaths: ["/admin/communications", "/admin/communications/intelligence"],
    apiPaths: [],
    sourcePaths: ["src/lib/communications"],
    primaryTools: ["communications-intelligence-engine", "message-sequence-planner"],
    relatedTools: ["email-os-agent-router", "relationship-memory-review"],
    upstreamDependencies: ["county_intelligence", "events_calendar", "research_strategy"],
    downstreamDependencies: ["email_os_ecc", "volunteer_field", "content_media", "public_site"],
    sourceHealthIds: ["communications"],
    campaignStateFields: ["communicationsHealth", "commsReadiness", "communicationActions"],
    knowledgeGraphEntityTypes: ["message", "person", "organization", "lesson"],
    humanOwners: ["communications_director", "campaign_manager"],
    restrictedActions: noAutoComms,
    improvesCampaignUnderstandingHow: "Shows which messages, follow-ups, and audience risks shape turnout and volunteer behavior.",
  },
  {
    id: "email_os_ecc",
    label: "Email OS / ECC",
    mission: "Prepare safe email operations while keeping all send decisions human-gated.",
    ownedDomains: ["communications", "approvals"],
    routePaths: ["/admin/communications/email", "/admin/communications/ecc"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events/ai-tools/sprint-email-os-agent-tools.ts"],
    primaryTools: ["email-os-readiness-checker", "ecc-human-approval-packet"],
    relatedTools: ["communications-intelligence-engine"],
    upstreamDependencies: ["communications", "compliance"],
    downstreamDependencies: ["volunteer_field", "events_calendar", "public_site"],
    sourceHealthIds: ["email_ecc"],
    campaignStateFields: ["emailEccReadiness", "commsReadiness"],
    knowledgeGraphEntityTypes: ["message", "workflow", "risk"],
    humanOwners: ["communications_director"],
    restrictedActions: noAutoComms,
    improvesCampaignUnderstandingHow: "Separates message prep from send approval so email outcomes can teach the map without unsafe automation.",
  },
  {
    id: "events_calendar",
    label: "Events + Calendar",
    mission: "Coordinate event readiness, calendar truth, county visit prep, and post-event learning.",
    ownedDomains: ["calendar", "event_planning", "approvals", "host", "hot_wash"],
    routePaths: ["/admin/campaign-events/workbench", "/admin/campaign-calendar", "/admin/campaign-events/review"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events"],
    primaryTools: ["event-readiness-builder", "calendar-sync-health", "hot-wash-intelligence"],
    relatedTools: ["county-action-package-builder", "communications-sequence-plan"],
    upstreamDependencies: ["county_intelligence", "scheduling", "finance_reimbursement"],
    downstreamDependencies: ["volunteer_field", "communications", "content_media", "memory_observations"],
    sourceHealthIds: ["calendar_events"],
    campaignStateFields: ["eventReadiness", "calendarEventPressure", "eventActions"],
    knowledgeGraphEntityTypes: ["event", "county", "person", "lesson", "observation"],
    humanOwners: ["scheduler", "event_lead", "campaign_manager"],
    restrictedActions: ["google_calendar_write", "production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Connects where Kelly goes, who is involved, what was learned, and what follow-up is needed.",
  },
  {
    id: "volunteer_field",
    label: "Volunteer + Field",
    mission: "Turn priorities into volunteer assignments and field follow-up without exporting contacts.",
    ownedDomains: ["volunteer", "field", "county"],
    routePaths: ["/admin/volunteers", "/admin/county-intelligence"],
    apiPaths: [],
    sourcePaths: ["src/lib/volunteers", "src/lib/agents/county-intelligence"],
    primaryTools: ["volunteer-system", "field-priority-orchestrator"],
    relatedTools: ["county-intelligence-bridge", "communications-intelligence-engine"],
    upstreamDependencies: ["county_intelligence", "events_calendar", "communications"],
    downstreamDependencies: ["memory_observations", "training_copilots"],
    sourceHealthIds: ["volunteer"],
    campaignStateFields: ["volunteerHealth", "volunteerActions"],
    knowledgeGraphEntityTypes: ["volunteer", "task", "county", "workflow"],
    humanOwners: ["field_manager", "volunteer_coordinator"],
    restrictedActions: ["voter_export", "contact_export", "auto_send_sms"],
    improvesCampaignUnderstandingHow: "Shows whether recommendations translate into staffed events, useful outreach, and field momentum.",
  },
  {
    id: "finance_reimbursement",
    label: "Finance + Reimbursement",
    mission: "Prepare review packets for costs, mileage, and reimbursement without posting or submitting anything.",
    ownedDomains: ["finance", "reimbursement", "travel"],
    routePaths: ["/admin/campaign-events/finance", "/admin/campaign-events/reimbursement", "/admin/campaign-events/travel"],
    apiPaths: [],
    sourcePaths: ["src/lib/finance", "src/lib/campaign-events/reimbursement"],
    primaryTools: ["finance-event-fusion", "reimbursement-packet-builder"],
    relatedTools: ["compliance-gap-workflow"],
    upstreamDependencies: ["events_calendar", "scheduling"],
    downstreamDependencies: ["compliance", "executive_command"],
    sourceHealthIds: ["finance", "reimbursement"],
    campaignStateFields: ["financeHealth", "reimbursementReadiness", "financeComplianceWarnings"],
    knowledgeGraphEntityTypes: ["issue", "workflow", "risk", "document"],
    humanOwners: ["treasurer", "campaign_manager"],
    restrictedActions: noFinance,
    improvesCampaignUnderstandingHow: "Reveals operational cost blockers before they become compliance or scheduling problems.",
  },
  {
    id: "compliance",
    label: "Compliance",
    mission: "Keep filing, receipt, approval, and risk workflows visible and human-owned.",
    ownedDomains: ["compliance", "approvals"],
    routePaths: ["/admin/compliance"],
    apiPaths: [],
    sourcePaths: ["src/lib/compliance"],
    primaryTools: ["compliance-readiness-checker", "receipt-gap-detector"],
    relatedTools: ["finance-event-fusion", "ecc-human-approval-packet"],
    upstreamDependencies: ["finance_reimbursement", "email_os_ecc"],
    downstreamDependencies: ["deployment_readiness", "executive_command"],
    sourceHealthIds: ["compliance"],
    campaignStateFields: ["complianceReadiness", "financeComplianceWarnings"],
    knowledgeGraphEntityTypes: ["risk", "document", "issue"],
    humanOwners: ["treasurer", "compliance_lead"],
    restrictedActions: ["finance_post", "reimbursement_submit", "production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Tells the AI which recommendations are unsafe or incomplete until compliance evidence is reviewed.",
  },
  {
    id: "content_media",
    label: "Content + Media",
    mission: "Prepare content/media packets from events, county intelligence, and campaign narrative.",
    ownedDomains: ["social_media", "communications", "hot_wash"],
    routePaths: ["/admin/communications", "/admin/campaign-events/media"],
    apiPaths: [],
    sourcePaths: ["src/lib/social", "src/lib/communications"],
    primaryTools: ["content-recap-builder", "media-moment-detector"],
    relatedTools: ["hot-wash-intelligence", "communications-intelligence-engine"],
    upstreamDependencies: ["events_calendar", "communications", "research_strategy"],
    downstreamDependencies: ["public_site", "donor_fundraising", "memory_observations"],
    sourceHealthIds: ["communications"],
    campaignStateFields: ["communicationActions"],
    knowledgeGraphEntityTypes: ["media_item", "message", "event", "lesson"],
    humanOwners: ["communications_director"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Captures which public moments and narratives are worth repeating or correcting.",
  },
  {
    id: "donor_fundraising",
    label: "Donor + Fundraising",
    mission: "Connect county, event, and comms signals to donor follow-up opportunities without financial posting.",
    ownedDomains: ["finance", "communications", "event_planning"],
    routePaths: ["/admin/campaign-events/finance"],
    apiPaths: [],
    sourcePaths: ["src/lib/finance"],
    primaryTools: ["donor-followup-opportunity-detector"],
    relatedTools: ["event-intelligence-playbook", "communications-sequence-plan"],
    upstreamDependencies: ["events_calendar", "content_media", "communications"],
    downstreamDependencies: ["finance_reimbursement", "executive_command"],
    sourceHealthIds: ["finance"],
    campaignStateFields: ["financeHealth", "activeOpportunities"],
    knowledgeGraphEntityTypes: ["donor", "event", "opportunity"],
    humanOwners: ["finance_director", "campaign_manager"],
    restrictedActions: ["finance_post", "contact_export"],
    improvesCampaignUnderstandingHow: "Identifies where momentum or events create fundraising context the campaign should not miss.",
  },
  {
    id: "scheduling",
    label: "Scheduling",
    mission: "Coordinate candidate time, travel, approvals, and event readiness.",
    ownedDomains: ["calendar", "travel", "candidate"],
    routePaths: ["/admin/campaign-calendar", "/admin/campaign-events/travel"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events/calendar"],
    primaryTools: ["calendar-sync-health", "travel-ledger-review"],
    relatedTools: ["candidate-briefing", "event-readiness-builder"],
    upstreamDependencies: ["executive_command", "county_intelligence"],
    downstreamDependencies: ["events_calendar", "finance_reimbursement", "compliance"],
    sourceHealthIds: ["calendar_events"],
    campaignStateFields: ["calendarEventPressure", "candidateReadiness"],
    knowledgeGraphEntityTypes: ["event", "person", "workflow"],
    humanOwners: ["scheduler", "campaign_manager"],
    restrictedActions: ["google_calendar_write"],
    improvesCampaignUnderstandingHow: "Shows where time, travel, and approvals constrain the campaign plan.",
  },
  {
    id: "research_strategy",
    label: "Research + Strategy",
    mission: "Convert issues, risks, and opportunities into sourced strategic context.",
    ownedDomains: ["campaign_management", "candidate", "communications"],
    routePaths: ["/admin/ai-command-center"],
    apiPaths: [],
    sourcePaths: ["src/lib/agents/orchestration/knowledge"],
    primaryTools: ["campaign-lessons-engine", "knowledge-gap-detector"],
    relatedTools: ["orchestration-reasoning-engine"],
    upstreamDependencies: ["memory_observations", "executive_command"],
    downstreamDependencies: ["communications", "county_intelligence", "executive_command"],
    sourceHealthIds: ["campaign_knowledge"],
    campaignStateFields: ["knowledge", "activeOpportunities", "topRisks"],
    knowledgeGraphEntityTypes: ["issue", "risk", "opportunity", "lesson"],
    humanOwners: ["campaign_manager", "candidate"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Distinguishes sourced campaign learning from guesses and flags under-informed strategy areas.",
  },
  {
    id: "ask_kelly",
    label: "Ask Kelly",
    mission: "Route candidate-facing questions into safe briefing and knowledge gap prompts.",
    ownedDomains: ["candidate", "communications", "training"],
    routePaths: ["/admin/ask-kelly", "/admin/ai-command-center/copilots"],
    apiPaths: [],
    sourcePaths: ["src/lib/agents"],
    primaryTools: ["candidate-copilot-briefing", "ask-kelly-question-router"],
    relatedTools: ["campaign-knowledge-state"],
    upstreamDependencies: ["research_strategy", "memory_observations"],
    downstreamDependencies: ["training_copilots", "communications"],
    sourceHealthIds: ["candidate"],
    campaignStateFields: ["candidateReadiness", "knowledge"],
    knowledgeGraphEntityTypes: ["person", "document", "lesson"],
    humanOwners: ["candidate", "campaign_manager"],
    restrictedActions: noAutoComms,
    improvesCampaignUnderstandingHow: "Turns candidate questions into gaps, briefing needs, and reusable lessons.",
  },
  {
    id: "tool_builder",
    label: "Tool Builder",
    mission: "Turn friction, missing intelligence, and repeated manual work into prioritized tool tickets.",
    ownedDomains: ["tool_builder", "dashboard_ux"],
    routePaths: ["/admin/ai-command-center/tool-builder"],
    apiPaths: ["/api/agents/tool-builder-queue"],
    sourcePaths: ["src/lib/agents/tool-builder"],
    primaryTools: ["tool-gap-detector", "tool-builder-queue"],
    relatedTools: ["agent-tool-coverage", "feedback-learning-engine"],
    upstreamDependencies: ["memory_observations", "executive_command"],
    downstreamDependencies: ["deployment_readiness", "executive_command"],
    sourceHealthIds: ["tool_builder"],
    campaignStateFields: ["toolBuildActions", "toolCoverage", "agentTooling"],
    knowledgeGraphEntityTypes: ["tool", "issue", "lesson"],
    humanOwners: ["campaign_manager", "developer"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Shows which missing tools would most improve campaign visibility and reduce repeated friction.",
  },
  {
    id: "training_copilots",
    label: "Training + Copilots",
    mission: "Map role readiness, training gaps, and copilot support to campaign execution.",
    ownedDomains: ["training", "candidate", "dashboard_ux"],
    routePaths: ["/admin/training", "/admin/ai-command-center/copilots"],
    apiPaths: [],
    sourcePaths: ["src/lib/training", "src/lib/agents"],
    primaryTools: ["training-gap-router", "role-copilot-briefing"],
    relatedTools: ["dashboard-simplification-planner"],
    upstreamDependencies: ["volunteer_field", "ask_kelly"],
    downstreamDependencies: ["executive_command", "deployment_readiness"],
    sourceHealthIds: ["training"],
    campaignStateFields: ["trainingHealth", "trainingActions"],
    knowledgeGraphEntityTypes: ["person", "task", "lesson"],
    humanOwners: ["training_lead", "campaign_manager"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Connects human readiness to why workflows stall or succeed.",
  },
  {
    id: "memory_observations",
    label: "Memory + Observations",
    mission: "Capture observations, feedback, lessons, and approved memory without unsafe auto-promotion.",
    ownedDomains: ["memory", "hot_wash", "campaign_management"],
    routePaths: ["/admin/orchestration"],
    apiPaths: ["/api/agents/campaign-knowledge-state", "/api/agents/orchestration-feedback", "/api/agents/lesson-approvals"],
    sourcePaths: ["src/lib/agents/orchestration/knowledge", "src/lib/agents/orchestration/feedback"],
    primaryTools: ["campaign-observation-intake", "campaign-lessons-engine", "feedback-learning-engine"],
    relatedTools: ["memory-review-store", "knowledge-graph-builder"],
    upstreamDependencies: ["executive_command", "events_calendar", "volunteer_field"],
    downstreamDependencies: ["research_strategy", "tool_builder", "executive_command"],
    sourceHealthIds: ["campaign_knowledge"],
    campaignStateFields: ["knowledge", "feedbackLoop", "memoryObservationSummary"],
    knowledgeGraphEntityTypes: ["observation", "lesson", "recommendation", "outcome"],
    humanOwners: ["campaign_manager"],
    restrictedActions: ["sensitive_memory_auto_store"],
    improvesCampaignUnderstandingHow: "Turns outcomes and observations into the durable campaign map, with approval gates.",
  },
  {
    id: "public_site",
    label: "Public Site",
    mission: "Keep public-facing campaign surfaces aligned with approved narrative and deployment safety.",
    ownedDomains: ["communications", "dashboard_ux"],
    routePaths: ["/"],
    apiPaths: [],
    sourcePaths: ["src/app", "src/components"],
    primaryTools: ["public-route-health-check", "content-readiness-review"],
    relatedTools: ["deployment-readiness-playbook"],
    upstreamDependencies: ["content_media", "compliance", "deployment_readiness"],
    downstreamDependencies: ["communications", "donor_fundraising"],
    sourceHealthIds: ["deployment"],
    campaignStateFields: ["dashboardHealth", "communicationActions"],
    knowledgeGraphEntityTypes: ["document", "message", "risk"],
    humanOwners: ["communications_director", "developer"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Shows whether public narrative and site readiness match current campaign truth.",
  },
  {
    id: "deployment_readiness",
    label: "Deployment Readiness",
    mission: "Verify tests, typecheck, build, migrations, docs, and route health before shipping.",
    ownedDomains: ["dashboard_ux", "tool_builder", "compliance"],
    routePaths: ["/admin/orchestration"],
    apiPaths: [],
    sourcePaths: ["package.json", "scripts", "prisma/migrations"],
    primaryTools: ["test-runner", "typecheck", "next-build", "prisma-migrate-status"],
    relatedTools: ["release-gate-report"],
    upstreamDependencies: ["tool_builder", "public_site"],
    downstreamDependencies: ["executive_command", "public_site"],
    sourceHealthIds: ["deployment"],
    campaignStateFields: ["signalLoadErrors", "systemRisk"],
    knowledgeGraphEntityTypes: ["tool", "risk", "document"],
    humanOwners: ["developer", "campaign_manager"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Tells the agent whether the campaign map can safely become shipped operator reality.",
  },
];

export const REQUIRED_CAMPAIGN_SECTION_IDS: CampaignSectionId[] = [
  "executive_command",
  "county_intelligence",
  "communications",
  "email_os_ecc",
  "events_calendar",
  "volunteer_field",
  "finance_reimbursement",
  "compliance",
  "content_media",
  "donor_fundraising",
  "scheduling",
  "research_strategy",
  "ask_kelly",
  "tool_builder",
  "training_copilots",
  "memory_observations",
  "public_site",
  "deployment_readiness",
];

export function getCampaignSection(id: CampaignSectionId): CampaignSection {
  const section = CAMPAIGN_SECTION_MAP.find((s) => s.id === id);
  if (!section) throw new Error(`Unknown campaign section: ${id}`);
  return section;
}
