import type { CampaignSectionMapEntry } from "./cross-domain-orchestrator-types";

export const CAMPAIGN_SECTION_MAP: CampaignSectionMapEntry[] = [
  {
    id: "executive_command",
    label: "Executive Command",
    mission: "Keep the campaign manager oriented around the live campaign map, top blockers, risks, and safe next moves.",
    ownedDomains: ["campaign_management", "candidate", "dashboard_ux"],
    routePaths: ["/admin/orchestration", "/admin/ai-command-center", "/admin/campaign-manager-dashboard", "/admin/candidate-dashboard"],
    apiPaths: ["/api/agents/orchestration-state"],
    sourcePaths: ["src/lib/agents/orchestration/", "src/components/admin/orchestration/"],
    primaryTools: ["campaign-state-loader", "orchestration-reasoning-engine", "campaign-manager-daily-plan-builder"],
    relatedTools: ["campaign-priority-ranker", "campaign-risk-detector", "campaign-opportunity-detector"],
    upstreamDependencies: ["memory_observations", "deployment_readiness"],
    downstreamDependencies: ["county_intelligence", "communications", "finance_reimbursement", "compliance"],
    sourceHealthIds: ["os_control", "campaign_knowledge", "agent_tooling"],
    campaignStateFields: ["overallHealth", "activeBlockers", "activeOpportunities", "topMoves"],
    knowledgeGraphEntityTypes: ["domain", "blocker", "opportunity", "recommendation"],
    humanOwners: ["campaign_manager", "candidate"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Creates the single prioritized operating view that teaches the AI which domains matter now.",
  },
  {
    id: "county_intelligence",
    label: "County Intelligence",
    mission: "Translate county heat, gaps, and local signals into field, event, comms, and fundraising preparation.",
    ownedDomains: ["county", "field", "host"],
    routePaths: ["/admin/county-intelligence", "/admin/field-playbook"],
    apiPaths: [],
    sourcePaths: ["src/lib/agents/county-intelligence/", "src/lib/campaign-events/county-memory/"],
    primaryTools: ["field-priority-orchestrator", "county-volunteer-comms-fusion-engine"],
    relatedTools: ["county-to-event-calendar-router", "hotwash-to-county-strategy-router"],
    upstreamDependencies: ["memory_observations", "research_strategy"],
    downstreamDependencies: ["events_calendar", "volunteer_field", "communications", "content_media", "donor_fundraising"],
    sourceHealthIds: ["county_intelligence"],
    campaignStateFields: ["countyHealth", "countyIntelligenceSummary", "countyActions"],
    knowledgeGraphEntityTypes: ["county", "person", "organization", "opportunity", "lesson"],
    humanOwners: ["field_director", "campaign_manager"],
    restrictedActions: ["voter_export", "contact_export", "sensitive_memory_auto_store"],
    improvesCampaignUnderstandingHow: "Connects geography, people, events, and blockers so the AI knows where campaign attention compounds.",
  },
  {
    id: "communications",
    label: "Communications",
    mission: "Turn narrative, follow-up, fatigue, and audience signals into draft-only campaign communication plans.",
    ownedDomains: ["communications", "social_media"],
    routePaths: ["/admin/communications", "/admin/communications/intelligence", "/admin/workbench/communication-command-center/readiness"],
    apiPaths: [],
    sourcePaths: ["src/lib/communications/", "src/app/admin/(board)/communications/"],
    primaryTools: ["communications-priority-orchestrator", "communications-to-volunteer-retention-router"],
    relatedTools: ["campaign-risk-detector", "orchestration-human-gate-enforcer"],
    upstreamDependencies: ["county_intelligence", "events_calendar", "research_strategy"],
    downstreamDependencies: ["email_os_ecc", "volunteer_field", "content_media", "public_site"],
    sourceHealthIds: ["communications"],
    campaignStateFields: ["communicationsHealth", "commsReadiness", "communicationActions"],
    knowledgeGraphEntityTypes: ["message", "person", "organization", "issue", "lesson"],
    humanOwners: ["communications_director", "campaign_manager"],
    restrictedActions: ["auto_send_email", "auto_send_sms", "contact_export"],
    improvesCampaignUnderstandingHow: "Shows the AI which messages, audiences, and follow-ups are ready versus blocked.",
  },
  {
    id: "email_os_ecc",
    label: "Email OS / ECC",
    mission: "Prepare email readiness checks, audience review, and sandbox packets without sending.",
    ownedDomains: ["communications", "approvals"],
    routePaths: ["/admin/workbench/email-command-center/launch-room", "/admin/workbench/email-command-center/audiences", "/admin/workbench/communication-command-center/email-sandbox"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events/ai-tools/sprint-email-os-agent-tools.ts", "src/app/admin/(board)/workbench/email-command-center/"],
    primaryTools: ["communications-priority-orchestrator"],
    relatedTools: ["orchestration-autonomy-boundary-checker", "orchestration-human-gate-enforcer"],
    upstreamDependencies: ["communications", "compliance"],
    downstreamDependencies: ["volunteer_field", "events_calendar", "memory_observations"],
    sourceHealthIds: ["communications"],
    campaignStateFields: ["emailEccReadiness", "commsReadiness"],
    knowledgeGraphEntityTypes: ["message", "workflow", "risk", "observation"],
    humanOwners: ["communications_director"],
    restrictedActions: ["auto_send_email", "contact_export"],
    improvesCampaignUnderstandingHow: "Separates safe preparation from send risk so the AI knows whether outreach is blocked or review-ready.",
  },
  {
    id: "events_calendar",
    label: "Events + Calendar",
    mission: "Coordinate calendar truth, event readiness, approvals, volunteers, comms, and post-event learning.",
    ownedDomains: ["calendar", "event_planning", "approvals", "travel", "hot_wash"],
    routePaths: ["/admin/campaign-calendar", "/admin/campaign-events/workbench", "/admin/campaign-events/review", "/admin/campaign-events/travel"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events/", "src/app/admin/(board)/campaign-events/"],
    primaryTools: ["event-county-volunteer-planner", "county-to-event-calendar-router"],
    relatedTools: ["workflow-readiness-checker", "hotwash-to-county-strategy-router"],
    upstreamDependencies: ["county_intelligence", "scheduling", "finance_reimbursement"],
    downstreamDependencies: ["volunteer_field", "communications", "content_media", "memory_observations"],
    sourceHealthIds: ["calendar", "events"],
    campaignStateFields: ["eventReadiness", "calendarEventPressure", "eventActions"],
    knowledgeGraphEntityTypes: ["event", "county", "person", "workflow", "lesson"],
    humanOwners: ["scheduler", "campaign_manager"],
    restrictedActions: ["google_calendar_write", "production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Events reveal where field, volunteer, comms, and county strategy meet in real operations.",
  },
  {
    id: "volunteer_field",
    label: "Volunteer + Field",
    mission: "Prepare volunteer activation and field follow-up from county, event, and comms signals.",
    ownedDomains: ["volunteer", "field", "county"],
    routePaths: ["/admin/volunteers", "/admin/county-intelligence"],
    apiPaths: [],
    sourcePaths: ["src/lib/volunteers/", "src/lib/agents/county-intelligence/"],
    primaryTools: ["volunteer-workload-balancer", "field-priority-orchestrator"],
    relatedTools: ["communications-to-volunteer-retention-router", "event-county-volunteer-planner"],
    upstreamDependencies: ["county_intelligence", "communications", "events_calendar"],
    downstreamDependencies: ["memory_observations", "content_media"],
    sourceHealthIds: ["volunteer"],
    campaignStateFields: ["volunteerHealth", "volunteerActions", "commsReadiness.volunteerAtRisk"],
    knowledgeGraphEntityTypes: ["volunteer", "county", "task", "workflow", "lesson"],
    humanOwners: ["field_director", "volunteer_coordinator"],
    restrictedActions: ["voter_export", "contact_export"],
    improvesCampaignUnderstandingHow: "Connects people capacity to county and event needs so the AI learns what can actually be staffed.",
  },
  {
    id: "finance_reimbursement",
    label: "Finance + Reimbursement",
    mission: "Prepare finance, travel, and reimbursement review packets without posting or submitting anything.",
    ownedDomains: ["finance", "reimbursement", "travel"],
    routePaths: ["/admin/campaign-events/finance", "/admin/campaign-events/reimbursement", "/admin/campaign-events/travel"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events/finance/", "src/lib/campaign-events/reimbursement/"],
    primaryTools: ["finance-event-compliance-fusion-engine", "campaign-risk-detector"],
    relatedTools: ["workflow-execution-package-builder"],
    upstreamDependencies: ["events_calendar", "scheduling"],
    downstreamDependencies: ["compliance", "executive_command"],
    sourceHealthIds: ["finance", "reimbursement"],
    campaignStateFields: ["financeHealth", "reimbursementReadiness", "financeComplianceWarnings"],
    knowledgeGraphEntityTypes: ["workflow", "issue", "risk", "document", "lesson"],
    humanOwners: ["treasurer", "campaign_manager"],
    restrictedActions: ["finance_post", "reimbursement_submit"],
    improvesCampaignUnderstandingHow: "Tells the AI whether campaign activity is financially ready, blocked, or compliance-sensitive.",
  },
  {
    id: "compliance",
    label: "Compliance",
    mission: "Surface filing, receipt, and approval risk as human-only review checklists.",
    ownedDomains: ["compliance", "finance", "approvals"],
    routePaths: ["/admin/compliance", "/admin/compliance/command-center", "/admin/compliance/filing-readiness"],
    apiPaths: [],
    sourcePaths: ["src/app/admin/(board)/compliance/", "src/lib/compliance/"],
    primaryTools: ["campaign-risk-detector", "finance-event-compliance-fusion-engine"],
    relatedTools: ["orchestration-human-gate-enforcer"],
    upstreamDependencies: ["finance_reimbursement", "events_calendar"],
    downstreamDependencies: ["deployment_readiness", "executive_command", "communications"],
    sourceHealthIds: ["compliance"],
    campaignStateFields: ["complianceReadiness", "financeComplianceWarnings", "systemRisk"],
    knowledgeGraphEntityTypes: ["risk", "document", "issue", "workflow", "lesson"],
    humanOwners: ["treasurer", "compliance_lead"],
    restrictedActions: ["finance_post", "reimbursement_submit", "production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Prevents the AI from mistaking operational readiness for legally safe execution.",
  },
  {
    id: "content_media",
    label: "Content + Media",
    mission: "Prepare public narrative, recap, and media follow-up based on events, county, and comms context.",
    ownedDomains: ["social_media", "communications", "hot_wash"],
    routePaths: ["/admin/communications", "/admin/workbench/comms/media", "/admin/narrative-distribution"],
    apiPaths: [],
    sourcePaths: ["src/lib/social/", "src/lib/communications/"],
    primaryTools: ["communications-priority-orchestrator"],
    relatedTools: ["hotwash-to-county-strategy-router"],
    upstreamDependencies: ["events_calendar", "communications", "county_intelligence"],
    downstreamDependencies: ["public_site", "donor_fundraising", "memory_observations"],
    sourceHealthIds: ["communications"],
    campaignStateFields: ["communicationActions", "knowledge.strongestLessons"],
    knowledgeGraphEntityTypes: ["media_item", "message", "event", "lesson"],
    humanOwners: ["communications_director"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Turns what happened into narrative evidence and lessons for future outreach.",
  },
  {
    id: "donor_fundraising",
    label: "Donor + Fundraising",
    mission: "Connect county/event/comms momentum to donor follow-up preparation without payment or finance posting.",
    ownedDomains: ["finance", "communications", "event_planning"],
    routePaths: ["/admin/campaign-events/finance", "/admin/workbench/email-command-center/audiences"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events/finance/", "src/lib/communications/"],
    primaryTools: ["campaign-opportunity-detector", "communications-priority-orchestrator"],
    relatedTools: ["finance-event-compliance-fusion-engine"],
    upstreamDependencies: ["events_calendar", "communications", "county_intelligence"],
    downstreamDependencies: ["finance_reimbursement", "compliance"],
    sourceHealthIds: ["finance", "communications"],
    campaignStateFields: ["financeHealth", "activeOpportunities"],
    knowledgeGraphEntityTypes: ["donor", "event", "message", "opportunity"],
    humanOwners: ["finance_director", "campaign_manager"],
    restrictedActions: ["finance_post", "contact_export", "auto_send_email"],
    improvesCampaignUnderstandingHow: "Shows whether campaign momentum can safely become fundraising follow-up preparation.",
  },
  {
    id: "scheduling",
    label: "Scheduling",
    mission: "Keep candidate, travel, approvals, and event pressure aligned before calendar changes.",
    ownedDomains: ["calendar", "candidate", "travel", "approvals"],
    routePaths: ["/admin/campaign-calendar", "/admin/campaign-events/workbench", "/admin/campaign-events/travel"],
    apiPaths: [],
    sourcePaths: ["src/lib/campaign-events/", "src/app/admin/(board)/campaign-calendar/"],
    primaryTools: ["county-to-event-calendar-router", "workflow-readiness-checker"],
    relatedTools: ["candidate-daily-briefing-orchestrator"],
    upstreamDependencies: ["county_intelligence", "executive_command"],
    downstreamDependencies: ["events_calendar", "finance_reimbursement", "communications"],
    sourceHealthIds: ["calendar"],
    campaignStateFields: ["calendarEventPressure", "candidateReadiness", "eventReadiness"],
    knowledgeGraphEntityTypes: ["event", "person", "workflow", "risk"],
    humanOwners: ["scheduler", "candidate"],
    restrictedActions: ["google_calendar_write"],
    improvesCampaignUnderstandingHow: "Links time constraints to campaign opportunity so the AI knows what can realistically happen.",
  },
  {
    id: "research_strategy",
    label: "Research + Strategy",
    mission: "Maintain strategic context, issue intelligence, opposition-safe sourcing, and county priorities.",
    ownedDomains: ["campaign_management", "county", "communications"],
    routePaths: ["/admin/campaign-strategy", "/admin/organizing-intelligence"],
    apiPaths: [],
    sourcePaths: ["src/app/admin/(board)/campaign-strategy/", "src/lib/agents/orchestration/knowledge/"],
    primaryTools: ["campaign-momentum-interpreter", "campaign-opportunity-detector"],
    relatedTools: ["campaign-knowledge-memory-synthesizer", "orchestration-observation-miner"],
    upstreamDependencies: ["memory_observations"],
    downstreamDependencies: ["county_intelligence", "communications", "content_media"],
    sourceHealthIds: ["campaign_knowledge"],
    campaignStateFields: ["knowledge", "activeOpportunities", "weakDomains"],
    knowledgeGraphEntityTypes: ["issue", "document", "observation", "lesson", "risk"],
    humanOwners: ["campaign_manager", "strategy_lead"],
    restrictedActions: ["unsourced_opponent_claim", "sensitive_memory_auto_store"],
    improvesCampaignUnderstandingHow: "Converts facts, lessons, and source confidence into strategic context the AI can reuse.",
  },
  {
    id: "ask_kelly",
    label: "Ask Kelly",
    mission: "Route candidate-facing questions and answers into safe briefings and knowledge gaps.",
    ownedDomains: ["candidate", "training", "memory"],
    routePaths: ["/admin/ask-kelly", "/admin/ai-command-center/copilots"],
    apiPaths: [],
    sourcePaths: ["src/app/admin/ai-command-center/copilots/", "src/lib/agents/"],
    primaryTools: ["candidate-daily-briefing-orchestrator"],
    relatedTools: ["orchestration-memory-candidate-builder"],
    upstreamDependencies: ["research_strategy", "memory_observations"],
    downstreamDependencies: ["executive_command", "training_copilots"],
    sourceHealthIds: ["campaign_knowledge"],
    campaignStateFields: ["candidateReadiness", "knowledge.unknownSummary"],
    knowledgeGraphEntityTypes: ["person", "document", "observation", "lesson"],
    humanOwners: ["candidate", "campaign_manager"],
    restrictedActions: ["sensitive_memory_auto_store"],
    improvesCampaignUnderstandingHow: "Turns candidate questions into explicit knowledge gaps and briefing needs.",
  },
  {
    id: "tool_builder",
    label: "Tool Builder",
    mission: "Convert repeated friction and missing intelligence into prioritized supervised build tickets.",
    ownedDomains: ["tool_builder", "dashboard_ux", "campaign_management"],
    routePaths: ["/admin/ai-command-center/tool-builder"],
    apiPaths: ["/api/agents/tool-builder-queue"],
    sourcePaths: ["src/lib/agents/tool-builder/", "src/app/api/agents/tool-builder-queue/route.ts"],
    primaryTools: ["campaign-tool-gap-orchestrator", "system-improvement-package-builder"],
    relatedTools: ["orchestration-observation-miner"],
    upstreamDependencies: ["memory_observations", "deployment_readiness"],
    downstreamDependencies: ["deployment_readiness", "executive_command"],
    sourceHealthIds: ["tool_builder"],
    campaignStateFields: ["toolBuildActions", "memoryObservationSummary.pendingToolTickets", "agentTooling.coverageByDomain"],
    knowledgeGraphEntityTypes: ["tool", "task", "observation", "lesson"],
    humanOwners: ["engineering", "campaign_manager"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Makes the AI aware of missing instruments and why building them would improve the campaign map.",
  },
  {
    id: "training_copilots",
    label: "Training + Copilots",
    mission: "Prepare role-safe guidance and training unlocks based on gaps, not autonomous work.",
    ownedDomains: ["training", "candidate", "dashboard_ux"],
    routePaths: ["/admin/training", "/admin/ai-command-center/copilots"],
    apiPaths: [],
    sourcePaths: ["src/app/admin/training/", "src/lib/agents/user-intelligence/"],
    primaryTools: ["training-to-dashboard-unlock-router", "role-action-router"],
    relatedTools: ["intern-safe-work-orchestrator"],
    upstreamDependencies: ["ask_kelly", "executive_command"],
    downstreamDependencies: ["executive_command"],
    sourceHealthIds: ["training"],
    campaignStateFields: ["trainingHealth", "trainingActions", "roleActions"],
    knowledgeGraphEntityTypes: ["person", "task", "workflow", "lesson"],
    humanOwners: ["campaign_manager", "training_lead"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Shows which humans can safely use which tools and where guidance is still missing.",
  },
  {
    id: "memory_observations",
    label: "Memory + Observations",
    mission: "Convert observations, feedback, hot wash, and lessons into reviewable campaign memory.",
    ownedDomains: ["memory", "hot_wash", "campaign_management"],
    routePaths: ["/admin/orchestration", "/admin/ai-command-center"],
    apiPaths: ["/api/agents/campaign-knowledge-state", "/api/agents/orchestration-feedback", "/api/agents/lesson-approvals"],
    sourcePaths: ["src/lib/agents/orchestration/knowledge/", "src/lib/agents/orchestration/feedback/"],
    primaryTools: ["orchestration-memory-candidate-builder", "campaign-knowledge-memory-synthesizer"],
    relatedTools: ["campaign-lessons-engine", "orchestration-observation-miner"],
    upstreamDependencies: ["events_calendar", "communications"],
    downstreamDependencies: ["executive_command", "research_strategy", "tool_builder"],
    sourceHealthIds: ["campaign_knowledge"],
    campaignStateFields: ["knowledge", "feedbackLoop", "memoryCandidates"],
    knowledgeGraphEntityTypes: ["observation", "lesson", "recommendation", "workflow", "domain"],
    humanOwners: ["campaign_manager"],
    restrictedActions: ["sensitive_memory_auto_store"],
    improvesCampaignUnderstandingHow: "This is the learning layer: it tells the AI what happened, what worked, and what still needs proof.",
  },
  {
    id: "public_site",
    label: "Public Site",
    mission: "Reflect approved public narrative and readiness without leaking internal intelligence.",
    ownedDomains: ["communications", "dashboard_ux"],
    routePaths: ["/", "/admin/homepage"],
    apiPaths: [],
    sourcePaths: ["src/app/", "src/app/admin/(board)/homepage/"],
    primaryTools: ["campaign-risk-detector"],
    relatedTools: ["communications-priority-orchestrator"],
    upstreamDependencies: ["content_media", "compliance", "deployment_readiness"],
    downstreamDependencies: ["communications", "donor_fundraising"],
    sourceHealthIds: ["deployment"],
    campaignStateFields: ["dashboardHealth", "communicationsHealth"],
    knowledgeGraphEntityTypes: ["document", "message", "risk"],
    humanOwners: ["communications_director", "engineering"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Connects approved public surfaces back to narrative readiness and launch risk.",
  },
  {
    id: "deployment_readiness",
    label: "Deployment Readiness",
    mission: "Confirm tests, typecheck, build, migration, docs, and release blockers before shipping.",
    ownedDomains: ["dashboard_ux", "tool_builder", "compliance"],
    routePaths: ["/admin/orchestration"],
    apiPaths: ["/api/agents/cross-domain-orchestration-state"],
    sourcePaths: ["scripts/", "docs/campaign-events/", "prisma/migrations/"],
    primaryTools: ["orchestration-sprint-recommender", "campaign-tool-gap-orchestrator"],
    relatedTools: ["campaign-state-loader", "orchestration-autonomy-boundary-checker"],
    upstreamDependencies: ["tool_builder", "compliance"],
    downstreamDependencies: ["public_site", "executive_command"],
    sourceHealthIds: ["deployment"],
    campaignStateFields: ["signalLoadErrors", "agentTooling.safetySummary", "crossDomainOrchestration.safetySummary"],
    knowledgeGraphEntityTypes: ["document", "tool", "risk", "lesson"],
    humanOwners: ["engineering", "campaign_manager"],
    restrictedActions: ["production_mutation_without_approval"],
    improvesCampaignUnderstandingHow: "Tells the AI whether the campaign operating system itself is safe to ship and trust.",
  },
];

export function getCampaignSection(id: string): CampaignSectionMapEntry | undefined {
  return CAMPAIGN_SECTION_MAP.find((s) => s.id === id);
}

export const REQUIRED_CAMPAIGN_SECTION_IDS = CAMPAIGN_SECTION_MAP.map((s) => s.id);
