/**
 * Phase 4G — Campaign Brain top-level operating model (metadata mirror).
 */

export const CAMPAIGN_BRAIN_OPERATING_STACK = [
  "mission",
  "goals",
  "canonicalData",
  "readinessGates",
  "countyIntelligence",
  "countyInstitutionalMemory",
  "countyResourceOperationsLayer",
  "publicNarrativeIntelligenceLayer",
  "cityPrecinctIntelligence",
  "voterWarehouseSchemaReadiness",
  "registrationSnapshotFlow",
  "countyWinPathwayFormula",
  "countySummaryBrief",
  "fieldNeeds",
  "commsNeeds",
  "eventsCalendar",
  "volunteerCapacity",
  "strategyEligibility",
  "automationEligibility",
] as const;

export const CAMPAIGN_BRAIN_OPERATING_MODEL = {
  modelId: "campaignBrain",
  label: "Campaign Brain",
  rule: "UNIFICATION_BEFORE_AUTOMATION",
  phase: "4P",
  stack: CAMPAIGN_BRAIN_OPERATING_STACK,
  operatingSystemMap: "data/campaign-events/campaign-brain-operating-system-map.json",
  jsonRegistry: "data/campaign-events/campaign-brain-operating-model.json",
  countyInstitutionalMemory: {
    mode: "READ_ONLY_CONTEXT_LAYER",
    can: [
      "summarize county memory",
      "explain historical context",
      "identify recurring operational issues",
      "identify regional/county relationships",
      "suggest safe data collection actions",
    ],
    cannot: [
      "target individual voters",
      "generate contact lists",
      "automate outreach",
      "produce final strategy while strategy gate is NO",
      "infer missing facts as truth",
    ],
  },
  countyResourceOperationsLayer: {
    mode: "READ_ONLY_OPERATIONAL_FORECASTING",
    can: [
      "analyze operational readiness",
      "identify staffing/resource gaps",
      "forecast operational bottlenecks",
      "prioritize intervention urgency",
      "recommend safe operational actions",
    ],
    cannot: [
      "target voters",
      "generate contact lists",
      "automate outreach",
      "produce final strategy while strategy gate is NO",
      "allocate real funds automatically",
      "dispatch field operations automatically",
    ],
  },
  publicNarrativeIntelligenceLayer: {
    mode: "READ_ONLY_PUBLIC_SIGNAL_ANALYSIS",
    can: [
      "summarize public issue environments",
      "analyze recurring county concerns",
      "compare narrative clusters",
      "identify earned-media opportunities",
      "recommend safe communications readiness actions",
    ],
    cannot: [
      "target voters",
      "infer private beliefs",
      "generate psychological persuasion profiles",
      "automate outreach",
      "generate final strategy while strategy gate is NO",
      "create individualized messaging plans",
    ],
  },
  civicFoundation: {
    sourceRegistry: "data/civic/source-registry.json",
    geographyIndex: "data/civic/geography-index.json",
    civicDataReadiness: "data/audit/civic-data-readiness-table.json",
  },
  automationGate: {
    requires: [
      "data/civic/source-registry.json",
      "data/civic/geography-index.json",
      "data/audit/civic-data-readiness-table.json",
      "data/audit/voter-warehouse-schema-readiness.json",
      "data/import-templates/voter-registration-snapshot-template.csv",
      "data/audit/county-win-pathway-inputs.json",
      "data/campaign-events/county-landing-page-orchestration-contract.json",
      "data/county-memory/county-memory-index.json",
      "data/county-memory/county-event-outcomes.json",
      "data/county-memory/county-relationship-graph.json",
      "data/county-memory/regional-influence-map.json",
      "data/audit/county-memory-readiness-table.json",
      "data/resource-allocation/resource-allocation-model.json",
      "data/resource-allocation/candidate-time-allocation.json",
      "data/resource-allocation/field-coverage-readiness.json",
      "data/resource-allocation/county-resource-pressure-table.json",
      "data/resource-allocation/event-roi-model.json",
      "data/resource-allocation/travel-priority-map.json",
      "data/audit/resource-allocation-readiness-table.json",
      "data/public-narrative/public-issue-signal-registry.json",
      "data/public-narrative/county-issue-clusters.json",
      "data/public-narrative/regional-narrative-map.json",
      "data/public-narrative/earned-media-opportunities.json",
      "data/public-narrative/civic-sentiment-summary.json",
      "data/public-narrative/public-meeting-watchlist.json",
      "data/audit/public-narrative-readiness-table.json",
      "civic-tools-source-citations",
      "strategy-gate",
    ],
    implementation: "countyWorkbench/src/lib/civic-geographic-intelligence/automation-eligibility-gate.ts",
  },
} as const;
