/**
 * Phase 4G — Campaign Brain top-level operating model (metadata mirror).
 */

export const CAMPAIGN_BRAIN_OPERATING_STACK = [
  "mission",
  "goals",
  "canonicalData",
  "readinessGates",
  "countyIntelligence",
  "countyInstitutionalMemory",
  "countyResourceOperationsLayer",
  "publicNarrativeIntelligenceLayer",
  "simulationScenarioEngine",
  "multiAgentCampaignBrain",
  "executiveCommandCenter",
  "strategyDoctrineLayer",
  "cityPrecinctIntelligence",
  "voterWarehouseSchemaReadiness",
  "registrationSnapshotFlow",
  "countyWinPathwayFormula",
  "countySummaryBrief",
  "fieldNeeds",
  "commsNeeds",
  "eventsCalendar",
  "volunteerCapacity",
  "strategyEligibility",
  "automationEligibility",
] as const;

export const CAMPAIGN_BRAIN_OPERATING_MODEL = {
  modelId: "campaignBrain",
  label: "Campaign Brain",
  rule: "UNIFICATION_BEFORE_AUTOMATION",
  phase: "5A",
  stack: CAMPAIGN_BRAIN_OPERATING_STACK,
  operatingSystemMap: "data/campaign-events/campaign-brain-operating-system-map.json",
  jsonRegistry: "data/campaign-events/campaign-brain-operating-model.json",
  countyInstitutionalMemory: {
    mode: "READ_ONLY_CONTEXT_LAYER",
    can: [
      "summarize county memory",
      "explain historical context",
      "identify recurring operational issues",
      "identify regional/county relationships",
      "suggest safe data collection actions",
    ],
    cannot: [
      "target individual voters",
      "generate contact lists",
      "automate outreach",
      "produce final strategy while strategy gate is NO",
      "infer missing facts as truth",
    ],
  },
  countyResourceOperationsLayer: {
    mode: "READ_ONLY_OPERATIONAL_FORECASTING",
    can: [
      "analyze operational readiness",
      "identify staffing/resource gaps",
      "forecast operational bottlenecks",
      "prioritize intervention urgency",
      "recommend safe operational actions",
    ],
    cannot: [
      "target voters",
      "generate contact lists",
      "automate outreach",
      "produce final strategy while strategy gate is NO",
      "allocate real funds automatically",
      "dispatch field operations automatically",
    ],
  },
  publicNarrativeIntelligenceLayer: {
    mode: "READ_ONLY_PUBLIC_SIGNAL_ANALYSIS",
    can: [
      "summarize public issue environments",
      "analyze recurring county concerns",
      "compare narrative clusters",
      "identify earned-media opportunities",
      "recommend safe communications readiness actions",
    ],
    cannot: [
      "target voters",
      "infer private beliefs",
      "generate psychological persuasion profiles",
      "automate outreach",
      "generate final strategy while strategy gate is NO",
      "create individualized messaging plans",
    ],
  },
  simulationScenarioEngine: {
    mode: "READ_ONLY_MODELING_AND_FORECASTING",
    can: [
      "run aggregate simulations",
      "model operational impacts",
      "estimate readiness trajectories",
      "compare scenarios",
      "estimate intervention impacts",
    ],
    cannot: [
      "target voters",
      "generate contact lists",
      "automate outreach",
      "represent scenarios as canon truth",
      "autonomously execute campaign strategy",
      "produce individualized persuasion models",
    ],
  },
  multiAgentCampaignBrain: {
    mode: "READ_ONLY_COORDINATED_SYNTHESIS",
    can: [
      "coordinate aggregate intelligence",
      "synthesize statewide readiness",
      "identify operational conflicts",
      "rank intervention urgency",
      "recommend safe operational priorities",
    ],
    cannot: [
      "autonomously execute campaign actions",
      "target voters",
      "generate contact lists",
      "automate outreach",
      "autonomously allocate money/resources",
      "autonomously generate final campaign strategy",
      "bypass safety gates",
    ],
  },
  executiveCommandCenter: {
    mode: "READ_ONLY_EXECUTIVE_SYNTHESIS",
    can: [
      "synthesize statewide operational intelligence",
      "rank statewide priorities",
      "identify risks/opportunities",
      "surface intervention needs",
      "build executive briefs",
      "monitor campaign-system health",
    ],
    cannot: [
      "autonomously execute campaign actions",
      "target voters",
      "generate contact lists",
      "automate outreach",
      "autonomously allocate resources",
      "autonomously generate final campaign strategy",
      "bypass safety gates",
    ],
  },
  strategyDoctrineLayer: {
    mode: "READ_ONLY_STRATEGY_DOCTRINE_INTAKE",
    can: [
      "read Steve strategy doctrine",
      "read Arkansas grassroots principles",
      "summarize Rockefeller case study",
      "explain GOTV backward-planning model",
      "explain poll watcher coverage model",
      "identify strategy doctrine gaps",
    ],
    cannot: [
      "target individual voters",
      "generate contact lists",
      "automate outreach",
      "create final strategy without human approval",
      "bypass legal/compliance review",
    ],
  },
  civicFoundation: {
    sourceRegistry: "data/civic/source-registry.json",
    geographyIndex: "data/civic/geography-index.json",
    civicDataReadiness: "data/audit/civic-data-readiness-table.json",
  },
  automationGate: {
    requires: [
      "data/civic/source-registry.json",
      "data/civic/geography-index.json",
      "data/audit/civic-data-readiness-table.json",
      "data/audit/voter-warehouse-schema-readiness.json",
      "data/import-templates/voter-registration-snapshot-template.csv",
      "data/audit/county-win-pathway-inputs.json",
      "data/campaign-events/county-landing-page-orchestration-contract.json",
      "data/county-memory/county-memory-index.json",
      "data/county-memory/county-event-outcomes.json",
      "data/county-memory/county-relationship-graph.json",
      "data/county-memory/regional-influence-map.json",
      "data/audit/county-memory-readiness-table.json",
      "data/resource-allocation/resource-allocation-model.json",
      "data/resource-allocation/candidate-time-allocation.json",
      "data/resource-allocation/field-coverage-readiness.json",
      "data/resource-allocation/county-resource-pressure-table.json",
      "data/resource-allocation/event-roi-model.json",
      "data/resource-allocation/travel-priority-map.json",
      "data/audit/resource-allocation-readiness-table.json",
      "data/public-narrative/public-issue-signal-registry.json",
      "data/public-narrative/county-issue-clusters.json",
      "data/public-narrative/regional-narrative-map.json",
      "data/public-narrative/earned-media-opportunities.json",
      "data/public-narrative/civic-sentiment-summary.json",
      "data/public-narrative/public-meeting-watchlist.json",
      "data/audit/public-narrative-readiness-table.json",
      "data/simulations/county-scenario-registry.json",
      "data/simulations/statewide-scenario-matrix.json",
      "data/simulations/pathway-sensitivity-model.json",
      "data/simulations/registration-growth-scenarios.json",
      "data/simulations/resource-impact-models.json",
      "data/simulations/event-impact-scenarios.json",
      "data/simulations/turnout-sensitivity-models.json",
      "data/audit/simulation-engine-readiness-table.json",
      "data/multi-agent/campaign-brain-agent-registry.json",
      "data/multi-agent/agent-capability-map.json",
      "data/multi-agent/agent-runtime-coordination-map.json",
      "data/multi-agent/agent-dependency-graph.json",
      "data/multi-agent/agent-safety-policy-map.json",
      "data/multi-agent/agent-runtime-state-table.json",
      "data/multi-agent/cross-agent-insight-stream.json",
      "data/audit/multi-agent-coordination-readiness-table.json",
      "data/executive-command/executive-command-state.json",
      "data/executive-command/statewide-readiness-matrix.json",
      "data/executive-command/executive-priority-ranking.json",
      "data/executive-command/operational-bottleneck-map.json",
      "data/executive-command/statewide-intervention-queue.json",
      "data/executive-command/regional-pressure-map.json",
      "data/executive-command/campaign-health-scorecard.json",
      "data/executive-command/executive-alert-stream.json",
      "data/executive-command/executive-brief-registry.json",
      "data/audit/executive-command-readiness-table.json",
      "data/strategy-doctrine/steve-strategy-doctrine.json",
      "data/strategy-doctrine/arkansas-grassroots-principles.json",
      "data/strategy-doctrine/rockefeller-grassroots-case-study.json",
      "data/strategy-doctrine/relational-organizing-playbook.json",
      "data/strategy-doctrine/gotv-backward-calendar-model.json",
      "data/strategy-doctrine/poll-watcher-coverage-model.json",
      "data/strategy-doctrine/event-visibility-playbook.json",
      "data/strategy-doctrine/county-strategy-source-index.json",
      "data/audit/strategy-doctrine-readiness-table.json",
      "civic-tools-source-citations",
      "strategy-gate",
    ],
    implementation: "countyWorkbench/src/lib/civic-geographic-intelligence/automation-eligibility-gate.ts",
  },
} as const;
