/**
 * Phase 4F — orchestration metadata mirror (County Workbench lane).
 * Implementation lives in countyWorkbench/ — no runtime import from RedDirt src.
 */

export const COUNTY_INTELLIGENCE_COPILOT_ORCHESTRATION = {
  id: "countyIntelligenceCopilot",
  lane: "County Workbench",
  mode: "READ_ONLY_ANALYSIS_UNTIL_READY" as const,
  phase: "4R",
  toolGroupCount: 15,
  toolCount: 133,
  toolGroups: {
    volunteerIntelligence: [
      "volunteerRosterSummary",
      "volunteerCapacityAnalyzer",
      "countyCaptainNeedsDetector",
      "volunteerFollowupRecommender",
      "signupSourceAnalyzer",
    ],
    messagingIntelligence: [
      "countyMessageThemeReader",
      "publicIssueSignalReader",
      "messageRiskChecker",
      "audienceSegmentMapper",
      "approvedTalkingPointMatcher",
    ],
    statisticsIntelligence: [
      "voterRegistrationFactReader",
      "electionBaselineAnalyzer",
      "turnoutGapAnalyzer",
      "voteGainScenarioExplainer",
      "countyTrendSummary",
    ],
    strengthsWeaknesses: [
      "countyStrengthDetector",
      "countyWeaknessDetector",
      "opportunityFinder",
      "threatRiskScanner",
      "confidenceScoreCalculator",
    ],
    campaignNeeds: [
      "countyNeedsRanker",
      "dataGapPrioritizer",
      "fieldCapacityNeeds",
      "commsNeeds",
      "eventNeeds",
      "leadershipNeeds",
    ],
    calendarEvents: [
      "countyEventReader",
      "eventCoverageAnalyzer",
      "calendarGapFinder",
      "upcomingDeadlineReader",
      "eventFollowupRecommender",
    ],
    strategyGuardrails: [
      "strategyReadinessGatekeeper",
      "strategyDraftPermissionChecker",
      "sourceCitationBuilder",
      "missingCanonBlocker",
      "humanApprovalRequirementChecker",
    ],
    civicGeographic: [
      "censusProfileReader",
      "blsLaborMarketReader",
      "socioeconomicRiskScanner",
      "cityProfileReader",
      "precinctProfileReader",
      "mapBoundaryInspector",
      "demographicShiftAnalyzer",
      "countyCityComparisonTool",
      "precinctOpportunityScanner",
      "sourceConfidenceExplainer",
    ],
    voterFile: [
      "voterFileCoverageInspector",
      "precinctVoterProfileReader",
      "voterRegistrationTrendAnalyzer",
      "voterDensityHeatmapBuilder",
      "voterGeocodeQualityChecker",
      "voterSegmentSummaryTool",
      "voterDataPrivacyGuard",
      "voterFileFieldDictionaryReader",
      "voterFileGapExplainer",
      "voterMapLayerBuilder",
      "voterFileChunkLocator",
      "voterSegmentModelReader",
      "voterHistoryPatternAnalyzer",
      "voterContactListPermissionGate",
    ],
    mapGeospatial: [
      "precinctBoundaryInspector",
      "geocodeCoverageAnalyzer",
      "voterDensityMapReadinessChecker",
      "precinctDataGapExplainer",
      "countyMapLayerBuilder",
      "cityMapLayerBuilder",
      "precinctMapLayerBuilder",
      "heatMapPermissionGate",
    ],
    countyInstitutionalMemory: [
      "countyMemoryTimeline",
      "countyPoliticalCultureProfile",
      "eventOutcomeAnalyzer",
      "recurringIssueTracker",
      "localInfluenceMap",
      "countyRelationshipGraphReader",
      "regionalInfluenceAnalyzer",
      "crossCountyTrendAnalyzer",
      "sharedIssueDetector",
      "institutionalMemoryGapExplainer",
    ],
    countyResourceOperationsLayer: [
      "resourceAllocationOptimizer",
      "candidateTimeAllocator",
      "eventROIAnalyzer",
      "fieldCoverageGapFinder",
      "travelPriorityPlanner",
      "volunteerCapacityForecast",
      "countyMomentumForecast",
      "organizationalFragilityDetector",
      "countyResourcePressureAnalyzer",
      "deploymentPriorityRanker",
      "countyInterventionRecommender",
      "statewideOperationalBottleneckScanner",
    ],
    publicNarrativeIntelligenceLayer: [
      "issueSignalTracker",
      "countyConcernAnalyzer",
      "publicNarrativeMonitor",
      "recurringIssueTracker",
      "localIssueHeatmap",
      "regionalNarrativeAnalyzer",
      "earnedMediaOpportunityFinder",
      "publicMeetingSignalReader",
      "civicSentimentSummaryBuilder",
      "messagingReadinessAnalyzer",
      "narrativeGapExplainer",
      "issueClusterExplorer",
      "countyNarrativeComparisonTool",
      "publicNarrativeTrendAnalyzer",
    ],
    simulationScenarioEngine: [
      "countyScenarioSimulator",
      "statewideScenarioExplorer",
      "pathwaySensitivityAnalyzer",
      "registrationGrowthProjector",
      "turnoutSensitivityAnalyzer",
      "resourceImpactModeler",
      "eventImpactScenarioModeler",
      "operationalTradeoffAnalyzer",
      "simulationConfidenceScorer",
      "readinessTrajectoryProjector",
      "interventionImpactEstimator",
      "countyScenarioComparisonTool",
      "statewideScenarioRankingTool",
      "simulationGapExplainer",
      "scenarioRiskAnalyzer",
    ],
    multiAgentCampaignBrain: [
      "campaignBrainSynthesisEngine",
      "crossAgentInsightAggregator",
      "statewideInterventionCoordinator",
      "crossAgentConflictResolver",
      "executivePriorityRanker",
      "operationalRiskFusionAnalyzer",
      "statewideReadinessSynthesizer",
      "crossDomainTrendAnalyzer",
      "campaignBrainHealthInspector",
      "agentSafetyGatekeeper",
      "agentDependencyInspector",
      "coordinationGapExplainer",
      "statewideResourceConflictAnalyzer",
      "statewideNarrativeAlignmentAnalyzer",
      "executiveCoordinationBriefBuilder",
    ],
  },
  orchestrationInputs: {
    voterWarehouseSchemaReadiness: "data/audit/voter-warehouse-schema-readiness.json",
    registrationSnapshotTemplate: "data/import-templates/voter-registration-snapshot-template.csv",
    registrationSnapshotImportFlow: "scripts/brain/import-voter-registration-snapshot.ts",
    countyWinPathwayInputs: "data/audit/county-win-pathway-inputs.json",
    countyLandingContract: "data/campaign-events/county-landing-page-orchestration-contract.json",
    countySummaryBriefBuilder: "src/lib/campaign-engine/county-brief-builder.ts",
    popeCountyAdapter: "src/lib/campaign-engine/county-dashboards/pope-county-brief-adapter.ts",
    strategyReadiness: "data/audit/county-strategy-readiness-table.json",
    countyMemoryIndex: "data/county-memory/county-memory-index.json",
    countyEventOutcomes: "data/county-memory/county-event-outcomes.json",
    countyRelationshipGraph: "data/county-memory/county-relationship-graph.json",
    regionalInfluenceMap: "data/county-memory/regional-influence-map.json",
    countyMemoryReadiness: "data/audit/county-memory-readiness-table.json",
    resourceAllocationModel: "data/resource-allocation/resource-allocation-model.json",
    candidateTimeAllocation: "data/resource-allocation/candidate-time-allocation.json",
    fieldCoverageReadiness: "data/resource-allocation/field-coverage-readiness.json",
    countyResourcePressure: "data/resource-allocation/county-resource-pressure-table.json",
    eventROIModel: "data/resource-allocation/event-roi-model.json",
    travelPriorityMap: "data/resource-allocation/travel-priority-map.json",
    resourceAllocationReadiness: "data/audit/resource-allocation-readiness-table.json",
    publicIssueSignalRegistry: "data/public-narrative/public-issue-signal-registry.json",
    countyIssueClusters: "data/public-narrative/county-issue-clusters.json",
    regionalNarrativeMap: "data/public-narrative/regional-narrative-map.json",
    earnedMediaOpportunities: "data/public-narrative/earned-media-opportunities.json",
    civicSentimentSummary: "data/public-narrative/civic-sentiment-summary.json",
    publicMeetingWatchlist: "data/public-narrative/public-meeting-watchlist.json",
    publicNarrativeReadiness: "data/audit/public-narrative-readiness-table.json",
    countyScenarioRegistry: "data/simulations/county-scenario-registry.json",
    statewideScenarioMatrix: "data/simulations/statewide-scenario-matrix.json",
    pathwaySensitivityModel: "data/simulations/pathway-sensitivity-model.json",
    registrationGrowthScenarios: "data/simulations/registration-growth-scenarios.json",
    resourceImpactModels: "data/simulations/resource-impact-models.json",
    eventImpactScenarios: "data/simulations/event-impact-scenarios.json",
    turnoutSensitivityModels: "data/simulations/turnout-sensitivity-models.json",
    simulationEngineReadiness: "data/audit/simulation-engine-readiness-table.json",
    campaignBrainAgentRegistry: "data/multi-agent/campaign-brain-agent-registry.json",
    agentCapabilityMap: "data/multi-agent/agent-capability-map.json",
    agentRuntimeCoordinationMap: "data/multi-agent/agent-runtime-coordination-map.json",
    agentDependencyGraph: "data/multi-agent/agent-dependency-graph.json",
    agentSafetyPolicyMap: "data/multi-agent/agent-safety-policy-map.json",
    agentRuntimeStateTable: "data/multi-agent/agent-runtime-state-table.json",
    crossAgentInsightStream: "data/multi-agent/cross-agent-insight-stream.json",
    multiAgentCoordinationReadiness: "data/audit/multi-agent-coordination-readiness-table.json",
  },
  can: [
    "summarize county condition",
    "explain gaps",
    "recommend next operational actions",
    "compare counties",
    "prepare captain briefings",
    "flag risks",
    "summarize county memory",
    "explain historical context",
    "identify recurring operational issues",
    "identify regional/county relationships",
    "suggest safe data collection actions",
    "analyze operational readiness",
    "identify staffing/resource gaps",
    "forecast operational bottlenecks",
    "prioritize intervention urgency",
    "recommend safe operational actions",
    "summarize public issue environments",
    "analyze recurring county concerns",
    "compare narrative clusters",
    "identify earned-media opportunities",
    "recommend safe communications readiness actions",
    "run aggregate simulations",
    "model operational impacts",
    "estimate readiness trajectories",
    "compare scenarios",
    "estimate intervention impacts",
    "coordinate aggregate intelligence",
    "synthesize statewide readiness",
    "identify operational conflicts",
    "rank intervention urgency",
    "recommend safe operational priorities",
  ],
  cannot: [
    "invent missing goals",
    "promote scenario estimates",
    "mutate RedDirt canon",
    "write to sister lanes",
    "create final strategy while gate is NO",
    "target individual voters",
    "generate contact lists",
    "automate outreach",
    "allocate real funds automatically",
    "dispatch field operations automatically",
    "infer private beliefs",
    "generate psychological persuasion profiles",
    "create individualized messaging plans",
    "represent scenarios as canon truth",
    "autonomously execute campaign strategy",
    "produce individualized persuasion models",
    "autonomously execute campaign actions",
    "autonomously allocate money/resources",
    "autonomously generate final campaign strategy",
    "bypass safety gates",
    "infer missing facts as truth",
  ],
  executionPolicy: {
    readOnly: true,
    strategyGenerationRequiresGateYes: true,
    automationEnabled: false,
  },
  jsonRegistry: "data/campaign-events/county-intelligence-copilot-orchestration.json",
} as const;
