/**
 * Phase 4F — orchestration metadata mirror (County Workbench lane).
 * Implementation lives in countyWorkbench/ — no runtime import from RedDirt src.
 */

export const COUNTY_INTELLIGENCE_COPILOT_ORCHESTRATION = {
  id: "countyIntelligenceCopilot",
  lane: "County Workbench",
  mode: "READ_ONLY_ANALYSIS_UNTIL_READY" as const,
  phase: "4N",
  toolGroupCount: 12,
  toolCount: 89,
  toolGroups: {
    volunteerIntelligence: [
      "volunteerRosterSummary",
      "volunteerCapacityAnalyzer",
      "countyCaptainNeedsDetector",
      "volunteerFollowupRecommender",
      "signupSourceAnalyzer",
    ],
    messagingIntelligence: [
      "countyMessageThemeReader",
      "publicIssueSignalReader",
      "messageRiskChecker",
      "audienceSegmentMapper",
      "approvedTalkingPointMatcher",
    ],
    statisticsIntelligence: [
      "voterRegistrationFactReader",
      "electionBaselineAnalyzer",
      "turnoutGapAnalyzer",
      "voteGainScenarioExplainer",
      "countyTrendSummary",
    ],
    strengthsWeaknesses: [
      "countyStrengthDetector",
      "countyWeaknessDetector",
      "opportunityFinder",
      "threatRiskScanner",
      "confidenceScoreCalculator",
    ],
    campaignNeeds: [
      "countyNeedsRanker",
      "dataGapPrioritizer",
      "fieldCapacityNeeds",
      "commsNeeds",
      "eventNeeds",
      "leadershipNeeds",
    ],
    calendarEvents: [
      "countyEventReader",
      "eventCoverageAnalyzer",
      "calendarGapFinder",
      "upcomingDeadlineReader",
      "eventFollowupRecommender",
    ],
    strategyGuardrails: [
      "strategyReadinessGatekeeper",
      "strategyDraftPermissionChecker",
      "sourceCitationBuilder",
      "missingCanonBlocker",
      "humanApprovalRequirementChecker",
    ],
    civicGeographic: [
      "censusProfileReader",
      "blsLaborMarketReader",
      "socioeconomicRiskScanner",
      "cityProfileReader",
      "precinctProfileReader",
      "mapBoundaryInspector",
      "demographicShiftAnalyzer",
      "countyCityComparisonTool",
      "precinctOpportunityScanner",
      "sourceConfidenceExplainer",
    ],
    voterFile: [
      "voterFileCoverageInspector",
      "precinctVoterProfileReader",
      "voterRegistrationTrendAnalyzer",
      "voterDensityHeatmapBuilder",
      "voterGeocodeQualityChecker",
      "voterSegmentSummaryTool",
      "voterDataPrivacyGuard",
      "voterFileFieldDictionaryReader",
      "voterFileGapExplainer",
      "voterMapLayerBuilder",
      "voterFileChunkLocator",
      "voterSegmentModelReader",
      "voterHistoryPatternAnalyzer",
      "voterContactListPermissionGate",
    ],
    mapGeospatial: [
      "precinctBoundaryInspector",
      "geocodeCoverageAnalyzer",
      "voterDensityMapReadinessChecker",
      "precinctDataGapExplainer",
      "countyMapLayerBuilder",
      "cityMapLayerBuilder",
      "precinctMapLayerBuilder",
      "heatMapPermissionGate",
    ],
    countyInstitutionalMemory: [
      "countyMemoryTimeline",
      "countyPoliticalCultureProfile",
      "eventOutcomeAnalyzer",
      "recurringIssueTracker",
      "localInfluenceMap",
      "countyRelationshipGraphReader",
      "regionalInfluenceAnalyzer",
      "crossCountyTrendAnalyzer",
      "sharedIssueDetector",
      "institutionalMemoryGapExplainer",
    ],
    countyResourceOperationsLayer: [
      "resourceAllocationOptimizer",
      "candidateTimeAllocator",
      "eventROIAnalyzer",
      "fieldCoverageGapFinder",
      "travelPriorityPlanner",
      "volunteerCapacityForecast",
      "countyMomentumForecast",
      "organizationalFragilityDetector",
      "countyResourcePressureAnalyzer",
      "deploymentPriorityRanker",
      "countyInterventionRecommender",
      "statewideOperationalBottleneckScanner",
    ],
  },
  orchestrationInputs: {
    voterWarehouseSchemaReadiness: "data/audit/voter-warehouse-schema-readiness.json",
    registrationSnapshotTemplate: "data/import-templates/voter-registration-snapshot-template.csv",
    registrationSnapshotImportFlow: "scripts/brain/import-voter-registration-snapshot.ts",
    countyWinPathwayInputs: "data/audit/county-win-pathway-inputs.json",
    countyLandingContract: "data/campaign-events/county-landing-page-orchestration-contract.json",
    countySummaryBriefBuilder: "src/lib/campaign-engine/county-brief-builder.ts",
    popeCountyAdapter: "src/lib/campaign-engine/county-dashboards/pope-county-brief-adapter.ts",
    strategyReadiness: "data/audit/county-strategy-readiness-table.json",
    countyMemoryIndex: "data/county-memory/county-memory-index.json",
    countyEventOutcomes: "data/county-memory/county-event-outcomes.json",
    countyRelationshipGraph: "data/county-memory/county-relationship-graph.json",
    regionalInfluenceMap: "data/county-memory/regional-influence-map.json",
    countyMemoryReadiness: "data/audit/county-memory-readiness-table.json",
    resourceAllocationModel: "data/resource-allocation/resource-allocation-model.json",
    candidateTimeAllocation: "data/resource-allocation/candidate-time-allocation.json",
    fieldCoverageReadiness: "data/resource-allocation/field-coverage-readiness.json",
    countyResourcePressure: "data/resource-allocation/county-resource-pressure-table.json",
    eventROIModel: "data/resource-allocation/event-roi-model.json",
    travelPriorityMap: "data/resource-allocation/travel-priority-map.json",
    resourceAllocationReadiness: "data/audit/resource-allocation-readiness-table.json",
  },
  can: [
    "summarize county condition",
    "explain gaps",
    "recommend next operational actions",
    "compare counties",
    "prepare captain briefings",
    "flag risks",
    "summarize county memory",
    "explain historical context",
    "identify recurring operational issues",
    "identify regional/county relationships",
    "suggest safe data collection actions",
    "analyze operational readiness",
    "identify staffing/resource gaps",
    "forecast operational bottlenecks",
    "prioritize intervention urgency",
    "recommend safe operational actions",
  ],
  cannot: [
    "invent missing goals",
    "promote scenario estimates",
    "mutate RedDirt canon",
    "write to sister lanes",
    "create final strategy while gate is NO",
    "target individual voters",
    "generate contact lists",
    "automate outreach",
    "allocate real funds automatically",
    "dispatch field operations automatically",
    "infer missing facts as truth",
  ],
  executionPolicy: {
    readOnly: true,
    strategyGenerationRequiresGateYes: true,
    automationEnabled: false,
  },
  jsonRegistry: "data/campaign-events/county-intelligence-copilot-orchestration.json",
} as const;
