/**
 * Orchestration domain registry — source of truth map for cross-domain reasoning.
 */

import type { CampaignDomainId } from "./campaign-state-types";

export type OrchestrationDomainSpec = {
  id: CampaignDomainId;
  label: string;
  sourceOfTruth: string;
  keyRoutes: string[];
  keyToolLifecycles: string[];
  keyKpis: string[];
  typicalBlockers: string[];
  observationPrefixes: string[];
  humanGates: string[];
  orchestrationOutputs: string[];
};

export const ORCHESTRATION_DOMAINS: OrchestrationDomainSpec[] = [
  {
    id: "campaign_management",
    label: "Campaign Management",
    sourceOfTruth: "OS control bundle + unified campaign context",
    keyRoutes: ["/admin/ai-command-center"],
    keyToolLifecycles: ["agent_os_control", "campaign_orchestration_intelligence"],
    keyKpis: ["systemHealthScore", "activeBlockers", "topMoves"],
    typicalBlockers: ["Stale period", "Unreviewed workflows"],
    observationPrefixes: ["os_", "agent_", "system_"],
    humanGates: ["Prepared actions only"],
    orchestrationOutputs: ["CM daily plan", "Top 3 moves", "Cross-domain blockers"],
  },
  {
    id: "candidate",
    label: "Candidate",
    sourceOfTruth: "Role copilot + candidate briefing tools",
    keyRoutes: ["/admin/ai-command-center/copilots", "/admin/campaign-events/workbench"],
    keyToolLifecycles: ["kelly_os_copilot_tooling", "candidate_briefing"],
    keyKpis: ["briefingReady", "eventsThisWeek"],
    typicalBlockers: ["Missing run-of-show", "Unapproved travel"],
    observationPrefixes: ["candidate_"],
    humanGates: ["No autonomous comms send"],
    orchestrationOutputs: ["Candidate daily briefing package"],
  },
  {
    id: "calendar",
    label: "Calendar",
    sourceOfTruth: "CampaignEventLedgerRecord + GCal sync truth",
    keyRoutes: ["/admin/campaign-calendar", "/admin/campaign-events/calendar-sync"],
    keyToolLifecycles: ["calendar_intake", "sprint5_calendar_promotion"],
    keyKpis: ["syncStale", "pendingPromotions"],
    typicalBlockers: ["Sync stale", "Unpromoted tentative"],
    observationPrefixes: ["calendar_", "gcal_"],
    humanGates: ["GCal write human-only"],
    orchestrationOutputs: ["Promotion queue", "Sync repair workflow"],
  },
  {
    id: "event_planning",
    label: "Event Planning",
    sourceOfTruth: "Event workbench + factCard + drilldown",
    keyRoutes: ["/admin/campaign-events/workbench"],
    keyToolLifecycles: ["event_planning_sprint6", "event_intelligence_sprint7"],
    keyKpis: ["readinessScore", "missingArtifacts"],
    typicalBlockers: ["Incomplete fact card", "No volunteers assigned"],
    observationPrefixes: ["event_", "planning_"],
    humanGates: ["Budget approval", "Materials sign-off"],
    orchestrationOutputs: ["Event execution package", "County visit prep chain"],
  },
  {
    id: "approvals",
    label: "Approvals",
    sourceOfTruth: "Approval queues + token email",
    keyRoutes: ["/admin/campaign-events/review"],
    keyToolLifecycles: ["tentative_approval", "sprint4_approval_email"],
    keyKpis: ["pendingApprovals"],
    typicalBlockers: ["Held events", "Expired tokens"],
    observationPrefixes: ["approval_"],
    humanGates: ["Recipient click required"],
    orchestrationOutputs: ["Approval chase workflow"],
  },
  {
    id: "travel",
    label: "Travel",
    sourceOfTruth: "Travel ledger JSON + wizard sessions",
    keyRoutes: ["/admin/campaign-events/travel"],
    keyToolLifecycles: ["travel_ledger"],
    keyKpis: ["openTrips", "mileageReview"],
    typicalBlockers: ["Missing receipts", "Unlinked events"],
    observationPrefixes: ["travel_"],
    humanGates: ["Treasurer review"],
    orchestrationOutputs: ["Travel fix chain before reimbursement"],
  },
  {
    id: "reimbursement",
    label: "Reimbursement",
    sourceOfTruth: "Reimbursement ops JSON + treasurer packet",
    keyRoutes: ["/admin/campaign-events/reimbursement"],
    keyToolLifecycles: ["mileage_reimbursement"],
    keyKpis: ["packetStatus", "printReady"],
    typicalBlockers: ["Open mileage rows", "Missing compliance docs"],
    observationPrefixes: ["reimbursement_"],
    humanGates: ["Print/export human"],
    orchestrationOutputs: ["Close month reimbursement workflow"],
  },
  {
    id: "finance",
    label: "Finance",
    sourceOfTruth: "Finance intelligence V2 + ledger",
    keyRoutes: ["/admin/campaign-events/finance"],
    keyToolLifecycles: ["campaign_finance_sprint8"],
    keyKpis: ["burnRate", "openCommitments"],
    typicalBlockers: ["Unreconciled costs"],
    observationPrefixes: ["finance_"],
    humanGates: ["No auto post"],
    orchestrationOutputs: ["Finance-event fusion package"],
  },
  {
    id: "compliance",
    label: "Compliance",
    sourceOfTruth: "Compliance readiness + receipt pipeline",
    keyRoutes: ["/admin/compliance"],
    keyToolLifecycles: ["compliance_receipts"],
    keyKpis: ["filingReadiness", "missingReceipts"],
    typicalBlockers: ["Receipt gaps"],
    observationPrefixes: ["compliance_"],
    humanGates: ["Filing human-only"],
    orchestrationOutputs: ["Compliance gap workflow"],
  },
  {
    id: "county",
    label: "County",
    sourceOfTruth: "countyWorkbench bridge + county-intelligence engine",
    keyRoutes: ["/admin/county-intelligence"],
    keyToolLifecycles: ["county_intelligence_bridge"],
    keyKpis: ["weakCounties", "powerOf5Gaps"],
    typicalBlockers: ["No field plan", "Zero events in county"],
    observationPrefixes: ["county_"],
    humanGates: ["Memory write approval"],
    orchestrationOutputs: ["Activate weak county workflow", "County action package"],
  },
  {
    id: "field",
    label: "Field",
    sourceOfTruth: "Field copilot + county packages",
    keyRoutes: ["/admin/county-intelligence", "/admin/ai-command-center/copilots"],
    keyToolLifecycles: ["kelly_os_copilot_tooling", "county_intelligence_bridge"],
    keyKpis: ["fieldDailyPlan", "countyPriorities"],
    typicalBlockers: ["Unassigned counties"],
    observationPrefixes: ["field_"],
    humanGates: ["No voter export"],
    orchestrationOutputs: ["Field priority orchestration"],
  },
  {
    id: "volunteer",
    label: "Volunteer",
    sourceOfTruth: "Volunteer CRM + assignment engine",
    keyRoutes: ["/admin/volunteers"],
    keyToolLifecycles: ["volunteer_system"],
    keyKpis: ["underusedSegments", "openShifts"],
    typicalBlockers: ["Unstaffed events"],
    observationPrefixes: ["volunteer_"],
    humanGates: ["Assignment human confirm"],
    orchestrationOutputs: ["Volunteer push workflow", "Workload balance"],
  },
  {
    id: "communications",
    label: "Communications",
    sourceOfTruth: "communications-intelligence-engine + JSON store",
    keyRoutes: ["/admin/communications", "/admin/communications/intelligence"],
    keyToolLifecycles: ["communications_system", "email_os_suite"],
    keyKpis: ["fatigueRisk", "followupGaps"],
    typicalBlockers: ["Draft backlog", "Suppression backlog"],
    observationPrefixes: ["comms_", "communications_"],
    humanGates: ["Mass send blocked", "ECC SEND APPROVED"],
    orchestrationOutputs: ["Comms sequence plan", "Volunteer retention router"],
  },
  {
    id: "social_media",
    label: "Social Media",
    sourceOfTruth: "Comms + hot wash media signals",
    keyRoutes: ["/admin/communications"],
    keyToolLifecycles: ["communications_system"],
    keyKpis: ["postCadence", "contentGaps"],
    typicalBlockers: ["No post-event recap"],
    observationPrefixes: ["social_"],
    humanGates: ["Publish human-only"],
    orchestrationOutputs: ["Post-event comms chain"],
  },
  {
    id: "host",
    label: "Host",
    sourceOfTruth: "Host relationship workflows",
    keyRoutes: ["/admin/campaign-events/workbench"],
    keyToolLifecycles: ["host_dashboard"],
    keyKpis: ["hostPipeline", "housePartyCount"],
    typicalBlockers: ["Unconfirmed host"],
    observationPrefixes: ["host_"],
    humanGates: ["Invite list human"],
    orchestrationOutputs: ["House party program workflow"],
  },
  {
    id: "hot_wash",
    label: "Hot Wash",
    sourceOfTruth: "hot-wash-intelligence + county memory",
    keyRoutes: ["/admin/campaign-events/media"],
    keyToolLifecycles: ["hot_wash_learning", "event_intelligence_sprint7"],
    keyKpis: ["learningCaptured", "countyMemoryUpdated"],
    typicalBlockers: ["No hot wash filed"],
    observationPrefixes: ["hot_wash_"],
    humanGates: ["Memory approval"],
    orchestrationOutputs: ["Hot wash → county strategy router"],
  },
  {
    id: "training",
    label: "Training",
    sourceOfTruth: "training-modules-data + progression unlocks",
    keyRoutes: ["/admin/training"],
    keyToolLifecycles: ["kelly_os_intelligence"],
    keyKpis: ["modulesComplete", "unlockGaps"],
    typicalBlockers: ["Role missing required modules"],
    observationPrefixes: ["training_"],
    humanGates: ["Supervisor sign-off for sensitive modules"],
    orchestrationOutputs: ["Training gap → dashboard unlock router"],
  },
  {
    id: "dashboard_ux",
    label: "Dashboard UX",
    sourceOfTruth: "dashboard-builder + dashboard-orchestration",
    keyRoutes: ["/admin/ai-command-center/dashboard-builder"],
    keyToolLifecycles: ["dashboard_nav_sprint9", "single_campaign_hardening"],
    keyKpis: ["moduleUsage", "blueprintSaved"],
    typicalBlockers: ["Too many blocks", "Role mismatch"],
    observationPrefixes: ["dashboard_"],
    humanGates: ["Safety guard on blocks"],
    orchestrationOutputs: ["Dashboard simplification plan"],
  },
  {
    id: "memory",
    label: "Memory",
    sourceOfTruth: "agent-memory-write-planner + memory review store",
    keyRoutes: ["/admin/ai-command-center"],
    keyToolLifecycles: ["agent_user_intelligence"],
    keyKpis: ["pendingMemoryReviews"],
    typicalBlockers: ["Unreviewed candidates"],
    observationPrefixes: ["memory_"],
    humanGates: ["All writes approved"],
    orchestrationOutputs: ["Memory candidate packages"],
  },
  {
    id: "tool_builder",
    label: "Tool Builder",
    sourceOfTruth: "tool-builder-queue.json",
    keyRoutes: ["/admin/ai-command-center/tool-builder"],
    keyToolLifecycles: ["kelly_os_intelligence"],
    keyKpis: ["openTickets", "frictionDerived"],
    typicalBlockers: ["Repeated UX friction"],
    observationPrefixes: ["tool_builder_"],
    humanGates: ["Build tickets human-prioritized"],
    orchestrationOutputs: ["Sprint recommender", "System improvement package"],
  },
];

export function getOrchestrationDomain(id: CampaignDomainId): OrchestrationDomainSpec | undefined {
  return ORCHESTRATION_DOMAINS.find((d) => d.id === id);
}
