import { contractToCatalogEntry, type CampaignAiToolContract } from "@/lib/campaign-events/ai-tools/tool-contract";
import type { AiToolEntry } from "@/lib/campaign-events/ai-tools-master-catalog";

const SPRINT = 16;
const L = "campaign_orchestration_intelligence" as const;
const ORCH = "src/lib/agents/orchestration/";
const ROUTE = ["/admin/ai-command-center"] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

export const OBS_ORCHESTRATION = [
  "orchestration_state_loaded",
  "orchestration_diagnosis_generated",
  "orchestration_workflow_planned",
  "orchestration_human_gate_checked",
  "orchestration_cross_domain_fusion",
] as const;

export const ORCHESTRATION_INTELLIGENCE_TOOL_CONTRACTS: CampaignAiToolContract[] = [
  c({ id: "campaign-orchestration-engine", name: "Campaign orchestration engine", purpose: "Top-level orchestration coordinator across domains.", currentStatus: "partial", trigger: "Command center orchestration panel", inputs: "period", outputs: "OrchestrationDiagnosis + plans", readsFrom: "signal loader", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only coordination", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: ["orchestration_diagnosis_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-state-loader", name: "Campaign state loader", purpose: "Build CampaignState from domain signals.", currentStatus: "partial", trigger: "Orchestration load", inputs: "period", outputs: "CampaignState", readsFrom: "load-campaign-orchestration-signals", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Graceful degradation", deterministicHelperPath: `${ORCH}load-campaign-orchestration-signals.ts`, routesUsingTool: [...ROUTE], observationEvents: ["orchestration_state_loaded"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-state-summarizer", name: "Campaign state summarizer", purpose: "Plain-language executive summary of CampaignState.", currentStatus: "partial", trigger: "After state load", inputs: "CampaignState", outputs: "summary text", readsFrom: "state", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}campaign-state-types.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "cross-domain-signal-loader", name: "Cross-domain signal loader", purpose: "Load OS, county, comms, finance, training slices.", currentStatus: "partial", trigger: "Orchestration boot", inputs: "period", outputs: "OrchestrationSignalBundle", readsFrom: "domain loaders", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Missing → blocker not crash", deterministicHelperPath: `${ORCH}load-campaign-orchestration-signals.ts`, routesUsingTool: [...ROUTE], observationEvents: ["orchestration_state_loaded"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "orchestration-reasoning-engine", name: "Orchestration reasoning engine", purpose: "Deterministic diagnosis, blockers, opportunities.", currentStatus: "partial", trigger: "State ready", inputs: "CampaignState", outputs: "OrchestrationDiagnosis", readsFrom: "state", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No LLM required V1", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: ["orchestration_diagnosis_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-priority-ranker", name: "Campaign priority ranker", purpose: "Rank urgent actions across domains.", currentStatus: "partial", trigger: "Diagnosis", inputs: "actions[]", outputs: "ranked", readsFrom: "state", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-risk-detector", name: "Campaign risk detector", purpose: "Surface compliance, send, and finance risks.", currentStatus: "partial", trigger: "Diagnosis", inputs: "state", outputs: "risks[]", readsFrom: "gates + domains", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-opportunity-detector", name: "Campaign opportunity detector", purpose: "Find momentum and growth opportunities.", currentStatus: "partial", trigger: "Diagnosis", inputs: "state", outputs: "opportunities[]", readsFrom: "domains", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-momentum-interpreter", name: "Campaign momentum interpreter", purpose: "Interpret strategic momentum from unified context.", currentStatus: "idea", trigger: "Weekly review", inputs: "unified context", outputs: "momentum narrative", readsFrom: "campaign-intelligence", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-operating-rhythm-builder", name: "Campaign operating rhythm builder", purpose: "Daily/weekly operating cadence from OS state.", currentStatus: "idea", trigger: "CM morning", inputs: "period", outputs: "rhythm plan", readsFrom: "os-control", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "cross-domain-workflow-planner", name: "Cross-domain workflow planner", purpose: "Build multi-step workflows across domains.", currentStatus: "partial", trigger: "Diagnosis recommendations", inputs: "workflow ids", outputs: "OrchestrationWorkflowPlan[]", readsFrom: "templates", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Plans only", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: ["orchestration_workflow_planned"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-chain-builder", name: "Workflow chain builder", purpose: "Ordered step chains with dependencies.", currentStatus: "partial", trigger: "Workflow select", inputs: "template id", outputs: "steps", readsFrom: "ORCHESTRATION_WORKFLOW_TEMPLATES", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-dependency-resolver", name: "Workflow dependency resolver", purpose: "Resolve step dependsOn ordering.", currentStatus: "partial", trigger: "Chain build", inputs: "steps", outputs: "ordered steps", readsFrom: "plan", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-owner-router", name: "Workflow owner router", purpose: "Assign ownerRole per step.", currentStatus: "partial", trigger: "Plan build", inputs: "steps", outputs: "owners", readsFrom: "plan", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-handoff-builder", name: "Workflow handoff builder", purpose: "Domain handoff routes between steps.", currentStatus: "partial", trigger: "Cross-domain plan", inputs: "plan", outputs: "handoffs", readsFrom: "os-control", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-readiness-checker", name: "Workflow readiness checker", purpose: "Score plan readiness vs blockers.", currentStatus: "partial", trigger: "Before present plan", inputs: "plan + blockers", outputs: "readinessScore", readsFrom: "state", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-execution-package-builder", name: "Workflow execution package builder", purpose: "Checklists + routes for human execution.", currentStatus: "partial", trigger: "Approved plan", inputs: "plan", outputs: "execution package", readsFrom: "plan", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "prepared_only", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-action-router", name: "Role action router", purpose: "Route actions to role copilots.", currentStatus: "partial", trigger: "Orchestration", inputs: "role + actions", outputs: "roleActions", readsFrom: "role-copilots", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE, "/admin/ai-command-center/copilots"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-manager-daily-plan-builder", name: "CM daily plan builder", purpose: "Campaign manager daily orchestration plan.", currentStatus: "partial", trigger: "CM role", inputs: "diagnosis", outputs: "daily plan", readsFrom: "campaign-manager-daily template", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-daily-briefing-orchestrator", name: "Candidate daily briefing orchestrator", purpose: "Candidate-safe cross-domain briefing.", currentStatus: "idea", trigger: "Candidate role", inputs: "state", outputs: "briefing", readsFrom: "copilots", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No sensitive finance detail", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-workload-balancer", name: "Volunteer workload balancer", purpose: "Balance volunteer assignments vs events.", currentStatus: "idea", trigger: "Volunteer domain weak", inputs: "volunteer + events", outputs: "balance plan", readsFrom: "volunteer_system", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE, "/admin/volunteers"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "field-priority-orchestrator", name: "Field priority orchestrator", purpose: "County + field daily priorities.", currentStatus: "partial", trigger: "Field role", inputs: "county state", outputs: "field plan", readsFrom: "county-intelligence", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE, "/admin/county-intelligence"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-priority-orchestrator", name: "Communications priority orchestrator", purpose: "Top comms moves from intelligence engine.", currentStatus: "partial", trigger: "Comms domain", inputs: "comms context", outputs: "comms actions", readsFrom: "communications-intelligence-engine", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No send", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE, "/admin/communications/intelligence"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "intern-safe-work-orchestrator", name: "Intern safe work orchestrator", purpose: "Restrict intern orchestration to safe tasks.", currentStatus: "partial", trigger: "Intern role", inputs: "gates", outputs: "safe queue", readsFrom: "human-approval-gate-matrix", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Intern safe only", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-volunteer-comms-fusion-engine", name: "County-volunteer-comms fusion", purpose: "Fuse county gaps with volunteer and comms plans.", currentStatus: "idea", trigger: "Weak county", inputs: "county + volunteer + comms", outputs: "fusion package", readsFrom: "three domains", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: ["orchestration_cross_domain_fusion"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-county-volunteer-planner", name: "Event-county-volunteer planner", purpose: "Event prep with county and volunteer alignment.", currentStatus: "partial", trigger: "prepare-county-visit", inputs: "event id", outputs: "plan", readsFrom: "event + county + volunteer", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: ["orchestration_cross_domain_fusion"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "finance-event-compliance-fusion-engine", name: "Finance-event-compliance fusion", purpose: "Tie event costs to finance and compliance.", currentStatus: "idea", trigger: "Event finance review", inputs: "event + finance", outputs: "fusion", readsFrom: "finance sprint8", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No auto post", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "hotwash-to-county-strategy-router", name: "Hot wash to county strategy router", purpose: "Route hot wash learnings into county strategy.", currentStatus: "partial", trigger: "Post event", inputs: "hot wash", outputs: "county updates", readsFrom: "hot-wash-intelligence", writesTo: "memory candidates", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Memory approval", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "training-to-dashboard-unlock-router", name: "Training to dashboard unlock router", purpose: "Connect training gaps to dashboard unlocks.", currentStatus: "partial", trigger: "Training gap", inputs: "progress", outputs: "unlock plan", readsFrom: "training-unlock-engine", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE, "/admin/training"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-to-volunteer-retention-router", name: "Comms to volunteer retention router", purpose: "Retention sequences for volunteer segments.", currentStatus: "idea", trigger: "Volunteer push", inputs: "segments", outputs: "sequence plan", readsFrom: "communications sequences", writesTo: "drafts only", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Draft only", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-to-event-calendar-router", name: "County to event calendar router", purpose: "Propose events from county gaps onto calendar.", currentStatus: "idea", trigger: "County activation", inputs: "county gaps", outputs: "event proposals", readsFrom: "county-intelligence", writesTo: "tentative only", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No GCal auto", deterministicHelperPath: `${ORCH}orchestration-workflow-planner.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "orchestration-memory-candidate-builder", name: "Orchestration memory candidate builder", purpose: "Propose memory from cross-domain patterns.", currentStatus: "partial", trigger: "Learning loop", inputs: "observations", outputs: "memory candidates", readsFrom: "agent-memory-write-planner", writesTo: "review queue", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human approval", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "orchestration-observation-miner", name: "Orchestration observation miner", purpose: "Mine observation stream for friction patterns.", currentStatus: "partial", trigger: "Periodic", inputs: "observations", outputs: "patterns", readsFrom: "user-observations", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No PII export", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-tool-gap-orchestrator", name: "Campaign tool gap orchestrator", purpose: "Align tool-builder queue with domain gaps.", currentStatus: "partial", trigger: "Gap analysis", inputs: "registry + queue", outputs: "gap report", readsFrom: "tool-builder-queue", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE, "/admin/ai-command-center/tool-builder"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "system-improvement-package-builder", name: "System improvement package builder", purpose: "Bundle improvements for engineering sprint.", currentStatus: "idea", trigger: "Tool gaps", inputs: "gaps", outputs: "improvement package", readsFrom: "tool-builder", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-reasoning-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "orchestration-sprint-recommender", name: "Orchestration sprint recommender", purpose: "Recommend next implementation phase.", currentStatus: "partial", trigger: "Roadmap review", inputs: "state + roadmap", outputs: "phase recommendation", readsFrom: "ORCHESTRATION_BUILD_ROADMAP", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ORCH}orchestration-readme.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "orchestration-human-gate-enforcer", name: "Orchestration human gate enforcer", purpose: "Enforce safe/gated/forbidden on orchestration outputs.", currentStatus: "partial", trigger: "Any execute path", inputs: "actionType", outputs: "allowed", readsFrom: "human-approval-gate-matrix", writesTo: "—", humanApprovalRequired: false, riskLevel: "high", guardrails: "Deny forbidden", deterministicHelperPath: "src/lib/agents/os-control/human-approval-gate-matrix.ts", routesUsingTool: [...ROUTE], observationEvents: ["orchestration_human_gate_checked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "orchestration-safe-action-router", name: "Orchestration safe action router", purpose: "Route only safe actions without review.", currentStatus: "partial", trigger: "Action routing", inputs: "action", outputs: "route", readsFrom: "gates", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Safe only", deterministicHelperPath: "src/lib/agents/os-control/human-approval-gate-matrix.ts", routesUsingTool: [...ROUTE], observationEvents: ["orchestration_human_gate_checked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "orchestration-autonomy-boundary-checker", name: "Orchestration autonomy boundary checker", purpose: "Block mass send, GCal write, finance post.", currentStatus: "partial", trigger: "Runtime", inputs: "tool id", outputs: "blocked boolean", readsFrom: "CAMPAIGN_AI_HUMAN_CONTROL_RULES", writesTo: "—", humanApprovalRequired: false, riskLevel: "high", guardrails: "Always block forbidden", deterministicHelperPath: "src/lib/campaign-events/ai-tools/tool-contract.ts", routesUsingTool: [...ROUTE], observationEvents: ["orchestration_human_gate_checked"], futureAutomationPath: "", testChecklist: [] }),
];

export const ORCHESTRATION_INTELLIGENCE_TOOL_COUNT = ORCHESTRATION_INTELLIGENCE_TOOL_CONTRACTS.length;

export const ORCHESTRATION_INTELLIGENCE_CATALOG_ENTRIES: AiToolEntry[] =
  ORCHESTRATION_INTELLIGENCE_TOOL_CONTRACTS.map(contractToCatalogEntry);

/** Tools that must never auto-execute without human review. */
export const ORCHESTRATION_FORBIDDEN_AUTO_ACTIONS = [
  "mass-email-send",
  "gcal-promote-without-approval",
  "finance-transaction-post",
  "voter-file-export",
  "autonomous-outreach",
] as const;

export function assertOrchestrationSafetyBoundaries(): { ok: boolean; violations: string[] } {
  const violations: string[] = [];
  for (const tool of ORCHESTRATION_INTELLIGENCE_TOOL_CONTRACTS) {
    if (tool.riskLevel === "blocked") violations.push(`${tool.id}: blocked risk in catalog`);
    if (tool.id.includes("send") && !tool.humanApprovalRequired) {
      violations.push(`${tool.id}: send-related tool must require human approval`);
    }
  }
  return { ok: violations.length === 0, violations };
}
