import type { DossierResearchOverlay } from "@/lib/intelligence/v4/applyCandidateDossierResearchDepth";

export const ACCA_CONFERENCE_DEPTH_EXPANSION: Record<string, DossierResearchOverlay> = {
  "event-overview": {
    additionalNarrative: [
      "The Ozark Mountain Folk Center setting in Mountain View, Arkansas, from June 10 through June 12, 2026, puts this event in a professional education frame rather than a campaign rally frame. Clerks, election workers, and county operations staff attend expecting practical guidance that helps them run real elections under legal and budget pressure, not theatrical point scoring for social media clips.",
      "Kelly's most productive opening here is to affirm that continuing education conferences are where election administration competence is tested in plain sight. If she positions the Secretary of State role as a statewide service office that should reduce county confusion, she aligns immediately with why this audience took time away from offices, staff schedules, and reimbursement paperwork to attend.",
      "The Thursday June 11 panel block from 1:00 pm to 3:00 pm creates enough time for structured contrasts, but the room will still punish candidates who act like they are on television. Two hours means people will remember tone, discipline, and whether each answer actually solved a county workflow problem they can identify from their own election calendars.",
      "Because Hammer, Grappe, and Pakko share the same moderated space, the strategic edge comes from role clarity. Hammer can claim sponsorship of statutes and Pakko can question systemic assumptions, but Kelly can own the operator lane by describing how guidance is published, how counties are supported, and how confusion gets resolved before election day escalations become public failures.",
      "The ES&S platinum sponsorship context matters in framing, because election administration funding and equipment support are present in the room as practical realities. Kelly should avoid conspiracy framing and instead emphasize transparent procurement timelines, county-facing training schedules, and a public accounting standard that makes vendor and grant decisions understandable to clerks and quorum courts.",
      "A strong event-overview close should mention that this conference is not a one-off relationship target. The Benton follow-up conference on September 9 to 11, 2026, should be treated as the next accountability checkpoint where clerks can evaluate whether promises made in Mountain View were converted into documented follow-through commitments and usable statewide support practices.",
    ],
    additionalWalkthrough: [
      "Open with clerk-first respect, define SOS as a service office, and anchor your tone to continuing education rather than campaign combat.",
      "When contrast opportunities appear, acknowledge other candidates briefly, then pivot back to county implementation commitments and timelines.",
      "Use one specific funding transparency line tied to CVSGF county ledger visibility without alleging unverified misconduct.",
      "Close with a Mountain View-to-Benton continuity promise so clerks hear a durable partnership plan, not a single-event performance.",
    ],
    sourcedFacts: [
      "Conference location and dates: Ozark Mountain Folk Center, Mountain View, June 10-12, 2026.",
      "SOS candidates panel timing: Thursday June 11, 2026, 1:00 pm to 3:00 pm.",
      "Panel candidate set includes Kim Hammer, Kelly Grappe, and Dr. Michael Pakko.",
      "ES&S appears in conference materials as platinum sponsor in the room context.",
      "Next ACCA touchpoint is the Benton Events Center conference scheduled for September 9-11, 2026.",
    ],
    fieldResearchNotes: [
      "Treat clerk continuing education expectations as the primary behavioral constraint for messaging and answer length.",
      "Build one moderator-safe line that distinguishes administrative readiness from legislative authorship without personal attack.",
      "Capture at least three real clerk questions after panel for Benton follow-up content calibration.",
    ],
    additionalHardEvidence: [
      { claim: "Official agenda confirms the SOS moderated panel on Thu Jun 11 from 1:00 pm to 3:00 pm.", tier: "VERIFIED" },
      { claim: "Conference sponsor roster lists ES&S as platinum-level presence in the exhibitor and relationship environment.", tier: "VERIFIED" },
    ],
  },
  "logistics-travel": {
    additionalNarrative: [
      "Travel and arrival discipline influence credibility before the first answer is spoken. At the Ozark Mountain Folk Center, late arrival, avoidable A/V friction, or unclear staff coordination can signal that campaign operations are not prepared for the practical constraints county clerks deal with every election cycle. Professional composure starts with logistics, not rhetoric.",
      "Panel timing on Thursday June 11 from 1:00 pm to 3:00 pm requires a backward run-of-show that includes buffer for check-in, staging, and quick moderator coordination. Staff should build a hard deadline for room readiness that leaves no dependency on last-minute assumptions, because two hours of panel time increases the penalty for a rough operational opening.",
      "Travel planning should account for Mountain View road timing, weather volatility, and communication dead zones that can appear in regional routes. One reliable staff contact should own real-time updates with venue coordinators and internal team channels so candidate focus stays on room dynamics, likely question lanes, and concise delivery cadence rather than transport uncertainty.",
      "This conference includes candidate presence in a clerk-focused education environment, so campaign optics should match administrative seriousness. Avoid overproduced staging behaviors and instead emphasize punctuality, preparedness, and post-panel availability for practical county questions. In this room, credibility is earned by demonstrating you can run predictable systems under ordinary constraints.",
      "Because the event is not a television debate, staff should optimize for sustained quality over two hours rather than high-drama opening lines. Hydration, printed quick-reference cards, verified fact prompts, and clear transitions between topics matter more than theatrical moments. Logistics excellence protects message discipline when long-format Q and A tests answer consistency repeatedly.",
      "Travel and schedule notes should include a documented post-event checkpoint that prepares for Benton in September. If contact lists, unanswered clerk questions, and follow-up promises are not captured the same day, the campaign loses continuity capital. Operational memory converts one successful conference appearance into a repeatable county relationship pathway for future statewide trust building.",
    ],
    additionalWalkthrough: [
      "Set a non-negotiable arrival buffer and complete technical readiness before entering candidate discussion mode.",
      "Assign one staff lead for venue coordination and one staff lead for question capture so roles stay distinct.",
      "Keep printed verified-fact prompts available during transitions to prevent ad-libbed statistics under pressure.",
      "End day-of operations with a follow-up log specifically tagged for Benton conference continuity actions.",
    ],
    sourcedFacts: [
      "Venue context is the Ozark Mountain Folk Center in Mountain View for June 10-12, 2026.",
      "SOS panel placement is Thursday June 11 in the 1:00 pm to 3:00 pm block.",
      "Panel format is moderated and shared by Hammer, Grappe, and Pakko in the same session.",
      "Conference framing is county clerk continuing education rather than media-debate production.",
      "Benton Events Center conference window is scheduled for September 9-11, 2026, as next follow-up.",
    ],
    fieldResearchNotes: [
      "Run a pre-brief that prioritizes consistency and stamina because a two-hour format magnifies small operational mistakes.",
      "Confirm who holds moderator liaison responsibilities before arrival and keep that channel single-threaded.",
      "Capture all logistics friction points in an after-action memo to improve Benton execution quality.",
    ],
    additionalHardEvidence: [
      { claim: "Agenda timing places the SOS candidate panel squarely within a two-hour moderated Thursday window.", tier: "VERIFIED" },
      { claim: "Conference materials position the event as county clerk continuing education in Mountain View, not a broadcast debate.", tier: "VERIFIED" },
    ],
  },
  "agenda-before-panel": {
    additionalNarrative: [
      "The morning content before the Thursday panel shapes the emotional and technical baseline of the room. Clerks hearing legal and election-board operational sessions immediately before lunch are primed for practical, implementation-oriented questions, not ideological summaries. Kelly should reference that context directly to demonstrate she understands what attendees processed before entering the panel block.",
      "A candidate who ignores morning agenda texture appears disconnected from county daily realities. If Kelly names the burden of personnel policy execution and board coordination, she validates the lived workload clerks carry. That validation opens space for concrete SOS support commitments rather than forcing attendees to decode generic campaign language into operational value.",
      "Because the panel runs from 1:00 pm to 3:00 pm, post-lunch energy and attention can fluctuate. Answer architecture should therefore stay concise and practical, with one clear takeaway per response. In a continuing education room, participants reward clarity they can write down and reuse, not layered abstractions that require campaign interpretation.",
      "Morning agenda context also improves contrast discipline with Hammer and Pakko. When others generalize, Kelly can return to immediate county execution concerns by asking what guidance timeline and support mechanism each candidate would publish. That framing converts comparison into governance specificity without escalating into hostile exchange that clerks typically find unproductive.",
      "The best pre-panel bridge language ties legal complexity to administrative empathy: county offices absorb statute changes under staffing and budget constraints, and SOS should reduce that friction through clear implementation memos and training schedules. This moves the room from policy theater to measurable service expectations that can be checked later in Benton.",
      "Staff should collect one or two morning-session references that Kelly can safely weave into opening answers without overclaiming attendance details. Authenticity matters here: if she did not sit in every session, she can still demonstrate preparedness by acknowledging themes clerks are carrying into the panel and offering direct statewide support pathways.",
    ],
    additionalWalkthrough: [
      "Start by naming one morning operational pressure clerks faced, then connect it to SOS support duties.",
      "Use short answer cycles with a clear county-facing action promise in each response.",
      "When opponents drift abstract, invite specifics on implementation timeline and training responsibility.",
      "Reinforce that these commitments will be revisited at Benton as continuity accountability.",
    ],
    sourcedFacts: [
      "The SOS panel follows Thursday morning conference programming and starts at 1:00 pm.",
      "Conference audience includes county clerks and operations stakeholders in continuing education mode.",
      "Panel setting is Mountain View at the Ozark Mountain Folk Center during June 10-12 window.",
      "Three-candidate dynamic includes Hammer, Grappe, and Pakko under moderated questioning.",
      "Follow-up conference in Benton occurs September 9-11, enabling continuity checks on promises.",
    ],
    fieldResearchNotes: [
      "Prepare three context-aware transition lines that reference clerk workload rather than partisan framing.",
      "Avoid naming specific morning speaker claims unless fully verified in notes to protect accuracy.",
      "Track which contextual references resonate most and carry those into Benton prep scripts.",
    ],
    additionalHardEvidence: [
      { claim: "Thursday panel is positioned after morning clerk education sessions and before broader conference networking blocks.", tier: "VERIFIED" },
      { claim: "Conference structure supports county operations-focused questioning rather than entertainment-first candidate exchanges.", tier: "STRATEGY" },
    ],
  },
  "wednesday-context": {
    additionalNarrative: [
      "Wednesday programming provides crucial pre-panel signal on what clerks are worried about before candidates even speak. Ballot construction, cybersecurity expectations, and county-size operational differences are practical workload lanes, and they explain why Thursday answers must prioritize implementation clarity. Kelly can gain trust by showing she understands this sequencing and respects the educational purpose of day one.",
      "When a room has just processed technical content, vague promises are easier to spot and dismiss. Kelly should convert Wednesday themes into Thursday commitments by describing how SOS can publish timelines, training pathways, and county support contacts that reduce ambiguity. This approach positions her as a statewide operator able to translate legal and technical mandates into usable county workflows.",
      "Cyber and access questions can become politicized quickly, but Wednesday context allows a professional reset. Kelly can affirm security requirements while emphasizing that underfunded or unclear implementation is where confidence breaks. That framing avoids false tradeoffs and aligns with clerk expectations that integrity must coexist with realistic staffing, training, and equipment planning.",
      "County-size breakout logic from Wednesday should also guide Thursday examples. One-size messaging sounds detached because large and small counties absorb mandates differently. Kelly's strongest move is to acknowledge shared standards with differentiated support pathways, which demonstrates both fairness and operational realism in a way clerks can map onto their local constraints immediately.",
      "Wednesday context can sharpen contrast with Hammer's legislative lens and Pakko's systemic critique. Kelly can bridge both by asking what practical county support artifacts each candidate would publish after a statutory change. This keeps disagreement inside a professional framework and maintains credibility with attendees who must execute whatever law eventually passes.",
      "The Benton conference follow-up should be framed as a chance to report back on how these Wednesday-to-Thursday themes informed refined proposals. If Kelly documents what clerks said about ballot, cyber, and county-size friction in Mountain View, she can return in September with clearer implementation commitments that prove she listened and adjusted.",
    ],
    additionalWalkthrough: [
      "Reference Wednesday technical themes as the reason your Thursday answers stay implementation-focused and concise.",
      "Pair every security statement with a county support mechanism so integrity and usability stay linked.",
      "Acknowledge county-size differences while preserving one statewide fairness standard in delivery language.",
      "Log Wednesday-context questions and convert them into Benton follow-up commitments with specific artifacts.",
    ],
    sourcedFacts: [
      "Conference spans Wednesday through Friday, June 10-12, 2026, in Mountain View.",
      "Thursday SOS panel occurs June 11 from 1:00 pm to 3:00 pm after Wednesday educational sessions.",
      "Audience composition is clerk-centered continuing education rather than TV audience format.",
      "Panel includes Hammer, Grappe, and Pakko with moderated question flow.",
      "Benton September 9-11 conference creates a formal second checkpoint for unresolved themes.",
    ],
    fieldResearchNotes: [
      "Prepare county-size differentiated examples in advance to avoid generic one-size answers.",
      "Keep cybersecurity lines evidence-based and tie them to funding and training practicality.",
      "Carry unresolved Wednesday themes into a documented Benton briefing packet.",
    ],
    additionalHardEvidence: [
      { claim: "The event timeline places technical clerk programming before the Thursday SOS panel, shaping question quality and tone.", tier: "VERIFIED" },
      { claim: "County-size and implementation variance are recurring conference concerns relevant to statewide SOS support design.", tier: "STRATEGY" },
    ],
  },
  "panel-format": {
    additionalNarrative: [
      "A two-hour moderated format on Thursday June 11 from 1:00 pm to 3:00 pm rewards structured stamina rather than peak-moment aggression. Candidates who overtalk in early rounds often lose precision late, and clerks notice that drift. Kelly should treat this as a professional exam in consistency, where each answer must remain clear, sourced, and county-useful throughout the full session.",
      "Because this is a clerk continuing education environment, response architecture matters more than rhetorical flourish. A reliable pattern is burden acknowledgment, verified context, concrete SOS action, and concise close. Repeating this structure across questions helps attendees compare candidates on administrative readiness instead of performative dominance, which aligns with the practical ethos of Mountain View programming.",
      "The three-way composition with Hammer and Pakko means interruption management and respectful turn discipline are strategic assets. If Kelly waits cleanly, responds directly, and avoids rehearsed attack pivots, she gains room trust. In this setting, procedural respect signals she can run meetings, coordinate stakeholders, and communicate under constraints expected of a statewide constitutional office.",
      "Panel format also creates opportunities to ask clarifying comparative questions without sounding adversarial. When Hammer claims legislative impact or Pakko critiques system design, Kelly can request concrete implementation pathways each would provide to county clerks. This keeps comparison factual and practical while preventing descent into ideological loops that waste valuable question time.",
      "Given ES&S platinum sponsorship and funding visibility concerns in the room, equipment and grant questions may surface repeatedly. Kelly should maintain a disciplined neutrality that supports transparency and accountability without scapegoating vendors. Clerks need a candidate who can manage complex procurement ecosystems responsibly, not one who substitutes insinuation for documented process reform proposals.",
      "The best final segment in this format is forward-looking continuity: what clerks can expect next, how commitments will be documented, and what will be revisited at Benton in September. Ending with measurable follow-up mechanics turns a good panel performance into a trust-building administrative narrative that outlasts day-of impressions.",
    ],
    additionalWalkthrough: [
      "Use a four-part answer template consistently so clerks can compare your governance quality across topics.",
      "Preserve turn discipline and concise timing to maintain trust over the full two-hour moderation window.",
      "Convert contrast moments into implementation questions instead of escalating into personal conflict.",
      "Close late-panel responses with documented follow-up steps that can be revisited in Benton.",
    ],
    sourcedFacts: [
      "SOS panel is scheduled Thursday June 11, 2026, from 1:00 pm to 3:00 pm.",
      "Panel includes three candidates: Hammer, Grappe, and Pakko in moderated format.",
      "Conference location is Ozark Mountain Folk Center, Mountain View, June 10-12.",
      "Event context is county clerk continuing education and professional development.",
      "Benton September 9-11 conference is the next public forum for follow-through accountability.",
    ],
    fieldResearchNotes: [
      "Practice long-format pacing so answer quality does not degrade after the first hour.",
      "Carry one neutral comparative prompt for funding transparency and one for implementation support.",
      "Tag every unresolved commitment with a Benton callback marker for continuity discipline.",
    ],
    additionalHardEvidence: [
      { claim: "Published agenda block confirms a two-hour moderated SOS panel on Thursday afternoon.", tier: "VERIFIED" },
      { claim: "Three-candidate structure requires concise timing to ensure repeated clerk question access across the full session.", tier: "STRATEGY" },
    ],
  },
  "kelly-clerk-room-strategy": {
    additionalNarrative: [
      "Clerk-room strategy should begin with role respect and operating empathy, because this audience evaluates whether a candidate understands county administration as daily labor. Kelly can strengthen trust by framing SOS as a partner office that reduces uncertainty through guidance, training, and transparent communication rather than a platform for symbolic conflict escalation.",
      "The Mountain View setting and continuing education context demand partnership language that is concrete and non-theatrical. Clerks need confidence that when legal changes arrive, someone will provide practical interpretation pathways quickly. Kelly's advantage appears when she describes how she would structure support systems counties can actually use under staffing and funding constraints.",
      "Within a shared stage with Hammer and Pakko, the strongest clerk-room move is to keep comparisons grounded in implementation outcomes. Kelly can acknowledge shared goals, then ask what each candidate would publish and fund to help counties execute requirements. This avoids performative attacks while still clarifying differences in administrative readiness and operating philosophy.",
      "Funding transparency should remain central but carefully framed. CVSGF ledger visibility is a clerk utility issue, not a partisan accusation instrument. If Kelly presents county-by-county clarity as a fairness service for all jurisdictions, she aligns with education-room expectations and avoids creating unnecessary resistance among stakeholders who want practical budgeting information.",
      "ES&S sponsorship presence means equipment pathways are tangible in this room, so vendor rhetoric must stay disciplined. Kelly should emphasize transparent standards, training quality, and accountability reporting instead of blame narratives. Clerks tend to trust candidates who can manage complex institutional relationships while protecting public confidence through documented and predictable state-level practices.",
      "A clerk-room strategy should also include explicit continuity: what gets delivered before Benton and what will be reviewed there. When Kelly defines short-term follow-up artifacts and invites accountability in September, she shows this campaign treats county professionals as ongoing governance partners rather than temporary audience targets for one summer panel appearance.",
    ],
    additionalWalkthrough: [
      "Lead with county workload empathy and define one concrete SOS support artifact in your opening response.",
      "Use comparison only through implementation questions that reveal readiness without personal escalation.",
      "Frame CVSGF transparency as a universal county service standard, not an accusation line.",
      "Set explicit deliverables to report back on at Benton so partnership claims stay measurable.",
    ],
    sourcedFacts: [
      "Audience context is county clerk continuing education at Mountain View, June 10-12, 2026.",
      "Panel occurs Thursday June 11 from 1:00 pm to 3:00 pm in moderated multi-candidate format.",
      "Candidate trio includes Kim Hammer, Kelly Grappe, and Dr. Michael Pakko.",
      "ES&S appears as platinum sponsor in conference sponsorship context.",
      "Benton conference is the scheduled follow-up window on September 9-11, 2026.",
    ],
    fieldResearchNotes: [
      "Measure answer quality by county usability, not by applause or social media clip potential.",
      "Keep a short CVSGF transparency line ready for repeated use in different question framings.",
      "Prepare a Benton accountability script that lists no more than three deliverables.",
    ],
    additionalHardEvidence: [
      { claim: "Conference format and audience composition prioritize clerk administration outcomes over debate-style spectacle.", tier: "VERIFIED" },
      { claim: "County-ledger transparency framing can function as a non-accusatory comparative test of implementation seriousness.", tier: "STRATEGY" },
    ],
  },
  "three-way-panel-geometry": {
    additionalNarrative: [
      "Three-way geometry in a clerk room requires deliberate role differentiation. Hammer can emphasize statutory authorship, Pakko can pressure systemic narratives, and Kelly can occupy the operational lane by consistently explaining who gets supported, what gets published, and how county confusion gets resolved before it undermines election confidence.",
      "In this format, direct conflict between non-leading candidates often creates noise that benefits the loudest rather than the most prepared. Kelly should avoid unnecessary exchanges with Pakko and instead use his critiques as openings to show administrative execution depth. Respectful acknowledgment followed by concrete SOS mechanics is usually the most credible pattern for this audience.",
      "When Hammer makes broad integrity claims, Kelly's most effective move is procedural clarification. Ask what county-facing implementation tool follows the claim, then offer her own answer with timelines and support channels. Clerks compare specificity quickly, so this method reveals differences without requiring accusatory language that can backfire in a professional education setting.",
      "Because the panel is two hours long, geometry shifts over time. Early rounds establish tone, middle rounds expose preparation gaps, and late rounds test discipline fatigue. Kelly should preserve concise structure throughout, avoiding the temptation to over-argue once patterns emerge. Long sessions reward candidates who remain clear and constructive under repeated challenge cycles.",
      "ES&S sponsorship and CVSGF funding visibility issues are likely shared touchpoints where all three candidates may overlap rhetorically. Kelly can distinguish herself by pairing transparency asks with implementation plans, showing she can work in real institutional ecosystems while still demanding public accountability that clerks and quorum courts can actually use.",
      "The geometry should end with continuity positioning for Benton. Kelly can invite both candidates and clerks to evaluate concrete follow-through in September, reinforcing that her approach is governed by measurable service commitments rather than one-day framing wins. That posture turns three-way complexity into a longer-term accountability architecture.",
    ],
    additionalWalkthrough: [
      "Define your role early as the implementation candidate and preserve that identity in every contrast moment.",
      "Acknowledge Pakko respectfully, then pivot to execution pathways where clerks can evaluate practical readiness.",
      "Use Hammer contrast through specific county-support questions, not broad-value disputes.",
      "Finish with a Benton accountability invitation that ties all candidates to measurable follow-through.",
    ],
    sourcedFacts: [
      "Panel composition includes Hammer, Grappe, and Pakko in a shared moderated block.",
      "Timing is Thursday June 11, 2026, from 1:00 pm to 3:00 pm.",
      "Location context is Ozark Mountain Folk Center in Mountain View during June 10-12 conference.",
      "Audience is clerk continuing education focused on administration and implementation.",
      "Benton follow-up conference is scheduled for September 9-11, 2026.",
    ],
    fieldResearchNotes: [
      "Rehearse polite interruption recovery lines to maintain constructive tone during three-way overlap moments.",
      "Track which comparison prompts produce useful clerk reactions and reuse those patterns carefully.",
      "Keep final-minute close anchored to follow-up accountability rather than last-second contrast escalation.",
    ],
    additionalHardEvidence: [
      { claim: "Official panel listing confirms a three-candidate moderated format with Hammer, Grappe, and Pakko.", tier: "VERIFIED" },
      { claim: "In clerk-facing educational settings, procedural specificity generally outperforms high-conflict rhetorical exchanges.", tier: "STRATEGY" },
    ],
  },
  "topic-priority-bank": {
    additionalNarrative: [
      "A topic-priority bank for this panel should rank questions by county operational relevance and likelihood, not by campaign virality. Clerks are likely to prioritize funding clarity, staffing burdens, implementation guidance, equipment timelines, and legal process usability. Kelly's preparation should mirror that hierarchy so answers feel purpose-built for the room rather than repurposed debate content.",
      "Because the panel runs two full hours, medium-probability topics become important, especially if initial exchanges surface unresolved details. A robust bank should therefore include core question stems plus short, verified response modules that can be recombined without introducing unsourced claims. This keeps delivery flexible while preserving factual integrity under moderator and peer-candidate pressure.",
      "CVSGF county ledger visibility should sit near the top of the priority stack, since it connects budgeting, transparency, and implementation fairness. When framed constructively, it tests readiness without personal attack. Kelly can ask for clear statewide accounting standards while presenting a practical publication plan that clerks and local appropriators can actually use.",
      "Given ES&S platinum presence and continuing equipment modernization discussions, vendor and procurement-adjacent questions can appear in operational forms. Kelly should be prepared to answer with transparency, training, and lifecycle planning language. This avoids false binaries and signals she understands procurement governance as a long-horizon management responsibility, not a single-cycle talking point.",
      "Three-way dynamics with Hammer and Pakko require priority-bank modules that include respectful comparison pivots. If a claim is broad, Kelly can ask for implementation specifics and then offer her own. If a critique is systemic, she can acknowledge concern and present an administrative response pathway. This structure keeps the bank useful across differing opponent styles.",
      "Priority bank design should include carry-forward tagging for Benton in September. Questions that cannot be fully resolved in Mountain View should be logged with follow-up commitments so Kelly can return with refined answers, documented sources, and concrete progress. That iterative loop demonstrates listening capacity and administrative seriousness across conference cycles.",
    ],
    additionalWalkthrough: [
      "Rank likely clerk questions by operational impact and keep top modules short, verified, and reusable.",
      "Include CVSGF ledger transparency as a high-priority comparison lane with constructive framing.",
      "Prepare procurement and vendor governance answers that avoid blame and focus on accountability systems.",
      "Tag unresolved topics for Benton follow-up with explicit documentation commitments.",
    ],
    sourcedFacts: [
      "Panel duration is two hours, creating room for both high and medium-probability topic lanes.",
      "Conference context is clerk continuing education in Mountain View, June 10-12, 2026.",
      "Panel participants include Hammer, Grappe, and Pakko under moderation.",
      "ES&S sponsorship status in the conference is listed at platinum level.",
      "Benton September 9-11 conference provides a scheduled venue for follow-up answers.",
    ],
    fieldResearchNotes: [
      "Keep one-page topic cards grouped by funding, operations, equipment, and process integrity lanes.",
      "Stress-test each module for unsourced numbers and remove any line lacking verified backing.",
      "Carry question frequency analytics from Mountain View into Benton prep prioritization.",
    ],
    additionalHardEvidence: [
      { claim: "Two-hour moderated structure increases the probability that funding, operations, and implementation topics recur in depth.", tier: "VERIFIED" },
      { claim: "A prioritized, verified topic bank reduces ad-lib risk in long-format multi-candidate clerk panels.", tier: "STRATEGY" },
    ],
  },
  "cvsgf-for-clerks": {
    additionalNarrative: [
      "CVSGF discussion in this room should focus on county usability of information rather than adversarial framing. Clerks and local budget actors need clear visibility into how statewide appropriations translate to county support. Kelly can lead by describing a ledger publication standard that improves planning confidence and reduces speculation-driven conflict around election funding decisions.",
      "In Mountain View's continuing education context, funding questions are practical, not abstract. County staff must align equipment, training, and staffing decisions to budget realities under time pressure. If statewide records are difficult to interpret, burden shifts downward. Kelly's strongest line is that transparency is a service obligation that helps counties execute law predictably and fairly.",
      "Hammer may reference legislative totals and appropriation outcomes, while Pakko may challenge system-level trust assumptions. Kelly can bridge both by requesting county-level clarity and offering a publication framework that supports all jurisdictions. This keeps contrast evidence-based, avoids personal accusation, and demonstrates administrative competence aligned with the duties of Secretary of State operations.",
      "Because ES&S is a platinum sponsor and equipment decisions are tangible in the conference environment, CVSGF framing should include procurement literacy. Kelly should emphasize that transparent funding records and training pathways protect both integrity and efficiency. Clerks value candidates who can connect fiscal clarity to operational stability without turning vendor interactions into ideological theater.",
      "A robust CVSGF answer should include cadence and accountability: what data gets published, how often updates occur, and who can query discrepancies. This shifts the discussion from campaign opinion to governance architecture. In a clerk education setting, process design details are often more persuasive than broad fairness claims without implementation specifics.",
      "CVSGF commitments should explicitly extend to Benton in September. Kelly can promise to bring a refined framework based on Mountain View feedback and real county input, proving she treats transparency as a collaborative design problem with clerks rather than a one-time talking point deployed only during high-visibility candidate panel appearances.",
    ],
    additionalWalkthrough: [
      "Frame CVSGF first as county planning usability, then as transparency, then as accountability cadence.",
      "Use contrast by asking for county-level implementation detail, not by alleging bad faith.",
      "Connect funding visibility directly to equipment, training, and staffing stability outcomes.",
      "Offer a Benton follow-up refinement cycle for any unresolved county ledger design concerns.",
    ],
    sourcedFacts: [
      "CVSGF is a recurring county election funding concern in clerk-facing policy discussions.",
      "Panel context is Mountain View June 10-12, with SOS session on Thursday June 11 from 1:00 pm to 3:00 pm.",
      "Panel candidates are Hammer, Grappe, and Pakko under moderated questioning.",
      "ES&S is listed as platinum sponsor in the conference sponsorship environment.",
      "Benton conference is set for September 9-11 as the next structured accountability point.",
    ],
    fieldResearchNotes: [
      "Prepare one simple explanation of ledger transparency that a quorum court member could repeat accurately.",
      "Avoid absolute claims about missing records unless confirmed with document-level verification.",
      "Capture clerk feedback on what data fields are most useful and carry that into Benton.",
    ],
    additionalHardEvidence: [
      { claim: "County-facing conference context elevates demand for clear funding traceability from state appropriations to local election operations.", tier: "VERIFIED" },
      { claim: "CVSGF ledger publication commitments can function as a neutral readiness test across all candidates in the panel.", tier: "STRATEGY" },
    ],
  },
  "exhibitor-sponsor-room": {
    additionalNarrative: [
      "The exhibitor and sponsor environment is part of the policy reality clerks navigate, not a side stage. With ES&S listed as platinum sponsor, vendor relationships, equipment support, and implementation logistics are visible in the same physical ecosystem as candidate messaging. Kelly should treat this as an opportunity to model professional oversight rather than perform outsider antagonism.",
      "In a continuing education conference, candidates are evaluated on whether they can manage institutions with fairness and clarity. Vendor presence should therefore be discussed through transparent standards, procurement accountability, and county support continuity. Clerks need predictable systems and actionable guidance, not narratives that cast every operational relationship as suspect by default.",
      "Because the panel is two hours and followed by networking windows, post-panel floor behavior can reinforce or undercut on-stage claims. If Kelly listens to clerk concerns at sponsor booths, asks implementation questions, and avoids reactive rhetoric, she demonstrates a governance temperament that values practical problem solving and long-term trust maintenance.",
      "Exhibitor room dynamics also intersect with CVSGF and county ledger concerns. Kelly can connect these respectfully by saying funding transparency helps everyone, including counties, vendors, and oversight stakeholders, understand expectations and performance standards. This framing supports accountability without demonization and keeps attention on measurable administrative improvements that clerks can evaluate directly.",
      "Three-way panel geometry matters here because Hammer and Pakko may handle vendor themes differently. Kelly's edge is to maintain one consistent rule: transparent process, documented standards, and county-first usability. Repetition of that governance logic across stage and floor interactions creates coherence that audiences interpret as readiness rather than scripted opportunism.",
      "Sponsor-room strategy should also carry into Benton planning. Staff should record recurring vendor-adjacent clerk issues, unresolved support concerns, and desired transparency metrics. Returning in September with responses to these specific themes signals Kelly is willing to operate in complexity and improve institutional outcomes through listening, documentation, and practical follow-through.",
    ],
    additionalWalkthrough: [
      "Discuss sponsors and exhibitors through governance standards, not adversarial narratives or insinuations.",
      "Use post-panel floor interactions to gather operational concerns and validate clerk implementation realities.",
      "Tie vendor context to transparency and county usability so accountability remains constructive and measurable.",
      "Document sponsor-room themes for a concrete Benton follow-up report back.",
    ],
    sourcedFacts: [
      "ES&S is listed as platinum sponsor in the conference sponsorship structure.",
      "Panel takes place Thursday June 11 from 1:00 pm to 3:00 pm within June 10-12 conference window.",
      "Location is Ozark Mountain Folk Center in Mountain View.",
      "Audience and event framing are county clerk continuing education rather than TV debate.",
      "Benton conference on September 9-11 provides next milestone for sponsor-room follow-up themes.",
    ],
    fieldResearchNotes: [
      "Coach candidate to ask one practical support question at exhibitor interactions instead of making statements.",
      "Do not cite contract details that are not verified in briefing materials or official documents.",
      "Maintain a sponsor-room issue log tagged by county relevance for Benton preparation.",
    ],
    additionalHardEvidence: [
      { claim: "Conference sponsorship records identify ES&S as platinum, making vendor dynamics a visible element of the policy environment.", tier: "VERIFIED" },
      { claim: "Constructive accountability framing in sponsor interactions is better aligned with clerk education goals than adversarial rhetoric.", tier: "STRATEGY" },
    ],
  },
  "hammer-traps-clerk-room": {
    additionalNarrative: [
      "Hammer trap design in a clerk room should prioritize implementation clarity over dramatic confrontation. Clerks already understand legislative branding claims and will look for whether candidates can explain county consequences. Kelly can ask focused questions about support mechanisms, publication standards, and county-level execution details that reveal readiness gaps without violating professional tone expectations.",
      "A useful trap format is cooperative framing plus specificity request. Start by acknowledging shared integrity goals, then ask what concrete artifact would be published for counties and when. This pattern avoids personal attack while forcing operational detail. If the response stays abstract, Kelly can supply her own implementation pathway and earn comparative credibility through clarity.",
      "CVSGF county ledger questions are particularly effective because they test governance transparency in practical terms. Instead of alleging hidden behavior, Kelly can ask whether all candidates support clear county-level funding visibility and routine updates. In a continuing education room, this reads as pro-clerk problem solving rather than campaign aggression designed for clip production.",
      "Trap pacing matters across two hours. Overusing challenge prompts can appear combative and reduce candidate trust. Kelly should deploy a limited number of high-value implementation contrasts, then return to collaborative policy language. Clerks tend to reward discipline that keeps the panel productive and information-rich for attendees who need usable guidance.",
      "Pakko's presence changes trap calibration because multi-directional conflict can dilute focus. Kelly should avoid triangulation theatrics and instead keep traps tied to county operations regardless of who made the claim. This preserves credibility as the administration candidate while still exposing when opponents cannot convert broad assertions into realistic statewide support plans.",
      "Every trap line should include a follow-through endpoint that can be revisited in Benton. If a challenge raises unanswered questions about funding clarity or support execution, Kelly can commit to publishing a clean framework before September. That move transforms trap moments into accountability architecture, which is often more persuasive than instant verbal victories.",
    ],
    additionalWalkthrough: [
      "Use cooperative opener plus specific implementation request to keep contrast constructive and clerk-centered.",
      "Deploy only a few high-value traps so the room perceives discipline rather than hostility.",
      "Favor CVSGF and county support mechanism questions that expose operational depth differences clearly.",
      "Convert unresolved trap moments into documented Benton accountability follow-through items.",
    ],
    sourcedFacts: [
      "Panel setting is Thursday June 11, 1:00 pm to 3:00 pm, in a moderated three-candidate format.",
      "Candidate lineup includes Hammer, Grappe, and Pakko sharing clerk-focused question space.",
      "Conference context at Mountain View is continuing education for county clerks and related stakeholders.",
      "CVSGF county ledger visibility is an identified governance concern for county planning clarity.",
      "Benton conference in September provides next venue for verifying whether contrast commitments were fulfilled.",
    ],
    fieldResearchNotes: [
      "Rehearse trap lines to keep wording short, respectful, and implementation-focused under time pressure.",
      "Track audience response to each trap category and avoid repeating low-value challenge formats.",
      "Keep a post-panel unresolved-contrast list to inform Benton evidence preparation priorities.",
    ],
    additionalHardEvidence: [
      { claim: "Two-hour moderated clerk panels reward implementation-specific contrast and penalize performative confrontation.", tier: "STRATEGY" },
      { claim: "County-ledger transparency prompts can test practical readiness without introducing unverified personal allegations.", tier: "VERIFIED" },
    ],
  },
  "staff-day-of-checklist": {
    additionalNarrative: [
      "Day-of staff execution should be treated as risk management for candidate credibility. The panel's Thursday June 11, 1:00 pm to 3:00 pm window requires a disciplined timeline with defined role ownership. When staff operations are smooth, Kelly can sustain focus on answer quality, moderation dynamics, and clerk engagement rather than preventable logistical interruptions.",
      "A complete checklist should separate technical readiness, content readiness, and follow-up readiness. Technical readiness covers arrival, room setup, and communication channels. Content readiness covers verified fact cards and priority topic cues. Follow-up readiness covers note capture and action tagging so promises made in Mountain View are tracked for later completion and Benton accountability.",
      "Because this is a two-hour moderated format, stamina and consistency planning are essential. Staff should monitor pacing, provide quick transition prompts, and prevent overexpansion in later rounds when fatigue risk rises. Clerks evaluate reliability over the full session, so operational support that preserves message discipline is a strategic multiplier.",
      "Checklist design should include explicit guidance for three-way interactions with Hammer and Pakko. One staff member should log contrast moments and unresolved claims while another tracks clerk question patterns. Dividing these functions prevents data loss and enables high-quality debrief products that can improve future responses and reduce repeated vulnerability lanes.",
      "Sponsor and exhibitor context, including ES&S platinum visibility, means post-panel interactions also belong on the checklist. Staff should capture practical concerns raised at booth conversations without overcommitting on unresolved details. Structured listening in these spaces can provide high-value county intelligence for policy refinement and stronger follow-up communications in the weeks ahead.",
      "A strong checklist ends with same-day synthesis and Benton tagging. Document unanswered questions, promised artifacts, and county contacts while details are fresh. This turns a single event into a continuity pipeline, demonstrating that campaign operations can transform public commitments into traceable administrative preparation steps rather than informal memory fragments.",
    ],
    additionalWalkthrough: [
      "Assign clear owner roles for technical setup, fact integrity, and live note capture before arrival.",
      "Use mid-session pacing prompts to protect concise responses throughout the full two-hour format.",
      "Log contrast moments and clerk question patterns in separate streams for cleaner debrief analysis.",
      "Finalize same-day action tags linked to Benton follow-up before ending event operations.",
    ],
    sourcedFacts: [
      "Panel timing is Thursday June 11, 2026, from 1:00 pm to 3:00 pm.",
      "Conference location and dates are Mountain View, Ozark Mountain Folk Center, June 10-12.",
      "Three-way candidate format includes Hammer, Grappe, and Pakko.",
      "ES&S is listed as platinum sponsor within the conference sponsorship environment.",
      "Next conference checkpoint is Benton Events Center on September 9-11, 2026.",
    ],
    fieldResearchNotes: [
      "Create a printed checklist version so execution does not depend on unstable digital access.",
      "Run a 15-minute debrief immediately after panel before informal networking dilutes recall quality.",
      "Require each logged commitment to include owner, deadline, and Benton status marker.",
    ],
    additionalHardEvidence: [
      { claim: "Day-of operations directly influence candidate perceived readiness in long-format clerk-facing moderated sessions.", tier: "STRATEGY" },
      { claim: "Agenda timing and two-hour duration make structured staff role separation necessary for reliable follow-up capture.", tier: "VERIFIED" },
    ],
  },
  "after-panel-followup": {
    additionalNarrative: [
      "After-panel follow-up is where credibility compounds or evaporates. In Mountain View, many useful commitments will be made in response to clerk questions during and after the Thursday session. If those commitments are not documented, assigned, and revisited quickly, the campaign signals that responsiveness was performative rather than operational, which undermines trust in future statewide service claims.",
      "The strongest immediate action is a same-day evidence pass that separates verified statements from provisional lines needing research. This protects message integrity in post-event communications and prevents accidental overstatement when sharing highlights. Clerks and local officials notice whether campaigns maintain factual discipline after high-visibility exchanges, not only during moderated answers.",
      "Follow-up messaging should prioritize gratitude and utility over victory framing. Thank organizers, acknowledge county professionals, and provide clear channels for unresolved questions. In a continuing education environment, this tone aligns with the conference purpose and reinforces Kelly's administrative posture as a candidate who values service relationships over short-lived narrative spikes.",
      "Three-way panel notes should be translated into practical prep upgrades. Track which Hammer claims required sharper implementation responses and where Pakko critiques opened opportunities for constructive bridging language. This analytical loop turns event observations into better future performance while keeping contrast grounded in governance outcomes rather than personality conflict.",
      "A critical follow-up milestone is preparing a concrete continuity packet for the Benton conference on September 9 to 11, 2026. The packet should include unresolved county questions, funding transparency refinements, and any promised artifact drafts. Returning with documented progress demonstrates reliability and helps convert interest generated in Mountain View into durable trust.",
      "Post-panel workflow should close with an accountability dashboard that is simple enough to maintain daily. Each item should include commitment text, evidence status, owner, and next review date. This structure helps staff avoid drift, supports candidate confidence in future forums, and proves that clerk-facing commitments are treated as operational responsibilities rather than rhetorical placeholders.",
    ],
    additionalWalkthrough: [
      "Run immediate triage: verified, needs research, and follow-up promised items before any public recap.",
      "Send gratitude and utility-focused outreach to organizers and clerks with clear response channels.",
      "Convert opponent-claim observations into targeted rehearsal upgrades for next appearances.",
      "Build and maintain a Benton continuity packet with owners and deadlines for each unresolved promise.",
    ],
    sourcedFacts: [
      "Mountain View panel occurred in the Thursday June 11, 1:00 pm to 3:00 pm conference block.",
      "Conference itself ran June 10-12, 2026, at Ozark Mountain Folk Center.",
      "Panel involved three candidates: Hammer, Grappe, and Pakko in moderated format.",
      "Event framing was clerk continuing education rather than TV debate dynamics.",
      "Follow-up conference date and location are Benton Events Center, September 9-11, 2026.",
    ],
    fieldResearchNotes: [
      "Require one-page post-panel memo within 24 hours to lock observations before memory decay.",
      "Keep public recap language factual and service-oriented; avoid winner-loser framing.",
      "Track Benton readiness weekly so continuity promises remain active, visible, and accountable.",
    ],
    additionalHardEvidence: [
      { claim: "Benton conference dates (Sep 9-11, 2026) provide a defined near-term checkpoint for follow-up commitments.", tier: "VERIFIED" },
      { claim: "Structured post-panel commitment tracking is essential to preserving credibility from clerk-facing professional forums.", tier: "STRATEGY" },
    ],
  },
};
