import type { DossierResearchOverlay } from "@/lib/intelligence/v4/applyCandidateDossierResearchDepth";

export const KELLY_DOSSIER_RESEARCH_OVERLAY: Record<string, DossierResearchOverlay> = {
  "kelly-sos-office-overview": {
    additionalNarrative: [
      "The candidate dossier generated on 2026-06-04 frames this race as administration of a multi-division trust office, not a single-issue election lane. That framing matters because Arkansas SOS duties span elections, business and UCC filings, Capitol stewardship, records transparency, civic education, and county service in all seventy-five counties.",
      "In the same dossier, core strengths are not abstract slogans. They map directly to office functions: organizational leadership to cross-division management, training systems to clerk support, and civic education to lawful participation literacy. This mapping gives Kelly a repeatable answer architecture when moderators blend election integrity, petition process, and county implementation in one question.",
      "Public-record and attack-vector files show opponents will collapse the office into election conflict, especially around petition law and LEARNS-era politics. The defensible counter is function-by-function stewardship: publish guidance, train county users, and maintain predictable administration whether the user is a county clerk, small business owner, notary applicant, or first-time voter.",
      "Road-story corpus evidence reinforces why the overview should start with service logistics, not ideological language. Stories from clerks, poll workers, and volunteers describe Friday-afternoon rule drops and Monday operational uncertainty. Each story supports a practical SOS commitment: hotline responsiveness, plain-language implementation memos, and a county-facing training cadence tied to statute changes.",
      "Campaign bio details, including Verizon leadership, Rock Dental training-program development, Rose Bud roots, and foster-adoption stewardship, become strongest when attached to this office map. The overview section should train staff to translate biography into duty ownership: who needs support, what division is responsible, when guidance is issued, and how public trust is measured.",
    ],
    additionalHighlights: [
      "Use the 2026-06-04 dossier office map as the anchor before any contrast line.",
      "Tie every biography claim to one SOS function and one county-facing deliverable.",
      "Frame election integrity as one division responsibility inside a broader trust office.",
      "Use road-story operational details to make the service argument concrete and local.",
      "Reinforce that all seventy-five counties are users of the same state service platform.",
    ],
    additionalWalkthrough: [
      "Open with the office map sentence: elections, filings, Capitol, records, civic education, and county support.",
      "Select one audience-specific function, then bridge to Kelly's matching experience domain.",
      "If pushed into partisan conflict, pivot to implementation mechanics and county service obligations.",
      "Close with a measurable stewardship promise: published guidance, training rhythm, and response pathway.",
      "Debrief after rehearsal by checking whether each answer named a function, user, and service output.",
    ],
    sourcedFacts: [
      "2026-06-04 Kelly dossier explicitly defines SOS as a multi-division public trust office; status marked PRODUCTION.",
      "Dossier lists election administration across seventy-five counties as a central office responsibility.",
      "Dossier core strengths include organizational leadership, training systems, civic education, and rural service framing.",
      "Road-stories dataset (generated 2026-06-04) includes clerk and poll-worker implementation strain narratives.",
      "Public-record brief includes depoliticize-SOS framing and 'call balls and strikes' language from campaign messaging.",
      "Attack-vectors file identifies 'experience-readiness' and 'petition organizer vs administrator' as top-stage risk lanes.",
    ],
    fieldResearchNotes: [
      "Operator should keep a one-page SOS function card in the green room and force every mock answer through it.",
      "When moderators ask broad trust questions, avoid leading with opponent names; lead with service architecture.",
      "Flag any new numeric claims for claims-gate review before insertion into this overview lane.",
    ],
  },
  "kelly-organizational-leadership": {
    additionalNarrative: [
      "The dossier and campaign bio repeatedly reference roughly three decades of leadership experience, with Verizon and Rock Dental as the two most recognized anchors. In this overlay, the tactical objective is not biography recitation but administration transfer: systems reliability, staff development, budget discipline, and cross-functional execution under changing requirements.",
      "Attack-vector modeling indicates Hammer's strongest framing is legislative tenure versus outsider readiness. The reply should separate rule authorship from service administration. Kelly's leadership evidence is strongest when described as managing complex organizations where front-line teams needed clear standards, training continuity, escalation paths, and predictable accountability when requirements changed unexpectedly.",
      "Road stories, especially road-01 and road-05, provide field-level proof that county teams experience law changes as operational strain. Organizational leadership in the SOS role means preventing that strain from becoming failure points. This allows Kelly to present herself as implementation-first: she measures success by county usability, not by volume of statutory language.",
      "Public-record brief material on depoliticizing the office strengthens this section if leadership is framed as fairness infrastructure. A manager who sets transparent standards and applies them evenly across counties offers an operational definition of neutrality that avoids performative partisanship debates while still acknowledging legal obligations and election security responsibilities.",
      "For clerk and quorum-court audiences, this section should emphasize execution sequence: assess mandate impact, publish plain-language guidance, resource training, and monitor county feedback loops. This sequence maps corporate and healthcare-adjacent leadership patterns to SOS governance and gives moderators a concrete reason to trust Kelly's readiness.",
    ],
    additionalHighlights: [
      "Translate Verizon and Rock Dental experience into operational governance language, not title language.",
      "Contrast authorship politics with county implementation accountability and service delivery metrics.",
      "Use road-01 and road-05 to humanize how county staff absorb state-level changes.",
      "Define neutrality as consistent process enforcement, transparent guidance, and equal county treatment.",
      "Keep leadership answers tied to escalation pathways and Monday-morning execution readiness.",
    ],
    additionalWalkthrough: [
      "Start with one sentence on leadership scope, then immediately state the SOS function it informs.",
      "Use a county-facing example from road stories to show implementation consequences of poor guidance.",
      "Name the management sequence: guidance, training, hotline, and feedback correction loop.",
      "If opponent cites years in office, agree respectfully and pivot to administrator job requirements.",
      "End with a concrete promise about response standards for clerks and county election officials.",
    ],
    sourcedFacts: [
      "Candidate dossier core strengths cite three decades of organizational leadership and systems management.",
      "Campaign bio references Verizon leadership background and Rock Dental training-program development.",
      "Attack-vectors file labels 'experience-readiness' as HIGH prep priority and a predictable stage attack.",
      "Road story road-01 documents clerk concern after Friday mandate with no clear SOS contact.",
      "Road story road-05 describes poll-worker overtime from repeated election-procedure changes.",
      "Public-record brief records campaign commitment to depoliticize SOS and focus on county fairness.",
    ],
    fieldResearchNotes: [
      "Operator should coach Kelly to replace role nouns with process verbs: publish, train, answer, certify.",
      "In mock debates, penalize any answer that does not identify who in a county is being served.",
      "Keep one backup line ready if Hammer presses tenure: 'Years writing bills and years running service systems are different.'",
    ],
  },
  "kelly-leadership-development": {
    additionalNarrative: [
      "The dossier states Kelly built learning and leadership-development programs, and this is a direct fit for an office that must train county users under evolving legal conditions. Clerk support is not incidental; it is operational infrastructure, and training quality determines whether statutory change produces order or confusion across counties.",
      "Road-story evidence repeatedly describes procedural ambiguity rather than voter indifference. That distinction supports a training-first argument: many failures are preventable when state guidance is timely, plain-language, and role-specific. Leadership-development experience helps Kelly promise practical supports, including training calendars, implementation memos, and escalation points for county staff.",
      "Attack-vector files note that opponents will frame complexity as proof of toughness on integrity. Kelly's counter should be that integrity requires usability. A rule that cannot be taught consistently across seventy-five counties cannot be administered fairly, regardless of intent. This creates a pragmatic bridge between security goals and public access obligations.",
      "Public-record brief material around petition and LEARNS/CAPES attack surfaces should not dominate this section, but it can be referenced as why training clarity matters for lawful participation. The SOS office must explain process without partisan coloring, and Kelly's teaching background becomes a neutral service asset in that context.",
      "When this section is used in debates, the strongest close is a deliverable sentence: every new act gets plain-language county guidance, timeline expectations, and staffed support. That is how leadership-development evidence turns into institutional readiness rather than personal résumé defense.",
    ],
    additionalHighlights: [
      "Training design experience is a first-order SOS competency, not a secondary soft skill.",
      "Usability is an integrity requirement when laws must function in all seventy-five counties.",
      "Road stories support a guidance-gap diagnosis, not a motivation-gap diagnosis among county staff.",
      "Teaching clarity helps depoliticize process communication in petition and election administration.",
      "Close with training deliverables: calendar, memos, hotline, and county feedback channel.",
    ],
    additionalWalkthrough: [
      "Define the user first: clerk, poll worker, notary applicant, or filing desk staff.",
      "Explain the training artifact that solves the user's current friction point.",
      "Connect artifact quality to fairness and consistency across county lines.",
      "If opponent says 'more laws fixed it,' ask whether implementation supports were funded and delivered.",
      "Finish with a measurable commitment to guidance publication timing after statute changes.",
    ],
    sourcedFacts: [
      "Dossier narrative references Kelly's leadership-development and training-system work as transferable to SOS duties.",
      "Road story road-06 describes clerk uncertainty under Act 768 before clear guidance was published.",
      "Road story road-02 reports petition volunteers halted by confusing procedural requirements.",
      "Attack-vectors file warns against reducing integrity debates to raw rule volume without implementation planning.",
      "Public-record brief notes campaign promise to administer rules fairly and publish usable guidance.",
      "SOS function map in dossier includes county clerk training and poll-worker support responsibilities.",
    ],
    fieldResearchNotes: [
      "Staff should test every training line with one question: could a county clerk act on this Monday morning?",
      "In rehearsals, forbid abstract 'education matters' phrasing unless paired with a specific deliverable.",
      "If time is short on stage, prioritize one high-clarity training promise over multiple generic commitments.",
    ],
  },
  "kelly-civic-education": {
    additionalNarrative: [
      "The public-record brief identifies Stand Up Arkansas co-founder status as verified and cites Arkansas Times coverage dated 2025-10-08 for SOS candidacy context. This section should treat civic education as documented leadership, then immediately distinguish campaign-era organizer history from SOS-era neutral administration responsibilities.",
      "The same brief and attack vectors show LEARNS/CAPES spouse linkage and For AR Kids petition history are predictable bundling attacks. Kelly's highest-safety pattern is acknowledge lawful civic engagement, set a one-sentence household boundary, and pivot to equal administration for every lawful petition regardless of viewpoint.",
      "Road story material adds useful texture: volunteers and first-time participants frequently experience process as opaque. That supports Kelly's argument that civic education is not persuasion; it is procedural literacy delivered by a trust office. SOS communication quality can raise both compliance and public confidence without partisan messaging.",
      "Dossier framing around depoliticization aligns with this lane when language stays operational. Civic education should be presented as transparent explanation of rules, deadlines, and rights, not as campaign advocacy. This protects against activist-label attacks while preserving Kelly's credibility as someone who has done grassroots civic work.",
      "For debate deployment, this section works best in short cycles: own record, draw administration line, offer implementation tools, and return to county service. The goal is credibility with moderators and clerks who want predictable governance, not prolonged ideological argument that obscures office duties.",
    ],
    additionalHighlights: [
      "Stand Up Arkansas role is verified; use it confidently with a strict SOS neutrality bridge.",
      "2025-10-08 Arkansas Times citation is a durable source anchor for candidacy and civic profile.",
      "LEARNS/CAPES and For AR Kids belong in boundary language, not in extended debate relitigation.",
      "Civic education in SOS context means process clarity, not partisan mobilization rhetoric.",
      "Use volunteer confusion stories to justify plain-language statewide guidance commitments.",
    ],
    additionalWalkthrough: [
      "Acknowledge civic-education history in one sentence with source-grounded language.",
      "State the neutrality line: SOS serves every lawful petition and every county equally.",
      "Add one practical education tool: published FAQ, act summary, or hotline support window.",
      "If spouse question appears, keep household boundary to one sentence and pivot immediately.",
      "End on office duty, not on movement identity or opponent motivation claims.",
    ],
    sourcedFacts: [
      "Public-record brief marks 'stand-up-arkansas' fact as VERIFIED with Arkansas Times and DASS source references.",
      "Arkansas Times URL in brief documents Kelly's candidacy announcement date: 2025-10-08.",
      "Public-record brief marks LEARNS/CAPES spouse linkage as VERIFIED and high-risk framing lane.",
      "For AR Kids signature effort noted in brief with July 2024 reference context.",
      "Attack-vectors file lists 'stand-up-learns-family' as CRITICAL prep priority.",
      "Dossier includes civic education and lawful participation as mapped SOS-relevant competencies.",
    ],
    fieldResearchNotes: [
      "Operator should run 30-second drills that force a transition from organizer history to administrator obligations.",
      "Reject any rehearsal script that sounds apologetic about lawful civic engagement; own and pivot.",
      "Mark this lane as high moderator-probability whenever Hammer participates in the forum.",
    ],
  },
  "kelly-rural-arkansas": {
    additionalNarrative: [
      "Campaign biography and dossier materials place Rose Bud roots, small-farm stewardship, and rural engagement at the center of Kelly's credibility frame. This section should use those facts to support county-equity administration arguments, not nostalgia. The office serves every county, and rural implementation constraints must be explicitly acknowledged.",
      "Road-story corpus gives practical evidence that rule changes land harder where staffing is thin and training bandwidth is limited. Stories from South Arkansas, Delta, and clerk-centered settings show a repeating pattern: local administrators absorb state complexity without synchronized support, which is exactly the governance gap Kelly argues she will close.",
      "Attack vectors suggest opponents may frame rural language as campaign branding while defending bill authorship. The rebuttal is to name county execution burdens and specific support tools. Rural credibility rises when paired with actionable commitments such as hotline standards, training schedules, and public implementation memos after legislative sessions.",
      "Dossier function mapping links rural perspective to election administration, business filing usability, and equitable service delivery. That broad mapping is important because rural Arkansas users interact with SOS through more than elections, including UCC/business interfaces and document reliability needs that affect small enterprises and farm-adjacent economies.",
      "On stage, the section should avoid urban-versus-rural conflict framing. Kelly can position rural perspective as diagnostic competence: understanding how policy text becomes courthouse workflow under limited staffing. That stance resonates with clerks and quorum courts and keeps the answer in an administrator lane rather than culture-war theatrics.",
    ],
    additionalHighlights: [
      "Rose Bud and small-farm narrative supports county-equity governance when tied to operations.",
      "Road stories show recurring rural implementation strain after state-level election law shifts.",
      "Rural lane should include elections plus business filing and records usability responsibilities.",
      "Avoid identity signaling; focus on practical county support architecture and response standards.",
      "Operational rural framing undercuts outsider caricatures without personal attacks.",
    ],
    additionalWalkthrough: [
      "Open with county-equity principle: every county deserves usable rules and state support.",
      "Use one road-story vignette to show how staffing realities shape local implementation outcomes.",
      "Name two support levers: training cadence and rapid-response guidance publication.",
      "Bridge to broader SOS services so the answer does not collapse into one election topic.",
      "Close with a fairness sentence that includes both rural and urban counties.",
    ],
    sourcedFacts: [
      "Candidate dossier includes rural perspective among core strengths and maps it to county service duties.",
      "Campaign bio references Rose Bud roots and small-farm ownership context.",
      "Road story road-03 captures quorum-court concern over unfunded election mandate burdens.",
      "Road story road-05 captures poll-worker overtime stress in Delta-region framing.",
      "Dossier office overview names service obligations across all seventy-five Arkansas counties.",
      "Road story county labels are marked INTERPRETATION pending candidate confirmation before broadcast.",
    ],
    fieldResearchNotes: [
      "Before any county-specific mention, confirm labels from travel log to replace INTERPRETATION markers.",
      "Coach Kelly to use one rural story per answer; multiple stories in one response dilute clarity.",
      "Maintain a neutral tone toward urban counties to avoid unnecessary divide framing.",
    ],
  },
  "kelly-community-building": {
    additionalNarrative: [
      "Dossier narrative positions community building as a governance competency, not campaign ornament. In SOS context, coalition work is required whenever statute updates must be translated across clerks, election workers, business users, and public-information channels. Kelly's community leadership history supports this connective administrative role.",
      "Public-record brief and attack-vector materials show how easily opponents can cast civic network activity as partisan activism. The practical defense is to frame coalition skills around implementation outcomes: reducing confusion, increasing compliance, and preserving trust through clear, consistent communication standards applied across county and political differences.",
      "Road stories provide strong evidence for this section because they feature people who are not asking for ideological alignment; they are asking for predictability. Clerks and volunteers need communication pathways, not rhetoric spikes. Community-building experience becomes relevant when presented as cross-stakeholder problem solving under legal constraints.",
      "This lane complements public-trust stewardship by showing that trust is built relationally and operationally. A transparent office still fails if stakeholders cannot reach it, understand it, or anticipate its guidance cycle. Kelly's coalition and mentoring profile helps explain how she would maintain service legitimacy under contested conditions.",
      "In debate rehearsals, this section should be measured by de-escalation performance. If opponents push personal or tribal frames, Kelly can hold composure, validate public concern, and return to process commitments. That pattern models the temperament voters expect from a Secretary of State managing high-friction public systems.",
    ],
    additionalHighlights: [
      "Community-building is governance infrastructure when statutes require multi-stakeholder execution.",
      "Coalition framing should center clarity, compliance, and trust, not identity alignment.",
      "Road stories confirm demand for predictable communication more than ideological signaling.",
      "Relational credibility plus process consistency strengthens SOS public-legitimacy arguments.",
      "This section is a temperament asset in three-way and high-friction moderator formats.",
    ],
    additionalWalkthrough: [
      "Validate concern first, then shift to the office process that addresses it.",
      "Describe who receives guidance and how feedback returns to state-level adjustments.",
      "Keep language inclusive across party lines without diluting legal accountability standards.",
      "If debate tone escalates, shorten sentences and return to service commitments immediately.",
      "Close by naming trust outcomes: consistency, transparency, and equal treatment.",
    ],
    sourcedFacts: [
      "Dossier section identifies community building as a mapped competency for coalition and stakeholder engagement.",
      "Public-record brief records long civic and media trail that opponents may weaponize as activist labeling.",
      "Attack-vectors file flags culture-war bait as HIGH priority and recommends quick process pivots.",
      "Road story road-07 reports cross-partisan audience demand for a non-combative SOS posture.",
      "Dossier links community-building lane with public-trust and family-stewardship sections for message continuity.",
      "Campaign messaging includes depoliticization and county fairness as coalition-compatible framing anchors.",
    ],
    fieldResearchNotes: [
      "Staff should evaluate practice answers for calm cadence under interruption, not only factual accuracy.",
      "In clerk-facing events, prioritize relationship language tied to concrete support schedules.",
      "Prepare one bipartisan listening-room anecdote that does not require naming unverified attendees.",
    ],
  },
  "kelly-family-stewardship": {
    additionalNarrative: [
      "Campaign bio references foster care and adoption parenthood, and dossier text advises this lane as principle framing rather than credentials inflation. The strongest use is to connect family stewardship to institutional trust: Arkansans need public offices that are stable, fair, and dependable over long horizons.",
      "Public-record and attack-vector files indicate family-related questions can be used to bait emotional overextension or redirect from SOS responsibilities. Kelly's protective strategy is brevity: one sentence that grounds values, followed by an immediate return to office duty, county service, and transparent administration commitments.",
      "This section also supports intergenerational framing in civic education and election trust discussions. Instead of sentimental overreach, Kelly can articulate a governance ethic: decisions in this office affect families, schools, businesses, and civic participation years after any one campaign cycle has ended.",
      "Road stories can be used sparingly here to illustrate real families encountering system complexity, but only if tied to process improvements. The lane should never become a biography monologue. Its purpose is emotional credibility that reinforces competence, not emotional substitution for policy execution.",
      "In rehearsal, enforce a strict timing rule. If family story exceeds one sentence before the SOS bridge, trim it. Effective stewardship messaging sounds grounded and disciplined, signaling that Kelly can hold empathy and administrative rigor at the same time in a trust office setting.",
    ],
    additionalHighlights: [
      "Foster-adoption biography is best used as values context, not as technical qualifications proof.",
      "One-sentence family principle followed by immediate SOS duty bridge is the safest pattern.",
      "Intergenerational trust framing fits records, elections, and civic-education responsibilities.",
      "Avoid emotional overextension that invites off-topic probing and reduces policy airtime.",
      "Discipline in this lane signals executive steadiness under moderator pressure.",
    ],
    additionalWalkthrough: [
      "Deliver one concise family-value sentence tied to trust and responsibility.",
      "Bridge directly to a concrete SOS service commitment in the same breath.",
      "If opponent personalizes the exchange, decline escalation and return to office functions.",
      "Use this lane mostly in closing or audience-led personal questions, not policy rebuttals.",
      "After practice, time the segment and cut anything that dilutes administrative clarity.",
    ],
    sourcedFacts: [
      "Dossier family section states Kelly became a parent through foster care and adoption.",
      "Campaign bio also includes grandmother framing as future-generations context.",
      "Dossier explicitly warns against presenting family biography as technical SOS qualification.",
      "Public-record brief prioritizes verified civic and campaign facts over personal over-disclosure.",
      "Attack-vectors file warns culture-war bait can redirect candidate off office-plan content.",
    ],
    fieldResearchNotes: [
      "Operator should script a 12-second family bridge and rehearse it until automatic.",
      "If moderators do not invite personal context, skip this lane and stay in office-function framing.",
      "Keep family references positive and universal; avoid comparative language about opponents.",
    ],
  },
  "kelly-public-trust-stewardship": {
    additionalNarrative: [
      "The dossier describes SOS as a trust office where reliability and transparency are evaluated before ideology by many voters. This section should center public-facing service mechanics: published rules, explainable timelines, county responsiveness, and auditable processes that reduce confusion and improve confidence across political divides.",
      "Public-record brief includes verified campaign language on depoliticizing SOS and calling balls and strikes. That phrase works when paired with operational examples. Neutrality should be defined as consistent process administration, not as an absence of values, and certainly not as passivity when guidance is needed.",
      "Attack vectors indicate opponents may claim activist inconsistency or legislative superiority. Kelly's trust answer is institutional: the office serves lawful users regardless of affiliation, and service quality is measured by clarity, fairness, and execution speed. This keeps the response in governor-like management terrain instead of personality confrontation.",
      "Road stories support the trust frame by documenting moments when citizens or officials did not know where to turn for clear answers. A trust office cannot outsource understanding to rumor. Publishing plain-language implementation paths and maintaining staffed escalation channels are trust-building acts, not merely communications tasks.",
      "When deploying this section, end with a verification habit. Kelly can emphasize that new numbers, legal claims, and quotes are claims-gated before use. That discipline demonstrates respect for public facts and prevents single-line credibility damage that opponents can amplify in post-debate media cycles.",
    ],
    additionalHighlights: [
      "Define trust through process consistency, transparency, and response reliability across counties.",
      "Use depoliticize-SOS language only with concrete examples of fair administration behavior.",
      "Institutional stewardship framing beats personality conflict in moderator and clerk settings.",
      "Road-story evidence helps explain why trust depends on guidance availability, not slogans.",
      "Claims-gate discipline is itself a public-trust competency in high-scrutiny environments.",
    ],
    additionalWalkthrough: [
      "Lead with trust office definition and immediately name two operational trust levers.",
      "If activist-label attack appears, pivot to equal-service obligations and process safeguards.",
      "Use one short road-story detail to show consequences of missing guidance infrastructure.",
      "State how transparency will be delivered: publication cadence, documentation, and accountability.",
      "Close with a fact-discipline line emphasizing verified sourcing before public claims.",
    ],
    sourcedFacts: [
      "Dossier public-trust section calls SOS a trust office and stresses transparency and fairness.",
      "Public-record brief marks depoliticize-SOS campaign framing as VERIFIED via campaign site messaging.",
      "Attack-vectors file includes depoliticize lane as HIGH priority due to activist-label attacks.",
      "Road story road-04 highlights first-time voter demand for findable online guidance.",
      "Road story road-01 highlights county need for responsive SOS contacts after legal updates.",
      "Dossier references claims gate as mandatory before introducing new figures or quotes on stage.",
    ],
    fieldResearchNotes: [
      "Require every trust answer to include at least one mechanism, not only values language.",
      "Staff should track whether Kelly names who receives service: clerks, voters, or filing users.",
      "Avoid overpromising legislative outcomes; keep this lane anchored to SOS-administered functions.",
    ],
  },
  "kelly-debate-credential-intro": {
    additionalNarrative: [
      "Dossier guidance already defines the strongest introduction pattern as experience to skill to office. This overlay deepens that method by grounding each skill claim in sourced record clusters: organizational leadership from Verizon and Rock Dental, civic education from Stand Up Arkansas, and county-service orientation from road-story evidence.",
      "Attack-vector analysis warns that title-first answers invite easy dismissal or gotcha escalation. Kelly should avoid opening with employer names unless those names are immediately translated into governance capability. Moderators and clerk audiences respond better to process fluency than to résumé chronology, especially under tight response windows.",
      "Public-record brief confirms that opponents will try to turn biography into ideology proof. A disciplined credential intro can neutralize that by defining role obligations first, then offering one evidentiary sentence, then promising a service output. This sequencing limits vulnerability while preserving authenticity and confidence.",
      "Road stories provide vivid but concise insertion points. For example, a Friday-mandate story can illustrate why leadership and training capability are relevant to SOS administration. The story should be one sentence only in intro context, followed by clear office commitments to avoid drifting into anecdote-heavy territory.",
      "Use timing discipline: twenty-five to thirty seconds is the target in opening credential frames. Overlong intros reduce rebuttal flexibility and invite interruptions. The best performance profile is calm voice, one skill bridge, one office function, and one measurable service promise tied to county users.",
    ],
    additionalHighlights: [
      "Use skill-first intros; title-first intros are easier for opponents to undercut.",
      "Anchor each credential sentence in sourced dossier or public-record evidence clusters.",
      "One anecdote maximum in intro format, then pivot to office responsibility and service output.",
      "Sequence answers as obligation, evidence, implementation, and pledge.",
      "Target 25-30 second credential responses for interruption resilience.",
    ],
    additionalWalkthrough: [
      "Draft three credential intros keyed to leadership, training, and civic-education lanes.",
      "Practice each intro against interruption; preserve the office-function clause under pressure.",
      "Replace generic adjectives with concrete functions like train, publish, certify, and support.",
      "Insert one verified source cue when needed, then move back to forward-looking administration.",
      "End every intro with a county-facing service promise to signal practical readiness.",
    ],
    sourcedFacts: [
      "Dossier credential-intro section explicitly recommends experience-skill-office structure.",
      "Campaign bio names Verizon leadership and Rock Dental training-program leadership elements.",
      "Public-record brief verifies Stand Up Arkansas co-founder status and associated civic profile.",
      "Attack-vectors file identifies inexperience framing as a recurring Hammer lane.",
      "Road story set documents county implementation pain that credential intros can operationalize.",
      "Dossier maps credential themes to specific SOS functions rather than generalized biography claims.",
    ],
    fieldResearchNotes: [
      "Operator should red-flag any intro script that cannot be diagrammed as experience-skill-office.",
      "Maintain a short and long intro variant for TV versus town-hall forum formats.",
      "Track filler words in rehearsal; concise phrasing improves authority and time control.",
    ],
  },
  "kelly-30-second-bio": {
    additionalNarrative: [
      "The dossier's past-present-future framework is already strong, and this overlay adds source-grounded precision to each segment. Past should include leadership and training evidence from Verizon and Rock Dental plus civic education leadership references. Present should highlight county service intent. Future should define measurable SOS trust outputs.",
      "Public-record brief and attack vectors indicate biography openings can be hijacked into petition and spouse-adjacent attacks if phrasing is loose. Tight language prevents drift: acknowledge documented civic work, state current race role, and commit to fair administration for every lawful user without revisiting older campaign episodes in detail.",
      "Road-story content can sharpen the 'present' portion by showing why this candidacy is service-driven. One sentence about a clerk, volunteer, or first-time voter confusion incident gives urgency to the run without requiring negative attacks. It positions Kelly as responsive to implementation failures rather than ideological theater.",
      "For timing, keep the core version under twenty-eight seconds at debate pace. This leaves room for moderator interruption and follow-up while preserving the future-oriented pledge. Long bios often sacrifice the most important line, which is what Kelly will do inside SOS operations on day one and week one.",
      "Campaign bio anchors like Rose Bud roots and foster-adoption stewardship are useful in select venues but should not crowd out office framing in strict timed formats. The strongest 30-second bio is concise, sourced, and duty-centered, with clear county-level applicability and no unsourced claim risk.",
    ],
    additionalHighlights: [
      "Past-present-future structure should include sourced evidence, not only thematic placeholders.",
      "Keep civic-history references concise to avoid attack-vector detours during opening statements.",
      "Use one short road-story cue to explain candidacy motivation in operational terms.",
      "Protect the future pledge line; it carries the highest persuasion value in timed formats.",
      "Prioritize duty-centered wording over identity-centered wording in high-pressure forums.",
    ],
    additionalWalkthrough: [
      "Write a 28-second script and a 20-second compressed variant for hard-cut moderator formats.",
      "Test whether each clause maps to a source-backed fact from dossier or brief materials.",
      "Insert one county-service phrase so the bio sounds office-specific, not generic campaign copy.",
      "Practice with interruption at second 18 and preserve the closing administration promise.",
      "Review tape and remove any phrase likely to trigger unnecessary petition-history debates.",
    ],
    sourcedFacts: [
      "Dossier defines 30-second framework as past, present, and future with county-service close.",
      "Campaign bio references Verizon, Rock Dental, Rose Bud, Stand Up Arkansas, and foster/adoption context.",
      "Public-record brief documents activism attack surfaces that can consume bio time if not bounded.",
      "Attack-vectors file marks petition-organizer framing as CRITICAL and likely to appear early.",
      "Road story road-04 offers first-time voter clarity cue suitable for concise motivation framing.",
      "Dossier recommends under-30-second pacing to preserve moderator follow-up flexibility.",
    ],
    fieldResearchNotes: [
      "Staff should maintain bio scripts by format type: TV debate, ACCA panel, and small community forum.",
      "If the moderator already introduces party and résumé basics, skip duplicates and move to service pledge.",
      "Enforce a hard stop at the future commitment line to avoid overrun penalties.",
    ],
  },
  "kelly-experience-office-crosswalk": {
    additionalNarrative: [
      "The crosswalk section is the internal logic table behind nearly every reliable answer in this dossier. This overlay adds rehearsal emphasis: each row must contain one source-backed experience input, one SOS function output, and one implementation behavior so that staff can audit answer quality objectively.",
      "Source files already establish core row structure: organizational leadership, training systems, civic education, rural perspective, community building, family stewardship, and public trust. The value of this crosswalk is speed under pressure. Kelly can pivot across topics without losing functional alignment to SOS responsibilities.",
      "Attack-vector files confirm that opponents will attempt topic compression into petition conflict, tenure hierarchy, or activist labeling. A well-practiced crosswalk allows fast counter-moves: acknowledge concern, select matching row, deliver implementation answer, and avoid unforced rhetorical expansion beyond verified claim boundaries.",
      "Road stories should be attached to crosswalk rows as optional evidence boosters, not mandatory inclusions. For example, road-01 aligns with leadership and training rows; road-02 and road-06 align with civic-process clarity; road-05 aligns with county-support operations. This matrix prevents anecdote misuse and keeps context discipline.",
      "As new sections are added, including career timeline deep and public-record defensive modules, the crosswalk should function as the integration layer. It ensures chronology and defensive research do not become separate narratives but feed the same office-readiness argument with consistent language and sourced grounding.",
    ],
    additionalHighlights: [
      "Crosswalk rows should be auditable: source fact, office function, and implementation behavior.",
      "Use crosswalk as a rapid topic-switch tool under moderator or opponent pressure.",
      "Attach road stories to rows selectively to avoid anecdotal overload in short answers.",
      "Crosswalk prevents attack-vector compression from derailing office-function alignment.",
      "New timeline and defensive modules should plug into existing row logic, not replace it.",
    ],
    additionalWalkthrough: [
      "Build a rehearsal sheet where each row has a 15-second and 30-second answer variant.",
      "Run random-topic drills and require immediate row selection before speaking.",
      "Tag each row with one safe road story and one risk note for claims-status handling.",
      "After mock debates, score answers on row fidelity and verified-source compliance.",
      "Update the matrix after each forum with observed moderator patterns and effective pivots.",
    ],
    sourcedFacts: [
      "Dossier crosswalk section labels itself as a master competency matrix for SOS mapping.",
      "Core strengths in dossier correspond directly to crosswalk themes used throughout sections.",
      "Attack-vectors file identifies common compression attacks that crosswalk sequencing can neutralize.",
      "Road stories provide eight reusable field narratives with different function alignment opportunities.",
      "Public-record brief supplies verified defensive anchors for high-risk rows like civic education and petitions.",
      "Dossier related-section links indicate crosswalk is the primary bridge between modules.",
    ],
    fieldResearchNotes: [
      "Operator should keep a printed row matrix visible during rehearsal and spin-room prep.",
      "If an answer cannot be mapped to a row within five seconds, simplify and restart.",
      "Review for redundancy weekly so rows stay distinct and do not blur into generic talking points.",
    ],
  },
  "kelly-next-prep-modules": {
    additionalNarrative: [
      "The dossier presents this section as a navigation hub, and this overlay adds sequencing discipline based on source risk and debate probability. First pass should be office overview plus two priority sections, then move into public-record defensive drills and expected questions before any advanced contrast rehearsal.",
      "Public-record brief and attack vectors together show the highest damage potential comes from unsourced or poorly bounded answers, not from policy disagreement itself. Therefore, next-module workflow should embed claims-gate checks before final script lock, especially for petition history, spouse linkage, and media-clip contexts.",
      "Road-story modules belong in the middle of prep sequence, after core framing is stable. They are persuasive accelerators, but if introduced too early they can fragment answer architecture. Tie each story to one section objective, one function mapping, and one claims-status reminder before debate deployment.",
      "The addition of new sections in this pass, including career timeline deep and public-record defensive modules, should be integrated into nightly prep loops. Timeline work improves credibility consistency, while defensive work reduces unforced errors. Both should feed back into the 30-second bio and credential intro scripts.",
      "Operationally, this section should end each prep day with a short after-action review: what claims were used, what interruptions occurred, where pivots failed, and which modules need rerun. That cadence turns static research assets into a living debate system calibrated to real moderator behavior.",
    ],
    additionalHighlights: [
      "Prioritize modules by risk: office map, defensive record, then offensive contrast layers.",
      "Embed claims-gate checks before final script lock on every high-risk lane.",
      "Introduce road stories only after core answer architecture is stable and timed.",
      "Integrate timeline and defensive modules into nightly rehearsal loops.",
      "Use short after-action reviews to keep prep adaptive between events.",
    ],
    additionalWalkthrough: [
      "Run a pre-forum sequence: overview, two priority sections, public-record defensive, expected questions.",
      "Audit each script for unsourced claims and remove or flag before final rehearsal.",
      "Assign one operator to story-governance: when-to-use and claims-status compliance in real time.",
      "Complete a post-forum debrief within 30 minutes while memory is fresh and actionable.",
      "Update module priority list weekly based on opponent patterns and moderator trend data.",
    ],
    sourcedFacts: [
      "Dossier next-prep section lists linked modules: debate coaching, public record brief, opponent dossiers, claims gate.",
      "Public-record brief emphasizes verified lines and warns against unsupported legal or media assertions.",
      "Attack-vectors prep sequence includes culture-war pivots, petition drills, and diligence-log completion.",
      "Road-stories file includes explicit when-to-use fields and claims-status markers for each story.",
      "Dossier references candidate-eyes-only mirror materials requiring gating and distribution discipline.",
      "Existing section links point to expected questions and claims endpoints as core prep infrastructure.",
    ],
    fieldResearchNotes: [
      "Designate a single prep captain to enforce module order and prevent late-night random script drift.",
      "Record one rehearsal daily; review only interruption handling and pivot quality for efficiency.",
      "Flag unresolved diligence items in the prep checklist so candidate never improvises around missing verification.",
    ],
  },
  "kelly-career-timeline-deep": {
    additionalNarrative: [
      "This new section should give staff a chronology scaffold that prevents contradictory wording across interviews, debates, and printed materials. Use decade markers rather than unverified exact years when source precision is pending. The verified arc is Verizon leadership, Rock Dental training-development leadership, then SOS campaign built on civic education and county service framing.",
      "A timeline format improves credibility because it shows how competencies accumulated before this race. Early career leadership contexts establish systems discipline, mid-career training development establishes implementation capability, and recent civic and campaign work establishes public-facing governance motivation. Each phase should map to a present SOS function with no inflation.",
      "Public-record brief and dossier records support this narrative sequencing, while attack vectors highlight why chronology consistency matters. Opponents often exploit any mismatch in timeline phrasing as evidence of exaggeration. A pre-approved decade-based script reduces that risk and allows Kelly to answer quickly under cross-examination conditions.",
      "Include a campaign arc waypoint for 2025-10-08 candidacy announcement as a date anchor. Pair that with 2026 dossier generation references for prep context, then connect to day-one office commitments. This grounds the story in documented moments while keeping focus on future administration rather than nostalgia.",
      "In practice, the timeline should feed other sections rather than stand alone. Credential intro, 30-second bio, and crosswalk rows all benefit from stable chronology. Staff should maintain one canonical timeline text so every surrogate, social post, and debate prep deck uses identical sequence language and source notes.",
    ],
    additionalHighlights: [
      "Use decade markers for stable chronology when exact title dates are not yet fully packeted.",
      "Map each career phase to one SOS capability to avoid résumé-only storytelling.",
      "Anchor timeline with documented date points like 2025-10-08 candidacy announcement.",
      "Consistency across scripts blocks easy opponent attacks on timeline discrepancies.",
      "Maintain one canonical timeline source file for staff and surrogate alignment.",
    ],
    additionalWalkthrough: [
      "Draft a three-phase timeline: Verizon era, Rock Dental era, campaign and civic era.",
      "Attach one verified source cue to each phase and one SOS function mapping line.",
      "Rehearse a 20-second and 45-second version for different moderator prompts.",
      "Cross-check every timeline phrase against dossier, brief, and campaign bio references.",
      "Lock canonical wording and distribute to prep team to prevent drift.",
    ],
    sourcedFacts: [
      "Campaign bio references Verizon leadership and Rock Dental training-program development.",
      "Dossier generated 2026-06-04 describes approximately three decades of leadership experience.",
      "Public-record brief includes Arkansas Times candidacy announcement dated 2025-10-08.",
      "Dossier repeatedly maps leadership and training experience to SOS administrative duties.",
      "Stand Up Arkansas role appears as verified civic-education context in public-record brief.",
      "Attack-vectors emphasize readiness attacks where timeline clarity can strengthen credibility defense.",
    ],
    fieldResearchNotes: [
      "Collect resume packet and lock exact year ranges when available, then upgrade decade markers.",
      "Do not improvise new timeline dates on stage unless pre-cleared in claims gate.",
      "Keep this section synchronized with website bio copy and moderator handout language.",
    ],
  },
  "kelly-public-record-defensive": {
    additionalNarrative: [
      "This new defensive section should consolidate high-risk lines from `kellyCandidatePublicRecordBrief.ts` and `kellyCandidateResearchDepth.ts` into a controlled rehearsal map. Core lanes are Stand Up Arkansas identity framing, LEARNS/CAPES spouse linkage, For AR Kids petition history, media clips, and business-record diligence boundaries.",
      "Use the NOT_SEARCHED frame exactly where diligence is incomplete. Attack-vector content and brief guidance are clear: never claim clean CourtConnect or UCC outcomes until logged in staff diligence artifacts and counsel-reviewed. Defensive credibility comes from disciplined boundaries, not categorical denials unsupported by completed searches.",
      "Date and source anchors matter in this section. The Arkansas Times 2025-10-08 candidacy profile is a verified public anchor. Dem-Gaz CAPES references and July 2024 For AR Kids context should be cited as source hints without improvising details beyond what documented files currently support.",
      "For media-clip defense, keep answers short and procedural. The brief marks some media-trail material as PARTIAL, so avoid over-committing to quote disputes in live formats. Own lawful civic engagement, reassert administrator neutrality obligations, and return to office execution lines that are fully sourced and role-appropriate.",
      "This section should be rehearsed with interruption patterns because moderators may bundle multiple allegations in one prompt. The safe sequence is acknowledge known fact, set boundary where verification is partial or pending, and pivot to how SOS administration will treat lawful users equally under transparent published rules.",
    ],
    additionalHighlights: [
      "Consolidate verified, partial, and NOT_SEARCHED defensive lanes in one controlled script source.",
      "Never state clean-search outcomes before diligence logs and counsel review are complete.",
      "Use documented anchors: 2025-10-08 candidacy profile and brief-listed CAPES references.",
      "Keep media-clip defense short when verification status is PARTIAL.",
      "Practice bundled-attack responses with strict acknowledge-boundary-pivot sequencing.",
    ],
    additionalWalkthrough: [
      "Prepare lane cards for Stand Up, LEARNS/CAPES, For AR Kids, media trail, and diligence status.",
      "Tag each card VERIFIED, PARTIAL, or NOT_SEARCHED based on current source files.",
      "Rehearse one 15-second response per lane with a mandatory office-function pivot.",
      "Run combination drills where two or three lanes are bundled in one moderator question.",
      "Before event day, review diligence log status and update only pre-cleared wording.",
    ],
    sourcedFacts: [
      "Public-record brief marks Stand Up Arkansas role as VERIFIED with Arkansas Times and DASS cues.",
      "Public-record brief includes LEARNS/CAPES spouse lane as VERIFIED and sensitive on-stage terrain.",
      "Public-record brief references For AR Kids signature effort context in July 2024.",
      "Attack-vectors include court-record diligence warnings and prohibit premature clean-search claims.",
      "Public-record brief marks media paper trail category as PARTIAL with archive verification notes.",
      "Brief and attack vectors both instruct candidate not to fabricate denials of specific filings.",
      "Candidacy announcement source date in brief is 2025-10-08 from Arkansas Times.",
    ],
    fieldResearchNotes: [
      "Designate one operator to call out verification status during live prep and spin-room response drafting.",
      "If a question references an unknown clip or filing, default to boundary language and follow-up commitment.",
      "Update this section immediately after diligence log changes so candidate scripts remain synchronized.",
    ],
  },
  "kelly-road-stories-fieldbook": {
    additionalNarrative: [
      "This new fieldbook section compiles all eight road stories from `kelly-road-stories.json` and should be treated as a tactical deployment map, not a freeform anecdote bank. Each story must preserve its county label status, when-to-use guidance, and claims-status marker exactly as currently documented for broadcast safety.",
      "Road-01 is the Friday-mandate clerk call story with a Saline-area interpretation label and fits county-service and implementation lanes. Road-02 is volunteer confusion over petition rules in Central Arkansas interpretation context. Road-03 addresses quorum-court unfunded-mandate concern in South Arkansas interpretation framing and supports fiscal-governance contrasts.",
      "Road-04 focuses on first-time voter transparency expectations in Northwest interpretation context. Road-05 highlights Delta-region election-worker overtime after procedure changes. Road-06 covers Act 768 confusion with interpretation county placeholder. Road-07 captures cross-partisan fatigue with division. Road-08 cites statewide civic-index concern and is explicitly NEEDS_REVIEW before broadcast.",
      "This fieldbook should enforce timing and relevance discipline. Most stories should be delivered in one sentence, followed by policy mapping and service commitment. Overlong storytelling invites interruption and weakens claims control, especially where county labels remain interpretation placeholders pending candidate confirmation from travel logs.",
      "Integrate fieldbook usage with crosswalk rows and defensive modules. A story should only be deployed when its claims status is acceptable for the setting and when the section objective is clear. Stories are most persuasive when they illustrate one operational failure and one fix, not when they serve as emotional filler.",
    ],
    additionalHighlights: [
      "Include all eight stories with exact IDs, county labels, when-to-use, and claims-status governance.",
      "Road-08 is flagged NEEDS_REVIEW and should not be broadcast without source-year verification.",
      "Interpretation county labels must be candidate-confirmed before naming counties publicly.",
      "Deploy stories as one-sentence evidence, then pivot to office-function solutions.",
      "Use crosswalk alignment to prevent anecdote drift or irrelevant story insertion.",
    ],
    additionalWalkthrough: [
      "Create a story card deck for road-01 through road-08 with claims-status color coding.",
      "Before each event, mark which stories are approved, restricted, or hold due to verification gaps.",
      "In rehearsal, require one-sentence delivery plus immediate function mapping for every story.",
      "Train staff to interrupt and reset if Kelly begins stacking multiple stories in one answer.",
      "After events, log which stories landed well and whether any source verification updates are required.",
    ],
    sourcedFacts: [
      "Road stories file includes exactly eight entries: road-01, road-02, road-03, road-04, road-05, road-07, road-08, and road-06.",
      "Road-01 county label: Saline County area (INTERPRETATION), with county-service usage guidance.",
      "Road-02 county label: Central Arkansas (INTERPRETATION), with petition-process usage guidance.",
      "Road-03 county label: South Arkansas (INTERPRETATION), with unfunded-mandate usage guidance.",
      "Road-04 label: Northwest Arkansas (INTERPRETATION); road-05 label: Delta region (INTERPRETATION).",
      "Road-06 and road-07 county entries remain INTERPRETATION pending candidate confirmation.",
      "Road-08 is statewide and explicitly marked NEEDS_REVIEW for civic-index source/year verification.",
      "Dataset generatedAt is 2026-06-04 with explicit instruction to replace interpretation counties from travel log.",
    ],
    fieldResearchNotes: [
      "Operator should maintain a live approval list so unverified stories are never used on stage by mistake.",
      "If candidate names a county ad-lib, verify against travel log before reuse in future events.",
      "Use road stories mostly in mid-answer support; avoid opening statements dominated by anecdotal content.",
    ],
  },
};
