import type { DossierResearchOverlay } from "@/lib/intelligence/v4/applyCandidateDossierResearchDepth";

export const KELLY_DOSSIER_DEPTH_EXPANSION: Record<string, DossierResearchOverlay> = {
  "kelly-sos-office-overview": {
    additionalNarrative: [
      "Wave 2 office framing should open by naming the Secretary of State as a trust operator for elections, business filings, records access, and county support in all seventy-five counties. In debate rehearsal, Kelly should map each question to one operational lane, then cite a service action and a measurable follow-through deadline.",
      "The June 11, 2026 ACCA audience is likely to test whether she can move from slogan language to clerk-room execution detail. The strongest answer sequence is office function, county user, and implementation pathway, followed by a short verification line that all figures and legal references passed claims gate before public use.",
      "Verizon and Rock Dental credentials should be translated into system stewardship language, not résumé listing. For SOS overview answers, she should explain how multi-site management experience becomes statewide process discipline, especially when one statute change must be communicated clearly across county clerks, election workers, and business-filing users in the same week.",
      "Road-story evidence from road-01, road-04, and road-07 supports a practical overview argument: Arkansans need predictable guidance more than rhetorical escalation. In prep, staff should force one sentence tying each story to an SOS duty, so no anecdote is delivered without direct mapping to elections administration, records transparency, or filing reliability.",
      "The overview lane should also acknowledge legal pressure points like Act 350 and CVSGF governance questions without over-promising legal outcomes outside SOS authority. Debate reps should practice a boundary sentence that separates what the Secretary can administer directly from what must be coordinated with counties, counsel, and published rule guidance.",
      "Rose Bud roots and statewide travel should appear as service perspective, then quickly pivot to office accountability commitments. The close of every overview response should name one day-one action, one county-facing communication standard, and one oversight mechanism so moderators can hear executive readiness rather than abstract campaign branding.",
    ],
    additionalHighlights: [
      "Frame SOS as a multi-division trust office serving seventy-five counties every day.",
      "Use ACCA June 11 forum prep to test office-function mapping under interruption pressure.",
      "Translate Verizon and Rock Dental into governance process, training rhythm, and escalation design.",
      "Pair Act 350 and CVSGF references with clear SOS authority boundaries and claims gate discipline.",
    ],
    additionalWalkthrough: [
      "Open with four-function office map, then identify which county user is affected first.",
      "Insert one source-grounded detail, then state the implementation action and deadline.",
      "If challenged on ideology, pivot to published guidance, training cadence, and hotline accountability.",
      "Close with claims gate assurance and a measurable trust-office outcome for clerks and voters.",
    ],
    sourcedFacts: [
      "ACCA conference date anchor in this corpus is June 11, 2026 for clerk-facing message testing.",
      "Kelly dossier architecture repeatedly maps SOS responsibility across seventy-five Arkansas counties.",
      "Act 350 appears in the prep corpus as a legal pressure point requiring clear implementation guidance.",
      "CVSGF is tagged in campaign intelligence as a governance lane that must stay fact-verified.",
      "Claims gate is designated as mandatory before introducing new numbers, quotes, or legal assertions.",
    ],
    fieldResearchNotes: [
      "Run a two-minute drill where each answer must name function, user, action, and timing.",
      "Flag any overview line that cannot be traced to sourced facts in the dossier packet.",
      "Keep one fallback sentence for authority boundaries when moderators request non-SOS commitments.",
    ],
  },
  "kelly-organizational-leadership": {
    additionalNarrative: [
      "Organizational leadership answers should convert private-sector scale into public-service reliability by naming supervision structure, documentation habits, and correction loops. In debate rehearsal, Kelly should avoid title-heavy phrasing and instead describe how she would standardize guidance for county clerks while preserving local usability across diverse staffing levels and election-cycle pressures.",
      "Verizon experience is strongest when framed as managing distributed teams under shifting requirements, which closely resembles statewide SOS communication challenges after legislative updates. The useful contrast is not corporate versus government, but whether a leader can keep operations coherent when one unclear memo creates county-level confusion by Monday morning.",
      "Rock Dental references should emphasize training-system design and repeatable onboarding practices because SOS administration requires repeatable interpretation support, not one-off speeches. In mock exchanges, moderators should press with hypothetical statute changes so Kelly can demonstrate stepwise response discipline: assess change, publish guidance, train counties, track errors, and adjust quickly.",
      "Road-05 and road-06 show what happens when implementation burden outpaces support staffing. This lane becomes persuasive when she connects leadership to preventative structure: standardized FAQ updates, defined response windows, and escalation owners. Staff should score answers by whether they mention county users, process controls, and transparent accountability rather than personality language.",
      "Act 350 and CVSGF can be referenced here as stress tests for management clarity, provided she avoids legal overreach and sticks to administrative obligations. A strong line is that public trust depends on equal process application, documented interpretation updates, and timely county briefings whenever legal context shifts in high-scrutiny environments.",
      "For ACCA June 11 prep, the most credible leadership close is an operations pledge with measurable service metrics. Kelly should commit to predictable guidance cadence, published implementation notes, and response tracking, then invite clerk feedback loops so leadership is presented as reciprocal stewardship rather than one-direction command.",
    ],
    additionalHighlights: [
      "Leadership credibility increases when answers describe systems, owners, and correction loops.",
      "Verizon and Rock Dental examples should be translated into county-facing process reliability.",
      "Road-05 and road-06 support the case for training cadence and escalation standards.",
      "ACCA prep should test leadership claims against measurable clerk-service commitments.",
    ],
    additionalWalkthrough: [
      "Start with one management principle, then map it to a specific SOS duty.",
      "Add a field example, then explain the process control that prevents recurrence.",
      "If tenure attacks appear, distinguish lawmaking experience from service-system administration.",
      "End with published guidance cadence, response metric, and county feedback mechanism.",
    ],
    sourcedFacts: [
      "Campaign materials identify Verizon leadership as a long-horizon management credential.",
      "Rock Dental appears in dossier packets as evidence of training-program development capability.",
      "Road-05 documents overtime strain after procedural shifts in election operations.",
      "Road-06 captures confusion around Act 350-era implementation interpretation requirements.",
      "ACCA June 11, 2026 is treated as a high-value rehearsal forum for clerk credibility.",
    ],
    fieldResearchNotes: [
      "Penalize rehearsal answers that describe leadership values without naming execution mechanics.",
      "Require one sentence on county support architecture in every leadership response.",
      "Use interruption drills to ensure process language survives pressure and cross-talk.",
    ],
  },
  "kelly-leadership-development": {
    additionalNarrative: [
      "Leadership development should be presented as public infrastructure because county performance depends on training clarity as much as statute text. In this lane, Kelly should describe how she would build role-specific learning paths for clerks, election workers, and filing staff so statewide rule updates translate into consistent local action.",
      "Rock Dental training references become powerful when tied to repeatability and accountability, not generic mentorship rhetoric. Debate reps should include one concrete artifact, such as implementation bulletins or short procedural modules, and then explain how those assets reduce interpretation drift between counties during compressed election and petition deadlines.",
      "Verizon-era management lessons can support this section by showing experience with continuous coaching in distributed environments. The SOS parallel is straightforward: county teams need fast, reliable guidance channels and common language. Rehearsal should test whether every answer includes timing, responsible party, and a feedback pathway for frontline corrections.",
      "Road-02 and road-03 highlight confusion points where procedural literacy breaks down before intent does. Kelly should frame leadership development as fairness protection: if people cannot understand lawful pathways, trust declines. The policy bridge is to publish plain-language aids and track which counties need additional support without stigma or partisan framing.",
      "LEARNS-CAPES pressure questions may surface in this lane because opponents conflate civic context with administrative neutrality. The safe move is to acknowledge lawful public engagement history, then pivot to neutral training obligations of the SOS office. Staff should rehearse this pivot until it can be delivered in under twelve seconds.",
      "For ACCA June 11 preparation, this section should end with a county-coaching commitment tied to claims gate discipline. Kelly can promise that all training modules cite verified legal language, update dates, and contact points, so clerks know guidance is current, sourced, and operationally safe for immediate implementation.",
    ],
    additionalHighlights: [
      "Treat training systems as first-order election and filing reliability infrastructure.",
      "Use role-specific learning artifacts, not abstract coaching language, in debate answers.",
      "Road-02 and road-03 support fairness-through-clarity framing across county lines.",
      "Rehearse LEARNS-CAPES pivot to neutrality obligations in under twelve seconds.",
    ],
    additionalWalkthrough: [
      "Name the user role first, then describe the learning artifact they receive.",
      "Explain how that artifact prevents confusion and preserves equal administration.",
      "Cite update timing and ownership so implementation responsibility is unmistakable.",
      "Close with verification discipline: sourced legal text, date stamps, and support contact.",
    ],
    sourcedFacts: [
      "Rock Dental is repeatedly cited in dossier content for training-program leadership capability.",
      "Verizon background is used as distributed-team coaching and process-discipline evidence.",
      "Road-02 records petition-process confusion in volunteer-facing civic participation contexts.",
      "Road-03 captures county concern about unfunded or unclear implementation burden.",
      "Claims gate requirements apply to legal summaries used in training materials and debate lines.",
    ],
    fieldResearchNotes: [
      "Build one-page county training template with legal source, actions, and escalation contacts.",
      "Track which rehearsal lines exceed twelve seconds before reaching office-duty language.",
      "Maintain a live list of terms that require plain-language replacement for public settings.",
    ],
  },
  "kelly-civic-education": {
    additionalNarrative: [
      "Civic education answers should begin with the distinction between participation literacy and partisan mobilization. Kelly can reference Stand Up Arkansas as documented public work, then clarify that SOS duty is neutral process explanation for every lawful participant. Rehearsal should enforce that this distinction appears before any attack-reply language.",
      "For AR Kids and LEARNS-CAPES references are predictable debate triggers, so this lane needs high-speed boundary control. The recommended sequence is acknowledge verified public history, set household boundary in one sentence, and pivot to equal administration commitments. This keeps the frame on office responsibility rather than culture-war adjudication.",
      "Road-04 and road-07 support a civic education argument centered on transparency and de-escalation. Voters and volunteers repeatedly report procedural uncertainty, not demand for partisan theater. Kelly should use one short story to show why plain-language guidance matters, then deliver an SOS action promise tied to update cadence and accountability.",
      "Rose Bud framing can reinforce this section when used as community perspective rather than identity shield. The persuasive move is to say rural and urban Arkansans alike deserve understandable process pathways. Staff should drill this line against interruption so it remains calm, specific, and office-centered during adversarial moderator exchanges.",
      "Act 350 context belongs in civic education only as a process-clarity case study. Kelly should avoid legal adjudication claims and instead explain how SOS can publish implementation guides, route questions, and coordinate county training windows. This demonstrates governance maturity while respecting institutional boundaries and ongoing legal complexity.",
      "At ACCA on June 11, 2026, civic education credibility will likely hinge on practical examples. The strongest close is a concrete commitment to updated public FAQs, county briefing notes, and claims gate review before disseminating legal interpretations, so clerk offices receive consistent language they can implement without added confusion.",
    ],
    additionalHighlights: [
      "Define civic education as neutral process literacy, not partisan persuasion.",
      "Use Stand Up Arkansas with a fast bridge to equal-service SOS obligations.",
      "Handle For AR Kids and LEARNS-CAPES via acknowledge-boundary-pivot discipline.",
      "Connect civic education commitments to FAQs, county briefs, and claims gate review.",
    ],
    additionalWalkthrough: [
      "Open with neutrality definition and one verified civic-history reference.",
      "Set boundaries on personal or household framing in a single concise sentence.",
      "Pivot to county-facing tools: FAQs, timelines, and implementation support channels.",
      "End by affirming equal treatment for all lawful petitions and election participants.",
    ],
    sourcedFacts: [
      "Stand Up Arkansas appears in public-record packets as a verified organizing reference.",
      "For AR Kids is documented as a petition-history lane requiring careful framing.",
      "LEARNS-CAPES linkage is marked as a recurring attack vector in prep materials.",
      "Road-04 includes first-time voter clarity concerns tied to trust and transparency.",
      "Road-07 captures broad fatigue with division and preference for practical guidance.",
    ],
    fieldResearchNotes: [
      "Limit all civic-history segments to one sentence before office-duty pivot.",
      "Pre-clear every legal phrase related to Act 350 through claims gate notes.",
      "Use timer drills to preserve calm cadence under family-adjacent challenge prompts.",
    ],
  },
  "kelly-rural-arkansas": {
    additionalNarrative: [
      "Rural Arkansas framing should establish operational empathy, not symbolic branding. Kelly can reference Rose Bud and small-farm context as perspective, then map directly to SOS duties that hit thinly staffed counties hardest: election training, records access, and business filing usability. Debate practice should reward specificity over sentiment-heavy storytelling.",
      "Road-01, road-03, and road-05 provide practical evidence that implementation friction is uneven across regions. The persuasive move is to explain how statewide guidance can reduce county strain without creating one-size-fits-none directives. In rehearsal, each rural answer should include one support mechanism and one accountability timeline.",
      "The seventy-five county frame is essential here because it prevents false rural-versus-urban binaries. Kelly should say every county deserves usable rules, then note that constrained staffing can magnify ambiguity. That framing protects against culture signaling while preserving a strong case for proactive SOS communication systems and training support.",
      "Act 350 and CVSGF can be mentioned as examples of why rural administrators need plain-language implementation pathways. She should avoid legal predictions and focus on the practical county question: what does the clerk do on Monday morning. This keeps the lane grounded in service execution under real staffing constraints.",
      "Verizon and Rock Dental transfer cleanly into this section when framed as distributed operations experience. Rural service requires disciplined information flow and fast correction loops when guidance is misunderstood. Staff should run simulation drills with conflicting county scenarios to ensure Kelly can provide consistent statewide standards with local usability.",
      "For ACCA June 11 readiness, close rural answers with a concrete county-equity commitment such as published response standards and rotating clerk briefings. The objective is to make rural credibility inseparable from statewide fairness so opponents cannot recast it as regional preference or campaign nostalgia.",
    ],
    additionalHighlights: [
      "Use Rose Bud perspective as a bridge to county operations, not identity signaling.",
      "Road-01, road-03, and road-05 anchor rural implementation strain with factual context.",
      "Seventy-five county framing prevents unhelpful rural-versus-urban rhetorical traps.",
      "Tie Act 350 and CVSGF mentions to Monday-morning clerk action clarity.",
    ],
    additionalWalkthrough: [
      "Lead with county-equity principle across all seventy-five jurisdictions.",
      "Insert one field story and immediately map it to SOS support mechanics.",
      "Name timing, ownership, and correction loop for implementation communication.",
      "Close with statewide fairness language that includes rural and urban communities equally.",
    ],
    sourcedFacts: [
      "Rose Bud appears in campaign biography material as a core origin reference.",
      "Road-01 captures clerk frustration after late-week mandate without clear response channel.",
      "Road-03 records quorum-court concern around operational burden and implementation clarity.",
      "Road-05 documents overtime pressure in election administration after procedure changes.",
      "Dossier structures this lane around service obligations to all seventy-five counties.",
    ],
    fieldResearchNotes: [
      "Verify any named county label from road logs before public use in forum settings.",
      "Use one rural story per response to avoid anecdotal overload under time pressure.",
      "Audit scripts monthly to keep county-equity language balanced and non-divisive.",
    ],
  },
  "kelly-community-building": {
    additionalNarrative: [
      "Community-building should be framed as implementation coordination because SOS outcomes depend on how clerks, volunteers, and residents receive and act on guidance. Kelly should describe coalition work as process alignment across differences. Debate rehearsal should test whether she can de-escalate tone while still delivering firm administrative commitments.",
      "Stand Up Arkansas references can support this lane when paired with explicit neutrality commitments for office administration. The useful line is that relationship experience helps gather feedback quickly, but rules must be applied equally. This distinction protects credibility against activist-label attacks while preserving authentic evidence of community engagement.",
      "Road-07 and road-08 indicate broad fatigue with conflict-driven communication and demand for practical clarity. Kelly can use these stories to justify transparent updates, predictable support windows, and respectful public briefings. Staff should rehearse this lane with interruption so she maintains composure and returns to process without sounding evasive.",
      "For AR Kids and LEARNS-CAPES challenges may appear even in community-building prompts, so response discipline matters. The safest move is acknowledge lawful civic history, set boundaries, and pivot to shared county-service needs. That keeps audience attention on governance behavior rather than reopening older campaign disputes in defensive detail.",
      "Verizon leadership experience can be applied here by describing cross-team communication structures that reduce confusion under pressure. In SOS context, that means consistent message chains from state office to county desks. Rehearsal scoring should track whether answers include clear channels, update ownership, and feedback integration plans.",
      "At ACCA June 11, this lane should close with a commitment to reciprocal trust: publish guidance early, listen to clerk feedback, and correct quickly when implementation friction appears. Community-building becomes tangible when tied to this practical cycle, not treated as generic unity language disconnected from office obligations.",
    ],
    additionalHighlights: [
      "Community-building credibility rises when linked to operational coordination and execution.",
      "Use Stand Up Arkansas carefully with immediate neutrality and equal-administration bridge.",
      "Road-07 and road-08 support de-escalation plus practical guidance commitments.",
      "Score answers on channels, ownership, and correction loops rather than tone alone.",
    ],
    additionalWalkthrough: [
      "Start by validating concern, then identify the office process that addresses it.",
      "Name how state guidance reaches counties and how county feedback returns upstream.",
      "If personal attacks surface, use boundary language and re-anchor to service obligations.",
      "Close with publish-listen-correct cycle and measurable trust outcome.",
    ],
    sourcedFacts: [
      "Stand Up Arkansas appears as a documented public-engagement anchor in dossier materials.",
      "Road-07 records appetite for lower-conflict, function-focused public leadership.",
      "Road-08 is flagged for verification caution but still indicates statewide trust concerns.",
      "Prep corpus marks activist-label framing as a recurring attack lane requiring pivots.",
      "ACCA June 11 forum is prioritized for testing clerk-facing de-escalation language.",
    ],
    fieldResearchNotes: [
      "Run live drills where moderators interrupt at second ten to test pivot stability.",
      "Require one measurable service action in every community-building response.",
      "Keep road-08 usage restricted until source-year verification is fully locked.",
    ],
  },
  "kelly-family-stewardship": {
    additionalNarrative: [
      "Family stewardship should communicate values discipline, then return rapidly to office execution. Kelly can reference foster and adoption parenthood as context for long-horizon responsibility, but she should avoid overextending this lane. In debate rehearsal, staff should time the personal segment and enforce immediate transition to SOS duties.",
      "The strategic function of this section is trust calibration, not technical qualification. After a brief values statement, Kelly should name how those values translate into fair process, transparent communication, and consistent county service. This keeps empathy connected to governance rather than allowing opponents to reframe the exchange as sentiment versus competence.",
      "When LEARNS-CAPES or For AR Kids references are injected into family prompts, the response should stay bounded and procedural. Acknowledge known context, decline personal escalation, and pivot to equal administration obligations for all lawful participants. Rehearsal should penalize any answer that lingers in personal defense beyond one sentence.",
      "Rose Bud roots can reinforce family stewardship in rural forums if paired with statewide fairness language. She should explicitly say values formed in one community now inform service to all seventy-five counties. This avoids regional narrowing and supports the broader trust-office argument central to SOS responsibilities.",
      "Road-04 and road-07 can be used sparingly to illustrate why stable institutions matter to families navigating elections and civic participation. The key is to connect story evidence to practical commitments, such as clear guidance and response standards, rather than emotional amplification that consumes policy airtime under strict clocks.",
      "For ACCA June 11 readiness, this lane should conclude with a calm administrative pledge: protect process integrity, explain rules plainly, and treat every county user with equal respect. That closing frame signals maturity and keeps family values integrated with executive stewardship rather than parallel to it.",
    ],
    additionalHighlights: [
      "Use family context briefly, then pivot fast to office-function commitments.",
      "Treat this lane as trust calibration, not résumé or qualification inflation.",
      "Bound LEARNS-CAPES and For AR Kids spillover with one-sentence procedural pivots.",
      "Connect Rose Bud values to statewide fairness across all seventy-five counties.",
    ],
    additionalWalkthrough: [
      "Deliver one concise values line and transition immediately to SOS obligations.",
      "Name one specific trust mechanism: transparency, consistency, or response accountability.",
      "Decline personal escalation and return to equal-lawful-user administration language.",
      "Close with calm stewardship pledge tied to county-facing service outcomes.",
    ],
    sourcedFacts: [
      "Campaign biography references foster and adoption parenthood as established personal context.",
      "Rose Bud identity appears as a recurring grounding point in messaging assets.",
      "Road-04 and road-07 contain trust and tone signals relevant to family-impact framing.",
      "Attack prep materials warn against overlong personal responses in high-pressure debates.",
      "Seventy-five county fairness language is repeatedly emphasized in SOS readiness materials.",
    ],
    fieldResearchNotes: [
      "Hard-cap personal context to ten seconds in rehearsed timed responses.",
      "Track transitions; if office duty appears after second twelve, revise script.",
      "Use this lane mostly in personal prompts, not primary policy rebuttal slots.",
    ],
  },
  "kelly-public-trust-stewardship": {
    additionalNarrative: [
      "Public trust stewardship should define neutrality as consistent process behavior, not rhetorical distance from conflict. Kelly should explain that SOS credibility comes from clear guidance, equal application, and documented corrections when issues emerge. Debate rehearsal should include hostile questioning so this definition holds under pressure and interruption.",
      "Claims gate belongs at the center of this section because factual discipline is a trust behavior audiences can observe immediately. Kelly should state that legal references, dates, and statistics are verified before use, then connect this discipline to how SOS guidance will be published for counties and the public.",
      "Act 350 and CVSGF can be used as examples of why trust requires transparent communication boundaries. She should avoid litigating unsettled facts on stage and instead describe what the office can do reliably: publish implementation notes, maintain contact pathways, and correct errors publicly when interpretations are updated.",
      "Road-01 and road-04 highlight what trust failure looks like in practice: unclear channels and hard-to-find guidance. This lane becomes strong when she connects those stories to concrete commitments such as response standards, update logs, and county briefing cadence. Staff should insist on these mechanics in every trust answer.",
      "Verizon and Rock Dental references support trust only when translated into accountability systems rather than leadership mythology. She should explain how distributed operations experience informs documentation rigor and support escalation structure. Rehearsal metrics should score whether each response names accountability owner, timeline, and verification checkpoint.",
      "At ACCA on June 11, 2026, the best close is a public standard: equal treatment across seventy-five counties, transparent updates on contested issues, and open correction when guidance changes. This framing demonstrates confidence without overclaiming authority and aligns trust language with executable administrative practice.",
    ],
    additionalHighlights: [
      "Define neutrality as repeatable process fairness, transparency, and correction discipline.",
      "Use claims gate as visible evidence of trustworthiness under scrutiny.",
      "Reference Act 350 and CVSGF as communication-boundary stress tests, not legal theater.",
      "Anchor trust claims with response standards, update logs, and county brief cadence.",
    ],
    additionalWalkthrough: [
      "Open with trust definition tied to specific process behaviors.",
      "Add one verified field example and the mechanism that addresses it.",
      "State claims gate commitment for legal and numerical public assertions.",
      "Close with equal-county standard and public correction protocol.",
    ],
    sourcedFacts: [
      "Claims gate is embedded in this dossier family as a precondition for public assertions.",
      "Act 350 appears throughout prep materials as an implementation communication pressure point.",
      "CVSGF is tracked as a sensitive governance lane requiring precise sourcing.",
      "Road-01 documents uncertainty after late-week directive with weak response visibility.",
      "Road-04 reflects first-time user demand for transparent, findable election guidance.",
    ],
    fieldResearchNotes: [
      "Disallow trust answers that do not include at least one operational mechanism.",
      "Maintain a running list of approved legal phrases for Act 350 and CVSGF mentions.",
      "Simulate rapid-fire cross-exam to preserve calm tone and factual boundaries.",
    ],
  },
  "kelly-debate-credential-intro": {
    additionalNarrative: [
      "Credential introductions should be built as obligation-evidence-capability sequences rather than chronology dumps. Kelly should open with what SOS requires, then supply one evidence anchor from Verizon, Rock Dental, or civic education work, and close with county-service capability. This structure is resilient under interruption and avoids résumé inflation.",
      "The strongest credential proof points are operational: distributed leadership, training systems, and public communication clarity. In rehearsal, moderators should challenge with tenure comparisons so she can distinguish lawmaking experience from administrative execution. The objective is not diminishing opponents, but clarifying role-fit for a trust office that serves all counties.",
      "Stand Up Arkansas references can appear in credential intros only if immediately tied to neutral process literacy goals. This protects against activist-label traps and demonstrates message control. Staff should monitor whether each intro line maps to a current SOS duty and has a factual anchor already cleared through claims gate.",
      "Road-05 and road-06 can be inserted as one-line evidence that implementation failures are practical, not theoretical. The lane should show she understands county consequences when guidance is late or unclear. Each story insertion must end with a concrete administration fix so anecdote never replaces policy readiness.",
      "ACCA June 11 rehearsal should include twenty-five second and fifteen second intro variants because panel formats differ. Kelly should preserve the same backbone in both versions: office duty, verified evidence, and execution promise. This consistency improves credibility across media clips and prevents mixed messaging between events.",
      "Act 350, CVSGF, and public-record attack lanes should not dominate credential intros, but she should keep a short boundary sentence ready. If baited, she can acknowledge seriousness, reaffirm verification discipline, and return to office readiness. That move protects tempo while signaling command of high-risk topics.",
    ],
    additionalHighlights: [
      "Use obligation-evidence-capability structure for interruption-resistant credential openings.",
      "Translate Verizon and Rock Dental into role-fit for SOS administration.",
      "Keep Stand Up Arkansas references paired with neutrality and process-literacy framing.",
      "Maintain fifteen and twenty-five second intro variants with identical structural backbone.",
    ],
    additionalWalkthrough: [
      "Start by stating the office requirement before naming any biography element.",
      "Insert one verified credential and map it to county-facing execution ability.",
      "Add a short field cue only if it strengthens, not replaces, process detail.",
      "Close with measurable service promise and claims gate reliability statement.",
    ],
    sourcedFacts: [
      "Verizon and Rock Dental are core credential anchors across campaign and dossier files.",
      "Stand Up Arkansas appears as a documented civic engagement reference in public records.",
      "Road-05 and road-06 provide implementation-friction examples suitable for concise intros.",
      "ACCA June 11, 2026 is prioritized for clerk-facing credential stress testing.",
      "Claims gate is required before using new legal or statistical references in debate lines.",
    ],
    fieldResearchNotes: [
      "Reject intros that spend more than half the time on biography nouns.",
      "Track whether every intro ends with an office-output commitment and timeline.",
      "Use video review to remove filler words that weaken authority in first ten seconds.",
    ],
  },
  "kelly-30-second-bio": {
    additionalNarrative: [
      "The thirty-second bio should run as past-present-future with strict factual discipline and SOS mapping in each segment. Past can include Verizon and Rock Dental leadership in one concise clause, present can define county-focused service mission, and future must promise transparent trust-office execution with measurable communication standards.",
      "Rose Bud roots and family stewardship references are valuable but must be proportioned to time. In timed debate contexts, one personal phrase is enough before returning to office readiness. Staff should rehearse this transition repeatedly so emotional credibility supports, rather than displaces, policy and administrative competence.",
      "Stand Up Arkansas can be included as civic education evidence if immediately bounded by neutrality obligations of the Secretary role. This keeps the bio from drifting into activism debates and demonstrates message maturity. The safe pattern is identify history, define role boundary, then commit to equal lawful-user administration.",
      "Road-04 provides a useful one-line present-tense motivation cue about first-time user confusion and transparency needs. Kelly should use it sparingly and always pair it with one implementation action, such as clearer public guidance and county support channels. This turns biography into service rationale instead of anecdotal drift.",
      "For AR Kids, LEARNS-CAPES, and other attack surfaces should not be preloaded into the standard bio script. Instead, she should maintain a compact boundary response if moderators redirect. The core bio must remain forward-looking, trust-centered, and rooted in verified facts that survive rapid media clipping without context loss.",
      "ACCA June 11 preparation should include hard-stop timing at twenty-eight seconds to preserve space for follow-ups. Every version must end with a future-tense office commitment plus claims gate assurance, signaling that Kelly values both accuracy and execution in a role where public confidence depends on documented clarity.",
    ],
    additionalHighlights: [
      "Past-present-future bio format should include explicit SOS function mapping in each phase.",
      "Use Rose Bud and family context briefly, then prioritize office-readiness language.",
      "Include Stand Up Arkansas only with immediate neutrality and equal-administration bridge.",
      "End every bio with future commitment and claims gate reliability signal.",
    ],
    additionalWalkthrough: [
      "Draft one twenty-eight second script and one twenty-second compressed backup version.",
      "Ensure each clause is source-backed and tied to a present SOS duty.",
      "Practice interruption at second eighteen while preserving the future commitment close.",
      "Audit clips for accidental drift into attack-lane details not needed in bio answers.",
    ],
    sourcedFacts: [
      "Campaign bio packets include Verizon, Rock Dental, Rose Bud, and family stewardship elements.",
      "Stand Up Arkansas appears in verified civic-engagement references used across dossier sections.",
      "Road-04 is documented as a transparency and first-time user confusion narrative lane.",
      "Attack prep warns that LEARNS-CAPES and For AR Kids can derail opening statements.",
      "Claims gate is a standing requirement for legal, statistical, and quote-level assertions.",
    ],
    fieldResearchNotes: [
      "Keep a printed beat map so bio pacing stays stable under stress.",
      "Cut any sentence that does not directly improve role-fit or trust-office credibility.",
      "Run daily stopwatch reps with random moderator interruption to harden transition discipline.",
    ],
  },
  "kelly-experience-office-crosswalk": {
    additionalNarrative: [
      "The crosswalk should function as the master translation grid from biography evidence to SOS execution duties. Each row must contain one proven experience anchor, one office function, and one delivery behavior. Debate rehearsal should require immediate row selection before speaking so answers stay structured under pressure and topic pivots.",
      "Verizon, Rock Dental, Stand Up Arkansas, and rural service perspective should map to different duty clusters rather than repetitive generic claims. This prevents overuse of any single credential and helps moderators hear role breadth. Staff can score responses for row fidelity, factual sourcing, and practical county-user relevance.",
      "Road stories road-01 through road-08 should be tagged as optional evidence boosters linked to specific rows. For example, road-01 supports guidance responsiveness, road-03 supports burden awareness, and road-04 supports transparency commitments. This tagging keeps anecdotes aligned with function and avoids random story insertion during heated exchanges.",
      "Act 350 and CVSGF references should appear in governance-risk rows with strict boundary language and claims gate checks. The point is to demonstrate disciplined administration in sensitive contexts, not to litigate unsettled matters on stage. Crosswalk cards should include approved phrases and red-line statements for each risk lane.",
      "For ACCA June 11 forum prep, the crosswalk should drive rapid-response drills where clerks ask practical implementation questions. Kelly should answer by naming row, action, and timeline in one concise arc. This format demonstrates readiness and makes follow-up commitments auditable after the event.",
      "As new modules evolve, including career timeline deep and public-record defensive, they should plug into existing crosswalk logic rather than create parallel scripts. A single source of message truth reduces contradiction risk, improves surrogate alignment, and keeps every answer connected to actionable trust-office performance.",
    ],
    additionalHighlights: [
      "Use crosswalk rows as mandatory pre-speech structure in all debate rehearsal rounds.",
      "Map each credential to distinct SOS function lanes to prevent repetitive messaging.",
      "Tag road-01 through road-08 to specific rows for controlled anecdote deployment.",
      "Include Act 350 and CVSGF boundary phrases and claims gate status on risk rows.",
    ],
    additionalWalkthrough: [
      "Build row cards with evidence anchor, office function, and implementation behavior.",
      "Run random prompts and require row callout before answer delivery.",
      "Attach one approved story and one risk warning to each applicable row.",
      "Post-session, score row fidelity, factual integrity, and county-user clarity.",
    ],
    sourcedFacts: [
      "Crosswalk concept is already embedded in dossier architecture as a core mapping instrument.",
      "Road set includes eight numbered stories from road-01 through road-08 for selective use.",
      "Act 350 and CVSGF are treated as sensitive governance topics needing strict sourcing.",
      "Claims gate is designated as required before introducing fresh legal or numeric assertions.",
      "ACCA June 11, 2026 is a priority environment for practical clerk-facing crosswalk testing.",
    ],
    fieldResearchNotes: [
      "Keep laminated row cards in prep room and spin-room kits for consistency.",
      "If a response cannot be row-mapped in five seconds, restart with simpler structure.",
      "Review weekly for overlap so each row remains distinct and tactically useful.",
    ],
  },
  "kelly-next-prep-modules": {
    additionalNarrative: [
      "Next-module sequencing should prioritize risk containment before contrast ambition. Start with SOS office overview, credential intro, and public trust stewardship, then run public-record defensive drills. This order reduces unforced errors and creates stable language foundations before layering opponent contrasts or longer narrative riffs in advanced rounds.",
      "Claims gate checkpoints should be embedded between every module transition, especially before high-risk topics like Act 350, CVSGF, LEARNS-CAPES, and For AR Kids. Staff should treat verification status as a release gate: no unresolved line moves into final scripts until sourcing is documented and dispute boundaries are explicit.",
      "Road stories should be introduced only after core architecture is stable because anecdotes can either clarify or derail depending on timing. The recommended flow is teach function mapping first, then attach one story at a time with purpose, claims status, and a required office-action sentence following immediately.",
      "ACCA June 11 prep should include dedicated clerk-question simulation blocks because that audience rewards implementation specificity. Kelly should practice response formats that include action owner, timeline, and county support pathway. Module scoring should prioritize practical clarity and factual integrity over rhetorical flourish.",
      "Career timeline deep and public-record defensive modules should be integrated nightly so chronology and boundary language stay synchronized across media, debates, and surrogate talking points. A single canonical phrasing set prevents contradiction clips and keeps focus on trust-office readiness rather than message repair after events.",
      "Post-event debrief should be mandatory within thirty minutes and captured in a short loop: what landed, what overran, what claims need recheck, and which module requires rerun. This operational cadence turns static research packets into a living preparation system that improves with each public test.",
    ],
    additionalHighlights: [
      "Sequence modules by risk control before contrast performance to reduce unforced errors.",
      "Enforce claims gate checkpoints between modules, especially on sensitive legal lanes.",
      "Add road stories only after function-mapping architecture is stable and timed.",
      "Use ACCA clerk simulation blocks to stress-test practical execution language.",
    ],
    additionalWalkthrough: [
      "Run baseline modules first: overview, credentials, trust, then defensive record.",
      "Pause for claims gate review before adding legal or opponent-specific detail.",
      "Attach one road story per target lane with purpose and boundary notes.",
      "Close day with rapid debrief and assign next-session rerun priorities.",
    ],
    sourcedFacts: [
      "Claims gate is an explicit control mechanism throughout the Kelly dossier system.",
      "Act 350, CVSGF, LEARNS-CAPES, and For AR Kids are listed as sensitive prep lanes.",
      "Road stories are organized as road-01 through road-08 with usage and caution metadata.",
      "ACCA forum date in this packet is June 11, 2026 for clerk-facing performance validation.",
      "Public-record defensive and timeline modules are referenced as new synchronization priorities.",
    ],
    fieldResearchNotes: [
      "Assign one prep captain to enforce module order and stop script drift.",
      "Track error categories daily: sourcing, timing, pivot delay, and boundary breaches.",
      "Never promote a new line to final script without documented claims gate status.",
    ],
  },
  "kelly-career-timeline-deep": {
    additionalNarrative: [
      "Career timeline deep should provide a stable chronology backbone that prevents contradictory phrasing across interviews and debates. The recommended arc is early leadership development, Verizon distributed operations, Rock Dental training systems, then statewide SOS candidacy grounded in trust-office stewardship and county service obligations across Arkansas.",
      "Verizon phase should emphasize scale management, process consistency, and distributed accountability because those competencies map directly to statewide office administration. In rehearsals, Kelly should answer timeline prompts by immediately linking each era to one SOS duty so chronology always serves role-fit rather than nostalgia or credential inflation.",
      "Rock Dental phase should focus on training and leadership development architecture, including repeatable instruction methods and support pathways. This matters for Secretary of State readiness because counties need clear implementation guidance when legal contexts shift. Staff should ensure timeline references include practical transfer language, not merely employer mentions.",
      "Candidacy phase should anchor to documented public milestones, including Arkansas press references and ACCA June 11, 2026 preparation focus. The timeline should show a progression from private leadership to public trust service, while preserving factual boundaries around dates and details not yet fully packeted for unrestricted stage use.",
      "Rose Bud and civic education references should be positioned as continuity markers that explain motivation and perspective. The key is to keep this lane operational: values inform process behavior, and process behavior produces trust. Rehearsal scoring should reward answers that maintain this chain under interruption or adversarial framing.",
      "To protect against attack clips, every timeline version should end with future-tense office commitments and claims gate standards. That closing move signals discipline and prevents the section from becoming backward-looking. The audience should hear a coherent journey that culminates in specific, verifiable administrative promises for county users.",
    ],
    additionalHighlights: [
      "Use one canonical timeline arc to prevent contradiction across forums and media clips.",
      "Map Verizon and Rock Dental phases directly to SOS administration capabilities.",
      "Anchor candidacy era with documented milestones and ACCA June 11 prep context.",
      "End timeline answers with forward-looking commitments and claims gate discipline.",
    ],
    additionalWalkthrough: [
      "Draft three timeline phases and attach one SOS function to each phase.",
      "Create short and long variants that preserve identical sequencing and language.",
      "Stress-test timeline under hostile prompts that attempt date or role confusion.",
      "Close with concrete day-one commitments and factual verification posture.",
    ],
    sourcedFacts: [
      "Verizon appears consistently as a primary leadership-era credential in campaign materials.",
      "Rock Dental is documented as a key training and leadership-development reference.",
      "Rose Bud background is included in biography assets as a perspective anchor.",
      "ACCA June 11, 2026 is a scheduled clerk-facing test point for message discipline.",
      "Claims gate is required before adding new date-specific or legal-detail assertions.",
    ],
    fieldResearchNotes: [
      "Maintain one shared timeline sheet for candidate, staff, and surrogate alignment.",
      "Mark any uncertain date detail as provisional until verification is completed.",
      "Audit published bios monthly so all channels match canonical timeline wording.",
    ],
  },
  "kelly-public-record-defensive": {
    additionalNarrative: [
      "Public-record defensive prep should consolidate high-risk lanes into a single acknowledge-boundary-pivot model. Kelly should acknowledge verified facts, mark unresolved items as pending verification, and pivot to SOS administration commitments. This method preserves credibility and prevents escalation into speculative claims that can be clipped and amplified post-debate.",
      "Stand Up Arkansas, LEARNS-CAPES, and For AR Kids should each have prewritten micro-responses with explicit sourcing status and transition language. The objective is not evasion but control: answer what is known, avoid inventing legal conclusions, and return to equal administration for all lawful participants across county election and petition systems.",
      "Act 350 and CVSGF references require additional caution because legal and governance nuance can be distorted in rapid exchanges. Kelly should avoid declarative overreach and instead describe what SOS can reliably do: provide clear guidance, maintain transparent records channels, and ensure county offices receive timely implementation support materials.",
      "Road-story support can strengthen defensive pivots by showing practical stakes for clerks and residents when communication fails. However, each story must stay concise and sourced. Staff should prohibit stacked anecdotes in defensive answers because overlength creates openings for follow-up traps and undermines the intended clarity.",
      "Claims gate is non-negotiable in this section. Any new quote, number, or allegation response should be held until verification status is clear. Rehearsal should include surprise prompts using partial or ambiguous claims so Kelly practices disciplined uncertainty language without sounding hesitant or unprepared.",
      "For ACCA June 11 scenarios, defensive answers should end with institutional fairness commitments: equal treatment, transparent updates, and accountable correction when guidance changes. This closing pattern reframes attacks into governance standards, allowing Kelly to project steadiness while respecting factual and legal boundaries.",
    ],
    additionalHighlights: [
      "Use acknowledge-boundary-pivot structure for all high-risk public-record prompts.",
      "Prepare separate micro-responses for Stand Up Arkansas, LEARNS-CAPES, and For AR Kids.",
      "Treat Act 350 and CVSGF as precision lanes with strict authority boundaries.",
      "Enforce claims gate before adding any new quote, statistic, or legal assertion.",
    ],
    additionalWalkthrough: [
      "Label each risk lane by verification status: verified, partial, or pending.",
      "Rehearse one concise response per lane with mandatory SOS duty pivot.",
      "Run bundled-attack drills combining two or three lanes in one question.",
      "End with equal-treatment and transparent-correction governance commitments.",
    ],
    sourcedFacts: [
      "Stand Up Arkansas is listed in packet materials as a documented civic-engagement reference.",
      "LEARNS-CAPES is marked as a recurring sensitivity lane in debate prep files.",
      "For AR Kids appears as a petition-history topic requiring careful factual boundaries.",
      "Act 350 and CVSGF are tracked as legal-governance issues needing precise sourcing.",
      "Claims gate is designated as mandatory for high-risk public-record response content.",
    ],
    fieldResearchNotes: [
      "Keep laminated lane cards with approved phrasing and prohibited speculative language.",
      "Designate one staff verifier to call status in real time during rapid prep cycles.",
      "Update defensive scripts immediately when sourcing status changes in research files.",
    ],
  },
  "kelly-road-stories-fieldbook": {
    additionalNarrative: [
      "The road stories fieldbook should be managed as a controlled evidence system, not an open anecdote shelf. Every card for road-01 through road-08 must include when-to-use, claims status, and SOS function mapping. Debate rehearsal should reject any story use that lacks a direct policy-action bridge.",
      "Road-01, road-02, and road-03 are strongest in implementation and burden discussions because they show practical friction at county level. Kelly should deliver each in one sentence, then pivot to guidance cadence, training support, or response standards. This preserves narrative force while maintaining trust-office professionalism.",
      "Road-04, road-05, and road-06 are best for transparency and process-clarity lanes, especially when moderators ask about election confidence under legal change. Staff should ensure county labels and contextual claims are verified before public use, and any provisional detail should be replaced with broader regional wording until confirmed.",
      "Road-07 and road-08 support tone and trust arguments, but road-08 requires stricter review status handling. Kelly should never use a flagged story as a hard factual claim unless verification is completed. In prep, operators should color-code cards so risky stories are visibly restricted during fast exchanges.",
      "The fieldbook should interface directly with crosswalk rows so each anecdote has a predefined function. This reduces improvisation drift and keeps answers coherent across formats. Rehearsal should include random prompt drills where Kelly must select one story card and one office-action card in sequence.",
      "For ACCA June 11 readiness, the fieldbook close should reinforce disciplined storytelling: one story, one function, one commitment, one verification standard. This formula delivers authenticity without sacrificing precision, and it aligns road narratives with claims gate requirements and county-service accountability expectations.",
    ],
    additionalHighlights: [
      "Treat road-01 through road-08 as controlled evidence cards with status metadata.",
      "Use one-sentence story delivery followed by immediate office-action mapping.",
      "Restrict road-08 until verification status is cleared for broad public use.",
      "Integrate story cards with crosswalk rows to prevent improvisational narrative drift.",
    ],
    additionalWalkthrough: [
      "Build card deck for road-01 to road-08 with function tags and caution notes.",
      "Practice random selection drills pairing one story card with one policy-action card.",
      "Enforce one-sentence limit before pivoting to implementation commitments.",
      "Run pre-event verification check so restricted stories are not used on stage.",
    ],
    sourcedFacts: [
      "Road story corpus in this lane uses numbered entries road-01 through road-08.",
      "Road-01 to road-03 are repeatedly referenced for county burden and process friction context.",
      "Road-04 to road-06 support transparency and election-operations clarity narratives.",
      "Road-07 and road-08 are used for trust-tone framing, with road-08 requiring extra caution.",
      "Claims gate standards apply to anecdote deployment when facts are presented as definitive.",
    ],
    fieldResearchNotes: [
      "Assign one staff member as story gatekeeper during debates and media availabilities.",
      "Remove any card from live use immediately when verification status becomes uncertain.",
      "Log post-event story performance to refine deployment choices for future forums.",
    ],
  },
};
