import type { DossierResearchOverlay } from "@/lib/intelligence/v4/applyCandidateDossierResearchDepth";

export const OPPONENT_DOSSIER_DEPTH_EXPANSION: Record<string, DossierResearchOverlay> = {
  "hammer-executive-profile": {
    additionalNarrative: [
      "Hammer's executive profile performs best when his senate experience is acknowledged first, then narrowed to the Secretary of State execution test. Counsel-safe contrast avoids motive language and instead asks whether county clerks received timely implementation aids after each legislative change that he credits on stage and online.",
      "The 2021 six-bill package, SB486 through SB644, gives Hammer a coherent authorship narrative that sounds complete to non-specialist audiences. The response opportunity is not to deny the package, but to distinguish bill passage from county deployment readiness across staffing, training windows, and hotline response obligations.",
      "March 2026 Arkansas Advocate runoff framing matters because it reflects a competitive Republican lane rather than a placeholder candidacy. Counsel-safe messaging should concede electoral legitimacy while pressing operational readiness questions that belong to the office users in all seventy-five counties, not partisan identity arguments.",
      "At ACCA Mountain View on June 11, executive-profile answers should remain technical and brief. County officials are likely to reward candidates who can convert legislative references into practical administration commitments, especially around communication timing, process clarity, and post-enactment support pathways for election workers and clerks.",
      "hammerforarkansas.com claims often bundle rankings, integrity language, and broad confidence assertions in one packet. The disciplined response is to split each claim into verifiable component parts, label what is verified versus interpreted, and then move to a county-service transparency standard that moderators can defend as fair.",
      "Executive-profile contrast should remain role-specific: senate record as policy authorship, Secretary of State as statewide operating system. That distinction keeps Kelly's framing counsel-safe, avoids personal attacks, and reinforces the argument that trust in elections depends on execution quality as much as statutory text.",
    ],
    additionalHardEvidence: [
      { claim: "KH-0B source stack documents SB486-SB644 mapped to Acts 727-729, 973-974, and 1051 in 2021 package framing", tier: "VERIFIED" },
      { claim: "Arkansas Advocate March 2026 runoff coverage appears in Hammer lead-story references as competitive context", tier: "VERIFIED" },
      { claim: "ACCA Mountain View June 11 panel context is documented in conference preparation files", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Acknowledge legislative tenure and runoff legitimacy in one sentence without embellishment.",
      "Anchor to one verified package fact, then ask for county implementation evidence.",
      "Use CVSGF and county support transparency as an office-function bridge.",
      "Close on Secretary of State service obligations and execution metrics.",
    ],
    sourcedFacts: [
      "kim-hammer-kh0b-2021-integrity-foundation.json includes SB486, SB487, SB488, SB582, SB643, and SB644 package mapping.",
      "Acts 727, 728, 729, 973, 974, and 1051 are listed in package source metadata.",
      "Arkansas Advocate runoff reporting from March 2026 is linked in opponent lead-story references.",
      "ACCA Mountain View June 11 candidate panel is documented in conference depth files.",
      "hammerforarkansas.com claim lanes are indexed in Hammer claims-ledger research tracks.",
    ],
    fieldResearchNotes: [
      "In clerk rooms, keep executive-profile contrast to role function and implementation burden only.",
      "Never improvise ranking rebuttals unless the source artifact is in hand and pre-cleared.",
      "Treat biography acknowledgement as a bridge, not as the center of the response.",
    ],
  },
  "hammer-strengths-deep": {
    additionalNarrative: [
      "Hammer strengths should be treated as audience realities, not points to negate. Counsel-safe practice begins by acknowledging election-law fluency and base familiarity, then transitioning to administrative burden questions that county officials can verify from their own timelines, staffing limits, and support experiences.",
      "The six-bill 2021 package gives his strengths argument a memorably structured backbone that can dominate short exchanges. Kelly's highest-value move is to grant package coherence while asking what state-level support followed enactment, including training cadence, county guidance clarity, and transparent public help channels.",
      "hammerforarkansas.com strengths claims can appear polished and confidence-heavy, especially when merged with integrity branding. Instead of arguing tone, the safer move is claim decomposition: separate verified bill authorship from outcome claims, then request measurable county-facing results that tie to the office's service mandate.",
      "Runoff and campaign momentum references from March 2026 should be treated as contextual strength signals rather than policy proof. Counsel-safe framing can concede campaign viability and still insist that voters and clerks deserve operational evidence for implementation success, not only campaign-era rhetorical confidence.",
      "At ACCA Mountain View, strengths rebuttal fails when it sounds dismissive or ideological. It succeeds when Kelly sounds like the administrator in the room, asking practical questions on funding traceability, guidance timelines, and hotline accountability without disputing that Hammer has legislative command.",
      "Strengths strategy should be scripted as acknowledge, test, and offer. Acknowledge his known assets, test implementation outputs with factual precision, and offer a county service framework that appears constructive, disciplined, and defensible to moderators who prioritize practical governance over performative conflict.",
    ],
    additionalHardEvidence: [
      { claim: "Hammer strengths matrix identifies tenure, election-law specialization, and community identity as recurring validated strengths", tier: "VERIFIED" },
      { claim: "Claims-ledger files track hammerforarkansas.com messaging clusters and verification tiers", tier: "VERIFIED" },
      { claim: "ACCA panel prep emphasizes technical clerk audience expectations and implementation-focused questioning", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Identify which Hammer strength is active in the exchange before responding.",
      "Acknowledge the strength briefly, then move to implementation evidence demands.",
      "Use one county-support question tied to funding, training, or guidance publication.",
      "Offer Kelly's operational alternative and stop without overextending.",
    ],
    sourcedFacts: [
      "kim-hammer-strengths-matrix.json catalogs primary strength categories and confidence tags.",
      "kim-hammer-candidate-dossier.json connects strengths to election-security narrative architecture.",
      "kim-hammer-claims-ledger entries classify claim components by verification status.",
      "ACCA conference depth files describe clerk-centered audience conditions for June 11.",
      "KH-0B package records are cross-referenced in strengths and bill-record sections.",
    ],
    fieldResearchNotes: [
      "Never frame a recognized strength as fake when evidence shows it as real and audience-salient.",
      "Use one question per response lane to preserve calm administrator tone.",
      "Keep a pre-cleared phrasing bank to avoid drift into unsourced comparisons.",
    ],
  },
  "hammer-weaknesses-deep": {
    additionalNarrative: [
      "Hammer weakness framing must stay counsel-safe by focusing on governance consequences rather than attributing intent. The strongest lane is county burden and implementation friction, especially where policy packages expanded obligations faster than local support systems could absorb in normal election administration workflows.",
      "The direct-democracy and petition-restriction weakness lane should be framed as process tradeoff analysis, not morality theater. Kelly can ask whether fraud-prevention benefits were documented against participation friction, while explicitly avoiding claims of bad faith unless supported by verified primary records.",
      "CVSGF ledger trap is a controlled weakness lane because it concerns transparency architecture rather than accusation. The safe question is whether county-visible grant allocation and expenditure pathways were published with enough detail for local officials and voters to independently track deployment outcomes.",
      "Runoff competitiveness from March 2026 should not be used as personal diminishment language. It can be used narrowly to show that this contest is serious and that all claims deserve scrutiny under the same verification rules, which protects Kelly's credibility with moderators and clerk audiences.",
      "Weaknesses tied to rhetoric or controversy should remain in low-frequency use unless sourcing is complete and fresh. Counsel-safe doctrine prioritizes high-utility, low-risk lines that can be defended with records already in the file, reducing avoidable debate volatility and post-event corrections.",
      "The practical objective is disciplined pressure: raise implementation gaps, request proof, and return to service commitments. If Kelly keeps weaknesses procedural and evidence-labeled, she preserves trust while maintaining sharp accountability contrast against legislative branding-heavy messaging from Hammer.",
    ],
    additionalHardEvidence: [
      { claim: "Hammer vulnerability matrices classify county burden and petition-process restrictions as debate-usable lanes", tier: "VERIFIED" },
      { claim: "CVSGF transparency gap questions are documented in funding depth analysis as governance inquiries", tier: "VERIFIED" },
      { claim: "Arkansas Advocate runoff context supports competitiveness framing but not policy-outcome inference", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Select one weakness lane with verified records and clear audience relevance.",
      "Phrase the point as a governance question, not an intent accusation.",
      "Request implementation or ledger proof tied to county impact.",
      "Pivot back to Kelly's operational plan before escalation begins.",
    ],
    sourcedFacts: [
      "kim-hammer-vulnerability-matrix.json includes safer wording and risk-tier metadata.",
      "Funding depth files reference CVSGF transparency and county-facing accountability gaps.",
      "Petition and direct-democracy lanes appear in Hammer legislative pattern records.",
      "Runoff context from Arkansas Advocate is stored in lead-story references.",
      "Claims-ledger tooling differentiates verified fact, interpretation, and reported claim tiers.",
    ],
    fieldResearchNotes: [
      "Use weakness lanes as questions unless there is direct primary proof for a declarative line.",
      "Avoid bundling multiple weaknesses in one answer; it lowers perceived precision.",
      "Default to county-impact phrasing when moderator prompts feel adversarial.",
    ],
  },
  "hammer-claims-ledger": {
    additionalNarrative: [
      "Hammer claims-ledger work should be run as a verification workflow, not an argument pile. Each claim needs exact wording capture, tier assignment, source path, and response template before stage use. This discipline lowers error risk and increases moderator trust when exchanges turn technical.",
      "The six-bill package claims are usually verifiable at bill and act level, but downstream outcome claims require caution. Counsel-safe framing can concede authorship and enactment while testing evidence for county support adequacy, implementation speed, and service quality after statutory changes landed.",
      "CVSGF lane is where claim discipline matters most. Appropriation or funding references can be true while county-level transparency remains incomplete. Kelly's safest response is to separate those layers clearly and ask for public ledger detail, not to imply misconduct absent direct proof.",
      "hammerforarkansas.com claims often combine factual anchors with broad evaluative conclusions. The ledger should split factual and interpretive segments so Kelly can agree where verified and challenge where evidence is pending, preserving credibility while maintaining contrast on operational accountability and execution readiness.",
      "Runoff narrative claims from March 2026 can inform political context but should never be promoted as policy validation. Claims-ledger notes should mark that distinction explicitly, so staff avoid accidental overreach when time pressure tempts shorthand language during debates or press availability.",
      "A mature claims-ledger process ends with rehearsed agree-verify-contrast language. That structure keeps Kelly in counsel-safe territory, prevents reflex rebuttal errors, and gives a repeatable method for handling repeated Hammer lines without sounding evasive or personally combative.",
    ],
    additionalHardEvidence: [
      { claim: "Hammer claims-ledger artifacts classify recurring lines by evidence tier and response protocol", tier: "VERIFIED" },
      { claim: "KH-0B and bill index sources verify core 2021 sponsorship and act-mapping claims", tier: "VERIFIED" },
      { claim: "Funding depth notes distinguish appropriations facts from county-ledger transparency questions", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Capture the exact claim wording before selecting a response template.",
      "Map each claim component to verified, interpretation, or pending status.",
      "Respond with agree-verify-contrast language using one evidence anchor.",
      "Close on county-service commitments and avoid speculative add-ons.",
    ],
    sourcedFacts: [
      "kim-hammer-candidate-dossier.json tracks repeated campaign claims and response framing.",
      "kim-hammer-kh0b-2021-integrity-foundation.json verifies six-bill package metadata.",
      "kim-hammer-election-record-bill-index.json includes session and act-reference details.",
      "Funding depth files include CVSGF and county-transparency research questions.",
      "Claims-ledger rules define evidence-status categories used in debate preparation.",
    ],
    fieldResearchNotes: [
      "Always pre-brief staff on any claim status changes before public events.",
      "Do not rebut ranking claims with alternative rankings unless equally sourced and current.",
      "Treat uncertain claims as prompts for transparency questions, not declarative disputes.",
    ],
  },
  "hammer-lead-stories": {
    additionalNarrative: [
      "Hammer lead stories should be prioritized by trigger probability and downside risk. The top tier includes ACCA Mountain View June 11 exchanges, 2021 package framing, CVSGF transparency pressure, and runoff-context references. Story prioritization prevents over-prep on low-impact lanes that rarely appear in live moderator flow.",
      "March 2026 Arkansas Advocate runoff coverage belongs in context-only use. It supports competitiveness framing and voter attention, but it is not policy proof. Counsel-safe scripting should keep this story as a setup line when moderators ask electability or campaign dynamics questions directly.",
      "The six-bill package lead story is persistent because it is easy to narrate and hard to ignore. Kelly's adaptation should acknowledge package coherence, then ask what support architecture followed enactment for counties facing new workload, compliance complexity, and operational deadlines.",
      "CVSGF story placement should be strategic rather than repetitive. When introduced at the right moment, it reframes abstract integrity claims into measurable transparency obligations. The safest line requests county-visible documentation and update cadence, avoiding any accusation unsupported by verified records.",
      "hammerforarkansas.com story spikes often follow campaign content drops or social amplification. Staff should log exact phrasing and avoid paraphrase drift. Counsel-safe response quality depends on precise claim capture, especially when line edits in campaign copy subtly change what is actually being asserted.",
      "Lead-story management is complete only when post-event logging is immediate. Captured quotes, moderator framing, and audience reactions should feed back into claims tiers and script updates, so the next appearance reflects real-world exchange conditions rather than static draft assumptions.",
    ],
    additionalHardEvidence: [
      { claim: "ACCA June 11 panel is marked as a critical lead-story environment in conference planning files", tier: "VERIFIED" },
      { claim: "Runoff story references include Arkansas Advocate March 2026 coverage links in dossier data", tier: "VERIFIED" },
      { claim: "Hammer campaign claims tracked from hammerforarkansas.com are tied to claims-ledger records", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Sort lead stories by probability, impact, and verification readiness before each event.",
      "Assign one response frame and one evidence anchor to each priority story.",
      "Deploy only when trigger language appears in moderator or opponent remarks.",
      "Log outcomes immediately and refresh tiers for the next prep cycle.",
    ],
    sourcedFacts: [
      "kim-hammer-candidate-dossier.json includes prioritized lead-story fields.",
      "ACCA conference files identify June 11 Mountain View as high-density exchange setting.",
      "Arkansas Advocate runoff citation is linked in story references for March 2026 context.",
      "KH-0B package story appears across bill-record and claims-ledger modules.",
      "CVSGF transparency lane is documented in election-funding drill-down research.",
    ],
    fieldResearchNotes: [
      "Avoid introducing medium-priority stories unless high-priority lanes are exhausted.",
      "Use verbatim quote logging so claims-ledger updates are precise and auditable.",
      "Keep one fallback service frame ready when an unplanned story appears.",
    ],
  },
  "hammer-acca-panel-tactics": {
    additionalNarrative: [
      "ACCA Mountain View on June 11 should be handled as a technical governance forum where clerks and county operators evaluate execution credibility more than partisan volume. Tactical success depends on concise answers, respectful tone, and implementation-first questioning anchored in records rather than insinuation.",
      "Hammer's likely panel tactic is package fluency plus confidence framing. Kelly's counter is to concede legal authorship anchors, then ask specific county-execution questions on training cycles, guidance timing, and support channels. This keeps contrast counsel-safe and aligned with the audience's practical concerns.",
      "CVSGF ledger trap is especially effective in ACCA because county officials are accustomed to documentation standards. The question should remain neutral: what county-level tracking and publication pathways exist for grant allocations and expenditures, and how can clerks verify updates without political mediation.",
      "Three-way geometry with Pakko also matters at ACCA. Pakko can validate burden critiques while presenting reform language. Kelly should avoid competition for outsider bandwidth and instead become the implementation closer who turns shared concerns into concrete statewide service commitments.",
      "The June 11 room will likely reward procedural literacy over rhetorical aggression. Counsel-safe script design should avoid labels, motive claims, and speculative legal assertions, emphasizing verifiable records and operational planning that demonstrate readiness to manage county-facing administrative complexity immediately.",
      "Post-panel operations are part of tactics, not optional cleanup. Staff should capture exact claims, classify them by tier, and update lead-story decks within hours, ensuring future messaging reflects what was actually said rather than memory-dependent paraphrases or social clip distortions.",
    ],
    additionalHardEvidence: [
      { claim: "ACCA conference depth files list June 11 Mountain View SOS panel with Hammer, Kelly, and Pakko", tier: "VERIFIED" },
      { claim: "Funding transparency modules tie CVSGF ledger questions to county accountability concerns", tier: "VERIFIED" },
      { claim: "Three-way geometry guidance advises no spoiler language and execution-focused differentiation", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Open with clerk-service framing and shared integrity objective.",
      "Ask one implementation question after any broad Hammer claim packet.",
      "Deploy CVSGF ledger transparency line only with neutral governance wording.",
      "Close on county partnership deliverables and immediate follow-up discipline.",
    ],
    sourcedFacts: [
      "accaClerksConference2026Depth.ts records panel logistics and audience context.",
      "Opponent dossiers reference ACCA as a critical lead-story event for all candidates.",
      "Funding drill-down materials include CVSGF transparency inquiry language.",
      "Pakko three-way sections emphasize reform overlap and role-differentiation strategy.",
      "Claims-ledger guidance requires quote capture and post-event evidence reclassification.",
    ],
    fieldResearchNotes: [
      "Assign one staffer to quotes and one to county-question themes during the panel.",
      "Cap each Kelly answer at one acknowledgment and one operational ask.",
      "Defer any uncertain legal specifics to documented follow-up instead of ad-libbing.",
    ],
  },
  "hammer-bill-record-arc": {
    additionalNarrative: [
      "Hammer bill-record arc should be presented as sequence across 2021, 2023, and 2025 rather than isolated talking points. Sequence framing helps audiences understand continuity while giving Kelly a structured path to test implementation impacts on counties that had to absorb recurring procedural change.",
      "The 2021 package remains the cleanest anchor: SB486, SB487, SB488, SB582, SB643, and SB644 tied to Acts 727-729, 973-974, and 1051. Counsel-safe deployment should cite this accurately and then move to what changed for local administration in practice.",
      "Bill-arc responses should separate enactment certainty from outcome interpretation. A law can be real and still produce uneven county burdens if support systems lag. That distinction protects credibility and allows Kelly to challenge execution outcomes without contesting the underlying legislative record itself.",
      "Later-cycle petition and procedural bills should be framed as continuity themes, not proof of motive. The safer language asks whether participation protections, compliance clarity, and county support resources evolved proportionally with legal complexity imposed over multiple sessions.",
      "hammerforarkansas.com references to election-law leadership can be acknowledged as narrative consistency. The response lane is operational: what statewide guidance artifacts, training updates, and county-facing transparency outputs accompanied the bill arc over time, and were they published predictably for public scrutiny.",
      "A strong bill-record answer avoids bill-soup delivery. It uses three anchors maximum, translates each into county-level implementation relevance, and closes with Kelly's service plan. That pattern keeps exchanges understandable and defensible under moderator time pressure and post-event fact checks.",
    ],
    additionalHardEvidence: [
      { claim: "Bill index and KH-0B files verify 2021 package bill numbers and act mappings", tier: "VERIFIED" },
      { claim: "Bill-record datasets include multi-session election-related entries beyond 2021", tier: "VERIFIED" },
      { claim: "Petition-era continuity themes appear in 2025 bill tracking metadata", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Anchor with one verified 2021 package fact including bill and act mapping.",
      "Add one later-session continuity point with clear source status.",
      "Translate each anchor into county implementation pressure or support needs.",
      "End with Kelly's execution and transparency commitments for counties.",
    ],
    sourcedFacts: [
      "kim-hammer-election-record-bill-index.json includes session, summary, and act-reference fields.",
      "kim-hammer-kh0b-2021-integrity-foundation.json details six-bill architecture and narratives.",
      "2025 petition-cluster entries are documented in election record tracking data.",
      "Claims-ledger modules reference bill-arc claims as recurring campaign talking points.",
      "ACCA prep materials frame bill-record questions around county execution impact.",
    ],
    fieldResearchNotes: [
      "Keep a one-page bill-to-county-impact cheat sheet for live responses.",
      "Never overstate legal effects beyond what source summaries explicitly support.",
      "If uncertain on a bill detail, cite known anchor and defer granular interpretation.",
    ],
  },
  "hammer-kelly-response-playbook": {
    additionalNarrative: [
      "The Hammer response playbook should run on a repeatable cadence: affirm shared objective, test implementation evidence, then close on service delivery. This sequence is counsel-safe, keeps tone disciplined, and reduces risk of unforced errors when exchanges become rapid or confrontational.",
      "For six-bill and integrity claims, playbook language should concede what records confirm while preserving room to question county support outcomes. This avoids denial traps and positions Kelly as a practical administrator focused on whether laws were made usable for local officials and voters.",
      "CVSGF transparency lines belong in the middle phase of the sequence, where evidence testing occurs. The safest prompt asks for county-visible ledger mechanics and publication cadence, not for admissions of wrongdoing. Neutral governance language increases moderator tolerance for sharp accountability questions.",
      "When hammerforarkansas.com lines are quoted, playbook discipline requires exact wording capture and tier check. Staff should avoid memory paraphrase because subtle wording changes can alter claim category. Precision protects Kelly from rebutting claims that were never actually stated in that form.",
      "Runoff context from March 2026 can be acknowledged when electability framing appears, but should not displace office-function contrast. The playbook's core purpose is governance differentiation, not campaign punditry, especially in clerk settings where operational detail carries greater persuasive value.",
      "The best playbook performance is brief and calm. Once the contrast lands, Kelly should stop and yield. Overextension introduces speculation risk and dilutes the administrator persona that this playbook is designed to reinforce across repeated opponent interactions.",
    ],
    additionalHardEvidence: [
      { claim: "Opponent response modules define agree-verify-contrast structure for Hammer exchanges", tier: "VERIFIED" },
      { claim: "Claims-ledger process requires exact quote capture before rebuttal or extension", tier: "VERIFIED" },
      { claim: "Funding depth files provide neutral CVSGF transparency prompts suitable for clerk audiences", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Agree on objective, then identify the exact claim being made.",
      "Verify status and test one implementation or transparency element.",
      "State one county-service commitment that addresses the identified gap.",
      "Stop speaking after the close to preserve discipline and tone.",
    ],
    sourcedFacts: [
      "kim-hammer-candidate-dossier.json includes scripted response lanes for recurring claims.",
      "hammer-claims-ledger entries define evidence tiers and safe rebuttal posture.",
      "Funding depth and CVSGF research assets contain governance-safe question templates.",
      "Runoff reference from Arkansas Advocate is linked in lead-story context files.",
      "ACCA tactical notes recommend concise, non-accusatory implementation questioning.",
    ],
    fieldResearchNotes: [
      "Rehearse 45-second and 90-second versions of the same playbook response.",
      "If interrupted, skip re-argument and move directly to service commitment close.",
      "Flag any ad-lib line that introduces claims not present in the verified ledger.",
    ],
  },
  "hammer-2021-six-bill-deep": {
    additionalNarrative: [
      "The 2021 six-bill packet is foundational and should be memorized with precise pairing: SB486, SB487, SB488, SB582, SB643, and SB644 mapped to Acts 728, 729, 727, 1051, 973, and 974. Accuracy here signals seriousness and prevents easy procedural credibility hits.",
      "Counsel-safe framing should treat the package as real legislative architecture while preserving space to question implementation burden. Kelly can ask whether counties received synchronized guidance, staffing support, and training timelines commensurate with six substantial process changes in one session.",
      "SB486 and SB487 lanes are often used rhetorically as broad integrity proof. The disciplined response acknowledges statutory change and then tests real-world execution effects, including polling-site operations, precinct processes, and downstream burden on county election workers under practical constraints.",
      "SB488, SB582, SB643, and SB644 each introduce specific procedural implications that should be discussed without overclaiming legal outcomes. Use title-level confidence where necessary and avoid definitive causal assertions unless legal text and implementation data are directly corroborated.",
      "This section should connect to CVSGF and support infrastructure questions where appropriate. If policy complexity increased, did transparency and assistance mechanisms scale accordingly. That governance question remains counsel-safe, measurable, and highly relevant to the Secretary of State operating mandate.",
      "In live forums, the six-bill deep lane should end with an implementation offer, not merely critique. Kelly gains credibility by translating accurate bill references into a practical county-support plan that emphasizes guidance publication, training consistency, and accessible escalation channels.",
    ],
    additionalHardEvidence: [
      { claim: "KH-0B file lists all six 2021 bills with enrolled act mappings and plain-language summaries", tier: "VERIFIED" },
      { claim: "Bill index metadata confirms package continuity and affected-office tags for county administration", tier: "VERIFIED" },
      { claim: "Claims-ledger records show six-bill package as recurring Hammer argument anchor", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Recite six bill-and-act pairings accurately before making any contrast claim.",
      "Select two package elements and ask how counties were operationally supported.",
      "Use one transparency bridge tied to guidance publication or grant accountability.",
      "Close with Kelly's implementation-first service framework for all counties.",
    ],
    sourcedFacts: [
      "kim-hammer-kh0b-2021-integrity-foundation.json contains bill and act mapping records.",
      "kim-hammer-election-record-bill-index.json includes affected-office and summary fields.",
      "Acts 727, 728, 729, 973, 974, and 1051 are represented in package files.",
      "Hammer claims-ledger references six-bill package as repeated campaign proof point.",
      "ACCA strategy notes anticipate package references in clerk-facing exchanges.",
    ],
    fieldResearchNotes: [
      "Drill pairings until recall is automatic to avoid stage hesitation errors.",
      "Use title-level language when legal-text interpretation remains pending counsel review.",
      "Never imply outcome certainty beyond documented implementation evidence.",
    ],
  },
  "hammer-background-business-pastoral": {
    additionalNarrative: [
      "Hammer background, business, and pastoral identity should be handled with respect-first discipline. Counsel-safe strategy acknowledges biography and community service while avoiding personal attack lanes, then pivots quickly to office-function standards where candidates can be compared on administration rather than identity.",
      "Pastoral and community-service records often function as trust multipliers with voters. Kelly should not contest personal legitimacy narratives directly. The effective contrast asks whether county users received consistent, transparent operational support as legislative requirements grew and election systems became more complex.",
      "Business references in public reporting require careful sourcing and neutral wording. If raised, Kelly should stay inside documented facts and avoid implication language. Biography lanes can become legal risk zones when unsourced innuendo replaces verified records and clearly bounded interpretation markers.",
      "At ACCA and clerk forums, biography conflict generally underperforms compared with operations framing. County officials tend to prioritize practical execution evidence. A brief respectful acknowledgment followed by implementation questions preserves tone, avoids backlash, and reinforces Kelly's administrator posture.",
      "hammerforarkansas.com often foregrounds values and trust language linked to biography. The counsel-safe response does not dispute values claims. It asks how those values translated into transparent support systems, guidance quality, and county-level usability under actual statutory and budget constraints.",
      "This section's purpose is inoculation against bait. If moderators invite personal-comparison exchanges, Kelly should decline escalation and return to service commitments. That restraint strengthens credibility and keeps debate content aligned with Secretary of State responsibilities that voters can evaluate concretely.",
    ],
    additionalHardEvidence: [
      { claim: "Background profile files include pastoral and community service references with source confidence tags", tier: "VERIFIED" },
      { claim: "Business-related mentions are documented as reported items requiring careful phrasing boundaries", tier: "PARTIAL" },
      { claim: "Campaign-site biography framing appears in hammerforarkansas.com message clusters", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Acknowledge background respectfully in one sentence without evaluative language.",
      "Decline personal-comparison framing and pivot to office-function metrics.",
      "Ask one implementation question linked to county support or transparency.",
      "Close on Kelly's service commitments and equal county treatment.",
    ],
    sourcedFacts: [
      "kim-hammer-background-deep-profile.json includes pastoral, civic, and business reference fields.",
      "Source confidence tags in background files distinguish verified and partial items.",
      "hammerforarkansas.com claim clusters include values-and-trust biography messaging.",
      "Opponent strategy modules advise biography acknowledgement plus operations pivot.",
      "ACCA tactics notes prioritize technical implementation framing over personal conflict.",
    ],
    fieldResearchNotes: [
      "Never introduce business allegations unless already sourced and counsel-cleared.",
      "Use respectful tone guardrails in all faith and background references.",
      "If biography is moderator-led, answer briefly and return to administration.",
    ],
  },
  "packo-executive-profile": {
    additionalNarrative: [
      "Packo executive profile should be treated as credible third-candidate infrastructure, not novelty. The verified arc includes Federal Reserve Bank of St. Louis service from 1993 to 2009, Arkansas AEDI leadership, and long Libertarian Party chair continuity that shapes policy communication credibility.",
      "Counsel-safe differentiation acknowledges Pakko's analytical strengths while emphasizing Secretary of State execution obligations. Kelly should avoid electability taunts and instead frame contrast around county operations, implementation logistics, and statewide service systems that must perform under legal deadlines and public scrutiny.",
      "At ACCA Mountain View on June 11, Pakko can resonate with process-focused audiences through reform language. Kelly's advantage is not rejection of reform themes but conversion of those themes into specific administrative outputs like publication schedules, clerk training cadence, and practical escalation pathways.",
      "Pakko timeline depth supports respectful stage handling: economist identity, communicator presence, and party leadership discipline. These facts should be conceded where verified. Contrast begins only when discussing day-one office operations and who can manage county execution across changing legal and procedural requirements.",
      "Three-way settings can tempt direct Hammer-versus-Pakko comparison requests. Counsel-safe protocol is to avoid referee language and remain role-specific. Kelly should state that analysis and reform matter, then emphasize that Secretary of State success is measured by implementation reliability for all counties.",
      "Executive-profile messaging should also watch naming consistency and source precision. Internal files may carry mixed spellings, but on-stage references should remain accurate and respectful. Professional tone discipline helps Kelly look steady while maintaining substantive differentiation rooted in office function.",
    ],
    additionalHardEvidence: [
      { claim: "Bio timeline files record Fed St. Louis tenure from 1993-2009 and AEDI leadership from 2009 onward", tier: "VERIFIED" },
      { claim: "Pakko records identify long Libertarian Party chair tenure and 2026 SOS nomination status", tier: "VERIFIED" },
      { claim: "ACCA June 11 panel listings include Kelly, Hammer, and Pakko in shared forum context", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Acknowledge Pakko credentials with one verified timeline anchor.",
      "Bridge from shared reform value to office-execution requirements.",
      "Differentiate using county implementation deliverables and accountability rhythms.",
      "Close respectfully and avoid electability or spoiler language.",
    ],
    sourcedFacts: [
      "michael-packo-bio-timeline.json includes Fed and AEDI chronology anchors.",
      "michael-packo-candidate-dossier.json tracks nomination, claims, and profile framing.",
      "michael-packo-strengths-matrix.json identifies communicator and reform strengths.",
      "ACCA conference depth files include June 11 three-candidate panel context.",
      "Three-way geometry sections advise respect-first role differentiation strategy.",
    ],
    fieldResearchNotes: [
      "Never frame Pakko as illegitimate or unserious; it backfires in process audiences.",
      "Use one credential acknowledgment before any operational contrast line.",
      "Keep all differentiation tied to Secretary of State duties and county service.",
    ],
  },
  "packo-strengths-deep": {
    additionalNarrative: [
      "Packo strengths are best understood as persuasion assets in analytical and reform-oriented rooms. Economist background, communication fluency, and long party leadership continuity can make his answers sound coherent and calm, especially when moderators seek structural critiques rather than campaign-style attack exchanges.",
      "Counsel-safe handling means respecting those strengths while preserving Kelly's office-readiness contrast. The objective is not to dispute Pakko competence in policy analysis, but to clarify that Secretary of State administration requires implementation systems, county support infrastructure, and sustained operational follow-through.",
      "The Fed-to-AEDI career arc gives Pakko credibility with audiences that value technical framing. Kelly should concede this as verified context and then ask who can execute statewide service obligations under real statutory timelines, staffing realities, and county variation in operational capacity.",
      "At ACCA, strengths like calm demeanor and burden skepticism can resonate with clerks. Kelly should avoid defensive tone and instead convert agreement moments into concrete deliverables, such as guidance publication standards, support hotlines, and transparent county-facing tracking commitments tied to office responsibilities.",
      "Pakko's LP chair continuity can be framed as organizational persistence without conceding executive readiness for the SOS operating environment. Counsel-safe language can respect persistence while asking practical questions about implementation playbooks, inter-county consistency, and administrative escalation procedures that voters can evaluate.",
      "The most reliable formula is acknowledge strength, extend into execution specifics, and close with service commitments. This avoids unnecessary conflict, preserves moderator trust, and demonstrates that Kelly can absorb valid reform concerns while still leading the conversation toward operational competence.",
    ],
    additionalHardEvidence: [
      { claim: "Pakko strengths matrix documents economist communicator profile and debate-impact assessments", tier: "VERIFIED" },
      { claim: "Bio timeline confirms Fed St. Louis and AEDI career anchors used in strengths framing", tier: "VERIFIED" },
      { claim: "ACCA planning notes identify reform and burden themes likely to intersect with Pakko strengths", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Identify the Pakko strength being highlighted before answering.",
      "Acknowledge it briefly with one verified source anchor.",
      "Extend into county-execution requirements for the SOS role.",
      "Close on Kelly's concrete implementation commitments and tone discipline.",
    ],
    sourcedFacts: [
      "michael-packo-strengths-matrix.json lists strengths and confidence metadata.",
      "michael-packo-bio-timeline.json provides chronology for credential references.",
      "michael-packo-candidate-dossier.json includes recurring reform and transparency claims.",
      "ACCA conference files frame three-way exchanges around implementation and burden.",
      "Three-way strategy guidance emphasizes respectful extension instead of dismissal.",
    ],
    fieldResearchNotes: [
      "Do not collapse Pakko strengths into caricature labels or dismissive shorthand.",
      "Use extension framing more than contradiction framing in live debates.",
      "Keep one default administrator-contrast close ready for unexpected moderator pivots.",
    ],
  },
  "packo-weaknesses-deep": {
    additionalNarrative: [
      "Packo weaknesses should be framed as office-function gaps, not ideological disqualification. Counsel-safe language can acknowledge reform energy while asking how proposals become county-operable systems with clear guidance, training support, and compliance pathways under the practical constraints election officials face.",
      "The core weakness lane is administration specificity. Policy analysis and transparency rhetoric can be persuasive, but Secretary of State execution requires procedural detail: who publishes guidance, when updates occur, how counties escalate, and what accountability rhythm governs statewide implementation performance.",
      "At ACCA and similar forums, direct anti-Libertarian framing is strategically costly and substantively unnecessary. Kelly can differentiate effectively by agreeing on concern, then pressing for executable plan details. This preserves respect, avoids backlash, and keeps moderator focus on managerial readiness.",
      "Pakko's Fed and AEDI background should be acknowledged as credible analytic preparation, yet still separated from office administration workload. Counsel-safe contrast asks whether campaign framing has translated into specific operational workflows that county clerks and election workers could actually run tomorrow.",
      "Weakness messaging must avoid vote-direction cues, spoiler framing, or strategic electoral math. Those lines introduce reputational risk and distract from governance substance. The strongest differentiation remains practical: Kelly's plan for statewide service delivery consistency under statutory obligations and public accountability expectations.",
      "A disciplined weakness response ends quickly. Raise one role-specific question, offer one administrative commitment, and stop. Overextension can sound defensive and creates opportunities for mischaracterization, while concise role-based contrast keeps Kelly credible with process-focused audiences.",
    ],
    additionalHardEvidence: [
      { claim: "Packo dossier identifies research and operational-detail gaps in SOS administration specifics", tier: "VERIFIED" },
      { claim: "Three-way guidance explicitly warns against spoiler or anti-Libertarian framing", tier: "VERIFIED" },
      { claim: "ACCA tactical notes favor implementation-focused contrast over ideological conflict", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Agree on a valid reform concern to establish respect and shared objective.",
      "Ask how the proposal maps to county implementation and accountability mechanics.",
      "Differentiate Kelly on operational readiness and statewide service infrastructure.",
      "Close without electability language or adversarial escalation.",
    ],
    sourcedFacts: [
      "michael-packo-candidate-dossier.json records claim clusters and open research items.",
      "michael-packo-bio-timeline.json supports credential acknowledgment before contrast.",
      "packo-three-way-geometry section codifies no-spoiler language discipline.",
      "ACCA conference depth materials prioritize county-operability questions.",
      "Strengths matrix flags high-persuasion lanes that require careful response posture.",
    ],
    fieldResearchNotes: [
      "Phrase every weakness line as role requirements, not voter-judgment language.",
      "If uncertain on Packo policy detail, pivot to implementation questions immediately.",
      "Keep response length short to preserve calm, professional contrast optics.",
    ],
  },
  "packo-claims-ledger": {
    additionalNarrative: [
      "Packo claims-ledger workflow should prioritize respectful precision. Many Pakko claims are values-compatible with Kelly's transparency messaging, so blunt rebuttal is often suboptimal. Counsel-safe practice is to agree where verified, then extend into specific implementation commitments expected from a Secretary of State.",
      "Claims around transparency, competitiveness, and independent governance should be split into factual and interpretive components. This prevents accidental over-endorsement while preserving tone. Kelly can acknowledge principle alignment and still ask for county-operable detail that voters can use to compare execution readiness.",
      "Fed and AEDI credentials can strengthen claim delivery credibility for Pakko, especially in policy-heavy forums. The ledger should treat those credentials as context, not claim proof. Administrative promises still require practical pathways, timelines, and county-facing accountability mechanisms to be considered complete.",
      "At ACCA, claims-ledger discipline matters because clerks may probe practical follow-through. Kelly should be prepared to move from shared-value agreement to operational specifics quickly, demonstrating that transparency in office depends on publication systems, support infrastructure, and measurable service standards.",
      "Some reform-detail claims may remain under-researched or quote-incomplete. Counsel-safe handling labels uncertainty and avoids speculative rebuttal. If a claim is unverified, Kelly can ask clarifying questions and return to her own documented execution plan without appearing evasive or dismissive.",
      "Packo ledger strategy should be additive rather than adversarial: agree, specify, and deliver. This keeps three-way exchanges constructive, protects credibility, and prevents the conversation from drifting into ideological sorting that obscures the administrative duties voters are actually choosing for.",
    ],
    additionalHardEvidence: [
      { claim: "Packo candidate dossier tracks recurring claims with evidence-status metadata", tier: "VERIFIED" },
      { claim: "Bio timeline and strengths files support credential context but not automatic operational proof", tier: "VERIFIED" },
      { claim: "Three-way strategy modules define respectful agree-and-extend response architecture", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Capture and classify each Packo claim by verified and interpretive components.",
      "Agree on verified value elements without overcommitting to interpretations.",
      "Add county-implementation specifics Kelly would execute in office.",
      "Exit response with respect and no partisan or spoiler framing.",
    ],
    sourcedFacts: [
      "michael-packo-candidate-dossier.json includes claim tables and response cues.",
      "michael-packo-bio-timeline.json documents credential background for context.",
      "michael-packo-strengths-matrix.json provides persuasion and confidence signals.",
      "packo-three-way-geometry guidance prescribes respectful differentiation methods.",
      "ACCA preparation files emphasize implementation detail in clerk-facing discourse.",
    ],
    fieldResearchNotes: [
      "Do not rebut value statements as if they were factual errors.",
      "If quote precision is missing, shift to a transparency standards question.",
      "Keep a short extension template ready for repeated Packo transparency lines.",
    ],
  },
  "packo-lead-stories": {
    additionalNarrative: [
      "Packo lead stories should be managed as geometry triggers rather than attack opportunities. The highest-priority stories involve reform overlap at ACCA, transparency alignment moments, and moderator prompts about independent governance. Story strategy should protect respect while preserving Kelly's execution-focused distinction.",
      "The June 11 ACCA panel is central because Packo can validate burden concerns without carrying Hammer's legislative ownership. Kelly's response should welcome shared concern and then transition into practical office delivery commitments, showing she can operationalize reform sentiment at statewide county scale.",
      "Packo lead stories tied to career credentials should be acknowledged as verified context, not dismissed. Fed St. Louis 1993-2009 and AEDI tenure support analytical profile narratives. Differentiation should remain office-specific: analysis is valuable, but administration requires execution systems and accountability cadence.",
      "Three-way story handling should avoid unnecessary conflict. Counsel-safe doctrine is to reject spoiler framing, avoid vote-direction language, and treat Packo as a legitimate participant. This posture builds moderator trust and keeps Kelly's tone aligned with statewide service leadership expectations.",
      "Transparency co-sign stories can be highly productive if Kelly extends quickly into measurable outputs. Instead of competing for rhetorical ownership, she should specify publication schedules, county guidance standards, and documented support pathways that a Secretary of State can actually implement and maintain.",
      "Post-event lead-story logging remains essential. Staff should record exact Packo language, classify claim status, and update response decks. The objective is not to harden opposition narrative, but to refine respectful operational contrasts that remain accurate under repeated public scrutiny.",
    ],
    additionalHardEvidence: [
      { claim: "Packo dossier identifies ACCA and transparency overlap as high-priority lead-story triggers", tier: "VERIFIED" },
      { claim: "Bio timeline anchors Fed 1993-2009 and AEDI tenure for credential-context story lanes", tier: "VERIFIED" },
      { claim: "Three-way guidance requires no spoiler language in Packo handling", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Prioritize Packo lead stories by trigger likelihood and operational relevance.",
      "Respond with respect-first extension into execution specifics.",
      "Use verified credential anchors only as context, not as rebuttal targets.",
      "Log exact phrasing after events and update response tiers promptly.",
    ],
    sourcedFacts: [
      "michael-packo-candidate-dossier.json includes prioritized lead stories and cues.",
      "michael-packo-bio-timeline.json documents credential timeline used in story handling.",
      "packo-three-way-geometry section defines respectful contrast constraints.",
      "ACCA conference files frame June 11 as central three-way interaction surface.",
      "Strengths matrix records persuasion factors relevant to lead-story sequencing.",
    ],
    fieldResearchNotes: [
      "Treat Packo stories as contrast calibration tools, not hostility prompts.",
      "Capture quotes verbatim to avoid misclassification in the claims ledger.",
      "Keep one fallback line focused on county execution when stories are unexpected.",
    ],
  },
  "packo-three-way-geometry": {
    additionalNarrative: [
      "Three-way geometry with Packo should be approached as disciplined asymmetry: respect Packo's reform and analysis credibility, hold Hammer to record accountability, and position Kelly as the execution candidate. This structure keeps tone constructive while making office-readiness distinctions visible and defensible.",
      "At ACCA Mountain View, shared burden concerns may emerge from both opponents for different reasons. Kelly's geometry advantage is to convert shared critique into practical commitments: publication discipline, county training support, and transparent operational reporting that can be evaluated by clerks and voters alike.",
      "Counsel-safe geometry explicitly excludes spoiler framing, electoral math speculation, and vote-direction cues. Those lines introduce legal and reputational risk without improving governance contrast. Kelly should instead use role clarity language that respects all participants while emphasizing Secretary of State administrative obligations.",
      "Packo credentials, including Fed St. Louis 1993-2009 and AEDI leadership, can elevate his reform framing. Kelly should concede those credentials and then ask implementation questions: what mechanisms, timelines, and county-interface structures would produce reliable service under statutory pressure and public scrutiny.",
      "Geometry responses should remain compact. Acknowledge shared concern, differentiate on execution, and close on statewide service to all lawful users. Brevity prevents crossfire traps and maintains the calm administrator tone that can outperform both opposition styles in high-information forums.",
      "This section should be rehearsed with interruption and forced-choice moderator prompts. Kelly needs a stable phrase set that declines binary framing while still answering directly. Counsel-safe language can deliver clarity without antagonism, preserving trust with clerks, media, and undecided process-focused voters.",
    ],
    additionalHardEvidence: [
      { claim: "Three-way modules identify no-spoiler and no-vote-direction constraints as mandatory guardrails", tier: "VERIFIED" },
      { claim: "ACCA conference depth files describe June 11 as a major three-candidate geometry test", tier: "VERIFIED" },
      { claim: "Packo timeline records Fed and AEDI credentials that shape his reform credibility in shared forums", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Acknowledge shared concern without selecting a side in opponent crossfire.",
      "Differentiate Kelly on county execution systems and operational accountability.",
      "Decline spoiler framing and keep language role-specific and counsel-safe.",
      "Close with all-county service commitments and measurable transparency outputs.",
    ],
    sourcedFacts: [
      "packo-three-way-geometry guidance codifies permitted and prohibited framing patterns.",
      "accaClerksConference2026Depth.ts marks June 11 panel as key geometry event.",
      "michael-packo-bio-timeline.json provides verified credential references for acknowledgment.",
      "michael-packo-candidate-dossier.json includes overlap lanes with Hammer critiques.",
      "Opponent tactical modules prioritize execution-focused closes in three-way settings.",
    ],
    fieldResearchNotes: [
      "Practice decline lines for moderator attempts to force binary candidate positioning.",
      "Avoid body-language cues that imply personal conflict with Packo during exchanges.",
      "Keep one short geometry close that always returns to county service delivery.",
    ],
  },
  "packo-bio-career": {
    additionalNarrative: [
      "Packo bio-career content should be used as respectful grounding, not opposition caricature. The verified timeline from Fed St. Louis service beginning in 1993 through 2009, then Arkansas AEDI leadership, establishes a serious policy-analysis profile that audiences may view as credible and steady.",
      "Long Libertarian Party chair continuity adds organizational durability to his public role, which can influence moderator treatment and voter expectations. Counsel-safe handling acknowledges this persistence while reserving contrast for office-function specifics that distinguish policy commentary from statewide administrative management duties.",
      "Career references should remain source-disciplined and concise. Overly detailed biography recitation can distract from Secretary of State comparison. Kelly's best move is one credential acknowledgment followed by operational differentiation centered on county support systems, guidance reliability, and implementation accountability cadence.",
      "At ACCA and other technical forums, Pakko's communication style may read as calm competence. Kelly can respond by matching composure and emphasizing administrative readiness. The contrast is not who sounds analytical, but who can run day-to-day SOS workflows under legal deadlines and operational stress.",
      "Biography handling must avoid spelling and naming inconsistencies in live settings. Internal files may include mixed labels, but public-facing references should be accurate and respectful to prevent avoidable credibility noise that can overshadow substantive policy and governance points.",
      "Counsel-safe doctrine for this section is simple: concede verified career facts, avoid dismissive framing, and pivot to office requirements. That approach protects tone, preserves trust, and keeps the debate centered on practical public-service outcomes that matter to counties and voters.",
    ],
    additionalHardEvidence: [
      { claim: "Bio timeline files document Packo Fed St. Louis service from 1993-2009 and AEDI leadership period", tier: "VERIFIED" },
      { claim: "Packo records include LP chair continuity and statewide candidacy milestones", tier: "VERIFIED" },
      { claim: "ACCA planning indicates biography and qualification prompts are likely in moderated panel format", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Acknowledge one verified Packo credential and career milestone.",
      "Bridge immediately to Secretary of State role requirements and county operations.",
      "Avoid over-detailed biography discussion that consumes policy response time.",
      "Close with Kelly's administration-first commitments and equal service framing.",
    ],
    sourcedFacts: [
      "michael-packo-bio-timeline.json includes dated milestones from education through 2026 cycle.",
      "michael-packo-candidate-dossier.json summarizes profile and recurring campaign themes.",
      "Strengths matrices link communicator profile to public economist role visibility.",
      "ACCA depth files show likely qualification-focused prompt environments.",
      "Three-way guidance recommends respectful biography handling and role-based contrast.",
    ],
    fieldResearchNotes: [
      "Keep biography acknowledgment under one sentence in most debate responses.",
      "Verify pronunciation and spelling in moderator materials before events.",
      "Do not infer unlogged career details beyond timeline records.",
    ],
  },
  "packo-kelly-response-playbook": {
    additionalNarrative: [
      "Kelly's Packo playbook should run respect-first differentiation on repeat. The purpose is to keep coalition openness while showing administrative readiness superiority. Counsel-safe wording starts with shared reform principle, then transitions to concrete execution standards expected from a Secretary of State.",
      "Packo's transparency and competitiveness lines are often values-compatible with Kelly messaging. The playbook should avoid unnecessary contradiction and instead extend into practical commitments: publication cadence, county guidance delivery, help-channel responsiveness, and documented accountability workflows for implementation performance.",
      "At ACCA and other policy-heavy forums, this playbook protects tone and focus. Kelly should acknowledge Packo's analytic credibility, including Fed and AEDI context where relevant, but keep contrast anchored to operational management responsibilities that require daily statewide administrative leadership.",
      "No spoiler language is a hard constraint. Counsel-safe practice rejects electability taunts, strategic-vote suggestions, and party-dismissive phrasing. Those lines damage trust and distract from governance arguments. Respectful discipline gives Kelly more credibility with moderators and process-focused undecided voters.",
      "When Packo critiques opacity or mandates, Kelly should absorb the concern and lead with implementation detail. This additive style can outperform adversarial replies because it demonstrates practical readiness while avoiding needless conflict with a candidate many audiences perceive as policy-serious.",
      "The playbook should end every exchange quickly with a county-service close. Over-speaking introduces risk and can blur differentiation. The best result is calm, precise, and operationally grounded: acknowledge, specify, deliver, then yield the floor.",
    ],
    additionalHardEvidence: [
      { claim: "Packo response modules define respect-first, implementation-focused contrast as primary strategy", tier: "VERIFIED" },
      { claim: "Three-way geometry guidance forbids spoiler framing and vote-direction language", tier: "VERIFIED" },
      { claim: "Bio and strengths files support acknowledging Fed/AEDI analytical profile before office contrast", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Agree on valid transparency concern and acknowledge Packo credentials briefly.",
      "Differentiate with one concrete SOS execution commitment and timeline.",
      "Avoid electability or spoiler framing under any moderator prompt.",
      "Close on county service obligations and equal treatment standards.",
    ],
    sourcedFacts: [
      "michael-packo-candidate-dossier.json includes response framing cues for recurring claims.",
      "packo-three-way-geometry section lists prohibited and preferred language patterns.",
      "michael-packo-bio-timeline.json provides credential anchors for respectful acknowledgment.",
      "michael-packo-strengths-matrix.json highlights persuasion dynamics relevant to tone discipline.",
      "ACCA tactical files emphasize concise administrator closes in three-way contexts.",
    ],
    fieldResearchNotes: [
      "Rehearse interruption-resistant versions of the playbook close sentence.",
      "If uncertain on a Packo detail, return to Kelly's documented implementation plan.",
      "Audit post-event clips for tone drift into adversarial language and correct quickly.",
    ],
  },
  "packo-economist-platform-deep": {
    additionalNarrative: [
      "Packo economist-platform depth is anchored in a long Fed St. Louis tenure from 1993 through 2009 and continued Arkansas AEDI leadership. This profile supports an evidence-driven communication style that can resonate with policy-oriented audiences and moderators seeking technical framing.",
      "Long LP chair continuity adds platform stability and helps explain why Packo messaging can influence debate structure beyond raw vote share assumptions. Counsel-safe handling should acknowledge this organizational persistence while keeping contrast focused on statewide administrative execution responsibilities.",
      "Economist-platform arguments often emphasize transparency, competitiveness, and structural reform. Kelly should not reject those values reflexively. The effective move is to ask how each principle maps to county-operable systems, legal timelines, and practical support mechanisms under Secretary of State authority.",
      "At ACCA, platform depth can appear as calm analytical commentary. Kelly's differentiation is implementation command: who publishes guidance, how counties receive updates, what escalation channels exist, and how transparent reporting is maintained. This role-specific contrast keeps exchanges substantive and non-combative.",
      "Counsel-safe script design requires clear evidence labeling for platform claims not fully quoted or sourced. Where details remain pending, Kelly can state shared principle and return to documented execution commitments, avoiding speculative disputes that create avoidable fact-check vulnerabilities.",
      "This section should finish with office-function clarity. Analysis expertise is valuable, but the Secretary of State role is judged by operational reliability across counties. Kelly's strongest close is a concrete service promise that demonstrates executable governance rather than theoretical alignment alone.",
    ],
    additionalHardEvidence: [
      { claim: "Bio timeline verifies Packo Fed St. Louis 1993-2009 and AEDI tenure beginning in 2009", tier: "VERIFIED" },
      { claim: "Packo records include LP chair continuity and statewide campaign milestones relevant to platform stability", tier: "VERIFIED" },
      { claim: "Strengths matrices document economist communicator profile as a high-impact persuasion lane", tier: "VERIFIED" },
    ],
    additionalWalkthrough: [
      "Anchor response in one verified career milestone from Fed or AEDI timeline.",
      "Acknowledge shared transparency principle before moving to execution tests.",
      "Differentiate on county-operable implementation structures and accountability cadence.",
      "Close with Kelly's practical statewide service commitments for SOS operations.",
    ],
    sourcedFacts: [
      "michael-packo-bio-timeline.json provides the 1993-2009 Fed and post-2009 AEDI chronology.",
      "michael-packo-candidate-dossier.json records platform themes and campaign claim clusters.",
      "michael-packo-strengths-matrix.json includes communicator and policy-framing dimensions.",
      "Three-way strategy modules advise additive contrast over adversarial dismissal.",
      "ACCA planning files indicate high-probability technical and governance-oriented prompts.",
    ],
    fieldResearchNotes: [
      "Use platform depth mostly for qualification and governance-philosophy questions.",
      "Avoid debating unsourced policy specifics; route to implementation commitments.",
      "Keep one concise close tying analysis respect to administrative execution need.",
    ],
  },
};
