/**
 * Additional expected SOS questions — ACCA panel, CVSGF, VVSG, equipment, 2021 package.
 * Appended to SOS_DEBATE_QUESTION_BANK at load time.
 */
import type { SosDebateQuestionDrillDown } from "@/lib/intelligence/v4/sosDebateQuestionTypes";
import { buildSpeakOrderDrills } from "@/lib/intelligence/v4/sosDebateQuestionSpeakOrder";

function links(bills: string[], trap?: string) {
  const out = [
    { href: "/admin/intelligence/film-room", label: "Film room" },
    { href: "/admin/intelligence/trap-lanes", label: "Trap lanes" },
    { href: "/admin/intelligence/claims", label: "Claims gate" },
    ...bills.map((b) => ({ href: `/admin/intelligence/kim-hammer/bills/${b}/act-proof`, label: `${b} act proof` })),
  ];
  if (trap) out.unshift({ href: trap, label: "Trap lane" });
  return out;
}

function r(trigger: string, hammer: string, agree: string, contrast: string, bridge: string, claims?: string) {
  return { trigger, hammerLikelyLine: hammer, agree, contrast, bridge, claimsNote: claims };
}

export const SOS_DEBATE_QUESTION_BANK_ADDITIONS: SosDebateQuestionDrillDown[] = [
  {
    questionId: "cvsgf-county-funding-ledger",
    questionNumber: 24,
    category: "county-administration",
    categoryLabel: "County election administration",
    title: "County Voting System Grant Fund — who gets what, and will you publish a ledger?",
    moderatorLikelyPhrasings: [
      "How does CVSGF money reach counties?",
      "Can you show voters a county-by-county grant spreadsheet?",
      "UCC fees fund election equipment — is that money accounted for publicly?",
      "Clerks cannot find grant totals — what will you do?",
    ],
    probability: "HIGH",
    researchBasis: "ACCA panel + election funding intelligence; Act 408/HB1041 $11M + HAVA $4M verified; no public statewide ledger.",
    researchRefs: [],
    sosJobDuties: ["CVSGF grant guidelines", "County equipment support", "Transparency"],
    whyModeratorsAsk: "Clerks budget from local grant lines; voters cannot verify equitable distribution.",
    whatHammerLikelySays: [
      "We appropriated $11 million and Act 808 sent $8.24 million to counties",
      "Arkansas elections are funded and secure",
      "I stand with clerks on equipment",
    ],
    whatPackoMayAdd: [
      "Government spending lacks transparency",
      "Publish fiscal data openly",
    ],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "CVSGF and county grants",
      firstLayer:
        "Publish county-by-county CVSGF and HAVA awards — county, amount, date, purpose, fund source — plus reimbursement and equipment transfer records.",
      secondLayer:
        "Hammer cites Little Rock totals — ask for the clerk-facing spreadsheet. Pakko may agree opacity — add SOS publish plan.",
      thirdLayer:
        "Fair line: surprisingly difficult for the public to find county-by-county accounting — election transparency includes funding transparency.",
      agreePhrase: "I agree counties need modern equipment and secure systems.",
      attackPivot: "Do not accuse hiding money — accuse opacity you will fix as SOS",
    }),
    directAnswer30s:
      "I've been researching how election funding flows to counties, and it is hard for the public to find county-by-county accounting — I will publish a grant ledger as Secretary of State.",
    directAnswer60s:
      "Arkansas has a County Voting System Grant Fund — UCC fees and legislative appropriations flow through SOS grant guidelines. Verified appropriations exist — a public county-by-county award table does not. I will publish one: amount, date, purpose, equipment, fund source. Clerks deserve it; voters deserve it.",
    agreeButNeverOnlyAgree: "Agree funding exists → contrast public ledger → SOS pledge",
    rebuttalIfHammerAttacks: [
      r(
        "We funded counties",
        "Look at Act 808 and $11M",
        "I agree money was authorized in Little Rock",
        "Totals are not the same as a county ledger clerks can budget from",
        "Show the spreadsheet — I will publish one as SOS",
      ),
    ],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Accusing fraud without ledger", "Citing Garland $14,340 without primary PDF"],
    bodyLanguageAndTone: "Calm clerk-room tone — ACCA audience",
    rehearsalSteps: ["Rehearse fair public line", "Trap question on ledger"],
    relatedBills: [],
    relatedActs: ["808", "408"],
    trapLaneHref: "/admin/intelligence/trap-lanes/county-champion",
    relatedLinks: [
      { href: "/admin/intelligence/election-funding/county-ledger-gap", label: "CVSGF depth" },
      ...links([], "/admin/intelligence/trap-lanes/county-champion"),
    ],
    claimsGate: "Appropriations VERIFIED; county ledger gap VERIFIED; do not cite unverified county amounts",
    estimatedPrepMinutes: 25,
  },
  {
    questionId: "vvsg-equipment-modernization",
    questionNumber: 25,
    category: "security-cyber",
    categoryLabel: "Security & cyber",
    title: "VVSG 2.0 equipment modernization — timeline and who pays?",
    moderatorLikelyPhrasings: [
      "Voting equipment is aging — what is your replacement plan?",
      "Federal VVSG 2.0 certification takes years — how will Arkansas keep up?",
      "Will counties bear VVSG 2.0 costs alone?",
    ],
    probability: "HIGH",
    researchBasis: "EAC May 2026 VVSG 2.0 report ingested; ES&S ACCA platinum sponsor.",
    researchRefs: [],
    sosJobDuties: ["Equipment certification", "CVSGF grants", "County support"],
    whyModeratorsAsk: "Clerks face multi-year certification lead times and higher unit costs.",
    whatHammerLikelySays: ["Integrity laws modernized elections", "We funded equipment", "ES&S partnership"],
    whatPackoMayAdd: ["Question centralized procurement costs"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "VVSG 2.0 modernization",
      firstLayer:
        "Pair CVSGF planning with VVSG 2.0 lead times — SOS publishes replacement roadmap and training budget, not slogans.",
      secondLayer: "Add: integrity bills without equipment dollars are unfunded mandates.",
      thirdLayer: "National equipment aging — Arkansas needs sustained grants, not one appropriation headline.",
      agreePhrase: "I agree Arkansas needs certified modern equipment.",
      attackPivot: "Vendor room — no vendor bashing",
    }),
    directAnswer30s:
      "VVSG 2.0 certification takes years and costs more — SOS must plan grants and clerk training now, not after the next mandate.",
    directAnswer60s:
      "The EAC reports nationwide equipment is aging and VVSG 2.0 deployment depends on sustained funding. Arkansas SOS grant guidelines must plan for those lead times. I will publish a county equipment roadmap tied to CVSGF — integrity means modern equipment plus transparent grants plus clerk training.",
    agreeButNeverOnlyAgree: "Agree modernization → add funding + timeline plan",
    rebuttalIfHammerAttacks: [
      r(
        "We already funded equipment",
        "Act 808 and appropriations",
        "Authorized dollars yes",
        "Which counties have a published VVSG 2.0 replacement schedule tied to your bills?",
        "SOS publishes roadmap — senator publishes acts",
      ),
    ],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Attacking ES&S in vendor room"],
    bodyLanguageAndTone: "Professional — vendors in room at ACCA",
    rehearsalSteps: ["Read VVSG module executive summary"],
    relatedBills: ["HB1457"],
    relatedActs: ["350"],
    trapLaneHref: null,
    relatedLinks: [{ href: "/admin/intelligence/election-equipment-vvsg", label: "VVSG 2.0 education" }],
    claimsGate: "EAC report ingested — verify AR-specific inventory before county claims",
    estimatedPrepMinutes: 20,
  },
  {
    questionId: "act-350-paper-ballots",
    questionNumber: 26,
    category: "elections-integrity",
    categoryLabel: "Elections & integrity",
    title: "Act 350 and paper ballot requirements — can clerks execute?",
    moderatorLikelyPhrasings: [
      "What is your plan for Act 350 implementation?",
      "Paper ballots and audits — counties ready?",
      "Who pays for Act 350 rollout?",
    ],
    probability: "HIGH",
    researchBasis: "Hammer authorship; county implementation burden.",
    researchRefs: [],
    sosJobDuties: ["Rulemaking", "County training", "Equipment standards"],
    whyModeratorsAsk: "Tests operational readiness vs legislative authorship.",
    whatHammerLikelySays: ["Act 350 strengthens integrity", "Counties will comply", "I wrote the law"],
    whatPackoMayAdd: ["Another unfunded mandate"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "Act 350 paper ballots",
      firstLayer: "SOS publishes Act 350 playbook, training modules, and staffing plan per county — funded.",
      secondLayer: "Ask Hammer: SOS staff ratio per county for Act 350?",
      thirdLayer: "Security with procedures clerks can execute — state pays rollout help desk.",
      agreePhrase: "I agree paper trails and audits build trust when implemented well.",
      attackPivot: "Act number + clerk desk impact",
    }),
    directAnswer30s:
      "Act 350 is law — clerks need SOS training, funding, and a help desk. I will publish an implementation calendar counties can actually use.",
    directAnswer60s:
      "Paper ballots and audits can build trust — if clerks have training and dollars. Act 350 landed on county desks — SOS must fund rollout, publish plain rules, and answer calls. Writing the law is not administering seventy-five counties.",
    agreeButNeverOnlyAgree: "Agree paper trail value → implementation plan",
    rebuttalIfHammerAttacks: [r("I secured Act 350", "Integrity", "Agree goal", "Who pays per county?", "SOS help desk pledge")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Opposing Act 350 outright"],
    bodyLanguageAndTone: "Implementation focus",
    rehearsalSteps: ["HB1457/Act 350 playbook"],
    relatedBills: ["HB1457"],
    relatedActs: ["350"],
    trapLaneHref: "/admin/intelligence/trap-lanes/county-champion",
    relatedLinks: links(["HB1457"], "/admin/intelligence/trap-lanes/county-champion"),
    claimsGate: "Verify Act 350 enrolled text before stage",
    estimatedPrepMinutes: 20,
  },
  {
    questionId: "acca-clerk-panel-partnership",
    questionNumber: 27,
    category: "county-administration",
    categoryLabel: "County election administration",
    title: "ACCA panel: What is your first-90-days plan for county clerks?",
    moderatorLikelyPhrasings: [
      "You have two hours with clerks — what will you do differently day one?",
      "First ninety days — top three priorities for clerks?",
      "Why should this room trust you over Senator Hammer?",
    ],
    probability: "HIGH",
    researchBasis: "ACCA Jun 11 2026 panel Mountain View — primary audience.",
    researchRefs: [],
    sosJobDuties: ["All county support functions"],
    whyModeratorsAsk: "Operational audition for clerk endorsement credibility.",
    whatHammerLikelySays: ["Smooth transition", "Experience", "Integrity laws"],
    whatPackoMayAdd: ["Independent administrator", "Fiscal transparency"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "first 90 days for clerks",
      firstLayer: "Day 1: clerk hotline live. Week 2: training calendar published. Day 90: CVSGF county ledger draft published.",
      secondLayer: "Hammer offers laws — you offer desk. Pakko offers analysis — you offer administration.",
      thirdLayer: "Memorable: clerks save my cell — opponents leave flyers.",
      agreePhrase: "I agree this room deserves more than campaign promises.",
      attackPivot: "Partnership not performance",
    }),
    directAnswer30s:
      "Day one: clerk hotline. Publish training calendar and CVSGF ledger plan in ninety days. SOS as service desk — not another mandate.",
    directAnswer60s:
      "First ninety days: launch clerk hotline, publish training calendar tied to active acts, draft county-by-county grant ledger, and meet quorum courts that fund you. I will not add rules without an implementation memo. This room implements what Little Rock writes — I will show up.",
    agreeButNeverOnlyAgree: "Concrete 90-day deliverables",
    rebuttalIfHammerAttacks: [r("I know elections", "I wrote bills", "Respect focus", "SOS administers", "Hotline + ledger")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Cable debate tone in clerk room", "Attacking Margaret Darter's association"],
    bodyLanguageAndTone: "Professional warmth — thank ACCA president",
    rehearsalSteps: ["ACCA panel prep hub", "90s clerk-first open"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: "/admin/intelligence/county-clerk-week/acca-summer-conference/panel-format",
    relatedLinks: [{ href: "/admin/intelligence/county-clerk-week/acca-summer-conference", label: "ACCA prep hub" }],
    claimsGate: "No fake clerk endorsements",
    estimatedPrepMinutes: 30,
  },
  {
    questionId: "election-equipment-vendors",
    questionNumber: 28,
    category: "county-administration",
    categoryLabel: "County election administration",
    title: "ES&S and election vendors — SOS role in procurement and support?",
    moderatorLikelyPhrasings: [
      "ES&S sponsors this conference — is that a problem?",
      "How will you handle statewide vendor contracts?",
      "Should SOS pick vendors or counties?",
    ],
    probability: "MEDIUM",
    researchBasis: "ES&S platinum ACCA sponsor; Arkansas statewide ES&S role in research.",
    researchRefs: [],
    sosJobDuties: ["Procurement", "Certification", "Grant guidelines"],
    whyModeratorsAsk: "Vendor politics + clerk equipment pain.",
    whatHammerLikelySays: ["Proven vendor relationships", "Secure systems"],
    whatPackoMayAdd: ["Competition in procurement"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "election vendors",
      firstLayer: "Transparent procurement, clerk choice within certification standards, grant dollars tracked publicly.",
      secondLayer: "No vendor bashing in ES&S room — literacy + transparency.",
      thirdLayer: "VVSG 2.0 roadmap with open accounting.",
      agreePhrase: "I agree counties need reliable certified equipment.",
      attackPivot: "Professional tone",
    }),
    directAnswer30s:
      "SOS must run transparent procurement and publish grant dollars — clerks need support, not vendor politics on stage.",
    directAnswer60s:
      "Election vendors serve counties — SOS sets certification and grant rules fairly. I will publish procurement decisions and CVSGF spending by county. Integrity includes knowing where equipment dollars went — without attacking clerks' vendors in this room.",
    agreeButNeverOnlyAgree: "Transparency + clerk support",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["ES&S bashing at ACCA"],
    bodyLanguageAndTone: "Visit vendor floor professionally after panel",
    rehearsalSteps: [],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: [{ href: "/admin/intelligence/election-equipment-vvsg", label: "VVSG module" }],
    claimsGate: "Verify AR ES&S contract status before specifics",
    estimatedPrepMinutes: 15,
  },
  {
    questionId: "ranked-choice-election-reform",
    questionNumber: 29,
    category: "three-way-race",
    categoryLabel: "Three-way race",
    title: "Ranked choice and election reform — SOS role?",
    moderatorLikelyPhrasings: [
      "Dr. Pakko supports election reform — your view?",
      "Should Arkansas adopt ranked choice voting?",
      "How do you differ from Libertarian reform ideas?",
    ],
    probability: "MEDIUM",
    researchBasis: "Pakko campaign themes; verify exact proposal before stage.",
    researchRefs: [],
    sosJobDuties: ["Administer current law", "Rulemaking within statute"],
    whyModeratorsAsk: "Three-way differentiation; Pakko home turf.",
    whatHammerLikelySays: ["Follow current law", "No radical changes"],
    whatPackoMayAdd: [
      "Competitiveness and ranked choice",
      "Duopoly protects incumbents",
    ],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "ranked choice and reform",
      firstLayer: "SOS administers law as written — I focus on clerk-ready rules and funding today.",
      secondLayer: "Respect Pakko reform voice — contrast administrator job.",
      thirdLayer: "Clerks cannot absorb another process change without training dollars.",
      agreePhrase: "I agree voters deserve meaningful choices.",
      attackPivot: "Never attack L voters",
    }),
    directAnswer30s:
      "Reform debates belong in the legislature — SOS must administer elections clerks can run today. I will publish clear rules and fund training.",
    directAnswer60s:
      "Dr. Pakko and I both want voters heard — if the legislature changes election methods, SOS must implement with clerk training and transparent funding. My focus is administering Arkansas's elections fairly now — hotline, ledger, training calendar.",
    agreeButNeverOnlyAgree: "Respect reform → administrator focus",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Debating unverified Pakko platform details"],
    bodyLanguageAndTone: "Respectful to Pakko",
    rehearsalSteps: ["Verify pakko4ar.com before stage"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: "/admin/intelligence/debate-depth/three-way",
    relatedLinks: [{ href: "/admin/intelligence/opponents/dossiers/michael-packo", label: "Pakko dossier" }],
    claimsGate: "Verify ranked choice position on campaign site",
    estimatedPrepMinutes: 15,
  },
  {
    questionId: "ucc-fees-funding-pipeline",
    questionNumber: 30,
    category: "business-services",
    categoryLabel: "Business & commercial services",
    title: "UCC fees fund election equipment — is that connection transparent?",
    moderatorLikelyPhrasings: [
      "Business filing fees pay for voting machines — do voters know that?",
      "Should UCC revenue flows be published?",
    ],
    probability: "MEDIUM",
    researchBasis: "A.C.A. § 19-5-1247 CVSGF UCC remittance.",
    researchRefs: [],
    sosJobDuties: ["UCC administration", "CVSGF remittance"],
    whyModeratorsAsk: "Links business desk to election funding — obscure to public.",
    whatHammerLikelySays: ["Dedicated funding stream", "Secure elections funded"],
    whatPackoMayAdd: ["Dedicated fees are hidden tax"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "UCC fees and CVSGF",
      firstLayer: "Publish UCC-to-CVSGF remittance annually alongside county grant ledger.",
      secondLayer: "Business filers deserve transparency too.",
      thirdLayer: "One dashboard: fees in, grants out, by county.",
      agreePhrase: "I agree dedicated funding beats unfunded mandates.",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "UCC fees feed the County Voting System Grant Fund by statute — voters and clerks deserve a public dashboard showing fees in and grants out.",
    directAnswer60s:
      "Every UCC filing fee pipeline to CVSGF should be public — remittance totals, appropriations, and county awards in one SOS dashboard. Business filers and county clerks deserve the same sunlight.",
    agreeButNeverOnlyAgree: "Transparency dashboard pledge",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: [],
    bodyLanguageAndTone: "Plain language",
    rehearsalSteps: [],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: [{ href: "/admin/intelligence/election-funding/who-funds-cvsgf", label: "UCC statutory depth" }],
    claimsGate: "Statute VERIFIED; remittance totals NEEDS_RESEARCH",
    estimatedPrepMinutes: 12,
  },
  {
    questionId: "election-night-reporting",
    questionNumber: 31,
    category: "elections-integrity",
    categoryLabel: "Elections & integrity",
    title: "Election night reporting and canvass — SOS responsibilities?",
    moderatorLikelyPhrasings: [
      "How will you improve election night reporting?",
      "When results are slow — who is accountable?",
    ],
    probability: "MEDIUM",
    researchBasis: "Core SOS duty; 2022 AR debate patterns.",
    researchRefs: [],
    sosJobDuties: ["Canvass certification", "Results systems"],
    whyModeratorsAsk: "Public confidence on election night.",
    whatHammerLikelySays: ["Secure reporting", "Follow law"],
    whatPackoMayAdd: [],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "election night reporting",
      firstLayer: "SOS coordinates county reporting standards, publishes timelines voters understand, supports clerks under pressure.",
      secondLayer: "Add: slow results often mean clerks following new procedures without training.",
      thirdLayer: "Trust = accurate + explained delays.",
      agreePhrase: "I agree voters deserve timely accurate results.",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "Election night is clerks under pressure — SOS publishes reporting standards, supports counties, and explains delays honestly.",
    directAnswer60s:
      "When results slow down, clerks are often implementing new laws without enough training. SOS must coordinate reporting, backstop counties, and communicate with the public — not blame election workers on television.",
    agreeButNeverOnlyAgree: "Support clerks on election night",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Blaming clerks for delays"],
    bodyLanguageAndTone: "Grateful to election workers",
    rehearsalSteps: [],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK",
    estimatedPrepMinutes: 10,
  },
  {
    questionId: "voter-list-maintenance",
    questionNumber: 32,
    category: "voter-access",
    categoryLabel: "Voter access",
    title: "Voter roll maintenance — access vs list cleaning?",
    moderatorLikelyPhrasings: [
      "How do you balance accurate rolls with removing voters wrongly?",
      "List maintenance lawsuits nationally — Arkansas plan?",
    ],
    probability: "MEDIUM",
    researchBasis: "National SOS debate pattern; county clerk coordination.",
    researchRefs: [],
    sosJobDuties: ["Statewide coordination", "Rules for counties"],
    whyModeratorsAsk: "Access vs integrity tension.",
    whatHammerLikelySays: ["Clean rolls prevent fraud", "Integrity laws"],
    whatPackoMayAdd: ["Less intrusive government"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "voter list maintenance",
      firstLayer: "Accurate rolls with notice, cure process, and clerk training — no silent purges.",
      secondLayer: "Prosecute real fraud; protect lawful voters.",
      thirdLayer: "Sunlight on list maintenance procedures.",
      agreePhrase: "I agree accurate rolls matter.",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "Accurate rolls yes — with notice, cure, and clerk training. SOS publishes procedures voters can verify.",
    directAnswer60s:
      "List maintenance must be accurate and fair — voters deserve notice and a cure path. SOS coordinates counties with plain rules and training, not surprise purges. Integrity and participation together.",
    agreeButNeverOnlyAgree: "Anti-fraud + pro-participation",
    rebuttalIfHammerAttacks: [r("Fraud on rolls", "Clean lists", "Agree accuracy", "Show AR cases", "Published procedures")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["National purge rhetoric"],
    bodyLanguageAndTone: "Balanced",
    rehearsalSteps: [],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "Fraud cases — verify before cite",
    estimatedPrepMinutes: 12,
  },
  {
    questionId: "absentee-ballot-cure-process",
    questionNumber: 33,
    category: "voter-access",
    categoryLabel: "Voter access",
    title: "Absentee and mail ballots — cure process and clerk burden?",
    moderatorLikelyPhrasings: [
      "Should voters get a chance to fix ballot errors?",
      "Mail voting rules — too tight or too loose?",
    ],
    probability: "MEDIUM",
    researchBasis: "2022 AR SOS debate mail voting split; clerk implementation.",
    researchRefs: [],
    sosJobDuties: ["Rulemaking", "County guidance"],
    whyModeratorsAsk: "Access vs security live issue.",
    whatHammerLikelySays: ["Secure absentee process", "Integrity safeguards"],
    whatPackoMayAdd: ["Let voters participate"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "absentee and cure",
      firstLayer: "Cure process with clerk training; published SOS guidance; no unfunded signature rules.",
      secondLayer: "Security with participation — both.",
      thirdLayer: "Clerks should not be signature detectives without standards.",
      agreePhrase: "I agree absentee ballots must be secure.",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "Secure absentee voting with a clear cure process — SOS publishes standards so clerks are not guessing.",
    directAnswer60s:
      "Absentee voting must be secure and accessible. SOS publishes cure procedures, trains clerks, and funds implementation when the legislature tightens rules. Stop trapping lawful voters with confusion.",
    agreeButNeverOnlyAgree: "Security + cure + clerk training",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: [],
    bodyLanguageAndTone: "Calm",
    rehearsalSteps: [],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK",
    estimatedPrepMinutes: 10,
  },
  {
    questionId: "hammer-2021-package-burden",
    questionNumber: 34,
    category: "current-record",
    categoryLabel: "Current record",
    title: "The 2021 six-bill package — burden or security?",
    moderatorLikelyPhrasings: [
      "Senator Hammer passed six election bills in 2021 — net effect on counties?",
      "Was the 2021 package too much at once?",
      "Which training budget matched those bills?",
    ],
    probability: "HIGH",
    researchBasis: "2021 integrity foundation package; ACCA clerk audience.",
    researchRefs: [],
    sosJobDuties: ["Implementation support"],
    whyModeratorsAsk: "Direct Hammer record test in clerk room.",
    whatHammerLikelySays: [
      "2021 secured Arkansas after 2020",
      "Six bills were necessary",
      "Counties adapted",
    ],
    whatPackoMayAdd: ["Too many mandates at once"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "2021 six-bill package",
      firstLayer: "Security yes — six process changes in one year without county implementation memo is burden.",
      secondLayer: "Name two acts + clerk impact; ask training budget line.",
      thirdLayer: "Kelly will not add a package without funding memo.",
      agreePhrase: "I agree 2021 responded to real concerns.",
      attackPivot: "Timeline not motive",
    }),
    directAnswer30s:
      "2021 added real security steps — and six bills in one session shifted burden to counties without a visible SOS training package. I will not repeat that.",
    directAnswer60s:
      "Senator Hammer's 2021 package changed how clerks run elections — observers, equipment, petitions, timelines. Security matters — so does implementation. Which budget line funded clerk training for each act? SOS must publish an implementation calendar when the legislature passes clusters — not leave counties absorbing alone.",
    agreeButNeverOnlyAgree: "Agree security → contrast unfunded cluster",
    rebuttalIfHammerAttacks: [
      r("You attack my record", "I secured elections", "I agree goal", "Show training dollars per county", "SOS service desk"),
    ],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Six bill numbers without county frame", "Motive attacks"],
    bodyLanguageAndTone: "Record fight calm",
    rehearsalSteps: ["2021 package module", "Two act anchors"],
    relatedBills: ["SB250", "HB1457", "SB291"],
    relatedActs: [],
    trapLaneHref: "/admin/intelligence/trap-lanes/2021-vs-2025-pivot",
    relatedLinks: [
      { href: "/admin/intelligence/kim-hammer/integrity-foundation-2021", label: "2021 package" },
      ...links(["SB250", "HB1457"], "/admin/intelligence/trap-lanes/2021-vs-2025-pivot"),
    ],
    claimsGate: "Verify act numbers on Arkleg",
    estimatedPrepMinutes: 25,
  },
  {
    questionId: "sos-nonpartisan-service",
    questionNumber: 35,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Can you keep the Secretary of State's office non-partisan?",
    moderatorLikelyPhrasings: [
      "This office has become political — how will you depoliticize it?",
      "Will you treat all parties fairly on the ballot?",
      "Partisan SOS — your pledge?",
    ],
    probability: "HIGH",
    researchBasis: "Kelly pillar; 2022 AR debate role-of-office split.",
    researchRefs: [],
    sosJobDuties: ["Non-partisan certification", "Ballot access"],
    whyModeratorsAsk: "Trust question for clerks and independents.",
    whatHammerLikelySays: ["Follow law fairly", "Integrity non-partisan"],
    whatPackoMayAdd: ["Two-party duopoly politicized SOS"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "non-partisan SOS",
      firstLayer: "Balls-and-strikes administration — publish rules, certify fairly, educate public.",
      secondLayer: "Contrast legislator-as-SOS vs service desk.",
      thirdLayer: "Civic Index accountability — educate citizens.",
      agreePhrase: "I agree this office must not be a campaign headquarters.",
      attackPivot: "Values not smears",
    }),
    directAnswer30s:
      "This office is not a campaign headquarters — it certifies elections, trains clerks, and serves all parties fairly. I will keep administration non-partisan.",
    directAnswer60s:
      "Secretary of State administers law for every party and every county — not just the majority. I will publish rules, certify ballots fairly, and educate the public. Legislators debate policy; SOS implements with transparency. That is my pledge.",
    agreeButNeverOnlyAgree: "Non-partisan pledge + concrete transparency",
    rebuttalIfHammerAttacks: [r("Partisan Democrat", "I am fair", "Service not division", "Compare SOS plans", "Clerk hotline")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [],
    zingers: [],
    mistakesFirstTimersMake: ["Partisan jabs at Hammer voters"],
    bodyLanguageAndTone: "Inclusive",
    rehearsalSteps: [],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK",
    estimatedPrepMinutes: 15,
  },
];
