import type { SosDebateQuestionDrillDown } from "@/lib/intelligence/v4/sosDebateQuestionTypes";
import { buildSpeakOrderDrills } from "@/lib/intelligence/v4/sosDebateQuestionSpeakOrder";
import { KELLY_FIELD_TESTED_THEMES } from "@/lib/intelligence/v4/kellyTestedDebateThemes";

const THEME = {
  unity: KELLY_FIELD_TESTED_THEMES.find((t) => t.id === "unity-across-aisle")!,
  nonpartisan: KELLY_FIELD_TESTED_THEMES.find((t) => t.id === "nonpartisan-office")!,
  educate: KELLY_FIELD_TESTED_THEMES.find((t) => t.id === "public-education")!,
  civic: KELLY_FIELD_TESTED_THEMES.find((t) => t.id === "civic-index-accountability")!,
};

const REFS = {
  ar2022: { source: "AR PBS SOS debate 2022", url: "https://www.pbs.org/video/arkansas-pbs-debates-2022-sectretary-of-state-cx0foi/", note: "Thurston vs Gorman — baseline AR SOS forum" },
  demGaz: { source: "Arkansas Democrat-Gazette 2022 recap", url: "https://www.arkansasonline.com/news/2022/oct/19/thurston-gorman-spar-over-role-of-secretary-of/", note: "Role of office, capitol security, business delays" },
  ky: { source: "Kentucky SOS debate question bank 2024", url: "https://www.wlky.com/article/kentucky-secretary-of-state-debate-wlky/45583803", note: "National moderator question patterns" },
  ualr: { source: "UALR Public Radio 2022", url: "https://www.ualrpublicradio.org/local-regional-news/2022-10-18/arkansas-secretary-of-state-candidates-differ-on-2020-election-fairness", note: "2020 fairness split, mail voting" },
};

function links(bills: string[], trap?: string) {
  const out = [
    { href: "/admin/intelligence/film-room", label: "Film room" },
    { href: "/admin/intelligence/trap-lanes", label: "Trap lanes" },
    { href: "/admin/intelligence/claims", label: "Claims gate" },
    ...bills.map((b) => ({ href: `/admin/intelligence/kim-hammer/bills/${b}/act-proof`, label: `${b} act proof` })),
  ];
  if (trap) out.unshift({ href: trap, label: "Trap lane drill-down" });
  return out;
}

function r(trigger: string, hammer: string, agree: string, contrast: string, bridge: string, claims?: string) {
  return { trigger, hammerLikelyLine: hammer, agree, contrast, bridge, claimsNote: claims };
}

/** Full drill-down corpus — 23 expected SOS debate questions (three-way AR 2026). */
export const SOS_DEBATE_QUESTION_BANK: SosDebateQuestionDrillDown[] = [
  {
    questionId: "2020-election-fairness",
    questionNumber: 1,
    category: "elections-integrity",
    categoryLabel: "Elections & integrity",
    title: "Was the 2020 presidential election fair — and was Arkansas's count accurate?",
    moderatorLikelyPhrasings: [
      "Do you believe the 2020 election was free and fair?",
      "Can you tell voters whether you trust the 2020 outcome?",
      "Was Arkansas's 2020 election conducted securely?",
    ],
    probability: "HIGH",
    researchBasis:
      "Central split in 2022 AR SOS debate (Thurston hedged nationally; Gorman said fair). National SOS races still litigate 2020 for voter confidence framing.",
    researchRefs: [REFS.ar2022, REFS.ualr],
    sosJobDuties: ["Certify state results", "Support county canvass", "Public confidence in process"],
    whyModeratorsAsk: "Tests whether candidate fuels doubt or stabilizes trust — SOS credibility hinge.",
    whatHammerLikelySays: [
      "Arkansas's election was secure; I cannot speak for every other state.",
      "Record turnout here; we had safe elections.",
      "Integrity requires the laws I have worked on since 2021.",
    ],
    whatPackoMayAdd: ["Federal overreach fears", "Less government interference in how counties run elections"],
    whatNorrisMayHaveSaid: ["N/A — prior cycle; use as press pattern only"],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "2020 fairness",
      firstLayer:
        "Arkansas's results were certified — my focus is what the Secretary of State does next: published rules, clerk training, and a hotline when a new law lands on a Friday.",
      secondLayer:
        "Add: I will not nationalize Arkansas's story — I will answer what our clerks need for the next election, including funding when the legislature passes mandates.",
      thirdLayer:
        "Close the triangle: both opponents want integrity — neither answered who pays for implementation in Saline, Sebastian, or Phillips counties.",
      agreePhrase: "I agree Arkansas's 2020 count was certified and our clerks did their jobs under pressure.",
      attackPivot: "Question is SOS readiness, not re-litigating 2020 — I will administer the next election, not perform on cable news.",
    }),
    directAnswer30s:
      "Yes — Arkansas's election was certified and our county officials delivered. My job is the next election: clear guidance, training, and support when Little Rock changes the rules.",
    directAnswer60s:
      "Arkansas's 2020 results were certified — I trust our county election officials who did extraordinary work. Where I differ from a legislator's answer is what happens after the camera leaves: the Secretary of State should publish rules voters can read, fund clerk training, and answer the phone when a new act hits a Friday afternoon. I will not trade Arkansas's credibility for national talking points.",
    agreeButNeverOnlyAgree:
      "Agree integrity matters → add SOS implementation plan → one county example (verify before stage) → bridge to service desk.",
    rebuttalIfHammerAttacks: [
      r(
        "He says you are weak on integrity",
        "I wrote the integrity laws.",
        "We all want secure elections.",
        "Writing law is not administering 75 counties — SOS funds training and answers clerks.",
        "I will be the partner counties call, not another mandate from the Capitol.",
        "NEEDS_REVIEW — only cite acts verified night-before",
      ),
    ],
    rebuttalIfYouArePileOnTarget: [
      "Do not litigate 2020 back-and-forth — pivot to Arkansas forward and clerk support.",
      "One sentence on fairness, then county implementation.",
    ],
    sampleScripts: [
      { label: "30s — direct", duration: "30s", text: "Arkansas's 2020 election was certified. I will run the Secretary of State's office so clerks get training and voters get rules they can read — not more confusion from Little Rock." },
      { label: "60s — with contrast", duration: "60s", text: "I agree our 2020 count was accurate and our election workers were heroes. The Secretary of State's job is what happens next: when the legislature passes another election bill, counties need funding, training calendars, and a human being who answers the phone. I will not use Arkansas to score national points — I will serve Arkansas counties." },
    ],
    zingers: [],
    mistakesFirstTimersMake: [
      "Spending 45s on national 2020 instead of Arkansas forward",
      "Saying 'stolen election' or 'perfect fraud-free' without data",
      "Attacking Hammer personally instead of author vs administrator",
    ],
    bodyLanguageAndTone: "Steady eye contact with moderator; calm certitude on AR; no smirk when opponents invoke 2020.",
    rehearsalSteps: [
      "Staff plays Hammer 2020 hedge line",
      "Kelly 30s twice",
      "Add one verified county line if available",
    ],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: "/admin/intelligence/trap-lanes/experience-equals-sos-ready",
    relatedLinks: links([], "/admin/intelligence/trap-lanes/experience-equals-sos-ready"),
    claimsGate: "Do not cite national fraud statistics; Arkansas certified — VERIFIED pattern from 2022 debate press",
    estimatedPrepMinutes: 20,
  },
  {
    questionId: "integrity-vs-access",
    questionNumber: 2,
    category: "elections-integrity",
    categoryLabel: "Elections & integrity",
    title: "How do you balance election security with voter access?",
    moderatorLikelyPhrasings: [
      "Is it possible to have both security and access?",
      "Have recent laws made it too hard to vote?",
      "How do you prevent fraud without discouraging participation?",
    ],
    probability: "HIGH",
    researchBasis: "Kentucky, Georgia, Washington SOS debates all frame security vs access; AR 2022 on new integrity laws and turnout.",
    researchRefs: [REFS.ky, REFS.ar2022, REFS.ualr],
    sosJobDuties: ["Election procedures", "Voter registration", "Public guidance"],
    whyModeratorsAsk: "Defines whether candidate is perceived as suppressive or serious about participation.",
    whatHammerLikelySays: [
      "Security and integrity are not opposite — fraud prevention protects voters.",
      "2025 laws closed loopholes in petition process.",
      "You need ID to board a plane — you need ID to vote.",
    ],
    whatPackoMayAdd: ["Government should not make participation harder", "Let volunteers circulate without trap rules"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "security and access",
      firstLayer:
        "They are not opposites — prosecute fraud, publish plain-language rules, and protect lawful petition drives with training instead of fear.",
      secondLayer:
        "Add: Hammer's session passed multiple petition bills — access dies when volunteers cannot read the rules; SOS publishes guidance counties can use Monday morning.",
      thirdLayer:
        "Memorable close: integrity without participation is a false choice — I will run an office that does both.",
      agreePhrase: "I agree we must prosecute real fraud and secure ballots.",
      attackPivot: "Accusation of being soft on fraud → ask for conviction data tied to each act — research-question if not verified.",
    }),
    directAnswer30s:
      "Security and participation belong together — prosecute fraud, publish rules people can read, and stop treating lawful petition volunteers like suspects.",
    directAnswer60s:
      "I reject the false choice. Arkansas should prosecute real fraud, secure ballots, and still let lawful citizens participate — in-person, absentee, and initiative. The Secretary of State should publish plain-language guidance so clerks and volunteers are not guessing after every Friday mandate from Little Rock.",
    agreeButNeverOnlyAgree: "Agree prosecute fraud → contrast process burden → SOS training/hotline pledge.",
    rebuttalIfHammerAttacks: [
      r(
        "Chaos at the ballot",
        "We need tight petition rules.",
        "Chaos helps no one.",
        "Confusing rules are not security — they stop lawful participation.",
        "I will fund training and publish rules — that is SOS work.",
      ),
    ],
    rebuttalIfYouArePileOnTarget: ["Pivot to false choice frame; one act anchor if verified"],
    sampleScripts: [
      { label: "30s", duration: "30s", text: "Prosecute fraud. Secure ballots. And publish rules so lawful voters and petition volunteers are not trapped by confusion — that is the Secretary of State I will run." },
    ],
    zingers: [],
    mistakesFirstTimersMake: ["Sounding anti-security", "Listing seven bills in one answer"],
    bodyLanguageAndTone: "Warm on participation; firm on prosecution of real fraud — not volunteers.",
    rehearsalSteps: ["Rehearse agree line", "Practice act anchor once"],
    relatedBills: ["SB207", "SB584", "HB1222"],
    relatedActs: ["218", "768"],
    trapLaneHref: "/admin/intelligence/trap-lanes/integrity-without-participation",
    relatedLinks: links(["SB207", "SB584"], "/admin/intelligence/trap-lanes/integrity-without-participation"),
    claimsGate: "Fraud statistics require verified data — use research-question framing",
    estimatedPrepMinutes: 25,
  },
  {
    questionId: "voter-turnout-registration",
    questionNumber: 3,
    category: "voter-access",
    categoryLabel: "Voter access & turnout",
    title: "Arkansas ranks low in voter turnout and registration — what will you do as SOS?",
    moderatorLikelyPhrasings: [
      "How will you increase voter engagement?",
      "Why is turnout so low and whose fault is it?",
      "Will you prioritize registering more voters?",
    ],
    probability: "HIGH",
    researchBasis: "Gorman hammered low AR turnout in 2022; Kentucky Q1 national pattern; SOS bully-pulpit vs bookkeeping split.",
    researchRefs: [REFS.ar2022, REFS.ky, REFS.demGaz],
    sosJobDuties: ["Voter registration systems", "Public education", "County partnership"],
    whyModeratorsAsk: "Popular accountability metric; separates performative vs operational candidates.",
    whatHammerLikelySays: [
      "Integrity laws build confidence so more people participate.",
      "Online registration is a legislative issue.",
      "I will use the bully pulpit for election confidence.",
    ],
    whatPackoMayAdd: ["Remove barriers", "Government should get out of the way"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "turnout and registration",
      firstLayer:
        "Turnout rises when rules are readable — SOS will run registration outreach with clerks, not lecture counties from Little Rock.",
      secondLayer:
        "Add: I support online registration — and as SOS I will ask the legislature for tools while still serving clerks today.",
      thirdLayer:
        "Fresh close: lowest turnout is a policy failure when citizens cannot understand the rules — I will publish them.",
      agreePhrase: "I agree turnout is too low and that is a problem for democracy in Arkansas.",
      attackPivot: "If called inexperienced — pivot to listening sessions with clerks already on calendar.",
    }),
    directAnswer30s:
      "People participate when they trust the process and understand the rules — I will partner with clerks on registration drives and publish voter guidance in plain English. The Arkansas Civic Index ranks us last in civic health in this country — that is accountability on how this office has educated Arkansans.",
    directAnswer60s:
      "Turnout is too low. The Secretary of State cannot fix that with slogans — you educate the public, publish readable rules, and work across the aisle so people trust the process again. The Arkansas Civic Index puts Arkansas last — that is a report card on administration, not an excuse to blame voters. I will measure progress transparently and support clerks on day one.",
    agreeButNeverOnlyAgree:
      "Agree turnout is a crisis → add Civic Index accountability + SOS must educate + transparency across the aisle — never blame clerks alone.",
    rebuttalIfHammerAttacks: [
      r("Low turnout is your fault", "My laws protect elections", "Turnout is a shared problem", "Confusing rules suppress participation", "SOS publishes guidance and funds training"),
    ],
    rebuttalIfYouArePileOnTarget: ["No defensiveness — agree turnout low, pivot to solutions"],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Turnout rises when rules are clear and clerks are supported — I will run registration outreach with counties, not against them." }],
    zingers: [],
    mistakesFirstTimersMake: ["Blaming voters", "Promising online reg without legislative path"],
    bodyLanguageAndTone: "Optimistic, practical — county partners not victims.",
    rehearsalSteps: ["30s out loud x3"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: THEME.civic.claimsGate,
    estimatedPrepMinutes: 15,
  },
  {
    questionId: "online-voter-registration",
    questionNumber: 4,
    category: "voter-access",
    categoryLabel: "Voter access & turnout",
    title: "Do you support online voter registration?",
    moderatorLikelyPhrasings: [
      "Should Arkansas adopt online voter registration?",
      "Why hasn't Arkansas moved faster on OVR?",
    ],
    probability: "MEDIUM",
    researchBasis: "Both 2022 AR candidates supported concept; Thurston said legislative issue — classic pass-the-buck SOS answer to beat.",
    researchRefs: [REFS.ualr, REFS.ar2022],
    sosJobDuties: ["Registration systems", "Legislative liaison", "Implementation"],
    whyModeratorsAsk: "Simple yes/no with implementation follow-up.",
    whatHammerLikelySays: ["Support in principle — legislature must act", "Security safeguards first"],
    whatPackoMayAdd: ["Yes — reduce government friction"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "online registration",
      firstLayer: "Yes — and as SOS I will implement securely the day the legislature authorizes it, while improving paper pathways now.",
      secondLayer: "Add: Senator Hammer can say legislature — I will say SOS delivery timeline and clerk training.",
      thirdLayer: "Add: opponents agree yes — I add implementation calendar and county help desk.",
      agreePhrase: "Yes, I support secure online voter registration.",
      attackPivot: "N/A",
    }),
    directAnswer30s: "Yes — securely, with clerk buy-in. I will not hide behind 'the legislature' — I will publish an implementation plan counties can execute.",
    directAnswer60s:
      "Yes. Arkansas should modernize registration with security and privacy. The Secretary of State implements — I will build the clerk training and public explainer the day it passes, and until then I will fix the paper path so it is not punishing.",
    agreeButNeverOnlyAgree: "Yes + implementation ownership vs pass-the-buck.",
    rebuttalIfHammerAttacks: [r("You need legislature", "I passed election bills", "So do I", "OVR needs SOS implementation", "I administer; he authors")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Yes to online registration — with security. I will implement and train clerks, not punt to another session." }],
    zingers: [],
    mistakesFirstTimersMake: ["Only blaming legislature without yes"],
    bodyLanguageAndTone: "Forward-leaning, tech-positive but security-aware",
    rehearsalSteps: ["Beat Hammer pass-the-buck line"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "INTERPRETATION — verify legislative status",
    estimatedPrepMinutes: 10,
  },
  {
    questionId: "mail-absentee-dropboxes",
    questionNumber: 5,
    category: "voter-access",
    categoryLabel: "Voter access & turnout",
    title: "Mail voting, absentee ballots, and drop boxes — where do you stand?",
    moderatorLikelyPhrasings: [
      "Should Arkansas expand mail voting?",
      "Are drop boxes secure?",
      "How do you prevent absentee fraud?",
    ],
    probability: "HIGH",
    researchBasis: "2022 AR debate — Thurston warned fraud expansion; Gorman emphasized access. National SOS debates repeat.",
    researchRefs: [REFS.ualr, REFS.ky],
    sosJobDuties: ["Absentee procedures", "Guidance to clerks", "Security protocols"],
    whyModeratorsAsk: "Hot button — tests fraud narrative vs access.",
    whatHammerLikelySays: ["Expansion invites fraud", "Arkansas absentee process was adequate in 2020", "Tighten chain of custody"],
    whatPackoMayAdd: ["Let voters choose methods"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "mail and absentee voting",
      firstLayer: "Absentee voting is lawful — secure it with clear SOS rules and prosecute fraud, do not scare seniors away.",
      secondLayer: "Add: ask Hammer for conviction numbers tied to absentee expansion claims.",
      thirdLayer: "Add: both want security — I add senior voter story + clerk training (verify county).",
      agreePhrase: "I agree absentee voting must be secure and auditable.",
      attackPivot: "Fraud scare → Arkansas data question, not national anecdote",
    }),
    directAnswer30s:
      "Absentee voting is legal — secure the chain of custody, publish rules, and prosecute real fraud without telling seniors their vote does not count.",
    directAnswer60s:
      "Arkansans lawfully vote absentee. The Secretary of State should make procedures readable, train clerks, and prosecute fraud where it exists — not use fear to shrink participation. If my opponent claims widespread absentee fraud, show Arkansas convictions or admit it is rhetoric.",
    agreeButNeverOnlyAgree: "Secure absentee + access for lawful voters",
    rebuttalIfHammerAttacks: [r("Fraud in mail", "Expansion is dangerous", "Prosecute fraud", "Show me Arkansas convictions", "SOS guidance not slogans", "NEEDS_REVIEW")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Secure absentee voting, clear rules, prosecute real fraud — do not discourage lawful voters." }],
    zingers: [],
    mistakesFirstTimersMake: ["Dismissing absentee entirely", "National fraud stories"],
    bodyLanguageAndTone: "Protect seniors; firm on prosecution",
    rehearsalSteps: ["Fraud-data-dare practice"],
    relatedBills: ["SB487"],
    relatedActs: [],
    trapLaneHref: "/admin/intelligence/trap-lanes/fraud-data-dare",
    relatedLinks: links(["SB487"], "/admin/intelligence/trap-lanes/fraud-data-dare"),
    claimsGate: "Conviction counts — verify or research-question",
    estimatedPrepMinutes: 20,
  },
  {
    questionId: "voter-id-laws",
    questionNumber: 6,
    category: "elections-integrity",
    categoryLabel: "Elections & integrity",
    title: "Voter ID laws — support, change, or repeal?",
    moderatorLikelyPhrasings: [
      "Do you support voter ID?",
      "Is voter ID suppressive?",
    ],
    probability: "MEDIUM",
    researchBasis: "2022 recap — Gorman supported ID but worried suppression; national SOS split.",
    researchRefs: [REFS.demGaz],
    sosJobDuties: ["Election administration", "Voter education"],
    whyModeratorsAsk: "Values signal — easy trap for sound bite.",
    whatHammerLikelySays: ["Strong support for voter ID", "Common sense integrity"],
    whatPackoMayAdd: ["ID ok if free and easy"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "voter ID",
      firstLayer: "I support voter ID with free education and clerk training so implementation does not become a barrier.",
      secondLayer: "Add: ID plus readable rules — security and access.",
      thirdLayer: "Add: agree ID — fresh: SOS publishes where and how, partners with DMVs/clerks.",
      agreePhrase: "I support voter identification with implementation that respects voters.",
      attackPivot: "Soft on fraud → agree ID, pivot implementation",
    }),
    directAnswer30s: "I support voter ID — and I will make sure clerks and voters know exactly how it works before election day, not after a confused primary.",
    directAnswer60s:
      "I support voter ID as Arkansas law requires. The Secretary of State's job is implementation: training, published guidance, and making sure no voter is turned away because nobody explained the process. Security without confusion.",
    agreeButNeverOnlyAgree: "Support ID + implementation burden on SOS",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Support voter ID — with training and clear rules so it is security, not confusion." }],
    zingers: [],
    mistakesFirstTimersMake: ["Opposing ID outright in AR context"],
    bodyLanguageAndTone: "Practical, non-cultural",
    rehearsalSteps: ["Once aloud"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "Current AR law — verify statute",
    estimatedPrepMinutes: 10,
  },
  {
    questionId: "recent-election-laws-hard-or-easy",
    questionNumber: 7,
    category: "current-record",
    categoryLabel: "Current record & 2025 laws",
    title: "Have recent election integrity laws made voting too hard or not hard enough?",
    moderatorLikelyPhrasings: [
      "Senator Hammer's 2025 bills — too restrictive?",
      "Did the legislature go too far on petitions?",
    ],
    probability: "HIGH",
    researchBasis: "2022 AR debate question on new laws; 2026 Hammer record is center of race.",
    researchRefs: [REFS.ualr, REFS.ar2022],
    sosJobDuties: ["Implement laws", "Clerk support", "Guidance"],
    whyModeratorsAsk: "Direct record contrast for Hammer as SOS candidate.",
    whatHammerLikelySays: ["Laws closed loopholes", "Not hard enough nationally", "Protect constitution"],
    whatPackoMayAdd: ["Too many restrictions"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "recent election laws",
      firstLayer: "They made volunteering harder and counties poorer — SOS must fund training when legislature passes mandates.",
      secondLayer: "Add: pattern in one session — name two acts if verified, not seven.",
      thirdLayer: "Add: Hammer authors, SOS implements — I choose counties.",
      agreePhrase: "I agree election security matters.",
      attackPivot: "Record attack → author vs administrator + county burden",
    }),
    directAnswer30s:
      "They shifted burden to counties and volunteers without training money — security should not mean confusion. I will fund implementation as SOS.",
    directAnswer60s:
      "Recent bills may aim at security — but when multiple petition and county-administration acts land in one session without SOS training dollars, you get lower participation, not higher trust. I will implement with clerks, not against them.",
    agreeButNeverOnlyAgree: "Security goal + implementation critique",
    rebuttalIfHammerAttacks: [
      r("Check my record", "I led on integrity", "Welcome that record", "Show me county funding line items", "SOS administers"),
    ],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "60s record", duration: "60s", text: "Security without training is unfunded mandate theater. I will publish rules and fund clerks — that is the SOS difference." }],
    zingers: [],
    mistakesFirstTimersMake: ["Seven act numbers in 30s", "Motive attacks"],
    bodyLanguageAndTone: "Calm record fight; eyes on moderator",
    rehearsalSteps: ["Check My Record six-beat from coaching"],
    relatedBills: ["SB207", "SB584", "HB1457"],
    relatedActs: ["218", "768", "444"],
    trapLaneHref: "/admin/intelligence/trap-lanes/2021-vs-2025-pivot",
    relatedLinks: links(["SB207", "SB584"], "/admin/intelligence/trap-lanes/2021-vs-2025-pivot"),
    claimsGate: "Verify each act on Arkleg before stage",
    estimatedPrepMinutes: 30,
  },
  {
    questionId: "county-clerks-unfunded-mandates",
    questionNumber: 8,
    category: "county-administration",
    categoryLabel: "County election administration",
    title: "What will you do for county clerks and election commissioners?",
    moderatorLikelyPhrasings: [
      "County clerks say they are overwhelmed — your plan?",
      "Will you fund mandates from the state?",
      "Poll worker shortages — SOS role?",
    ],
    probability: "HIGH",
    researchBasis: "Kentucky Q3 poll workers; 2022 AR capitol vs business priority split; Kelly differentiator.",
    researchRefs: [REFS.ky, REFS.demGaz, REFS.ar2022],
    sosJobDuties: ["Support 75 counties", "Training", "Certification"],
    whyModeratorsAsk: "Clerk audience for AR SOS; credibility with rural voters.",
    whatHammerLikelySays: ["Partner with clerks", "Clerk association support", "Smooth transition"],
    whatPackoMayAdd: ["Less state paperwork"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "county clerks",
      firstLayer: "Hotline, training calendar, and funding fights in Little Rock when acts land — SOS shows up.",
      secondLayer: "Add: Hammer pledges partnership — ask which training modules existed for Act 444.",
      thirdLayer: "Add: memorable — clerks are heroes; SOS serves them.",
      agreePhrase: "I agree county election officials are the backbone of our democracy.",
      attackPivot: "No clerk endorsement → do not claim; pledge service",
    }),
    directAnswer30s:
      "I will run a Secretary of State's office clerks can call — training, funding advocacy, and plain rules when Little Rock passes another election bill.",
    directAnswer60s:
      "County clerks implement everything the legislature writes. The Secretary of State should fund training, publish guidance, and answer the phone — not blame counties when mandates arrive without dollars. I will host a training calendar and a clerk hotline starting day one.",
    agreeButNeverOnlyAgree: "Honor clerks + concrete SOS deliverables",
    rebuttalIfHammerAttacks: [r("You never ran a county", "I work with clerks", "Clerks need a champion", "I listen — he authors", "SOS service desk")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Clerks implement the law — I will fund training, publish rules, and answer their calls. That is the SOS job." }],
    zingers: [],
    mistakesFirstTimersMake: ["Fake clerk quotes", "Attacking election workers"],
    bodyLanguageAndTone: "Respectful — clerks as allies",
    rehearsalSteps: ["Road story if verified"],
    relatedBills: ["HB1457", "SB487"],
    relatedActs: ["444"],
    trapLaneHref: "/admin/intelligence/trap-lanes/county-champion",
    relatedLinks: links(["HB1457"], "/admin/intelligence/trap-lanes/county-champion"),
    claimsGate: "Clerk endorsements — do not claim without proof",
    estimatedPrepMinutes: 25,
  },
  {
    questionId: "poll-workers-shortage",
    questionNumber: 9,
    category: "county-administration",
    categoryLabel: "County election administration",
    title: "Poll worker shortages — what is your plan?",
    moderatorLikelyPhrasings: [
      "How will you recruit poll workers?",
      "Counties cannot staff precincts — help how?",
    ],
    probability: "MEDIUM",
    researchBasis: "Kentucky SOS debate explicit question; operational SOS test.",
    researchRefs: [REFS.ky],
    sosJobDuties: ["Support counties", "Public recruitment campaigns"],
    whyModeratorsAsk: "Humanize election administration; shows operational thinking.",
    whatHammerLikelySays: ["Confidence brings workers", "Integrity laws help"],
    whatPackoMayAdd: [],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "poll workers",
      firstLayer: "SOS recruits with counties — paid training, high school civics partnerships, simplify procedures.",
      secondLayer: "Add: new laws added procedures without staff — SOS reduces confusion.",
      thirdLayer: "Add: honor workers + SOS recruitment campaign.",
      agreePhrase: "I agree poll workers are heroes and we are short.",
      attackPivot: "N/A",
    }),
    directAnswer30s: "Partner with counties on recruitment, simplify procedures where law allows, and train — poll workers should not absorb unfunded mandates alone.",
    directAnswer60s:
      "Poll workers are heroes. The Secretary of State should run recruitment with counties, streamline training, and stop piling procedures without dollars when the legislature passes bills. I will launch a statewide recruitment push tied to clerk schedules.",
    agreeButNeverOnlyAgree: "Honor workers + SOS recruitment role",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Recruit with clerks, train, simplify — poll workers should not pay the price for unfunded mandates." }],
    zingers: [],
    mistakesFirstTimersMake: ["Blaming workers"],
    bodyLanguageAndTone: "Grateful tone toward workers",
    rehearsalSteps: ["30s x2"],
    relatedBills: ["SB487"],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links(["SB487"]),
    claimsGate: "INTERPRETATION — staffing claims",
    estimatedPrepMinutes: 12,
  },
  {
    questionId: "petition-initiative-process",
    questionNumber: 10,
    category: "direct-democracy",
    categoryLabel: "Direct democracy & petitions",
    title: "Ballot initiatives and petition drives — security vs citizen access?",
    moderatorLikelyPhrasings: [
      "Are petition rules too tight?",
      "How do you protect initiative process?",
      "THV11 said Hammer led charge on restrictions — response?",
    ],
    probability: "HIGH",
    researchBasis: "2026 Hammer record cluster; THV11 transcript in film room; AR 2025 session stack.",
    researchRefs: [REFS.ar2022],
    sosJobDuties: ["Petition guidance", "County coordination"],
    whyModeratorsAsk: "Direct democracy voters; Packo may align on access.",
    whatHammerLikelySays: ["Protect constitution from fraud", "2025 fixes loopholes", "Led integrity package"],
    whatPackoMayAdd: ["Let citizens petition without traps"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "petitions and initiatives",
      firstLayer: "Prosecute fraud on petitions; publish rules volunteers can read — not seven bills worth of fear.",
      secondLayer: "Add: pattern in one session — Acts 218–768 if verified; THV11 NEEDS_REVIEW.",
      thirdLayer: "Add: agree security — fresh: lawful circulators protected.",
      agreePhrase: "I agree we must stop fraudulent signatures.",
      attackPivot: "Led the charge line — verify THV11 before quoting",
    }),
    directAnswer30s:
      "Stop fraudulent signatures — and stop trapping lawful volunteers. SOS publishes plain rules and trains counties.",
    directAnswer60s:
      "Prosecute real petition fraud. Protect lawful circulators with rules they can read. When multiple acts hit in one session, volunteers stop — that is not security. I will publish guidance and partner with counties — not weaponize confusion.",
    agreeButNeverOnlyAgree: "Anti-fraud + pro-participation",
    rebuttalIfHammerAttacks: [r("Led restrictions", "I protected constitution", "Show Arkansas fraud cases", "Pattern of bills", "SOS transparency")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "60s", duration: "60s", text: "Fraud is a crime. Confusion is a choice. I will publish petition rules voters and volunteers can verify — that is Secretary of State service." }],
    zingers: [],
    mistakesFirstTimersMake: ["Dismantled democracy rhetoric", "Unverified THV11 quote"],
    bodyLanguageAndTone: "Respect initiative voters",
    rehearsalSteps: ["Film room THV11 segment review"],
    relatedBills: ["SB584", "SB207", "HB1222"],
    relatedActs: ["768", "218"],
    trapLaneHref: "/admin/intelligence/trap-lanes/integrity-without-participation",
    relatedLinks: links(["SB584"], "/admin/intelligence/trap-lanes/integrity-without-participation"),
    claimsGate: "THV11 led the charge — NEEDS_REVIEW; acts verified on Arkleg",
    estimatedPrepMinutes: 30,
  },
  {
    questionId: "business-services-backlog",
    questionNumber: 11,
    category: "business-services",
    categoryLabel: "Business & commercial services",
    title: "Business filings are delayed — how will you run the business side of SOS?",
    moderatorLikelyPhrasings: [
      "Website says filings delayed — fix how?",
      "SOS is not just elections — business services?",
      "Entrepreneurs cannot get LLCs timely — plan?",
    ],
    probability: "MEDIUM",
    researchBasis: "2022 AR debate — Gorman hit Thurston on delays; WA SOS on business costs; core SOS duty.",
    researchRefs: [REFS.demGaz, REFS.ar2022],
    sosJobDuties: ["Business filings", "UCC", "Customer service"],
    whyModeratorsAsk: "Shows breadth beyond culture-war elections.",
    whatHammerLikelySays: ["Staffing shortages everywhere", "Will improve efficiency"],
    whatPackoMayAdd: ["Cut red tape"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "business services",
      firstLayer: "Elections are visible — but SOS must run business desk: timelines, online status, staffing plan day one.",
      secondLayer: "Add: Hammer runs on election integrity — I add business customer service metrics.",
      thirdLayer: "Add: jobs and entrepreneurs need SOS too — fresh operational pledge.",
      agreePhrase: "I agree entrepreneurs deserve timely filings.",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "The Secretary of State serves job creators too — clear timelines, modern website, and accountability when filings slip.",
    directAnswer60s:
      "Elections are critical — so is the business desk. Arkansas entrepreneurs deserve predictable filing times, transparent status online, and a Secretary of State who staffs the mission. I will publish turnaround standards and fix the website clerks and businesses actually use.",
    agreeButNeverOnlyAgree: "Agree problem + SOS operations plan",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "SOS must serve businesses with clear timelines and a website that works — not excuses about staffing." }],
    zingers: [],
    mistakesFirstTimersMake: ["Only talking elections"],
    bodyLanguageAndTone: "Pro-business, competent manager",
    rehearsalSteps: ["Learn current delay language from site — verify"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "Verify current SOS website delay notice",
    estimatedPrepMinutes: 12,
  },
  {
    questionId: "capitol-security-vs-elections",
    questionNumber: 12,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Capitol security vs elections — what is your top priority?",
    moderatorLikelyPhrasings: [
      "What area of SOS needs most improvement?",
      "Capitol Police and grounds — priority?",
    ],
    probability: "MEDIUM",
    researchBasis: "Thurston said capitol security #1 in 2022; Gorman said turnout/business — classic split.",
    researchRefs: [REFS.demGaz],
    sosJobDuties: ["Capitol Police", "Elections", "Prioritization"],
    whyModeratorsAsk: "Reveals candidate theory of office.",
    whatHammerLikelySays: ["Capitol security first", "Protect the people's house"],
    whatPackoMayAdd: [],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "priorities",
      firstLayer: "Elections and county support first — capitol security matters with professional leadership, not as excuse to ignore clerks.",
      secondLayer: "Add: Thurston chose capitol — I choose clerks and business desk.",
      thirdLayer: "Add: both matter — fresh: SOS org chart with accountable leads for each.",
      agreePhrase: "I agree the Capitol must be safe.",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "Election administration and county support come first — with capitol security led by professionals, not as a distraction from clerks.",
    directAnswer60s:
      "The Capitol must be safe. So must every county election. My priority is the work only the Secretary of State does for 75 counties — training, guidance, certification — while capitol security is led by qualified professionals with clear accountability.",
    agreeButNeverOnlyAgree: "Safe capitol + elections first",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "County elections first; capitol security with pros — clerks cannot wait for another session." }],
    zingers: [],
    mistakesFirstTimersMake: ["Ignoring capitol entirely"],
    bodyLanguageAndTone: "Balanced, not dismissive of security",
    rehearsalSteps: ["Once"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK — priority framing",
    estimatedPrepMinutes: 10,
  },
  {
    questionId: "bully-pulpit-vs-bookkeeping",
    questionNumber: 13,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Is the Secretary of State a bully pulpit or a bookkeeping office?",
    moderatorLikelyPhrasings: [
      "How do you see the role of SOS?",
      "Will you use the office to advocate?",
    ],
    probability: "MEDIUM",
    researchBasis: "Barnes framed Gorman bully pulpit vs Thurston bookkeeping — 2022 AR.",
    researchRefs: [REFS.demGaz],
    sosJobDuties: ["All duties — framing"],
    whyModeratorsAsk: "Philosophy question — defines campaign narrative.",
    whatHammerLikelySays: ["Steward of records", "Integrity pulpit"],
    whatPackoMayAdd: ["Less politics"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "role philosophy",
      firstLayer: "Neither — it is a service desk for voters, clerks, and businesses with transparent rules.",
      secondLayer: "Add: bookkeeping without service is failure; pulpit without implementation is theater.",
      thirdLayer: "Add: memorable service desk line.",
      agreePhrase: "I agree the office must be nonpartisan in how ballots are administered.",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "Neither slogan — it is a non-partisan service desk: transparent elections, public education, and accountability when filings or guidance slip.",
    directAnswer60s:
      "Bookkeeping without service fails Arkansas. A partisan pulpit widens division. I will run a transparent, accountable, non-partisan Secretary of State who educates the public and works across the aisle — clerks, voters, and businesses treated fairly in all seventy-five counties.",
    agreeButNeverOnlyAgree: "Reject false binary → non-partisan service desk + educate public + unity not division",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Not bully pulpit, not bookkeeping — a service desk for clerks, voters, and businesses." }],
    zingers: [],
    mistakesFirstTimersMake: ["Culture war pulpit"],
    bodyLanguageAndTone: "Humble competence",
    rehearsalSteps: ["Service desk phrase x5"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK",
    estimatedPrepMinutes: 12,
  },
  {
    questionId: "nonpartisan-ballot-arbiter",
    questionNumber: 14,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Can the Secretary of State be a nonpartisan arbiter of ballot access?",
    moderatorLikelyPhrasings: [
      "Will personal views shade ballot access?",
      "Should SOS be nonpartisan?",
    ],
    probability: "MEDIUM",
    researchBasis: "Gorman 2022 line on nonpartisan arbiter; credibility with moderates.",
    researchRefs: [REFS.demGaz],
    sosJobDuties: ["Ballot access", "Petition certification"],
    whyModeratorsAsk: "Tests fairness commitment.",
    whatHammerLikelySays: ["Follow the law", "Not let feelings shade decisions"],
    whatPackoMayAdd: [],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "nonpartisan administration",
      firstLayer: "Yes — publish rules, post decisions, invite clerk review before changes go live.",
      secondLayer: "Add: agree with opponents — fresh transparency mechanisms.",
      thirdLayer: "Add: closing — trust is earned in public process.",
      agreePhrase: "Yes — ballot access must be administered fairly regardless of my personal views.",
      attackPivot: "Partisan attack → transparency pledge",
    }),
    directAnswer30s: THEME.nonpartisan.debateLine30s,
    directAnswer60s:
      "The Secretary of State must administer ballot access fairly and stay non-partisan — publish guidance, educate voters, and work with anyone who wants transparent rules. Trust is earned in daylight, not in division.",
    agreeButNeverOnlyAgree:
      "Yes non-partisan ballot administration → add published transparency + educate voters + work across aisle — office must unite, not divide",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: THEME.nonpartisan.debateLine30s }],
    zingers: [],
    mistakesFirstTimersMake: ["Overpromising independence from law"],
    bodyLanguageAndTone: "Institutional respect",
    rehearsalSteps: ["Once"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK",
    estimatedPrepMinutes: 10,
  },
  {
    questionId: "experience-sos-ready",
    questionNumber: 15,
    category: "experience-readiness",
    categoryLabel: "Experience & readiness",
    title: "What qualifies you to administer the Secretary of State's office?",
    moderatorLikelyPhrasings: [
      "Why you and not Senator Hammer?",
      "You have not been SOS — ready how?",
      "Check my record — your response?",
    ],
    probability: "HIGH",
    researchBasis: "Universal SOS debate theme; Hammer runoff media; Check My Record coaching.",
    researchRefs: [REFS.ar2022],
    sosJobDuties: ["Full agency administration"],
    whyModeratorsAsk: "Threshold credibility question.",
    whatHammerLikelySays: ["16 years experience", "Smooth transition", "Check my record", "Election integrity #1"],
    whatPackoMayAdd: ["Fresh outsider"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "qualifications",
      firstLayer: "I am running to administer — listen to clerks, publish rules, run business desk — not to author another unfunded mandate.",
      secondLayer: "Add: welcome record comparison — author vs administrator.",
      thirdLayer: "Add: third speaker summary — both legislators; I choose service desk.",
      agreePhrase: "I respect my opponent's years in the legislature.",
      attackPivot: "Check my record → six-beat coaching script",
    }),
    directAnswer30s:
      "Senator Hammer wrote election law. I will administer it — clerks, training, hotline, transparent business services — that is the Secretary of State job.",
    directAnswer60s:
      "Experience in the Capitol is not the same as running the Secretary of State's office. My opponent authored bills counties must implement. I will fund training, publish rules voters can read, answer clerk calls, and fix the business desk — that is the job description voters hired.",
    agreeButNeverOnlyAgree: "Respect tenure + administrator contrast",
    rebuttalIfHammerAttacks: [
      r("No experience", "I have 16 years", "Legislative experience matters", "SOS administers 75 counties", "Check my record — then check who pays for it"),
    ],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "60s Check My Record", duration: "60s", text: "Check my record — you will see bills. Check who implements them — that is the Secretary of State I will be." }],
    zingers: [],
    mistakesFirstTimersMake: ["Résumé invention", "Personal attacks"],
    bodyLanguageAndTone: "Confident welcome of comparison",
    rehearsalSteps: ["Coaching panel six-beat"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: "/admin/intelligence/trap-lanes/experience-equals-sos-ready",
    relatedLinks: links([], "/admin/intelligence/trap-lanes/experience-equals-sos-ready"),
    claimsGate: "Acts only if verified",
    estimatedPrepMinutes: 25,
  },
  {
    questionId: "cybersecurity-elections",
    questionNumber: 16,
    category: "security-cyber",
    categoryLabel: "Cybersecurity",
    title: "How confident are you in Arkansas election cybersecurity?",
    moderatorLikelyPhrasings: [
      "Can foreign actors interfere?",
      "Election system security — your plan?",
    ],
    probability: "MEDIUM",
    researchBasis: "Thurston cited federal partners 2022; WA/GA national frame.",
    researchRefs: [REFS.ar2022],
    sosJobDuties: ["Election systems", "Coordination with state IT"],
    whyModeratorsAsk: "Technical credibility; fear-based voter concern.",
    whatHammerLikelySays: ["Very confident", "Federal agents onsite", "Best in country"],
    whatPackoMayAdd: [],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "cybersecurity",
      firstLayer: "Confidence comes from tested systems AND clerk training — SOS coordinates, does not boast.",
      secondLayer: "Add: agree federal partnership — fresh county communication plan.",
      thirdLayer: "Add: humble confidence + transparent incident reporting.",
      agreePhrase: "I agree cybersecurity is essential and Arkansas has strong partners.",
      attackPivot: "Boastful claims → verify or pivot to clerk training",
    }),
    directAnswer30s:
      "I am confident when systems are tested and clerks know the playbook — SOS will coordinate transparently, not boast on TV.",
    directAnswer60s:
      "Cybersecurity requires state systems and county vigilance. I will coordinate with partners, run exercises with clerks, and communicate clearly with the public — confidence without arrogance, transparency without fear-mongering.",
    agreeButNeverOnlyAgree: "Security partners + SOS coordination role",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Tested systems, trained clerks, transparent SOS coordination — that builds real confidence." }],
    zingers: [],
    mistakesFirstTimersMake: ["Claiming best in nation without source"],
    bodyLanguageAndTone: "Serious, not alarmist",
    rehearsalSteps: ["Once"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "No unsourced superlatives",
    estimatedPrepMinutes: 12,
  },
  {
    questionId: "misinformation-role-sos",
    questionNumber: 17,
    category: "security-cyber",
    categoryLabel: "Cybersecurity & trust",
    title: "How should the Secretary of State fight election misinformation?",
    moderatorLikelyPhrasings: [
      "Conspiracy theories — SOS role?",
      "Disinformation on social media — plan?",
    ],
    probability: "MEDIUM",
    researchBasis: "Kentucky Q5-6; Washington AI/disinformation clash — growing SOS topic.",
    researchRefs: [REFS.ky],
    sosJobDuties: ["Public communication", "Voter education"],
    whyModeratorsAsk: "Post-2020 environment; tests balance free speech vs leadership.",
    whatHammerLikelySays: ["Tell the truth about integrity laws", "Confidence in Arkansas elections"],
    whatPackoMayAdd: ["Government should not censor"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "misinformation",
      firstLayer: "Publish facts, clerk testimonials, and plain rules — not surveillance state.",
      secondLayer: "Add: agree fight lies — fresh transparent fact hub on SOS site.",
      thirdLayer: "Add: oppose censorship — support sunlight.",
      agreePhrase: "I agree lies undermine elections and must be countered with facts.",
      attackPivot: "Censorship accusation → sunlight not surveillance",
    }),
    directAnswer30s:
      THEME.educate.debateLine30s,
    directAnswer60s:
      "The Secretary of State must educate the public — published facts, plain voter guides, and clerk voices voters already trust. Transparency and accountability beat conspiracy; I will not turn this office into speech police or a partisan pulpit.",
    agreeButNeverOnlyAgree:
      "Agree lies hurt democracy → add SOS educates public + transparency hub + non-partisan facts — not censorship",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Sunlight — published facts and clerk truth — not censorship." }],
    zingers: [],
    mistakesFirstTimersMake: ["Promising to police social media"],
    bodyLanguageAndTone: "Calm truth-teller",
    rehearsalSteps: ["Once"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "Avoid AI vendor claims without contract facts",
    estimatedPrepMinutes: 12,
  },
  {
    questionId: "three-way-why-kelly",
    questionNumber: 18,
    category: "three-way-race",
    categoryLabel: "Three-way race (Kelly · Hammer · Packo)",
    title: "Why should voters choose you over Hammer and the Libertarian candidate?",
    moderatorLikelyPhrasings: [
      "What separates you from your opponents?",
      "Why not Senator Hammer?",
      "Packo offers X — your reply?",
    ],
    probability: "HIGH",
    researchBasis: "2026 AR three-way; Packo scaffold in repo; anything-but-Hammer strategy internal.",
    researchRefs: [REFS.ar2022],
    sosJobDuties: ["Full SOS vision"],
    whyModeratorsAsk: "Closing differentiation — may be last word opportunity.",
    whatHammerLikelySays: ["Integrity", "Experience", "Check my record"],
    whatPackoMayAdd: ["Less government", "More ballot access", "Outsider"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "three-way choice",
      firstLayer: "Hammer wrote the rules; Packo and I agree government should not confuse citizens — I will administer with clerks and publish guidance.",
      secondLayer: "Add: respect Packo access points — contrast Hammer implementation record.",
      thirdLayer: "Add: closing — SOS service desk vs legislator resume.",
      agreePhrase: "I respect both opponents' commitment to Arkansas.",
      attackPivot: "Do not ask for Packo vote on stage — Packo-friendly lines only",
    }),
    directAnswer30s:
      "I offer transparency, accountability, and a non-partisan Secretary of State who educates the public and works across the aisle — Hammer wrote much of the code; I will administer it with clerks.",
    directAnswer60s:
      "Senator Hammer wrote much of the election code counties live under. The Libertarian nominee will speak to access. I am the candidate who will keep this office non-partisan, educate Arkansans, and bring people together instead of widening division — and the Civic Index says we are last until we change that. Compare who will show up Monday morning for counties.",
    agreeButNeverOnlyAgree:
      "Respect opponents → add unity + non-partisan educate + administrator vs author — never empty contrast",
    rebuttalIfHammerAttacks: [r("Wasted vote", "Split vote", "Arkansas deserves clear choice", "SOS administrator", "Service desk")],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "60s close", duration: "60s", text: "Compare records. Then ask who administers with counties. I am running to serve — not to perform." }],
    zingers: [],
    mistakesFirstTimersMake: ["Explicit Packo vote plea", "Attacking Packo", "Ignoring Packo"],
    bodyLanguageAndTone: "Inclusive toward Packo voters; firm on service",
    rehearsalSteps: ["Three-way coaching module"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: [
      { href: "/admin/intelligence/kelly-debate-coaching", label: "Debate coaching" },
      { href: "/admin/intelligence/opponents", label: "Opponents hub" },
    ],
    claimsGate: "Packo spelling Pakko on site — do not attack third candidate",
    estimatedPrepMinutes: 20,
  },
  {
    questionId: "consolidate-constitutional-offices",
    questionNumber: 19,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Should constitutional offices be consolidated?",
    moderatorLikelyPhrasings: [
      "Merge SOS with auditor/treasurer?",
      "Government efficiency — consolidate?",
    ],
    probability: "LOW",
    researchBasis: "2022 AR — both opposed consolidation.",
    researchRefs: [REFS.demGaz],
    sosJobDuties: ["Constitutional independence"],
    whyModeratorsAsk: "Occasional efficiency question.",
    whatHammerLikelySays: ["Oppose consolidation", "Independence matters"],
    whatPackoMayAdd: ["Maybe shrink government"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "consolidation",
      firstLayer: "Oppose — independence protects elections from being buried in a mega-agency.",
      secondLayer: "Add: agree with Hammer here — fresh: strengthen SOS service instead of merging away focus.",
      thirdLayer: "Add: independence + modernize operations.",
      agreePhrase: "I agree constitutional offices should stay independent.",
      attackPivot: "N/A",
    }),
    directAnswer30s: "I oppose consolidation — elections and business filings need a focused Secretary of State, not a buried desk in a mega-agency.",
    directAnswer60s:
      "I oppose merging these offices. Independence keeps election administration visible. I will modernize the agency instead of diluting it — better website, training, and staffing plans.",
    agreeButNeverOnlyAgree: "Agree independence + add modernization",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Keep SOS independent — modernize service, do not merge it away." }],
    zingers: [],
    mistakesFirstTimersMake: ["Long policy lecture"],
    bodyLanguageAndTone: "Brief agreement zone with Hammer ok",
    rehearsalSteps: ["Once"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK",
    estimatedPrepMinutes: 8,
  },
  {
    questionId: "federal-takeover-elections",
    questionNumber: 20,
    category: "elections-integrity",
    categoryLabel: "Elections & integrity",
    title: "Federal interference in state elections — threat or help?",
    moderatorLikelyPhrasings: [
      "Should elections be federalized?",
      "FBI and state elections — your view?",
    ],
    probability: "LOW",
    researchBasis: "4029/2022 themes; GA 2026 federal interference rhetoric.",
    researchRefs: [REFS.ar2022],
    sosJobDuties: ["State sovereignty", "Federal partnerships"],
    whyModeratorsAsk: "Federalism flashpoint.",
    whatHammerLikelySays: ["Oppose federalization", "Arkansas runs Arkansas elections"],
    whatPackoMayAdd: ["Keep feds out"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "federal role",
      firstLayer: "Arkansas runs Arkansas elections — partner with feds on security, not surrender control.",
      secondLayer: "Add: agree state control — fresh clerk partnership.",
      thirdLayer: "Add: state sovereignty + transparent federal coordination.",
      agreePhrase: "I agree Arkansas must run Arkansas elections.",
      attackPivot: "N/A",
    }),
    directAnswer30s: "Arkansas elections run in Arkansas — coordinate on security, never surrender county control to Washington theater.",
    directAnswer60s:
      "State and county officials run our elections. Federal partners can help on cybersecurity — but the Secretary of State works for Arkansas clerks, not federal headlines. I will coordinate transparently without federalizing our process.",
    agreeButNeverOnlyAgree: "State control + security partnership",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [{ label: "30s", duration: "30s", text: "Arkansas runs Arkansas elections — partner on security, not federal takeover." }],
    zingers: [],
    mistakesFirstTimersMake: ["Partisan federal bait"],
    bodyLanguageAndTone: "State pride without DC bashing excess",
    rehearsalSteps: ["Once"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: links([]),
    claimsGate: "OK",
    estimatedPrepMinutes: 8,
  },
  {
    questionId: "opening-why-running",
    questionNumber: 21,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Opening: Why are you running for Secretary of State?",
    moderatorLikelyPhrasings: ["Tell us why you are running", "Opening statement"],
    probability: "HIGH",
    researchBasis: "Standard debate bookends.",
    researchRefs: [REFS.ar2022],
    sosJobDuties: ["All"],
    whyModeratorsAsk: "Sets first impression — speak order 1 matters most here.",
    whatHammerLikelySays: ["Integrity #1", "Experience", "Smooth transition"],
    whatPackoMayAdd: ["Restore trust"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "why running",
      firstLayer:
        "I am running because Arkansas needs transparency, accountability, and a Secretary of State who works across the aisle to bring people together — not widen the division we see now.",
      secondLayer: THEME.unity.freshAddWhenSecond,
      thirdLayer: "If last: Civic Index or county story — one fresh image only, do not repeat opponents.",
      agreePhrase: "N/A",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      THEME.unity.debateLine30s,
    directAnswer60s:
      "I am running to keep this office non-partisan, educate the public, and administer fair elections with clerks — transparent, accountable, and focused on service instead of division. Arkansas finishes last on the Civic Index; that changes under my administration.",
    agreeButNeverOnlyAgree: "N/A — lead with vision",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [
      {
        label: "90s warm open (field-tested)",
        duration: "90s",
        text: "I am Kelly [use legal name on stage]. I am running for Secretary of State because Arkansas needs transparency, accountability, and leaders who work across the aisle to bring people together — not more division. I will keep this office non-partisan, educate the public, and support clerks in all seventy-five counties. Thank you.",
        deliveryNote: "Warm, no attack first 15s — unity themes tested GREAT in independent and Republican rooms",
      },
      {
        label: "90s Civic Index open",
        duration: "90s",
        text: "The Arkansas Civic Index ranks us last in civic health in America — that is accountability on this administration. I am running to educate Arkansans, administer elections fairly, and earn trust through transparency. Thank you.",
        deliveryNote: "Verify Civic Index in claims before using rank on stage",
      },
    ],
    zingers: [],
    mistakesFirstTimersMake: ["Attack in first 15s", "Stack of unverified acts"],
    bodyLanguageAndTone: "Smile; steady pace",
    rehearsalSteps: ["Record on phone", "5 repetitions"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: [{ href: "/admin/intelligence/kelly-debate-coaching", label: "Opening scripts" }],
    claimsGate: `${THEME.civic.claimsGate} · Unity lines OK`,
    estimatedPrepMinutes: 20,
  },
  {
    questionId: "civic-education-unity-accountability",
    questionNumber: 22,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Transparency, civic education, and bringing Arkansans together",
    moderatorLikelyPhrasings: [
      "How will you restore trust and reduce political division?",
      "Arkansas ranks poorly on civic engagement — what will you do?",
      "Should the SOS educate voters or only enforce election law?",
      "How do you work across the aisle?",
    ],
    probability: "HIGH",
    researchBasis:
      "Field-tested Kelly themes in independent and Republican rooms statewide; Arkansas Civic Index last-in-nation frame as administration accountability.",
    researchRefs: [REFS.demGaz, REFS.ar2022],
    sosJobDuties: ["Public education", "Election administration", "Non-partisan certification"],
    whyModeratorsAsk:
      "Voters want tone and results — moderators bridge integrity questions to trust, education, and non-partisan service.",
    whatHammerLikelySays: [
      "Integrity laws build confidence",
      "Experience and smooth transition",
      "Follow the law fairly",
    ],
    whatPackoMayAdd: ["Less government friction", "Stop dividing voters"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "unity transparency and civic education",
      firstLayer: THEME.unity.debateLine60s.slice(0, 220),
      secondLayer: THEME.unity.freshAddWhenSecond,
      thirdLayer: THEME.civic.freshAddWhenThird,
      agreePhrase: "I agree Arkansans deserve honesty about how elections are run.",
      attackPivot: "Partisan label → non-partisan transparency pledge + educate public",
    }),
    directAnswer30s: THEME.unity.debateLine30s,
    directAnswer60s: `${THEME.unity.debateLine60s} ${THEME.educate.debateLine30s}`,
    agreeButNeverOnlyAgree:
      "Agree trust matters → add transparency + accountability + cross-aisle unity + non-partisan SOS + educate public (Civic Index if verified)",
    rebuttalIfHammerAttacks: [
      r(
        "You are divisive",
        "I passed tough bills",
        "I am offering service not division",
        "SOS must educate and unite — Civic Index shows we are last when we fail to teach citizens the rules",
        "Compare who will publish guidance clerks can use Monday morning",
        THEME.civic.claimsGate,
      ),
    ],
    rebuttalIfYouArePileOnTarget: ["Stay calm — unity frame, no tribal language"],
    sampleScripts: [
      { label: "30s unity", duration: "30s", text: THEME.unity.debateLine30s },
      { label: "30s Civic Index", duration: "30s", text: THEME.civic.debateLine30s, deliveryNote: "Verify index before air" },
      { label: "60s full", duration: "60s", text: THEME.unity.debateLine60s },
    ],
    zingers: [],
    mistakesFirstTimersMake: [
      "Sounding partisan while preaching unity",
      "Citing Civic Index rank without claims verification",
      "Attacking voters who disagree",
    ],
    bodyLanguageAndTone: "Warm, inclusive — look at audience not only opponents",
    rehearsalSteps: [
      "Rehearse 30s unity line until automatic",
      "Rehearse Civic Index line after claims verify",
      "Practice position 2 fresh-add standing",
    ],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: [
      { href: "/admin/intelligence", label: "Hub narrative spine" },
      { href: "/admin/intelligence/claims", label: "Claims — Civic Index" },
    ],
    claimsGate: THEME.civic.claimsGate,
    estimatedPrepMinutes: 25,
  },
  {
    questionId: "closing-final-thought",
    questionNumber: 23,
    category: "office-role",
    categoryLabel: "Role of the office",
    title: "Closing: What should voters remember?",
    moderatorLikelyPhrasings: ["Closing statement", "Final thought for voters"],
    probability: "HIGH",
    researchBasis: "Standard; last speaker wins recall.",
    researchRefs: [REFS.ar2022],
    sosJobDuties: ["All"],
    whyModeratorsAsk: "Last impression.",
    whatHammerLikelySays: ["Integrity", "Experience"],
    whatPackoMayAdd: ["Freedom"],
    whatNorrisMayHaveSaid: [],
    speakOrderDrills: buildSpeakOrderDrills({
      topic: "closing",
      firstLayer: "Remember: SOS is service for clerks and voters — I will show up.",
      secondLayer: "If second: do not repeat — one new county image.",
      thirdLayer: "Best close slot: contrast author vs administrator in one sentence.",
      agreePhrase: "N/A",
      attackPivot: "N/A",
    }),
    directAnswer30s:
      "Remember: transparency, accountability, and a non-partisan Secretary of State who educates the public and brings Arkansans together.",
    directAnswer60s:
      "Compare our records. Ask who will keep this office non-partisan, educate citizens, and work across the aisle instead of widening division. The Civic Index says we are last — that changes with service and sunlight. I am Kelly [legal name] — thank you.",
    agreeButNeverOnlyAgree: "N/A",
    rebuttalIfHammerAttacks: [],
    rebuttalIfYouArePileOnTarget: [],
    sampleScripts: [
      {
        label: "60s close (field-tested)",
        duration: "60s",
        text: "Bring Arkansas together — transparent, accountable, non-partisan. Educate the public. Support clerks. That is the Secretary of State I ask for your vote.",
      },
    ],
    zingers: [],
    mistakesFirstTimersMake: ["New attacks in close", "Rushed thank-you"],
    bodyLanguageAndTone: "Warm, forward-looking",
    rehearsalSteps: ["Memorize close", "Eyes to camera"],
    relatedBills: [],
    relatedActs: [],
    trapLaneHref: null,
    relatedLinks: [{ href: "/admin/intelligence/kelly-debate-coaching", label: "Closing scripts" }],
    claimsGate: THEME.civic.claimsGate,
    estimatedPrepMinutes: 15,
  },
];
