import type { RebuttalScript, SampleScript, DebateZinger } from "@/lib/intelligence/v4/debatePrepDrillDownTypes";
import type { PlaybookStep } from "@/lib/intelligence/v4/debateOperatorPlaybookTypes";
import type { DebateEncounterDepth } from "@/lib/intelligence/v4/debateEncounterDepthTypes";

export type TrapLaneDrillDown = {
  laneId: string;
  laneNumber: number;
  title: string;
  summary: string;
  narrativeOverview: string;
  whatToExpectHammerToSay: string[];
  hammerTonalities: string[];
  whatModeratorMayAsk: string[];
  setupMoves: string[];
  setupTiming: string;
  baitPsychology: string;
  whenHeBitesSignals: string[];
  kellyPivotDeep: string;
  rebuttalScripts: RebuttalScript[];
  sampleScripts: SampleScript[];
  zingers: DebateZinger[];
  ifHeDoesNotBite: string[];
  mistakesFirstTimersMake: string[];
  bodyLanguageAndTone: string;
  rehearsalSteps: string[];
  relatedActs: string[];
  relatedBills: string[];
  relatedLinks?: Array<{ href: string; label: string }>;
  packoNote?: string;
  claimsGate: string;
  estimatedPrepMinutes: number;
  debateSteps: PlaybookStep[];
  whatToLookForOffensive: string[];
  whatToLookForDefensive: string[];
  whatToLookForVerify: string[];
  debateOffensiveUse: string;
  debateDefensiveUse: string;
  encounterDepth?: DebateEncounterDepth;
};
