import fs from 'node:fs';import {createReplaySnapshot,validateReplayOutcome} from '../src/historical-agent-replay.js';import {createShadowObservation,resolveShadowObservation} from '../src/live-shadow-agents.js';import {planResearchRun,advanceResearchRun} from '../src/research-orchestrator.js';import {buildAgentAlphaReport,scoreAgentObservation} from '../src/agent-alpha.js';import {synthesizeChiefStrategy} from '../src/chief-strategy.js';import {evaluateOpportunity} from '../src/opportunity-hunters.js';
const expectThrow=fn=>{let x=false;try{fn()}catch{x=true}if(!x)throw new Error('expected hostile rejection')};
const replay=createReplaySnapshot({replayId:'hostile',symbol:'TEST',cutoffAt:'2025-01-10T16:00:00Z',evidence:[{id:'future',publishedAt:'2025-01-11T00:00:00Z'},{id:'unknown'}]});if(replay.acceptedEvidence.length!==0||replay.rejectedEvidence.length!==2)throw new Error('future/unproven leakage');expectThrow(()=>validateReplayOutcome(replay,{windowStartAt:'2025-01-10T15:59:00Z',windowEndAt:'2025-01-11T00:00:00Z',realizedReturn:.1}));
const shadow=createShadowObservation({shadowId:'h1',symbol:'TEST',capturedAt:'2026-01-05T21:00:00Z',snapshotId:'snap',research:{chiefView:'FAVORABLE'},evidenceState:'AVAILABLE'});expectThrow(()=>resolveShadowObservation({...shadow,hashPayload:{...shadow.hashPayload,research:{chiefView:'UNFAVORABLE'}}},{windowStartAt:'2026-01-06T00:00:00Z',windowEndAt:'2026-01-07T00:00:00Z',realizedReturn:-.1}));
const plan=planResearchRun({eventType:'RESEARCH_REQUEST',symbol:'TEST',snapshotId:'snap',computeBudget:5});if(plan.compute.planned>5||!plan.truncated)throw new Error('compute bypass');const halt=advanceResearchRun(planResearchRun({eventType:'RESEARCH_REQUEST',symbol:'TEST',snapshotId:'snap2',computeBudget:30}),{completedStages:['truth'],evidenceState:'STALE'});if(!halt.halted)throw new Error('stale escalation');
const directors=['research-director','quant-director','opportunity-director','risk-director','learning-director'].map(id=>({directorId:id,state:'READY',view:id==='risk-director'?'BLOCKED':'FAVORABLE',missingEvidence:[]}));const chief=synthesizeChiefStrategy({symbol:'TEST',committee:{directors,riskBlocked:true},packets:[],invokedAt:'2026-01-01T00:00:00Z'});if(chief.view!=='BLOCKED'||chief.mayExecuteTrade||chief.researchAuthority)throw new Error('chief control/authority bypass');
const obs=scoreAgentObservation({agentId:'momentum',packetId:'p',direction:'BULLISH',decisionClass:'FAVORABLE',realizedReturn:.01});const report=buildAgentAlphaReport([obs]);if(report.cells[0].status!=='LOW_SAMPLE'||report.cells[0].authorityWeight!==null)throw new Error('small sample promoted');
const cheap=evaluateOpportunity('lower-price-liquid-mover',{price:3,avgDollarVolume:100000,relativeVolume:4,momentum:.2});if(!cheap||cheap.qualified)throw new Error('cheap illiquid trap qualified');
for(const f of ['agents/chief-strategy.v1.json','agents/live-shadow.v1.json','agents/historical-replay.v1.json','agents/orchestration.v1.json']){const s=fs.readFileSync(new URL('../'+f,import.meta.url),'utf8').toLowerCase();if(!s.includes('execute')&&!s.includes('execution'))throw new Error('missing execution boundary '+f)}
console.log('V2.5-17 hostile audit harness: PASS');
