import type { KimHammerBriefingDomain } from "@/lib/opposition/kimHammerBriefingTypes";

export const KIM_HAMMER_COMMAND_CENTER_HREF = "/admin/intelligence/kim-hammer";

export const KIM_HAMMER_BRIEFING_DOMAINS: KimHammerBriefingDomain[] = [
  {
    id: "domain-kh4-governance",
    layer: "KH-4",
    title: "Evidence Governance & Export",
    eyebrow: "KH-4 · Publication safety · Copilot registry",
    description:
      "Operational command layer: claim disposition, debate export, safety blockers, and read-only AI suggestion agents.",
    moduleIds: [
      "evidence-command",
      "audit-log",
      "citation-locker",
      "ai-suggestion-sandbox",
      "export-control-center",
      "narrative-state",
      "geographic-narrative-intelligence",
      "county-briefings",
      "narrative-usage-analytics",
      "public-debate-evidence",
      "debate-packet-export",
      "kh4-agent-tools",
      "ai-opposition-copilot",
      "attack-surface",
      "intel-heat-map",
      "narrative-drift-monitor",
    ],
  },
  {
    id: "domain-kh3b-retrieval",
    layer: "KH-3B",
    title: "Retrieval Task Execution",
    eyebrow: "KH-3B · Ranked evidence-gap queue",
    description: "Executable retrieval missions that close gaps before claims move toward export tiers.",
    moduleIds: ["intelligence-gaps", "research-gaps"],
  },
  {
    id: "domain-kh3-deep",
    layer: "KH-3",
    title: "Deep Research & Operational Expansion",
    eyebrow: "KH-3 · Archives · Patterns · County exposure",
    description:
      "Expanded dossier modules: writings, management capacity, narrative testing, bill graphs, and rapid response scaffolding.",
    moduleIds: [
      "writings",
      "background-deep",
      "management-capacity",
      "debate-archive",
      "response-model",
      "kh3-operational",
      "network-influence",
      "pattern-analysis",
      "vulnerability-matrix-kh3",
      "narrative-testing",
      "county-exposure",
      "modern-sos-contrast",
      "rapid-response",
      "bill-relationship-graph",
      "timeline-heatmap",
      "direct-democracy",
    ],
  },
  {
    id: "domain-kh2-debate",
    layer: "KH-2",
    title: "Contrast & Debate Intelligence",
    eyebrow: "KH-2 · Strategy · Rebuttal · Message analysis",
    description: "Debate prep, contrast framing, website/message analysis, and safer external wording guidance.",
    moduleIds: [
      "message-analysis",
      "strengths-weaknesses",
      "contrast-vs-kelly",
      "debate-profile",
      "debate-prep",
      "debate-ai-workbench",
      "rebuttal-prep",
      "claims-review",
      "website",
    ],
  },
  {
    id: "domain-kh1-profile",
    layer: "KH-1",
    title: "Public Profile Intelligence",
    eyebrow: "KH-1 · Identity · Electoral · Media",
    description: "Baseline opponent identity: biography, electoral history, media footprint, and public timeline.",
    moduleIds: [
      "profile",
      "electoral-history",
      "media-footprint",
      "public-timeline",
      "public-controversies",
    ],
  },
  {
    id: "domain-kh0-record",
    layer: "KH-0",
    title: "Election Record Intelligence",
    eyebrow: "KH-0 · Bills · Themes · Legislative timeline",
    description: "Legislative dossier foundation: bill index, theme matrices, timelines, KH-0B narrative intelligence, and drill queues.",
    moduleIds: [
      "integrity-foundation-2021",
      "county-administration-burden",
      "legislative-chronology",
      "themes",
      "timeline",
    ],
  },
];

export const KIM_HAMMER_MODULE_HREFS: Record<string, string> = {
  "evidence-command": `${KIM_HAMMER_COMMAND_CENTER_HREF}/evidence-command`,
  "audit-log": `${KIM_HAMMER_COMMAND_CENTER_HREF}/audit-log`,
  "citation-locker": `${KIM_HAMMER_COMMAND_CENTER_HREF}/citation-locker`,
  "ai-suggestion-sandbox": `${KIM_HAMMER_COMMAND_CENTER_HREF}/ai-suggestion-sandbox`,
  "export-control-center": `${KIM_HAMMER_COMMAND_CENTER_HREF}/export-control-center`,
  "narrative-state": `${KIM_HAMMER_COMMAND_CENTER_HREF}/narrative-state`,
  "geographic-narrative-intelligence": `${KIM_HAMMER_COMMAND_CENTER_HREF}/geographic-narrative-intelligence`,
  "county-briefings": `${KIM_HAMMER_COMMAND_CENTER_HREF}/county-briefings`,
  "narrative-usage-analytics": `${KIM_HAMMER_COMMAND_CENTER_HREF}/narrative-usage-analytics`,
  "public-debate-evidence": `${KIM_HAMMER_COMMAND_CENTER_HREF}/public-debate-evidence`,
  "debate-packet-export": `${KIM_HAMMER_COMMAND_CENTER_HREF}/debate-packet-export`,
  "kh4-agent-tools": `${KIM_HAMMER_COMMAND_CENTER_HREF}/kh4-agent-tools`,
  "ai-opposition-copilot": `${KIM_HAMMER_COMMAND_CENTER_HREF}/ai-opposition-copilot`,
  "attack-surface": `${KIM_HAMMER_COMMAND_CENTER_HREF}/attack-surface`,
  "intel-heat-map": `${KIM_HAMMER_COMMAND_CENTER_HREF}/intel-heat-map`,
  "narrative-drift-monitor": `${KIM_HAMMER_COMMAND_CENTER_HREF}/narrative-drift-monitor`,
  "intelligence-gaps": `${KIM_HAMMER_COMMAND_CENTER_HREF}/intelligence-gaps`,
  "research-gaps": `${KIM_HAMMER_COMMAND_CENTER_HREF}/research-gaps`,
  writings: `${KIM_HAMMER_COMMAND_CENTER_HREF}/writings`,
  "background-deep": `${KIM_HAMMER_COMMAND_CENTER_HREF}/background-deep`,
  "management-capacity": `${KIM_HAMMER_COMMAND_CENTER_HREF}/management-capacity`,
  "debate-archive": `${KIM_HAMMER_COMMAND_CENTER_HREF}/debate-archive`,
  "response-model": `${KIM_HAMMER_COMMAND_CENTER_HREF}/response-model`,
  "kh3-operational": `${KIM_HAMMER_COMMAND_CENTER_HREF}/kh3-operational`,
  "network-influence": `${KIM_HAMMER_COMMAND_CENTER_HREF}/network-influence`,
  "pattern-analysis": `${KIM_HAMMER_COMMAND_CENTER_HREF}/pattern-analysis`,
  "vulnerability-matrix-kh3": `${KIM_HAMMER_COMMAND_CENTER_HREF}/vulnerability-matrix-kh3`,
  "narrative-testing": `${KIM_HAMMER_COMMAND_CENTER_HREF}/narrative-testing`,
  "county-exposure": `${KIM_HAMMER_COMMAND_CENTER_HREF}/county-exposure`,
  "modern-sos-contrast": `${KIM_HAMMER_COMMAND_CENTER_HREF}/modern-sos-contrast`,
  "rapid-response": `${KIM_HAMMER_COMMAND_CENTER_HREF}/rapid-response`,
  "bill-relationship-graph": `${KIM_HAMMER_COMMAND_CENTER_HREF}/bill-relationship-graph`,
  "timeline-heatmap": `${KIM_HAMMER_COMMAND_CENTER_HREF}/timeline-heatmap`,
  "direct-democracy": `${KIM_HAMMER_COMMAND_CENTER_HREF}/direct-democracy`,
  "message-analysis": `${KIM_HAMMER_COMMAND_CENTER_HREF}/message-analysis`,
  "strengths-weaknesses": `${KIM_HAMMER_COMMAND_CENTER_HREF}/strengths-weaknesses`,
  "contrast-vs-kelly": `${KIM_HAMMER_COMMAND_CENTER_HREF}/contrast-vs-kelly`,
  "debate-profile": `${KIM_HAMMER_COMMAND_CENTER_HREF}/debate-profile`,
  "debate-prep": `${KIM_HAMMER_COMMAND_CENTER_HREF}/debate-prep`,
  "debate-ai-workbench": `${KIM_HAMMER_COMMAND_CENTER_HREF}/debate-ai-workbench`,
  "rebuttal-prep": `${KIM_HAMMER_COMMAND_CENTER_HREF}/rebuttal-prep`,
  "claims-review": `${KIM_HAMMER_COMMAND_CENTER_HREF}/claims-review`,
  website: `${KIM_HAMMER_COMMAND_CENTER_HREF}/website`,
  profile: `${KIM_HAMMER_COMMAND_CENTER_HREF}/profile`,
  "electoral-history": `${KIM_HAMMER_COMMAND_CENTER_HREF}/electoral-history`,
  "media-footprint": `${KIM_HAMMER_COMMAND_CENTER_HREF}/media-footprint`,
  "public-timeline": `${KIM_HAMMER_COMMAND_CENTER_HREF}/public-timeline`,
  "public-controversies": `${KIM_HAMMER_COMMAND_CENTER_HREF}/public-controversies`,
  themes: `${KIM_HAMMER_COMMAND_CENTER_HREF}/themes`,
  timeline: `${KIM_HAMMER_COMMAND_CENTER_HREF}/timeline`,
  "integrity-foundation-2021": `${KIM_HAMMER_COMMAND_CENTER_HREF}/integrity-foundation-2021`,
  "county-administration-burden": `${KIM_HAMMER_COMMAND_CENTER_HREF}/county-administration-burden`,
  "legislative-chronology": `${KIM_HAMMER_COMMAND_CENTER_HREF}/legislative-chronology`,
};

export function getKimHammerDomainForModule(moduleId: string): KimHammerBriefingDomain | undefined {
  return KIM_HAMMER_BRIEFING_DOMAINS.find((domain) => domain.moduleIds.includes(moduleId));
}

export function getKimHammerModuleHref(moduleId: string): string {
  return KIM_HAMMER_MODULE_HREFS[moduleId] ?? KIM_HAMMER_COMMAND_CENTER_HREF;
}
