export type AeacResource = {
  id: string;
  title: string;
  summary: string;
  href: string;
  kind: "law" | "agency" | "research" | "data" | "civic";
  why: string;
};

export const aeacResources: AeacResource[] = [
  {
    id: "ar-sos-elections",
    title: "Arkansas Secretary of State — Elections",
    summary: "Statewide voter information, election calendars, and official election pages.",
    href: "https://www.sos.arkansas.gov/elections",
    kind: "agency",
    why: "This is the public front door for Arkansas election administration. Start here before a national site.",
  },
  {
    id: "ar-voter-info",
    title: "Arkansas voter information",
    summary: "Registration, ID, and voter-facing explanations from the state.",
    href: "https://www.sos.arkansas.gov/elections/voter-information",
    kind: "agency",
    why: "Most “how do I vote?” questions should be answered with the current state page, not a screenshot from another year.",
  },
  {
    id: "arkleg",
    title: "Arkansas General Assembly",
    summary: "Bills, acts, and access to state law.",
    href: "https://www.arkleg.state.ar.us/",
    kind: "law",
    why: "Election findings should cite Arkansas acts and code, not a national talking point.",
  },
  {
    id: "ar-foia",
    title: "Arkansas Attorney General — FOIA",
    summary: "How public records requests work in Arkansas.",
    href: "https://arkansasag.gov/arkansas-foia/",
    kind: "law",
    why: "When someone wants a contract, a canvass sheet, or a training memo, this is the lawful path.",
  },
  {
    id: "eac",
    title: "U.S. Election Assistance Commission",
    summary: "HAVA, certified voting systems, poll-worker guides, and VVSG.",
    href: "https://www.eac.gov/",
    kind: "agency",
    why: "This is the federal home for “what does certified equipment mean?”",
  },
  {
    id: "eac-certified",
    title: "EAC certified voting systems",
    summary: "The public list of systems that completed federal testing.",
    href: "https://www.eac.gov/voting-equipment/certified-voting-systems",
    kind: "agency",
    why: "Use this list instead of repeating a vendor claim.",
  },
  {
    id: "nist-voting",
    title: "NIST voting publications",
    summary: "Technical papers on voting systems, audits, and guidelines.",
    href: "https://www.nist.gov/itl/voting",
    kind: "research",
    why: "When the Commission needs the lab-level explanation of a test or an audit method.",
  },
  {
    id: "cisa",
    title: "CISA — election security",
    summary: "Federal election-infrastructure security guidance.",
    href: "https://www.cisa.gov/topics/election-security",
    kind: "agency",
    why: "Physical and cyber guidance for the systems counties already run.",
  },
  {
    id: "doj-nvra",
    title: "Department of Justice — NVRA",
    summary: "Federal voter-registration and list-maintenance statute.",
    href: "https://www.justice.gov/crt/national-voter-registration-act-1993-nvra",
    kind: "law",
    why: "List-maintenance arguments have to survive this statute.",
  },
  {
    id: "doj-voting",
    title: "Department of Justice — Voting Section",
    summary: "Federal voting-rights enforcement and guidance.",
    href: "https://www.justice.gov/crt/voting-section",
    kind: "law",
    why: "For questions about access, language, and federal voting-rights duties.",
  },
  {
    id: "fvap",
    title: "Federal Voting Assistance Program",
    summary: "Military and overseas voting (UOCAVA).",
    href: "https://www.fvap.gov/",
    kind: "agency",
    why: "Absentee questions from soldiers and overseas Arkansans have a dedicated federal desk.",
  },
  {
    id: "census",
    title: "U.S. Census Bureau",
    summary: "Population, age, language, commuting, and disability tables.",
    href: "https://www.census.gov/",
    kind: "data",
    why: "Use this when a county’s staffing or access problem is really a people-and-distance problem.",
  },
  {
    id: "acs",
    title: "American Community Survey",
    summary: "The Census Bureau’s yearly community estimates.",
    href: "https://www.census.gov/programs-surveys/acs",
    kind: "data",
    why: "Better than guessing how many people in a county may need language help, a ride, or a daytime poll worker.",
  },
  {
    id: "census-api",
    title: "Census API documentation",
    summary: "How software can pull official Census tables.",
    href: "https://www.census.gov/data/developers/guidance/api-user-guide.html",
    kind: "data",
    why: "This site can connect a Census key when one is set. The public docs stay here either way.",
  },
  {
    id: "bls",
    title: "Bureau of Labor Statistics",
    summary: "Jobs, unemployment, and wage series.",
    href: "https://www.bls.gov/",
    kind: "data",
    why: "Election staffing and county budgets sit in a labor market. BLS is the official measure.",
  },
  {
    id: "bls-lau",
    title: "BLS Local Area Unemployment Statistics",
    summary: "County and state unemployment series.",
    href: "https://www.bls.gov/lau/",
    kind: "data",
    why: "Useful when a recommendation assumes a county can hire extra workers next month.",
  },
  {
    id: "bls-api",
    title: "BLS public API",
    summary: "Developer access to official labor series.",
    href: "https://www.bls.gov/developers/",
    kind: "data",
    why: "The same series this project can retrieve when a BLS key is configured.",
  },
  {
    id: "data-gov",
    title: "data.gov",
    summary: "The federal catalog of open government datasets.",
    href: "https://data.gov/",
    kind: "data",
    why: "A hunt desk for official tables that are not on the Census or BLS home pages.",
  },
  {
    id: "google-civic",
    title: "Google Civic Information API",
    summary: "Look up representatives and some election information by address.",
    href: "https://developers.google.com/civic-information",
    kind: "civic",
    why: "Useful for “who represents this address” lookups. It is not a substitute for the county clerk.",
  },
  {
    id: "mit-lab",
    title: "MIT Election Data + Science Lab",
    summary: "Research on how elections are run and measured.",
    href: "https://electionlab.mit.edu/",
    kind: "research",
    why: "When the Commission needs a methods paper on turnout, audits, or wait times.",
  },
  {
    id: "verified-voting",
    title: "Verified Voting",
    summary: "Independent equipment and paper-record tracking.",
    href: "https://verifiedvoting.org/",
    kind: "research",
    why: "A check on “what machine does this county use?” that is not a vendor brochure.",
  },
  {
    id: "ncsl",
    title: "National Conference of State Legislatures — elections",
    summary: "50-state bill and process summaries.",
    href: "https://www.ncsl.org/elections-and-campaigns",
    kind: "research",
    why: "To compare Arkansas to other states without pretending another state’s statute is ours.",
  },
  {
    id: "nass",
    title: "National Association of Secretaries of State",
    summary: "The association of state chief election officers.",
    href: "https://www.nass.org/",
    kind: "agency",
    why: "Peer practice among secretaries of state — still filtered through Arkansas law.",
  },
  {
    id: "ada-voting",
    title: "ADA.gov — voting",
    summary: "Federal accessibility rules for voting.",
    href: "https://www.ada.gov/topics/voting/",
    kind: "law",
    why: "Accessibility is a legal duty, not an optional courtesy.",
  },
  {
    id: "ar-counties",
    title: "Association of Arkansas Counties",
    summary: "County government association and clerk-facing resources.",
    href: "https://www.arcounties.org/",
    kind: "agency",
    why: "The people who run the 75 courthouses have their own desk. The Commission should read it.",
  },
];

export const aeacResourceKinds: { id: AeacResource["kind"]; label: string }[] = [
  { id: "agency", label: "Official desks" },
  { id: "law", label: "Law and rights" },
  { id: "data", label: "Census, labor, and open data" },
  { id: "civic", label: "Civic lookup tools" },
  { id: "research", label: "Research and methods" },
];
