/**
 * Canonical campaign video + transcript contracts (Pass 1 — file-backed).
 */

export type CampaignMediaFormat =
  | "FULL_VIDEO"
  | "SHORT"
  | "CANDIDATE_FORUM"
  | "INTERVIEW"
  | "CAMPAIGN_STORY"
  | "ISSUE_EXPLAINER"
  | "TOWN_HALL"
  | "LEADERSHIP_ADDRESS";

export type TranscriptStatus =
  | "NOT_REQUESTED"
  | "DRAFT"
  | "REVIEW_REQUIRED"
  | "APPROVED"
  | "PUBLISHED"
  | "UNAVAILABLE";

export type TranscriptSource =
  | "CREATOR_SUPPLIED"
  | "YOUTUBE_CREATOR_CAPTIONS"
  | "YOUTUBE_AUTOMATIC_CAPTIONS"
  | "AI_GENERATED"
  | "MANUAL"
  | "UNKNOWN";

export type CampaignMediaPublicationStatus =
  | "DRAFT"
  | "IN_REVIEW"
  | "APPROVED"
  | "PUBLISHED"
  | "ARCHIVED";

export type TranscriptSegment = {
  id: string;
  startSeconds?: number;
  endSeconds?: number;
  speaker?: string;
  chapter?: string;
  text: string;
};

export type CampaignTranscript = {
  status: TranscriptStatus;
  source: TranscriptSource;
  language: string;
  isAutoGenerated: boolean;
  reviewedAt?: string;
  reviewedBy?: string;
  approvedAt?: string;
  approvedBy?: string;
  lastUpdatedAt?: string;
  plainText: string;
  segments: TranscriptSegment[];
};

export type CampaignMediaRecord = {
  id: string;
  slug: string;
  provider: "YOUTUBE";
  youtubeVideoId: string;
  format: CampaignMediaFormat;
  title: string;
  shortTitle?: string;
  description: string;
  summary?: string;
  featuredQuote?: string;
  thumbnailUrl?: string;
  uploadDate?: string;
  durationIso8601?: string;
  topics: string[];
  counties?: string[];
  relatedPagePaths: string[];
  featured: boolean;
  homepageEligible: boolean;
  publicationStatus: CampaignMediaPublicationStatus;
  transcript: CampaignTranscript;
};

export const EMPTY_TRANSCRIPT: CampaignTranscript = {
  status: "NOT_REQUESTED",
  source: "UNKNOWN",
  language: "en-US",
  isAutoGenerated: false,
  plainText: "",
  segments: [],
};
