/**
 * Canonical campaign video + transcript contracts (Pass 1 + Pass 2 ingestion).
 */

export type CampaignMediaFormat =
  | "FULL_VIDEO"
  | "SHORT"
  | "CANDIDATE_FORUM"
  | "INTERVIEW"
  | "CAMPAIGN_STORY"
  | "ISSUE_EXPLAINER"
  | "TOWN_HALL"
  | "LEADERSHIP_ADDRESS";

/** Pass 2 extends Pass 1 statuses. Public rendering still requires PUBLISHED only. */
export type TranscriptStatus =
  | "NOT_REQUESTED"
  | "DISCOVERED"
  | "DOWNLOADING"
  | "DOWNLOADED"
  | "NORMALIZED"
  | "AI_GENERATED"
  | "DRAFT"
  | "REVIEW_REQUIRED"
  | "APPROVED"
  | "PUBLISHED"
  | "ARCHIVED"
  | "FAILED"
  | "UNAVAILABLE";

export type TranscriptSource =
  | "CREATOR_SUPPLIED"
  | "YOUTUBE_CREATOR_CAPTIONS"
  | "YOUTUBE_AUTOMATIC_CAPTIONS"
  | "AI_GENERATED"
  | "MANUAL"
  | "MIXED"
  | "UNKNOWN";

/** Compact source labels used in pipeline metadata (maps onto TranscriptSource). */
export type TranscriptPipelineSourceKind = "CREATOR" | "YOUTUBE_AUTO" | "AI" | "MANUAL" | "MIXED";

export type CampaignMediaPublicationStatus =
  | "DRAFT"
  | "IN_REVIEW"
  | "APPROVED"
  | "PUBLISHED"
  | "ARCHIVED";

export type TranscriptSegment = {
  id: string;
  startSeconds?: number;
  endSeconds?: number;
  speaker?: string;
  chapter?: string;
  text: string;
};

export type CampaignTranscript = {
  status: TranscriptStatus;
  source: TranscriptSource;
  language: string;
  isAutoGenerated: boolean;
  reviewedAt?: string;
  reviewedBy?: string;
  approvedAt?: string;
  approvedBy?: string;
  lastUpdatedAt?: string;
  plainText: string;
  segments: TranscriptSegment[];
};

export type CampaignMediaRecord = {
  id: string;
  slug: string;
  provider: "YOUTUBE";
  youtubeVideoId: string;
  format: CampaignMediaFormat;
  title: string;
  shortTitle?: string;
  description: string;
  summary?: string;
  featuredQuote?: string;
  thumbnailUrl?: string;
  uploadDate?: string;
  durationIso8601?: string;
  topics: string[];
  counties?: string[];
  relatedPagePaths: string[];
  featured: boolean;
  homepageEligible: boolean;
  publicationStatus: CampaignMediaPublicationStatus;
  transcript: CampaignTranscript;
};

export const EMPTY_TRANSCRIPT: CampaignTranscript = {
  status: "NOT_REQUESTED",
  source: "UNKNOWN",
  language: "en-US",
  isAutoGenerated: false,
  plainText: "",
  segments: [],
};

export function mapPipelineSourceKind(kind: TranscriptPipelineSourceKind): TranscriptSource {
  switch (kind) {
    case "CREATOR":
      return "YOUTUBE_CREATOR_CAPTIONS";
    case "YOUTUBE_AUTO":
      return "YOUTUBE_AUTOMATIC_CAPTIONS";
    case "AI":
      return "AI_GENERATED";
    case "MANUAL":
      return "MANUAL";
    case "MIXED":
      return "MIXED";
    default:
      return "UNKNOWN";
  }
}
