/**
 * Auto-generated by `npm run ingest:kellymedia` — one image per county+day “setting” for site use.
 * Wire into sections via `kellymediaWebPicks` or merge into trail pools manually.
 */
export type KellymediaWebPick = {
  id: string;
  src: string;
  alt: string;
  countyLabel?: string | null;
  recordedAt?: string | null;
};

export const kellymediaWebPicks: KellymediaWebPick[] = [];
