/**
 * Auto-generated by `npm run ingest:kellymedia` — B-roll and speech clips for “Hear Kelly”.
 * Do not edit by hand.
 */
export type KellySpeakClip = {
  id: string;
  title: string;
  /** Public URL under /public */
  src: string;
  countyLabel?: string | null;
  recordedAt?: string | null;
};

export const kellySpeakIngestClips: KellySpeakClip[] = [];
