import { kellyStill, type MediaRef } from "@/content/media/media-ref";

/** One unused campaign still per visitor page/slot that used to share the same banner. */
export const uniquePageStills = {
  aboutHero: kellyStill({
    src: "/media/campaign-photos/church-hall-constituent-conversation-20260717.png",
    scene: "talks with neighbors in a community hall",
    width: 768,
    height: 1024,
  }),
  aboutExperienceHero: kellyStill({
    src: "/media/campaign-photos/fireplace-mic-remarks-20260502.png",
    scene: "speaks to a community gathering with a microphone",
    width: 768,
    height: 1024,
  }),
  aboutPortrait: kellyStill({
    src: "/media/campaign-photos/church-sanctuary-conversation-20260511.png",
    scene: "listens during a conversation in a sanctuary setting",
    width: 768,
    height: 1024,
  }),
  journeyHero: kellyStill({
    src: "/media/campaign-photos/gravel-lot-supporter-conversation-20260509.png",
    scene: "talks with a supporter outdoors beside a campaign stop",
    width: 1024,
    height: 768,
  }),
  journeyStrip: kellyStill({
    src: "/media/campaign-photos/outdoor-fair-card-handout-20260613.png",
    scene: "hands a campaign card to a neighbor at an outdoor fair",
    width: 768,
    height: 1024,
  }),
  communityHero: kellyStill({
    src: "/media/campaign-photos/community-dinner-constituent-conversation-20260723.png",
    scene: "visits with community members at a local dinner",
    width: 768,
    height: 1024,
  }),
  whyHero: kellyStill({
    src: "/media/campaign-photos/outdoor-rally-handshake-regnat-20260328.png",
    scene: "greets a neighbor with a handshake at an outdoor rally",
    width: 768,
    height: 1024,
  }),
  speaksHero: kellyStill({
    src: "/media/campaign-photos/church-stage-shared-moment-20260322.png",
    scene: "shares a moment on stage at a community event",
    width: 768,
    height: 1024,
  }),
  speaksFeatured: kellyStill({
    src: "/media/campaign-photos/war-memorial-stadium-community-laugh-20260320.png",
    scene: "laughs with neighbors on the War Memorial Stadium concourse",
    width: 1024,
    height: 768,
    place: "Little Rock, Arkansas",
  }),
  campaignPhotosIntro: kellyStill({
    src: "/media/campaign-photos/parade-campaign-fans-outreach-20260718.png",
    scene: "walks a parade route with campaign fans",
    width: 768,
    height: 1024,
  }),
  roadHero: kellyStill({
    src: "/media/campaign-photos/parking-lot-community-conversation-20260328.png",
    scene: "talks with neighbors at a community stop",
    width: 768,
    height: 1024,
  }),
  pressHero: kellyStill({
    src: "/media/campaign-photos/campaign-hq-supporter-conversation-20260711.png",
    scene: "talks with supporters inside a campaign office",
    width: 1024,
    height: 768,
  }),
  eventsHero: kellyStill({
    src: "/media/campaign-photos/stone-building-outdoor-gathering-20260620.png",
    scene: "stands with neighbors at an outdoor gathering",
    width: 1024,
    height: 768,
  }),
  eventsRequestHero: kellyStill({
    src: "/media/campaign-photos/home-wine-tasting-conversation-20260329.png",
    scene: "visits with hosts at a living-room gathering",
    width: 768,
    height: 1024,
  }),
  scheduleHero: kellyStill({
    src: "/media/campaign-photos/bates-event-conversation-20260626.png",
    scene: "talks with attendees at a community event",
    width: 768,
    height: 1024,
  }),
  listeningHero: kellyStill({
    src: "/media/campaign-photos/vfw-hall-voter-conversation-20260725.png",
    scene: "listens to a community member at a hall gathering",
    width: 768,
    height: 1024,
  }),
  arkansasHero: kellyStill({
    src: "/media/campaign-photos/stone-building-handshake-steps-20260620.png",
    scene: "shakes hands on the steps of a stone civic building",
    width: 768,
    height: 1024,
  }),
  getInvolvedHero: kellyStill({
    src: "/media/campaign-photos/people-over-politics-supporter-selfie-20260725.png",
    scene: "stands with supporters in People Over Politics shirts",
    width: 1024,
    height: 473,
    objectPosition: "50% 40%",
  }),
  donateHero: kellyStill({
    src: "/media/campaign-photos/festival-booth-supporter-selfie-20260619.png",
    scene: "poses with supporters at a festival campaign booth",
    width: 1024,
    height: 768,
  }),
  contactHero: kellyStill({
    src: "/media/campaign-photos/community-room-sos-shirt-conversation-20260613.png",
    scene: "talks with neighbors in a community room",
    width: 768,
    height: 1024,
  }),
  voterRegHero: kellyStill({
    src: "/media/campaign-photos/porch-door-knock-approach-20260301.png",
    scene: "approaches a neighbor on a porch during voter outreach",
    width: 1024,
    height: 768,
  }),
  hostGatheringHero: kellyStill({
    src: "/media/campaign-photos/community-meal-table-conversation-20260712.png",
    scene: "visits at a community meal table",
    width: 768,
    height: 1024,
  }),
  localTeamHero: kellyStill({
    src: "/media/campaign-photos/brewery-usw-handshake-20260426.png",
    scene: "shakes hands with a union supporter at a meet-and-greet",
    width: 1024,
    height: 768,
  }),
  officeHubHero: kellyStill({
    src: "/media/campaign-photos/good-things-grow-crowd-conversation-20260613.png",
    scene: "talks with a crowd at a Good Things Grow gathering",
    width: 768,
    height: 1024,
  }),
  ddHubHero: kellyStill({
    src: "/media/campaign-photos/brewery-crowd-conversation-20260426.png",
    scene: "talks with a crowd at a community meet-and-greet",
    width: 768,
    height: 1024,
  }),
  whatWeBelieveStill: kellyStill({
    src: "/media/campaign-photos/supporter-group-selfie-20260315.png",
    scene: "stands with supporters for a group photo",
    width: 1024,
    height: 473,
    objectPosition: "50% 40%",
  }),
  homeHeroPortrait: kellyStill({
    src: "/media/campaign-photos/stone-porch-door-conversation-20260301.png",
    scene: "talks with a neighbor at a stone porch doorway",
    width: 768,
    height: 1024,
  }),
  homePersonalityPrimary: kellyStill({
    src: "/media/campaign-photos/restaurant-community-meal-selfie-20260717.png",
    scene: "sits with community members at a local meal",
    width: 1024,
    height: 473,
    objectPosition: "50% 40%",
  }),
  homePersonalitySecondary: kellyStill({
    src: "/media/campaign-photos/good-things-grow-tomato-table-20260613.png",
    scene: "visits a community table at a Good Things Grow event",
    width: 768,
    height: 1024,
  }),
  homeExecutiveLeadership: kellyStill({
    src: "/media/campaign-photos/pavilion-picnic-table-conversation-20260410.png",
    scene: "talks with neighbors at a pavilion picnic table",
    width: 768,
    height: 1024,
  }),
  homeVolunteerCallout: kellyStill({
    src: "/media/campaign-photos/toad-suck-daze-tent-first-responders-20260501.png",
    scene: "visits with first responders under a festival tent",
    width: 768,
    height: 1024,
    place: "Toad Suck Daze, Arkansas",
  }),
  homeOfficeServices: kellyStill({
    src: "/media/campaign-photos/county-clerk-tomato-table-20260613.png",
    scene: "visits with a county clerk at a community table",
    width: 1024,
    height: 768,
  }),
  homeClosing: kellyStill({
    src: "/media/campaign-photos/war-memorial-stadium-concourse-20260320.png",
    scene: "walks the War Memorial Stadium concourse with neighbors",
    width: 768,
    height: 1024,
    place: "Little Rock, Arkansas",
  }),
  resourcesHero: kellyStill({
    src: "/media/campaign-photos/hallway-tracksuit-conversation-20260301.png",
    scene: "talks with a neighbor in a community hallway",
    width: 768,
    height: 1024,
  }),
  editorialLocalPower: kellyStill({
    src: "/media/campaign-photos/toad-suck-daze-pafford-ems-20260501.png",
    scene: "visits with first responders at a community festival",
    width: 1024,
    height: 768,
    place: "Toad Suck Daze, Arkansas",
  }),
} as const satisfies Record<string, MediaRef>;
