import type { CampaignOrchestrationRoleId, CampaignRoleDefinition } from "./role-copilot-types";

const NO_SEND = ["auto_send_email", "auto_send_sms", "contact_export"];
const NO_FINANCE = ["finance_post", "reimbursement_submit"];
const NO_PROD = ["production_mutation_without_approval"];

function role(input: CampaignRoleDefinition): CampaignRoleDefinition {
  return input;
}

export const CAMPAIGN_ROLE_REGISTRY: CampaignRoleDefinition[] = [
  role({
    id: "campaign_manager",
    label: "Campaign Manager",
    mission: "Hold the full campaign map, clear blockers, delegate packets, and keep human gates honest.",
    dailyResponsibilities: ["Review top moves", "Triage blockers", "Assign cross-domain packets", "Record outcome feedback"],
    ownedDomains: ["campaign_management", "approvals", "dashboard_ux"],
    relatedSections: ["executive_command", "memory_observations", "tool_builder", "deployment_readiness"],
    primaryTools: ["campaign-state-loader", "orchestration-reasoning-engine", "cross-domain-agent-orchestrator"],
    secondaryTools: ["feedback-learning-engine", "campaign-manager-daily-command-playbook"],
    requiredInputs: ["CampaignState", "sourceHealth", "feedbackLoop", "crossDomainOrchestration"],
    outputsProduced: ["daily priorities", "review packets", "delegation decisions", "feedback records"],
    decisionsPrepared: ["which section needs attention", "which packet humans should review first"],
    humanApprovalBoundaries: ["No production mutation without review", "No sensitive memory auto-approval"],
    restrictedActions: NO_PROD,
    trainingNeeds: ["orch-101-campaign-brain", "orch-201-feedback-loop", "orch-301-cross-domain-packets"],
    whatThisRoleTeachesCampaignState: "Teaches the campaign map which recommendations humans actually acted on and where blockers repeat.",
  }),
  role({
    id: "candidate",
    label: "Candidate",
    mission: "Prepare Kelly with concise briefings, schedule context, and safe approval asks.",
    dailyResponsibilities: ["Review briefing", "Approve/hold candidate decisions", "Flag questions", "Capture what felt off"],
    ownedDomains: ["candidate", "calendar", "communications"],
    relatedSections: ["ask_kelly", "scheduling", "events_calendar"],
    primaryTools: ["candidate-copilot-briefing", "candidate-daily-briefing-orchestrator"],
    secondaryTools: ["campaign-knowledge-state", "event-intelligence-playbook"],
    requiredInputs: ["candidateReadiness", "calendarEventPressure", "knowledge"],
    outputsProduced: ["candidate briefing", "approval notes", "candidate questions"],
    decisionsPrepared: ["approve/hold event", "request briefing correction"],
    humanApprovalBoundaries: ["Candidate approves only human-facing decisions", "No mass comms send from briefing"],
    restrictedActions: NO_SEND,
    trainingNeeds: ["orch-101-campaign-brain", "candidate-briefing-safety"],
    whatThisRoleTeachesCampaignState: "Candidate reactions reveal which briefings, events, and messages are actually useful.",
  }),
  role({
    id: "communications_director",
    label: "Communications Director",
    mission: "Turn campaign truth into safe message plans while keeping send gates human-owned.",
    dailyResponsibilities: ["Review comms readiness", "Prepare message packets", "Check ECC gates", "Capture message outcomes"],
    ownedDomains: ["communications", "social_media"],
    relatedSections: ["communications", "email_os_ecc", "content_media", "public_site"],
    primaryTools: ["communications-intelligence-engine", "email-os-readiness-checker", "message-sequence-planner"],
    secondaryTools: ["comms-to-field-mobilization-playbook", "content-recap-builder"],
    requiredInputs: ["communicationsHealth", "commsReadiness", "emailEccReadiness"],
    outputsProduced: ["message prep", "audience notes", "approval checklist", "post-comms lesson"],
    decisionsPrepared: ["which message needs approval", "which audience needs follow-up"],
    humanApprovalBoundaries: ["Human must approve sends", "ECC gates before any email operation"],
    restrictedActions: NO_SEND,
    trainingNeeds: ["orch-105-comms-gates", "ecc-human-approval"],
    whatThisRoleTeachesCampaignState: "Teaches which messages create turnout, volunteer action, or fatigue risk.",
  }),
  role({
    id: "field_director",
    label: "Field Director",
    mission: "Use county intelligence to choose field priorities and route volunteer work.",
    dailyResponsibilities: ["Review weak counties", "Prepare visit packets", "Coordinate county leads", "Log field blockers"],
    ownedDomains: ["field", "county", "volunteer"],
    relatedSections: ["county_intelligence", "volunteer_field", "events_calendar"],
    primaryTools: ["county-intelligence-bridge", "field-priority-orchestrator", "county-activation-playbook"],
    secondaryTools: ["campaign-observation-intake", "county-memory-enricher"],
    requiredInputs: ["countyHealth", "countyIntelligenceSummary", "volunteerHealth"],
    outputsProduced: ["field priority plan", "county packet", "field observations"],
    decisionsPrepared: ["where to deploy field attention", "which county needs follow-up"],
    humanApprovalBoundaries: ["No voter export", "Memory enrichment requires approval"],
    restrictedActions: ["voter_export", "contact_export", "sensitive_memory_auto_store"],
    trainingNeeds: ["orch-103-weak-county", "power-of-five-safety"],
    whatThisRoleTeachesCampaignState: "Teaches whether county recommendations produce real field momentum.",
  }),
  role({
    id: "volunteer_coordinator",
    label: "Volunteer Coordinator",
    mission: "Staff priority work and capture whether volunteer asks translated into action.",
    dailyResponsibilities: ["Review open volunteer needs", "Prepare assignments", "Coordinate follow-up", "Log no-show patterns"],
    ownedDomains: ["volunteer", "field"],
    relatedSections: ["volunteer_field", "communications", "events_calendar"],
    primaryTools: ["volunteer-system", "volunteer-workload-balancer", "comms-to-field-mobilization-playbook"],
    secondaryTools: ["event-intelligence-playbook", "feedback-learning-engine"],
    requiredInputs: ["volunteerHealth", "volunteerActions", "calendarEventPressure"],
    outputsProduced: ["assignment plan", "volunteer follow-up prep", "workflow outcome notes"],
    decisionsPrepared: ["which event needs staffing", "which volunteer segment needs follow-up"],
    humanApprovalBoundaries: ["Human confirms assignments", "No contact exports"],
    restrictedActions: ["contact_export", "auto_send_sms", "voter_export"],
    trainingNeeds: ["orch-104-volunteer-push", "volunteer-data-safety"],
    whatThisRoleTeachesCampaignState: "Teaches which volunteer recommendations become staffed events or stalled workflows.",
  }),
  role({
    id: "finance_director",
    label: "Finance Director",
    mission: "Prepare finance and reimbursement review packets without posting transactions.",
    dailyResponsibilities: ["Review finance warnings", "Prepare reimbursement checks", "Escalate missing docs", "Capture finance blockers"],
    ownedDomains: ["finance", "reimbursement", "travel"],
    relatedSections: ["finance_reimbursement", "compliance", "scheduling"],
    primaryTools: ["finance-event-fusion", "reimbursement-packet-builder", "compliance-safe-operations-playbook"],
    secondaryTools: ["travel-ledger-review", "receipt-gap-detector"],
    requiredInputs: ["financeHealth", "reimbursementReadiness", "financeComplianceWarnings"],
    outputsProduced: ["finance review checklist", "reimbursement packet", "documentation gaps"],
    decisionsPrepared: ["what must be reviewed before close", "which packet is blocked"],
    humanApprovalBoundaries: ["Treasurer review required", "No finance post or reimbursement submit"],
    restrictedActions: NO_FINANCE,
    trainingNeeds: ["orch-102-close-month", "finance-human-gates"],
    whatThisRoleTeachesCampaignState: "Teaches which operational costs and documents block safe campaign execution.",
  }),
  role({
    id: "compliance_lead",
    label: "Compliance Lead",
    mission: "Keep filing, evidence, and compliance risk visible before any operational step becomes unsafe.",
    dailyResponsibilities: ["Review compliance readiness", "Check receipt gaps", "Flag risk", "Approve evidence review only"],
    ownedDomains: ["compliance", "approvals"],
    relatedSections: ["compliance", "finance_reimbursement", "deployment_readiness"],
    primaryTools: ["compliance-readiness-checker", "receipt-gap-detector", "compliance-safe-operations-playbook"],
    secondaryTools: ["orchestration-human-gate-enforcer"],
    requiredInputs: ["complianceReadiness", "financeComplianceWarnings", "sourceHealth"],
    outputsProduced: ["risk checklist", "evidence request", "human approval boundary notes"],
    decisionsPrepared: ["what requires compliance review", "which packet cannot proceed"],
    humanApprovalBoundaries: ["Human compliance review required", "No filing certification by AI"],
    restrictedActions: ["finance_post", "reimbursement_submit", "production_mutation_without_approval"],
    trainingNeeds: ["compliance-evidence-review", "orch-105-human-gates"],
    whatThisRoleTeachesCampaignState: "Teaches which actions remain unsafe until evidence exists.",
  }),
  role({
    id: "scheduler",
    label: "Scheduler",
    mission: "Coordinate candidate time, travel, event readiness, and calendar truth.",
    dailyResponsibilities: ["Review calendar pressure", "Check travel dependencies", "Prepare schedule packets", "Flag stale sync"],
    ownedDomains: ["calendar", "travel", "candidate"],
    relatedSections: ["scheduling", "events_calendar", "finance_reimbursement"],
    primaryTools: ["calendar-sync-health", "travel-ledger-review", "event-intelligence-playbook"],
    secondaryTools: ["candidate-briefing"],
    requiredInputs: ["calendarEventPressure", "candidateReadiness", "eventReadiness"],
    outputsProduced: ["schedule review packet", "travel dependency list", "calendar risk note"],
    decisionsPrepared: ["which schedule item needs approval", "which event/travel item is blocked"],
    humanApprovalBoundaries: ["No Google Calendar write without explicit human action"],
    restrictedActions: ["google_calendar_write"],
    trainingNeeds: ["calendar-truth-101", "travel-ledger-review"],
    whatThisRoleTeachesCampaignState: "Teaches whether calendar truth is blocking events, travel, or candidate readiness.",
  }),
  role({
    id: "county_lead",
    label: "County Lead",
    mission: "Represent local county truth and feed grounded county observations back into the campaign map.",
    dailyResponsibilities: ["Review county priorities", "Suggest local actions", "Capture county notes", "Escalate local blockers"],
    ownedDomains: ["county", "field"],
    relatedSections: ["county_intelligence", "events_calendar", "memory_observations"],
    primaryTools: ["county-intelligence-bridge", "county-action-package-builder"],
    secondaryTools: ["campaign-observation-intake"],
    requiredInputs: ["countyHealth", "countyIntelligenceSummary"],
    outputsProduced: ["county notes", "local event suggestions", "Power of 5 gaps"],
    decisionsPrepared: ["what the county needs next", "which local blocker repeats"],
    humanApprovalBoundaries: ["No voter/contact export", "County memory promotion requires review"],
    restrictedActions: ["voter_export", "contact_export", "sensitive_memory_auto_store"],
    trainingNeeds: ["orch-103-weak-county", "county-memory-approval"],
    whatThisRoleTeachesCampaignState: "Teaches local reality that statewide summaries miss.",
  }),
  role({
    id: "digital_director",
    label: "Digital Director",
    mission: "Coordinate public site, social, and digital readiness without unsafe publishing.",
    dailyResponsibilities: ["Review digital content gaps", "Check deployment readiness", "Prepare publish packets", "Log content outcomes"],
    ownedDomains: ["social_media", "communications", "dashboard_ux"],
    relatedSections: ["content_media", "public_site", "deployment_readiness"],
    primaryTools: ["content-recap-builder", "public-route-health-check", "deployment-readiness-playbook"],
    secondaryTools: ["communications-intelligence-engine"],
    requiredInputs: ["communicationActions", "dashboardHealth", "sourceHealth"],
    outputsProduced: ["digital readiness packet", "content gap list", "publish review checklist"],
    decisionsPrepared: ["what can be published after approval", "what route/content needs repair"],
    humanApprovalBoundaries: ["No production mutation or public publish by AI"],
    restrictedActions: NO_PROD,
    trainingNeeds: ["digital-publish-safety", "deployment-readiness-review"],
    whatThisRoleTeachesCampaignState: "Teaches whether public narrative and operator readiness match campaign truth.",
  }),
  role({
    id: "research_director",
    label: "Research Director",
    mission: "Turn questions, issues, and knowledge gaps into sourced strategic context.",
    dailyResponsibilities: ["Review knowledge gaps", "Validate claims", "Prepare sourced notes", "Flag strategy risk"],
    ownedDomains: ["campaign_management", "candidate", "communications"],
    relatedSections: ["research_strategy", "ask_kelly", "memory_observations"],
    primaryTools: ["campaign-lessons-engine", "knowledge-gap-detector", "campaign-knowledge-state"],
    secondaryTools: ["orchestration-observation-miner"],
    requiredInputs: ["knowledge", "activeOpportunities", "topRisks"],
    outputsProduced: ["sourced strategy notes", "knowledge gap prompts", "risk warnings"],
    decisionsPrepared: ["what needs evidence", "which lesson should be approved or rejected"],
    humanApprovalBoundaries: ["No unsourced opponent claims", "Strategic memory requires approval"],
    restrictedActions: ["sensitive_memory_auto_store", "production_mutation_without_approval"],
    trainingNeeds: ["knowledge-gap-review", "strategic-memory-approval"],
    whatThisRoleTeachesCampaignState: "Teaches the AI what it does not know and which strategic claims are supported.",
  }),
  role({
    id: "data_director",
    label: "Data Director",
    mission: "Improve source health, data coverage, and measurement without exporting voter/contact data.",
    dailyResponsibilities: ["Review source health", "Inspect tool coverage", "Flag stale data", "Prepare data quality tickets"],
    ownedDomains: ["dashboard_ux", "tool_builder", "campaign_management"],
    relatedSections: ["deployment_readiness", "tool_builder", "memory_observations"],
    primaryTools: ["campaign-state-loader", "agent-tool-coverage", "continuous-optimization"],
    secondaryTools: ["campaign-tool-gap-orchestrator"],
    requiredInputs: ["sourceHealth", "toolCoverage", "agentTooling"],
    outputsProduced: ["data quality notes", "tool gap tickets", "source repair prompts"],
    decisionsPrepared: ["which source needs repair", "which measurement gap matters"],
    humanApprovalBoundaries: ["No voter/contact export", "No production data mutation"],
    restrictedActions: ["voter_export", "contact_export", "production_mutation_without_approval"],
    trainingNeeds: ["data-safety-101", "source-health-review"],
    whatThisRoleTeachesCampaignState: "Teaches whether the map is fresh enough to trust.",
  }),
  role({
    id: "content_director",
    label: "Content Director",
    mission: "Transform events, county signals, and strategy into approved content packets.",
    dailyResponsibilities: ["Review content opportunities", "Prepare recap prompts", "Coordinate comms", "Capture content lessons"],
    ownedDomains: ["social_media", "communications", "hot_wash"],
    relatedSections: ["content_media", "events_calendar", "communications"],
    primaryTools: ["content-recap-builder", "media-moment-detector", "event-intelligence-playbook"],
    secondaryTools: ["hot-wash-intelligence"],
    requiredInputs: ["communicationActions", "eventReadiness", "knowledge"],
    outputsProduced: ["content packet", "recap prompt", "media lesson"],
    decisionsPrepared: ["which moment deserves content", "which content needs approval"],
    humanApprovalBoundaries: ["Human approves publish", "No public claim without source"],
    restrictedActions: ["production_mutation_without_approval"],
    trainingNeeds: ["content-approval-safety", "hot-wash-to-content"],
    whatThisRoleTeachesCampaignState: "Teaches which narratives and media moments are useful enough to repeat.",
  }),
  role({
    id: "event_lead",
    label: "Event Lead",
    mission: "Prepare events, coordinate day-of needs, and capture hot wash learning.",
    dailyResponsibilities: ["Review event readiness", "Check host/volunteer gaps", "Prepare event packet", "File hot wash prompt"],
    ownedDomains: ["event_planning", "calendar", "host", "hot_wash"],
    relatedSections: ["events_calendar", "volunteer_field", "content_media"],
    primaryTools: ["event-readiness-builder", "calendar-sync-health", "event-intelligence-playbook"],
    secondaryTools: ["hot-wash-intelligence", "volunteer-system"],
    requiredInputs: ["eventReadiness", "calendarEventPressure", "volunteerHealth"],
    outputsProduced: ["event prep packet", "day-of checklist", "hot wash prompt"],
    decisionsPrepared: ["what event needs prep", "what blocker needs escalation"],
    humanApprovalBoundaries: ["No calendar write", "No public publish"],
    restrictedActions: ["google_calendar_write", "production_mutation_without_approval"],
    trainingNeeds: ["event-readiness-101", "hot-wash-capture"],
    whatThisRoleTeachesCampaignState: "Teaches whether events produced county, volunteer, comms, and media learning.",
  }),
  role({
    id: "operations_lead",
    label: "Operations Lead",
    mission: "Keep internal operations, tooling, deployment readiness, and handoffs coherent.",
    dailyResponsibilities: ["Review operational blockers", "Check deployment readiness", "Prepare handoff", "Route tool gaps"],
    ownedDomains: ["campaign_management", "tool_builder", "dashboard_ux"],
    relatedSections: ["executive_command", "tool_builder", "deployment_readiness"],
    primaryTools: ["deployment-readiness-playbook", "campaign-tool-gap-orchestrator", "continuous-optimization"],
    secondaryTools: ["orchestration-sprint-recommender"],
    requiredInputs: ["signalLoadErrors", "agentTooling", "crossDomainOrchestration"],
    outputsProduced: ["ops packet", "handoff notes", "tool gap review"],
    decisionsPrepared: ["what is safe to ship", "what tool gap blocks next sprint"],
    humanApprovalBoundaries: ["No production mutation without explicit approval"],
    restrictedActions: NO_PROD,
    trainingNeeds: ["deployment-readiness-review", "orchestration-handoff"],
    whatThisRoleTeachesCampaignState: "Teaches which operating systems are ready enough for humans to rely on.",
  }),
];

export const REQUIRED_CAMPAIGN_ROLE_IDS: CampaignOrchestrationRoleId[] = [
  "campaign_manager",
  "candidate",
  "communications_director",
  "field_director",
  "volunteer_coordinator",
  "finance_director",
  "compliance_lead",
  "scheduler",
  "county_lead",
  "digital_director",
  "research_director",
  "data_director",
  "content_director",
  "event_lead",
  "operations_lead",
];

export function getCampaignRole(id: CampaignOrchestrationRoleId): CampaignRoleDefinition {
  const role = CAMPAIGN_ROLE_REGISTRY.find((r) => r.id === id);
  if (!role) throw new Error(`Unknown campaign role: ${id}`);
  return role;
}
