import type { RoleCopilotDefinition, RoleCopilotId } from "./role-copilot-types";

const M = "2026-03";

function t(label: string, path: string): { label: string; href: string } {
  const href = path.includes("month=") ? path : path.includes("?") ? path : path.includes("/admin") ? `${path}${path.includes("campaign-events") || path.includes("campaign-manager") || path.includes("candidate") ? (path.includes("?") ? "&" : "?") + `month=${M}` : path}` : path;
  return { label, href: href.replace("2026-03", M) };
}

export const ROLE_COPILOT_REGISTRY: RoleCopilotDefinition[] = [
  {
    id: "candidate",
    label: "Candidate",
    campaignUserRole: "candidate",
    mission: "Stay on top of approvals, travel totals, and calendar truth without drowning in ops detail.",
    focusAreas: ["Approvals", "Travel reimbursement", "Upcoming events"],
    firstTasks: [
      t("Open candidate dashboard", `/admin/candidate-dashboard?month=${M}`),
      t("Review approval queue", `/admin/campaign-events/review?month=${M}&mode=chronological`),
      t("Check reimbursement summary", `/admin/campaign-events/reimbursement?month=${M}`),
    ],
    dailyTasks: ["Scan pending approvals", "Confirm travel lines look right", "Glance at week ahead"],
    weeklyTasks: ["Sign off month readiness with CM", "Review reimbursement packet before print"],
    trainingModuleIds: ["tr-candidate-approvals-101", "tr-calendar-truth-101", "tr-reimbursement-candidate-101"],
    dashboardModuleIds: ["executive_summary", "approval_queue", "travel_reimbursement_summary", "upcoming_events", "ai_next_actions"],
    safeActions: ["View dashboards", "Approve/deny/hold in review", "Open approval packages"],
    gatedActions: ["Promote to Google Calendar", "Send approval email", "Print reimbursement (confirm totals first)"],
    doNotTouch: ["Volunteer CRM exports", "Finance posting", "Mass communications send"],
    escalationPath: "Campaign manager → Steve/operator",
    explanationStyle: "warm",
    skillLevels: ["beginner", "intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Approvals cleared within 48h", "Zero surprise travel totals", "Calendar matches expectations"],
    linkedToolIds: ["role-copilot-brief-builder", "presentation-readiness-advisor"],
  },
  {
    id: "campaign_manager",
    label: "Campaign manager",
    campaignUserRole: "campaign_manager",
    mission: "Run month operations: workbench, review queues, calendar sync, and readiness close.",
    focusAreas: ["Month review", "Workbench triage", "Calendar health"],
    firstTasks: [
      t("CM dashboard", `/admin/campaign-manager-dashboard?month=${M}`),
      t("Events workbench", `/admin/campaign-events/workbench?month=${M}`),
      t("Month review wizard", `/admin/campaign-events/review?month=${M}&mode=chronological`),
    ],
    dailyTasks: ["Clear highest-priority review items", "Check sync health", "Triage intake"],
    weeklyTasks: ["Month readiness score", "Promotion readiness review", "Hot wash queue"],
    trainingModuleIds: ["tr-os-navigation-101", "tr-workbench-101", "tr-month-review-101", "tr-calendar-sync-101"],
    dashboardModuleIds: ["executive_summary", "approval_queue", "calendar_sync_health", "promotion_readiness", "event_planning_checklist", "hot_wash_queue", "ai_next_actions"],
    safeActions: ["Edit fact cards", "Queue review", "Planning workbook saves"],
    gatedActions: ["GCal live promotion", "Mass email", "Batch approvals without review"],
    doNotTouch: ["FIN-1 post", "Compliance filing export without counsel"],
    escalationPath: "Treasurer (finance) · Steve/operator (architecture)",
    explanationStyle: "direct",
    skillLevels: ["beginner", "intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Month readiness ≥ target", "Sync stale count = 0", "Intake conflicts resolved"],
    linkedToolIds: ["role-copilot-brief-builder", "dashboard-module-recommender"],
  },
  {
    id: "treasurer",
    label: "Treasurer",
    campaignUserRole: "treasurer",
    mission: "Produce accurate reimbursement packets and audit-ready travel documentation.",
    focusAreas: ["Reimbursement", "Mileage gaps", "Receipt completeness"],
    firstTasks: [
      t("Reimbursement page", `/admin/campaign-events/reimbursement?month=${M}`),
      t("Travel report", `/admin/campaign-events/travel-report?month=${M}`),
      t("Finance readiness panel", `/admin/campaign-events/reimbursement?month=${M}`),
    ],
    dailyTasks: ["Review new travel lines", "Flag missing mileage", "Receipt gap check"],
    weeklyTasks: ["Print-ready packet review", "Exception list with CM"],
    trainingModuleIds: ["tr-reimbursement-treasurer-101", "tr-mileage-101", "tr-finance-readiness-101"],
    dashboardModuleIds: ["travel_reimbursement_summary", "missing_mileage", "finance_readiness", "receipt_gaps", "print_download_actions"],
    safeActions: ["Review totals", "Export/print when blockers clear", "Annotate exceptions"],
    gatedActions: ["Change approval decisions without candidate", "Post to FIN-1"],
    doNotTouch: ["Calendar promotion", "Volunteer mass outreach"],
    escalationPath: "Compliance lead · Campaign manager",
    explanationStyle: "precise",
    skillLevels: ["beginner", "intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Packet prints clean", "Mileage queue empty at close", "Exceptions documented"],
    linkedToolIds: ["role-copilot-brief-builder"],
  },
  {
    id: "event_planner",
    label: "Event planner",
    campaignUserRole: "campaign_manager",
    mission: "Execute event quality: planning workbook, run of show, materials, volunteer slots.",
    focusAreas: ["Event drilldown", "Planning readiness", "Volunteer needs"],
    firstTasks: [
      t("Workbench", `/admin/campaign-events/workbench?month=${M}`),
      t("Campaign calendar", `/admin/campaign-calendar/timeline`),
      t("Training: event planning", `/admin/training?role=event_planner`),
    ],
    dailyTasks: ["Update run of show", "Pack list checks", "Host follow-up flags"],
    weeklyTasks: ["Month planning readiness", "County-tagged events review"],
    trainingModuleIds: ["tr-event-planning-101", "tr-run-of-show-101", "tr-host-support-101"],
    dashboardModuleIds: ["upcoming_events", "event_planning_checklist", "volunteer_needs", "host_follow_up"],
    safeActions: ["Save planning sections", "Draft emails (no send)", "Media intake metadata"],
    gatedActions: ["Approve events", "Promote calendar", "Send comms"],
    doNotTouch: ["Reimbursement finalize", "Voter file"],
    escalationPath: "Campaign manager",
    explanationStyle: "direct",
    skillLevels: ["beginner", "intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Planning readiness up", "Run of show complete pre-event", "Post-event hot wash filed"],
    linkedToolIds: ["role-copilot-brief-builder"],
  },
  {
    id: "volunteer_coordinator",
    label: "Volunteer coordinator",
    campaignUserRole: "volunteer_coordinator",
    mission: "Staff events with the right volunteers and clear asks — no unsafe outreach.",
    focusAreas: ["Volunteer command center", "Event assignments", "Training paths"],
    firstTasks: [
      t("Volunteer center", `/admin/volunteers`),
      t("Volunteer intake", `/admin/volunteers/intake`),
      t("Events workbench", `/admin/campaign-events/workbench?month=${M}`),
    ],
    dailyTasks: ["Review new signups", "Match volunteers to events", "Follow up no-shows"],
    weeklyTasks: ["County volunteer gaps", "Training completion check"],
    trainingModuleIds: ["tr-volunteer-mgmt-101", "tr-event-volunteer-planning-101"],
    dashboardModuleIds: ["volunteer_needs", "upcoming_events", "host_follow_up", "role_training"],
    safeActions: ["Update volunteer profiles", "Recommend assignments", "Log notes"],
    gatedActions: ["Mass SMS/email", "Export PII lists"],
    doNotTouch: ["Approval queue", "GCal write", "FIN exports"],
    escalationPath: "Campaign manager",
    explanationStyle: "warm",
    skillLevels: ["beginner", "intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Slots filled", "Training modules completed", "No duplicate assignments"],
    linkedToolIds: ["volunteer-copilot", "role-copilot-brief-builder"],
  },
  {
    id: "volunteer",
    label: "Volunteer",
    campaignUserRole: "volunteer_coordinator",
    mission: "Show up prepared, check in, capture helpful field signal — safely.",
    focusAreas: ["Assignments", "Run of show summary", "Check-in"],
    firstTasks: [
      t("Training start", `/admin/training?role=volunteer`),
      t("Onboarding", `/admin/onboarding`),
      t("Volunteer resources", `/volunteer/resources`),
    ],
    dailyTasks: ["Read assignment", "Check in at event", "Upload photos (metadata only)"],
    weeklyTasks: ["Complete one training module", "Thank-you follow-up template review"],
    trainingModuleIds: ["tr-volunteer-basics-101", "tr-check-in-101", "tr-photo-metadata-101"],
    dashboardModuleIds: ["upcoming_events", "onboarding_checklist", "role_training", "ai_next_actions"],
    safeActions: ["View assignments", "Mark tasks done locally", "Ask AI tutor"],
    gatedActions: ["Approve anything", "Access finance", "Send email from OS"],
    doNotTouch: ["Admin queues", "Reimbursement", "Promotion"],
    escalationPath: "Volunteer coordinator",
    explanationStyle: "warm",
    skillLevels: ["beginner", "intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Check-ins recorded", "Training progress", "Zero finance route visits"],
    linkedToolIds: ["volunteer-copilot"],
  },
  {
    id: "intern",
    label: "Intern",
    campaignUserRole: "new_admin_user",
    mission: "Learn campaign ops by completing supervised tasks: receipts, drafts, checklists.",
    focusAreas: ["Task list", "Receipt upload", "Event detail drafts"],
    firstTasks: [
      t("Onboarding", `/admin/onboarding`),
      t("Training", `/admin/training?role=intern`),
      t("Workbench (read)", `/admin/campaign-events/workbench?month=${M}`),
    ],
    dailyTasks: ["Assigned checklist items", "Upload receipt metadata", "Flag gaps to supervisor"],
    weeklyTasks: ["Complete training module", "Shadow month review (read-only)"],
    trainingModuleIds: ["tr-intern-basics-101", "tr-receipt-upload-101", "tr-event-detail-draft-101"],
    dashboardModuleIds: ["onboarding_checklist", "event_planning_checklist", "receipt_gaps", "missing_mileage", "role_training"],
    safeActions: ["Draft fields", "Upload under supervision", "Local training progress"],
    gatedActions: ["Finalize reimbursement", "Approve/deny", "Promote calendar"],
    doNotTouch: ["Send email", "FIN-1", "Mass comms"],
    escalationPath: "Campaign manager or treasurer",
    explanationStyle: "educational",
    skillLevels: ["beginner", "intermediate"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Tasks closed", "Supervisor approval rate", "Modules completed"],
    linkedToolIds: ["intern-copilot"],
  },
  {
    id: "field_manager",
    label: "Field manager",
    campaignUserRole: "county_lead",
    mission: "Coordinate county priorities, volunteers, and post-event learning.",
    focusAreas: ["County intel", "Volunteer needs", "Hot wash"],
    firstTasks: [
      t("County intelligence", `/admin/county-intelligence`),
      t("Counties bridge", `/admin/counties`),
      t("Hot wash", `/admin/campaign-events/media-approval`),
    ],
    dailyTasks: ["County priority scan", "Field notes", "Volunteer gaps"],
    weeklyTasks: ["Power of 5 review", "County memory update after events"],
    trainingModuleIds: ["tr-county-dashboard-101", "tr-power-of-five-101", "tr-hot-wash-county-101"],
    dashboardModuleIds: ["county_memory", "volunteer_needs", "hot_wash_queue", "upcoming_events"],
    safeActions: ["Read county dashboards", "Add county memory notes", "Recommend priorities"],
    gatedActions: ["Voter file export", "Mass outreach"],
    doNotTouch: ["Finance finalize", "GCal promotion"],
    escalationPath: "Campaign manager",
    explanationStyle: "direct",
    skillLevels: ["intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["County gaps narrowing", "Events staffed", "Memory records updated"],
    linkedToolIds: ["field-manager-copilot"],
  },
  {
    id: "county_lead",
    label: "County lead",
    campaignUserRole: "county_lead",
    mission: "Represent county organizing: local events, party meetings, county portal bridge.",
    focusAreas: ["County ops", "Local calendar", "Party meetings"],
    firstTasks: [
      t("Counties", `/admin/counties`),
      t("County intel", `/admin/county-intelligence`),
      t("Workbench", `/admin/campaign-events/workbench?month=${M}`),
    ],
    dailyTasks: ["Local event review", "County contacts", "Share field notes"],
    weeklyTasks: ["County readiness with CM", "Coordinate with field manager"],
    trainingModuleIds: ["tr-county-lead-101", "tr-county-dashboard-101"],
    dashboardModuleIds: ["county_memory", "upcoming_events", "volunteer_needs"],
    safeActions: ["View county data", "Suggest events", "Training modules"],
    gatedActions: ["Statewide approval", "Finance"],
    doNotTouch: ["Promotion", "Mass email"],
    escalationPath: "Field manager → campaign manager",
    explanationStyle: "warm",
    skillLevels: ["beginner", "intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["County events on calendar", "Volunteer pipeline active"],
    linkedToolIds: ["field-manager-copilot"],
  },
  {
    id: "host",
    label: "Host",
    campaignUserRole: "host",
    mission: "Support hosted events: intake clarity, follow-up, and host communications drafts.",
    focusAreas: ["Host intake", "Follow-up", "Event confirmations"],
    firstTasks: [
      t("Get involved (public)", `/get-involved`),
      t("Communications (read)", `/admin/communications`),
      t("Training hosts", `/admin/training?role=host`),
    ],
    dailyTasks: ["Respond to host questions", "Confirm event details", "Draft follow-up (no send)"],
    weeklyTasks: ["Review intake queue with CM"],
    trainingModuleIds: ["tr-host-basics-101", "tr-intake-bridge-101"],
    dashboardModuleIds: ["host_follow_up", "upcoming_events", "role_training"],
    safeActions: ["View intake", "Draft messages", "Training"],
    gatedActions: ["Send email", "Approve events"],
    doNotTouch: ["Finance", "Volunteer export", "Calendar write"],
    escalationPath: "Communications lead → campaign manager",
    explanationStyle: "warm",
    skillLevels: ["beginner", "intermediate"],
    progressionLevels: [1, 2],
    successMetrics: ["Hosts confirmed", "Intake complete", "Follow-ups drafted"],
    linkedToolIds: ["communications-lead-copilot"],
  },
  {
    id: "social_media_lead",
    label: "Social media lead",
    campaignUserRole: "operator",
    mission: "Plan content, draft posts, queue approvals — never auto-publish.",
    focusAreas: ["Owned media", "Content calendar", "Approval queue"],
    firstTasks: [
      t("Social workbench", `/admin/workbench/social`),
      t("Owned media", `/admin/owned-media`),
      t("Training", `/admin/training?role=social_media_lead`),
    ],
    dailyTasks: ["Review drafts", "Schedule planning", "Engagement check"],
    weeklyTasks: ["Content calendar with CM", "Hot wash media picks"],
    trainingModuleIds: ["tr-social-basics-101", "tr-owned-media-101"],
    dashboardModuleIds: ["hot_wash_queue", "recent_activity", "ai_next_actions"],
    safeActions: ["Draft posts", "Upload media metadata", "Training"],
    gatedActions: ["Auto-publish", "Mass email"],
    doNotTouch: ["Finance", "Approvals", "GCal promotion"],
    escalationPath: "Communications lead",
    explanationStyle: "direct",
    skillLevels: ["intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Drafts approved", "Calendar on track", "No off-brand posts"],
    linkedToolIds: ["social-media-copilot"],
  },
  {
    id: "communications_lead",
    label: "Communications lead",
    campaignUserRole: "operator",
    mission: "Coordinate email lanes, hosts, and coalition outreach with send gates off by default.",
    focusAreas: ["Comms center", "Email command center", "Host follow-up"],
    firstTasks: [
      t("Communications center", `/admin/communications`),
      t("Email command center", `/admin/workbench/email-command-center`),
      t("Training", `/admin/training?role=communications_lead`),
    ],
    dailyTasks: ["Review drafts", "Audience readiness", "Host/coalition threads"],
    weeklyTasks: ["Comms plan with CM", "ECC readiness check"],
    trainingModuleIds: ["tr-comms-center-101", "tr-email-safety-101", "tr-host-comms-101"],
    dashboardModuleIds: ["host_follow_up", "ai_next_actions", "role_training"],
    safeActions: ["Draft", "Preview", "Training modules"],
    gatedActions: ["EMAIL_SEND_ENABLED sends", "Mass broadcast"],
    doNotTouch: ["FIN-1", "Calendar promotion", "Approval decisions"],
    escalationPath: "Steve/operator · campaign manager",
    explanationStyle: "precise",
    skillLevels: ["intermediate", "advanced"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Drafts ready", "Zero accidental sends", "Host pipeline healthy"],
    linkedToolIds: ["communications-lead-copilot"],
  },
  {
    id: "finance_helper",
    label: "Finance helper",
    campaignUserRole: "treasurer",
    mission: "Support treasurer: receipts, mileage flags, compliance handoff — no finalize alone.",
    focusAreas: ["Receipts", "Mileage", "Compliance docs"],
    firstTasks: [
      t("Reimbursement (read)", `/admin/campaign-events/reimbursement?month=${M}`),
      t("Compliance", `/admin/compliance`),
      t("Training", `/admin/training?role=finance_helper`),
    ],
    dailyTasks: ["Receipt staging", "Mileage flag review", "Ask treasurer questions"],
    weeklyTasks: ["Exception list update"],
    trainingModuleIds: ["tr-receipt-basics-101", "tr-compliance-intro-101"],
    dashboardModuleIds: ["receipt_gaps", "missing_mileage", "finance_readiness"],
    safeActions: ["Upload receipts", "Annotate", "Training"],
    gatedActions: ["Print packet", "Approve reimbursements"],
    doNotTouch: ["Send email", "GCal", "Approvals"],
    escalationPath: "Treasurer",
    explanationStyle: "precise",
    skillLevels: ["beginner", "intermediate"],
    progressionLevels: [1, 2],
    successMetrics: ["Receipt gaps down", "Clean handoff to treasurer"],
    linkedToolIds: ["role-copilot-brief-builder"],
  },
  {
    id: "new_admin",
    label: "New admin",
    campaignUserRole: "new_admin_user",
    mission: "Learn navigation and simple surfaces before touching high-risk workflows.",
    focusAreas: ["Navigation", "Onboarding", "Command palette"],
    firstTasks: [
      t("Onboarding", `/admin/onboarding`),
      t("Training", `/admin/training?role=new_admin`),
      t("AI command center", `/admin/ai-command-center`),
    ],
    dailyTasks: ["Complete one training step", "Practice Ctrl+K palette", "Review do-not-touch list"],
    weeklyTasks: ["Unlock next module", "Shadow CM dashboard (read-only)"],
    trainingModuleIds: ["tr-os-navigation-101", "tr-ai-command-center-101", "tr-safety-gates-101"],
    dashboardModuleIds: ["onboarding_checklist", "role_training", "command_palette", "executive_summary"],
    safeActions: ["Browse", "Training", "Ask AI tutor"],
    gatedActions: ["All gated ops until L2 training"],
    doNotTouch: ["Promotion", "Send", "FIN", "Approvals until trained"],
    escalationPath: "Steve/operator",
    explanationStyle: "educational",
    skillLevels: ["beginner"],
    progressionLevels: [1, 2, 3],
    successMetrics: ["Modules completed", "No accidental gated clicks"],
    linkedToolIds: ["guided-walkthrough-builder"],
  },
  {
    id: "operator",
    label: "Steve / operator",
    campaignUserRole: "operator",
    mission: "Full Campaign OS oversight: command center, tool builder queue, and architecture safety.",
    focusAreas: ["Command center", "System health", "Tool gaps"],
    firstTasks: [
      t("AI command center", `/admin/ai-command-center`),
      t("Dashboard builder", `/admin/ai-command-center/dashboard-builder`),
      t("Tool builder queue", `/admin/ai-command-center/tool-builder`),
    ],
    dailyTasks: ["OS control snapshot", "Review tool tickets", "Presentation readiness"],
    weeklyTasks: ["Sprint priorities", "County/comms/volunteer panels", "Merge discipline"],
    trainingModuleIds: ["tr-operator-command-101", "tr-tool-builder-101"],
    dashboardModuleIds: ["executive_summary", "recent_activity", "ai_next_actions", "command_palette", "calendar_sync_health"],
    safeActions: ["All read paths", "Blueprint build", "Ticket review"],
    gatedActions: ["Production deploy", "Enable mass send", "Enable GCal write in prod"],
    doNotTouch: ["Bypass human gates in prod", "Commit secrets"],
    escalationPath: "Self + developer review",
    explanationStyle: "direct",
    skillLevels: ["advanced"],
    progressionLevels: [3],
    successMetrics: ["Deploy green", "Tool queue triaged", "Demo readiness score"],
    linkedToolIds: ["tool-gap-detector", "tool-build-ticket-generator"],
  },
];

export function getRoleCopilot(role: RoleCopilotId): RoleCopilotDefinition | undefined {
  return ROLE_COPILOT_REGISTRY.find((r) => r.id === role);
}

export function listRoleCopilotIds(): RoleCopilotId[] {
  return ROLE_COPILOT_REGISTRY.map((r) => r.id);
}
