import type { ArkansasMediaSourceSeed } from "./types";

/**
 * Single source of truth for Arkansas earned-media outlets.
 * Update RSS/sitemap/search URLs here — do not duplicate definitions elsewhere.
 */
export const ARKANSAS_MEDIA_SOURCE_SEEDS: ArkansasMediaSourceSeed[] = [
  {
    slug: "arkansas-democrat-gazette",
    name: "Arkansas Democrat-Gazette",
    sourceType: "NEWSPAPER",
    region: "Central Arkansas / Statewide",
    coveredCities: ["Little Rock", "North Little Rock", "Sherwood", "Jacksonville"],
    homepage: "https://www.arkansasonline.com",
    priority: 10,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE", "SECTION_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Primary statewide paper; prefer official RSS/sitemap when verified — many pages are paywalled.",
    isActive: true,
  },
  {
    slug: "arkansas-times",
    name: "Arkansas Times",
    sourceType: "NEWS_MAGAZINE",
    region: "Central Arkansas / Statewide",
    coveredCities: ["Little Rock", "North Little Rock", "Sherwood", "Jacksonville"],
    homepage: "https://arktimes.com",
    priority: 9,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE", "TAG_PAGE"],
    rssUrl: "https://arktimes.com/feed/",
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Opinion, editorials, and political narrative.",
    isActive: true,
  },
  {
    slug: "fayetteville-flyer",
    name: "Fayetteville Flyer",
    sourceType: "DIGITAL_LOCAL",
    region: "Northwest Arkansas",
    coveredCities: ["Fayetteville"],
    homepage: "https://fayettevilleflyer.com",
    priority: 9,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "CATEGORY_PAGE"],
    rssUrl: "https://fayettevilleflyer.com/feed/",
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "NWA civic and event coverage.",
    isActive: true,
  },
  {
    slug: "log-cabin-democrat",
    name: "Log Cabin Democrat",
    sourceType: "NEWSPAPER",
    region: "Central Arkansas",
    coveredCities: ["Conway"],
    homepage: "https://www.thecabin.net",
    priority: 8,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Primary Conway outlet.",
    isActive: true,
  },
  {
    slug: "arkansas-leader",
    name: "Arkansas Leader",
    sourceType: "DIGITAL_LOCAL",
    region: "Central Arkansas",
    coveredCities: ["Cabot"],
    homepage: "https://www.arkansasleader.com",
    priority: 8,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Cabot-area digital outlet.",
    isActive: true,
  },
  {
    slug: "daily-citizen",
    name: "The Daily Citizen",
    sourceType: "NEWSPAPER",
    region: "Central Arkansas",
    coveredCities: ["Searcy"],
    homepage: "https://www.thedailycitizen.com",
    priority: 8,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Searcy.",
    isActive: true,
  },
  {
    slug: "jonesboro-sun",
    name: "The Jonesboro Sun",
    sourceType: "NEWSPAPER",
    region: "Northeast Arkansas",
    coveredCities: ["Jonesboro"],
    homepage: "https://www.jonesborosun.com",
    priority: 8,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Jonesboro.",
    isActive: true,
  },
  {
    slug: "southwest-times-record",
    name: "Southwest Times Record",
    sourceType: "NEWSPAPER",
    region: "River Valley / Western Arkansas",
    coveredCities: ["Fort Smith"],
    homepage: "https://www.swtimes.com",
    priority: 8,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Fort Smith.",
    isActive: true,
  },
  {
    slug: "pine-bluff-commercial",
    name: "Pine Bluff Commercial",
    sourceType: "NEWSPAPER",
    region: "Southeast Arkansas",
    coveredCities: ["Pine Bluff"],
    homepage: "https://www.pbcommercial.com",
    priority: 8,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "SECTION_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Pine Bluff.",
    isActive: true,
  },
  {
    slug: "sentinel-record",
    name: "The Sentinel-Record",
    sourceType: "NEWSPAPER",
    region: "Hot Springs / Garland County",
    coveredCities: ["Hot Springs"],
    homepage: "https://www.hotsr.com",
    priority: 7,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Hot Springs.",
    isActive: true,
  },
  {
    slug: "paragould-daily-press",
    name: "Paragould Daily Press",
    sourceType: "NEWSPAPER",
    region: "Northeast Arkansas",
    coveredCities: ["Paragould"],
    homepage: "https://www.paragoulddailypress.com",
    priority: 7,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Paragould.",
    isActive: true,
  },
  {
    slug: "evening-times",
    name: "Evening Times",
    sourceType: "NEWSPAPER",
    region: "East Arkansas / Crittenden County",
    coveredCities: ["West Memphis"],
    homepage: "https://marioneveningtimes-ar.newsmemory.com",
    priority: 7,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Crittenden County; Newsmemory host — verify robots/terms before deep fetch.",
    isActive: true,
  },
  {
    slug: "mena-star",
    name: "Mena Star",
    sourceType: "NEWSPAPER",
    region: "Polk County / Western Arkansas",
    coveredCities: ["Mena"],
    homepage: "https://www.menastar.com",
    priority: 7,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SITEMAP_IF_AVAILABLE", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Kelly has appeared here — add RSS/sitemap when verified.",
    isActive: true,
  },
  {
    slug: "el-dorado-news-times",
    name: "El Dorado News-Times",
    sourceType: "NEWSPAPER",
    region: "South Arkansas / Union County",
    coveredCities: ["El Dorado"],
    homepage: "https://www.eldoradonews.com",
    priority: 7,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SEARCH_PAGE", "SECTION_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Union County coverage; verify homepage URL + feed for current CMS.",
    isActive: true,
  },
  {
    slug: "jacksonville-leader",
    name: "Jacksonville Leader",
    sourceType: "NEWSPAPER",
    region: "Central Arkansas",
    coveredCities: ["Jacksonville"],
    homepage: "https://www.jacksonvilleleader.com",
    priority: 8,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Local Jacksonville paper — confirm live domain and add RSS when available.",
    isActive: true,
  },
  {
    slug: "saline-courier",
    name: "Saline Courier",
    sourceType: "NEWSPAPER",
    region: "Central Arkansas",
    coveredCities: ["Benton", "Bryant"],
    homepage: "https://www.bentoncourier.com",
    priority: 7,
    discoveryMethods: ["RSS_IF_AVAILABLE", "SEARCH_PAGE", "SECTION_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Saline County; domain may be branded Benton Courier — verify.",
    isActive: true,
  },
  {
    slug: "katv",
    name: "KATV",
    sourceType: "TV",
    region: "Central Arkansas",
    coveredCities: ["Little Rock", "North Little Rock", "Sherwood", "Jacksonville", "Benton"],
    homepage: "https://katv.com",
    priority: 10,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "TAG_PAGE", "VIDEO_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Add station RSS/outbound feed URL when verified.",
    isActive: true,
  },
  {
    slug: "thv11",
    name: "THV11",
    sourceType: "TV",
    region: "Central Arkansas",
    coveredCities: ["Little Rock", "North Little Rock", "Sherwood", "Jacksonville", "Benton"],
    homepage: "https://www.thv11.com",
    priority: 10,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "VIDEO_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Tegna — check for public RSS or news sitemap.",
    isActive: true,
  },
  {
    slug: "kark",
    name: "KARK",
    sourceType: "TV",
    region: "Central Arkansas",
    coveredCities: ["Little Rock", "North Little Rock", "Sherwood", "Jacksonville", "Benton"],
    homepage: "https://www.kark.com",
    priority: 9,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "VIDEO_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Nexstar — outbound RSS often under /feeds/ when enabled.",
    isActive: true,
  },
  {
    slug: "fox16",
    name: "FOX16 KLRT",
    sourceType: "TV",
    region: "Central Arkansas",
    coveredCities: ["Little Rock", "North Little Rock", "Sherwood", "Jacksonville", "Benton"],
    homepage: "https://www.fox16.com",
    priority: 9,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "VIDEO_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Central AR FOX affiliate.",
    isActive: true,
  },
  {
    slug: "knwa-fox24",
    name: "KNWA / FOX24",
    sourceType: "TV",
    region: "Northwest Arkansas / River Valley",
    coveredCities: ["Fayetteville", "Springdale", "Rogers", "Bentonville", "Bella Vista", "Fort Smith"],
    homepage: "https://www.nwahomepage.com",
    priority: 9,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "VIDEO_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "NWA / River Valley.",
    isActive: true,
  },
  {
    slug: "4029",
    name: "40/29",
    sourceType: "TV",
    region: "Northwest Arkansas / River Valley",
    coveredCities: ["Fayetteville", "Springdale", "Rogers", "Bentonville", "Bella Vista", "Fort Smith"],
    homepage: "https://www.4029tv.com",
    priority: 9,
    discoveryMethods: ["HOMEPAGE_RECRAWL", "SEARCH_PAGE", "VIDEO_PAGE"],
    rssUrl: null,
    sitemapUrl: null,
    searchUrlTemplate: null,
    notes: "Hearst ABC/CW — check news sitemap.",
    isActive: true,
  },
];

/** First-wave automated RSS slice (expand feeds as you verify them). */
export const VERTICAL_SLICE_SOURCE_SLUGS: string[] = [
  "arkansas-democrat-gazette",
  "arkansas-times",
  "fayetteville-flyer",
  "katv",
  "thv11",
  "kark",
  "knwa-fox24",
  "4029",
];

export function seedsBySlug(): Map<string, ArkansasMediaSourceSeed> {
  return new Map(ARKANSAS_MEDIA_SOURCE_SEEDS.map((s) => [s.slug, s]));
}

export function filterSeedsForRun(options: {
  onlySlugs?: string[] | null;
  verticalSliceOnly: boolean;
  singleSlug?: string | null;
}): ArkansasMediaSourceSeed[] {
  const map = seedsBySlug();
  if (options.singleSlug) {
    const s = map.get(options.singleSlug);
    return s && s.isActive ? [s] : [];
  }
  let list = ARKANSAS_MEDIA_SOURCE_SEEDS.filter((s) => s.isActive);
  if (options.verticalSliceOnly) {
    const allow = new Set(VERTICAL_SLICE_SOURCE_SLUGS);
    list = list.filter((s) => allow.has(s.slug));
  }
  if (options.onlySlugs?.length) {
    const allow = new Set(options.onlySlugs);
    list = list.filter((s) => allow.has(s.slug));
  }
  return list.sort((a, b) => b.priority - a.priority);
}
