import React from "react";
import Link from "next/link";
import type { CampaignMediaRecord } from "@/content/media/campaign-media-types";
import {
  formatTranscriptTimestamp,
  isPublicTranscript,
  youtubeWatchUrl,
} from "@/lib/media/campaign-transcript";

export type CampaignTranscriptDisclosureProps = {
  media: CampaignMediaRecord;
  className?: string;
};

/**
 * Accessible transcript disclosure. Transcript text is server-rendered inside `<details>`
 * so crawlers and users without JS still receive the content.
 */
export function CampaignTranscriptDisclosure({ media, className }: CampaignTranscriptDisclosureProps) {
  if (!isPublicTranscript(media)) return null;

  const { transcript } = media;
  const hasSegments = transcript.segments.length > 0;

  return (
    <details
      className={
        className ??
        "mt-6 rounded-card border border-kelly-ink/10 bg-kelly-fog/80 open:bg-white open:shadow-sm"
      }
    >
      <summary className="cursor-pointer list-none px-4 py-3 font-body text-base font-semibold text-kelly-navy marker:content-none [&::-webkit-details-marker]:hidden focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-kelly-gold focus-visible:ring-offset-2">
        <span className="inline-flex items-center gap-2">
          <span aria-hidden className="text-kelly-slate">
            ▾
          </span>
          Read the transcript
        </span>
      </summary>
      <div className="border-t border-kelly-ink/10 px-4 py-5 md:px-6">
        <p className="font-body text-sm text-kelly-slate">
          {transcript.isAutoGenerated
            ? "This transcript was reviewed for accuracy after automated captioning."
            : "Transcript reviewed for accuracy."}
          {transcript.source !== "UNKNOWN" ? (
            <span className="ml-1">
              Source:{" "}
              {transcript.source === "CREATOR_SUPPLIED" || transcript.source === "MANUAL"
                ? "Creator-supplied"
                : transcript.source === "YOUTUBE_CREATOR_CAPTIONS"
                  ? "YouTube creator captions"
                  : transcript.source === "YOUTUBE_AUTOMATIC_CAPTIONS"
                    ? "YouTube captions (reviewed)"
                    : transcript.source === "AI_GENERATED"
                      ? "AI-assisted (reviewed)"
                      : "Campaign editorial"}
            </span>
          ) : null}
        </p>

        {hasSegments ? (
          <div className="mt-5 space-y-5">
            {transcript.segments.map((seg) => {
              const stamp =
                seg.startSeconds != null ? formatTranscriptTimestamp(seg.startSeconds) : null;
              const jumpHref =
                seg.startSeconds != null
                  ? youtubeWatchUrl(media.youtubeVideoId, seg.startSeconds)
                  : null;
              return (
                <div key={seg.id} className="max-w-prose">
                  {seg.chapter ? (
                    <h3 className="font-heading text-lg font-bold text-kelly-ink">{seg.chapter}</h3>
                  ) : null}
                  <p className="mt-1 font-body text-sm text-kelly-slate">
                    {stamp && jumpHref ? (
                      <a
                        href={jumpHref}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-semibold text-kelly-navy underline-offset-2 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-kelly-gold"
                      >
                        <span aria-hidden>{stamp}</span>
                        <span className="sr-only">
                          Jump to {stamp} on YouTube
                          {seg.speaker ? ` — ${seg.speaker}` : ""}
                        </span>
                      </a>
                    ) : stamp ? (
                      <span className="font-semibold text-kelly-navy">{stamp}</span>
                    ) : null}
                    {seg.speaker ? (
                      <span className="ml-2 font-semibold text-kelly-ink">— {seg.speaker}</span>
                    ) : null}
                  </p>
                  <p className="mt-2 font-body text-base leading-relaxed text-kelly-ink">{seg.text}</p>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="mt-5 max-w-prose space-y-4 font-body text-base leading-relaxed text-kelly-ink whitespace-pre-wrap">
            {transcript.plainText}
          </div>
        )}

        <p className="mt-6">
          <Link
            href={youtubeWatchUrl(media.youtubeVideoId)}
            target="_blank"
            rel="noopener noreferrer"
            className="font-body text-sm font-semibold text-kelly-navy underline-offset-2 hover:underline"
          >
            Open on YouTube
          </Link>
        </p>
      </div>
    </details>
  );
}
