#Requires -Version 5.1
<#
.SYNOPSIS
  Configure NASS_API_KEY via a paste-friendly dialog.
  Values are never printed. Writes gitignored .env in the RCIP worktree.
#>
$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvPath = Join-Path $RepoRoot ".env"
$BackupDir = Join-Path $RepoRoot ".local\temp"

function Test-UsableKey([string]$Value) {
  if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
  $v = $Value.Trim()
  if ($v.Length -lt 8) { return $false }
  if ($v -match '(?i)your_?.*api_?key') { return $false }
  if ($v -match '<.*>') { return $false }
  if ($v -match '(?i)^(changeme|todo|replace|xxx|placeholder)$') { return $false }
  return $true
}

function Read-KeyDialog([string]$Title, [string]$Label) {
  $form = New-Object System.Windows.Forms.Form
  $form.Text = $Title
  $form.Size = New-Object System.Drawing.Size(560, 200)
  $form.StartPosition = "CenterScreen"
  $form.FormBorderStyle = "FixedDialog"
  $form.MaximizeBox = $false
  $form.MinimizeBox = $false
  $form.TopMost = $true

  $lbl = New-Object System.Windows.Forms.Label
  $lbl.Location = New-Object System.Drawing.Point(12, 12)
  $lbl.Size = New-Object System.Drawing.Size(520, 36)
  $lbl.Text = $Label
  $form.Controls.Add($lbl)

  $box = New-Object System.Windows.Forms.TextBox
  $box.Location = New-Object System.Drawing.Point(12, 56)
  $box.Size = New-Object System.Drawing.Size(520, 28)
  $box.UseSystemPasswordChar = $true
  $form.Controls.Add($box)

  $hint = New-Object System.Windows.Forms.Label
  $hint.Location = New-Object System.Drawing.Point(12, 90)
  $hint.Size = New-Object System.Drawing.Size(520, 20)
  $hint.Text = "Ctrl+V to paste, then OK. Key is not shown."
  $form.Controls.Add($hint)

  $ok = New-Object System.Windows.Forms.Button
  $ok.Text = "OK"
  $ok.Location = New-Object System.Drawing.Point(376, 120)
  $ok.Size = New-Object System.Drawing.Size(75, 28)
  $ok.DialogResult = [System.Windows.Forms.DialogResult]::OK
  $form.Controls.Add($ok)
  $form.AcceptButton = $ok

  $cancel = New-Object System.Windows.Forms.Button
  $cancel.Text = "Cancel"
  $cancel.Location = New-Object System.Drawing.Point(457, 120)
  $cancel.Size = New-Object System.Drawing.Size(75, 28)
  $cancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
  $form.Controls.Add($cancel)
  $form.CancelButton = $cancel

  $form.Add_Shown({ $box.Focus() })
  $result = $form.ShowDialog()
  if ($result -ne [System.Windows.Forms.DialogResult]::OK) {
    return $null
  }
  return $box.Text
}

function Set-EnvKey([string]$Content, [string]$Name, [string]$Value) {
  $line = "$Name=$Value"
  $pattern = "(?m)^(?:export\s+)?" + [regex]::Escape($Name) + "\s*="
  if ($Content -match $pattern) {
    $replacePattern = "(?m)^(?:export\s+)?" + [regex]::Escape($Name) + "\s*=.*$"
    return [regex]::Replace($Content, $replacePattern, $line, 1)
  }
  if ([string]::IsNullOrWhiteSpace($Content)) {
    return @(
      "# RCIP public-statistics credentials (gitignored - do not commit)"
      "# Generated by scripts/configure-nass-key.ps1"
      $line
    ) -join "`r`n"
  }
  return ($Content.TrimEnd() + "`r`n" + $line + "`r`n")
}

Write-Host ""
Write-Host "RCIP NASS Quick Stats credential setup" -ForegroundColor Green
Write-Host ("Target file: " + $EnvPath) -ForegroundColor Green
Write-Host "Register at https://quickstats.nass.usda.gov/api if needed." -ForegroundColor DarkGray
Write-Host "Note: API_DOT_GOV_KEY is NOT a Quick Stats substitute." -ForegroundColor DarkGray
Write-Host "A paste-friendly dialog will open (not the Cursor terminal)." -ForegroundColor DarkGray

$nass = Read-KeyDialog "NASS API key" "Paste NASS_API_KEY (from quickstats.nass.usda.gov/api)."
if ($null -eq $nass) {
  Write-Host "Cancelled. Nothing written." -ForegroundColor Yellow
  exit 1
}

if (-not (Test-UsableKey $nass)) {
  Write-Host "ERROR: NASS_API_KEY looks empty or like a placeholder. Nothing written." -ForegroundColor Red
  exit 1
}

$existing = ""
if (Test-Path -LiteralPath $EnvPath) {
  New-Item -ItemType Directory -Force -Path $BackupDir | Out-Null
  $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $backup = Join-Path $BackupDir ("env-backup-before-nass-key-" + $stamp + ".env")
  Copy-Item -LiteralPath $EnvPath -Destination $backup -Force
  $existing = Get-Content -LiteralPath $EnvPath -Raw -ErrorAction Stop
  Write-Host ("Backed up existing .env to: " + $backup) -ForegroundColor DarkGray
}

$next = Set-EnvKey $existing "NASS_API_KEY" $nass.Trim()

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($EnvPath, ($next.TrimEnd() + "`n"), $utf8)

$verify = Get-Content -LiteralPath $EnvPath -Raw
$nassOk = $verify -match '(?m)^NASS_API_KEY=.+'

Write-Host ""
if ($nassOk) {
  Write-Host "OK - key written (presence only):" -ForegroundColor Green
  Write-Host ("  NASS_API_KEY: CONFIGURED (length " + $nass.Trim().Length + ")")
  Write-Host ("  File: " + $EnvPath)
  Write-Host ""
  Write-Host "Close this window and tell the agent the NASS key is set." -ForegroundColor Cyan
  exit 0
}

Write-Host "ERROR: write verification failed." -ForegroundColor Red
exit 1
