#Requires -Version 5.1
<#
.SYNOPSIS
  Configure the RCIP "available keys" batch via paste-friendly dialogs.
  Values are never printed. Writes gitignored .env.

.DESCRIPTION
  Keys:
    GOOGLE_CIVIC_API_KEY
    NEWSAPI_API_KEY
    CONGRESS_GOV_API_KEY
    OPENSTATES_API_KEY
    API_DOT_GOV_KEY
    SOCRATA_APP_TOKEN

  Blank OK keeps the existing .env value for that key.
  Cancel aborts without writing.

.PARAMETER Only
  Optional comma-separated key names to configure.
#>
param(
  [string]$Only = ""
)

$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvPath = Join-Path $RepoRoot ".env"
$BackupDir = Join-Path $RepoRoot ".local\temp"

function Test-UsableKey([string]$Value) {
  if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
  $v = $Value.Trim()
  if ($v.Length -lt 8) { return $false }
  if ($v -match '(?i)your_?.*api_?key') { return $false }
  if ($v -match '<.*>') { return $false }
  if ($v -match '(?i)^(changeme|todo|replace|xxx|placeholder)$') { return $false }
  return $true
}

function Read-KeyDialog([string]$Title, [string]$Label) {
  $form = New-Object System.Windows.Forms.Form
  $form.Text = $Title
  $form.Size = New-Object System.Drawing.Size(560, 240)
  $form.StartPosition = "CenterScreen"
  $form.FormBorderStyle = "FixedDialog"
  $form.MaximizeBox = $false
  $form.MinimizeBox = $false
  $form.TopMost = $true

  $lbl = New-Object System.Windows.Forms.Label
  $lbl.Location = New-Object System.Drawing.Point(12, 12)
  $lbl.Size = New-Object System.Drawing.Size(520, 60)
  $lbl.Text = $Label
  $form.Controls.Add($lbl)

  $box = New-Object System.Windows.Forms.TextBox
  $box.Location = New-Object System.Drawing.Point(12, 80)
  $box.Size = New-Object System.Drawing.Size(520, 28)
  $box.UseSystemPasswordChar = $true
  $form.Controls.Add($box)

  $hint = New-Object System.Windows.Forms.Label
  $hint.Location = New-Object System.Drawing.Point(12, 116)
  $hint.Size = New-Object System.Drawing.Size(520, 20)
  $hint.Text = "Ctrl+V to paste, then OK. Blank OK = skip. Cancel aborts."
  $form.Controls.Add($hint)

  $ok = New-Object System.Windows.Forms.Button
  $ok.Text = "OK"
  $ok.Location = New-Object System.Drawing.Point(376, 156)
  $ok.Size = New-Object System.Drawing.Size(75, 28)
  $ok.DialogResult = [System.Windows.Forms.DialogResult]::OK
  $form.Controls.Add($ok)
  $form.AcceptButton = $ok

  $cancel = New-Object System.Windows.Forms.Button
  $cancel.Text = "Cancel"
  $cancel.Location = New-Object System.Drawing.Point(457, 156)
  $cancel.Size = New-Object System.Drawing.Size(75, 28)
  $cancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
  $form.Controls.Add($cancel)
  $form.CancelButton = $cancel

  $form.Add_Shown({ $box.Focus() })
  $result = $form.ShowDialog()
  if ($result -ne [System.Windows.Forms.DialogResult]::OK) {
    return $null
  }
  return $box.Text
}

function Set-EnvKey([string]$Content, [string]$Name, [string]$Value) {
  $line = "$Name=$Value"
  $pattern = "(?m)^(?:export\s+)?" + [regex]::Escape($Name) + "\s*="
  if ($Content -match $pattern) {
    $replacePattern = "(?m)^(?:export\s+)?" + [regex]::Escape($Name) + "\s*=.*$"
    return [regex]::Replace($Content, $replacePattern, $line, 1)
  }
  if ([string]::IsNullOrWhiteSpace($Content)) {
    return @(
      "# RCIP credentials (gitignored - do not commit)"
      "# Generated by scripts/configure-available-api-keys.ps1"
      $line
    ) -join "`r`n"
  }
  return ($Content.TrimEnd() + "`r`n" + $line + "`r`n")
}

Write-Host ""
Write-Host "RCIP available API key batch setup" -ForegroundColor Green
Write-Host ("Target file: " + $EnvPath) -ForegroundColor Green
Write-Host "A paste-friendly dialog will open for each key (not the Cursor terminal)." -ForegroundColor DarkGray
Write-Host "Note: API_DOT_GOV_KEY is NOT a Census or NASS Quick Stats substitute." -ForegroundColor Yellow

$allSpecs = @(
  @{
    Name = "GOOGLE_CIVIC_API_KEY"
    Title = "Google Civic API key"
    Label = "Paste GOOGLE_CIVIC_API_KEY (Google Civic Information). Blank OK keeps existing."
  },
  @{
    Name = "NEWSAPI_API_KEY"
    Title = "NewsAPI key"
    Label = "Paste NEWSAPI_API_KEY (newsapi.org). Blank OK keeps existing."
  },
  @{
    Name = "CONGRESS_GOV_API_KEY"
    Title = "Congress.gov API key"
    Label = "Paste CONGRESS_GOV_API_KEY (api.congress.gov). Blank OK keeps existing."
  },
  @{
    Name = "OPENSTATES_API_KEY"
    Title = "Open States API key"
    Label = "Paste OPENSTATES_API_KEY (v3.openstates.org). Blank OK keeps existing."
  },
  @{
    Name = "API_DOT_GOV_KEY"
    Title = "api.data.gov key"
    Label = "Paste API_DOT_GOV_KEY (api.data.gov). NOT Census/NASS. Blank OK keeps existing."
  },
  @{
    Name = "SOCRATA_APP_TOKEN"
    Title = "Socrata app token"
    Label = "Paste SOCRATA_APP_TOKEN (Socrata / open-data portals). Blank OK keeps existing."
  }
)

$filter = @()
if (-not [string]::IsNullOrWhiteSpace($Only)) {
  $filter = $Only.Split(",") | ForEach-Object { $_.Trim().ToUpperInvariant() } | Where-Object { $_ }
}
$specs = @()
foreach ($spec in $allSpecs) {
  if ($filter.Count -eq 0 -or ($filter -contains $spec.Name)) {
    $specs += $spec
  }
}
if ($specs.Count -eq 0) {
  Write-Host "ERROR: -Only filter matched no keys." -ForegroundColor Red
  exit 1
}

$collected = @{}
$skipped = @()
foreach ($spec in $specs) {
  $raw = Read-KeyDialog $spec.Title $spec.Label
  if ($null -eq $raw) {
    Write-Host ("Cancelled at " + $spec.Name + ". Nothing written.") -ForegroundColor Yellow
    exit 1
  }
  if ([string]::IsNullOrWhiteSpace($raw)) {
    $skipped += $spec.Name
    Write-Host ("  skip " + $spec.Name + " (keep existing)") -ForegroundColor DarkGray
    continue
  }
  if (-not (Test-UsableKey $raw)) {
    Write-Host ("ERROR: " + $spec.Name + " looks empty or like a placeholder. Nothing written.") -ForegroundColor Red
    exit 1
  }
  $collected[$spec.Name] = $raw.Trim()
}

if ($collected.Count -eq 0) {
  Write-Host "No new keys provided. Existing values left unchanged." -ForegroundColor Yellow
  Write-Host "Next: npm run credentials:probe-available" -ForegroundColor Cyan
  exit 0
}

$existing = ""
if (Test-Path -LiteralPath $EnvPath) {
  New-Item -ItemType Directory -Force -Path $BackupDir | Out-Null
  $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
  $backup = Join-Path $BackupDir ("env-backup-before-available-api-keys-" + $stamp + ".env")
  Copy-Item -LiteralPath $EnvPath -Destination $backup -Force
  $existing = Get-Content -LiteralPath $EnvPath -Raw -ErrorAction Stop
  Write-Host ("Backed up existing .env to: " + $backup) -ForegroundColor DarkGray
}

$next = $existing
foreach ($name in $collected.Keys) {
  $next = Set-EnvKey $next $name $collected[$name]
}

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($EnvPath, ($next.TrimEnd() + "`n"), $utf8)

$verify = Get-Content -LiteralPath $EnvPath -Raw
$allOk = $true
Write-Host ""
Write-Host "OK - keys written (presence only):" -ForegroundColor Green
foreach ($name in $collected.Keys) {
  $present = $verify -match ("(?m)^" + [regex]::Escape($name) + "=.+")
  if (-not $present) { $allOk = $false }
  Write-Host ("  " + $name + ": CONFIGURED (length " + $collected[$name].Length + ")")
}
foreach ($name in $skipped) {
  Write-Host ("  " + $name + ": SKIPPED")
}
Write-Host ("  File: " + $EnvPath)
Write-Host ""
Write-Host "Next: npm run credentials:probe-available" -ForegroundColor Cyan

if (-not $allOk) {
  Write-Host "ERROR: write verification failed." -ForegroundColor Red
  exit 1
}
exit 0
