/**
 * Smoke: Pass 8 transcript intelligence (chapters/quotes/claims/do-not-claim).
 * From RedDirt:
 *   node scripts/run-with-h-drive-env.cjs npx --yes tsx scripts/smoke-transcript-intelligence.ts
 */
import Module from "node:module";

const originalLoad = (Module as unknown as { _load: (...args: unknown[]) => unknown })._load;
(Module as unknown as { _load: (...args: unknown[]) => unknown })._load = function (...args: unknown[]) {
  const request = String(args[0] ?? "");
  const normalized = request.replace(/\\/g, "/");
  if (
    request === "server-only" ||
    normalized.includes("/server-only/") ||
    normalized.endsWith("/server-only")
  ) {
    return {};
  }
  return originalLoad.apply(this, args);
};

async function main() {
  const {
    analyzeTranscriptIntelligence,
    applyTranscriptIntelToOverlay,
  } = await import("../src/lib/campaign-media/transcript-intelligence");

  const plain = [
    "Friends, Arkansas deserves an elections office that protects the ballot.",
    "In Pulaski County we heard clerks ask for clearer guidance on early voting.",
    "My opponent claims we will cut access — that is not what this campaign is about.",
    "We will train county clerks, publish plain-language guidance, and track errors at 12% reduction targets only after verification.",
    "Voting should be secure and accessible for every eligible Arkansan.",
  ].join(" ");

  const segments = plain.split(/(?<=[.!?])\s+/).map((text, i) => ({
    id: `s${i}`,
    text,
    startSeconds: i * 95,
    endSeconds: i * 95 + 12,
  }));

  const result = analyzeTranscriptIntelligence({
    youtubeVideoId: "smoke-pass8-yt",
    speechId: "smoke-pass8-speech",
    isAutoGeneratedOverride: true,
    plainTextOverride: plain,
    segmentsOverride: segments,
    chaptersOverride: [{ id: "c1", title: "Ballot integrity", startSeconds: 0 }],
    overlay: { counties: ["Polk"], city: "Mena" },
  });

  if (!result.ok) {
    console.error("FAIL: analyze", result.error);
    process.exit(1);
  }
  const p = result.proposal;
  if (!p.chapters.length || !p.quotes.length || !p.doNotClaim.length) {
    console.error("FAIL: expected chapters/quotes/doNotClaim", p);
    process.exit(1);
  }
  if (!p.doNotClaim.some((d) => /auto-generated/i.test(d))) {
    console.error("FAIL: missing auto-generated guardrail", p.doNotClaim);
    process.exit(1);
  }
  if (!p.doNotClaim.some((d) => /Pulaski/i.test(d))) {
    console.error("FAIL: should warn unverified Pulaski County", p.doNotClaim);
    process.exit(1);
  }

  const applied = applyTranscriptIntelToOverlay({
    overlay: { counties: ["Polk"], city: "Mena" },
    proposal: p,
    applyFields: ["whatThisProves", "keyQuotes", "doNotClaim", "transcriptChapters"],
  });
  if (!applied.keyQuotes?.length || !applied.doNotClaim?.length || !applied.transcriptChapters?.length) {
    console.error("FAIL: apply", applied);
    process.exit(1);
  }

  console.log(
    JSON.stringify(
      {
        ok: true,
        chapters: p.chapters.length,
        quotes: p.quotes.length,
        claims: p.claimCandidates.length,
        doNotClaim: p.doNotClaim.length,
        appliedQuotes: applied.keyQuotes.length,
      },
      null,
      2,
    ),
  );
  console.log("OK smoke-transcript-intelligence");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
