/**
 * Pass 2 focused tests — YouTube transcript ingestion pipeline (no live API calls).
 * Run: npm run agents:test-campaign-video-transcripts-pass2
 */

import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import {
  normalizeCaptionToTranscript,
  parseCaptionFileToSegments,
  segmentsToSrt,
} from "../src/lib/media/youtube-transcripts/normalize-transcript";
import { flagProperNouns } from "../src/lib/media/youtube-transcripts/proper-noun-flags";
import {
  emptyWorkspace,
  saveWorkspaceRecord,
  loadWorkspaceRecord,
  restoreRevision,
} from "../src/lib/media/youtube-transcripts/workspace-store";
import { publishWorkspaceTranscript } from "../src/lib/media/youtube-transcripts/publish-overlay-fs";
import { buildTranscriptSearchIndex, searchTranscriptIndex } from "../src/lib/media/youtube-transcripts/search-index";
import { sealYouTubeTokenPayload, openYouTubeTokenPayload } from "../src/lib/media/youtube-transcripts/token-crypto";
import { pickPreferredCaptionTrack } from "../src/lib/media/youtube-transcripts/captions-api";
import { isPublicTranscript } from "../src/lib/media/campaign-transcript";
import type { CampaignMediaRecord } from "../src/content/media/campaign-media-types";
import { emptyTranscript } from "../src/lib/media/campaign-transcript";
import { assertCampaignMediaRegistryInvariants } from "../src/content/media/campaign-media-registry";

function section(name: string) {
  console.log(`\n== ${name} ==`);
}

section("registry still valid");
assertCampaignMediaRegistryInvariants();

section("vtt normalize");
const vtt = `WEBVTT

00:00:00.000 --> 00:00:02.000
Thank you for inviting me.

00:00:02.200 --> 00:00:05.000
The Secretary of State's office belongs to the people.
`;
const parsed = normalizeCaptionToTranscript(vtt);
assert.ok(parsed.plainText.includes("Secretary of State"));
assert.ok(parsed.segments.length >= 1);
assert.ok(parseCaptionFileToSegments(vtt).length >= 1);
const srt = segmentsToSrt(parsed.segments);
assert.ok(srt.includes("-->"));

section("proper noun flags");
const flags = flagProperNouns(parsed.plainText);
assert.ok(flags.some((f) => /Secretary of State/i.test(f.term) || f.category === "OFFICE"));

section("caption track preference");
const preferred = pickPreferredCaptionTrack([
  {
    id: "auto",
    videoId: "x",
    language: "en",
    name: "",
    trackKind: "asr",
    isAutoGenerated: true,
    isDraft: false,
  },
  {
    id: "creator",
    videoId: "x",
    language: "en",
    name: "English",
    trackKind: "standard",
    isAutoGenerated: false,
    isDraft: false,
  },
]);
assert.equal(preferred?.id, "creator");

section("workspace versioning + never auto publish");
const tmp = mkdtempSync(path.join(os.tmpdir(), "yt-transcript-"));
process.env.YOUTUBE_TOKEN_ENCRYPTION_KEY = "test-pass2-encryption-key-not-real";
try {
  let ws = emptyWorkspace("testVideoIdPass2", "Fixture video");
  ws = saveWorkspaceRecord(
    {
      ...ws,
      status: "REVIEW_REQUIRED",
      source: "YOUTUBE_AUTOMATIC_CAPTIONS",
      plainText: "Fixture draft only — not Kelly speech.",
      segments: [{ id: "seg-1", text: "Fixture draft only — not Kelly speech.", startSeconds: 0 }],
      isAutoGenerated: true,
    },
    { author: "test", reason: "initial draft" },
    tmp,
  );
  assert.equal(ws.revisions.length, 1);
  assert.equal(ws.status, "REVIEW_REQUIRED");

  assert.throws(() => publishWorkspaceTranscript(ws, "test", tmp));

  ws = saveWorkspaceRecord(
    { ...ws, status: "APPROVED", approvedAt: new Date().toISOString(), approvedBy: "test" },
    { author: "test", reason: "approved" },
    tmp,
  );
  const published = publishWorkspaceTranscript(ws, "test", tmp);
  assert.equal(published.status, "PUBLISHED");

  const reloaded = loadWorkspaceRecord("testVideoIdPass2", tmp);
  assert.ok(reloaded);
  const restored = restoreRevision("testVideoIdPass2", reloaded!.revisions[0]!.revisionId, "test", tmp);
  assert.equal(restored.status, "DRAFT");

  section("token seal roundtrip");
  const sealed = sealYouTubeTokenPayload(JSON.stringify({ refresh_token: "rt-test", access_token: "at-test" }));
  const opened = JSON.parse(openYouTubeTokenPayload(sealed)) as { refresh_token: string };
  assert.equal(opened.refresh_token, "rt-test");
} finally {
  rmSync(tmp, { recursive: true, force: true });
}

section("public gate still requires PUBLISHED media + transcript");
const media: CampaignMediaRecord = {
  id: "x",
  slug: "x",
  provider: "YOUTUBE",
  youtubeVideoId: "x",
  format: "FULL_VIDEO",
  title: "X",
  description: "X",
  topics: [],
  relatedPagePaths: [],
  featured: false,
  homepageEligible: false,
  publicationStatus: "PUBLISHED",
  transcript: {
    ...emptyTranscript(),
    status: "REVIEW_REQUIRED",
    plainText: "secret draft",
    segments: [{ id: "1", text: "secret draft" }],
  },
};
assert.equal(isPublicTranscript(media), false);

section("search index ignores empty");
const index = buildTranscriptSearchIndex([]);
assert.equal(searchTranscriptIndex(index, { q: "arkansas" }).length, 0);

console.log("\nAll campaign video transcript Pass 2 checks passed.");
