import type { EventItem, EventType } from "@/content/types";

const TZ = "America/Chicago";
const DETAILS_LATER =
  "Confirmed on the August campaign timeline. Venue, program, and how to join will be posted here when the host confirms them. All times are U.S. Central.";

type StopDraft = {
  slug: string;
  title: string;
  type: EventType;
  region: string;
  countySlug?: string;
  startsAt: string;
  endsAt?: string;
  timeTbd?: boolean;
  locationLabel: string;
  city?: string;
  addressLine?: string;
  summary: string;
  description?: string;
  whatToExpect?: string[];
  whoItsFor?: string;
  organizerNote?: string;
  attendanceType?: EventItem["attendanceType"];
  audienceTags: string[];
  mapCoordinates?: { lat: number; lng: number };
  mapPinQuality?: EventItem["mapPinQuality"];
  relatedEventSlugs: string[];
};

function campaignStop(draft: StopDraft): EventItem {
  const date = draft.startsAt.slice(0, 10);
  return {
    slug: draft.slug,
    title: draft.title,
    type: draft.type,
    region: draft.region,
    countySlug: draft.countySlug,
    status: "upcoming",
    startsAt: draft.startsAt,
    endsAt: draft.endsAt ?? (draft.timeTbd ? `${date}T23:59:00` : undefined),
    timezone: TZ,
    locationLabel: draft.locationLabel,
    city: draft.city ?? draft.locationLabel,
    addressLine: draft.addressLine,
    summary: draft.summary,
    description: draft.description ?? DETAILS_LATER,
    whatToExpect: draft.whatToExpect ?? [
      "Stop details will be added when the host confirms venue and program.",
    ],
    whoItsFor: draft.whoItsFor ?? "Neighbors, volunteers, and anyone who wants to meet the campaign on the trail.",
    organizerNote:
      draft.organizerNote ?? "August 2026 campaign timeline — public facts only; details to be added.",
    attendanceType: draft.attendanceType,
    audienceTags: draft.audienceTags,
    relatedEventSlugs: draft.relatedEventSlugs,
    relatedResourceHrefs: [
      { label: "Events calendar", href: "/events" },
      { label: "Get involved", href: "/get-involved" },
    ],
    mapCoordinates: draft.mapCoordinates,
    mapPinQuality: draft.mapPinQuality,
    fieldAttendance: "confirmed",
    campaignTrail: true,
    eventSource: "movement",
    opsFlags: {
      timeTbd: draft.timeTbd,
      missingCounty: !draft.countySlug,
      missingCoordinates: !draft.mapCoordinates,
    },
  };
}

/** Confirmed public campaign stops for August 2026. Travel-only days are not listed. */
export const august2026CampaignStops: EventItem[] = [
  campaignStop({
    slug: "pocahontas-breakfast-meet-greet-2026-08-15",
    title: "Breakfast meet & greet — Pocahontas",
    type: "Community Conversation",
    region: "Northeast Arkansas",
    countySlug: "randolph-county",
    startsAt: "2026-08-15T09:00:00",
    endsAt: "2026-08-15T11:00:00",
    locationLabel: "Pocahontas",
    addressLine: "Pocahontas, AR (venue TBA)",
    summary: "Saturday morning meet & greet in Pocahontas. Venue to be posted.",
    audienceTags: ["Pocahontas", "Randolph County", "Northeast Arkansas"],
    mapCoordinates: { lat: 36.2615, lng: -90.9712 },
    relatedEventSlugs: ["horseshoe-bend-fundraiser-2026-08-15"],
  }),
  campaignStop({
    slug: "horseshoe-bend-fundraiser-2026-08-15",
    title: "Fundraiser — Horseshoe Bend",
    type: "Community Conversation",
    region: "North Central Arkansas",
    countySlug: "izard-county",
    startsAt: "2026-08-15T14:00:00",
    endsAt: "2026-08-15T16:00:00",
    locationLabel: "Horseshoe Bend",
    addressLine: "Horseshoe Bend, AR (venue TBA)",
    summary: "Saturday afternoon fundraiser in Horseshoe Bend. Venue and ticket details to be posted.",
    audienceTags: ["Horseshoe Bend", "Izard County", "Fundraiser"],
    mapCoordinates: { lat: 36.229, lng: -91.764 },
    relatedEventSlugs: ["pocahontas-breakfast-meet-greet-2026-08-15"],
  }),
  campaignStop({
    slug: "saline-county-josh-irby-2026-08-16",
    title: "Saline County event with Josh Irby",
    type: "Community Conversation",
    region: "Central Arkansas",
    countySlug: "saline-county",
    startsAt: "2026-08-16T11:00:00",
    timeTbd: true,
    locationLabel: "Saline County (venue TBA)",
    addressLine: "Saline County, AR",
    summary: "Confirmed Saline County stop with Josh Irby. Time and venue to be posted.",
    audienceTags: ["Saline County", "Central Arkansas"],
    mapCoordinates: { lat: 34.5645, lng: -92.5868 },
    relatedEventSlugs: ["fundraiser-dr-kahn-2026-08-16"],
  }),
  campaignStop({
    slug: "fundraiser-dr-kahn-2026-08-16",
    title: "Fundraiser with Dr. Kahn",
    type: "Community Conversation",
    region: "Central Arkansas",
    startsAt: "2026-08-16T14:00:00",
    timeTbd: true,
    locationLabel: "Venue TBA — confirm with host",
    summary: "Confirmed fundraiser with Dr. Kahn the same day as the Saline County stop. City and time to be posted.",
    audienceTags: ["Fundraiser"],
    relatedEventSlugs: ["saline-county-josh-irby-2026-08-16"],
  }),
  campaignStop({
    slug: "washington-county-democrats-2026-08-17",
    title: "Washington County Democrats meeting",
    type: "Community Conversation",
    region: "Northwest Arkansas",
    countySlug: "washington-county",
    startsAt: "2026-08-17T12:00:00",
    timeTbd: true,
    locationLabel: "Washington County (venue TBA)",
    addressLine: "Washington County, AR",
    summary: "Confirmed Washington County Democrats meeting. Time, format, and room to be posted.",
    audienceTags: ["Democratic Party", "Washington County", "Fayetteville"],
    mapCoordinates: { lat: 36.0626, lng: -94.1574 },
    relatedEventSlugs: ["nwa-senior-democrats-fayetteville-2026-08-18"],
  }),
  campaignStop({
    slug: "nwa-senior-democrats-fayetteville-2026-08-18",
    title: "NWA Senior Democrats meeting — Fayetteville",
    type: "Community Conversation",
    region: "Northwest Arkansas",
    countySlug: "washington-county",
    startsAt: "2026-08-18T12:00:00",
    endsAt: "2026-08-18T13:00:00",
    locationLabel: "Butterfield Trail Village Lodge",
    city: "Fayetteville",
    addressLine: "1923 E. Joyce Blvd., Fayetteville, AR 72703",
    summary:
      "Tuesday at noon. Kelly will speak at the Northwest Arkansas Senior Democrats meeting at Butterfield Trail Village Lodge in Fayetteville.",
    description:
      "The Northwest Arkansas Senior Democrats meet at the Butterfield Trail Village Lodge in Fayetteville, off Joyce Boulevard. The meeting starts at noon. Members often arrive around 11:30 a.m. to eat and socialize; remarks usually begin around 12:20 p.m., and the meeting ends at 1:00 p.m. Parking is in front of the Lodge and on streets inside the Village — do not park on the mailbox side of the street. Look first for the EV charging station in front of the Lodge.",
    whatToExpect: [
      "Noon meeting at Butterfield Trail Village Lodge, with social time from about 11:30 a.m.",
      "Kelly speaks during the noon program; please leave time for questions.",
      "Park in front of the Lodge or on Village streets — not on the mailbox side. Look for the EV charging station out front.",
      "The meeting wraps at 1:00 p.m.",
    ],
    whoItsFor: "Members of the Northwest Arkansas Senior Democrats and guests at their monthly meeting.",
    organizerNote: "Confirmed with the host for Tuesday, August 18, 2026. Public venue and schedule only.",
    attendanceType: "CAMPAIGN_APPEARANCE",
    audienceTags: ["Democratic Party", "Washington County", "Fayetteville", "Northwest Arkansas"],
    mapCoordinates: { lat: 36.0994, lng: -94.1368 },
    mapPinQuality: "exact",
    relatedEventSlugs: ["washington-county-democrats-2026-08-17"],
  }),
  campaignStop({
    slug: "dumas-regional-meeting-2026-08-21",
    title: "Regional meeting — Dumas",
    type: "Community Conversation",
    region: "Lower Delta",
    countySlug: "desha-county",
    startsAt: "2026-08-21T17:00:00",
    locationLabel: "Dumas",
    addressLine: "Dumas, AR (venue TBA)",
    summary: "Friday 5:00 p.m. Central regional meeting in Dumas. Venue to be posted.",
    audienceTags: ["Dumas", "Desha County", "Lower Delta"],
    mapCoordinates: { lat: 33.887, lng: -91.4918 },
    relatedEventSlugs: ["coffee-with-kelly-searcy-2026-08-22"],
  }),
  campaignStop({
    slug: "coffee-with-kelly-searcy-2026-08-22",
    title: "Coffee with Kelly — Searcy",
    type: "Community Conversation",
    region: "North Central Arkansas",
    countySlug: "white-county",
    startsAt: "2026-08-22T10:30:00",
    endsAt: "2026-08-22T11:30:00",
    locationLabel: "Janet & Larry Crain Memorial Library",
    city: "Searcy",
    addressLine: "1609 W Beebe Capps Expressway, Searcy, AR",
    summary:
      "Saturday 10:30–11:30 a.m. Central. Drop by and meet Kelly Grappe, candidate for Secretary of State.",
    description:
      "Drop by and meet Kelly Grappe, candidate for Secretary of State. Coffee with Kelly is Saturday, August 22, 2026, from 10:30 to 11:30 a.m. Central at the Janet & Larry Crain Memorial Library, 1609 W Beebe Capps Expressway, Searcy.",
    whatToExpect: [
      "Drop by anytime between 10:30 and 11:30 a.m. Central — no RSVP required.",
      "Janet & Larry Crain Memorial Library, 1609 W Beebe Capps Expressway, Searcy.",
      "Meet Kelly Grappe, candidate for Arkansas Secretary of State.",
    ],
    whoItsFor: "Neighbors in Searcy and White County — come say hello.",
    organizerNote: "Posted from the campaign Coffee with Kelly flyer. Paid for by the Committee to Elect Kelly Grappe.",
    attendanceType: "PUBLIC_OPEN",
    audienceTags: ["Searcy", "White County", "Coffee with Kelly"],
    mapCoordinates: { lat: 35.2478, lng: -91.7612 },
    mapPinQuality: "exact",
    relatedEventSlugs: ["mccrory-fair-rodeo-2026-08-22"],
  }),
  campaignStop({
    slug: "mccrory-fair-rodeo-2026-08-22",
    title: "McCrory Fair & Rodeo",
    type: "Fairs and Festivals",
    region: "Upper Delta",
    countySlug: "woodruff-county",
    startsAt: "2026-08-22T17:00:00",
    locationLabel: "McCrory",
    addressLine: "McCrory, AR (fairgrounds / host site TBA)",
    summary: "Saturday 5:00 p.m. Central at the McCrory Fair & Rodeo. Exact table or staging spot to be posted.",
    audienceTags: ["McCrory", "Woodruff County", "Festival"],
    mapCoordinates: { lat: 35.2565, lng: -91.1998 },
    relatedEventSlugs: ["coffee-with-kelly-searcy-2026-08-22"],
  }),
  campaignStop({
    slug: "paragould-campaign-activities-2026-08-25",
    title: "Campaign activities — Paragould",
    type: "Community Conversation",
    region: "Northeast Arkansas",
    countySlug: "greene-county",
    startsAt: "2026-08-25T12:00:00",
    timeTbd: true,
    locationLabel: "Paragould",
    addressLine: "Paragould, AR (schedule TBA)",
    summary: "Confirmed campaign activities in Paragould. Public stops that day will be posted as they are confirmed.",
    audienceTags: ["Paragould", "Greene County", "Northeast Arkansas"],
    mapCoordinates: { lat: 36.0584, lng: -90.4973 },
    relatedEventSlugs: ["paragould-rotary-lunch-2026-08-26", "asu-back-to-school-2026-08-26"],
  }),
  campaignStop({
    slug: "paragould-rotary-lunch-2026-08-26",
    title: "Rotary Club lunch — Paragould",
    type: "Community Conversation",
    region: "Northeast Arkansas",
    countySlug: "greene-county",
    startsAt: "2026-08-26T12:00:00",
    timeTbd: true,
    locationLabel: "Paragould",
    addressLine: "Paragould, AR (Rotary meeting site TBA)",
    summary: "Confirmed Rotary Club lunch in Paragould. Start time and room to be posted.",
    audienceTags: ["Paragould", "Greene County", "Rotary"],
    mapCoordinates: { lat: 36.0584, lng: -90.4973 },
    relatedEventSlugs: ["asu-back-to-school-2026-08-26", "paragould-campaign-activities-2026-08-25"],
  }),
  campaignStop({
    slug: "asu-back-to-school-2026-08-26",
    title: "Back-to-school event — Arkansas State University",
    type: "Youth Civic Session",
    region: "Northeast Arkansas",
    countySlug: "craighead-county",
    startsAt: "2026-08-26T15:00:00",
    timeTbd: true,
    locationLabel: "Arkansas State University — Jonesboro",
    addressLine: "Jonesboro, AR (campus site TBA)",
    summary: "Confirmed back-to-school event at Arkansas State University. Time and campus location to be posted.",
    audienceTags: ["Youth", "Jonesboro", "Craighead County", "ASU"],
    mapCoordinates: { lat: 35.8423, lng: -90.6795 },
    relatedEventSlugs: ["paragould-rotary-lunch-2026-08-26"],
  }),
  campaignStop({
    slug: "logan-county-democrats-paris-2026-08-27",
    title: "Logan County Democrats — Paris",
    type: "Community Conversation",
    region: "Northwest Arkansas",
    countySlug: "logan-county",
    startsAt: "2026-08-27T18:00:00",
    locationLabel: "Paris, Arkansas",
    addressLine: "Paris, AR (venue TBA)",
    summary: "Thursday 6:00 p.m. Central Logan County Democrats meeting in Paris. Venue to be posted.",
    audienceTags: ["Democratic Party", "Logan County", "Paris"],
    mapCoordinates: { lat: 35.292, lng: -93.7224 },
    relatedEventSlugs: ["arkansas-youth-coalition-retreat-2026-08-28"],
  }),
  campaignStop({
    slug: "arkansas-youth-coalition-retreat-2026-08-28",
    title: "Arkansas Youth Coalition Retreat",
    type: "Youth Civic Session",
    region: "North Central Arkansas",
    countySlug: "yell-county",
    startsAt: "2026-08-28T19:00:00",
    locationLabel: "Mount Nebo",
    addressLine: "Mount Nebo, AR (retreat site TBA)",
    summary: "Friday 7:00 p.m. Central Arkansas Youth Coalition Retreat at Mount Nebo. Site details to be posted.",
    audienceTags: ["Youth", "Mount Nebo", "Yell County"],
    mapCoordinates: { lat: 35.2146, lng: -93.2518 },
    relatedEventSlugs: ["chickin-n-politikin-mount-nebo-2026-08-29"],
  }),
  campaignStop({
    slug: "chickin-n-politikin-mount-nebo-2026-08-29",
    title: "Chickin’ N Politikin’ — Mount Nebo",
    type: "Community Conversation",
    region: "North Central Arkansas",
    countySlug: "yell-county",
    startsAt: "2026-08-29T12:00:00",
    timeTbd: true,
    locationLabel: "Mount Nebo",
    addressLine: "Mount Nebo, AR (venue TBA)",
    summary: "Confirmed Chickin’ N Politikin’ gathering at Mount Nebo. Time and site to be posted.",
    audienceTags: ["Mount Nebo", "Yell County"],
    mapCoordinates: { lat: 35.2146, lng: -93.2518 },
    relatedEventSlugs: ["arkansas-youth-coalition-retreat-2026-08-28", "quendy-event-scott-2026-08-30"],
  }),
  campaignStop({
    slug: "quendy-event-scott-2026-08-30",
    title: "Quendy event — Scott",
    type: "Community Conversation",
    region: "Central Arkansas",
    countySlug: "pulaski-county",
    startsAt: "2026-08-30T16:30:00",
    endsAt: "2026-08-30T17:30:00",
    locationLabel: "Scott",
    city: "Scott",
    addressLine: "Scott, AR (venue TBA)",
    summary: "Sunday 4:30–5:30 p.m. Central gathering in Scott. Exact site to be posted.",
    description:
      "Confirmed on Kelly’s calendar for Sunday, August 30, 2026, from 4:30 to 5:30 p.m. Central in Scott. The street address and how to join will be posted here when the host confirms them.",
    whatToExpect: [
      "4:30–5:30 p.m. Central on Sunday, August 30.",
      "Scott, Arkansas — exact site to be posted.",
    ],
    whoItsFor: "Neighbors and supporters gathering in Scott.",
    organizerNote: "Confirmed calendar hold. Venue details to be added when the host confirms them. No virtual join link on the public page.",
    attendanceType: "CAMPAIGN_APPEARANCE",
    audienceTags: ["Scott", "Pulaski County", "Central Arkansas"],
    mapCoordinates: { lat: 34.6965, lng: -92.0943 },
    relatedEventSlugs: ["chickin-n-politikin-mount-nebo-2026-08-29", "political-animals-fayetteville-2026-08-31"],
  }),
  campaignStop({
    slug: "political-animals-fayetteville-2026-08-31",
    title: "Political Animals — Fayetteville",
    type: "Community Conversation",
    region: "Northwest Arkansas",
    countySlug: "washington-county",
    startsAt: "2026-08-31T18:00:00",
    locationLabel: "Fayetteville",
    addressLine: "Fayetteville, AR (venue TBA)",
    summary: "Monday 6:00 p.m. Central Political Animals in Fayetteville. Venue to be posted.",
    audienceTags: ["Fayetteville", "Washington County", "Northwest Arkansas"],
    mapCoordinates: { lat: 36.0626, lng: -94.1574 },
    relatedEventSlugs: ["quendy-event-scott-2026-08-30"],
  }),
];

/** Public route context only — travel days are not event pages. */
export const AUGUST_2026_CAMPAIGN_ROUTE: Array<{ date: string; line: string }> = [
  { date: "Aug. 15", line: "Pocahontas → Horseshoe Bend" },
  { date: "Aug. 16", line: "Saline County → Fayetteville" },
  { date: "Aug. 17", line: "Washington County" },
  { date: "Aug. 18", line: "Fayetteville" },
  { date: "Aug. 19", line: "Little Rock" },
  { date: "Aug. 20", line: "→ Dumas" },
  { date: "Aug. 21", line: "Dumas → Rose Bud" },
  { date: "Aug. 22", line: "Searcy → McCrory" },
  { date: "Aug. 23", line: "Open" },
  { date: "Aug. 24", line: "→ Paragould" },
  { date: "Aug. 25", line: "Paragould" },
  { date: "Aug. 26", line: "Paragould → ASU / Jonesboro area" },
  { date: "Aug. 27", line: "Paris" },
  { date: "Aug. 28", line: "→ Mount Nebo" },
  { date: "Aug. 29", line: "Mount Nebo" },
  { date: "Aug. 30", line: "Scott" },
  { date: "Aug. 31", line: "Fayetteville" },
];
