import type { EventItem, EventType } from "@/content/types";
import { getMovementRegionForCountySlug, STATEWIDE_EVENT_REGION } from "@/content/arkansas-movement-regions";

const TZ = "America/Chicago";
const DETAILS_LATER =
  "Restored to the public calendar after the September 3–5 unpublished-card cuts. Venue, program, and how to join will be added when the host confirms them. All times are U.S. Central.";

type StopDraft = {
  slug: string;
  title: string;
  type: EventType;
  region?: string;
  countySlug?: string;
  startsAt: string;
  endsAt?: string;
  timeTbd?: boolean;
  locationLabel: string;
  addressLine?: string;
  city?: string;
  summary: string;
  description?: string;
  whatToExpect?: string[];
  audienceTags: string[];
  mapCoordinates?: { lat: number; lng: number };
  relatedEventSlugs: string[];
  relatedResourceHrefs?: Array<{ label: string; href: string }>;
  primaryHref?: string;
  primaryCtaLabel?: string;
  fieldAttendance?: "confirmed" | "tentative";
  whoItsFor?: string;
  organizerNote?: string;
  attendanceType?: EventItem["attendanceType"];
  statewideVirtual?: boolean;
  mapPinQuality?: EventItem["mapPinQuality"];
};

function campaignStop(draft: StopDraft): EventItem {
  const date = draft.startsAt.slice(0, 10);
  const tentative = draft.fieldAttendance !== "confirmed";
  const countySlug = draft.countySlug;
  return {
    slug: draft.slug,
    title: draft.title,
    type: draft.type,
    region: draft.region ?? (countySlug ? getMovementRegionForCountySlug(countySlug) ?? STATEWIDE_EVENT_REGION : STATEWIDE_EVENT_REGION),
    countySlug,
    status: "upcoming",
    startsAt: draft.startsAt,
    endsAt: draft.endsAt ?? (draft.timeTbd ? `${date}T23:59:00` : undefined),
    timezone: TZ,
    locationLabel: draft.locationLabel,
    city: draft.city ?? draft.locationLabel,
    addressLine: draft.addressLine,
    summary: draft.summary,
    description: draft.description ?? DETAILS_LATER,
    whatToExpect: draft.whatToExpect ?? ["Stop details will be added when the host confirms venue and program."],
    whoItsFor: draft.whoItsFor ?? "Neighbors, volunteers, and anyone who wants to meet the campaign on the trail.",
    organizerNote:
      draft.organizerNote ??
      (tentative
        ? "Restored 2026-09-06 from the September unpublished-card archive — tentative until confirmed."
        : "Restored 2026-09-06 from the September unpublished-card archive."),
    attendanceType: draft.attendanceType,
    audienceTags: draft.audienceTags,
    relatedEventSlugs: draft.relatedEventSlugs,
    relatedResourceHrefs: draft.relatedResourceHrefs ?? [
      { label: "Events calendar", href: "/events" },
      { label: "Get involved", href: "/get-involved" },
    ],
    primaryHref: draft.primaryHref,
    primaryCtaLabel: draft.primaryCtaLabel,
    mapCoordinates: draft.mapCoordinates,
    mapPinQuality: draft.mapPinQuality,
    fieldAttendance: draft.fieldAttendance ?? "tentative",
    campaignTrail: true,
    statewideVirtual: draft.statewideVirtual,
    eventSource: "movement",
    opsFlags: {
      timeTbd: draft.timeTbd,
      missingCounty: draft.statewideVirtual ? false : !countySlug,
      missingCoordinates: draft.statewideVirtual ? false : !draft.mapCoordinates,
    },
  };
}

/** Upcoming cards taken off /events between Sept 3 and Sept 5, plus live extras that were not in index.ts. */
export const restoredUpcomingFromSeptCuts: EventItem[] = [
  campaignStop({
    slug: "washington-county-labor-event-2026",
    title: "Labor event — Washington County",
    type: "Labor / Worker Roundtable",
    countySlug: "washington-county",
    startsAt: "2026-09-07T10:00:00",
    endsAt: "2026-09-07T16:00:00",
    locationLabel: "Washington County — labor event (city TBA)",
    addressLine: "Washington County, AR. Clock and city not on the all-day calendar block.",
    summary:
      "Monday, September 7, 2026: Labor event in Washington County on the campaign calendar. Time and city TBA. Same morning is Rector Labor Day — those do not pair.",
    description:
      "Steve’s Google Calendar listed a Washington County labor event as an all-day block on Monday, September 7.\n\nThe public calendar already has Rector Labor Day Parade and Picnic that morning in Clay County. Confirm the labor clock before promising both.",
    whatToExpect: ["All-day hold on the campaign calendar", "City and hour TBA"],
    audienceTags: ["Washington County", "Labor"],
    mapCoordinates: { lat: 36.0617, lng: -94.1608 },
    mapPinQuality: "region",
    relatedEventSlugs: ["rector-labor-day-parade-picnic-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "dallas-county-fair-fordyce-2026-09-11",
    title: "Dallas County Fair — Fordyce",
    type: "Fairs and Festivals",
    countySlug: "dallas-county",
    startsAt: "2026-09-11T18:00:00",
    endsAt: "2026-09-11T21:00:00",
    locationLabel: "Dallas County Fair — Fordyce",
    city: "Fordyce",
    summary: "Friday, September 11, 2026, 6:00 p.m. Central: Dallas County Fair in Fordyce.",
    audienceTags: ["Fordyce", "Dallas County", "Festival"],
    mapCoordinates: { lat: 33.8137, lng: -92.4124 },
    relatedEventSlugs: ["sharp-county-hq-highland-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "baxter-county-candidate-forum-2026-09-14",
    title: "Candidate Forum",
    type: "Town Hall",
    countySlug: "baxter-county",
    startsAt: "2026-09-14T18:00:00",
    endsAt: "2026-09-14T20:00:00",
    locationLabel: "Mountain Home",
    city: "Mountain Home",
    summary: "Monday 6:00 p.m. Central candidate forum in Mountain Home.",
    audienceTags: ["Mountain Home", "Baxter County", "Candidate Forum"],
    mapCoordinates: { lat: 36.3353, lng: -92.3851 },
    relatedEventSlugs: ["faulkner-dems-hq-opening-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "pope-county-fair-russellville-2026",
    title: "Pope County Fair — Russellville",
    type: "Fairs and Festivals",
    countySlug: "pope-county",
    startsAt: "2026-09-15T09:00:00",
    endsAt: "2026-09-19T22:00:00",
    timeTbd: true,
    locationLabel: "Russellville",
    city: "Russellville",
    summary: "Tuesday, September 15 through Saturday, September 19: Pope County Fair in Russellville.",
    audienceTags: ["Russellville", "Pope County", "Festival"],
    mapCoordinates: { lat: 35.2784, lng: -93.1338 },
    relatedEventSlugs: ["russellville-mary-ella-voter-registration-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "calhoun-county-fair-2026-09-18",
    title: "Calhoun County Fair",
    type: "Fairs and Festivals",
    countySlug: "calhoun-county",
    startsAt: "2026-09-18T12:00:00",
    timeTbd: true,
    locationLabel: "Calhoun County Fair",
    city: "Hampton",
    summary: "Tentative Calhoun County Fair. Time and fairgrounds details to be posted if confirmed.",
    audienceTags: ["Calhoun County", "Festival"],
    mapCoordinates: { lat: 33.5379, lng: -92.4696 },
    relatedEventSlugs: ["little-rock-comic-con-2026-09-19", "grassroots-guitar-strings-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "little-rock-comic-con-2026-09-19",
    title: "Little Rock Comic Con",
    type: "Fairs and Festivals",
    countySlug: "pulaski-county",
    startsAt: "2026-09-19T09:00:00",
    endsAt: "2026-09-19T14:00:00",
    locationLabel: "Little Rock",
    city: "Little Rock",
    summary:
      "Saturday morning–2:00 p.m. Central at Little Rock Comic Con. Kelly heads to Malvern afterward for the 5:00 p.m. Hot Spring County cookout.",
    audienceTags: ["Little Rock", "Pulaski County", "Festival"],
    mapCoordinates: { lat: 34.7465, lng: -92.2896 },
    relatedEventSlugs: ["hot-spring-county-cookout-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "clark-county-multi-church-tour-2026-09-20",
    title: "Multi-Church Tour",
    type: "Community Conversation",
    countySlug: "clark-county",
    startsAt: "2026-09-20T09:00:00",
    endsAt: "2026-09-20T16:00:00",
    timeTbd: true,
    locationLabel: "Gurdon / Arkadelphia",
    city: "Gurdon / Arkadelphia",
    summary: "Sunday Clark County Multi-Church Tour, with stops in Gurdon and Arkadelphia.",
    description:
      "Public listing for the September 20 Multi-Church Tour in Clark County. Gurdon and Arkadelphia are both in Clark County, so this is one county stop with two city visits — not two unrelated events.",
    whatToExpect: [
      "Gurdon — church stop on the Multi-Church Tour",
      "Arkadelphia — church stop on the Multi-Church Tour",
      "Exact service times to be posted with host confirmation",
    ],
    audienceTags: ["Clark County", "Gurdon", "Arkadelphia"],
    mapCoordinates: { lat: 34.1209, lng: -93.0538 },
    relatedEventSlugs: ["arkadelphia-sep-20-2026", "dequeen-sep-20-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "arkadelphia-sep-20-2026",
    title: "Arkadelphia",
    type: "Community Conversation",
    countySlug: "clark-county",
    startsAt: "2026-09-20T10:00:00",
    endsAt: "2026-09-20T16:00:00",
    locationLabel: "Arkadelphia (stop TBA)",
    addressLine: "Arkadelphia, AR (clock and street not on the all-day block)",
    summary: "Sunday, September 20, 2026: Arkadelphia all-day hold. Same date is the Clark County Multi-Church Tour.",
    audienceTags: ["Arkadelphia", "Clark County"],
    mapCoordinates: { lat: 34.1209, lng: -93.0538 },
    mapPinQuality: "region",
    relatedEventSlugs: ["clark-county-multi-church-tour-2026-09-20"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "howard-county-visit-nashville-2026-09-22",
    title: "Howard County visit — Nashville",
    type: "Community Conversation",
    countySlug: "howard-county",
    startsAt: "2026-09-22T12:00:00",
    timeTbd: true,
    locationLabel: "Nashville",
    city: "Nashville",
    summary: "Tuesday, September 22, 2026: Howard County visit in Nashville. Confirm whether this night or September 8 is the locked stop.",
    audienceTags: ["Nashville", "Howard County"],
    mapCoordinates: { lat: 33.9457, lng: -93.8471 },
    relatedEventSlugs: ["howard-county-nashville-sep-8-2026", "garland-library-county-candidates-forum-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "crittenden-prairie-arkansas-swing-2026-09-23",
    title: "Crittenden, Prairie, and Arkansas County swing",
    type: "Immersion",
    countySlug: "crittenden-county",
    startsAt: "2026-09-23T09:00:00",
    timeTbd: true,
    locationLabel: "Crittenden, Prairie, and Arkansas Counties",
    city: "East Arkansas",
    summary: "Wednesday, September 23, 2026: Crittenden, Prairie, and Arkansas County swing.",
    audienceTags: ["Crittenden County", "Prairie County", "Arkansas County"],
    mapCoordinates: { lat: 35.1465, lng: -90.1845 },
    mapPinQuality: "region",
    relatedEventSlugs: [],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "hot-springs-forum-2026-09-25",
    title: "Hot Springs Forum",
    type: "Town Hall",
    countySlug: "garland-county",
    startsAt: "2026-09-25T12:00:00",
    timeTbd: true,
    locationLabel: "Hot Springs",
    city: "Hot Springs",
    summary: "Friday, September 25, 2026: Hot Springs Forum in Garland County.",
    audienceTags: ["Hot Springs", "Garland County", "Candidate Forum"],
    mapCoordinates: { lat: 34.5037, lng: -93.0552 },
    relatedEventSlugs: ["leslie-karaoke-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "greene-county-candidate-forum-2026-09-26",
    title: "Candidate Forum",
    type: "Town Hall",
    countySlug: "greene-county",
    startsAt: "2026-09-26T14:00:00",
    endsAt: "2026-09-26T16:00:00",
    locationLabel: "Paragould",
    city: "Paragould",
    summary: "Saturday 2:00 p.m. Central candidate forum in Paragould.",
    audienceTags: ["Paragould", "Greene County", "Candidate Forum"],
    mapCoordinates: { lat: 36.0584, lng: -90.4973 },
    relatedEventSlugs: ["marche-day-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "harrison-balloon-fest-2026-09-28",
    title: "Harrison Balloon Fest",
    type: "Fairs and Festivals",
    countySlug: "boone-county",
    startsAt: "2026-09-28T09:00:00",
    timeTbd: true,
    locationLabel: "Harrison",
    city: "Harrison",
    summary:
      "Monday, September 28, 2026: Harrison Balloon Fest. Distinct from the September 13 Anstaff Soccer Complex stop.",
    audienceTags: ["Harrison", "Boone County", "Festival"],
    mapCoordinates: { lat: 36.2298, lng: -93.1077 },
    relatedEventSlugs: ["harrison-hot-air-balloon-festival-2026", "dppc-gigis-rally-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "van-buren-moonshine-music-festival-2026-10-03",
    title: "Moonshine + Music Festival",
    type: "Fairs and Festivals",
    countySlug: "van-buren-county",
    startsAt: "2026-10-03T13:00:00",
    locationLabel: "Van Buren County",
    city: "Van Buren County",
    summary: "Saturday 1:00 p.m. Central Moonshine + Music Festival in Van Buren County.",
    audienceTags: ["Van Buren County", "Festival"],
    mapCoordinates: { lat: 35.5915, lng: -92.4593 },
    relatedEventSlugs: ["goat-fest-oct-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "king-biscuit-blues-festival-2026-10-09",
    title: "King Biscuit Blues Festival",
    type: "Fairs and Festivals",
    countySlug: "phillips-county",
    startsAt: "2026-10-09T12:00:00",
    timeTbd: true,
    locationLabel: "Helena-West Helena",
    city: "Helena-West Helena",
    summary: "Friday King Biscuit Blues Festival in Helena-West Helena. Time to be posted.",
    audienceTags: ["Helena-West Helena", "Phillips County", "Festival"],
    mapCoordinates: { lat: 34.5293, lng: -90.5901 },
    relatedEventSlugs: ["olli-for-coffee-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "yellville-turkey-trot-2026-10-10",
    title: "Turkey Trot",
    type: "Fairs and Festivals",
    countySlug: "marion-county",
    startsAt: "2026-10-10T12:00:00",
    timeTbd: true,
    locationLabel: "Yellville",
    city: "Yellville",
    summary: "Saturday Turkey Trot in Yellville. Time to be posted.",
    audienceTags: ["Yellville", "Marion County", "Festival"],
    mapCoordinates: { lat: 36.2262, lng: -92.6849 },
    relatedEventSlugs: ["october-daze-booneville-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "ayc-karaoke-hot-springs-2026-10-11",
    title: "AYC Karaoke Event",
    type: "Youth Civic Session",
    countySlug: "garland-county",
    startsAt: "2026-10-11T18:00:00",
    timeTbd: true,
    locationLabel: "Hot Springs",
    city: "Hot Springs",
    summary: "Sunday AYC karaoke event in Hot Springs. Time to be posted.",
    audienceTags: ["Hot Springs", "Garland County", "Youth", "College"],
    mapCoordinates: { lat: 34.5037, lng: -93.0552 },
    primaryHref: "/get-involved#volunteer",
    primaryCtaLabel: "Volunteer / Get involved",
    relatedEventSlugs: ["hot-springs-chili-cookout-2026"],
    relatedResourceHrefs: [
      { label: "Volunteer", href: "/get-involved#volunteer" },
      { label: "Events calendar", href: "/events" },
    ],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "saline-county-gotv-2026-10-12",
    title: "Saline County GOTV push — Benton",
    type: "Community Conversation",
    countySlug: "saline-county",
    startsAt: "2026-10-12T09:00:00",
    timeTbd: true,
    locationLabel: "Benton",
    city: "Benton",
    summary: "Monday, October 12, 2026: Saline County GOTV push in Benton.",
    audienceTags: ["Benton", "Saline County", "GOTV"],
    mapCoordinates: { lat: 34.5645, lng: -92.5868 },
    relatedEventSlugs: ["rison-in-the-fall-2026", "women-in-democracy-jonesboro-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "logan-scott-immersion-2026-10-18",
    title: "Logan and Scott immersion",
    type: "Immersion",
    countySlug: "logan-county",
    startsAt: "2026-10-18T09:00:00",
    timeTbd: true,
    locationLabel: "Logan and Scott Counties",
    city: "Logan and Scott Counties",
    summary: "Sunday, October 18, 2026: Logan and Scott County immersion.",
    audienceTags: ["Logan County", "Scott County"],
    mapCoordinates: { lat: 35.2145, lng: -93.7341 },
    mapPinQuality: "region",
    relatedEventSlugs: ["petit-jean-meat-festival-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "early-voting-launch-2026-10-20",
    title: "Early Voting launch — Little Rock",
    type: "Direct Democracy Briefing",
    countySlug: "pulaski-county",
    startsAt: "2026-10-20T09:00:00",
    timeTbd: true,
    locationLabel: "Little Rock",
    city: "Little Rock",
    summary: "Tuesday, October 20, 2026: Early Voting launch in Little Rock.",
    audienceTags: ["Little Rock", "Pulaski County", "Early voting"],
    mapCoordinates: { lat: 34.7465, lng: -92.2896 },
    relatedEventSlugs: [],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "greers-ferry-event-2026-10-23",
    title: "Greers Ferry Event",
    type: "Community Conversation",
    countySlug: "cleburne-county",
    startsAt: "2026-10-23T12:00:00",
    timeTbd: true,
    locationLabel: "Greers Ferry",
    city: "Greers Ferry",
    summary: "Tentative Friday event in Greers Ferry. Time to be posted if confirmed.",
    audienceTags: ["Greers Ferry", "Cleburne County"],
    mapCoordinates: { lat: 35.5767, lng: -92.1771 },
    relatedEventSlugs: ["lake-chicot-fall-fest-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "ponca-color-fest-2026-10-25",
    title: "Ponca Color Fest",
    type: "Fairs and Festivals",
    countySlug: "newton-county",
    startsAt: "2026-10-25T12:00:00",
    timeTbd: true,
    locationLabel: "Ponca",
    city: "Ponca",
    summary: "Sunday Ponca Color Fest in Newton County. Time to be posted.",
    description:
      "Public listing for Ponca Color Fest. Monday continues as a Madison and Newton County mountain trip while the leaves change.",
    whatToExpect: [
      "Ponca Color Fest in Newton County",
      "Monday continues as a Madison / Newton County Day on the same mountain trip",
    ],
    audienceTags: ["Ponca", "Newton County", "Festival"],
    mapCoordinates: { lat: 36.0223, lng: -93.3613 },
    relatedEventSlugs: ["madison-newton-county-day-2026-10-26", "mountain-view-bean-fest-outhouse-races-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "madison-newton-county-day-2026-10-26",
    title: "Madison / Newton County Day",
    type: "Community Conversation",
    countySlug: "madison-county",
    startsAt: "2026-10-26T12:00:00",
    timeTbd: true,
    locationLabel: "Madison and Newton Counties",
    city: "Madison and Newton Counties",
    summary:
      "Monday continuation of the Ponca Color Fest mountain trip, covering Madison and Newton Counties while the leaves change.",
    audienceTags: ["Madison County", "Newton County"],
    mapCoordinates: { lat: 36.0862, lng: -93.7363 },
    mapPinQuality: "region",
    relatedEventSlugs: ["ponca-color-fest-2026-10-25"],
    fieldAttendance: "confirmed",
  }),
];
