import type { EventItem, EventType } from "@/content/types";
import { getMovementRegionForCountySlug, STATEWIDE_EVENT_REGION } from "@/content/arkansas-movement-regions";

const TZ = "America/Chicago";
const DETAILS_LATER =
  "Restored to the public calendar after the September 3–5 unpublished-card cuts. Venue, program, and how to join will be added when the host confirms them. All times are U.S. Central.";

type StopDraft = {
  slug: string;
  title: string;
  type: EventType;
  region?: string;
  countySlug?: string;
  startsAt: string;
  endsAt?: string;
  timeTbd?: boolean;
  locationLabel: string;
  addressLine?: string;
  city?: string;
  summary: string;
  description?: string;
  whatToExpect?: string[];
  audienceTags: string[];
  mapCoordinates?: { lat: number; lng: number };
  relatedEventSlugs: string[];
  relatedResourceHrefs?: Array<{ label: string; href: string }>;
  primaryHref?: string;
  primaryCtaLabel?: string;
  fieldAttendance?: "confirmed" | "tentative";
  whoItsFor?: string;
  organizerNote?: string;
  attendanceType?: EventItem["attendanceType"];
  statewideVirtual?: boolean;
  mapPinQuality?: EventItem["mapPinQuality"];
};

function campaignStop(draft: StopDraft): EventItem {
  const date = draft.startsAt.slice(0, 10);
  const tentative = draft.fieldAttendance !== "confirmed";
  const countySlug = draft.countySlug;
  return {
    slug: draft.slug,
    title: draft.title,
    type: draft.type,
    region: draft.region ?? (countySlug ? getMovementRegionForCountySlug(countySlug) ?? STATEWIDE_EVENT_REGION : STATEWIDE_EVENT_REGION),
    countySlug,
    status: "upcoming",
    startsAt: draft.startsAt,
    endsAt: draft.endsAt ?? (draft.timeTbd ? `${date}T23:59:00` : undefined),
    timezone: TZ,
    locationLabel: draft.locationLabel,
    city: draft.city ?? draft.locationLabel,
    addressLine: draft.addressLine,
    summary: draft.summary,
    description: draft.description ?? DETAILS_LATER,
    whatToExpect: draft.whatToExpect ?? ["Stop details will be added when the host confirms venue and program."],
    whoItsFor: draft.whoItsFor ?? "Neighbors, volunteers, and anyone who wants to meet the campaign on the trail.",
    organizerNote:
      draft.organizerNote ??
      (tentative
        ? "Restored 2026-09-06 from the September unpublished-card archive — tentative until confirmed."
        : "Restored 2026-09-06 from the September unpublished-card archive."),
    attendanceType: draft.attendanceType,
    audienceTags: draft.audienceTags,
    relatedEventSlugs: draft.relatedEventSlugs,
    relatedResourceHrefs: draft.relatedResourceHrefs ?? [
      { label: "Events calendar", href: "/events" },
      { label: "Get involved", href: "/get-involved" },
    ],
    primaryHref: draft.primaryHref,
    primaryCtaLabel: draft.primaryCtaLabel,
    mapCoordinates: draft.mapCoordinates,
    mapPinQuality: draft.mapPinQuality,
    fieldAttendance: draft.fieldAttendance ?? "tentative",
    campaignTrail: true,
    statewideVirtual: draft.statewideVirtual,
    eventSource: "movement",
    opsFlags: {
      timeTbd: draft.timeTbd,
      missingCounty: draft.statewideVirtual ? false : !countySlug,
      missingCoordinates: draft.statewideVirtual ? false : !draft.mapCoordinates,
    },
  };
}

/** Upcoming cards taken off /events between Sept 3 and Sept 5, plus live extras that were not in index.ts. */
export const restoredUpcomingFromSeptCuts: EventItem[] = [
  campaignStop({
    slug: "washington-county-labor-event-2026",
    title: "Labor event — Washington County",
    type: "Labor / Worker Roundtable",
    countySlug: "washington-county",
    startsAt: "2026-09-07T10:00:00",
    endsAt: "2026-09-07T16:00:00",
    locationLabel: "Washington County — labor event (city TBA)",
    addressLine: "Washington County, AR. Clock and city not on the all-day calendar block.",
    summary:
      "Monday, September 7, 2026: Labor event in Washington County on the campaign calendar. Time and city TBA. Same morning is Rector Labor Day — those do not pair.",
    description:
      "Steve’s Google Calendar listed a Washington County labor event as an all-day block on Monday, September 7.\n\nThe public calendar already has Rector Labor Day Parade and Picnic that morning in Clay County. Confirm the labor clock before promising both.",
    whatToExpect: ["All-day hold on the campaign calendar", "City and hour TBA"],
    audienceTags: ["Washington County", "Labor"],
    mapCoordinates: { lat: 36.0617, lng: -94.1608 },
    mapPinQuality: "region",
    relatedEventSlugs: ["rector-labor-day-parade-picnic-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "dallas-county-fair-fordyce-2026-09-11",
    title: "Dallas County Fair — Fordyce",
    type: "Fairs and Festivals",
    countySlug: "dallas-county",
    startsAt: "2026-09-11T18:00:00",
    endsAt: "2026-09-11T21:00:00",
    locationLabel: "Dallas County Fair — Fordyce",
    city: "Fordyce",
    summary: "Friday, September 11, 2026, 6:00 p.m. Central: Dallas County Fair in Fordyce.",
    audienceTags: ["Fordyce", "Dallas County", "Festival"],
    mapCoordinates: { lat: 33.8137, lng: -92.4124 },
    relatedEventSlugs: ["sharp-county-hq-highland-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "baxter-county-candidate-forum-2026-09-14",
    title: "Candidate Forum",
    type: "Town Hall",
    countySlug: "baxter-county",
    startsAt: "2026-09-14T18:00:00",
    endsAt: "2026-09-14T20:00:00",
    locationLabel: "Mountain Home",
    city: "Mountain Home",
    summary: "Monday 6:00 p.m. Central candidate forum in Mountain Home.",
    audienceTags: ["Mountain Home", "Baxter County", "Candidate Forum"],
    mapCoordinates: { lat: 36.3353, lng: -92.3851 },
    relatedEventSlugs: ["faulkner-dems-hq-opening-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "pope-county-fair-russellville-2026",
    title: "Pope County Fair — Russellville",
    type: "Fairs and Festivals",
    countySlug: "pope-county",
    startsAt: "2026-09-15T09:00:00",
    endsAt: "2026-09-19T22:00:00",
    timeTbd: true,
    locationLabel: "Russellville",
    city: "Russellville",
    summary: "Tuesday, September 15 through Saturday, September 19: Pope County Fair in Russellville.",
    audienceTags: ["Russellville", "Pope County", "Festival"],
    mapCoordinates: { lat: 35.2784, lng: -93.1338 },
    relatedEventSlugs: ["russellville-mary-ella-voter-registration-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "calhoun-county-fair-2026-09-18",
    title: "Calhoun County Fair",
    type: "Fairs and Festivals",
    countySlug: "calhoun-county",
    startsAt: "2026-09-18T12:00:00",
    timeTbd: true,
    locationLabel: "Calhoun County Fair",
    city: "Hampton",
    summary: "Tentative Calhoun County Fair. Time and fairgrounds details to be posted if confirmed.",
    audienceTags: ["Calhoun County", "Festival"],
    mapCoordinates: { lat: 33.5379, lng: -92.4696 },
    relatedEventSlugs: ["little-rock-comic-con-2026-09-19", "grassroots-guitar-strings-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "little-rock-comic-con-2026-09-19",
    title: "Little Rock Comic Con",
    type: "Fairs and Festivals",
    countySlug: "pulaski-county",
    startsAt: "2026-09-19T09:00:00",
    endsAt: "2026-09-19T14:00:00",
    locationLabel: "Little Rock",
    city: "Little Rock",
    summary:
      "Saturday morning–2:00 p.m. Central at Little Rock Comic Con. Kelly heads to Malvern afterward for the 5:00 p.m. Hot Spring County cookout.",
    audienceTags: ["Little Rock", "Pulaski County", "Festival"],
    mapCoordinates: { lat: 34.7465, lng: -92.2896 },
    relatedEventSlugs: ["hot-spring-county-cookout-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "clark-county-multi-church-tour-2026-09-20",
    title: "Multi-Church Tour",
    type: "Community Conversation",
    countySlug: "clark-county",
    startsAt: "2026-09-20T09:00:00",
    endsAt: "2026-09-20T16:00:00",
    timeTbd: true,
    locationLabel: "Gurdon / Arkadelphia",
    city: "Gurdon / Arkadelphia",
    summary: "Sunday Clark County Multi-Church Tour, with stops in Gurdon and Arkadelphia — confirmed.",
    description:
      "Steve confirmed **Sunday, September 20, 2026** for the Clark County Multi-Church Tour. Gurdon and Arkadelphia are both in Clark County, so this is one county stop with two city visits — not two unrelated events.\n\nThe same Sunday is **De Queen 4:00–6:00 p.m.** and **travel to Becky's in Texarkana at 5:00 p.m.** — all three confirmed.",
    whatToExpect: [
      "Gurdon — church stop on the Multi-Church Tour",
      "Arkadelphia — church stop on the Multi-Church Tour",
      "Exact service times to be posted with host confirmation",
    ],
    audienceTags: ["Clark County", "Gurdon", "Arkadelphia"],
    mapCoordinates: { lat: 34.1209, lng: -93.0538 },
    relatedEventSlugs: ["arkadelphia-sep-20-2026", "dequeen-sep-20-2026", "beckys-texarkana-2026-09-20"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "beckys-texarkana-2026-09-20",
    title: "Travel to Becky's — Texarkana",
    type: "Community Conversation",
    region: "Southwest Arkansas",
    countySlug: "miller-county",
    startsAt: "2026-09-20T17:00:00",
    endsAt: "2026-09-20T19:00:00",
    locationLabel: "Becky's — Texarkana",
    city: "Texarkana",
    addressLine: "Texarkana, AR (private destination — street not published)",
    summary:
      "Sunday, September 20, 2026, **5:00 p.m. Central**: travel to Becky's in Texarkana. This is travel, not a public gathering.",
    description:
      "Steve locked **travel to Becky's in Texarkana** for Sunday, **September 20**, **5:00 p.m. Central**.\n\nThis is **private travel**, not a walk-in campaign event. Do not publish a street.\n\nThe same afternoon is **De Queen 4:00–6:00 p.m.** De Queen to Texarkana is a southwest run that same evening.",
    whatToExpect: ["5:00 p.m. Central arrival / travel window", "Private stop — not a public event"],
    whoItsFor: "Campaign travel only. Neighbors should use the De Queen listing if they want a public Sunday stop.",
    organizerNote:
      "Steve 2026-09-08: Becky's Texarkana Sep 20 confirmed with Multi-Church Tour and De Queen the same day. Do not invent an address or last name.",
    audienceTags: ["Texarkana", "Miller County", "Southwest Arkansas"],
    mapCoordinates: { lat: 33.4251, lng: -94.0477 },
    mapPinQuality: "region",
    relatedEventSlugs: ["dequeen-sep-20-2026", "clark-county-multi-church-tour-2026-09-20"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "arkadelphia-sep-20-2026",
    title: "Arkadelphia",
    type: "Community Conversation",
    countySlug: "clark-county",
    startsAt: "2026-09-20T10:00:00",
    endsAt: "2026-09-20T16:00:00",
    locationLabel: "Arkadelphia (stop TBA)",
    addressLine: "Arkadelphia, AR (clock and street not on the all-day block)",
    summary: "Sunday, September 20, 2026: Arkadelphia all-day hold. Same date is the Clark County Multi-Church Tour.",
    audienceTags: ["Arkadelphia", "Clark County"],
    mapCoordinates: { lat: 34.1209, lng: -93.0538 },
    mapPinQuality: "region",
    relatedEventSlugs: ["clark-county-multi-church-tour-2026-09-20"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "howard-county-visit-nashville-2026-09-22",
    title: "Howard County visit — Nashville",
    type: "Community Conversation",
    countySlug: "howard-county",
    startsAt: "2026-09-22T12:00:00",
    timeTbd: true,
    locationLabel: "Nashville",
    city: "Nashville",
    summary: "Tuesday, September 22, 2026: Howard County visit in Nashville — confirmed. Time TBA.",
    description:
      "Steve confirmed **Tuesday, September 22, 2026** in **Nashville** for a **Howard County** visit.\n\nClock and street are still TBA.",
    whatToExpect: ["Confirmed Tuesday, September 22", "Time and street TBA"],
    audienceTags: ["Nashville", "Howard County"],
    mapCoordinates: { lat: 33.9457, lng: -93.8471 },
    mapPinQuality: "region",
    relatedEventSlugs: [],
    organizerNote: "Steve 2026-09-08: Sep 22 Howard County Nashville confirmed. Time TBA.",
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "crittenden-prairie-arkansas-swing-2026-09-23",
    title: "Crittenden, Prairie, and Arkansas County swing",
    type: "Immersion",
    countySlug: "crittenden-county",
    startsAt: "2026-09-23T09:00:00",
    timeTbd: true,
    locationLabel: "Crittenden, Prairie, and Arkansas Counties",
    city: "East Arkansas",
    summary: "Wednesday, September 23, 2026: Crittenden, Prairie, and Arkansas County swing.",
    audienceTags: ["Crittenden County", "Prairie County", "Arkansas County"],
    mapCoordinates: { lat: 35.1465, lng: -90.1845 },
    mapPinQuality: "region",
    relatedEventSlugs: [],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "hot-springs-forum-2026-09-25",
    title: "Hot Springs Forum",
    type: "Town Hall",
    countySlug: "garland-county",
    startsAt: "2026-09-25T12:00:00",
    timeTbd: true,
    locationLabel: "Hot Springs",
    city: "Hot Springs",
    summary: "Friday, September 25, 2026: Hot Springs Forum in Garland County.",
    audienceTags: ["Hot Springs", "Garland County", "Candidate Forum"],
    mapCoordinates: { lat: 34.5037, lng: -93.0552 },
    relatedEventSlugs: ["leslie-karaoke-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "greene-county-candidate-forum-2026-09-26",
    title: "Candidate Forum",
    type: "Town Hall",
    countySlug: "greene-county",
    startsAt: "2026-09-26T14:00:00-05:00",
    endsAt: "2026-09-26T16:00:00-05:00",
    locationLabel: "Paragould",
    city: "Paragould",
    summary: "Saturday afternoon candidate forum in Paragould — confirmed. Morning is Marche Day.",
    audienceTags: ["Paragould", "Greene County", "Candidate Forum"],
    mapCoordinates: { lat: 36.0584, lng: -90.4973 },
    relatedEventSlugs: ["marche-day-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "harrison-balloon-fest-2026-09-28",
    title: "Harrison Balloon Fest",
    type: "Fairs and Festivals",
    countySlug: "boone-county",
    startsAt: "2026-09-28T09:00:00",
    timeTbd: true,
    locationLabel: "Harrison",
    city: "Harrison",
    summary:
      "Monday, September 28, 2026: Harrison Balloon Fest. Distinct from the September 13 Anstaff Soccer Complex stop.",
    audienceTags: ["Harrison", "Boone County", "Festival"],
    mapCoordinates: { lat: 36.2298, lng: -93.1077 },
    relatedEventSlugs: ["harrison-hot-air-balloon-festival-2026", "dppc-gigis-rally-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "van-buren-moonshine-music-festival-2026-10-03",
    title: "Moonshine + Music Festival",
    type: "Fairs and Festivals",
    countySlug: "van-buren-county",
    startsAt: "2026-10-03T13:00:00",
    locationLabel: "Van Buren County",
    city: "Van Buren County",
    summary: "Saturday 1:00 p.m. Central Moonshine + Music Festival in Van Buren County.",
    audienceTags: ["Van Buren County", "Festival"],
    mapCoordinates: { lat: 35.5915, lng: -92.4593 },
    relatedEventSlugs: ["goat-fest-oct-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "king-biscuit-blues-festival-2026-10-09",
    title: "King Biscuit Blues Festival",
    type: "Fairs and Festivals",
    countySlug: "phillips-county",
    startsAt: "2026-10-09T12:00:00",
    timeTbd: true,
    locationLabel: "Helena-West Helena",
    city: "Helena-West Helena",
    summary: "Friday King Biscuit Blues Festival in Helena-West Helena. Time to be posted.",
    audienceTags: ["Helena-West Helena", "Phillips County", "Festival"],
    mapCoordinates: { lat: 34.5293, lng: -90.5901 },
    relatedEventSlugs: ["olli-for-coffee-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "yellville-turkey-trot-2026-10-10",
    title: "Turkey Trot",
    type: "Fairs and Festivals",
    countySlug: "marion-county",
    startsAt: "2026-10-10T12:00:00",
    timeTbd: true,
    locationLabel: "Yellville",
    city: "Yellville",
    summary: "Saturday Turkey Trot in Yellville. Time to be posted.",
    audienceTags: ["Yellville", "Marion County", "Festival"],
    mapCoordinates: { lat: 36.2262, lng: -92.6849 },
    relatedEventSlugs: ["october-daze-booneville-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "ayc-karaoke-hot-springs-2026-10-11",
    title: "AYC Karaoke Event",
    type: "Youth Civic Session",
    countySlug: "garland-county",
    startsAt: "2026-10-11T18:00:00",
    timeTbd: true,
    locationLabel: "Hot Springs",
    city: "Hot Springs",
    summary: "Sunday AYC karaoke event in Hot Springs. Time to be posted.",
    audienceTags: ["Hot Springs", "Garland County", "Youth", "College"],
    mapCoordinates: { lat: 34.5037, lng: -93.0552 },
    primaryHref: "/get-involved#volunteer",
    primaryCtaLabel: "Volunteer / Get involved",
    relatedEventSlugs: ["hot-springs-chili-cookout-2026"],
    organizerNote: "Steve 2026-09-08: AYC karaoke Oct 11 Hot Springs. Same evening Speakeasy at 626 Malvern Ave 5:30 p.m.",
    relatedResourceHrefs: [
      { label: "Volunteer", href: "/get-involved#volunteer" },
      { label: "Events calendar", href: "/events" },
    ],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "ayc-youth-retreat-little-rock-2026-10-16",
    title: "AYC youth retreat weekend — Little Rock",
    type: "Youth Civic Session",
    countySlug: "pulaski-county",
    startsAt: "2026-10-16T09:00:00",
    endsAt: "2026-10-18T17:00:00",
    timeTbd: true,
    locationLabel: "Little Rock (AYC youth retreat — venue TBA)",
    city: "Little Rock",
    addressLine: "Little Rock, AR (venue TBA)",
    summary:
      "Friday, October 16 through Sunday, October 18, 2026: **Arkansas Youth Coalition** youth retreat weekend in Little Rock — confirmed. Venue TBA.",
    description:
      "The campaign is in **Little Rock** Friday, **October 16** through Sunday, **October 18, 2026** for the **Arkansas Youth Coalition** youth retreat weekend.\n\nBuilding and daily clock are still TBA. This is the public hold for that weekend.",
    whatToExpect: [
      "Friday through Sunday in Little Rock",
      "AYC youth retreat — follow the coalition for the room and daily clock",
    ],
    whoItsFor: "AYC participants and invited campaign guests. Confirm the venue with the hosts before travel.",
    organizerNote:
      "Steve 2026-09-08: block Oct 16-18 AYC youth retreat weekend in Little Rock. Venue TBA.",
    audienceTags: ["Little Rock", "Pulaski County", "Youth", "College", "AYC"],
    mapCoordinates: { lat: 34.7465, lng: -92.2896 },
    mapPinQuality: "region",
    primaryHref: "/get-involved#volunteer",
    primaryCtaLabel: "Volunteer / Get involved",
    relatedEventSlugs: ["ayc-karaoke-hot-springs-2026-10-11"],
    relatedResourceHrefs: [
      { label: "Volunteer", href: "/get-involved#volunteer" },
      { label: "Events calendar", href: "/events" },
    ],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "saline-county-gotv-2026-10-12",
    title: "Saline County GOTV push — Benton",
    type: "Community Conversation",
    countySlug: "saline-county",
    startsAt: "2026-10-12T09:00:00",
    timeTbd: true,
    locationLabel: "Benton",
    city: "Benton",
    summary: "Monday, October 12, 2026: Saline County GOTV push in Benton.",
    audienceTags: ["Benton", "Saline County", "GOTV"],
    mapCoordinates: { lat: 34.5645, lng: -92.5868 },
    relatedEventSlugs: ["rison-in-the-fall-2026", "women-in-democracy-jonesboro-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "logan-scott-immersion-2026-10-18",
    title: "Logan and Scott immersion",
    type: "Immersion",
    countySlug: "logan-county",
    startsAt: "2026-10-18T09:00:00",
    timeTbd: true,
    locationLabel: "Logan and Scott Counties",
    city: "Logan and Scott Counties",
    summary: "Sunday, October 18, 2026: Logan and Scott County immersion.",
    audienceTags: ["Logan County", "Scott County"],
    mapCoordinates: { lat: 35.2145, lng: -93.7341 },
    mapPinQuality: "region",
    relatedEventSlugs: ["petit-jean-meat-festival-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "early-voting-launch-2026-10-20",
    title: "Early Voting launch — Little Rock",
    type: "Direct Democracy Briefing",
    countySlug: "pulaski-county",
    startsAt: "2026-10-20T09:00:00",
    timeTbd: true,
    locationLabel: "Little Rock",
    city: "Little Rock",
    summary: "Tuesday, October 20, 2026: Early Voting launch in Little Rock.",
    audienceTags: ["Little Rock", "Pulaski County", "Early voting"],
    mapCoordinates: { lat: 34.7465, lng: -92.2896 },
    relatedEventSlugs: ["vck-gotv-pep-rally-hot-springs-2026-10-20"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "vck-gotv-pep-rally-hot-springs-2026-10-20",
    title: "VCK Democratic Women GOTV pep rally — Hot Springs",
    type: "Community Conversation",
    countySlug: "garland-county",
    startsAt: "2026-10-20T17:30:00-05:00",
    endsAt: "2026-10-20T20:00:00-05:00",
    locationLabel: "The Jewish Center — Hot Springs",
    city: "Hot Springs",
    addressLine: "300 Quapaw Avenue, Hot Springs, AR",
    summary:
      "Tuesday, October 20, 2026: **VCK Democratic Women** Get Out the Vote pep rally at **The Jewish Center**, **300 Quapaw Avenue**, Hot Springs — tentative. Social **5:30 p.m.**, program **6:00 p.m.**, candidate introductions about **6:30 p.m.**",
    description:
      "VCK Democratic Women invited Kelly to a **Get Out the Vote pep rally** on **Tuesday, October 20, 2026** — the day early voting begins.\n\n**The Jewish Center**, **300 Quapaw Avenue**, Hot Springs. Social gathering **5:30 p.m. Central**. Program **6:00 p.m.** Candidate 30-second introductions around **6:30 p.m.**\n\nThe host night includes tailgate food and drinks, door prizes, Human Bingo, skits, and cheers. Attendees will be asked to write down five people to contact about voting. Candidates may bring signs, buttons, and swag.\n\nThis is a **VCK Democratic Women** event, not a Grappe-hosted rally. Kelly’s attendance is **tentative** until she RSVPs.\n\nThe same Tuesday the public calendar also has an Early Voting launch hold in Little Rock.",
    whatToExpect: [
      "5:30 p.m. social · 6:00 p.m. program · candidate intros about 6:30 p.m.",
      "Tailgate food, door prizes, Human Bingo, skits, and cheers",
      "30-second candidate introductions — host-run program",
    ],
    whoItsFor:
      "VCK Democratic Women, Hot Springs neighbors, and candidates the hosts invite. Confirm with the committee before treating this as a locked Kelly stop.",
    organizerNote:
      "Host letter dated 2026-09-05 from the VCK Democratic Women Pep Rally Planning Committee. fieldAttendance tentative. Keep host RSVP email and phone numbers off the public card.",
    audienceTags: ["Hot Springs", "Garland County", "GOTV", "Democratic Women", "Early voting"],
    mapCoordinates: { lat: 34.51, lng: -93.05 },
    mapPinQuality: "exact",
    relatedEventSlugs: ["early-voting-launch-2026-10-20"],
    relatedResourceHrefs: [
      { label: "Volunteer / Get involved", href: "/get-involved#volunteer" },
      { label: "Events calendar", href: "/events" },
    ],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "greers-ferry-event-2026-10-23",
    title: "Greers Ferry Event",
    type: "Community Conversation",
    countySlug: "cleburne-county",
    startsAt: "2026-10-23T12:00:00",
    timeTbd: true,
    locationLabel: "Greers Ferry",
    city: "Greers Ferry",
    summary: "Tentative Friday event in Greers Ferry. Time to be posted if confirmed.",
    audienceTags: ["Greers Ferry", "Cleburne County"],
    mapCoordinates: { lat: 35.5767, lng: -92.1771 },
    relatedEventSlugs: ["lake-chicot-fall-fest-2026"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "october-2-blocked-2026",
    title: "October 2 — booked",
    type: "House Gathering",
    startsAt: "2026-10-02T08:00:00-05:00",
    endsAt: "2026-10-02T20:00:00-05:00",
    timeTbd: true,
    locationLabel: "Venue TBA",
    city: "Venue TBA",
    attendanceType: "PRIVATE",
    summary:
      "Friday, October 2, 2026: the campaign is booked — confirmed. This is not an open public event.",
    description:
      "Steve blocked **Friday, October 2, 2026**.\n\nThis listing shows the campaign is booked that day. It is **not** an open neighbor event. Town and clock are not posted.",
    whatToExpect: ["Confirmed Friday, October 2", "Not an open campaign event"],
    whoItsFor: "This is not an open campaign event.",
    organizerNote: "Steve 2026-09-08: block off Oct 2. Personal/private hold. Do not invent a town.",
    audienceTags: ["Hold"],
    relatedEventSlugs: [],
    relatedResourceHrefs: [{ label: "Events calendar", href: "/events" }],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "fayetteville-fundraiser-2026-10-09",
    title: "Fundraiser — Fayetteville",
    type: "House Gathering",
    countySlug: "washington-county",
    startsAt: "2026-10-09T17:00:00-05:00",
    endsAt: "2026-10-09T20:00:00-05:00",
    locationLabel: "Fayetteville (venue TBA)",
    city: "Fayetteville",
    addressLine: "Fayetteville, AR (street TBA)",
    attendanceType: "INVITATION",
    summary:
      "Friday, October 9, 2026, **5:00–8:00 p.m. Central** in Fayetteville: campaign **fundraiser** hold — confirmed. Venue TBA.",
    description:
      "Steve scheduled a **fundraiser** hold for Friday, **October 9, 2026**, **5:00–8:00 p.m. Central** in **Fayetteville**.\n\nStreet and host room are still TBA.\n\nThe same afternoon is **OLLI for Coffee** at Jimmy’s Egg, **1:00–3:00 p.m.**",
    whatToExpect: ["Confirmed Friday, October 9", "5:00–8:00 p.m. Central", "Venue TBA"],
    whoItsFor: "Invited guests. This is not a walk-in public event.",
    organizerNote:
      "Steve 2026-09-08: schedule fundraiser Oct 9 Fayetteville 5:00-8:00 p.m. Hold the slot. Do not invent a street.",
    audienceTags: ["Fayetteville", "Washington County", "Fundraiser"],
    mapCoordinates: { lat: 36.0617, lng: -94.1608 },
    mapPinQuality: "region",
    relatedEventSlugs: ["olli-for-coffee-2026"],
    relatedResourceHrefs: [
      { label: "OLLI for Coffee — same afternoon", href: "/events/olli-for-coffee-2026" },
      { label: "Events calendar", href: "/events" },
    ],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "weston-colt-birthday-2026-10-24",
    title: "Weston Colt birthday",
    type: "House Gathering",
    startsAt: "2026-10-24T14:00:00-05:00",
    endsAt: "2026-10-24T18:00:00-05:00",
    locationLabel: "Venue TBA",
    city: "Venue TBA",
    attendanceType: "PRIVATE",
    summary:
      "Saturday, October 24, 2026, **2:00–6:00 p.m. Central**: **Weston Colt birthday** — confirmed. Venue TBA. Not an open campaign event.",
    description:
      "Saturday, **October 24, 2026**, **2:00–6:00 p.m. Central**: **Weston Colt birthday**.\n\nThis is a **confirmed** hold. Venue TBA.\n\nThis listing shows the campaign is booked that afternoon. It is **not** an open neighbor event.",
    whatToExpect: ["2:00–6:00 p.m. Central", "Venue TBA"],
    whoItsFor: "Invited guests. This is not an open campaign event.",
    organizerNote: "Steve 2026-09-08: Oct 24 Weston Colt birthday 2pm-6pm. Venue TBA.",
    audienceTags: ["Birthday"],
    relatedEventSlugs: [],
    relatedResourceHrefs: [{ label: "Events calendar", href: "/events" }],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "ponca-color-fest-2026-10-25",
    title: "Ponca Color Fest",
    type: "Fairs and Festivals",
    countySlug: "newton-county",
    startsAt: "2026-10-25T12:00:00",
    timeTbd: true,
    locationLabel: "Ponca",
    city: "Ponca",
    summary: "Sunday Ponca Color Fest in Newton County. Time to be posted.",
    description:
      "Public listing for Ponca Color Fest. Monday continues as a Madison and Newton County mountain trip while the leaves change.",
    whatToExpect: [
      "Ponca Color Fest in Newton County",
      "Monday continues as a Madison / Newton County Day on the same mountain trip",
    ],
    audienceTags: ["Ponca", "Newton County", "Festival"],
    mapCoordinates: { lat: 36.0223, lng: -93.3613 },
    relatedEventSlugs: ["madison-newton-county-day-2026-10-26", "mountain-view-bean-fest-outhouse-races-2026"],
    fieldAttendance: "confirmed",
  }),
  campaignStop({
    slug: "madison-newton-county-day-2026-10-26",
    title: "Madison / Newton County Day",
    type: "Community Conversation",
    countySlug: "madison-county",
    startsAt: "2026-10-26T12:00:00",
    timeTbd: true,
    locationLabel: "Madison and Newton Counties",
    city: "Madison and Newton Counties",
    summary:
      "Monday continuation of the Ponca Color Fest mountain trip, covering Madison and Newton Counties while the leaves change.",
    audienceTags: ["Madison County", "Newton County"],
    mapCoordinates: { lat: 36.0862, lng: -93.7363 },
    mapPinQuality: "region",
    relatedEventSlugs: ["ponca-color-fest-2026-10-25"],
    fieldAttendance: "confirmed",
  }),
];
