import type { EventItem, EventType } from "@/content/types";

const TZ = "America/Chicago";
const DETAILS_LATER =
  "Posted from the September 2026 campaign timeline. Venue, program, and how to join will be added when the host confirms them. All times are U.S. Central.";

type StopDraft = {
  slug: string;
  title: string;
  type: EventType;
  region: string;
  countySlug?: string;
  startsAt: string;
  endsAt?: string;
  timeTbd?: boolean;
  locationLabel: string;
  addressLine?: string;
  city?: string;
  summary: string;
  description?: string;
  whatToExpect?: string[];
  audienceTags: string[];
  mapCoordinates?: { lat: number; lng: number };
  relatedEventSlugs: string[];
  fieldAttendance?: "confirmed" | "tentative";
  statewideVirtual?: boolean;
  missingCounty?: boolean;
};

function campaignStop(draft: StopDraft): EventItem {
  const date = draft.startsAt.slice(0, 10);
  const tentative = draft.fieldAttendance === "tentative";
  return {
    slug: draft.slug,
    title: draft.title,
    type: draft.type,
    region: draft.region,
    countySlug: draft.countySlug,
    status: "upcoming",
    startsAt: draft.startsAt,
    endsAt: draft.endsAt ?? (draft.timeTbd ? `${date}T23:59:00` : undefined),
    timezone: TZ,
    locationLabel: draft.locationLabel,
    city: draft.city ?? (draft.statewideVirtual ? undefined : draft.locationLabel),
    addressLine: draft.addressLine,
    summary: draft.summary,
    description: draft.description ?? DETAILS_LATER,
    whatToExpect: draft.whatToExpect ?? ["Stop details will be added when the host confirms venue and program."],
    whoItsFor: "Neighbors, volunteers, and anyone who wants to meet the campaign on the trail.",
    organizerNote: tentative
      ? "September 2026 campaign timeline — tentative until confirmed."
      : "September 2026 campaign timeline — public facts only; details to be added.",
    audienceTags: draft.audienceTags,
    relatedEventSlugs: draft.relatedEventSlugs,
    relatedResourceHrefs: [
      { label: "Events calendar", href: "/events" },
      { label: "Get involved", href: "/get-involved" },
    ],
    mapCoordinates: draft.mapCoordinates,
    fieldAttendance: draft.fieldAttendance ?? "confirmed",
    campaignTrail: true,
    statewideVirtual: draft.statewideVirtual,
    attendanceType: draft.statewideVirtual ? "PUBLIC_OPEN" : undefined,
    eventSource: "movement",
    opsFlags: {
      timeTbd: draft.timeTbd,
      missingCounty: draft.statewideVirtual ? false : draft.missingCounty || !draft.countySlug,
      missingCoordinates: draft.statewideVirtual ? false : !draft.mapCoordinates,
    },
  };
}

/** Public September 2026 campaign timeline. Virtual series live in `recurring-virtual-series.ts`. */
export const september2026CampaignStops: EventItem[] = [
  campaignStop({
    slug: "madison-county-meeting-2026-09-03",
    title: "Madison County Meeting",
    type: "Community Conversation",
    region: "Northwest Arkansas",
    countySlug: "madison-county",
    startsAt: "2026-09-03T12:00:00",
    timeTbd: true,
    locationLabel: "Madison County (venue TBA)",
    summary: "Confirmed Madison County meeting. Time and venue to be posted.",
    description:
      "Thursday, September 3, 2026. Madison County meeting. Time and venue will be posted here when the host confirms them. All times are U.S. Central.",
    whatToExpect: [
      "Thursday, September 3. Time to be posted.",
      "Madison County, Northwest Arkansas. Venue to be posted.",
    ],
    audienceTags: ["Madison County", "Northwest Arkansas"],
    mapCoordinates: { lat: 36.0106, lng: -93.7232 },
    relatedEventSlugs: ["conway-county-fair-opening-night-2026-09-03"],
  }),
  campaignStop({
    slug: "conway-county-fair-opening-night-2026-09-03",
    title: "Conway County Fair Opening Night",
    type: "Fairs and Festivals",
    region: "Central Arkansas",
    countySlug: "conway-county",
    startsAt: "2026-09-03T18:00:00",
    endsAt: "2026-09-03T20:00:00",
    locationLabel: "Conway County Fair, Morrilton",
    city: "Morrilton",
    summary: "Thursday, September 3, 6:00–8:00 p.m. Central. Conway County Fair opening night in Morrilton.",
    description:
      "Thursday, September 3, 2026, 6:00–8:00 p.m. Central. Conway County Fair opening night in Morrilton. Fairgrounds details will be posted here when confirmed.",
    whatToExpect: [
      "Thursday, September 3, 6:00–8:00 p.m. Central.",
      "Conway County Fair, Morrilton.",
    ],
    audienceTags: ["Conway County", "Morrilton", "Festival"],
    mapCoordinates: { lat: 35.2648, lng: -92.6843 },
    relatedEventSlugs: ["madison-county-meeting-2026-09-03", "ashley-county-fair-2026-09-04"],
  }),
  campaignStop({
    slug: "ashley-county-fair-2026-09-04",
    title: "Ashley County Fair",
    type: "Fairs and Festivals",
    region: "Southeast Arkansas",
    countySlug: "ashley-county",
    startsAt: "2026-09-04T12:00:00",
    timeTbd: true,
    locationLabel: "Ashley County Fair",
    summary: "Tentative Ashley County Fair stop. Time and fairgrounds details to be posted if confirmed.",
    audienceTags: ["Ashley County", "Festival"],
    mapCoordinates: { lat: 33.2076, lng: -91.9312 },
    relatedEventSlugs: ["conway-county-fair-opening-night-2026-09-03", "festiville-jacksonville-2026-09-05"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "festiville-jacksonville-2026-09-05",
    title: "FestiVille",
    type: "Fairs and Festivals",
    region: "Central Arkansas",
    countySlug: "pulaski-county",
    startsAt: "2026-09-05T11:00:00",
    endsAt: "2026-09-05T15:00:00",
    locationLabel: "Jacksonville",
    city: "Jacksonville",
    summary: "Saturday 11:00 a.m. Central at FestiVille in Jacksonville.",
    audienceTags: ["Jacksonville", "Pulaski County", "Festival"],
    mapCoordinates: { lat: 34.8662, lng: -92.1101 },
    relatedEventSlugs: ["rector-labor-day-2026-09-06"],
  }),
  campaignStop({
    slug: "rector-labor-day-2026-09-06",
    title: "Rector Labor Day",
    type: "Fairs and Festivals",
    region: "Northeast Arkansas",
    countySlug: "clay-county",
    startsAt: "2026-09-06T12:00:00",
    timeTbd: true,
    locationLabel: "Rector",
    city: "Rector",
    summary: "Labor Day stop in Rector. Time and venue to be posted.",
    audienceTags: ["Clay County", "Rector", "Northeast Arkansas", "Festival"],
    mapCoordinates: { lat: 36.2631, lng: -90.2923 },
    relatedEventSlugs: ["festiville-jacksonville-2026-09-05", "roosevelt-dinner-2026-09-10"],
  }),
  campaignStop({
    slug: "roosevelt-dinner-2026-09-10",
    title: "Roosevelt Dinner",
    type: "Community Conversation",
    region: "Statewide",
    startsAt: "2026-09-10T18:00:00",
    endsAt: "2026-09-10T20:00:00",
    locationLabel: "Location to verify",
    city: "Location to verify",
    summary: "Thursday 6:00 p.m. Central Roosevelt Dinner. County and venue still to be verified before this stop can appear on the county map.",
    audienceTags: ["Dinner"],
    relatedEventSlugs: ["lafayette-county-softball-2026-09-11"],
    missingCounty: true,
  }),
  campaignStop({
    slug: "lafayette-county-softball-2026-09-11",
    title: "Fire Department vs. Police Department Softball Game",
    type: "Community Conversation",
    region: "Southwest Arkansas",
    countySlug: "lafayette-county",
    startsAt: "2026-09-11T18:00:00",
    endsAt: "2026-09-11T21:00:00",
    locationLabel: "Lafayette County",
    city: "Lafayette County",
    summary: "Friday 6:00 p.m. Central Fire Department vs. Police Department softball game in Lafayette County.",
    audienceTags: ["Lafayette County", "Southwest Arkansas"],
    mapCoordinates: { lat: 33.2412, lng: -93.6068 },
    relatedEventSlugs: ["cleveland-county-candidate-forum-2026-09-12"],
  }),
  campaignStop({
    slug: "cleveland-county-candidate-forum",
    title: "Candidate Forum",
    type: "Town Hall",
    region: "Southeast Arkansas",
    countySlug: "cleveland-county",
    startsAt: "2026-09-12T12:00:00",
    endsAt: "2026-09-12T14:00:00",
    locationLabel: "Cleveland County",
    city: "Cleveland County",
    summary: "Saturday noon Central candidate forum in Cleveland County.",
    audienceTags: ["Cleveland County", "Candidate Forum"],
    mapCoordinates: { lat: 33.8973, lng: -92.1851 },
    relatedEventSlugs: ["river-valley-candidate-rally-fort-smith-2026-09-13"],
  }),
  campaignStop({
    slug: "river-valley-candidate-rally-fort-smith-2026-09-13",
    title: "River Valley Candidate Rally",
    type: "Town Hall",
    region: "West Central Arkansas",
    countySlug: "sebastian-county",
    startsAt: "2026-09-13T12:00:00",
    endsAt: "2026-09-13T14:00:00",
    locationLabel: "Fort Smith",
    city: "Fort Smith",
    summary: "Sunday noon Central River Valley Candidate Rally in Fort Smith.",
    audienceTags: ["Fort Smith", "Sebastian County", "Rally"],
    mapCoordinates: { lat: 35.3859, lng: -94.3985 },
    relatedEventSlugs: ["baxter-county-candidate-forum-2026-09-14"],
  }),
  campaignStop({
    slug: "baxter-county-candidate-forum-2026-09-14",
    title: "Candidate Forum",
    type: "Town Hall",
    region: "North Central Arkansas",
    countySlug: "baxter-county",
    startsAt: "2026-09-14T18:00:00",
    endsAt: "2026-09-14T20:00:00",
    locationLabel: "Mountain Home",
    city: "Mountain Home",
    summary: "Monday 6:00 p.m. Central candidate forum in Mountain Home.",
    audienceTags: ["Mountain Home", "Baxter County", "Candidate Forum"],
    mapCoordinates: { lat: 36.3353, lng: -92.3851 },
    relatedEventSlugs: ["pope-county-registration-event-2026-09-15"],
  }),
  campaignStop({
    slug: "pope-county-registration-event-2026-09-15",
    title: "Registration Event",
    type: "Direct Democracy Briefing",
    region: "North Central Arkansas",
    countySlug: "pope-county",
    startsAt: "2026-09-15T15:00:00",
    endsAt: "2026-09-15T19:00:00",
    locationLabel: "Russellville",
    city: "Russellville",
    summary: "Tuesday 3:00–7:00 p.m. Central registration event in Russellville.",
    audienceTags: ["Russellville", "Pope County", "Voter registration"],
    mapCoordinates: { lat: 35.2784, lng: -93.1338 },
    relatedEventSlugs: ["hsv-candidate-forum-2026-09-16", "faith-and-reflection-zoom-2026-09-16"],
  }),
  campaignStop({
    slug: "hsv-candidate-forum-2026-09-16",
    title: "HSV Candidate Forum",
    type: "Town Hall",
    region: "Statewide",
    startsAt: "2026-09-16T14:00:00",
    endsAt: "2026-09-16T16:00:00",
    locationLabel: "HSV (city and county to verify)",
    city: "HSV",
    summary: "Wednesday 2:00 p.m. Central HSV candidate forum. City and county still to be verified before this stop can appear on the county map.",
    audienceTags: ["Candidate Forum"],
    relatedEventSlugs: ["faith-and-reflection-zoom-2026-09-16", "grassroots-guitar-strings-sherwood-2026-09-17"],
    missingCounty: true,
  }),
  campaignStop({
    slug: "grassroots-guitar-strings-sherwood-2026-09-17",
    title: "Grassroots & Guitar Strings",
    type: "Community Conversation",
    region: "Central Arkansas",
    countySlug: "pulaski-county",
    startsAt: "2026-09-17T18:00:00",
    timeTbd: true,
    locationLabel: "Sherwood",
    city: "Sherwood",
    summary: "Grassroots & Guitar Strings in Sherwood. Time to be posted.",
    audienceTags: ["Sherwood", "Pulaski County"],
    mapCoordinates: { lat: 34.8151, lng: -92.2243 },
    relatedEventSlugs: ["calhoun-county-fair-2026-09-18"],
  }),
  campaignStop({
    slug: "calhoun-county-fair-2026-09-18",
    title: "Calhoun County Fair",
    type: "Fairs and Festivals",
    region: "Southwest Arkansas",
    countySlug: "calhoun-county",
    startsAt: "2026-09-18T12:00:00",
    timeTbd: true,
    locationLabel: "Calhoun County Fair",
    city: "Hampton",
    summary: "Tentative Calhoun County Fair. Time and fairgrounds details to be posted if confirmed.",
    audienceTags: ["Calhoun County", "Festival"],
    mapCoordinates: { lat: 33.5379, lng: -92.4696 },
    relatedEventSlugs: ["little-rock-comic-con-2026-09-19", "hot-spring-county-cookout-2026-09-19"],
    fieldAttendance: "tentative",
  }),
  campaignStop({
    slug: "little-rock-comic-con-2026-09-19",
    title: "Little Rock Comic Con",
    type: "Fairs and Festivals",
    region: "Central Arkansas",
    countySlug: "pulaski-county",
    startsAt: "2026-09-19T09:00:00",
    endsAt: "2026-09-19T14:00:00",
    locationLabel: "Little Rock",
    city: "Little Rock",
    summary: "Saturday morning–2:00 p.m. Central at Little Rock Comic Con.",
    audienceTags: ["Little Rock", "Pulaski County", "Festival"],
    mapCoordinates: { lat: 34.7465, lng: -92.2896 },
    relatedEventSlugs: ["hot-spring-county-cookout-2026-09-19"],
  }),
  campaignStop({
    slug: "hot-spring-county-cookout-2026-09-19",
    title: "Hot Spring County Cookout",
    type: "Community Conversation",
    region: "West Central Arkansas",
    countySlug: "hot-spring-county",
    startsAt: "2026-09-19T17:00:00",
    endsAt: "2026-09-19T19:00:00",
    locationLabel: "Malvern",
    city: "Malvern",
    summary: "Saturday 5:00–7:00 p.m. Central cookout in Malvern.",
    audienceTags: ["Malvern", "Hot Spring County"],
    mapCoordinates: { lat: 34.3623, lng: -92.8132 },
    relatedEventSlugs: ["clark-county-multi-church-tour-2026-09-20"],
  }),
  campaignStop({
    slug: "clark-county-multi-church-tour-2026-09-20",
    title: "Multi-Church Tour",
    type: "Community Conversation",
    region: "Southwest Arkansas",
    countySlug: "clark-county",
    startsAt: "2026-09-20T09:00:00",
    endsAt: "2026-09-20T16:00:00",
    timeTbd: true,
    locationLabel: "Gurdon and Arkadelphia",
    city: "Gurdon / Arkadelphia",
    summary: "Sunday Clark County Multi-Church Tour, with stops in Gurdon and Arkadelphia.",
    description:
      "Public listing for the September 20 Multi-Church Tour in Clark County. Gurdon and Arkadelphia are both in Clark County, so this is one county stop with two city visits — not two unrelated events.",
    whatToExpect: [
      "Gurdon — church stop on the Multi-Church Tour",
      "Arkadelphia — church stop on the Multi-Church Tour",
      "Exact service times to be posted with host confirmation",
    ],
    audienceTags: ["Clark County", "Gurdon", "Arkadelphia"],
    mapCoordinates: { lat: 34.1209, lng: -93.0538 },
    relatedEventSlugs: ["little-river-county-stop-2026-09-21"],
  }),
  campaignStop({
    slug: "little-river-county-stop-2026-09-21",
    title: "Little River County stop",
    type: "Community Conversation",
    region: "Southwest Arkansas",
    countySlug: "little-river-county",
    startsAt: "2026-09-21T12:00:00",
    timeTbd: true,
    locationLabel: "Little River County (venue TBA)",
    summary: "Confirmed Little River County stop. Event title and time still to be posted.",
    audienceTags: ["Little River County"],
    mapCoordinates: { lat: 33.7001, lng: -94.2216 },
    relatedEventSlugs: ["press-freedom-gala-2026-09-22"],
  }),
  campaignStop({
    slug: "press-freedom-gala-2026-09-22",
    title: "Press Freedom Gala",
    type: "Community Conversation",
    region: "Statewide",
    startsAt: "2026-09-22T18:00:00",
    timeTbd: true,
    locationLabel: "Location to verify",
    city: "Location to verify",
    summary: "Tentative Press Freedom Gala. Location and time still needed — this date is not a Paragould candidate forum.",
    audienceTags: ["Press"],
    relatedEventSlugs: ["faith-and-reflection-zoom-2026-09-23"],
    fieldAttendance: "tentative",
    missingCounty: true,
  }),
  campaignStop({
    slug: "greene-county-candidate-forum-2026-09-26",
    title: "Candidate Forum",
    type: "Town Hall",
    region: "Northeast Arkansas",
    countySlug: "greene-county",
    startsAt: "2026-09-26T14:00:00",
    endsAt: "2026-09-26T16:00:00",
    locationLabel: "Paragould",
    city: "Paragould",
    summary: "Saturday 2:00 p.m. Central candidate forum in Paragould.",
    audienceTags: ["Paragould", "Greene County", "Candidate Forum"],
    mapCoordinates: { lat: 36.0584, lng: -90.4973 },
    relatedEventSlugs: ["little-flock-2026-09-27"],
  }),
  campaignStop({
    slug: "little-flock-2026-09-27",
    title: "Little Flock",
    type: "Community Conversation",
    region: "Northwest Arkansas",
    countySlug: "benton-county",
    startsAt: "2026-09-27T08:00:00",
    endsAt: "2026-09-27T10:00:00",
    locationLabel: "Little Flock",
    city: "Little Flock",
    summary: "Tentative 8:00 a.m. Central stop in Little Flock.",
    audienceTags: ["Little Flock", "Benton County", "Northwest Arkansas"],
    mapCoordinates: { lat: 36.3851, lng: -94.1355 },
    relatedEventSlugs: ["faith-and-reflection-zoom-2026-09-30"],
    fieldAttendance: "tentative",
  }),
];
