import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 3;
const L = "agent_intelligence_sprint3" as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "unified-agent-runtime", name: "Unified agent runtime", purpose: "Orchestrate intent → context → tools → response.", currentStatus: "functional", trigger: "askCampaignAgentAction", inputs: "AgentRuntimeRequest", outputs: "AgentRuntimeResponse", readsFrom: "campaign-agent-runtime.ts", writesTo: "agent-runtime-audit.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "No auto high-risk exec", deterministicHelperPath: "src/lib/agents/runtime/campaign-agent-runtime.ts", routesUsingTool: ["/admin/ai-command-center"], observationEvents: ["user_used_plain_language_request"], futureAutomationPath: "LLM layer optional", testChecklist: ["agents:test-runtime"] }),
  c({ id: "deterministic-intent-classifier", name: "Deterministic intent classifier", purpose: "Classify plain-language admin requests.", currentStatus: "functional", trigger: "Agent command palette", inputs: "message, pathname", outputs: "ClassifiedIntent", readsFrom: "intent-classifier.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No external profiling", deterministicHelperPath: "src/lib/agents/runtime/intent-classifier.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "LLM classify", testChecklist: [] }),
  c({ id: "safe-tool-router", name: "Safe tool router", purpose: "Select registry tools with guardrails.", currentStatus: "functional", trigger: "Runtime", inputs: "ClassifiedIntent", outputs: "ToolRouteResult", readsFrom: "tool-router.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Blocks auto-exec writes", deterministicHelperPath: "src/lib/agents/runtime/tool-router.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-execution-guard", name: "Tool execution guard", purpose: "Block high-risk tool auto-invocation.", currentStatus: "functional", trigger: "tool-router", inputs: "MasterToolRegistryEntry", outputs: "allowed boolean", readsFrom: "tool-execution-guard.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "Always on", deterministicHelperPath: "src/lib/agents/runtime/tool-execution-guard.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "agent-command-palette", name: "Agent command palette", purpose: "Admin UI for plain-language agent requests.", currentStatus: "functional", trigger: "Operator input", inputs: "message", outputs: "response panel", readsFrom: "AgentCommandPalette.tsx", writesTo: "audit", humanApprovalRequired: true, riskLevel: "low", guardrails: "Recommend only", deterministicHelperPath: "src/components/agents/AgentCommandPalette.tsx", routesUsingTool: ["/admin/campaign-manager-dashboard"], observationEvents: ["user_used_plain_language_request"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "ask-kelly-adapter", name: "Ask Kelly adapter", purpose: "Map public Ask Kelly tools to registry.", currentStatus: "partial", trigger: "Runtime bridge", inputs: "—", outputs: "AdapterToolMeta[]", readsFrom: "ask-kelly-adapter.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only bridge", deterministicHelperPath: "src/lib/agents/adapters/ask-kelly-adapter.ts", routesUsingTool: ["/api/assistant"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "kelly-agent-adapter", name: "Kelly Agent adapter", purpose: "Map admin Kelly Agent bundle to registry.", currentStatus: "partial", trigger: "Runtime bridge", inputs: "—", outputs: "AdapterToolMeta[]", readsFrom: "kelly-agent-adapter.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto bundle exec", deterministicHelperPath: "src/lib/agents/adapters/kelly-agent-adapter.ts", routesUsingTool: ["/api/admin/kelly-agent/recommend"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "memory-review-queue", name: "Memory review queue", purpose: "Human approve/reject memory candidates.", currentStatus: "functional", trigger: "memory-review page", inputs: "MemoryWritePlan", outputs: "JSON status", readsFrom: "memory-review-store.ts", writesTo: "agent-memory-review.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No vector write", deterministicHelperPath: "src/app/admin/(board)/ai-command-center/memory-review/page.tsx", routesUsingTool: ["/admin/ai-command-center/memory-review"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "runtime-audit-logger", name: "Runtime audit logger", purpose: "Append-only agent request audit.", currentStatus: "functional", trigger: "Runtime", inputs: "AgentRuntimeResponse", outputs: "RuntimeAuditEntry", readsFrom: "runtime-audit.ts", writesTo: "data/campaign-events/agent-runtime-audit.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "No secrets in message", deterministicHelperPath: "src/lib/agents/runtime/runtime-audit.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "page-aware-prompt-builder", name: "Page-aware prompt builder", purpose: "Suggested prompts per admin route.", currentStatus: "functional", trigger: "Palette mount", inputs: "pathname", outputs: "prompts[]", readsFrom: "page-aware-prompts.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/runtime/page-aware-prompts.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "agent-response-builder", name: "Agent response builder", purpose: "Format operator-facing response copy.", currentStatus: "functional", trigger: "Runtime", inputs: "plan + context", outputs: "markdown copy", readsFrom: "agent-response-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/runtime/agent-response-builder.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "high-risk-action-blocker", name: "High-risk action blocker", purpose: "Block send/approve/promote auto requests.", currentStatus: "functional", trigger: "Runtime", inputs: "message", outputs: "blocked reason", readsFrom: "tool-execution-guard.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "Hard block", deterministicHelperPath: "src/lib/agents/runtime/tool-execution-guard.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-link-recommender", name: "Operator link recommender", purpose: "Safe hrefs from intent + role.", currentStatus: "functional", trigger: "tool-router", inputs: "ClassifiedIntent", outputs: "actionLinks", readsFrom: "tool-router.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/runtime/tool-router.ts", routesUsingTool: [], observationEvents: ["next_action_clicked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "blocked-action-explainer", name: "Blocked action explainer", purpose: "Explain why auto-exec blocked.", currentStatus: "functional", trigger: "Runtime", inputs: "blockedActions", outputs: "copy", readsFrom: "agent-response-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/runtime/agent-response-builder.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-plan-summarizer", name: "Tool plan summarizer", purpose: "Summarize safe vs blocked plan steps.", currentStatus: "functional", trigger: "tool-planner", inputs: "ToolRouteResult", outputs: "AgentPlanStep[]", readsFrom: "tool-planner.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/runtime/tool-planner.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT3_AGENT_TOOL_CONTRACTS = TOOLS;
export const SPRINT3_AGENT_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
