import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 8;
const L = "campaign_finance_sprint8" as const;
const HELPERS = "src/lib/campaign-events/finance/finance-helpers.ts";
const ROUTES = ["/admin/campaign-events/[recordId]", "/admin/campaign-events/reimbursement", "/admin/candidate-dashboard", "/admin/campaign-manager-dashboard", "/admin/ai-command-center"] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

export const OBS_SPRINT8 = [
  "receipt_uploaded",
  "reimbursement_completed",
  "expense_flagged",
  "compliance_warning_detected",
  "financial_gap_detected",
  "audit_packet_generated",
  "receipt_missing_detected",
  "finance_risk_detected",
  "treasurer_review_requested",
  "campaign_spend_pattern_detected",
] as const;

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "event-budget-estimator", name: "Event budget estimator", purpose: "Seed exposure from travel ledger.", currentStatus: "functional", trigger: "Finance tab load", inputs: "CalendarSurfaceRow", outputs: "EventBudgetBlock", readsFrom: "ledger travel", writesTo: "_eventFinance.budget", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human save", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "expense-category-classifier", name: "Expense category classifier", purpose: "Classify expense text to category.", currentStatus: "functional", trigger: "Add expense", inputs: "description", outputs: "ExpenseCategory", readsFrom: "—", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Advisory", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "receipt-gap-detector", name: "Receipt gap detector", purpose: "Flag approved travel without receipts.", currentStatus: "functional", trigger: "Refresh readiness", inputs: "row + docs", outputs: "gaps[]", readsFrom: "finance documents", writesTo: "compliance.gaps", humanApprovalRequired: false, riskLevel: "medium", guardrails: "No auto-deny", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["receipt_missing_detected", "financial_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "reimbursement-readiness-scorer", name: "Reimbursement readiness scorer", purpose: "Month + event reimbursement readiness.", currentStatus: "functional", trigger: "Reimbursement page", inputs: "queues + report", outputs: "score/band", readsFrom: "travel queues", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: ["/admin/campaign-events/reimbursement"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "duplicate-expense-detector", name: "Duplicate expense detector", purpose: "Flag duplicate expense lines.", currentStatus: "partial", trigger: "Save finance", inputs: "expenses[]", outputs: "warnings", readsFrom: "_eventFinance", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["expense_flagged"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "duplicate-mileage-detector", name: "Duplicate mileage detector", purpose: "Same-day multiple mileage claims.", currentStatus: "functional", trigger: "Month ops load", inputs: "WorkbenchEventRow[]", outputs: "ReimbursementException[]", readsFrom: "ledger", writesTo: "reimbursement-ops", humanApprovalRequired: false, riskLevel: "medium", guardrails: "Flag only", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["finance_risk_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-spend-pattern-detector", name: "Campaign spend pattern detector", purpose: "County spend rollups.", currentStatus: "functional", trigger: "Finance snapshot", inputs: "rows by county", outputs: "countySpendNotes", readsFrom: "ledger", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-events/finance/load-campaign-finance-snapshot.ts", routesUsingTool: [...ROUTES], observationEvents: ["campaign_spend_pattern_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-spend-analyzer", name: "County spend analyzer", purpose: "Top counties by reimbursement.", currentStatus: "functional", trigger: "CM dashboard", inputs: "month rows", outputs: "notes[]", readsFrom: "ledger", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["campaign_spend_pattern_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-cost-anomaly-detector", name: "Event cost anomaly detector", purpose: "Reimbursement spikes vs median.", currentStatus: "functional", trigger: "Exception scan", inputs: "month amounts", outputs: "exceptions", readsFrom: "ledger", writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["finance_risk_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "compliance-risk-detector", name: "Compliance risk detector", purpose: "Warning level from gaps.", currentStatus: "functional", trigger: "Refresh finance", inputs: "compliance", outputs: "warningLevel", readsFrom: "_eventFinance", writesTo: "compliance", humanApprovalRequired: false, riskLevel: "medium", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["compliance_warning_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "receipt-followup-recommender", name: "Receipt follow-up recommender", purpose: "Next action for missing receipts.", currentStatus: "functional", trigger: "Gaps detected", inputs: "gaps[]", outputs: "recommendations", readsFrom: "compliance", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "No auto email", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["receipt_missing_detected"], futureAutomationPath: "Email scaffold", testChecklist: [] }),
  c({ id: "reimbursement-packet-builder", name: "Reimbursement packet builder", purpose: "Audit packet draft for month.", currentStatus: "functional", trigger: "Build packet", inputs: "month ctx", outputs: "ReimbursementPacketDraft", readsFrom: "report + docs", writesTo: "reimbursement-ops", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human triggers", deterministicHelperPath: HELPERS, routesUsingTool: ["/admin/campaign-events/reimbursement"], observationEvents: ["audit_packet_generated"], futureAutomationPath: "PDF export", testChecklist: [] }),
  c({ id: "finance-audit-trace-builder", name: "Finance audit trace builder", purpose: "Append audit history entries.", currentStatus: "functional", trigger: "Pipeline change", inputs: "action", outputs: "auditHistory", readsFrom: "reimbursement-ops", writesTo: "reimbursement-ops", humanApprovalRequired: true, riskLevel: "low", guardrails: "Append-only", deterministicHelperPath: "src/lib/campaign-events/finance/reimbursement-operations-store.ts", routesUsingTool: [...ROUTES], observationEvents: ["audit_packet_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "missing-documentation-detector", name: "Missing documentation detector", purpose: "Aggregate doc gaps.", currentStatus: "functional", trigger: "Treasurer panel", inputs: "snapshot", outputs: "blockers", readsFrom: "finance snapshot", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-events/finance/load-campaign-finance-snapshot.ts", routesUsingTool: [...ROUTES], observationEvents: ["financial_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "travel-expense-validator", name: "Travel expense validator", purpose: "Validate mileage + approval chain.", currentStatus: "functional", trigger: "Finance refresh", inputs: "row", outputs: "travelCompleteness", readsFrom: "ledger", writesTo: "compliance", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-finance-summary-builder", name: "Campaign finance summary builder", purpose: "Month finance rollup.", currentStatus: "functional", trigger: "Command center", inputs: "month", outputs: "CampaignFinanceSnapshot", readsFrom: "ledger + docs", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-events/finance/load-campaign-finance-snapshot.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "treasurer-review-preparer", name: "Treasurer review preparer", purpose: "Export readiness panel.", currentStatus: "functional", trigger: "Reimbursement page", inputs: "snapshot", outputs: "readiness label", readsFrom: "finance snapshot", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No FIN-1 post", deterministicHelperPath: HELPERS, routesUsingTool: ["/admin/campaign-events/reimbursement"], observationEvents: ["treasurer_review_requested"], futureAutomationPath: "Compliance bridge", testChecklist: [] }),
  c({ id: "financial-readiness-scorer", name: "Financial readiness scorer", purpose: "Event finance score 0-100.", currentStatus: "functional", trigger: "Save/refresh", inputs: "_eventFinance", outputs: "score + band", readsFrom: "finance + docs", writesTo: "compliance", humanApprovalRequired: false, riskLevel: "low", guardrails: "Advisory", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "expense-outlier-detector", name: "Expense outlier detector", purpose: "Alias for reimbursement spikes.", currentStatus: "functional", trigger: "Month scan", inputs: "amounts", outputs: "exceptions", readsFrom: "ledger", writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: ["expense_flagged"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-resource-efficiency-analyzer", name: "Campaign resource efficiency analyzer", purpose: "Volunteer/in-kind vs spend notes.", currentStatus: "partial", trigger: "Budget section", inputs: "budget block", outputs: "efficiency hint", readsFrom: "_eventFinance", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "LLM narrative", testChecklist: [] }),
];

export const SPRINT8_CAMPAIGN_FINANCE_TOOL_CONTRACTS = TOOLS;
export const SPRINT8_CAMPAIGN_FINANCE_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
