import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 13;
const L = "communications_system" as const;
const CM = "src/lib/campaign-events/communications/";
const ROUTES = ["/admin/communications", "/admin/workbench/email-command-center", "/admin/ai-command-center"] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "communications-system-inventory", name: "Communications system inventory", purpose: "Repo-wide email/comms inventory.", currentStatus: "functional", trigger: "Docs", inputs: "—", outputs: "inventory", readsFrom: "docs/campaign-events/EMAIL_SYSTEM_DEEP_INVENTORY.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}load-communications-bundle.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-provider-readiness-checker", name: "Email provider readiness checker", purpose: "SendGrid/Gmail/approval env gates.", currentStatus: "functional", trigger: "Comms center", inputs: "env", outputs: "EmailProviderReadinessReport", readsFrom: `${CM}email-provider-readiness.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No send", deterministicHelperPath: `${CM}email-provider-readiness.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: ["npm run campaign-events:test-email-readiness"] }),
  c({ id: "contact-source-discovery", name: "Contact source discovery", purpose: "Map all contact origins.", currentStatus: "functional", trigger: "Comms center", inputs: "—", outputs: "DiscoveredContactSource[]", readsFrom: `${CM}contact-source-discovery.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}contact-source-discovery.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "contact-normalizer", name: "Contact normalizer", purpose: "Normalize email + tags for V1 store.", currentStatus: "partial", trigger: "Import", inputs: "raw", outputs: "CampaignContact", readsFrom: `${CM}communications-types.ts`, writesTo: "contacts.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Consent review", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "ECC import", testChecklist: [] }),
  c({ id: "contact-deduper", name: "Contact deduper", purpose: "Flag duplicate emails across sources.", currentStatus: "idea", trigger: "Import commit", inputs: "contacts[]", outputs: "dupes", readsFrom: "prisma:EmailContactProfile", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "contact-consent-checker", name: "Contact consent checker", purpose: "Block send without consent label.", currentStatus: "partial", trigger: "Pre-send", inputs: "contact", outputs: "allowed", readsFrom: `${CM}communications-types.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "No send without consent", deterministicHelperPath: `${CM}email-provider-readiness.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "contact-segment-builder", name: "Contact segment builder", purpose: "Simple role/county segments.", currentStatus: "partial", trigger: "UI", inputs: "filter", outputs: "ContactSegment", readsFrom: `${CM}communications-store.ts`, writesTo: "segments.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "contact-list-health-scorer", name: "Contact list health scorer", purpose: "Score list suppression/consent health.", currentStatus: "idea", trigger: "List review", inputs: "list", outputs: "score", readsFrom: `${CM}communications-store.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-email-workflow-builder", name: "Volunteer email workflow builder", purpose: "Volunteer template + segment plan.", currentStatus: "partial", trigger: "Comms center", inputs: "workflow", outputs: "plan", readsFrom: "docs/COMMUNICATIONS_SYSTEM_COMPLETION_PLAN.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human send", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-team-email-workflow-builder", name: "Campaign team email workflow builder", purpose: "Role-aware team briefs.", currentStatus: "partial", trigger: "Comms center", inputs: "role", outputs: "plan", readsFrom: "tpl-team-daily-brief", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "host-email-workflow-builder", name: "Host email workflow builder", purpose: "Host follow-up drafts.", currentStatus: "partial", trigger: "Event drilldown", inputs: "event", outputs: "draft", readsFrom: "src/lib/campaign-events/email-draft-builder.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "mass-email-safety-guard", name: "Mass email safety guard", purpose: "Block all-contact sends by default.", currentStatus: "functional", trigger: "Any broadcast", inputs: "audience count", outputs: "blocked", readsFrom: `${CM}email-provider-readiness.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "Always block V1", deterministicHelperPath: `${CM}email-provider-readiness.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "sendgrid-readiness-checker", name: "SendGrid readiness checker", purpose: "ASM + from identity check.", currentStatus: "functional", trigger: "Readiness", inputs: "env", outputs: "sendgrid status", readsFrom: "src/lib/sendgrid/mail-send.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}email-provider-readiness.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "gmail-readiness-checker", name: "Gmail readiness checker", purpose: "OAuth + encryption env.", currentStatus: "functional", trigger: "Readiness", inputs: "env", outputs: "gmail status", readsFrom: `${CM}email-provider-readiness.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}email-provider-readiness.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-template-builder", name: "Email template builder", purpose: "CRUD communication templates.", currentStatus: "functional", trigger: "Comms center", inputs: "template", outputs: "CommunicationTemplate", readsFrom: `${CM}communications-store.ts`, writesTo: "templates.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-risk-scanner", name: "Email risk scanner", purpose: "Scan draft for compliance risks.", currentStatus: "partial", trigger: "Draft", inputs: "body", outputs: "risks[]", readsFrom: "CAMPAIGN_AI_HUMAN_CONTROL_RULES", writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "Advisory", deterministicHelperPath: "—", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-audience-reviewer", name: "Email audience reviewer", purpose: "Explain why audience selected.", currentStatus: "partial", trigger: "Pre-send", inputs: "segment", outputs: "explanation", readsFrom: `${CM}contact-source-discovery.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CM}load-communications-bundle.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-send-approval-gate", name: "Email send approval gate", purpose: "Human SEND APPROVED required.", currentStatus: "functional", trigger: "ECC send execution", inputs: "operator", outputs: "approved", readsFrom: "src/lib/email-command-center/send-execution.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "Typed confirmation", deterministicHelperPath: "src/lib/email-command-center/send-execution.ts", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-send-audit-logger", name: "Email send audit logger", purpose: "Append send audit rows.", currentStatus: "partial", trigger: "After send", inputs: "send meta", outputs: "CommunicationSendRecord", readsFrom: `${CM}communications-store.ts`, writesTo: "sends.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "Prisma EmailSendExecution", testChecklist: [] }),
  c({ id: "unsubscribe-suppression-checker", name: "Unsubscribe suppression checker", purpose: "Check suppressions before send.", currentStatus: "partial", trigger: "Pre-send", inputs: "emails[]", outputs: "blocked[]", readsFrom: "prisma:SendGridSuppression", writesTo: "—", humanApprovalRequired: false, riskLevel: "high", guardrails: "Required for broadcast", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-response-pathway-planner", name: "Email response pathway planner", purpose: "Reply handling plan.", currentStatus: "idea", trigger: "Gmail ingest", inputs: "thread", outputs: "pathway", readsFrom: "src/lib/email-workflow/", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No auto-reply", deterministicHelperPath: "—", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-dashboard-builder", name: "Communications dashboard builder", purpose: "Build comms center bundle.", currentStatus: "functional", trigger: "/admin/communications", inputs: "—", outputs: "CommunicationsBundle", readsFrom: `${CM}load-communications-bundle.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}load-communications-bundle.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-email-drafter", name: "Campaign email drafter", purpose: "Draft email from template + context.", currentStatus: "partial", trigger: "AI assist", inputs: "template, vars", outputs: "draft body", readsFrom: "src/lib/campaign-events/email-draft-builder.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-send", deterministicHelperPath: "src/lib/campaign-events/email-draft-builder.ts", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "kelly-voice-email-adapter", name: "Kelly voice email adapter", purpose: "Kelly-consistent tone for drafts.", currentStatus: "partial", trigger: "Draft", inputs: "text", outputs: "rewritten", readsFrom: "src/lib/agents/writing-agent/", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: "src/lib/agents/adapters/kelly-agent-adapter.ts", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-performance-learning-planner", name: "Email performance learning planner", purpose: "Plan learning from send metrics.", currentStatus: "idea", trigger: "Analytics", inputs: "SendGrid events", outputs: "learnings", readsFrom: "prisma:SendGridEvent", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_COMMUNICATIONS_TOOL_CONTRACTS = TOOLS;
export const SPRINT_COMMUNICATIONS_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
