import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 6;
const L = "event_planning_sprint6" as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const OBS_PLANNING = [
  "run_of_show_created",
  "pack_list_updated",
  "volunteer_plan_updated",
  "candidate_brief_generated",
  "cm_brief_generated",
  "planning_section_completed",
] as const;

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "run-of-show-generator", name: "Run of show generator", purpose: "Draft timeline rows from fact card.", currentStatus: "functional", trigger: "Generate ROS", inputs: "CalendarSurfaceRow", outputs: "RunOfShowRow[]", readsFrom: "factCard, calendar", writesTo: "_eventPlanning.runOfShow", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human saves", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: ["run_of_show_created"], futureAutomationPath: "LLM timeline", testChecklist: [] }),
  c({ id: "run-of-show-gap-detector", name: "Run of show gap detector", purpose: "Flag missing time/action/owner.", currentStatus: "functional", trigger: "After ROS save", inputs: "RunOfShowRow[]", outputs: "gaps[]", readsFrom: "event-planning", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "materials-pack-list-generator", name: "Materials pack list generator", purpose: "Build pack list from event type.", currentStatus: "functional", trigger: "Generate pack list", inputs: "factCard.what", outputs: "PackListItem[]", readsFrom: "factCard", writesTo: "_eventPlanning.packList", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human marks packed", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: ["pack_list_updated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-need-estimator", name: "Volunteer need estimator", purpose: "Estimate volunteers by event shape.", currentStatus: "functional", trigger: "Estimate volunteers", inputs: "event type", outputs: "VolunteerPlan", readsFrom: "factCard.who", writesTo: "_eventPlanning.volunteerPlan", humanApprovalRequired: true, riskLevel: "low", guardrails: "No auto SMS", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: ["volunteer_plan_updated"], futureAutomationPath: "Volunteer comms", testChecklist: [] }),
  c({ id: "contact-gap-detector", name: "Contact gap detector", purpose: "Missing host/venue/CP/emergency.", currentStatus: "functional", trigger: "Contacts section", inputs: "EventContacts", outputs: "gaps[]", readsFrom: "contacts + factCard", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-briefing-writer", name: "Candidate briefing writer", purpose: "Deterministic candidate brief.", currentStatus: "functional", trigger: "Generate brief", inputs: "row + planning", outputs: "CandidateBrief", readsFrom: "factCard, ROS", writesTo: "_eventPlanning.candidateBrief", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human edits before share", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: ["candidate_brief_generated"], futureAutomationPath: "LLM polish", testChecklist: [] }),
  c({ id: "campaign-manager-briefing-writer", name: "CM briefing writer", purpose: "Logistics brief for CM.", currentStatus: "functional", trigger: "Generate CM brief", inputs: "readiness + planning", outputs: "CampaignManagerBrief", readsFrom: "planning", writesTo: "_eventPlanning.cmBrief", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human approval", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: ["cm_brief_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-planning-readiness-scorer", name: "Event planning readiness scorer", purpose: "Completeness score + blockers.", currentStatus: "functional", trigger: "Drilldown load", inputs: "EventPlanningData", outputs: "PlanningReadinessResult", readsFrom: "planning + factCard", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Advisory only", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: ["planning_readiness_improved"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-risk-scanner", name: "Event risk scanner", purpose: "Conflicts, weather, approval gaps.", currentStatus: "functional", trigger: "Overview", inputs: "row", outputs: "risks[]", readsFrom: "ledger flags", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "logistics-next-action-recommender", name: "Logistics next action recommender", purpose: "Next best planning step.", currentStatus: "functional", trigger: "Readiness card", inputs: "missing, blockers", outputs: "actions[]", readsFrom: "readiness", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "house-meet-greet-planner", name: "House meet & greet planner", purpose: "Checklist for house events.", currentStatus: "partial", trigger: "Event type house", inputs: "title", outputs: "checklist", readsFrom: "calendar", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "speaking-event-planner", name: "Speaking event planner", purpose: "Checklist for speaking events.", currentStatus: "partial", trigger: "speaking slot", inputs: "factCard", outputs: "checklist", readsFrom: "what.speakingSlot", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "fundraiser-event-planner", name: "Fundraiser event planner", purpose: "Compliance + table checklist.", currentStatus: "partial", trigger: "fundraising flag", inputs: "why", outputs: "checklist", readsFrom: "factCard.why", writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "No FIN post", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "outdoor-event-weather-risk-checker", name: "Outdoor weather risk checker", purpose: "Flag outdoor weather risk.", currentStatus: "functional", trigger: "Risk scan", inputs: "title, location", outputs: "risk lines", readsFrom: "calendar", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "Weather API", testChecklist: [] }),
  c({ id: "event-owner-assignment-helper", name: "Event owner assignment helper", purpose: "Suggest ROS owners.", currentStatus: "functional", trigger: "CM brief", inputs: "runOfShow", outputs: "assignment text", readsFrom: "ROS", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human assigns", deterministicHelperPath: "src/lib/campaign-events/event-planning/event-planning-helpers.ts", routesUsingTool: [], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT6_EVENT_PLANNING_TOOL_CONTRACTS = TOOLS;
export const SPRINT6_EVENT_PLANNING_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
export { OBS_PLANNING };
