import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 14;
const L = "volunteer_system" as const;
const VM = "src/lib/campaign-events/volunteers/";
const ROUTES: string[] = ["/admin/volunteers", "/admin/ai-command-center", "/admin/campaign-manager-dashboard"];

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "volunteer-crm-inventory", name: "Volunteer CRM inventory", purpose: "Repo-wide volunteer artifact inventory.", currentStatus: "functional", trigger: "Docs", inputs: "—", outputs: "inventory", readsFrom: "docs/campaign-events/VOLUNTEER_CRM_DEEP_INVENTORY.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}load-volunteer-bundle.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-profile-builder", name: "Volunteer profile builder", purpose: "Build/normalize V1 volunteer profile.", currentStatus: "functional", trigger: "Add volunteer", inputs: "VolunteerProfileInput", outputs: "VolunteerProfile", readsFrom: `${VM}volunteer-profile-builder.ts`, writesTo: "volunteer-profiles.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Consent metadata", deterministicHelperPath: `${VM}volunteer-profile-builder.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_created"], futureAutomationPath: "Prisma VolunteerProfile", testChecklist: [] }),
  c({ id: "volunteer-skill-assessor", name: "Volunteer skill assessor", purpose: "Map interests to skills.", currentStatus: "partial", trigger: "Profile edit", inputs: "interests", outputs: "skills[]", readsFrom: `${VM}volunteer-types.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-profile-builder.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-availability-router", name: "Volunteer availability router", purpose: "Match availability to shifts.", currentStatus: "partial", trigger: "Assignment", inputs: "slots", outputs: "matches", readsFrom: `${VM}volunteer-types.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-assignment-engine.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-training-path-builder", name: "Volunteer training path builder", purpose: "Recommend next modules.", currentStatus: "functional", trigger: "Profile", inputs: "profile", outputs: "VolunteerTrainingPath", readsFrom: `${VM}volunteer-training-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-training-engine.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_training_started"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-assignment-recommender", name: "Volunteer assignment recommender", purpose: "Suggest event roles.", currentStatus: "functional", trigger: "Event drilldown", inputs: "EventVolunteerNeed", outputs: "recommendations[]", readsFrom: `${VM}volunteer-assignment-engine.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "No auto-assign", deterministicHelperPath: `${VM}volunteer-assignment-engine.ts`, routesUsingTool: [...ROUTES, "/admin/campaign-events/[recordId]"], observationEvents: ["volunteer_assignment_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-reliability-scorer", name: "Volunteer reliability scorer", purpose: "Score from assignment history.", currentStatus: "functional", trigger: "Profile", inputs: "assignments", outputs: "score", readsFrom: `${VM}volunteer-scoring.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Advisory", deterministicHelperPath: `${VM}volunteer-scoring.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-leadership-potential-detector", name: "Volunteer leadership potential detector", purpose: "Flag captain prospects.", currentStatus: "functional", trigger: "Review", inputs: "profile", outputs: "low|medium|high", readsFrom: `${VM}volunteer-scoring.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${VM}volunteer-scoring.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_leadership_flagged"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-recruitment-opportunity-detector", name: "Volunteer recruitment opportunity detector", purpose: "County/event recruit gaps.", currentStatus: "partial", trigger: "County intel", inputs: "KPIs", outputs: "opportunities", readsFrom: `${VM}load-volunteer-bundle.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}load-volunteer-bundle.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-followup-recommender", name: "Volunteer follow-up recommender", purpose: "Who needs follow-up.", currentStatus: "partial", trigger: "Command center", inputs: "store", outputs: "list", readsFrom: `${VM}load-volunteer-bundle.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto contact", deterministicHelperPath: `${VM}load-volunteer-bundle.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_followup_needed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-communication-drafter", name: "Volunteer communication drafter", purpose: "Draft-only volunteer messages.", currentStatus: "functional", trigger: "Profile comms", inputs: "workflowType", outputs: "VolunteerCommunicationDraft", readsFrom: `${VM}volunteer-communications-planner.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "No send", deterministicHelperPath: `${VM}volunteer-communications-planner.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "/admin/communications", testChecklist: [] }),
  c({ id: "volunteer-county-gap-detector", name: "Volunteer county gap detector", purpose: "Under-covered counties.", currentStatus: "functional", trigger: "Bundle", inputs: "county intel", outputs: "gaps[]", readsFrom: `${VM}load-volunteer-bundle.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}load-volunteer-bundle.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-event-staffing-estimator", name: "Volunteer event staffing estimator", purpose: "Gap vs needed headcount.", currentStatus: "functional", trigger: "Event", inputs: "eventId", outputs: "staffingGap", readsFrom: `${VM}load-event-volunteer-context.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${VM}volunteer-assignment-engine.ts`, routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-power-of-five-router", name: "Volunteer Power of 5 router", purpose: "Route P5 volunteers.", currentStatus: "partial", trigger: "P5 tab", inputs: "county", outputs: "plan", readsFrom: "src/lib/agents/county-intelligence/power-of-five-engine.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${VM}volunteer-communications-planner.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_power_of_five_started"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-onboarding-copilot", name: "Volunteer onboarding copilot", purpose: "Volunteer copilot def.", currentStatus: "functional", trigger: "Copilot", inputs: "—", outputs: "VolunteerCopilotDef", readsFrom: `${VM}volunteer-copilots.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-copilots.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "intern-onboarding-copilot", name: "Intern onboarding copilot", purpose: "Intern copilot def.", currentStatus: "functional", trigger: "Copilot", inputs: "—", outputs: "def", readsFrom: `${VM}volunteer-copilots.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-copilots.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "field-manager-copilot", name: "Field manager copilot", purpose: "Field manager copilot def.", currentStatus: "functional", trigger: "Copilot", inputs: "—", outputs: "def", readsFrom: `${VM}volunteer-copilots.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-copilots.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-coordinator-copilot", name: "Volunteer coordinator copilot", purpose: "Coordinator copilot def.", currentStatus: "functional", trigger: "Copilot", inputs: "—", outputs: "def", readsFrom: `${VM}volunteer-copilots.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-copilots.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "social-media-volunteer-router", name: "Social media volunteer router", purpose: "Tag social volunteers.", currentStatus: "partial", trigger: "Skills", inputs: "profile", outputs: "route", readsFrom: `${VM}volunteer-copilots.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-copilots.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-volunteer-router", name: "Communications volunteer router", purpose: "Comms volunteer tasks.", currentStatus: "partial", trigger: "Comms", inputs: "profile", outputs: "route", readsFrom: `${VM}volunteer-copilots.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-copilots.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-progress-level-tracker", name: "Volunteer progress level tracker", purpose: "Gamified level progression.", currentStatus: "functional", trigger: "Profile", inputs: "profile", outputs: "level", readsFrom: `${VM}volunteer-progression.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-progression.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-training-module-builder", name: "Volunteer training module builder", purpose: "Training registry.", currentStatus: "functional", trigger: "Training", inputs: "—", outputs: "modules[]", readsFrom: `${VM}volunteer-training-modules.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${VM}volunteer-training-modules.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_training_completed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-retention-risk-detector", name: "Volunteer retention risk detector", purpose: "Retention risk score.", currentStatus: "functional", trigger: "Bundle", inputs: "profile", outputs: "risk", readsFrom: `${VM}volunteer-scoring.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "Advisory", deterministicHelperPath: `${VM}volunteer-scoring.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-thank-you-generator", name: "Volunteer thank-you generator", purpose: "Draft thank-you.", currentStatus: "functional", trigger: "Post-event", inputs: "profile", outputs: "draft", readsFrom: `${VM}volunteer-communications-planner.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No send", deterministicHelperPath: `${VM}volunteer-communications-planner.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_thanked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-team-builder", name: "Volunteer team builder", purpose: "Build county teams.", currentStatus: "partial", trigger: "Teams", inputs: "county", outputs: "VolunteerTeam", readsFrom: `${VM}volunteer-storage.ts`, writesTo: "volunteer-teams.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: "src/lib/volunteer-ops/provision-solo-team.ts", routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_VOLUNTEER_TOOL_CONTRACTS = TOOLS;
export const SPRINT_VOLUNTEER_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
