import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 12;
const L = "county_intelligence_bridge" as const;
const CI = "src/lib/agents/county-intelligence/";
const ROUTES = [
  "/admin/ai-command-center",
  "/admin/campaign-manager-dashboard",
  "/admin/candidate-dashboard",
  "/admin/campaign-events/workbench",
  "/admin/campaign-events/[recordId]",
  "/admin/counties/[slug]",
] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "county-workbench-deep-reader", name: "County workbench deep reader", purpose: "Read-only bridge to countyWorkbench reports.", currentStatus: "functional", trigger: "Adapter load", inputs: "slug?", outputs: "county rows", readsFrom: `${CI}county-workbench-adapter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: `${CI}county-workbench-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Live API export", testChecklist: ["listCountyWorkbenchCounties"] }),
  c({ id: "county-kpi-normalizer", name: "County KPI normalizer", purpose: "Normalize workbench data to CountyNormalizedKpi.", currentStatus: "functional", trigger: "KPI load", inputs: "coverage+aligned", outputs: "CountyNormalizedKpi", readsFrom: `${CI}county-kpi-types.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Planning-estimate labeled", deterministicHelperPath: `${CI}county-workbench-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-goal-progress-calculator", name: "County goal progress calculator", purpose: "Registration/P5 progress when currents exist.", currentStatus: "partial", trigger: "Goals connected", inputs: "goal, current", outputs: "progress %", readsFrom: `${CI}county-workbench-adapter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-workbench-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "DB goals", testChecklist: [] }),
  c({ id: "county-weakness-detector", name: "County weakness detector", purpose: "Surface shell depth, low coverage, QA warnings.", currentStatus: "functional", trigger: "Engine", inputs: "CountyNormalizedKpi", outputs: "weaknesses[]", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-opportunity-ranker", name: "County opportunity ranker", purpose: "Rank persuasion and momentum counties.", currentStatus: "functional", trigger: "Statewide load", inputs: "counties[]", outputs: "ranked", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-readiness-scorer", name: "County readiness scorer", purpose: "Composite readiness from coverage+profile.", currentStatus: "functional", trigger: "KPI build", inputs: "coverage row", outputs: "readiness 0-100", readsFrom: `${CI}county-workbench-adapter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-workbench-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "power-of-five-gap-detector", name: "Power of 5 gap detector", purpose: "Detect relational organizing gaps.", currentStatus: "functional", trigger: "P5 engine", inputs: "county", outputs: "gap", readsFrom: `${CI}power-of-five-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}power-of-five-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "voter-registration-goal-tracker", name: "Voter registration goal tracker", purpose: "Track registration goals vs planning proxy.", currentStatus: "partial", trigger: "County goals", inputs: "slug", outputs: "reg summary", readsFrom: `${CI}county-workbench-adapter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No voter file writes", deterministicHelperPath: `${CI}county-workbench-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "CountyVoterMetrics", testChecklist: [] }),
  c({ id: "county-event-recommendation-builder", name: "County event recommendation builder", purpose: "Recommend events for weak counties.", currentStatus: "functional", trigger: "CM dashboard", inputs: "period", outputs: "recommendations", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-followup-action-builder", name: "County follow-up action builder", purpose: "Post-event follow-up from county context.", currentStatus: "functional", trigger: "Hot wash", inputs: "impact", outputs: "actions[]", readsFrom: `${CI}county-hotwash-impact.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-hotwash-impact.ts`, routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-leader-context-loader", name: "County leader context loader", purpose: "Links to leader/intelligence routes.", currentStatus: "partial", trigger: "Event drilldown", inputs: "slug", outputs: "leader links", readsFrom: `${CI}county-workbench-adapter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Verified only", deterministicHelperPath: `${CI}county-workbench-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-field-priority-ranker", name: "County field priority ranker", purpose: "Rank counties for field manager focus.", currentStatus: "functional", trigger: "Command center", inputs: "statewide", outputs: "heat list", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-dashboard-context-composer", name: "County dashboard context composer", purpose: "Compose panels for admin dashboards.", currentStatus: "functional", trigger: "Dashboard load", inputs: "—", outputs: "StatewideCountyIntelligence", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-to-event-strategy-adapter", name: "County to event strategy adapter", purpose: "Event planning county brief.", currentStatus: "functional", trigger: "Drilldown", inputs: "county name", outputs: "CountyIntelligenceSummary", readsFrom: `${CI}county-event-strategy.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-event-strategy.ts`, routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-hotwash-impact-analyzer", name: "County hot wash impact analyzer", purpose: "Compare event to county goals.", currentStatus: "functional", trigger: "Hot wash", inputs: "outcomes", outputs: "CountyHotWashImpactAnalysis", readsFrom: `${CI}county-hotwash-impact.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-hotwash-impact.ts`, routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-memory-enricher", name: "County memory enricher", purpose: "Workbench lines for county memory.", currentStatus: "functional", trigger: "Hot wash complete", inputs: "impact", outputs: "lines[]", readsFrom: `${CI}county-memory-enricher.ts`, writesTo: "county-memory advisory", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human save", deterministicHelperPath: `${CI}county-memory-enricher.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-progress-briefing-writer", name: "County progress briefing writer", purpose: "Plain-language county brief.", currentStatus: "functional", trigger: "Command center", inputs: "summary", outputs: "briefing text", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: ["/admin/ai-command-center"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "statewide-county-heatmap-builder", name: "Statewide county heatmap builder", purpose: "Top attention heat list.", currentStatus: "functional", trigger: "Statewide", inputs: "counties", outputs: "heatList", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-kpi-watchdog", name: "County KPI watchdog", purpose: "Flag stale/missing workbench bridge.", currentStatus: "functional", trigger: "Load", inputs: "bridge", outputs: "warnings", readsFrom: `${CI}county-workbench-path.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-workbench-path.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-action-plan-builder", name: "County action plan builder", purpose: "Per-county action plan.", currentStatus: "functional", trigger: "County slug", inputs: "slug", outputs: "CountyActionPlan", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_COUNTY_INTELLIGENCE_TOOL_CONTRACTS = TOOLS;
export const SPRINT_COUNTY_INTELLIGENCE_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
