import { contractToCatalogEntry, getContractById, type CampaignAiToolContract } from "./tool-contract";

export { getContractById };

const LIFECYCLE = "sprint4_approval_email" as const;
const SPRINT = 4;

export const SPRINT4_APPROVAL_EMAIL_TOOL_CONTRACTS: CampaignAiToolContract[] = [
  {
    id: "email-architecture-tracer",
    name: "Email architecture tracer",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Identify available mail providers/config and explain disabled/enabled state for operators.",
    trigger: "AI tools page · package preview load · dry-run script",
    inputs: "process.env (EMAIL_*, SENDGRID_*, APPROVAL_BASE_URL)",
    outputs: "Config summary DTO (no secrets)",
    readsFrom: "Env vars · SendGrid readiness helper",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Never log API keys; describe missing keys by name only",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/sprint4-tool-helpers.ts#traceEmailArchitecture",
    routesUsingTool: ["/admin/campaign-events/ai-tools", "/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: auto-detect Netlify vs local env drift and suggest fix copy",
    testChecklist: ["Shows disabled when EMAIL_SEND_ENABLED false", "Lists missing config keys"],
    priority: "P0",
  },
  {
    id: "approval-email-config-checker",
    name: "Approval email config checker",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Validate EMAIL_SEND_ENABLED, provider, from/reply-to, and base URL before any send.",
    trigger: "Send panel render · pre-send guard",
    inputs: "ApprovalEmailConfig",
    outputs: "readyToSend, missingConfig[], disabledReason",
    readsFrom: "approval-email-config.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Non-throwing on page load",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-email-config.ts",
    routesUsingTool: ["/admin/campaign-calendar/approval-package/[recordId]", "/admin/campaign-events/[recordId]"],
    observationEvents: ["approval_email_send_blocked", "ai_tool_invoked"],
    futureAutomationPath: "V2: preflight webhook before deploy",
    testChecklist: ["readyToSend false when send disabled", "Missing keys listed in UI"],
    priority: "P0",
  },
  {
    id: "approval-email-template-builder",
    name: "Approval email template builder",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Build professional HTML + plaintext approval package email with Kelly branding.",
    trigger: "Preview body · send package",
    inputs: "ApprovalPackagePayload · ApprovalEmailAssist · token links",
    outputs: "html, text bodies",
    readsFrom: "approval-package · approval-email-assist",
    writesTo: "— (ephemeral until send)",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "No unsourced opponent claims; GCal promotion disclaimer required",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-email-template.ts",
    routesUsingTool: ["/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["approval_email_generated", "ai_tool_invoked"],
    futureAutomationPath: "V2: learn preferred tone from operator-edited bodies",
    testChecklist: ["HTML + text both non-empty", "Footer disclaimer present"],
    priority: "P0",
  },
  {
    id: "approval-email-subject-writer",
    name: "Approval email subject writer",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Generate consistent subject lines from event title and date.",
    trigger: "Package build · email assist",
    inputs: "WorkbenchEventRow",
    outputs: "subject string",
    readsFrom: "calendar title · dateYmd",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Deterministic only",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-email-assist.ts",
    routesUsingTool: ["/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["approval_email_generated"],
    futureAutomationPath: "V2: A/B subject variants from acceptance rates",
    testChecklist: ["Subject includes event title"],
    priority: "P0",
  },
  {
    id: "approval-email-summary-writer",
    name: "Approval email summary writer",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Convert approval package into concise candidate-facing summary and risk language.",
    trigger: "Package build · public token page",
    inputs: "WorkbenchEventRow · conflicts · missing fields",
    outputs: "shortSummary, missingInfoLanguage, riskNote, plainEnglishPackage",
    readsFrom: "approval-summary-builder · row",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Suggestions only; human sends",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-email-assist.ts",
    routesUsingTool: ["/campaign-events/approval/[token]"],
    observationEvents: ["ai_summary_accepted", "ai_summary_edited"],
    futureAutomationPath: "V2: adapt phrasing to candidate preference observations",
    testChecklist: ["Missing fields reflected in copy"],
    priority: "P0",
  },
  {
    id: "approval-token-builder",
    name: "Approval token builder",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Create secure tokenized review and action links per recipient send.",
    trigger: "Successful send preflight (when enabled)",
    inputs: "recordId · packageLogId",
    outputs: "Token set (review, approve, deny, hold, request_info)",
    readsFrom: "approval-token-store.ts",
    writesTo: "data/campaign-events/approval-package-tokens.json",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "14-day TTL; action tokens single-use",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-token-store.ts",
    routesUsingTool: ["/campaign-events/approval/[token]"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: Prisma-backed tokens + per-recipient binding",
    testChecklist: ["URLs use APPROVAL_BASE_URL", "Review multi-use vs action single-use"],
    priority: "P0",
  },
  {
    id: "approval-token-validator",
    name: "Approval token validator",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Validate token status, expiry, and action before showing decision UI.",
    trigger: "Public approval page load · decision submit",
    inputs: "tokenId",
    outputs: "token status, canDecide boolean",
    readsFrom: "approval-token-store.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Revoked/expired/used rejected",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/load-approval-public-page.ts",
    routesUsingTool: ["/campaign-events/approval/[token]"],
    observationEvents: ["token_opened"],
    futureAutomationPath: "V2: signed JWT + revocation API",
    testChecklist: ["Expired token shows friendly message", "Used action token blocked"],
    priority: "P0",
  },
  {
    id: "approval-action-writer",
    name: "Approval action writer",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Apply approve/hold/deny/request-info to CampaignEventLedgerRecord only.",
    trigger: "Token decision confirm",
    inputs: "tokenId · optional note",
    outputs: "_review.decision on factCard",
    readsFrom: "approval-token-store · review-persistence",
    writesTo: "CampaignEventLedgerRecord.factCard._review",
    humanApprovalRequired: true,
    riskLevel: "high",
    guardrails: "No Google Calendar write; human click required",
    currentStatus: "functional",
    deterministicHelperPath: "src/app/campaign-events/approval/approval-token-actions.ts",
    routesUsingTool: ["/campaign-events/approval/[token]"],
    observationEvents: ["decision_approved", "decision_held", "decision_denied", "missing_info_requested"],
    futureAutomationPath: "V2: parse reply-by-email into structured decision",
    testChecklist: ["Approve writes approved", "Token marked used for action links"],
    priority: "P0",
  },
  {
    id: "approval-send-guard",
    name: "Approval send guard",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Block sending when config/provider/env incomplete or send disabled.",
    trigger: "sendApprovalPackageEmail · operator Send click",
    inputs: "ApprovalEmailConfig",
    outputs: "skipped_disabled log or proceed",
    readsFrom: "approval-email-config.ts",
    writesTo: "factCard._approvalEmailLog (skipped)",
    humanApprovalRequired: true,
    riskLevel: "blocked",
    guardrails: "Never call SendGrid when !readyToSend",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-email-send.ts",
    routesUsingTool: ["/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["approval_email_send_blocked"],
    futureAutomationPath: "V2: staged send queue with CM co-sign",
    testChecklist: ["EMAIL_SEND_ENABLED=false logs skipped", "UI button disabled"],
    priority: "P0",
  },
  {
    id: "approval-send-audit-logger",
    name: "Approval send audit logger",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Record send attempts, skipped sends, failures, and message IDs.",
    trigger: "Every send/dry-run/skip path",
    inputs: "recipients · subject · status · error",
    outputs: "ApprovalEmailLogEntry",
    readsFrom: "ledger row",
    writesTo: "factCard._approvalEmailLog",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No secret values in log meta",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-email-persist.ts",
    routesUsingTool: ["/admin/campaign-events/[recordId]", "/admin/candidate-dashboard"],
    observationEvents: ["approval_email_sent", "approval_email_send_failed", "approval_email_dry_run"],
    futureAutomationPath: "V2: export to compliance comms archive",
    testChecklist: ["Dry-run creates drafted entry", "Failed send stores error string"],
    priority: "P0",
  },
  {
    id: "approval-inbox-router",
    name: "Approval inbox router",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Surface pending/sent packages on candidate dashboard with status and preview links.",
    trigger: "Dashboard load",
    inputs: "Workbench rows · _approvalEmailLog",
    outputs: "ApprovalInboxItem[]",
    readsFrom: "load-campaign-events-dashboard.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Do not invent CM email",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/load-campaign-events-dashboard.ts",
    routesUsingTool: ["/admin/candidate-dashboard", "/admin/campaign-manager-dashboard"],
    observationEvents: ["approval_package_previewed"],
    futureAutomationPath: "V2: prioritize urgent events by risk score",
    testChecklist: ["packageStatus from last log", "awaitingCandidate when pending"],
    priority: "P1",
  },
  {
    id: "approval-email-risk-scanner",
    name: "Approval email risk scanner",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Detect missing fields, schedule conflicts, and work-hours warnings before send.",
    trigger: "Package build · send panel",
    inputs: "WorkbenchEventRow",
    outputs: "missingFields, conflicts, recommendedDecision",
    readsFrom: "approval-package · conflicts.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "medium",
    guardrails: "Flag only; no auto-deny",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/approval-package.ts",
    routesUsingTool: ["/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["operator_overrode_recommendation", "ai_tool_invoked"],
    futureAutomationPath: "V2: predict which packages need more info before send",
    testChecklist: ["Conflicts listed in package", "Hold recommended when conflicts"],
    priority: "P0",
  },
  {
    id: "approval-followup-recommender",
    name: "Approval follow-up recommender",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Suggest resend/follow-up timing based on last send and pending decision (scaffold).",
    trigger: "Package preview · inbox row",
    inputs: "lastEmailLog · rawDecision",
    outputs: "followUpHint string",
    readsFrom: "_approvalEmailLog",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Suggestion only; no auto-resend",
    currentStatus: "scaffolded",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/sprint4-tool-helpers.ts#recommendFollowUp",
    routesUsingTool: ["/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: optimal resend timing from observation history",
    testChecklist: ["Hint after sent + no decision"],
    priority: "P2",
  },
  {
    id: "approval-human-review-gate",
    name: "Approval human review gate",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Enforce human approval before any send or ledger decision from operator UI.",
    trigger: "Send · Resend · Review modal decisions",
    inputs: "operator session",
    outputs: "allowed / blocked UI state",
    readsFrom: "admin auth · human control policy",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "blocked",
    guardrails: "AI may not auto-send or auto-decide",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/tool-contract.ts",
    routesUsingTool: ["/admin/campaign-events/ai-tools", "/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["approval_email_send_blocked"],
    futureAutomationPath: "V2: role-based dual approval for CM send",
    testChecklist: ["Send requires button click", "No cron auto-send"],
    priority: "P0",
  },
  {
    id: "approval-google-write-blocker",
    name: "Approval Google write blocker",
    sprint: SPRINT,
    lifecycle: LIFECYCLE,
    version: "v1",
    purpose: "Ensure Sprint 4 approval paths never write to Google Calendar.",
    trigger: "All approval email + token paths",
    inputs: "code path registry",
    outputs: "assertNoGoogleWrite guard",
    readsFrom: "calendar sync writeEnabled flags",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "blocked",
    guardrails: "writeEnabled false on sync resolution; no GCal API in approval-email/*",
    currentStatus: "functional",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/sprint4-tool-helpers.ts#assertApprovalPathNoGoogleWrite",
    routesUsingTool: ["/campaign-events/approval/[token]", "/admin/campaign-calendar/approval-package/[recordId]"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "V2: static analysis check in CI",
    testChecklist: ["Token decision does not call GCal", "Send does not promote calendar"],
    priority: "P0",
  },
];

export const SPRINT4_APPROVAL_EMAIL_CATALOG_ENTRIES = SPRINT4_APPROVAL_EMAIL_TOOL_CONTRACTS.map(contractToCatalogEntry);
