/**
 * Kelly OS Intelligence sprint — copilots, training, progression, dashboard modules, tool builder.
 */
import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 12;
const L = "kelly_os_intelligence" as const;
const ROUTES = [
  "/admin/ai-command-center",
  "/admin/training",
  "/admin/onboarding",
  "/admin/ai-command-center/dashboard-builder",
  "/admin/ai-command-center/dashboard-builder/preview",
  "/admin/ai-command-center/tool-builder",
] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "role-copilot-engine", name: "Role copilot engine", purpose: "Lookup and recommend role copilots.", currentStatus: "functional", trigger: "Training/onboarding", inputs: "role", outputs: "RoleCopilotDefinition", readsFrom: "src/lib/agents/role-copilots/", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Guidance only", deterministicHelperPath: "src/lib/agents/role-copilots/role-copilot-engine.ts", routesUsingTool: [...ROUTES], observationEvents: ["role_copilot_opened"], futureAutomationPath: "", testChecklist: ["agents:test-role-copilots"] }),
  c({ id: "role-copilot-brief-builder", name: "Role copilot brief builder", purpose: "Daily brief per role.", currentStatus: "functional", trigger: "Command center", inputs: "role, context", outputs: "RoleCopilotBrief", readsFrom: "role-copilot-engine.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "role-copilot-engine.ts", routesUsingTool: [...ROUTES], observationEvents: ["role_copilot_opened"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-first-task-builder", name: "Role first task builder", purpose: "First 3 tasks by time/skill.", currentStatus: "functional", trigger: "Onboarding", inputs: "role, minutes", outputs: "tasks[]", readsFrom: "role-copilot-engine.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "role-copilot-engine.ts", routesUsingTool: [...ROUTES], observationEvents: ["onboarding_first_task_started"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-dashboard-module-mapper", name: "Role dashboard module mapper", purpose: "Map role level to dashboard blocks.", currentStatus: "functional", trigger: "Dashboard preview", inputs: "role, level", outputs: "blockIds[]", readsFrom: "progression/unlock-engine.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Registry only", deterministicHelperPath: "role-copilot-dashboard-map.ts", routesUsingTool: [...ROUTES], observationEvents: ["dashboard_module_added"], futureAutomationPath: "", testChecklist: ["agents:test-dashboard-modules"] }),
  c({ id: "role-escalation-router", name: "Role escalation router", purpose: "Escalation path from copilot registry.", currentStatus: "functional", trigger: "Guidance strip", inputs: "role", outputs: "escalation", readsFrom: "role-copilot-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "role-copilot-registry.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-copilot", name: "Volunteer copilot", purpose: "Volunteer role guidance.", currentStatus: "functional", trigger: "role=volunteer", inputs: "role", outputs: "copilot", readsFrom: "role-copilot-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No finance", deterministicHelperPath: "role-copilot-registry.ts", routesUsingTool: [...ROUTES], observationEvents: ["role_copilot_opened"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "intern-copilot", name: "Intern copilot", purpose: "Intern supervised tasks.", currentStatus: "functional", trigger: "role=intern", inputs: "role", outputs: "copilot", readsFrom: "role-copilot-registry.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Supervisor", deterministicHelperPath: "role-copilot-registry.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "field-manager-copilot", name: "Field manager copilot", purpose: "County/field guidance.", currentStatus: "functional", trigger: "County routes", inputs: "role", outputs: "copilot", readsFrom: "role-copilot-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "No voter export", deterministicHelperPath: "role-copilot-registry.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "social-media-copilot", name: "Social media copilot", purpose: "Draft-only social guidance.", currentStatus: "functional", trigger: "Social workbench", inputs: "role", outputs: "copilot", readsFrom: "role-copilot-registry.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-publish", deterministicHelperPath: "role-copilot-registry.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-lead-copilot", name: "Communications lead copilot", purpose: "Comms draft lanes.", currentStatus: "functional", trigger: "Comms center", inputs: "role", outputs: "copilot", readsFrom: "role-copilot-registry.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "EMAIL_SEND_ENABLED", deterministicHelperPath: "role-copilot-registry.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "training-module-registry", name: "Training module registry", purpose: "List training modules.", currentStatus: "functional", trigger: "Training center", inputs: "role", outputs: "modules[]", readsFrom: "training/training-module-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "training-module-registry.ts", routesUsingTool: ["/admin/training"], observationEvents: ["training_module_started"], futureAutomationPath: "", testChecklist: ["agents:test-training-layer"] }),
  c({ id: "training-path-builder", name: "Training path builder", purpose: "Ordered path per role.", currentStatus: "functional", trigger: "Training center", inputs: "role, skill", outputs: "path", readsFrom: "training-path-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "training-path-builder.ts", routesUsingTool: ["/admin/training"], observationEvents: ["training_path_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "training-unlock-engine", name: "Training unlock engine", purpose: "Unlock dashboard modules.", currentStatus: "functional", trigger: "Module complete", inputs: "completedIds", outputs: "blocks[]", readsFrom: "training-unlock-engine.ts", writesTo: "localStorage", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Guidance not permissions", deterministicHelperPath: "training-unlock-engine.ts", routesUsingTool: [...ROUTES], observationEvents: ["role_level_unlocked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "training-progress-tracker", name: "Training progress tracker", purpose: "Track module progress.", currentStatus: "functional", trigger: "Start/complete", inputs: "moduleId", outputs: "progress", readsFrom: "training-progress-store.ts", writesTo: "JSON/localStorage", humanApprovalRequired: false, riskLevel: "low", guardrails: "No PII", deterministicHelperPath: "training-progress-store.ts", routesUsingTool: ["/admin/training"], observationEvents: ["training_module_completed"], futureAutomationPath: "DB", testChecklist: [] }),
  c({ id: "ai-tutor-router", name: "AI tutor router", purpose: "Route to command palette tutor.", currentStatus: "partial", trigger: "Ask AI tutor", inputs: "moduleId", outputs: "palette query", readsFrom: "AgentCommandPalette", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: ["ai_command_palette_used"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "guided-training-walkthrough-builder", name: "Guided walkthrough builder", purpose: "Checklist walkthrough.", currentStatus: "partial", trigger: "Start module", inputs: "module", outputs: "steps", readsFrom: "training-modules-data.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-skill-assessment-agent", name: "Role skill assessment", purpose: "Map confidence to skill band.", currentStatus: "functional", trigger: "Onboarding V2", inputs: "profile", outputs: "skillLevel", readsFrom: "onboarding V2", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "role-onboarding-engine.ts", routesUsingTool: ["/admin/onboarding"], observationEvents: ["onboarding_role_selected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "available-time-training-router", name: "Available time router", purpose: "Time-boxed training path.", currentStatus: "functional", trigger: "hours/week", inputs: "minutes", outputs: "path", readsFrom: "training-path-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "buildTrainingPathForAvailableTime", routesUsingTool: ["/admin/training"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-level-registry", name: "Role level registry", purpose: "Progression tiers.", currentStatus: "functional", trigger: "Progress view", inputs: "role", outputs: "levels", readsFrom: "progression/role-level-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "role-level-registry.ts", routesUsingTool: [...ROUTES], observationEvents: ["role_level_unlocked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "progression-unlock-engine", name: "Progression unlock engine", purpose: "Compute unlocked modules.", currentStatus: "functional", trigger: "Training complete", inputs: "role, training", outputs: "modules", readsFrom: "unlock-engine.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Not RBAC", deterministicHelperPath: "unlock-engine.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "achievement-recorder", name: "Achievement recorder", purpose: "Record level achievements.", currentStatus: "functional", trigger: "Level up", inputs: "role, level", outputs: "achievement", readsFrom: "achievement-recorder.ts", writesTo: "memory", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "achievement-recorder.ts", routesUsingTool: [...ROUTES], observationEvents: ["role_level_unlocked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-unlock-manager", name: "Dashboard unlock manager", purpose: "Merge training + level unlocks.", currentStatus: "functional", trigger: "Preview", inputs: "progress", outputs: "blocks", readsFrom: "unlock-engine + training-unlock", writesTo: "localStorage", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: "unlock-engine.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-confidence-scorer", name: "Operator confidence scorer", purpose: "Score onboarding confidence.", currentStatus: "partial", trigger: "Onboarding", inputs: "profile", outputs: "score", readsFrom: "presentation-readiness-scorer", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-module-renderer", name: "Dashboard module renderer", purpose: "Render registry blocks.", currentStatus: "functional", trigger: "Preview page", inputs: "blockIds", outputs: "UI cards", readsFrom: "dashboard-component-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No codegen", deterministicHelperPath: "DashboardModulePreviewClient.tsx", routesUsingTool: ["/admin/ai-command-center/dashboard-builder/preview"], observationEvents: ["dashboard_module_added"], futureAutomationPath: "", testChecklist: ["agents:test-dashboard-modules"] }),
  c({ id: "dashboard-module-pin-manager", name: "Dashboard pin manager", purpose: "Pin modules on blueprint.", currentStatus: "functional", trigger: "Pin click", inputs: "blockId", outputs: "pinned[]", readsFrom: "localStorage", writesTo: "localStorage", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "DashboardModulePreviewClient.tsx", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-blueprint-saver", name: "Dashboard blueprint saver", purpose: "Save blueprint JSON.", currentStatus: "functional", trigger: "Save", inputs: "blueprint", outputs: "saveKey", readsFrom: "dashboard-blueprint-builder.ts", writesTo: "localStorage", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "dashboard-blueprint-builder.ts", routesUsingTool: [...ROUTES], observationEvents: ["dashboard_blueprint_saved"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "locked-module-explainer", name: "Locked module explainer", purpose: "Explain training lock.", currentStatus: "functional", trigger: "Locked module", inputs: "blockId", outputs: "training link", readsFrom: "training-unlock-engine.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "training-unlock-engine.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "simple-advanced-mode-router", name: "Simple/advanced mode router", purpose: "Toggle dashboard density.", currentStatus: "functional", trigger: "Mode toggle", inputs: "mode", outputs: "layout cap", readsFrom: "dashboard-layout-planner.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "dashboard-blueprint-builder.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-gap-detector", name: "Tool gap detector", purpose: "Detect gaps from observations.", currentStatus: "functional", trigger: "Tool builder", inputs: "observations", outputs: "tickets[]", readsFrom: "tool-builder-queue.ts", writesTo: "queue JSON", humanApprovalRequired: true, riskLevel: "low", guardrails: "Propose only", deterministicHelperPath: "detectToolGapsFromObservations", routesUsingTool: ["/admin/ai-command-center/tool-builder"], observationEvents: ["tool_gap_detected"], futureAutomationPath: "", testChecklist: ["agents:test-tool-builder"] }),
  c({ id: "tool-contract-drafter", name: "Tool contract drafter", purpose: "Draft contract text.", currentStatus: "partial", trigger: "Ticket create", inputs: "spec", outputs: "contract", readsFrom: "tool-contract.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-commit", deterministicHelperPath: "convertWorkflowProblemToToolSpec", routesUsingTool: [...ROUTES], observationEvents: ["tool_build_ticket_created"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-problem-to-tool-spec", name: "Workflow problem to tool spec", purpose: "Convert pain to spec.", currentStatus: "functional", trigger: "Gap detect", inputs: "problem", outputs: "ToolBuildTicket", readsFrom: "tool-builder-queue.ts", writesTo: "queue", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "convertWorkflowProblemToToolSpec", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-build-ticket-generator", name: "Tool build ticket generator", purpose: "Create queue ticket.", currentStatus: "functional", trigger: "Detect gap", inputs: "spec", outputs: "ticket", readsFrom: "tool-builder-queue.ts", writesTo: "ai-tool-builder-queue.json", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "createToolBuildTicket", routesUsingTool: ["/admin/ai-command-center/tool-builder"], observationEvents: ["tool_build_ticket_created"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-priority-scorer", name: "Tool priority scorer", purpose: "Score backlog priority.", currentStatus: "functional", trigger: "Ticket create", inputs: "ticket", outputs: "score", readsFrom: "scoreToolBuildPriority", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "tool-builder-queue.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-risk-reviewer", name: "Tool risk reviewer", purpose: "Flag high-risk specs.", currentStatus: "partial", trigger: "Review", inputs: "ticket", outputs: "risk", readsFrom: "CAMPAIGN_AI_HUMAN_CONTROL_RULES", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-test-plan-builder", name: "Tool test plan builder", purpose: "Suggest npm test script.", currentStatus: "partial", trigger: "Accept ticket", inputs: "tool id", outputs: "test plan", readsFrom: "package.json scripts", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "presentation-readiness-advisor", name: "Presentation readiness advisor", purpose: "Demo readiness score.", currentStatus: "functional", trigger: "Command center", inputs: "snapshot", outputs: "score", readsFrom: "presentation-readiness-scorer.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "presentation-readiness-scorer.ts", routesUsingTool: ["/admin/ai-command-center"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "route-polish-gap-detector", name: "Route polish gap detector", purpose: "Find nav gaps.", currentStatus: "partial", trigger: "Nav verify", inputs: "routes", outputs: "gaps", readsFrom: "agents:verify-campaign-os-nav", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "demo-path-builder", name: "Demo path builder", purpose: "Kelly demo walk order.", currentStatus: "partial", trigger: "Presentation", inputs: "audience", outputs: "steps", readsFrom: "PRESENTATION_READINESS_CHECKLIST.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-onboarding-scorer", name: "Operator onboarding scorer", purpose: "Score onboarding completeness.", currentStatus: "functional", trigger: "Onboarding complete", inputs: "profile V2", outputs: "score", readsFrom: "completeRoleOnboardingV2", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "role-onboarding-engine.ts", routesUsingTool: ["/admin/onboarding"], observationEvents: ["onboarding_role_selected"], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_KELLY_INTELLIGENCE_TOOL_CONTRACTS = TOOLS;
export const SPRINT_KELLY_INTELLIGENCE_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
