import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 14;
const L = "communications_system" as const;
const RI = "src/lib/communications/relationship-intelligence/";
const SEQ = "src/lib/communications/sequences/";
const WO = "src/lib/communications/writing-orchestration/";
const MEM = "src/lib/communications/memory/";
const CI = "src/lib/communications/";
const ROUTES = [
  "/admin/communications",
  "/admin/communications/intelligence",
  "/admin/communications/studio",
  "/admin/workbench/email-command-center",
  "/admin/ai-command-center/copilots",
  "/admin/county-intelligence",
] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v2_future", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "relationship-strength-engine", name: "Relationship strength engine", purpose: "Trust + strength scores from engagement.", currentStatus: "functional", trigger: "Graph build", inputs: "contact", outputs: "strengthScore", readsFrom: `${RI}relationship-strength-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Metadata only", deterministicHelperPath: `${RI}relationship-strength-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: ["relationship_warning_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-engagement-scorer", name: "Volunteer engagement scorer", purpose: "Score volunteer engagement from campaign metadata.", currentStatus: "functional", trigger: "Graph", inputs: "volunteer contact", outputs: "score", readsFrom: `${RI}engagement-scoring.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${RI}engagement-scoring.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "burnout-risk-detector", name: "Burnout risk detector", purpose: "Flag communication fatigue / burnout.", currentStatus: "functional", trigger: "Graph", inputs: "nodes", outputs: "risk", readsFrom: `${RI}engagement-scoring.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${SEQ}communication-fatigue-detector.ts`, routesUsingTool: [...ROUTES], observationEvents: ["burnout_warning_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "relationship-memory-builder", name: "Relationship memory builder", purpose: "Build human-reviewable relationship memory lines.", currentStatus: "functional", trigger: "Memory review", inputs: "node", outputs: "lines[]", readsFrom: `${RI}relationship-memory-builder.ts`, writesTo: "communications-memory.json", humanApprovalRequired: true, riskLevel: "low", guardrails: "Editable", deterministicHelperPath: `${RI}relationship-memory-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "outreach-history-composer", name: "Outreach history composer", purpose: "Compose send audit + touch history.", currentStatus: "functional", trigger: "Copilot", inputs: "node", outputs: "lines[]", readsFrom: `${MEM}outreach-history-composer.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${MEM}outreach-history-composer.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communication-sequence-builder", name: "Communication sequence builder", purpose: "Build human-reviewed outreach sequences.", currentStatus: "functional", trigger: "Copilot / intelligence", inputs: "type, audience", outputs: "CommunicationSequence", readsFrom: `${SEQ}communication-sequence-builder.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-send", deterministicHelperPath: `${SEQ}communication-sequence-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: ["communication_sequence_created", "communication_sequence_completed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communication-fatigue-detector", name: "Communication fatigue detector", purpose: "Warn on over-contacted supporters.", currentStatus: "functional", trigger: "Intelligence dashboard", inputs: "graph", outputs: "warnings[]", readsFrom: `${SEQ}communication-fatigue-detector.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${SEQ}communication-fatigue-detector.ts`, routesUsingTool: [...ROUTES], observationEvents: ["burnout_warning_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "followup-gap-detector", name: "Follow-up gap detector", purpose: "Detect overdue relationship follow-ups.", currentStatus: "functional", trigger: "Intelligence", inputs: "nodes", outputs: "gaps[]", readsFrom: `${SEQ}followup-gap-detector.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${SEQ}followup-gap-detector.ts`, routesUsingTool: [...ROUTES], observationEvents: ["communication_gap_detected", "followup_overdue_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "statewide-message-prioritizer", name: "Statewide message prioritizer", purpose: "Rank top comms priorities statewide.", currentStatus: "functional", trigger: "Intelligence", inputs: "context", outputs: "priorities[]", readsFrom: `${CI}communications-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}communications-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: ["communications_priority_viewed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-message-adapter", name: "County message adapter", purpose: "Adapt county intel to messaging.", currentStatus: "functional", trigger: "County comms", inputs: "slug", outputs: "angles", readsFrom: `${WO}county-message-adapter.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "County bridge read-only", deterministicHelperPath: `${WO}county-message-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: ["county_message_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "relationship-tone-adjuster", name: "Relationship tone adjuster", purpose: "Adjust tone by trust level.", currentStatus: "functional", trigger: "Writing", inputs: "trust", outputs: "tone", readsFrom: `${WO}relationship-tone-adjuster.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${WO}relationship-tone-adjuster.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-writing-router", name: "Campaign writing router", purpose: "Orchestrate drafts by audience/purpose/county.", currentStatus: "functional", trigger: "Message Studio", inputs: "WritingInput", outputs: "OrchestratedDraft", readsFrom: `${WO}campaign-writing-router.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-send", deterministicHelperPath: `${WO}campaign-writing-router.ts`, routesUsingTool: ["/admin/communications/studio", ...ROUTES], observationEvents: ["draft_generated", "draft_modified"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-cadence-engine", name: "Communications cadence engine", purpose: "Sequence touch cadence by type.", currentStatus: "functional", trigger: "Sequence build", inputs: "type", outputs: "days[]", readsFrom: `${SEQ}communication-cadence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${SEQ}communication-cadence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-risk-scanner", name: "Communications risk scanner", purpose: "Scan sequence + send readiness risks.", currentStatus: "functional", trigger: "Pre-send", inputs: "sequence", outputs: "risks[]", readsFrom: `${SEQ}sequence-risk-detector.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "Advisory", deterministicHelperPath: `${SEQ}sequence-risk-detector.ts`, routesUsingTool: [...ROUTES], observationEvents: ["relationship_warning_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-followup-coordinator", name: "Event follow-up coordinator", purpose: "Coordinate post-event comms sequence.", currentStatus: "functional", trigger: "Hot wash", inputs: "event", outputs: "sequence", readsFrom: `${SEQ}communication-sequence-builder.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CI}host-relationship-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: ["host_followup_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-welcome-sequence-builder", name: "Volunteer welcome sequence builder", purpose: "Onboarding sequence for new volunteers.", currentStatus: "functional", trigger: "Volunteer copilot", inputs: "audience", outputs: "sequence", readsFrom: `${CI}volunteer-communications-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}volunteer-communications-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: ["volunteer_outreach_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-retention-coach", name: "Volunteer retention coach", purpose: "Retention nudges without burnout.", currentStatus: "functional", trigger: "Intelligence", inputs: "volunteer", outputs: "draft", readsFrom: `${CI}volunteer-communications-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}volunteer-communications-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-outreach-prioritizer", name: "Volunteer outreach prioritizer", purpose: "Prioritize volunteer re-engagement.", currentStatus: "functional", trigger: "Graph", inputs: "volunteers", outputs: "list", readsFrom: `${RI}relationship-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${RI}relationship-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: ["volunteer_outreach_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-training-reminder-builder", name: "Volunteer training reminder builder", purpose: "Training nudge sequence.", currentStatus: "functional", trigger: "Training", inputs: "name", outputs: "sequence", readsFrom: `${CI}volunteer-communications-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}volunteer-communications-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "host-onboarding-sequence-builder", name: "Host onboarding sequence builder", purpose: "Host onboarding comms plan.", currentStatus: "functional", trigger: "Host copilot", inputs: "host", outputs: "sequence", readsFrom: `${CI}host-relationship-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CI}host-relationship-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "host-event-prep-coordinator", name: "Host event prep coordinator", purpose: "Prep draft for hosts before events.", currentStatus: "functional", trigger: "Drilldown", inputs: "host, event", outputs: "draft", readsFrom: `${CI}host-relationship-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CI}host-relationship-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "host-followup-builder", name: "Host follow-up builder", purpose: "Post-event host follow-up sequence.", currentStatus: "functional", trigger: "Hot wash", inputs: "host", outputs: "sequence", readsFrom: `${CI}host-relationship-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CI}host-relationship-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: ["host_followup_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-communications-gap-detector", name: "County communications gap detector", purpose: "Weak county comms gaps.", currentStatus: "functional", trigger: "Intelligence", inputs: "—", outputs: "briefs[]", readsFrom: `${CI}county-communications-intelligence.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only county", deterministicHelperPath: `${CI}county-communications-intelligence.ts`, routesUsingTool: [...ROUTES], observationEvents: ["communication_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-issue-summary-builder", name: "County issue summary builder", purpose: "County issue summary for comms.", currentStatus: "functional", trigger: "County", inputs: "slug", outputs: "summary", readsFrom: `${WO}county-message-adapter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${WO}county-message-adapter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-event-promotion-builder", name: "County event promotion builder", purpose: "County event promotion copy draft.", currentStatus: "functional", trigger: "Event promotion copilot", inputs: "slug", outputs: "idea", readsFrom: `${CI}county-communications-intelligence.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${CI}county-communications-intelligence.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "power-of-five-message-builder", name: "Power of 5 message builder", purpose: "PO5 outreach language from county intel.", currentStatus: "functional", trigger: "PO5 copilot", inputs: "slug", outputs: "ask", readsFrom: `${WO}county-message-adapter.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "Human approval", deterministicHelperPath: `${CI}volunteer-communications-workflows.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-manager-briefing-builder", name: "Campaign manager briefing builder", purpose: "CM statewide comms brief.", currentStatus: "functional", trigger: "Team briefing", inputs: "—", outputs: "priorities", readsFrom: `${CI}communications-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}communications-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-lead-daily-priorities", name: "Communications lead daily priorities", purpose: "Daily comms lead priority list.", currentStatus: "functional", trigger: "Comms lead copilot", inputs: "—", outputs: "guidance", readsFrom: `${CI}communications-copilot-applications.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}communications-copilot-applications.ts`, routesUsingTool: [...ROUTES], observationEvents: ["communications_priority_viewed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-message-briefing-builder", name: "Candidate message briefing builder", purpose: "Candidate messaging brief.", currentStatus: "functional", trigger: "Candidate copilot", inputs: "—", outputs: "draft hints", readsFrom: `${CI}communications-copilot-applications.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Fatigue protection", deterministicHelperPath: `${WO}campaign-writing-router.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "subject-line-optimizer", name: "Subject line optimizer", purpose: "Purpose-aware subject lines.", currentStatus: "functional", trigger: "Message Studio", inputs: "purpose", outputs: "subject", readsFrom: `${WO}subject-line-optimizer.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${WO}subject-line-optimizer.ts`, routesUsingTool: ["/admin/communications/studio"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "cta-builder", name: "CTA builder", purpose: "Audience-safe CTAs.", currentStatus: "functional", trigger: "Writing", inputs: "purpose", outputs: "cta", readsFrom: `${WO}cta-builder.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${WO}cta-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "audience-tone-engine", name: "Audience tone engine", purpose: "Resolve tone by audience/urgency.", currentStatus: "functional", trigger: "Writing", inputs: "audience", outputs: "tone", readsFrom: `${WO}audience-tone-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${WO}audience-tone-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "urgency-language-adjuster", name: "Urgency language adjuster", purpose: "Adjust urgency without pressure.", currentStatus: "functional", trigger: "Writing", inputs: "urgency", outputs: "tone", readsFrom: `${WO}audience-tone-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${WO}audience-tone-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-overload-detector", name: "Communications overload detector", purpose: "Operator overwhelm from comms queue.", currentStatus: "functional", trigger: "Intelligence", inputs: "fatigue", outputs: "warn", readsFrom: `${SEQ}communication-fatigue-detector.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}communications-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communication-workflow-gap-detector", name: "Communication workflow gap detector", purpose: "Detect missing workflow steps.", currentStatus: "functional", trigger: "Intelligence", inputs: "bundle", outputs: "gaps", readsFrom: `${CI}communications-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${SEQ}followup-gap-detector.ts`, routesUsingTool: [...ROUTES], observationEvents: ["communication_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-tool-gap-detector", name: "Communications tool gap detector", purpose: "Flag partial comms tools in catalog.", currentStatus: "partial", trigger: "Tool builder", inputs: "catalog", outputs: "gaps", readsFrom: "ai-tools-supplement.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/tool-builder/tool-builder-queue.ts", routesUsingTool: [...ROUTES], observationEvents: ["tool_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "relationship-graph-builder", name: "Relationship graph builder", purpose: "Build relationship graph from contacts.", currentStatus: "functional", trigger: "Intelligence load", inputs: "store", outputs: "RelationshipGraph", readsFrom: `${RI}relationship-intelligence-engine.ts`, writesTo: "relationship-graph.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "No inbox scrape", deterministicHelperPath: `${RI}relationship-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: ["communications:test-relationships"] }),
  c({ id: "communications-intelligence-composer", name: "Communications intelligence composer", purpose: "Compose intelligence dashboard context.", currentStatus: "functional", trigger: "/admin/communications/intelligence", inputs: "—", outputs: "context", readsFrom: `${CI}communications-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}communications-intelligence-engine.ts`, routesUsingTool: ["/admin/communications/intelligence"], observationEvents: ["communications_priority_viewed"], futureAutomationPath: "", testChecklist: ["communications:test-intelligence"] }),
  c({ id: "message-studio-draft-assist", name: "Message studio draft assist", purpose: "Message Studio orchestrated drafts.", currentStatus: "functional", trigger: "Studio", inputs: "audience, purpose", outputs: "draft", readsFrom: `${WO}campaign-writing-router.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No send button", deterministicHelperPath: "/admin/communications/studio", routesUsingTool: ["/admin/communications/studio"], observationEvents: ["message_studio_opened", "draft_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "unresolved-followup-detector", name: "Unresolved follow-up detector", purpose: "Memory + graph unresolved outreach.", currentStatus: "functional", trigger: "Memory", inputs: "—", outputs: "list", readsFrom: `${MEM}unresolved-followup-detector.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${MEM}unresolved-followup-detector.ts`, routesUsingTool: [...ROUTES], observationEvents: ["followup_overdue_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communication-purpose-engine", name: "Communication purpose engine", purpose: "Describe outreach purpose.", currentStatus: "functional", trigger: "Writing", inputs: "purpose", outputs: "text", readsFrom: `${WO}communication-purpose-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${WO}communication-purpose-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_COMMUNICATIONS_INTELLIGENCE_V2_TOOL_CONTRACTS = TOOLS;
export const SPRINT_COMMUNICATIONS_INTELLIGENCE_V2_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
