import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 9;
const L = "dashboard_nav_sprint9" as const;
const LIB = "src/lib/dashboard-orchestration/";
const ROUTES = [
  "/admin/campaign-manager-dashboard",
  "/admin/candidate-dashboard",
  "/admin/campaign-events/workbench",
  "/admin/campaign-events/reimbursement",
  "/admin/ai-command-center",
] as const;

export const OBS_DASHBOARD_NAV = [
  "dashboard_focus_changed",
  "workflow_reentry_detected",
  "operator_overwhelm_detected",
  "navigation_shortcut_used",
  "ai_command_palette_used",
  "workflow_guidance_followed",
  "workflow_guidance_ignored",
  "dashboard_card_collapsed",
  "dashboard_card_expanded",
  "operator_focus_mode_entered",
] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "adaptive-dashboard-orchestrator", name: "Adaptive dashboard orchestrator", purpose: "Reorder and emphasize dashboard cards by role and blockers.", currentStatus: "functional", trigger: "Dashboard load", inputs: "snapshot, role, observations", outputs: "AdaptiveDashboardPlan", readsFrom: "adaptive-dashboard-orchestrator.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "UI only", deterministicHelperPath: `${LIB}adaptive-dashboard-orchestrator.ts`, routesUsingTool: [...ROUTES], observationEvents: ["dashboard_focus_changed"], futureAutomationPath: "ML ranker", testChecklist: [] }),
  c({ id: "workflow-router-v1", name: "Workflow router V1", purpose: "Recommend next page and workflow from system state.", currentStatus: "functional", trigger: "Nav bundle load", inputs: "pathname, snapshot", outputs: "WorkflowRouteRecommendation[]", readsFrom: "workflow-router-v1.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Recommend only", deterministicHelperPath: `${LIB}workflow-router-v1.ts`, routesUsingTool: [...ROUTES], observationEvents: ["navigation_shortcut_used"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-context-session-manager", name: "Operator context session manager", purpose: "Persist month, paths, palette history, focus mode.", currentStatus: "functional", trigger: "Client navigation", inputs: "localStorage", outputs: "OperatorContextSession", readsFrom: "operator-context-session.ts", writesTo: "browser localStorage", humanApprovalRequired: false, riskLevel: "low", guardrails: "No PII", deterministicHelperPath: `${LIB}operator-context-session.ts`, routesUsingTool: [...ROUTES], observationEvents: ["dashboard_focus_changed"], futureAutomationPath: "Server session", testChecklist: [] }),
  c({ id: "operator-cognitive-load-analyzer", name: "Operator cognitive load analyzer", purpose: "Detect overload, route bounce, warning flood.", currentStatus: "functional", trigger: "Bundle load", inputs: "observations, panel count", outputs: "cognitive load score", readsFrom: "operator-cognitive-load-analyzer.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Advisory", deterministicHelperPath: `${LIB}operator-cognitive-load-analyzer.ts`, routesUsingTool: [...ROUTES], observationEvents: ["operator_overwhelm_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-guidance-generator", name: "Workflow guidance generator", purpose: "Plain-language guidance cards with routes.", currentStatus: "functional", trigger: "Dashboard surfaces", inputs: "snapshot", outputs: "WorkflowGuidanceCard[]", readsFrom: "workflow-guidance-generator.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}workflow-guidance-generator.ts`, routesUsingTool: [...ROUTES], observationEvents: ["workflow_guidance_followed", "workflow_guidance_ignored"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-priority-ranker", name: "Dashboard priority ranker", purpose: "Rank card emphasis primary/secondary/collapsed.", currentStatus: "functional", trigger: "Adaptive plan", inputs: "AdaptiveDashboardPlan", outputs: "cardPriorities", readsFrom: "adaptive-dashboard-orchestrator.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}adaptive-dashboard-orchestrator.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "executive-summary-builder", name: "Executive summary builder", purpose: "What matters / blocked / ready strip per surface.", currentStatus: "functional", trigger: "Page header", inputs: "surface, snapshot", outputs: "ExecutiveSummary", readsFrom: "executive-summary-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}executive-summary-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-focus-state-manager", name: "Operator focus state manager", purpose: "Toggle focus mode to collapse low-priority panels.", currentStatus: "functional", trigger: "Nav rail", inputs: "focusMode boolean", outputs: "UI state", readsFrom: "OperatorContextProvider.tsx", writesTo: "localStorage", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/components/admin/navigation/OperatorContextProvider.tsx", routesUsingTool: [...ROUTES], observationEvents: ["operator_focus_mode_entered"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "navigation-simplification-engine", name: "Navigation simplification engine", purpose: "Workflow-grouped Campaign OS left rail.", currentStatus: "functional", trigger: "Admin shell", inputs: "nav config", outputs: "CampaignOsNavGroup[]", readsFrom: "campaign-os-nav-config.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}campaign-os-nav-config.ts`, routesUsingTool: [...ROUTES], observationEvents: ["navigation_shortcut_used"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-clutter-detector", name: "Dashboard clutter detector", purpose: "Flag too many visible panels.", currentStatus: "functional", trigger: "Cognitive load", inputs: "panelCount", outputs: "panel_overload signal", readsFrom: "operator-cognitive-load-analyzer.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}operator-cognitive-load-analyzer.ts`, routesUsingTool: [...ROUTES], observationEvents: ["operator_overwhelm_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "route-bounce-detector", name: "Route bounce detector", purpose: "Detect repeated same-page returns.", currentStatus: "functional", trigger: "Observations", inputs: "user_returned_to_same_page", outputs: "route_bounce signal", readsFrom: "operator-cognitive-load-analyzer.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}operator-cognitive-load-analyzer.ts`, routesUsingTool: [...ROUTES], observationEvents: ["workflow_reentry_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-friction-simplifier", name: "Workflow friction simplifier", purpose: "Collapse sections when calm mode recommended.", currentStatus: "functional", trigger: "calmModeRecommended", inputs: "adaptive plan", outputs: "collapsed card ids", readsFrom: "adaptive-dashboard-orchestrator.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}adaptive-dashboard-orchestrator.ts`, routesUsingTool: [...ROUTES], observationEvents: ["dashboard_card_collapsed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-aware-dashboard-builder", name: "Role-aware dashboard builder", purpose: "Candidate vs CM card emphasis.", currentStatus: "functional", trigger: "Dashboard load", inputs: "role", outputs: "AdaptiveDashboardPlan", readsFrom: "adaptive-dashboard-orchestrator.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}adaptive-dashboard-orchestrator.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "ai-command-palette-router", name: "AI command palette router", purpose: "Global Cmd+K palette with deterministic reimbursement routing.", currentStatus: "functional", trigger: "Ctrl+K", inputs: "query, period", outputs: "PaletteQueryResult | agent response", readsFrom: "palette-query-router.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "No autonomous execution", deterministicHelperPath: `${LIB}palette-query-router.ts`, routesUsingTool: [...ROUTES], observationEvents: ["ai_command_palette_used"], futureAutomationPath: "LLM router", testChecklist: [] }),
  c({ id: "operational-calm-layout-engine", name: "Operational calm layout engine", purpose: "Spacing, hierarchy, progressive disclosure pass.", currentStatus: "functional", trigger: "Sprint 9 UI", inputs: "—", outputs: "calm CSS patterns", readsFrom: "ExecutiveSummaryStrip.tsx", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/components/admin/navigation/", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "next-best-action-explainer", name: "Next best action explainer", purpose: "Explain top workflow route in executive summary.", currentStatus: "functional", trigger: "Executive summary", inputs: "top route", outputs: "aiExplanation", readsFrom: "executive-summary-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}executive-summary-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-attention-manager", name: "Dashboard attention manager", purpose: "Surface top 3 actions before tables.", currentStatus: "functional", trigger: "Adaptive plan", inputs: "workflow routes", outputs: "topActions", readsFrom: "adaptive-dashboard-orchestrator.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}adaptive-dashboard-orchestrator.ts`, routesUsingTool: [...ROUTES], observationEvents: ["dashboard_focus_changed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-overwhelm-detector", name: "Operator overwhelm detector", purpose: "Emit overwhelm when cognitive load score high.", currentStatus: "functional", trigger: "Load score >= 55", inputs: "cognitive load", outputs: "observation", readsFrom: "operator-cognitive-load-analyzer.ts", writesTo: "user-observations.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}operator-cognitive-load-analyzer.ts`, routesUsingTool: [...ROUTES], observationEvents: ["operator_overwhelm_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-reentry-helper", name: "Workflow reentry helper", purpose: "Recent paths in nav for abandoned flow recovery.", currentStatus: "functional", trigger: "Context session", inputs: "recentPaths", outputs: "nav links", readsFrom: "operator-context-session.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}operator-context-session.ts`, routesUsingTool: [...ROUTES], observationEvents: ["workflow_reentry_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "system-focus-prioritizer", name: "System focus prioritizer", purpose: "Align nav badges with snapshot blockers.", currentStatus: "functional", trigger: "Nav bundle", inputs: "snapshot", outputs: "navBadges", readsFrom: "load-dashboard-navigation-bundle.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${LIB}load-dashboard-navigation-bundle.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT9_DASHBOARD_NAV_TOOL_CONTRACTS = TOOLS;
export const SPRINT9_DASHBOARD_NAV_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
