/**
 * Email OS Agent Tool Suite — unified catalog for ECC, SendGrid, inbox workflow, Campaign OS comms.
 * Human-gated: draft, score, route, prepare — never autonomous mass send.
 */
import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 15;
const L = "email_os_suite" as const;
const H = "src/lib/campaign-events/ai-tools/email-os-tool-helpers.ts";
const ECC = "src/lib/email-command-center/";
const EW = "src/lib/email-workflow/";
const SG = "src/lib/sendgrid/";
const CM = "src/lib/campaign-events/communications/";
const COM = "src/lib/communications/";

const ROUTES = [
  "/admin/workbench/email-command-center",
  "/admin/workbench/email-command-center/message-studio",
  "/admin/workbench/email-command-center/send-execution",
  "/admin/workbench/email-command-center/readiness",
  "/admin/workbench/email-command-center/launch-room",
  "/admin/workbench/email-command-center/audiences",
  "/admin/workbench/email-command-center/gmail",
  "/admin/workbench/email-command-center/analytics",
  "/admin/workbench/email-command-center/automation",
  "/admin/communications",
  "/admin/communications/intelligence",
  "/admin/communications/studio",
  "/admin/campaign-events/ai-tools",
  "/campaign-events/approval",
];

type PartialContract = Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">;

function c(p: PartialContract): CampaignAiToolContract {
  const { routesUsingTool, ...rest } = p;
  return {
    sprint: SPRINT,
    lifecycle: L,
    version: "v2_future",
    priority: rest.priority ?? "P0",
    ...rest,
    routesUsingTool: routesUsingTool ?? [...ROUTES],
  };
}

const TOOLS: CampaignAiToolContract[] = [
  // —— Suite meta ——
  c({ id: "email-os-suite-manifest", name: "Email OS suite manifest", purpose: "Manifest of rails, rules, and tool count.", currentStatus: "functional", trigger: "AI tools / agent runtime", inputs: "—", outputs: "EmailOsSuiteManifest", readsFrom: H, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: `${H}#getEmailOsSuiteManifest`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: ["agents:test-email-os-suite"] }),
  c({ id: "email-os-human-control-matrix", name: "Email OS human control matrix", purpose: "Campaign AI human control rules for all email tools.", currentStatus: "functional", trigger: "Agent preflight", inputs: "—", outputs: "rules[]", readsFrom: "src/lib/campaign-events/ai-tools/tool-contract.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Non-bypassable", deterministicHelperPath: `${H}#getEmailOsSuiteManifest`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-os-cross-rail-checklist", name: "Email OS cross-rail checklist", purpose: "ECC vs comms center vs approval path checklist.", currentStatus: "functional", trigger: "Operator onboarding", inputs: "—", outputs: "checklist", readsFrom: H, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsCrossRailChecklist`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),

  // —— Readiness & ECC cockpit ——
  c({ id: "ecc-readiness-lite-scanner", name: "ECC readiness lite scanner", purpose: "Lite readiness panel for operators.", currentStatus: "functional", trigger: "ECC readiness", inputs: "env+db", outputs: "EmailReadinessLite", readsFrom: `${ECC}email-readiness-lite.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}email-readiness-lite.ts`, routesUsingTool: ["/admin/workbench/email-command-center/readiness"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-provider-readiness-orchestrator", name: "Email provider readiness orchestrator", purpose: "SendGrid/Gmail/approval env gates.", currentStatus: "functional", trigger: "Any email surface", inputs: "env", outputs: "EmailProviderReadinessReport", readsFrom: `${CM}email-provider-readiness.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No send", deterministicHelperPath: `${H}#runEmailOsProviderReadiness`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "ecc-migration-gate-advisor", name: "ECC migration gate advisor", purpose: "Explain ECC Prisma migration gate rows.", currentStatus: "partial", trigger: "Readiness hosted-db", inputs: "—", outputs: "migration rows", readsFrom: `${ECC}ecc-migration-gate.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${ECC}ecc-migration-gate.ts`, routesUsingTool: ["/admin/workbench/email-command-center/readiness/hosted-db"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "hosted-db-proof-assistant", name: "Hosted DB proof assistant", purpose: "Hosted DB verification steps for production send.", currentStatus: "partial", trigger: "Readiness", inputs: "DATABASE_URL", outputs: "proof", readsFrom: `${ECC}hosted-db-proof.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "No credential echo", deterministicHelperPath: `${ECC}hosted-db-readiness-assistant.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "ecc-snapshot-reader", name: "ECC snapshot reader", purpose: "Full Email Command Center snapshot.", currentStatus: "functional", trigger: "ECC home", inputs: "—", outputs: "EmailCommandCenterSnapshot", readsFrom: `${ECC}read-model.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: `${ECC}read-model.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-launch-room-snapshot", name: "Email launch room snapshot", purpose: "Launch room send-packet context.", currentStatus: "functional", trigger: "Launch room", inputs: "—", outputs: "snapshot", readsFrom: `${ECC}launch-room.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}launch-room.ts`, routesUsingTool: ["/admin/workbench/email-command-center/launch-room"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),

  // —— Audiences & contacts ——
  c({ id: "contact-import-csv-parser", name: "Contact import CSV parser", purpose: "Parse CSV for ECC contact import.", currentStatus: "functional", trigger: "Import upload", inputs: "csv text", outputs: "rows", readsFrom: `${ECC}contact-import.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Consent review", deterministicHelperPath: `${ECC}contact-import.ts`, routesUsingTool: ["/admin/workbench/email-command-center/imports"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "contact-import-row-validator", name: "Contact import row validator", purpose: "Validate normalized import row.", currentStatus: "functional", trigger: "Import review", inputs: "NormalizedImportRow", outputs: "ValidationResult", readsFrom: `${ECC}contact-import.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${H}#runEmailOsImportRowCheck`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "contact-import-duplicate-detector", name: "Contact import duplicate detector", purpose: "Flag duplicate emails in import batch.", currentStatus: "functional", trigger: "Import commit", inputs: "rows[]", outputs: "dup map", readsFrom: `${ECC}contact-import.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}contact-import.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "audience-list-health-scanner", name: "Audience list health scanner", purpose: "Prisma profile health: dupes, opt-outs, missing email.", currentStatus: "functional", trigger: "Audiences / today", inputs: "—", outputs: "AudienceListHealthSnapshot", readsFrom: `${ECC}audience-list-health.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: `${ECC}audience-list-health.ts`, routesUsingTool: ["/admin/workbench/email-command-center/audiences"], observationEvents: ["communication_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "audience-studio-preview-helper", name: "Audience studio preview helper", purpose: "Audience preview form state for send planning.", currentStatus: "partial", trigger: "Audience studio", inputs: "filter", outputs: "preview", readsFrom: `${ECC}audience-studio.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${ECC}audience-preview-form-state.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "sendgrid-contact-sync-advisor", name: "SendGrid contact sync advisor", purpose: "Advise on marketing contact sync deltas.", currentStatus: "partial", trigger: "SendGrid sync", inputs: "profiles", outputs: "sync plan", readsFrom: `${ECC}sendgrid-contact-sync.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto sync without approval", deterministicHelperPath: `${ECC}sendgrid-contact-sync.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "profile-graph-context-loader", name: "Profile graph context loader", purpose: "Load ECC profile graph for AI grounding.", currentStatus: "partial", trigger: "Message Studio AI", inputs: "profileId", outputs: "graph context", readsFrom: `${ECC}profile-graph.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No PII in logs", deterministicHelperPath: `${ECC}profile-graph.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "ai-audience-strategist", name: "AI audience strategist", purpose: "Recommend audience slices for a send goal.", currentStatus: "partial", trigger: "Send planning", inputs: "goal", outputs: "segments", readsFrom: `${ECC}ai-audience-strategist.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human picks final audience", deterministicHelperPath: `${ECC}ai-audience-strategist.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-os-contact-store-auditor", name: "Campaign OS contact store auditor", purpose: "JSON store contacts/suppressions/sends counts.", currentStatus: "functional", trigger: "Comms center", inputs: "—", outputs: "counts", readsFrom: `${CM}communications-store.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsStoreHealth`, routesUsingTool: ["/admin/communications"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "contact-source-unifier", name: "Contact source unifier", purpose: "Map 11+ contact sources into operator view.", currentStatus: "functional", trigger: "Comms center", inputs: "—", outputs: "sources[]", readsFrom: `${CM}contact-source-discovery.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsContactSources`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),

  // —— Message Studio & content ——
  c({ id: "message-template-catalog-reader", name: "Message template catalog reader", purpose: "Read ECC Message Studio templates.", currentStatus: "functional", trigger: "Message Studio", inputs: "filter", outputs: "templates", readsFrom: `${ECC}message-templates.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}message-templates.ts`, routesUsingTool: ["/admin/workbench/email-command-center/message-studio"], observationEvents: ["template_applied"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "message-studio-draft-lister", name: "Message Studio draft lister", purpose: "List shared Message Studio drafts.", currentStatus: "functional", trigger: "Message Studio", inputs: "—", outputs: "drafts[]", readsFrom: `${ECC}message-studio-drafts.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}message-studio-drafts.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "deterministic-draft-critic", name: "Deterministic draft critic", purpose: "Red-team draft without LLM (compliance heuristics).", currentStatus: "functional", trigger: "Draft save / review", inputs: "draft", outputs: "DraftCritiqueResult", readsFrom: `${ECC}ai-draft-critic.ts`, writesTo: "metadata only", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-apply rewrites", deterministicHelperPath: `${H}#runEmailOsDraftCritique`, routesUsingTool: ROUTES, observationEvents: ["draft_generated", "draft_modified"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "message-studio-editorial-review-model", name: "Message Studio editorial review model", purpose: "Editorial review scoring model for drafts.", currentStatus: "partial", trigger: "NEEDS_REVIEW drafts", inputs: "draft", outputs: "review", readsFrom: `${ECC}message-studio-editorial-review-model.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${ECC}message-studio-editorial-review-model.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-voice-applier", name: "Campaign voice applier", purpose: "Apply Kelly campaign voice settings to drafts.", currentStatus: "functional", trigger: "Message Studio", inputs: "risk level", outputs: "voice excerpt", readsFrom: `${ECC}campaign-voice.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}campaign-voice.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "ai-source-grounding-builder", name: "AI source grounding builder", purpose: "Ground Message Studio AI in approved sources.", currentStatus: "partial", trigger: "AI assist", inputs: "sources", outputs: "grounding block", readsFrom: `${ECC}ai-source-grounding.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No invented facts", deterministicHelperPath: `${ECC}ai-source-grounding.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "merge-tag-validator", name: "Merge tag validator", purpose: "Validate template variables vs body.", currentStatus: "partial", trigger: "Template apply", inputs: "template, body", outputs: "missing vars", readsFrom: `${ECC}message-templates.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}message-templates.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "unsubscribe-footer-checker", name: "Unsubscribe footer checker", purpose: "Verify ASM/unsubscribe requirements for marketing.", currentStatus: "functional", trigger: "Pre-send", inputs: "env", outputs: "ok/blocked", readsFrom: `${CM}email-provider-readiness.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "high", guardrails: "Required for broadcast", deterministicHelperPath: `${CM}email-provider-readiness.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "preview-text-optimizer", name: "Preview text optimizer", purpose: "Suggest preview text from body.", currentStatus: "partial", trigger: "Draft edit", inputs: "body", outputs: "preview", readsFrom: `${COM}writing-orchestration/subject-line-optimizer.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${COM}writing-orchestration/campaign-writing-router.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),

  // —— Send execution & safety ——
  c({ id: "send-execution-preflight-explainer", name: "Send execution preflight explainer", purpose: "Parse preflightJson checks for operators.", currentStatus: "functional", trigger: "Send execution", inputs: "preflightJson", outputs: "checks+breakdown", readsFrom: `${ECC}send-execution-preflight-json.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsPreflightExplain`, routesUsingTool: ["/admin/workbench/email-command-center/send-execution"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "send-execution-human-gate", name: "Send execution human gate", purpose: "Typed human approval before SendGrid execute.", currentStatus: "functional", trigger: "Execute send", inputs: "operator", outputs: "approved/blocked", readsFrom: `${ECC}send-execution.ts`, writesTo: "EmailSendExecution", humanApprovalRequired: true, riskLevel: "blocked", guardrails: "SEND APPROVED required", deterministicHelperPath: `${ECC}send-execution.ts`, routesUsingTool: ROUTES, observationEvents: ["gated_action_presented"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "mass-send-block-enforcer", name: "Mass send block enforcer", purpose: "Enforce Campaign OS mass-send block.", currentStatus: "functional", trigger: "Broadcast attempt", inputs: "recipientCount", outputs: "blocked+reasons", readsFrom: `${H}#runEmailOsMassSendGuard`, writesTo: "—", humanApprovalRequired: true, riskLevel: "blocked", guardrails: "Always block V1 bulk", deterministicHelperPath: `${H}#runEmailOsMassSendGuard`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "recipient-breakdown-explainer", name: "Recipient breakdown explainer", purpose: "Explain suppressed/missing consent exclusions.", currentStatus: "functional", trigger: "Preflight", inputs: "preflightJson", outputs: "breakdown", readsFrom: `${ECC}send-execution-preflight-json.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsPreflightExplain`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "automation-policy-catalog-reader", name: "Automation policy catalog reader", purpose: "List read-only ECC automation policies.", currentStatus: "functional", trigger: "Automation page", inputs: "—", outputs: "policies[]", readsFrom: `${ECC}automation-policies.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only evaluation", deterministicHelperPath: `${H}#runEmailOsAutomationPolicyCatalog`, routesUsingTool: ["/admin/workbench/email-command-center/automation"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "automation-policy-runner-advisor", name: "Automation policy runner advisor", purpose: "Explain policy evaluation results.", currentStatus: "partial", trigger: "Automation run", inputs: "snapshot", outputs: "findings", readsFrom: `${ECC}automation-policy-runner.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No auto-send", deterministicHelperPath: `${ECC}automation-policy-runner.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "send-incident-stop-advisor", name: "Send incident stop advisor", purpose: "Advise pausing sends during incidents.", currentStatus: "functional", trigger: "Incident", inputs: "—", outputs: "hold steps", readsFrom: `${ECC}automation-policies.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "EMAIL_SEND_ENABLED off", deterministicHelperPath: `${H}#runEmailOsCrossRailChecklist`, routesUsingTool: ROUTES, observationEvents: ["human_gate_required"], futureAutomationPath: "", testChecklist: [] }),

  // —— SendGrid & deliverability ——
  c({ id: "sendgrid-foundation-checker", name: "SendGrid foundation checker", purpose: "Verify SendGrid foundation config.", currentStatus: "functional", trigger: "ECC SendGrid", inputs: "env", outputs: "status", readsFrom: `${ECC}sendgrid-foundation.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${SG}config.ts`, routesUsingTool: ["/admin/workbench/email-command-center/sendgrid"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "sendgrid-mail-send-guard", name: "SendGrid mail send guard", purpose: "Low-level mail send wrapper gates.", currentStatus: "functional", trigger: "Provider call", inputs: "payload", outputs: "result/blocked", readsFrom: `${SG}mail-send.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "blocked", guardrails: "Human execute only", deterministicHelperPath: `${SG}mail-send.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "sendgrid-event-reconciler", name: "SendGrid event reconciler", purpose: "Reconcile SendGrid events vs executions.", currentStatus: "partial", trigger: "Analytics", inputs: "events", outputs: "reconciliation", readsFrom: `${ECC}sendgrid-event-reconciliation.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ECC}sendgrid-event-reconciliation.ts`, routesUsingTool: ["/admin/workbench/email-command-center/analytics"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "sendgrid-suppression-explainer", name: "SendGrid suppression explainer", purpose: "Explain why recipients are suppressed.", currentStatus: "partial", trigger: "Preflight", inputs: "email", outputs: "reason", readsFrom: `${CM}communications-store.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "high", guardrails: "Use ECC suppressions in prod", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "Prisma SendGridSuppression", testChecklist: [] }),
  c({ id: "sendgrid-webhook-event-parser", name: "SendGrid webhook event parser", purpose: "Parse webhook event payloads.", currentStatus: "functional", trigger: "Webhook ingest", inputs: "payload", outputs: "normalized event", readsFrom: `${SG}event-parser.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${SG}event-parser.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "deliverability-anomaly-hint", name: "Deliverability anomaly hint", purpose: "Flag bounce/spam rate anomalies.", currentStatus: "partial", trigger: "Analytics drilldown", inputs: "metrics", outputs: "hints", readsFrom: `${ECC}analytics-operator-drilldown.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "Advisory", deterministicHelperPath: `${ECC}analytics-operator-drilldown.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),

  // —— Gmail & inbox workflow ——
  c({ id: "gmail-watch-readiness-scanner", name: "Gmail watch readiness scanner", purpose: "Production Gmail watch readiness.", currentStatus: "functional", trigger: "Gmail settings", inputs: "—", outputs: "readiness", readsFrom: `${ECC}gmail-production-watch.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsGmailWatchReadiness`, routesUsingTool: ["/admin/workbench/email-command-center/gmail"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "gmail-watch-renewal-planner", name: "Gmail watch renewal planner", purpose: "Plan watch renewals before expiry.", currentStatus: "partial", trigger: "Gmail ops", inputs: "accounts", outputs: "renewal plan", readsFrom: `${ECC}gmail-production-watch.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-renew without ops", deterministicHelperPath: `${ECC}gmail-production-watch.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-workflow-queue-summarizer", name: "Email workflow queue summarizer", purpose: "Summarize inbox workflow queue.", currentStatus: "partial", trigger: "Inbox load", inputs: "—", outputs: "summary", readsFrom: `${EW}queries.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${EW}queries.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-workflow-interpretation-runner", name: "Email workflow interpretation runner", purpose: "Run inbox interpretation pipeline.", currentStatus: "partial", trigger: "Item open", inputs: "itemId", outputs: "interpretation", readsFrom: `${EW}intelligence/interpreter.ts`, writesTo: "writeback", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-reply", deterministicHelperPath: `${EW}intelligence/interpreter.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-workflow-governance-checker", name: "Email workflow governance checker", purpose: "Allowed manual status transitions.", currentStatus: "functional", trigger: "Status change", inputs: "status", outputs: "allowed[]", readsFrom: `${EW}governance.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsWorkflowTransitions`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "inbox-reply-pathway-planner", name: "Inbox reply pathway planner", purpose: "Plan human reply pathways (no auto-send).", currentStatus: "functional", trigger: "Gmail review", inputs: "thread", outputs: "pathway steps", readsFrom: `${EW}intelligence/heuristics.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-reply", deterministicHelperPath: `${EW}intelligence/heuristics.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-ai-readiness-checker", name: "Email AI readiness checker", purpose: "Check if inbox AI analysis is configured.", currentStatus: "functional", trigger: "Inbox AI", inputs: "env", outputs: "EmailAiReadiness", readsFrom: `${EW}ai/config.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsInboxAiReadiness`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-workflow-ai-analyzer", name: "Email workflow AI analyzer", purpose: "Optional LLM analysis of inbox items.", currentStatus: "partial", trigger: "Analyze click", inputs: "item", outputs: "EmailAiAnalysisV1", readsFrom: `${EW}ai/analyzer.ts`, writesTo: "item metadata", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human applies suggestions", deterministicHelperPath: `${EW}ai/analyzer.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),

  // —— Campaign OS intelligence bridge ——
  c({ id: "communications-intelligence-composer", name: "Communications intelligence composer", purpose: "Statewide comms intelligence context.", currentStatus: "functional", trigger: "Intelligence dashboard", inputs: "—", outputs: "context", readsFrom: `${COM}communications-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsIntelligenceContext`, routesUsingTool: ["/admin/communications/intelligence"], observationEvents: ["communications_priority_viewed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "relationship-graph-email-bridge", name: "Relationship graph email bridge", purpose: "Relationship graph for email targeting.", currentStatus: "functional", trigger: "Email planning", inputs: "—", outputs: "graph", readsFrom: `${COM}relationship-intelligence/relationship-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Metadata only", deterministicHelperPath: `${H}#runEmailOsRelationshipGraph`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communication-sequence-email-packager", name: "Communication sequence email packager", purpose: "Package human-reviewed sequences for email.", currentStatus: "functional", trigger: "Copilot", inputs: "type", outputs: "sequence", readsFrom: `${COM}sequences/communication-sequence-builder.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${H}#runEmailOsSequence`, routesUsingTool: ROUTES, observationEvents: ["communication_sequence_created"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-writing-router-ecc-bridge", name: "Campaign writing router ECC bridge", purpose: "Orchestrated drafts for ECC/Message Studio.", currentStatus: "functional", trigger: "Studio / copilot", inputs: "audience,purpose", outputs: "OrchestratedDraft", readsFrom: `${COM}writing-orchestration/campaign-writing-router.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Draft only", deterministicHelperPath: `${H}#runEmailOsWritingRouter`, routesUsingTool: ROUTES, observationEvents: ["draft_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-message-ecc-bridge", name: "County message ECC bridge", purpose: "County-aware copy into email drafts.", currentStatus: "functional", trigger: "County comms", inputs: "slug", outputs: "angles", readsFrom: `${COM}writing-orchestration/county-message-adapter.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "County bridge read-only", deterministicHelperPath: `${COM}county-communications-intelligence.ts`, routesUsingTool: ROUTES, observationEvents: ["county_message_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-email-sequence-packager", name: "Volunteer email sequence packager", purpose: "Volunteer onboarding email sequence.", currentStatus: "functional", trigger: "Volunteer copilot", inputs: "—", outputs: "sequence", readsFrom: `${COM}volunteer-communications-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${COM}volunteer-communications-workflows.ts`, routesUsingTool: ROUTES, observationEvents: ["volunteer_outreach_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "host-email-sequence-packager", name: "Host email sequence packager", purpose: "Host onboarding/follow-up sequences.", currentStatus: "functional", trigger: "Host copilot", inputs: "host", outputs: "sequence", readsFrom: `${COM}host-relationship-workflows.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${COM}host-relationship-workflows.ts`, routesUsingTool: ROUTES, observationEvents: ["host_followup_recommended"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-fatigue-email-guard", name: "Communications fatigue email guard", purpose: "Block over-cadence email plans.", currentStatus: "functional", trigger: "Sequence plan", inputs: "graph", outputs: "warnings", readsFrom: `${COM}sequences/communication-fatigue-detector.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${COM}sequences/communication-fatigue-detector.ts`, routesUsingTool: ROUTES, observationEvents: ["burnout_warning_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "followup-gap-email-router", name: "Follow-up gap email router", purpose: "Route overdue follow-ups to operators.", currentStatus: "functional", trigger: "Intelligence", inputs: "nodes", outputs: "gaps", readsFrom: `${COM}sequences/followup-gap-detector.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${COM}sequences/followup-gap-detector.ts`, routesUsingTool: ROUTES, observationEvents: ["followup_overdue_detected"], futureAutomationPath: "", testChecklist: [] }),

  // —— Approval email bridge ——
  c({ id: "approval-email-path-tracer", name: "Approval email path tracer", purpose: "Trace approval email architecture.", currentStatus: "functional", trigger: "Sprint 4 tools", inputs: "—", outputs: "trace", readsFrom: "src/lib/campaign-events/ai-tools/sprint4-tool-helpers.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No GCal write", deterministicHelperPath: "src/lib/campaign-events/ai-tools/sprint4-tool-helpers.ts", routesUsingTool: ["/campaign-events/approval"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "approval-send-readiness-bridge", name: "Approval send readiness bridge", purpose: "Approval email send readiness vs ECC gates.", currentStatus: "functional", trigger: "Approval package", inputs: "env", outputs: "ready", readsFrom: "src/lib/campaign-events/approval-email/approval-email-config.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "EMAIL_SEND_ENABLED", deterministicHelperPath: `${H}#runEmailOsProviderReadiness`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "ecc-approval-audit-bridge", name: "ECC approval audit bridge", purpose: "Cross-link approval sends to ECC audit.", currentStatus: "partial", trigger: "Post-send", inputs: "send meta", outputs: "audit row", readsFrom: `${CM}communications-store.ts`, writesTo: "sends.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CM}communications-store.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "Prisma EmailSendExecution", testChecklist: [] }),

  // —— OS integration ——
  c({ id: "communications-bundle-orchestrator", name: "Communications bundle orchestrator", purpose: "Load full Campaign OS comms bundle.", currentStatus: "functional", trigger: "Comms surfaces", inputs: "—", outputs: "CommunicationsBundle", readsFrom: `${CM}load-communications-bundle.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${H}#runEmailOsCommunicationsBundle`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: ["campaign-events:test-communications"] }),
  c({ id: "email-os-agent-tool-router", name: "Email OS agent tool router", purpose: "Route agent intents to Email OS helpers.", currentStatus: "functional", trigger: "Agent runtime", inputs: "toolId", outputs: "result", readsFrom: H, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No send side effects", deterministicHelperPath: "src/lib/campaign-events/ai-tools/email-os-agent-tool-router.ts", routesUsingTool: ["/admin/ai-command-center"], observationEvents: ["ai_command_palette_used"], futureAutomationPath: "", testChecklist: ["agents:test-email-os-suite"] }),
  c({ id: "email-risk-compliance-scanner", name: "Email risk compliance scanner", purpose: "Scan drafts for compliance + human control rules.", currentStatus: "functional", trigger: "Draft / send plan", inputs: "draft", outputs: "critique+rules", readsFrom: `${ECC}ai-draft-critic.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "Advisory", deterministicHelperPath: `${H}#runEmailOsDraftCritique`, routesUsingTool: ROUTES, observationEvents: ["relationship_warning_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-performance-learning-planner", name: "Email performance learning planner", purpose: "Plan learning from SendGrid metrics (read-only).", currentStatus: "partial", trigger: "Analytics", inputs: "events", outputs: "learnings", readsFrom: `${ECC}sendgrid-event-reconciliation.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No auto strategy change", deterministicHelperPath: `${ECC}analytics-operator-drilldown.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "email-response-pathway-planner", name: "Email response pathway planner", purpose: "Human reply pathways from inbox (replaces idea tool).", currentStatus: "functional", trigger: "Inbox triage", inputs: "thread", outputs: "steps", readsFrom: `${EW}intelligence/composer.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-reply", deterministicHelperPath: `${EW}intelligence/composer.ts`, routesUsingTool: ROUTES, observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_EMAIL_OS_AGENT_TOOL_CONTRACTS = TOOLS;
export const SPRINT_EMAIL_OS_AGENT_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);

export const EMAIL_OS_SUITE_TOOL_COUNT = TOOLS.length;
