/**
 * Campaign Knowledge Graph + Lessons Engine — tool contracts (Phase 3A).
 */
import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 17;
const L = "campaign_knowledge_graph" as const;
const ROOT = "src/lib/agents/orchestration/knowledge/";
const ROUTE = ["/admin/orchestration", "/admin/ai-command-center"] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P1", ...partial };
}

export const CAMPAIGN_KNOWLEDGE_TOOL_CONTRACTS: CampaignAiToolContract[] = [
  c({ id: "campaign-entity-graph-builder", name: "Campaign entity graph builder", purpose: "Build unified entity graph from intake sources.", currentStatus: "partial", trigger: "Knowledge load", inputs: "observations + county + hot wash", outputs: "CampaignEntityGraph", readsFrom: "intake", writesTo: "entity-graph.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "Metadata only", deterministicHelperPath: `${ROOT}load-campaign-knowledge-bundle.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-observation-intake-engine", name: "Campaign observation intake", purpose: "Structure staff notes and signals into graph nodes.", currentStatus: "partial", trigger: "Intake pass", inputs: "UserObservationEntry[]", outputs: "ObservationIntakeResult", readsFrom: "user-observations", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No PII export", deterministicHelperPath: `${ROOT}campaign-observation-intake.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-lessons-engine", name: "Campaign lessons engine", purpose: "Rank and store campaign lessons with confidence.", currentStatus: "partial", trigger: "After intake", inputs: "lesson candidates", outputs: "CampaignLesson[]", readsFrom: "lessons.json", writesTo: "lessons.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human approval for approved status", deterministicHelperPath: `${ROOT}campaign-lessons-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-lesson-linker", name: "Campaign lesson linker", purpose: "Link lesson to county/person/event/workflow entities.", currentStatus: "partial", trigger: "Lesson create", inputs: "lesson + entity ids", outputs: "linked lesson", readsFrom: "graph", writesTo: "lessons.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${ROOT}campaign-lessons-store.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "recommendation-feedback-recorder", name: "Recommendation feedback recorder", purpose: "Record accepted/rejected/completed/successful/failed on AI advice.", currentStatus: "partial", trigger: "Operator feedback", inputs: "RecommendationFeedbackRecord", outputs: "saved record", readsFrom: "feedback.json", writesTo: "feedback.json", humanApprovalRequired: false, riskLevel: "low", guardrails: "No auto status", deterministicHelperPath: `${ROOT}recommendation-feedback-store.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "recommendation-outcome-analyzer", name: "Recommendation outcome analyzer", purpose: "Summarize which advice improved outcomes.", currentStatus: "partial", trigger: "Knowledge load", inputs: "feedback records", outputs: "RecommendationFeedbackSummary", readsFrom: "feedback.json", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}recommendation-feedback-store.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-knowledge-memory-synthesizer", name: "Knowledge memory synthesizer", purpose: "Build CampaignKnowledgeMemorySlice for CampaignState.", currentStatus: "partial", trigger: "Orchestration load", inputs: "graph + lessons + feedback", outputs: "memory slice", readsFrom: "bundle", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}campaign-knowledge-memory-types.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-pattern-detector", name: "Campaign pattern detector", purpose: "Detect emerging patterns across lessons and blockers.", currentStatus: "partial", trigger: "Lessons rank", inputs: "lessons", outputs: "patterns[]", readsFrom: "lessons", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}campaign-lessons-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-recurring-blocker-miner", name: "Recurring blocker miner", purpose: "Find blockers that repeat across periods.", currentStatus: "partial", trigger: "State build", inputs: "blockers", outputs: "recurring[]", readsFrom: "CampaignState", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}campaign-lessons-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-confidence-gap-analyzer", name: "Confidence gap analyzer", purpose: "List domains under-informed for AI reasoning.", currentStatus: "partial", trigger: "Graph summary", inputs: "graph + lessons", outputs: "gaps[]", readsFrom: "memory slice", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}campaign-knowledge-memory-types.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "hotwash-lesson-extractor", name: "Hot wash lesson extractor", purpose: "Propose lessons from hot wash learning snapshot.", currentStatus: "partial", trigger: "Intake", inputs: "CampaignLearningSnapshot", outputs: "lesson candidates", readsFrom: "hot-wash-intelligence", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human approval", deterministicHelperPath: `${ROOT}campaign-observation-intake.ts`, routesUsingTool: [...ROUTE], observationEvents: ["hotwash_completed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-lesson-extractor", name: "County lesson extractor", purpose: "Propose lessons from county intelligence gaps.", currentStatus: "partial", trigger: "Intake", inputs: "StatewideCountyIntelligence", outputs: "lesson candidates", readsFrom: "county-intelligence", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: `${ROOT}campaign-observation-intake.ts`, routesUsingTool: [...ROUTE], observationEvents: ["county_signal_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "comms-signal-intake", name: "Comms signal intake", purpose: "Ingest comms metadata into graph (no message bodies).", currentStatus: "idea", trigger: "Comms load", inputs: "comms intelligence", outputs: "message nodes", readsFrom: "communications-intelligence-engine", writesTo: "graph", humanApprovalRequired: false, riskLevel: "low", guardrails: "No inbox scrape", deterministicHelperPath: `${ROOT}campaign-observation-intake.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-activity-intake", name: "Volunteer activity intake", purpose: "Link volunteer segments to graph persons.", currentStatus: "idea", trigger: "Volunteer load", inputs: "volunteer CRM", outputs: "person nodes", readsFrom: "volunteer_system", writesTo: "graph", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}load-campaign-knowledge-bundle.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "finance-signal-intake", name: "Finance signal intake", purpose: "Ingest finance/compliance warnings as outcome nodes.", currentStatus: "idea", trigger: "Finance load", inputs: "finance snapshot", outputs: "outcome nodes", readsFrom: "finance intelligence", writesTo: "graph", humanApprovalRequired: false, riskLevel: "low", guardrails: "No auto post", deterministicHelperPath: `${ROOT}load-campaign-knowledge-bundle.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-usage-intake", name: "Tool usage intake", purpose: "Record AI tool usage as graph tool_usage nodes.", currentStatus: "idea", trigger: "Runtime audit", inputs: "runtime audit", outputs: "nodes", readsFrom: "runtime-audit.json", writesTo: "graph", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}load-campaign-knowledge-bundle.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-knowledge-bundle-loader", name: "Campaign knowledge bundle loader", purpose: "Load graph + lessons + feedback for orchestration.", currentStatus: "partial", trigger: "Orchestration / API", inputs: "period", outputs: "CampaignKnowledgeSummary", readsFrom: "all intake", writesTo: "JSON stores", humanApprovalRequired: false, riskLevel: "low", guardrails: "Graceful degrade", deterministicHelperPath: `${ROOT}campaign-knowledge-state.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "lesson-approval-gate", name: "Lesson approval gate", purpose: "Require human approval before lesson affects reasoning.", currentStatus: "partial", trigger: "Lesson status change", inputs: "lesson id", outputs: "approved/rejected", readsFrom: "lessons.json", writesTo: "lessons.json", humanApprovalRequired: true, riskLevel: "high", guardrails: "Never auto-approve strategic lessons", deterministicHelperPath: `${ROOT}campaign-lessons-store.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-state-knowledge-merge", name: "CampaignState knowledge merge", purpose: "Merge knowledge memory slice into CampaignState.", currentStatus: "partial", trigger: "State build", inputs: "CampaignKnowledgeBundle", outputs: "knowledgeMemory", readsFrom: "orchestration", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/orchestration/build-campaign-state-from-signals.ts", routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-knowledge-staleness-checker", name: "Knowledge staleness checker", purpose: "Flag stale domains and lessons.", currentStatus: "partial", trigger: "Lessons refresh", inputs: "lessons", outputs: "stale domains", readsFrom: "lessons.json", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ROOT}campaign-lessons-engine.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const CAMPAIGN_KNOWLEDGE_TOOL_COUNT = CAMPAIGN_KNOWLEDGE_TOOL_CONTRACTS.length;
export const CAMPAIGN_KNOWLEDGE_CATALOG_ENTRIES: AiToolEntry[] = CAMPAIGN_KNOWLEDGE_TOOL_CONTRACTS.map(contractToCatalogEntry);
