import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 7;
const L = "event_intelligence_sprint7" as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

export const OBS_SPRINT7 = [
  "hotwash_completed",
  "county_signal_detected",
  "event_blueprint_created",
  "relationship_opportunity_detected",
  "followup_task_generated",
  "messaging_signal_detected",
  "county_memory_updated",
  "event_pattern_detected",
  "strategic_signal_detected",
  "successful_event_logged",
] as const;

const ROUTE = ["/admin/campaign-events/[recordId]", "/admin/ai-command-center"] as const;
const HELPERS = "src/lib/campaign-events/hot-wash-intelligence/event-intelligence-helpers.ts";

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "event-hotwash-summarizer", name: "Event hot wash summarizer", purpose: "Executive summary from outcome + lessons.", currentStatus: "functional", trigger: "Save / complete hot wash", inputs: "HotWashIntelligenceData", outputs: "executiveSummary", readsFrom: "_hotWashIntelligence", writesTo: "executiveSummary", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human edits before complete", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["hotwash_completed"], futureAutomationPath: "LLM narrative", testChecklist: [] }),
  c({ id: "event-lessons-extractor", name: "Event lessons extractor", purpose: "Surface top findings from lessons block.", currentStatus: "functional", trigger: "Complete review", inputs: "lessons", outputs: "topFindings[]", readsFrom: "lessons", writesTo: "topFindings", humanApprovalRequired: true, riskLevel: "low", guardrails: "No auto-publish", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["strategic_signal_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-messaging-intelligence-builder", name: "Event messaging intelligence builder", purpose: "Normalize messaging section signals.", currentStatus: "functional", trigger: "Messaging section save", inputs: "messaging", outputs: "messaging", readsFrom: "messaging", writesTo: "messaging", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["messaging_signal_detected"], futureAutomationPath: "Applause line NLP", testChecklist: [] }),
  c({ id: "event-relationship-signal-detector", name: "Event relationship signal detector", purpose: "Prospects + coalition from relationships.", currentStatus: "functional", trigger: "Relationship section", inputs: "relationships", outputs: "prospect hints", readsFrom: "relationships", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No CRM auto-write", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["relationship_opportunity_detected"], futureAutomationPath: "CRM sync", testChecklist: [] }),
  c({ id: "county-memory-builder", name: "County memory builder", purpose: "Additive county summaries from hot wash.", currentStatus: "functional", trigger: "Complete review", inputs: "row + intel", outputs: "CountyMemoryRecord", readsFrom: "hot wash", writesTo: "data/campaign-events/county-memory/", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Additive only", deterministicHelperPath: "src/lib/campaign-events/county-memory/county-memory-builder.ts", routesUsingTool: [...ROUTE], observationEvents: ["county_memory_updated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-pattern-detector", name: "County pattern detector", purpose: "Recurring issues / formats across counties.", currentStatus: "functional", trigger: "Command center load", inputs: "CountyMemoryRecord[]", outputs: "trends", readsFrom: "county-memory", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: "src/lib/campaign-events/county-memory/county-memory-builder.ts", routesUsingTool: ["/admin/ai-command-center"], observationEvents: ["county_signal_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-blueprint-generator", name: "Event blueprint generator", purpose: "Reusable template from successful event.", currentStatus: "functional", trigger: "Generate blueprint", inputs: "row + intel", outputs: "EventBlueprint", readsFrom: "hot wash", writesTo: "event-blueprints/blueprints.json", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human triggers", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["event_blueprint_created"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "successful-event-pattern-detector", name: "Successful event pattern detector", purpose: "Score success for blueprint eligibility.", currentStatus: "functional", trigger: "Learning loop", inputs: "outcome + countySignals", outputs: "boolean", readsFrom: "intel", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["successful_event_logged", "event_pattern_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-prospect-detector", name: "Volunteer prospect detector", purpose: "Parse volunteer prospects from relationships.", currentStatus: "functional", trigger: "Complete review", inputs: "relationships.volunteerProspects", outputs: "names[]", readsFrom: "intel", writesTo: "county memory", humanApprovalRequired: true, riskLevel: "low", guardrails: "No auto outreach", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["relationship_opportunity_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "donor-prospect-detector", name: "Donor prospect detector", purpose: "Parse donor prospects from relationships.", currentStatus: "functional", trigger: "Complete review", inputs: "relationships.donorProspects", outputs: "names[]", readsFrom: "intel", writesTo: "county memory", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No FIN data", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["followup_task_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "speech-quote-extractor", name: "Speech quote extractor", purpose: "Placeholder quotes from speech media meta.", currentStatus: "scaffolded", trigger: "Speech upload approved", inputs: "HotWashMediaIntelligenceMeta", outputs: "quoteExtractionPlaceholder", readsFrom: "media index", writesTo: "intelligence", humanApprovalRequired: true, riskLevel: "low", guardrails: "No transcription V1", deterministicHelperPath: HELPERS, routesUsingTool: ["/admin/campaign-events/media-approval"], observationEvents: [], futureAutomationPath: "Whisper + LLM", testChecklist: [] }),
  c({ id: "issue-pattern-detector", name: "Issue pattern detector", purpose: "Local + opposition issue patterns.", currentStatus: "functional", trigger: "County memory merge", inputs: "messaging + countySignals", outputs: "issues[]", readsFrom: "intel", writesTo: "county memory", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["messaging_signal_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-energy-scorer", name: "Event energy scorer", purpose: "Numeric energy from outcome fields.", currentStatus: "functional", trigger: "Outcome section", inputs: "energyScore + strategicValue", outputs: "score + label", readsFrom: "outcome", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Advisory", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-performance-observer", name: "Candidate performance observer", purpose: "Summarize candidate performance field.", currentStatus: "functional", trigger: "Outcome save", inputs: "outcome.candidatePerformance", outputs: "observation text", readsFrom: "outcome", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Internal only", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["strategic_signal_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "organizer-performance-observer", name: "Organizer performance observer", purpose: "Summarize organizer performance.", currentStatus: "functional", trigger: "Outcome save", inputs: "outcome.organizerPerformance", outputs: "observation text", readsFrom: "outcome", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "followup-recommendation-builder", name: "Follow-up recommendation builder", purpose: "Action list from follow-up + relationships.", currentStatus: "functional", trigger: "Follow-up section", inputs: "followUp + relationships", outputs: "recommendations[]", readsFrom: "intel", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "No auto email", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["followup_task_generated"], futureAutomationPath: "Task queue", testChecklist: [] }),
  c({ id: "media-intelligence-builder", name: "Media intelligence builder", purpose: "Scaffold image/video/speech metadata.", currentStatus: "functional", trigger: "Upload + learning loop", inputs: "HotWashMediaRecord", outputs: "HotWashMediaIntelligenceMeta", readsFrom: "media index", writesTo: "intelligence", humanApprovalRequired: true, riskLevel: "low", guardrails: "No OCR/transcription V1", deterministicHelperPath: HELPERS, routesUsingTool: ["/admin/campaign-events/media-approval"], observationEvents: [], futureAutomationPath: "Vision + ASR", testChecklist: [] }),
  c({ id: "county-mood-estimator", name: "County mood estimator", purpose: "Enthusiasm + turnout signals text.", currentStatus: "functional", trigger: "County signals section", inputs: "countySignals", outputs: "mood label", readsFrom: "intel", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["county_signal_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "audience-reaction-analyzer", name: "Audience reaction analyzer", purpose: "Combine reactions + applause lines.", currentStatus: "functional", trigger: "Messaging section", inputs: "messaging", outputs: "summary", readsFrom: "messaging", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: HELPERS, routesUsingTool: [...ROUTE], observationEvents: ["messaging_signal_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-learning-loop-orchestrator", name: "Campaign learning loop orchestrator", purpose: "CAPTURE → enrich media → county → blueprint.", currentStatus: "functional", trigger: "Complete review", inputs: "row + intel", outputs: "LearningLoopResult", readsFrom: "hot wash + media", writesTo: "county-memory + blueprints", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human complete only", deterministicHelperPath: "src/lib/campaign-events/hot-wash-intelligence/campaign-learning-loop.ts", routesUsingTool: [...ROUTE], observationEvents: [...OBS_SPRINT7], futureAutomationPath: "Scheduled batch", testChecklist: [] }),
];

export const SPRINT7_EVENT_INTELLIGENCE_TOOL_CONTRACTS = TOOLS;
export const SPRINT7_EVENT_INTELLIGENCE_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
