/**
 * AI Copilot Tooling Expansion — 35+ tool-backed role assistants.
 */
import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 13;
const L = "kelly_os_copilot_tooling" as const;
const ROUTES = [
  "/admin/ai-command-center",
  "/admin/ai-command-center/copilots",
  "/admin/training",
  "/admin/onboarding",
  "/admin/campaign-manager-dashboard",
  "/admin/candidate-dashboard",
] as const;
const CORE = "src/lib/agents/role-copilots/copilot-intelligence-engine.ts";
const PKG = "src/lib/agents/role-copilots/copilot-task-package-builder.ts";
const READY = "src/lib/agents/role-copilots/copilot-readiness-scorer.ts";
const CTX = "src/lib/agents/role-copilots/copilot-role-context-composer.ts";
const SAFE = "src/lib/agents/role-copilots/copilot-safe-action-router.ts";
const RULES = "src/lib/agents/role-copilots/role-copilot-intelligence-rules.ts";

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const OBS = ["copilot_brief_viewed", "copilot_task_package_created"] as const;

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "copilot-intelligence-engine", name: "Copilot intelligence engine", purpose: "Full CopilotIntelligenceBrief per role.", currentStatus: "functional", trigger: "Copilot surfaces", inputs: "role, skill, route, progress", outputs: "CopilotIntelligenceBrief", readsFrom: CORE, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No autonomous actions", deterministicHelperPath: CORE, routesUsingTool: [...ROUTES], observationEvents: ["copilot_brief_viewed"], futureAutomationPath: "", testChecklist: ["agents:test-copilot-tooling"] }),
  c({ id: "copilot-task-package-builder", name: "Copilot task package builder", purpose: "Structured work packages with gates.", currentStatus: "functional", trigger: "Task recommend", inputs: "role, type", outputs: "CopilotTaskPackage", readsFrom: PKG, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: PKG, routesUsingTool: [...ROUTES], observationEvents: ["copilot_task_package_created"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "copilot-readiness-scorer", name: "Copilot readiness scorer", purpose: "Six-dimension readiness report.", currentStatus: "functional", trigger: "Copilot center", inputs: "role, training", outputs: "CopilotReadinessReport", readsFrom: READY, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Guidance not RBAC", deterministicHelperPath: READY, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "copilot-role-context-composer", name: "Copilot role context composer", purpose: "Role + campaign context snapshot.", currentStatus: "functional", trigger: "Brief build", inputs: "observations, os", outputs: "context", readsFrom: CTX, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: CTX, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "copilot-safe-action-router", name: "Copilot safe action router", purpose: "Block high-risk autonomous routes.", currentStatus: "functional", trigger: "Safe links", inputs: "role", outputs: "SafeActionRoute[]", readsFrom: SAFE, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Forbidden patterns", deterministicHelperPath: SAFE, routesUsingTool: [...ROUTES], observationEvents: ["copilot_safe_action_clicked"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-daily-briefing-builder", name: "Candidate daily briefing builder", purpose: "Calm daily brief for Kelly.", currentStatus: "functional", trigger: "role=candidate", inputs: "month", outputs: "brief slice", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No overwhelm", deterministicHelperPath: RULES, routesUsingTool: ["/admin/candidate-dashboard"], observationEvents: [...OBS], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-fatigue-risk-detector", name: "Candidate fatigue risk detector", purpose: "Detect overload signals.", currentStatus: "functional", trigger: "observations", inputs: "obs", outputs: "warnings", readsFrom: CORE, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: CORE, routesUsingTool: ["/admin/candidate-dashboard"], observationEvents: ["copilot_risk_warning_shown"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-event-prep-coach", name: "Candidate event prep coach", purpose: "Event prep task package.", currentStatus: "functional", trigger: "upcoming events", inputs: "role", outputs: "package", readsFrom: PKG, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: PKG, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-manager-blocker-ranker", name: "CM blocker ranker", purpose: "Rank OS blockers for CM.", currentStatus: "functional", trigger: "os snapshot", inputs: "blockers", outputs: "ranked", readsFrom: CORE, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: CORE, routesUsingTool: ["/admin/campaign-manager-dashboard"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-manager-workflow-delegator", name: "CM workflow delegator", purpose: "Suggest delegate handoffs.", currentStatus: "partial", trigger: "CM brief", inputs: "plans", outputs: "handoffs", readsFrom: "os-control", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-manager-staffing-risk-detector", name: "CM staffing risk detector", purpose: "Volunteer gap warnings.", currentStatus: "functional", trigger: "workbench", inputs: "events", outputs: "risks", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: ["copilot_risk_warning_shown"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "treasurer-packet-review-copilot", name: "Treasurer packet review copilot", purpose: "Review-only reimbursement path.", currentStatus: "functional", trigger: "reimbursement", inputs: "month", outputs: "package", readsFrom: PKG, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto print", deterministicHelperPath: PKG, routesUsingTool: ["/admin/campaign-events/reimbursement"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "treasurer-missing-docs-prioritizer", name: "Treasurer missing docs prioritizer", purpose: "Prioritize receipt/mileage gaps.", currentStatus: "functional", trigger: "finance", inputs: "gaps", outputs: "priority list", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "finance-helper-task-router", name: "Finance helper task router", purpose: "Safe intern/helper tasks.", currentStatus: "functional", trigger: "role=finance_helper", inputs: "skill", outputs: "packages", readsFrom: PKG, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Treasurer gate", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-planner-execution-coach", name: "Event planner execution coach", purpose: "Execution checklist packages.", currentStatus: "functional", trigger: "workbench", inputs: "event", outputs: "package", readsFrom: PKG, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-readiness-task-router", name: "Event readiness task router", purpose: "Route planning readiness tasks.", currentStatus: "functional", trigger: "planning", inputs: "readiness", outputs: "tasks", readsFrom: PKG, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "run-of-show-completion-coach", name: "Run of show completion coach", purpose: "Run of show steps.", currentStatus: "functional", trigger: "event drilldown", inputs: "event id", outputs: "steps", readsFrom: PKG, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-coordinator-staffing-copilot", name: "VC staffing copilot", purpose: "Staffing gap packages.", currentStatus: "functional", trigger: "volunteers", inputs: "events", outputs: "packages", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No mass SMS", deterministicHelperPath: RULES, routesUsingTool: ["/admin/volunteers"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-assignment-fit-scorer", name: "Volunteer assignment fit scorer", purpose: "Score volunteer-event fit.", currentStatus: "partial", trigger: "assignment", inputs: "profile, event", outputs: "score", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "volunteer OS", testChecklist: [] }),
  c({ id: "volunteer-retention-coach", name: "Volunteer retention coach", purpose: "Follow-up and thank-you tasks.", currentStatus: "partial", trigger: "no-show", inputs: "volunteer id", outputs: "tasks", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-first-task-coach", name: "Volunteer first task coach", purpose: "First-day volunteer package.", currentStatus: "functional", trigger: "onboarding", inputs: "role=volunteer", outputs: "package", readsFrom: PKG, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: PKG, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "intern-safe-task-router", name: "Intern safe task router", purpose: "Supervised intern tasks only.", currentStatus: "functional", trigger: "role=intern", inputs: "skill", outputs: "packages", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Supervisor", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "field-manager-county-gap-copilot", name: "Field manager county gap copilot", purpose: "County priority packages.", currentStatus: "functional", trigger: "county", inputs: "county", outputs: "package", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "No voter export", deterministicHelperPath: RULES, routesUsingTool: ["/admin/county-intelligence"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-lead-action-planner", name: "County lead action planner", purpose: "Local county weekly plan.", currentStatus: "functional", trigger: "county lead", inputs: "county", outputs: "tasks", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: ["/admin/counties"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "power-of-five-task-router", name: "Power of 5 task router", purpose: "PO5 gap tasks.", currentStatus: "functional", trigger: "PO5 panel", inputs: "gaps", outputs: "package", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "social-media-content-safety-coach", name: "Social content safety coach", purpose: "Draft-only + approval warnings.", currentStatus: "functional", trigger: "social", inputs: "draft", outputs: "warnings", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No publish", deterministicHelperPath: RULES, routesUsingTool: ["/admin/workbench/social"], observationEvents: ["copilot_risk_warning_shown"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "social-media-event-content-planner", name: "Social event content planner", purpose: "Event highlight drafts.", currentStatus: "partial", trigger: "hot wash", inputs: "media", outputs: "plan", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-audience-risk-scanner", name: "Comms audience risk scanner", purpose: "Audience size + gate scan.", currentStatus: "functional", trigger: "ECC", inputs: "audience", outputs: "risk", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "high", guardrails: "EMAIL_SEND_ENABLED", deterministicHelperPath: RULES, routesUsingTool: ["/admin/workbench/email-command-center"], observationEvents: ["copilot_risk_warning_shown"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "communications-message-calendar-builder", name: "Comms message calendar builder", purpose: "Draft calendar lanes.", currentStatus: "partial", trigger: "comms center", inputs: "week", outputs: "calendar", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No send", deterministicHelperPath: RULES, routesUsingTool: ["/admin/communications"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "host-invite-list-coach", name: "Host invite list coach", purpose: "Host prep + invite checklist.", currentStatus: "functional", trigger: "host", inputs: "event", outputs: "package", readsFrom: RULES, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "No send", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-system-gap-copilot", name: "Operator system gap copilot", purpose: "OS-wide gap summary.", currentStatus: "functional", trigger: "operator", inputs: "os bundle", outputs: "gaps", readsFrom: CORE, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: CORE, routesUsingTool: ["/admin/ai-command-center"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "sprint-priority-copilot", name: "Sprint priority copilot", purpose: "Suggest sprint focus.", currentStatus: "partial", trigger: "operator", inputs: "backlog", outputs: "priorities", readsFrom: "tool-builder-queue", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "demo-readiness-copilot", name: "Demo readiness copilot", purpose: "Presentation path for demos.", currentStatus: "functional", trigger: "presentation", inputs: "snapshot", outputs: "demo steps", readsFrom: "presentation-readiness-scorer", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: CORE, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "copilot-tool-gap-detector", name: "Copilot tool gap detector", purpose: "Missing tools per copilot.", currentStatus: "functional", trigger: "copilot audit", inputs: "role", outputs: "gaps", readsFrom: RULES, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: RULES, routesUsingTool: ["/admin/ai-command-center/copilots"], observationEvents: ["copilot_tool_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "copilot-training-gap-detector", name: "Copilot training gap detector", purpose: "Training not complete for role.", currentStatus: "functional", trigger: "readiness", inputs: "progress", outputs: "modules", readsFrom: READY, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: READY, routesUsingTool: [...ROUTES], observationEvents: ["copilot_training_recommended"], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_COPILOT_TOOLING_TOOL_CONTRACTS = TOOLS;
export const SPRINT_COPILOT_TOOLING_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
