import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 10;
const L = "single_campaign_hardening" as const;
const DB = "src/lib/agents/dashboard-builder/";
const ONB = "src/lib/agents/onboarding/";
const ROUTES = ["/admin/ai-command-center", "/admin/onboarding", "/admin/ai-command-center/dashboard-builder"] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "dashboard-request-interpreter", name: "Dashboard request interpreter", purpose: "Parse role/task/skill from operator request.", currentStatus: "functional", trigger: "Dashboard builder", inputs: "role, task, freeform", outputs: "InterpretedDashboardRequest", readsFrom: `${DB}dashboard-request-interpreter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No code gen", deterministicHelperPath: `${DB}dashboard-request-interpreter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-component-registry", name: "Dashboard component registry", purpose: "Safe reusable dashboard blocks.", currentStatus: "functional", trigger: "Blueprint build", inputs: "—", outputs: "DashboardBlockDefinition[]", readsFrom: `${DB}dashboard-component-registry.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${DB}dashboard-component-registry.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-layout-planner", name: "Dashboard layout planner", purpose: "Row layout primary/secondary.", currentStatus: "functional", trigger: "Blueprint build", inputs: "allowed blocks", outputs: "LayoutRow[]", readsFrom: `${DB}dashboard-layout-planner.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${DB}dashboard-layout-planner.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-blueprint-builder", name: "Dashboard blueprint builder", purpose: "Assemble safe blueprint + preview.", currentStatus: "functional", trigger: "Build button", inputs: "request", outputs: "DashboardBlueprint", readsFrom: `${DB}dashboard-blueprint-builder.ts`, writesTo: "localStorage optional", humanApprovalRequired: false, riskLevel: "low", guardrails: "Blueprint only", deterministicHelperPath: `${DB}dashboard-blueprint-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Rendered dashboards", testChecklist: [] }),
  c({ id: "dashboard-safety-guard", name: "Dashboard safety guard", purpose: "Block high-risk blocks for new users.", currentStatus: "functional", trigger: "Blueprint build", inputs: "blocks, request", outputs: "DashboardSafetyResult", readsFrom: `${DB}dashboard-safety-guard.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Human supervisor flags", deterministicHelperPath: `${DB}dashboard-safety-guard.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-onboarding-agent", name: "Role onboarding agent", purpose: "8-step role onboarding flow.", currentStatus: "functional", trigger: "/admin/onboarding", inputs: "RoleOnboardingProfile", outputs: "RoleOnboardingResult", readsFrom: `${ONB}role-onboarding-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ONB}role-onboarding-engine.ts`, routesUsingTool: ["/admin/onboarding"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "user-skillset-analyzer", name: "User skillset analyzer", purpose: "Map experience to detail level.", currentStatus: "functional", trigger: "Onboarding", inputs: "experience", outputs: "skillLevel", readsFrom: `${DB}dashboard-request-interpreter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${DB}dashboard-request-interpreter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "user-permission-recommender", name: "User permission recommender", purpose: "Scaffold permission recommendations.", currentStatus: "functional", trigger: "Placement agent", inputs: "role", outputs: "permissionScaffold", readsFrom: `${ONB}user-role-placement-agent.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Scaffold only", deterministicHelperPath: `${ONB}user-role-placement-agent.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Real RBAC", testChecklist: [] }),
  c({ id: "user-role-placement-agent", name: "User role placement agent", purpose: "Recommend role, tasks, training.", currentStatus: "functional", trigger: "Onboarding complete", inputs: "profile", outputs: "UserPlacementRecommendation", readsFrom: `${ONB}user-role-placement-agent.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ONB}user-role-placement-agent.ts`, routesUsingTool: ["/admin/onboarding"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "first-task-recommender", name: "First task recommender", purpose: "Top 3 tasks for new role.", currentStatus: "functional", trigger: "Placement", inputs: "role", outputs: "firstTasks", readsFrom: `${ONB}user-role-placement-agent.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ONB}user-role-placement-agent.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "training-path-builder", name: "Training path builder", purpose: "Onboarding + builder links.", currentStatus: "functional", trigger: "Onboarding", inputs: "role", outputs: "trainingPath", readsFrom: `${ONB}role-onboarding-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ONB}role-onboarding-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "new-user-friction-reducer", name: "New user friction reducer", purpose: "Simple layouts + onboarding blocks.", currentStatus: "functional", trigger: "skill=new", inputs: "request", outputs: "reduced layout", readsFrom: `${DB}dashboard-layout-planner.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${DB}dashboard-layout-planner.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-dashboard-matcher", name: "Role dashboard matcher", purpose: "Match role to workflow block sets.", currentStatus: "functional", trigger: "Interpreter", inputs: "targetRole", outputs: "workflowFocus", readsFrom: `${DB}dashboard-request-interpreter.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${DB}dashboard-request-interpreter.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "single-campaign-mode-optimizer", name: "Single campaign mode optimizer", purpose: "Kelly SOS default; hide dev tenancy.", currentStatus: "functional", trigger: "Admin shell", inputs: "env", outputs: "Kelly badge", readsFrom: "src/lib/campaign-tenancy/single-campaign-mode.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/campaign-tenancy/single-campaign-mode.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "presentation-readiness-scorer", name: "Presentation readiness scorer", purpose: "Demo readiness score for Netlify.", currentStatus: "functional", trigger: "Command center", inputs: "snapshot", outputs: "PresentationReadinessReport", readsFrom: `${ONB}presentation-readiness-scorer.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ONB}presentation-readiness-scorer.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-os-polish-gap-detector", name: "Campaign OS polish gap detector", purpose: "Flag blockers hurting presentation.", currentStatus: "functional", trigger: "Readiness scorer", inputs: "snapshot", outputs: "gaps[]", readsFrom: `${ONB}presentation-readiness-scorer.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${ONB}presentation-readiness-scorer.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_SINGLE_CAMPAIGN_HARDENING_TOOL_CONTRACTS = TOOLS;
export const SPRINT_SINGLE_CAMPAIGN_HARDENING_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
