import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 0;
const L = "victory_os" as const;
const VO = "src/lib/victory-os/";
const ROUTES = [
  "/admin/mission-brief",
  "/admin/victory-board",
  "/admin/daily-brief",
  "/admin/election-day",
  "/admin/ai-command-center",
  "/admin/campaign-manager-dashboard",
  "/admin/calendar-command-center/kelly",
] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

function c1(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: 1, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

function c2(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: 2, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

function c3(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: 3, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

function c4(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: 4, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

function c5(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: 5, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({
    id: "victory-map-loader",
    name: "Victory map loader",
    purpose: "Load 75-county Layer 0 profiles with ops enrichment.",
    currentStatus: "functional",
    trigger: "Path to Victory / agent context",
    inputs: "—",
    outputs: "CountyVictoryContext[]",
    readsFrom: `${VO}load-victory-map.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only; planning scenario only",
    deterministicHelperPath: `${VO}load-victory-map.ts`,
    routesUsingTool: [...ROUTES],
    observationEvents: ["victory_map_viewed"],
    futureAutomationPath: "",
    testChecklist: ["victory:map:verify"],
  }),
  c({
    id: "victory-map-dimension-classifier",
    name: "Victory map dimension classifier",
    purpose: "Deterministic electoral importance, opportunity, readiness from win-target + KPI heuristics.",
    currentStatus: "functional",
    trigger: "Seed / rebuild",
    inputs: "CountyWinTargetRow[], KPI",
    outputs: "VictoryMapCountyProfile",
    readsFrom: `${VO}classify-county-dimensions.ts`,
    writesTo: "victory-map-v1.json (via seed script)",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Leadership overrides; CM lock required",
    deterministicHelperPath: `${VO}classify-county-dimensions.ts`,
    routesUsingTool: [...ROUTES],
    observationEvents: [],
    futureAutomationPath: "Leadership lock workflow",
    testChecklist: ["victory:map:seed"],
  }),
  c({
    id: "deployment-priority-calculator",
    name: "Deployment priority calculator",
    purpose: "Victory Importance × Opportunity × Readiness Gap × Urgency (doctrine formula).",
    currentStatus: "functional",
    trigger: "Map load / rank",
    inputs: "dimensions + ops status",
    outputs: "DeploymentPriorityFactors",
    readsFrom: `${VO}score-maps.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Advisory only — not autonomous deployment",
    deterministicHelperPath: `${VO}score-maps.ts`,
    routesUsingTool: [...ROUTES],
    observationEvents: [],
    futureAutomationPath: "Sprint 1 Decision Engine input",
    testChecklist: [],
  }),
  c({
    id: "victory-map-statewide-brief-composer",
    name: "Victory map statewide brief composer",
    purpose: "Plain-language statewide Victory Map summary for copilots.",
    currentStatus: "functional",
    trigger: "Agent / CM context",
    inputs: "—",
    outputs: "brief text",
    readsFrom: `${VO}victory-map-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "INTERNAL_DRAFT; no Top 10 decisions",
    deterministicHelperPath: `${VO}victory-map-intelligence.ts#composeVictoryMapStatewideBrief`,
    routesUsingTool: [...ROUTES],
    observationEvents: ["victory_map_brief_composed"],
    futureAutomationPath: "",
    testChecklist: ["victory:map:verify"],
  }),
  c({
    id: "victory-map-county-brief-builder",
    name: "Victory map county brief builder",
    purpose: "Single-county Layer 0 narrative for event/county copilots.",
    currentStatus: "functional",
    trigger: "countySlug",
    inputs: "countySlug",
    outputs: "VictoryMapCountyBrief",
    readsFrom: `${VO}victory-map-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only county bridge",
    deterministicHelperPath: `${VO}victory-map-intelligence.ts#buildVictoryMapCountyBrief`,
    routesUsingTool: [...ROUTES, "/admin/counties/[slug]"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c({
    id: "victory-map-priority-ranker",
    name: "Victory map priority ranker",
    purpose: "Rank counties by deployment priority for advisory heat lists.",
    currentStatus: "functional",
    trigger: "Statewide load",
    inputs: "limit?",
    outputs: "VictoryMapCountyBrief[]",
    readsFrom: `${VO}victory-map-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Not Top 10 decisions — Sprint 0 preview only",
    deterministicHelperPath: `${VO}victory-map-intelligence.ts#rankCountiesByDeploymentPriority`,
    routesUsingTool: [...ROUTES],
    observationEvents: [],
    futureAutomationPath: "Sprint 1 feeds Decision Generator",
    testChecklist: [],
  }),
  c({
    id: "victory-map-completeness-auditor",
    name: "Victory map completeness auditor",
    purpose: "Audit 75-county coverage, critical ops red flags, leadership lock gaps.",
    currentStatus: "functional",
    trigger: "Verify script / agent preflight",
    inputs: "—",
    outputs: "VictoryMapAuditFinding[]",
    readsFrom: `${VO}victory-map-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Advisory audit only",
    deterministicHelperPath: `${VO}victory-map-intelligence.ts#auditVictoryMapCompleteness`,
    routesUsingTool: [...ROUTES],
    observationEvents: ["victory_map_audit_run"],
    futureAutomationPath: "",
    testChecklist: ["victory:map:verify"],
  }),
  c({
    id: "victory-map-agent-context-bundle",
    name: "Victory map agent context bundle",
    purpose: "Safe copilot context package for Victory OS Layer 0 (Sprint 0).",
    currentStatus: "functional",
    trigger: "Orchestration / copilot",
    inputs: "—",
    outputs: "agent context JSON",
    readsFrom: `${VO}victory-map-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "humanReviewRequired; no calendar writes; no fake Top 10",
    deterministicHelperPath: `${VO}victory-map-intelligence.ts#buildVictoryMapAgentContext`,
    routesUsingTool: ["/admin/ai-command-center", "/admin/mission-brief"],
    observationEvents: ["victory_map_agent_context_loaded"],
    futureAutomationPath: "Sprint 1 decision bundle extends this",
    testChecklist: ["victory:map:verify"],
  }),
  c({
    id: "critical-county-intervention-lister",
    name: "Critical county intervention lister",
    purpose: "List critical counties with weak readiness or yellow/red ops for CM review.",
    currentStatus: "functional",
    trigger: "Command center",
    inputs: "—",
    outputs: "VictoryMapCountyBrief[]",
    readsFrom: `${VO}victory-map-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Advisory — CM approves moves",
    deterministicHelperPath: `${VO}victory-map-intelligence.ts#listCriticalCountiesNeedingIntervention`,
    routesUsingTool: [...ROUTES],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c({
    id: "victory-season-resolver",
    name: "Victory season resolver",
    purpose: "Resolve current campaign victory season from victory-os-seasons-v1.json.",
    currentStatus: "functional",
    trigger: "Map / brief load",
    inputs: "asOf date?",
    outputs: "season id + label",
    readsFrom: `${VO}load-victory-map.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only doctrine file",
    deterministicHelperPath: `${VO}load-victory-map.ts#resolveCurrentVictorySeason`,
    routesUsingTool: [...ROUTES],
    observationEvents: [],
    futureAutomationPath: "Sprint 1 urgency factor",
    testChecklist: [],
  }),
  c1({
    id: "weekly-decision-generator",
    name: "Weekly decision generator",
    purpose: "Generate Top 10 CM decisions from Victory Map + season rules.",
    currentStatus: "functional",
    trigger: "Monday / npm run victory:decisions",
    inputs: "weekKey?, asOf?",
    outputs: "WeeklyDecisionBrief",
    readsFrom: `${VO}decision-engine/generate-weekly-decisions.ts`,
    writesTo: "data/mission-briefs/{weekKey}.json",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "INTERNAL_DRAFT; no auto-deploy",
    deterministicHelperPath: `${VO}decision-engine/generate-weekly-decisions.ts`,
    routesUsingTool: [...ROUTES],
    observationEvents: ["weekly_decision_brief_generated"],
    futureAutomationPath: "Scheduled Monday cron",
    testChecklist: ["victory:decisions:verify"],
  }),
  c1({
    id: "decision-brief-snapshot-loader",
    name: "Decision brief snapshot loader",
    purpose: "Load or generate persisted weekly brief snapshots.",
    currentStatus: "functional",
    trigger: "/admin/mission-brief",
    inputs: "weekKey",
    outputs: "WeeklyDecisionBrief",
    readsFrom: `${VO}decision-engine/load-decision-brief.ts`,
    writesTo: "data/mission-briefs/",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only unless regenerate API",
    deterministicHelperPath: `${VO}decision-engine/load-decision-brief.ts`,
    routesUsingTool: [...ROUTES, "/api/admin/victory-os/decisions"],
    observationEvents: ["weekly_decision_brief_viewed"],
    futureAutomationPath: "",
    testChecklist: ["victory:decisions"],
  }),
  c1({
    id: "county-resource-recommendation-resolver",
    name: "County resource recommendation resolver",
    purpose: "Resolve Kelly tier, resource type, and recommendation copy per county.",
    currentStatus: "functional",
    trigger: "Decision generate",
    inputs: "CountyVictoryContext, seasonId",
    outputs: "CountyDecisionRecommendation",
    readsFrom: `${VO}decision-engine/resolve-resource-recommendation.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Advisory recommendations only",
    deterministicHelperPath: `${VO}decision-engine/resolve-resource-recommendation.ts`,
    routesUsingTool: [...ROUTES],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c1({
    id: "decision-engine-agent-context-bundle",
    name: "Decision engine agent context bundle",
    purpose: "Copilot-safe Layer 1 brief bundle with Top 10 and deployment views.",
    currentStatus: "functional",
    trigger: "Orchestration / CM copilot",
    inputs: "weekKey?",
    outputs: "agent context JSON",
    readsFrom: `${VO}decision-engine-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "humanReviewRequired; CM approves decisions",
    deterministicHelperPath: `${VO}decision-engine-intelligence.ts#buildDecisionEngineAgentContext`,
    routesUsingTool: ["/admin/ai-command-center", "/admin/mission-brief"],
    observationEvents: ["decision_engine_context_loaded"],
    futureAutomationPath: "Kelly copilot integration",
    testChecklist: ["victory:decisions:verify"],
  }),
  c1({
    id: "decision-status-workflow",
    name: "Decision status workflow",
    purpose: "CM approve / decline / modify individual decisions in brief snapshot.",
    currentStatus: "functional",
    trigger: "Mission brief UI",
    inputs: "decisionId, status",
    outputs: "updated brief",
    readsFrom: "/api/admin/victory-os/decisions",
    writesTo: "data/mission-briefs/{weekKey}.json",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "CM-only; no calendar side effects",
    deterministicHelperPath: `${VO}decision-engine/load-decision-brief.ts#updateDecisionStatusInBrief`,
    routesUsingTool: ["/admin/mission-brief"],
    observationEvents: ["decision_status_updated"],
    futureAutomationPath: "Sprint 2 mission linkage complete",
    testChecklist: [],
  }),
  c2({
    id: "county-mission-stack-generator",
    name: "County mission stack generator",
    purpose: "Build long/monthly/weekly/daily mission stack for a county.",
    currentStatus: "functional",
    trigger: "Mission sync",
    inputs: "CountyVictoryContext, decision?",
    outputs: "CountyMissionStack",
    readsFrom: `${VO}mission-framework/generate-county-mission-stack.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Proposed missions only until CM approves",
    deterministicHelperPath: `${VO}mission-framework/generate-county-mission-stack.ts`,
    routesUsingTool: [...ROUTES, "/admin/counties/[slug]"],
    observationEvents: ["county_mission_stack_generated"],
    futureAutomationPath: "",
    testChecklist: ["victory:missions:verify"],
  }),
  c2({
    id: "daily-task-builder",
    name: "Daily task builder",
    purpose: "Generate daily execution checklist from weekly mission resource type.",
    currentStatus: "functional",
    trigger: "Stack generate",
    inputs: "weekly mission, weekKey",
    outputs: "CountyDailyTask[]",
    readsFrom: `${VO}mission-framework/build-daily-tasks.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Checklist only — no auto-schedule",
    deterministicHelperPath: `${VO}mission-framework/build-daily-tasks.ts`,
    routesUsingTool: [...ROUTES],
    observationEvents: [],
    futureAutomationPath: "Calendar tactic linkage Sprint 5",
    testChecklist: [],
  }),
  c2({
    id: "mission-brief-sync-engine",
    name: "Mission brief sync engine",
    purpose: "Sync all county stacks from weekly decision brief and link decision IDs.",
    currentStatus: "functional",
    trigger: "npm run victory:missions:sync",
    inputs: "weekKey",
    outputs: "CountyMissionSyncResult",
    readsFrom: `${VO}mission-framework/sync-missions-from-brief.ts`,
    writesTo: "data/county-missions/registry-v1.json",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Updates brief linkedMissionId fields",
    deterministicHelperPath: `${VO}mission-framework/sync-missions-from-brief.ts`,
    routesUsingTool: [...ROUTES, "/api/admin/victory-os/missions"],
    observationEvents: ["county_missions_synced"],
    futureAutomationPath: "Post-decision-generate hook",
    testChecklist: ["victory:missions:sync", "victory:missions:verify"],
  }),
  c2({
    id: "county-mission-registry-loader",
    name: "County mission registry loader",
    purpose: "Load statewide mission registry and per-county stacks.",
    currentStatus: "functional",
    trigger: "Mission brief / county admin",
    inputs: "countySlug?",
    outputs: "CountyMissionsRegistryFile",
    readsFrom: `${VO}mission-framework/load-county-missions.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only unless status API",
    deterministicHelperPath: `${VO}mission-framework/load-county-missions.ts`,
    routesUsingTool: [...ROUTES, "/admin/counties/[slug]"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: ["victory:missions:verify"],
  }),
  c2({
    id: "county-mission-agent-context-bundle",
    name: "County mission agent context bundle",
    purpose: "Copilot context for county four-level mission stack.",
    currentStatus: "functional",
    trigger: "Orchestration",
    inputs: "countySlug?",
    outputs: "agent context JSON",
    readsFrom: `${VO}mission-framework-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "No calendar writes from mission context",
    deterministicHelperPath: `${VO}mission-framework-intelligence.ts#buildCountyMissionAgentContext`,
    routesUsingTool: [...ROUTES, "/admin/counties/[slug]"],
    observationEvents: ["county_mission_context_loaded"],
    futureAutomationPath: "",
    testChecklist: ["victory:missions:verify"],
  }),
  c2({
    id: "mission-status-workflow",
    name: "Mission status workflow",
    purpose: "Update mission or daily task status in registry.",
    currentStatus: "functional",
    trigger: "Mission UI",
    inputs: "countySlug, missionId|taskId, status",
    outputs: "updated registry",
    readsFrom: "/api/admin/victory-os/missions",
    writesTo: "data/county-missions/registry-v1.json",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Field checklist status only",
    deterministicHelperPath: `${VO}mission-framework/load-county-missions.ts`,
    routesUsingTool: ["/admin/mission-brief"],
    observationEvents: ["mission_status_updated"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c3({
    id: "monday-brief-view-model-composer",
    name: "Monday brief view model composer",
    purpose: "Compose full Mission Brief UI bundle — decisions, readiness, delta, missions.",
    currentStatus: "functional",
    trigger: "/admin/mission-brief load",
    inputs: "weekKey?",
    outputs: "MondayBriefViewModel",
    readsFrom: `${VO}mission-brief/compose-monday-brief-view-model.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "INTERNAL_DRAFT display only",
    deterministicHelperPath: `${VO}mission-brief/compose-monday-brief-view-model.ts`,
    routesUsingTool: ["/admin/mission-brief", "/api/admin/victory-os/brief"],
    observationEvents: ["monday_brief_viewed"],
    futureAutomationPath: "",
    testChecklist: ["victory:brief:verify"],
  }),
  c3({
    id: "monday-pipeline-runner",
    name: "Monday pipeline runner",
    purpose: "Regenerate decisions, persist brief, sync county missions in one step.",
    currentStatus: "functional",
    trigger: "Run Monday pipeline button / npm run victory:monday",
    inputs: "weekKey",
    outputs: "MondayBriefViewModel",
    readsFrom: "/api/admin/victory-os/brief",
    writesTo: "data/mission-briefs/ + data/county-missions/",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "CM triggers only",
    deterministicHelperPath: "scripts/victory-os/run-monday-pipeline.ts",
    routesUsingTool: ["/admin/mission-brief"],
    observationEvents: ["monday_pipeline_completed"],
    futureAutomationPath: "Scheduled Monday cron with CM notify",
    testChecklist: ["victory:monday"],
  }),
  c3({
    id: "brief-week-delta-analyzer",
    name: "Brief week delta analyzer",
    purpose: "Week-over-week Top 10 and pace delta for CM standup.",
    currentStatus: "functional",
    trigger: "Monday brief load",
    inputs: "WeeklyDecisionBrief",
    outputs: "BriefWeekDelta",
    readsFrom: `${VO}mission-brief/compute-brief-week-delta.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Requires prior week snapshot",
    deterministicHelperPath: `${VO}mission-brief/compute-brief-week-delta.ts`,
    routesUsingTool: ["/admin/mission-brief"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c3({
    id: "brief-readiness-scorer",
    name: "Brief readiness scorer",
    purpose: "CM approval progress and execute-ready gate.",
    currentStatus: "functional",
    trigger: "Monday brief",
    inputs: "brief + mission registry",
    outputs: "BriefReadiness",
    readsFrom: `${VO}mission-brief/compute-brief-readiness.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: `${VO}mission-brief/compute-brief-readiness.ts`,
    routesUsingTool: ["/admin/mission-brief"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: ["victory:brief:verify"],
  }),
  c3({
    id: "monday-brief-print-exporter",
    name: "Monday brief print exporter",
    purpose: "Print-ready HTML brief for CM standup packet.",
    currentStatus: "functional",
    trigger: "Print brief link",
    inputs: "weekKey",
    outputs: "text/html",
    readsFrom: "/api/admin/victory-os/brief/print",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "INTERNAL_DRAFT watermark in copy",
    deterministicHelperPath: "src/app/api/admin/victory-os/brief/print/route.ts",
    routesUsingTool: ["/admin/mission-brief"],
    observationEvents: ["monday_brief_printed"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c3({
    id: "monday-brief-agent-context-bundle",
    name: "Monday brief agent context bundle",
    purpose: "Full Sprint 3 copilot context — brief + decisions + missions.",
    currentStatus: "functional",
    trigger: "Orchestration / CM copilot",
    inputs: "weekKey?",
    outputs: "agent context JSON",
    readsFrom: `${VO}mission-brief-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Campaign OS home context; no auto-execute",
    deterministicHelperPath: `${VO}mission-brief-intelligence.ts#composeMondayBriefAgentContext`,
    routesUsingTool: ["/admin/mission-brief", "/admin/ai-command-center"],
    observationEvents: ["monday_brief_agent_context_loaded"],
    futureAutomationPath: "",
    testChecklist: ["victory:brief:verify"],
  }),
  c4({
    id: "victory-board-view-model-composer",
    name: "Victory Board view model composer",
    purpose: "Compose Sprint 4 board — map pins, charts, regional rollups from Top 10 decisions.",
    currentStatus: "functional",
    trigger: "/admin/victory-board load",
    inputs: "weekKey?",
    outputs: "VictoryBoardViewModel",
    readsFrom: `${VO}victory-board/compose-victory-board-view-model.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Intelligence from decisions only — not raw CRM/calendar",
    deterministicHelperPath: `${VO}victory-board/compose-victory-board-view-model.ts`,
    routesUsingTool: ["/admin/victory-board", "/api/admin/victory-os/victory-board"],
    observationEvents: ["victory_board_viewed"],
    futureAutomationPath: "",
    testChecklist: ["victory:board:verify"],
  }),
  c4({
    id: "victory-board-map-layer-renderer",
    name: "Victory Board map layer renderer",
    purpose: "Color county pins by deployment priority, ops, electoral, or Top 10 rank.",
    currentStatus: "functional",
    trigger: "Map layer toggle on Victory Board",
    inputs: "VictoryBoardMapLayer + counties",
    outputs: "VictoryBoardCountyPin[]",
    readsFrom: `${VO}victory-board/board-color-maps.ts`,
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Advisory visualization until CM approves decisions",
    deterministicHelperPath: `${VO}victory-board/compose-victory-board-view-model.ts#rebuildVictoryBoardPinsForLayer`,
    routesUsingTool: ["/admin/victory-board"],
    observationEvents: ["victory_board_layer_changed"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c4({
    id: "victory-board-snapshot-persister",
    name: "Victory Board snapshot persister",
    purpose: "Persist board JSON snapshot for week-over-week reference.",
    currentStatus: "functional",
    trigger: "Save snapshot / npm run victory:board:compose",
    inputs: "weekKey",
    outputs: "data/victory-board/board-v1.json",
    readsFrom: "/api/admin/victory-os/victory-board",
    writesTo: "data/victory-board/board-v1.json",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "INTERNAL_DRAFT snapshot only",
    deterministicHelperPath: `${VO}victory-board/load-victory-board-snapshot.ts`,
    routesUsingTool: ["/admin/victory-board"],
    observationEvents: ["victory_board_snapshot_saved"],
    futureAutomationPath: "Auto-compose after Monday pipeline",
    testChecklist: ["victory:board:compose"],
  }),
  c4({
    id: "victory-board-agent-context-bundle",
    name: "Victory Board agent context bundle",
    purpose: "Full Sprint 4 copilot context — board + Monday brief + regional rollups.",
    currentStatus: "functional",
    trigger: "Orchestration / CM copilot",
    inputs: "weekKey?",
    outputs: "agent context JSON",
    readsFrom: `${VO}victory-board-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Display intelligence from decisions; no auto-deploy",
    deterministicHelperPath: `${VO}victory-board-intelligence.ts#composeVictoryBoardAgentContext`,
    routesUsingTool: ["/admin/victory-board", "/admin/ai-command-center"],
    observationEvents: ["victory_board_agent_context_loaded"],
    futureAutomationPath: "",
    testChecklist: ["victory:board:verify"],
  }),
  c5({
    id: "tactic-linkage-sync",
    name: "Tactic linkage sync",
    purpose: "Link calendar rows to county weekly missions and Top 10 decisions.",
    currentStatus: "functional",
    trigger: "Monday pipeline / npm run victory:tactics:sync",
    inputs: "weekKey",
    outputs: "data/tactic-linkage/registry-v1.json",
    readsFrom: `${VO}tactic-linkage/sync-tactic-linkage.ts`,
    writesTo: "data/tactic-linkage/registry-v1.json",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Calendar downstream of missions — read-only on calendar",
    deterministicHelperPath: `${VO}tactic-linkage/load-tactic-linkage.ts`,
    routesUsingTool: ["/admin/mission-brief?view=tactics", "/api/admin/victory-os/tactics"],
    observationEvents: ["tactic_linkage_synced"],
    futureAutomationPath: "Auto-link on calendar ingest",
    testChecklist: ["victory:tactics:verify"],
  }),
  c5({
    id: "season5-daily-brief-generator",
    name: "Season 5 daily brief generator",
    purpose: "Daily Kelly deployment brief for final 14 days cadence.",
    currentStatus: "functional",
    trigger: "/admin/daily-brief · npm run victory:daily",
    inputs: "dayKey?",
    outputs: "DailyDecisionBrief",
    readsFrom: `${VO}daily-decisions/generate-daily-decisions.ts`,
    writesTo: "data/daily-briefs/",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Season 5 daily cadence; weekly brief remains source",
    deterministicHelperPath: `${VO}daily-decisions/load-daily-brief.ts`,
    routesUsingTool: ["/admin/daily-brief", "/api/admin/victory-os/daily-brief"],
    observationEvents: ["daily_brief_generated"],
    futureAutomationPath: "Cron at 6am CT in Season 5",
    testChecklist: ["victory:daily:verify"],
  }),
  c5({
    id: "election-day-ops-composer",
    name: "Election Day ops center composer",
    purpose: "County goal/actual/gap cards and side panels for Nov 3 execution surface.",
    currentStatus: "functional",
    trigger: "/admin/election-day load",
    inputs: "—",
    outputs: "ElectionDayViewModel",
    readsFrom: `${VO}election-day/compose-election-day-view-model.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Advisory turnout until live feed; not a calendar",
    deterministicHelperPath: `${VO}election-day/compose-election-day-view-model.ts`,
    routesUsingTool: ["/admin/election-day", "/api/admin/victory-os/election-day"],
    observationEvents: ["election_day_ops_viewed"],
    futureAutomationPath: "Live SOS turnout API integration",
    testChecklist: ["victory:election-day:verify"],
  }),
  c5({
    id: "victory-os-full-agent-context",
    name: "Victory OS full agent context",
    purpose: "Complete Sprint 0–5 bundle for CM copilot — brief, board, daily, tactics, election day.",
    currentStatus: "functional",
    trigger: "Orchestration / Command Center",
    inputs: "weekKey?",
    outputs: "agent context JSON",
    readsFrom: `${VO}sprint5-intelligence.ts`,
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Recommend only — no auto-execute",
    deterministicHelperPath: `${VO}sprint5-intelligence.ts#composeVictoryOsFullAgentContext`,
    routesUsingTool: ROUTES,
    observationEvents: ["victory_os_full_context_loaded"],
    futureAutomationPath: "",
    testChecklist: ["victory:os:verify"],
  }),
];

export const SPRINT_VICTORY_OS_TOOL_CONTRACTS = TOOLS;
export const SPRINT_VICTORY_OS_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
