import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 2;
const L = "agent_intelligence_sprint2" as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

export const SPRINT2_AGENT_TOOL_CONTRACTS: CampaignAiToolContract[] = [
  c({
    id: "live-observation-capture",
    name: "Live observation capture",
    purpose: "Append safe UX metadata from operator surfaces via server action.",
    currentStatus: "functional",
    trigger: "AgentObservationTracker",
    inputs: "UserUxObservationEvent + route meta",
    outputs: "UserObservationEntry",
    readsFrom: "record-observation-safe.ts",
    writesTo: "data/campaign-events/user-observations.json",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No PII freeform; admin session required",
    deterministicHelperPath: "src/components/agents/AgentObservationTracker.tsx",
    routesUsingTool: ["/admin/candidate-dashboard", "/admin/campaign-manager-dashboard", "/admin/campaign-events/workbench"],
    observationEvents: ["page_viewed", "next_action_clicked"],
    futureAutomationPath: "Batch pattern miner",
    testChecklist: ["agents:test-observations"],
  }),
  c({
    id: "cross-domain-context-composer",
    name: "Cross-domain context composer",
    purpose: "Fuse calendar, travel, approval, intake blockers into one summary.",
    currentStatus: "functional",
    trigger: "Page load / command center",
    inputs: "CrossDomainContextInput",
    outputs: "CrossDomainContext",
    readsFrom: "cross-domain-context-composer.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only synthesis",
    deterministicHelperPath: "src/lib/agents/orchestration/cross-domain-context-composer.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Kelly Agent router input",
    testChecklist: ["composeCrossDomainContext"],
  }),
  c({
    id: "agent-memory-write-planner",
    name: "Agent memory write planner",
    purpose: "Plan memory candidates with risk + human review flags.",
    currentStatus: "functional",
    trigger: "Observation append",
    inputs: "UserObservationEntry",
    outputs: "MemoryWritePlan",
    readsFrom: "agent-memory-write-planner.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "No auto high-risk memory",
    deterministicHelperPath: "src/lib/agents/memory/agent-memory-write-planner.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: ["suggestion_accepted", "approval_decision_made"],
    futureAutomationPath: "Memory review queue UI",
    testChecklist: ["planMemoryWrite"],
  }),
  c({
    id: "workflow-friction-detector",
    name: "Workflow friction detector",
    purpose: "Detect repeated visits, abandoned queues, blocked promotions.",
    currentStatus: "functional",
    trigger: "Command center / CM dashboard",
    inputs: "observation log",
    outputs: "WorkflowFrictionSignal[]",
    readsFrom: "workflow-friction-detector.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Internal only",
    deterministicHelperPath: "src/lib/agents/user-intelligence/workflow-friction-detector.ts",
    routesUsingTool: ["/admin/ai-command-center", "/admin/campaign-manager-dashboard"],
    observationEvents: ["flow_abandoned", "no_results_search"],
    futureAutomationPath: "Proactive UX tickets",
    testChecklist: ["detectWorkflowFriction"],
  }),
  c({
    id: "adaptive-next-action-engine",
    name: "Adaptive next action engine",
    purpose: "V2 next actions with categories, observation weighting, cross-domain blockers.",
    currentStatus: "functional",
    trigger: "AgentNextActionPanel",
    inputs: "NextActionEngineInput",
    outputs: "NextActionResult",
    readsFrom: "next-action-engine.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Suggest only",
    deterministicHelperPath: "src/lib/agents/user-intelligence/next-action-engine.ts",
    routesUsingTool: ["/admin/candidate-dashboard", "/admin/campaign-manager-dashboard"],
    observationEvents: ["next_action_clicked", "suggestion_rejected"],
    futureAutomationPath: "Acceptance-rate ranking",
    testChecklist: ["buildNextActions category"],
  }),
  c({
    id: "writing-observation-capture",
    name: "Writing observation capture",
    purpose: "Metadata-only writing edit signals (no full body storage).",
    currentStatus: "functional",
    trigger: "Text field edit / accept",
    inputs: "WritingObservationMeta",
    outputs: "WritingStyleObservation",
    readsFrom: "writing-observation-capture.ts",
    writesTo: "data/campaign-events/writing-style-observations.json",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Snippet cap 80 chars",
    deterministicHelperPath: "src/lib/agents/writing-agent/writing-observation-capture.ts",
    routesUsingTool: ["/admin/campaign-events/review"],
    observationEvents: [],
    futureAutomationPath: "Voice profile auto-tune",
    testChecklist: ["recordWritingObservationAction"],
  }),
  c({
    id: "microcopy-context-router",
    name: "Microcopy context router",
    purpose: "Role-aware term explanations + related routes.",
    currentStatus: "functional",
    trigger: "MicrocopyHint",
    inputs: "MicrocopyTerm, role",
    outputs: "MicrocopyEntry",
    readsFrom: "microcopy-registry.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Static registry",
    deterministicHelperPath: "src/lib/agents/ux-intelligence/microcopy-registry.ts",
    routesUsingTool: ["/admin/campaign-events/workbench"],
    observationEvents: ["help_hover_opened"],
    futureAutomationPath: "Generated microcopy drafts",
    testChecklist: ["getMicrocopy"],
  }),
  c({
    id: "user-behavior-signal-reader",
    name: "User behavior signal reader",
    purpose: "Read latest observations for orchestration bundle.",
    currentStatus: "functional",
    trigger: "loadAgentIntelligenceBundle",
    inputs: "user-observations.json",
    outputs: "recent[]",
    readsFrom: "user-observations.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Admin only",
    deterministicHelperPath: "src/lib/agents/orchestration/load-agent-intelligence-bundle.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Stream to warehouse",
    testChecklist: ["loadGlobalUserObservations"],
  }),
  c({
    id: "dashboard-adaptation-planner",
    name: "Dashboard adaptation planner",
    purpose: "Suggest which dashboard cards to emphasize from friction.",
    currentStatus: "partial",
    trigger: "CM dashboard",
    inputs: "friction signals",
    outputs: "card priority hints",
    readsFrom: "workflow-friction-detector.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No auto UI changes",
    deterministicHelperPath: "src/lib/agents/user-intelligence/workflow-friction-detector.ts",
    routesUsingTool: ["/admin/campaign-manager-dashboard"],
    observationEvents: ["dashboard_card_clicked"],
    futureAutomationPath: "A/B card order",
    testChecklist: [],
  }),
  c({
    id: "tool-usage-signal-miner",
    name: "Tool usage signal miner",
    purpose: "Count toolId observations for catalog prioritization.",
    currentStatus: "functional",
    trigger: "Command center",
    inputs: "observations",
    outputs: "toolId counts",
    readsFrom: "load-agent-intelligence-bundle.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Internal",
    deterministicHelperPath: "src/lib/agents/orchestration/load-agent-intelligence-bundle.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Catalog auto-status",
    testChecklist: [],
  }),
  c({
    id: "agent-guardrail-monitor",
    name: "Agent guardrail monitor",
    purpose: "Surface human-control limits on command center.",
    currentStatus: "functional",
    trigger: "Command center",
    inputs: "CAMPAIGN_AI_HUMAN_CONTROL_RULES",
    outputs: "reminder list",
    readsFrom: "tool-contract.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "high",
    guardrails: "Always visible",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/tool-contract.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Env gate dashboard",
    testChecklist: [],
  }),
  c({
    id: "sprint-context-loader",
    name: "Sprint context loader",
    purpose: "Load Agent Intelligence sprint readiness for operator.",
    currentStatus: "partial",
    trigger: "Command center",
    inputs: "BUILD_SPRINT_STATUS.md",
    outputs: "sprint labels",
    readsFrom: "docs/campaign-events/BUILD_SPRINT_STATUS.md",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Docs only",
    deterministicHelperPath: "src/components/admin/campaign-events/AiCommandCenterHub.tsx",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "CI sprint reporter",
    testChecklist: [],
  }),
  c({
    id: "operator-intent-classifier",
    name: "Operator intent classifier",
    purpose: "Infer intent from route + recent observation mix.",
    currentStatus: "partial",
    trigger: "Observation batch",
    inputs: "pathname, events",
    outputs: "intent label",
    readsFrom: "user-personas.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No external profiling",
    deterministicHelperPath: "src/lib/agents/orchestration/cross-domain-context-composer.ts",
    routesUsingTool: [],
    observationEvents: ["page_viewed"],
    futureAutomationPath: "LLM classify",
    testChecklist: [],
  }),
  c({
    id: "campaign-os-context-summarizer",
    name: "Campaign OS context summarizer",
    purpose: "One-paragraph OS summary for master agent.",
    currentStatus: "functional",
    trigger: "Command center",
    inputs: "CrossDomainContext",
    outputs: "contextSummary string",
    readsFrom: "cross-domain-context-composer.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only",
    deterministicHelperPath: "src/lib/agents/orchestration/cross-domain-context-composer.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Kelly recommend API",
    testChecklist: [],
  }),
  c({
    id: "memory-review-queue-builder",
    name: "Memory review queue builder",
    purpose: "List memory candidates requiring human review.",
    currentStatus: "functional",
    trigger: "Command center",
    inputs: "observations",
    outputs: "MemoryWritePlan[]",
    readsFrom: "agent-memory-write-planner.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "No auto commit",
    deterministicHelperPath: "src/lib/agents/memory/agent-memory-write-planner.ts",
    routesUsingTool: ["/admin/ai-command-center#memory"],
    observationEvents: [],
    futureAutomationPath: "Approve memory UI",
    testChecklist: ["buildMemoryCandidatesFromObservations"],
  }),
];

export const SPRINT2_AGENT_CATALOG_ENTRIES: AiToolEntry[] = SPRINT2_AGENT_TOOL_CONTRACTS.map(contractToCatalogEntry);
