/**
 * Kelly OS planning sprint — training, copilots, gamification, tool-builder (V1 contracts only).
 * Docs: docs/campaign-events/*_PLAN.md — no autonomous production code changes.
 */
import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 11;
const L = "kelly_os_planning" as const;
const ROUTES = ["/admin/ai-command-center", "/admin/onboarding", "/admin/ai-command-center/dashboard-builder"] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P1", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  // Training
  c({ id: "training-module-builder", name: "Training module builder", purpose: "Assemble role training modules from templates.", currentStatus: "idea", trigger: "Training admin", inputs: "role, skill", outputs: "TrainingModule[]", readsFrom: "docs/CAMPAIGN_OS_TRAINING_LAYER.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Content review", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Persist modules", testChecklist: [] }),
  c({ id: "role-training-path-builder", name: "Role training path builder", purpose: "Ordered training path per role.", currentStatus: "partial", trigger: "Onboarding", inputs: "role", outputs: "trainingPath", readsFrom: "src/lib/agents/onboarding/role-onboarding-engine.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/onboarding/role-onboarding-engine.ts", routesUsingTool: ["/admin/onboarding"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "skill-assessment-agent", name: "Skill assessment agent", purpose: "Map experience to skill band.", currentStatus: "partial", trigger: "Onboarding step 3", inputs: "experience", outputs: "skillLevel", readsFrom: "src/lib/agents/dashboard-builder/dashboard-request-interpreter.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/dashboard-builder/dashboard-request-interpreter.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "available-time-router", name: "Available time router", purpose: "Route training depth by hours/week.", currentStatus: "idea", trigger: "Onboarding", inputs: "availableHours", outputs: "pace", readsFrom: "docs/CAMPAIGN_OS_TRAINING_LAYER.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "onboarding-readiness-scorer", name: "Onboarding readiness scorer", purpose: "Score readiness after onboarding.", currentStatus: "idea", trigger: "Onboarding complete", inputs: "profile", outputs: "readinessScore", readsFrom: "src/lib/agents/onboarding/user-role-placement-agent.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: ["/admin/onboarding"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "task-confidence-scorer", name: "Task confidence scorer", purpose: "Estimate confidence for first tasks.", currentStatus: "idea", trigger: "Placement", inputs: "role, tasks", outputs: "confidence", readsFrom: "docs/ROLE_PROGRESS_LEVELS_AND_UNLOCKS.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "training-unlock-manager", name: "Training unlock manager", purpose: "Unlock dashboard modules after training.", currentStatus: "idea", trigger: "Module complete", inputs: "moduleId", outputs: "unlockedModules", readsFrom: "docs/DASHBOARD_MODULE_SYSTEM.md", writesTo: "localStorage", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Supervisor gate", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "DB progress", testChecklist: [] }),
  c({ id: "guided-walkthrough-builder", name: "Guided walkthrough builder", purpose: "Step-by-step UI tours.", currentStatus: "idea", trigger: "First visit", inputs: "route, role", outputs: "walkthrough", readsFrom: "docs/CAMPAIGN_OS_TRAINING_LAYER.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Dismissible", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  // Gamification
  c({ id: "role-level-tracker", name: "Role level tracker", purpose: "Track progression level per user.", currentStatus: "idea", trigger: "Task complete", inputs: "userId, role", outputs: "level", readsFrom: "docs/ROLE_PROGRESS_LEVELS_AND_UNLOCKS.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Prisma progress", testChecklist: [] }),
  c({ id: "dashboard-unlock-recommender", name: "Dashboard unlock recommender", purpose: "Recommend next module unlock.", currentStatus: "idea", trigger: "Level up", inputs: "level", outputs: "moduleIds", readsFrom: "src/lib/agents/dashboard-builder/dashboard-component-registry.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "task-achievement-recorder", name: "Task achievement recorder", purpose: "Record completed onboarding/tasks.", currentStatus: "idea", trigger: "Task done", inputs: "taskId", outputs: "achievement", readsFrom: "user-observations.ts", writesTo: "observations JSON", humanApprovalRequired: false, riskLevel: "low", guardrails: "Metadata only", deterministicHelperPath: "src/lib/agents/user-intelligence/user-observations.ts", routesUsingTool: [...ROUTES], observationEvents: ["task_completed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "role-progression-advisor", name: "Role progression advisor", purpose: "Advise next level requirements.", currentStatus: "idea", trigger: "Profile view", inputs: "role, level", outputs: "requirements", readsFrom: "docs/ROLE_PROGRESS_LEVELS_AND_UNLOCKS.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "supervisor-approval-gate", name: "Supervisor approval gate", purpose: "Hold unlock until supervisor approves.", currentStatus: "idea", trigger: "Level 2+ unlock", inputs: "userId", outputs: "approved", readsFrom: "docs/CAMPAIGN_OS_TRAINING_LAYER.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Human only", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  // Copilots (stubs)
  c({ id: "volunteer-copilot", name: "Volunteer copilot", purpose: "Guide volunteers on events, check-in, photos.", currentStatus: "idea", trigger: "Volunteer surfaces", inputs: "role=volunteer", outputs: "nextActions", readsFrom: "docs/ROLE_COPILOT_EXPANSION_PLAN.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No finance/approval", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Dedicated volunteer dashboard", testChecklist: [] }),
  c({ id: "intern-copilot", name: "Intern copilot", purpose: "Intern tasks, receipts, event basics.", currentStatus: "idea", trigger: "Intern onboarding", inputs: "role=intern", outputs: "tasks", readsFrom: "docs/ROLE_COPILOT_EXPANSION_PLAN.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Supervised writes", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "field-manager-copilot", name: "Field manager copilot", purpose: "County priorities, volunteer needs, field notes.", currentStatus: "idea", trigger: "County/field routes", inputs: "county", outputs: "priorities", readsFrom: "docs/ROLE_COPILOT_EXPANSION_PLAN.md", writesTo: "—", humanApprovalRequired: false, riskLevel: "medium", guardrails: "No voter file export", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "countyWorkbench bridge", testChecklist: [] }),
  c({ id: "social-media-copilot", name: "Social media copilot", purpose: "Content calendar, post drafts, approval queue.", currentStatus: "idea", trigger: "Owned media", inputs: "campaign context", outputs: "drafts", readsFrom: "docs/ROLE_COPILOT_EXPANSION_PLAN.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-publish", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Sprint 12 comms", testChecklist: [] }),
  c({ id: "communications-lead-copilot", name: "Communications lead copilot", purpose: "Outreach, hosts, coalition, email lanes.", currentStatus: "idea", trigger: "Comms workbench", inputs: "relationship graph", outputs: "outreach plan", readsFrom: "docs/ROLE_COPILOT_EXPANSION_PLAN.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "EMAIL_SEND_ENABLED", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "Sprint 12", testChecklist: [] }),
  // Tool-builder intelligence
  c({ id: "ai-tool-gap-detector", name: "AI tool gap detector", purpose: "Detect repeated friction → missing tool.", currentStatus: "partial", trigger: "Observations rollup", inputs: "observations", outputs: "gaps[]", readsFrom: "src/lib/agents/campaign-intelligence/campaign-gap-analyzer.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Propose only", deterministicHelperPath: "src/lib/agents/campaign-intelligence/campaign-gap-analyzer.ts", routesUsingTool: ["/admin/ai-command-center"], observationEvents: [], futureAutomationPath: "docs/AI_TOOL_BUILDER_INTELLIGENCE_ROADMAP.md", testChecklist: [] }),
  c({ id: "tool-contract-drafter", name: "Tool contract drafter", purpose: "Draft tool-contract.ts entries from spec.", currentStatus: "idea", trigger: "Gap approved", inputs: "spec", outputs: "CampaignAiToolContract draft", readsFrom: "ai-tools/tool-contract.ts", writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "No auto-commit", deterministicHelperPath: "—", routesUsingTool: ["/admin/campaign-events/ai-tools"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-to-tool-spec-converter", name: "Workflow to tool spec converter", purpose: "Convert workflow pain to tool spec.", currentStatus: "idea", trigger: "OS control loop", inputs: "workflow", outputs: "ToolSpec", readsFrom: "src/lib/agents/os-control/", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: ["/admin/ai-command-center"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-build-ticket-generator", name: "Tool build ticket generator", purpose: "Human-reviewed backlog ticket.", currentStatus: "idea", trigger: "Spec ready", inputs: "ToolSpec", outputs: "BuildTicket markdown", readsFrom: "docs/AI_TOOL_BUILDER_INTELLIGENCE_ROADMAP.md", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Cursor prompt only", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-test-plan-generator", name: "Tool test plan generator", purpose: "npm script + checklist for new tool.", currentStatus: "idea", trigger: "Ticket created", inputs: "tool id", outputs: "test plan", readsFrom: "scripts/", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "tool-risk-reviewer", name: "Tool risk reviewer", purpose: "Score risk before catalog merge.", currentStatus: "idea", trigger: "Contract draft", inputs: "contract", outputs: "riskLevel", readsFrom: "CAMPAIGN_AI_HUMAN_CONTROL_RULES", writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Blocks high-risk auto", deterministicHelperPath: "ai-tools/tool-contract.ts", routesUsingTool: ["/admin/campaign-events/ai-tools"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  // Dashboard modules
  c({ id: "dashboard-module-recommender", name: "Dashboard module recommender", purpose: "Suggest modules from role/task.", currentStatus: "partial", trigger: "Dashboard builder", inputs: "request", outputs: "block ids", readsFrom: "src/lib/agents/dashboard-builder/dashboard-blueprint-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Registry only", deterministicHelperPath: "src/lib/agents/dashboard-builder/dashboard-blueprint-builder.ts", routesUsingTool: ["/admin/ai-command-center/dashboard-builder"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-module-unlock-manager", name: "Dashboard module unlock manager", purpose: "Persist unlocked modules per user.", currentStatus: "idea", trigger: "Training complete", inputs: "userId", outputs: "unlocks", readsFrom: "docs/DASHBOARD_MODULE_SYSTEM.md", writesTo: "localStorage", humanApprovalRequired: true, riskLevel: "medium", guardrails: "", deterministicHelperPath: "—", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "dashboard-complexity-scorer", name: "Dashboard complexity scorer", purpose: "Score cognitive load of layout.", currentStatus: "partial", trigger: "Blueprint build", inputs: "blocks", outputs: "score", readsFrom: "src/lib/dashboard-orchestration/cognitive-load-analyzer.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/dashboard-orchestration/cognitive-load-analyzer.ts", routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "simple-mode-dashboard-builder", name: "Simple mode dashboard builder", purpose: "≤4 blocks for new users.", currentStatus: "partial", trigger: "skill=new", inputs: "request", outputs: "blueprint", readsFrom: "src/lib/agents/dashboard-builder/dashboard-layout-planner.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/dashboard-builder/dashboard-layout-planner.ts", routesUsingTool: ["/admin/ai-command-center/dashboard-builder"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "advanced-mode-dashboard-builder", name: "Advanced mode dashboard builder", purpose: "Full registry for operators.", currentStatus: "partial", trigger: "skill=expert", inputs: "request", outputs: "blueprint", readsFrom: "src/lib/agents/dashboard-builder/dashboard-blueprint-builder.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Safety guard", deterministicHelperPath: "src/lib/agents/dashboard-builder/dashboard-safety-guard.ts", routesUsingTool: ["/admin/ai-command-center/dashboard-builder"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_KELLY_OS_PLANNING_TOOL_CONTRACTS = TOOLS;
export const SPRINT_KELLY_OS_PLANNING_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
