import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 1;

function c(lifecycle: string, partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle, version: "v1", priority: "P0", ...partial };
}

const USER_INTEL: CampaignAiToolContract[] = [
  c("agent_user_intelligence", {
    id: "user-intent-profiler",
    name: "User intent profiler",
    purpose: "Infer intent from pathname, role, and recent UX observations.",
    currentStatus: "partial",
    trigger: "Page load",
    inputs: "role, pathname, observations",
    outputs: "intent label + confidence",
    readsFrom: "user-personas.ts, user-observations.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Internal only; no external profiling",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-personas.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: ["page_viewed"],
    futureAutomationPath: "LLM intent classify with human review",
    testChecklist: ["inferRoleFromPath works"],
  }),
  c("agent_user_intelligence", {
    id: "role-needs-anticipator",
    name: "Role needs anticipator",
    purpose: "Map persona goals to likely next needs on this surface.",
    currentStatus: "functional",
    trigger: "Dashboard render",
    inputs: "CampaignUserRole",
    outputs: "needs[]",
    readsFrom: "user-personas.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No voter manipulation",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-personas.ts",
    routesUsingTool: ["/admin/candidate-dashboard", "/admin/campaign-manager-dashboard"],
    observationEvents: [],
    futureAutomationPath: "Learn from observation miners",
    testChecklist: ["Candidate persona has goals"],
  }),
  c("agent_user_intelligence", {
    id: "behavior-pattern-observer",
    name: "Behavior pattern observer",
    purpose: "Record internal UX observations (clicks, filters, abandoned flows).",
    currentStatus: "partial",
    trigger: "Operator action",
    inputs: "UserUxObservationEvent",
    outputs: "UserObservationEntry",
    readsFrom: "user-observations.ts",
    writesTo: "data/campaign-events/user-observations.json",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No hidden external tracking",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-observations.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: ["dashboard_card_clicked", "abandoned_flow"],
    futureAutomationPath: "Pattern miner batch job",
    testChecklist: ["JSON append works"],
  }),
  c("agent_user_intelligence", {
    id: "next-action-recommender",
    name: "Next action recommender",
    purpose: "Deterministic top action + calm secondary options.",
    currentStatus: "functional",
    trigger: "AgentNextActionPanel",
    inputs: "NextActionEngineInput",
    outputs: "NextActionResult",
    readsFrom: "next-action-engine.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Suggest only; operator clicks",
    deterministicHelperPath: "src/lib/agents/user-intelligence/next-action-engine.ts",
    routesUsingTool: ["/admin/candidate-dashboard", "/admin/campaign-manager-dashboard", "/admin/ai-command-center"],
    observationEvents: ["suggestion_accepted", "suggestion_rejected"],
    futureAutomationPath: "Rank by acceptance rate",
    testChecklist: ["buildNextActions returns primary"],
  }),
  c("agent_user_intelligence", {
    id: "workflow-abandonment-detector",
    name: "Workflow abandonment detector",
    purpose: "Flag started-but-not-finished review/promotion flows.",
    currentStatus: "scaffolded",
    trigger: "abandoned_flow observation",
    inputs: "observation log",
    outputs: "warning",
    readsFrom: "user-observations.json",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Internal",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-observations.ts",
    routesUsingTool: ["/admin/campaign-events/review"],
    observationEvents: ["abandoned_flow", "review_queue_started"],
    futureAutomationPath: "Session timeout heuristics",
    testChecklist: ["Event types defined"],
  }),
];

const WRITING: CampaignAiToolContract[] = [
  c("agent_writing", {
    id: "writing-voice-profile-builder",
    name: "Writing voice profile builder",
    purpose: "Maintain campaign writing profile (tone, themes, avoid list).",
    currentStatus: "functional",
    trigger: "Writing assist",
    inputs: "WritingProfile partial",
    outputs: "WritingProfile",
    readsFrom: "writing-profile.ts",
    writesTo: "data/campaign-events/writing-style-observations.json",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Explicit notes only; no bulk scrape",
    deterministicHelperPath: "src/lib/agents/writing-agent/writing-profile.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Learn from accepted edits",
    testChecklist: ["DEFAULT_WRITING_PROFILE"],
  }),
  c("agent_writing", {
    id: "user-voice-profile-builder",
    name: "User voice profile builder",
    purpose: "Alias scaffold for per-user voice (operator vs candidate).",
    currentStatus: "scaffolded",
    trigger: "Profile edit",
    inputs: "user id, notes",
    outputs: "profile slice",
    readsFrom: "writing-profile.ts",
    writesTo: "writing-style-observations.json",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "No autonomous posts",
    deterministicHelperPath: "src/lib/agents/writing-agent/writing-profile.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Per-role profiles",
    testChecklist: [],
  }),
  c("agent_writing", {
    id: "campaign-voice-style-matcher",
    name: "Campaign voice style matcher",
    purpose: "Match draft copy to campaign themes and audience.",
    currentStatus: "partial",
    trigger: "Copy draft",
    inputs: "text, WritingAudience",
    outputs: "WritingSuggestion",
    readsFrom: "writing-suggestion-builder.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Human approves send",
    deterministicHelperPath: "src/lib/agents/writing-agent/writing-suggestion-builder.ts",
    routesUsingTool: ["/admin/campaign-events/approval-package"],
    observationEvents: ["suggestion_accepted", "suggestion_rejected"],
    futureAutomationPath: "LLM optional layer",
    testChecklist: ["buildWritingSuggestion"],
  }),
  c("agent_writing", {
    id: "email-tone-adapter",
    name: "Email tone adapter",
    purpose: "Adjust approval email tone for candidate audience.",
    currentStatus: "partial",
    trigger: "Approval email assist",
    inputs: "subject, body",
    outputs: "toned copy",
    readsFrom: "approval-email-assist, writing-suggestion-builder",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "EMAIL_SEND_ENABLED gate",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/approval-email-assist.ts",
    routesUsingTool: ["/admin/campaign-calendar/approval-package"],
    observationEvents: ["approval_email_generated"],
    futureAutomationPath: "Accepted edit learning",
    testChecklist: [],
  }),
  c("agent_writing", {
    id: "approval-package-copy-improver",
    name: "Approval package copy improver",
    purpose: "Plain-language approval package summaries.",
    currentStatus: "partial",
    trigger: "Package build",
    inputs: "WorkbenchEventRow",
    outputs: "copy improvements",
    readsFrom: "approval-package.ts, buildWritingSuggestion",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "No auto-send",
    deterministicHelperPath: "src/lib/campaign-events/approval-package.ts",
    routesUsingTool: ["/admin/campaign-calendar/approval-package"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_writing", {
    id: "plain-language-simplifier",
    name: "Plain language simplifier",
    purpose: "Shorten jargon for candidate/public audiences.",
    currentStatus: "functional",
    trigger: "Writing assist",
    inputs: "text",
    outputs: "simplified text",
    readsFrom: "writing-suggestion-builder.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "No policy claims",
    deterministicHelperPath: "src/lib/agents/writing-agent/writing-suggestion-builder.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: ["Strips AI label"],
  }),
  c("agent_writing", {
    id: "non-overwhelming-copy-compressor",
    name: "Non-overwhelming copy compressor",
    purpose: "Compress long operator copy to calm bullets.",
    currentStatus: "partial",
    trigger: "Dashboard copy",
    inputs: "long text",
    outputs: "short text",
    readsFrom: "writing-suggestion-builder.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Max 2 sentences default",
    deterministicHelperPath: "src/lib/agents/writing-agent/writing-suggestion-builder.ts",
    routesUsingTool: ["/admin/candidate-dashboard"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_writing", {
    id: "host-copy-coach",
    name: "Host copy coach",
    purpose: "Host-facing tone for outreach templates.",
    currentStatus: "scaffolded",
    trigger: "Host comms",
    inputs: "draft",
    outputs: "host-toned draft",
    readsFrom: "writing-profile audienceOverrides.host",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Human sends",
    deterministicHelperPath: "src/lib/agents/writing-agent/writing-profile.ts",
    routesUsingTool: [],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_writing", {
    id: "candidate-briefing-writer",
    name: "Candidate briefing writer",
    purpose: "One-page candidate prep brief scaffold.",
    currentStatus: "idea",
    trigger: "Pre-event",
    inputs: "factCard",
    outputs: "brief markdown",
    readsFrom: "factCard",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "No auto-send",
    deterministicHelperPath: "cb-prep-brief catalog",
    routesUsingTool: ["/admin/candidate-dashboard"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
];

const UX: CampaignAiToolContract[] = [
  c("agent_ux_intelligence", {
    id: "microcopy-generator",
    name: "Microcopy generator",
    purpose: "Registry of tooltips and plain-English definitions.",
    currentStatus: "functional",
    trigger: "getMicrocopy()",
    inputs: "MicrocopyTerm, role?",
    outputs: "MicrocopyEntry",
    readsFrom: "microcopy-registry.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Factual only",
    deterministicHelperPath: "src/lib/agents/ux-intelligence/microcopy-registry.ts",
    routesUsingTool: ["/admin/campaign-events/month-readiness", "/admin/campaign-events/calendar-sync", "/admin/campaign-events/reimbursement"],
    observationEvents: ["help_hover_opened"],
    futureAutomationPath: "CMS for microcopy",
    testChecklist: ["getMicrocopy('sync_stale')"],
  }),
  c("agent_ux_intelligence", {
    id: "hover-help-router",
    name: "Hover help router",
    purpose: "Route term + role to microcopy for tooltips.",
    currentStatus: "functional",
    trigger: "MicrocopyHint hover",
    inputs: "term, role",
    outputs: "tooltip text",
    readsFrom: "microcopy-registry.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/agents/ux-intelligence/microcopy-registry.ts",
    routesUsingTool: ["/admin/campaign-events/month-readiness"],
    observationEvents: ["help_hover_opened"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_ux_intelligence", {
    id: "user-friction-detector",
    name: "User friction detector",
    purpose: "Detect high-friction patterns (repeated missing fields, abandoned flows).",
    currentStatus: "partial",
    trigger: "Observations + readiness",
    inputs: "observations, snapshot",
    outputs: "friction report",
    readsFrom: "user-observations, load-campaign-events-dashboard",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-observations.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: ["repeated_missing_field", "abandoned_flow"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_ux_intelligence", {
    id: "dashboard-overwhelm-detector",
    name: "Dashboard overwhelm detector",
    purpose: "Warn when too many stat cards/queues shown for persona density.",
    currentStatus: "partial",
    trigger: "Dashboard render",
    inputs: "role, card count",
    outputs: "overwhelm warning",
    readsFrom: "user-personas doNotOverwhelmRules",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Suggest collapse",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-personas.ts",
    routesUsingTool: ["/admin/candidate-dashboard"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_ux_intelligence", {
    id: "progressive-disclosure-advisor",
    name: "Progressive disclosure advisor",
    purpose: "Recommend what to hide behind 'show more'.",
    currentStatus: "scaffolded",
    trigger: "AgentNextActionPanel",
    inputs: "persona, section list",
    outputs: "disclosure plan",
    readsFrom: "user-personas",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-personas.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: ["user_collapsed_section", "user_expanded_section"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_ux_intelligence", {
    id: "role-based-dashboard-ranker",
    name: "Role-based dashboard ranker",
    purpose: "Rank dashboard sections by persona likelyDashboards.",
    currentStatus: "partial",
    trigger: "Dashboard build",
    inputs: "role",
    outputs: "ordered sections",
    readsFrom: "user-personas",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/agents/user-intelligence/user-personas.ts",
    routesUsingTool: ["/admin/campaign-manager-dashboard"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_ux_intelligence", {
    id: "new-user-onboarding-guide",
    name: "New user onboarding guide",
    purpose: "First-run path for new_admin_user persona.",
    currentStatus: "functional",
    trigger: "new_admin_user role",
    inputs: "period",
    outputs: "onboarding steps",
    readsFrom: "next-action-engine",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/agents/user-intelligence/next-action-engine.ts",
    routesUsingTool: ["/admin/ai-command-center", "/admin/campaign-manager-dashboard"],
    observationEvents: ["page_viewed"],
    futureAutomationPath: "",
    testChecklist: ["new user primary action"],
  }),
  c("agent_ux_intelligence", {
    id: "public-intake-friction-scanner",
    name: "Public intake friction scanner",
    purpose: "Flag website intake missing fields and duplicate risk.",
    currentStatus: "functional",
    trigger: "Intake bridge",
    inputs: "intake meta",
    outputs: "friction warnings",
    readsFrom: "intake-duplicate-conflict",
    writesTo: "_intake",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/campaign-events/intake-duplicate-conflict.ts",
    routesUsingTool: ["/admin/campaign-events/workbench"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_ux_intelligence", {
    id: "approval-pathway-optimizer",
    name: "Approval pathway optimizer",
    purpose: "Suggest shortest path from tentative to approved.",
    currentStatus: "partial",
    trigger: "Review queue",
    inputs: "pending count",
    outputs: "path steps",
    readsFrom: "approval workflow docs",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "No auto-approve",
    deterministicHelperPath: "src/lib/campaign-events/approval-package.ts",
    routesUsingTool: ["/admin/campaign-events/review"],
    observationEvents: ["approval_decision_made"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
];

const CAMPAIGN_INTEL: CampaignAiToolContract[] = [
  c("agent_campaign_intelligence", {
    id: "campaign-gap-analyzer",
    name: "Campaign gap analyzer",
    purpose: "Highest-impact ops/build gap from snapshot + registry.",
    currentStatus: "functional",
    trigger: "AI command center",
    inputs: "snapshot, readinessScore",
    outputs: "CampaignGapAnalysis",
    readsFrom: "campaign-gap-analyzer.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Recommendations only",
    deterministicHelperPath: "src/lib/agents/campaign-intelligence/campaign-gap-analyzer.ts",
    routesUsingTool: ["/admin/ai-command-center", "/admin/campaign-manager-dashboard"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "",
    testChecklist: ["analyzeCampaignGaps"],
  }),
  c("agent_campaign_intelligence", {
    id: "readiness-risk-scorer",
    name: "Readiness risk scorer",
    purpose: "Translate month readiness % into risk tier.",
    currentStatus: "functional",
    trigger: "Month readiness",
    inputs: "readiness score",
    outputs: "risk tier",
    readsFrom: "month-readiness-score.ts",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/campaign-events/month-readiness/month-readiness-score.ts",
    routesUsingTool: ["/admin/campaign-events/month-readiness"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_campaign_intelligence", {
    id: "operational-bottleneck-detector",
    name: "Operational bottleneck detector",
    purpose: "Find top blocker queue for CM.",
    currentStatus: "partial",
    trigger: "CM dashboard",
    inputs: "snapshot",
    outputs: "bottleneck",
    readsFrom: "workflow-bottleneck-detector overlap",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/agents/campaign-intelligence/campaign-gap-analyzer.ts",
    routesUsingTool: ["/admin/campaign-manager-dashboard"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_campaign_intelligence", {
    id: "volunteer-growth-opportunity-detector",
    name: "Volunteer growth opportunity detector",
    purpose: "Scaffold volunteer staffing opportunities from events.",
    currentStatus: "idea",
    trigger: "Event OS",
    inputs: "events",
    outputs: "opportunities",
    readsFrom: "volunteer-capacity-tool kelly-agent",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "No auto outreach",
    deterministicHelperPath: "src/lib/kelly-agent/tools/volunteer-capacity-tool.ts",
    routesUsingTool: [],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_campaign_intelligence", {
    id: "host-event-growth-suggester",
    name: "Host event growth suggester",
    purpose: "Suggest house meet & greets needing host info.",
    currentStatus: "partial",
    trigger: "Workbench",
    inputs: "missing host",
    outputs: "suggestions",
    readsFrom: "merge-persisted-row host gaps",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/campaign-events/calendar-event-flags.ts",
    routesUsingTool: ["/admin/campaign-events/workbench"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_campaign_intelligence", {
    id: "county-opportunity-scorer",
    name: "County opportunity scorer",
    purpose: "Score county-linked events for outreach priority.",
    currentStatus: "scaffolded",
    trigger: "County present on row",
    inputs: "county label",
    outputs: "score",
    readsFrom: "county-political-profile",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Demo data labeled",
    deterministicHelperPath: "src/lib/campaign-engine/county-political-profile.ts",
    routesUsingTool: [],
    observationEvents: [],
    futureAutomationPath: "countyWorkbench adapter",
    testChecklist: [],
  }),
];

const SYSTEM_INTEL: CampaignAiToolContract[] = [
  c("agent_system_intelligence", {
    id: "master-agent-router",
    name: "Master agent router",
    purpose: "Route to domain toolchains (alias of global-agent-router).",
    currentStatus: "partial",
    trigger: "Command center",
    inputs: "intent",
    outputs: "domain",
    readsFrom: "master-tool-registry",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/agents/master-tool-registry/index.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_system_intelligence", {
    id: "tool-selection-planner",
    name: "Tool selection planner",
    purpose: "Pick catalog tools for a given ops task.",
    currentStatus: "scaffolded",
    trigger: "AI builder",
    inputs: "task description",
    outputs: "tool id list",
    readsFrom: "ai-tools-master-catalog",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools-command-center.ts",
    routesUsingTool: ["/admin/campaign-events/ai-tools"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_system_intelligence", {
    id: "workflow-observation-miner",
    name: "Workflow observation miner",
    purpose: "Mine UX + AI observations for patterns.",
    currentStatus: "idea",
    trigger: "Weekly",
    inputs: "observation logs",
    outputs: "pattern report",
    readsFrom: "observation-pattern-miner",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "docs/campaign-events/AI_AGENT_OBSERVATION_AND_LEARNING_ROADMAP.md",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_system_intelligence", {
    id: "automation-readiness-scorer",
    name: "Automation readiness scorer",
    purpose: "Score which tools are safe to automate later.",
    currentStatus: "partial",
    trigger: "Registry audit",
    inputs: "tool catalog",
    outputs: "readiness score",
    readsFrom: "master-tool-registry",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "medium",
    guardrails: "Default human_gated",
    deterministicHelperPath: "src/lib/agents/master-tool-registry/index.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_system_intelligence", {
    id: "market-polish-prioritizer",
    name: "Market polish prioritizer",
    purpose: "Prioritize demo vs prod polish gaps.",
    currentStatus: "scaffolded",
    trigger: "Release review",
    inputs: "usability docs",
    outputs: "priority list",
    readsFrom: "market-polish-gap-detector",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "",
    deterministicHelperPath: "docs/campaign-events/CAMPAIGN_OS_USABILITY_PASS.md",
    routesUsingTool: [],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
  c("agent_system_intelligence", {
    id: "production-risk-forecaster",
    name: "Production risk forecaster",
    purpose: "Forecast live-write/send risks from env gates.",
    currentStatus: "partial",
    trigger: "Launch",
    inputs: "env",
    outputs: "risk forecast",
    readsFrom: "production-risk-scorer",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "high",
    guardrails: "Never auto-enable writes",
    deterministicHelperPath: "src/lib/agents/user-intelligence/next-action-engine.ts",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "",
    testChecklist: [],
  }),
];

export const AGENT_INTELLIGENCE_TOOL_CONTRACTS: CampaignAiToolContract[] = [
  ...USER_INTEL,
  ...WRITING,
  ...UX,
  ...CAMPAIGN_INTEL,
  ...SYSTEM_INTEL,
];

function toCatalog(contracts: CampaignAiToolContract[]): AiToolEntry[] {
  return contracts.map(contractToCatalogEntry);
}

export const AGENT_USER_INTELLIGENCE_CATALOG = toCatalog(USER_INTEL);
export const AGENT_WRITING_CATALOG = toCatalog(WRITING);
export const AGENT_UX_CATALOG = toCatalog(UX);
export const AGENT_CAMPAIGN_INTELLIGENCE_CATALOG = toCatalog(CAMPAIGN_INTEL);
export const AGENT_SYSTEM_INTELLIGENCE_CATALOG = toCatalog(SYSTEM_INTEL);

export const AGENT_INTELLIGENCE_ALL_CATALOG_ENTRIES: AiToolEntry[] = toCatalog(AGENT_INTELLIGENCE_TOOL_CONTRACTS);
