import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 10;
const L = "campaign_intelligence_sprint10" as const;
const STRAT = "src/lib/agents/campaign-intelligence/strategic-intelligence-engine.ts";
const LEARN = "src/lib/agents/campaign-intelligence/campaign-learning-loop-engine.ts";
const FIN = "src/lib/agents/campaign-intelligence/finance-intelligence-v2.ts";
const OPS = "src/lib/agents/campaign-intelligence/operator-intelligence-v2.ts";
const UNI = "src/lib/agents/campaign-intelligence/unified-campaign-context-assembler.ts";
const MEM = "src/lib/agents/campaign-intelligence/campaign-memory-synthesizer.ts";
const PSY = "src/lib/agents/campaign-intelligence/agent-psychology-intelligence.ts";
const TEN = "src/lib/campaign-tenancy/";
const ROUTE = ["/admin/ai-command-center", "/admin/campaign-onboarding", "/admin/campaign-portals"] as const;

export const OBS_SPRINT10 = [
  "campaign_momentum_changed",
  "candidate_overload_detected",
  "workflow_prediction_triggered",
  "operator_fatigue_detected",
  "strategic_gap_detected",
  "county_under_engaged",
  "event_success_pattern_detected",
  "campaign_energy_shift_detected",
  "resource_inefficiency_detected",
  "coalition_growth_detected",
  "executive_briefing_generated",
] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v1", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "campaign-strategy-gap-detector", name: "Campaign strategy gap detector", purpose: "Detect strategic gaps from snapshot + tenant goals.", currentStatus: "functional", trigger: "Unified context", inputs: "snapshot, settings", outputs: "strategicGaps", readsFrom: STRAT, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Advisory", deterministicHelperPath: STRAT, routesUsingTool: [...ROUTE], observationEvents: ["strategic_gap_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-momentum-analyzer", name: "Campaign momentum analyzer", purpose: "Score campaign momentum 0-100.", currentStatus: "functional", trigger: "Command center V3", inputs: "snapshot", outputs: "momentumScore", readsFrom: STRAT, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: STRAT, routesUsingTool: [...ROUTE], observationEvents: ["campaign_momentum_changed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-bandwidth-analyzer", name: "Candidate bandwidth analyzer", purpose: "Detect candidate overload from event density.", currentStatus: "functional", trigger: "Strategic engine", inputs: "snapshot", outputs: "candidateOverloadRisk", readsFrom: STRAT, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: STRAT, routesUsingTool: [...ROUTE], observationEvents: ["candidate_overload_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "schedule-sustainability-analyzer", name: "Schedule sustainability analyzer", purpose: "Assess schedule sustainable/strained/overloaded.", currentStatus: "functional", trigger: "Strategic engine", inputs: "event counts", outputs: "scheduleSustainability", readsFrom: STRAT, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: STRAT, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-priority-engine", name: "County priority engine", purpose: "Flag county engagement gaps.", currentStatus: "functional", trigger: "Strategic engine", inputs: "missingCounty", outputs: "countyEngagementGaps", readsFrom: STRAT, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: STRAT, routesUsingTool: [...ROUTE], observationEvents: ["county_under_engaged"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "field-intensity-scorer", name: "Field intensity scorer", purpose: "Recommend field intensity from intake + events.", currentStatus: "partial", trigger: "Strategic opportunities", inputs: "snapshot", outputs: "field signals", readsFrom: STRAT, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: STRAT, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "persuasion-opportunity-detector", name: "Persuasion opportunity detector", purpose: "Surface persuasion indicators from learning loop.", currentStatus: "functional", trigger: "Learning V2", inputs: "county memory", outputs: "persuasionIndicators", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No opponent claims", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "coalition-growth-analyzer", name: "Coalition growth analyzer", purpose: "Intake + coalition indicators.", currentStatus: "functional", trigger: "Learning V2", inputs: "intake queue", outputs: "coalitionIndicators", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: ["coalition_growth_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "volunteer-energy-monitor", name: "Volunteer energy monitor", purpose: "Volunteer reliability notes scaffold.", currentStatus: "partial", trigger: "Learning V2", inputs: "—", outputs: "volunteerReliabilityNotes", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "Volunteer CRM", testChecklist: [] }),
  c({ id: "earned-media-opportunity-detector", name: "Earned media opportunity detector", purpose: "Link successful events to media follow-up.", currentStatus: "partial", trigger: "Blueprints", inputs: "learning", outputs: "media opportunities", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-success-pattern-detector", name: "Event success pattern detector", purpose: "Detect patterns from blueprint library.", currentStatus: "functional", trigger: "Learning loop", inputs: "blueprints", outputs: "eventPatterns", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: ["event_success_pattern_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "supporter-recurrence-detector", name: "Supporter recurrence detector", purpose: "Recurring supporter signals from blueprints.", currentStatus: "partial", trigger: "Learning V2", inputs: "—", outputs: "recurringSupporterSignals", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "organizer-effectiveness-analyzer", name: "Organizer effectiveness analyzer", purpose: "Hot wash / media quality notes.", currentStatus: "partial", trigger: "Learning V2", inputs: "signals", outputs: "organizer notes", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-learning-loop-engine", name: "Campaign learning loop engine", purpose: "V2 learning intelligence bundle.", currentStatus: "functional", trigger: "Hot wash complete", inputs: "learning snapshot", outputs: "LearningIntelligenceV2", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: ["campaign_energy_shift_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "turnout-quality-estimator", name: "Turnout quality estimator", purpose: "Estimate turnout quality from blueprints.", currentStatus: "partial", trigger: "Learning V2", inputs: "blueprint count", outputs: "turnoutQuality", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "followup-opportunity-detector", name: "Follow-up opportunity detector", purpose: "Recommend post-event follow-ups.", currentStatus: "functional", trigger: "Learning V2", inputs: "—", outputs: "followUpRecommendations", readsFrom: LEARN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: LEARN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-energy-cycle-detector", name: "Campaign energy cycle detector", purpose: "Detect energy shifts from observations.", currentStatus: "functional", trigger: "Memory synthesizer", inputs: "observations", outputs: "instinct line", readsFrom: MEM, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: MEM, routesUsingTool: [...ROUTE], observationEvents: ["campaign_energy_shift_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-resource-efficiency-engine", name: "Campaign resource efficiency engine", purpose: "Score finance resource efficiency.", currentStatus: "functional", trigger: "Finance V2", inputs: "finance snapshot", outputs: "resourceEfficiencyScore", readsFrom: FIN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: FIN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "travel-efficiency-analyzer", name: "Travel efficiency analyzer", purpose: "Travel efficiency notes.", currentStatus: "functional", trigger: "Finance V2", inputs: "mileage gaps", outputs: "travelEfficiencyNotes", readsFrom: FIN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: FIN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "event-roi-estimator", name: "Event ROI estimator", purpose: "County spend / event ROI notes.", currentStatus: "partial", trigger: "Finance V2", inputs: "county spend", outputs: "eventRoiNotes", readsFrom: FIN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: FIN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-investment-analyzer", name: "County investment analyzer", purpose: "County investment notes.", currentStatus: "functional", trigger: "Finance V2", inputs: "countySpendNotes", outputs: "countyInvestmentNotes", readsFrom: FIN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: FIN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "budget-pacing-engine", name: "Budget pacing engine", purpose: "Budget pacing under/on/over.", currentStatus: "partial", trigger: "Finance V2", inputs: "efficiency score", outputs: "budgetPacing", readsFrom: FIN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: FIN, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "BUDGET-2", testChecklist: [] }),
  c({ id: "operational-waste-detector", name: "Operational waste detector", purpose: "Flag finance/travel waste.", currentStatus: "functional", trigger: "Finance V2", inputs: "exceptions", outputs: "operationalWasteFlags", readsFrom: FIN, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: FIN, routesUsingTool: [...ROUTE], observationEvents: ["resource_inefficiency_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-fatigue-detector", name: "Operator fatigue detector", purpose: "Detect operator fatigue from cognitive load.", currentStatus: "functional", trigger: "Operator V2", inputs: "observations", outputs: "fatigueDetected", readsFrom: OPS, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: OPS, routesUsingTool: [...ROUTE], observationEvents: ["operator_fatigue_detected"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "operator-specialization-learner", name: "Operator specialization learner", purpose: "Infer treasurer vs approval operator lean.", currentStatus: "functional", trigger: "Operator V2", inputs: "pathname obs", outputs: "specializationHint", readsFrom: OPS, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "No profiling PII", deterministicHelperPath: OPS, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "workflow-prediction-engine", name: "Workflow prediction engine", purpose: "Predict next workflows.", currentStatus: "functional", trigger: "Operator V2", inputs: "router", outputs: "predictedWorkflows", readsFrom: OPS, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: OPS, routesUsingTool: [...ROUTE], observationEvents: ["workflow_prediction_triggered"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "adaptive-explanation-engine", name: "Adaptive explanation engine", purpose: "Executive vs detailed explanation depth.", currentStatus: "functional", trigger: "Psychology + load", inputs: "cognitive load", outputs: "explanationDepth", readsFrom: OPS, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: OPS, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "executive-briefing-builder", name: "Executive briefing builder", purpose: "Short executive briefing string.", currentStatus: "functional", trigger: "Command center", inputs: "strategic + operator", outputs: "executiveBriefing", readsFrom: OPS, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: OPS, routesUsingTool: [...ROUTE], observationEvents: ["executive_briefing_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "daily-strategic-briefing-generator", name: "Daily strategic briefing generator", purpose: "Markdown daily briefing.", currentStatus: "functional", trigger: "Command center V3", inputs: "routes + narrative", outputs: "dailyStrategicBriefing", readsFrom: OPS, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: OPS, routesUsingTool: [...ROUTE], observationEvents: ["executive_briefing_generated"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "context-depth-router", name: "Context depth router", purpose: "Route explanation depth by fatigue.", currentStatus: "functional", trigger: "Operator V2", inputs: "fatigue", outputs: "explanationDepth", readsFrom: OPS, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: OPS, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "confidence-aware-guidance-engine", name: "Confidence-aware guidance engine", purpose: "Adjust guidance from psychology confidence.", currentStatus: "functional", trigger: "Psychology", inputs: "confidenceLevel", outputs: "uxAdjustments", readsFrom: PSY, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: PSY, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "unified-campaign-context-assembler", name: "Unified campaign context assembler", purpose: "Synthesize all domains into one context.", currentStatus: "functional", trigger: "Command center V3 load", inputs: "tenant, period", outputs: "UnifiedCampaignContext", readsFrom: UNI, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Read-only", deterministicHelperPath: UNI, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-memory-synthesizer", name: "Campaign memory synthesizer", purpose: "Merge operator/county/strategic/workflow memory lines.", currentStatus: "functional", trigger: "Unified context", inputs: "observations", outputs: "CampaignMemorySynthesis", readsFrom: MEM, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "Human review queue", deterministicHelperPath: MEM, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-style-memory-engine", name: "Candidate style memory engine", purpose: "Candidate bandwidth + style line.", currentStatus: "functional", trigger: "Memory synthesizer", inputs: "strategic", outputs: "candidateStyleLine", readsFrom: MEM, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: MEM, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-operating-instinct-builder", name: "Campaign operating instinct builder", purpose: "Instinct line from pacing + schedule.", currentStatus: "functional", trigger: "Memory synthesizer", inputs: "strategic + learning", outputs: "campaignInstinctLine", readsFrom: MEM, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: MEM, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "strategic-priority-ranker", name: "Strategic priority ranker", purpose: "Rank recommended campaign moves.", currentStatus: "functional", trigger: "Unified context", inputs: "routes + gaps", outputs: "recommendedCampaignMoves", readsFrom: UNI, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: UNI, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-health-intelligence-engine", name: "Campaign health intelligence engine", purpose: "Campaign readiness index 0-100.", currentStatus: "functional", trigger: "Command center V3", inputs: "domain scores", outputs: "campaignReadinessIndex", readsFrom: UNI, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: UNI, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "all-domain-situation-summarizer", name: "All-domain situation summarizer", purpose: "Plain-language situation summary.", currentStatus: "functional", trigger: "Unified context", inputs: "all domains", outputs: "situationSummary", readsFrom: UNI, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: UNI, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "campaign-tenant-context-resolver", name: "Campaign tenant context resolver", purpose: "Resolve active tenant from cookie + memberships.", currentStatus: "functional", trigger: "Admin load", inputs: "cookie", outputs: "tenant context", readsFrom: `${TEN}resolve-active-tenant.ts`, writesTo: "cookie", humanApprovalRequired: false, riskLevel: "low", guardrails: "JSON + Prisma scaffold", deterministicHelperPath: `${TEN}resolve-active-tenant.ts`, routesUsingTool: [...ROUTE], observationEvents: [], futureAutomationPath: "Prisma primary", testChecklist: [] }),
  c({ id: "campaign-onboarding-wizard-engine", name: "Campaign onboarding wizard engine", purpose: "Create tenant from onboarding draft.", currentStatus: "functional", trigger: "Onboarding submit", inputs: "CampaignOnboardingDraft", outputs: "tenant id", readsFrom: `${TEN}campaign-tenant-store.ts`, writesTo: "tenants.json", humanApprovalRequired: true, riskLevel: "medium", guardrails: "Admin only", deterministicHelperPath: `${TEN}campaign-tenant-store.ts`, routesUsingTool: ["/admin/campaign-onboarding"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT10_CAMPAIGN_INTELLIGENCE_TOOL_CONTRACTS = TOOLS;
export const SPRINT10_CAMPAIGN_INTELLIGENCE_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
