import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const SPRINT = 12;
const L = "county_intelligence_bridge" as const;
const CI = "src/lib/agents/county-intelligence/";
const ROUTES = [
  "/admin/county-intelligence",
  "/admin/ai-command-center",
  "/admin/ai-command-center/copilots",
  "/admin/campaign-manager-dashboard",
  "/admin/candidate-dashboard",
  "/admin/campaign-events/workbench",
  "/admin/campaign-events/[recordId]",
  "/admin/counties/[slug]",
  "/admin/training",
] as const;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: L, version: "v2_future", priority: "P0", ...partial };
}

const TOOLS: CampaignAiToolContract[] = [
  c({ id: "county-action-package-builder", name: "County action package builder", purpose: "Build county_recovery/growth/event packages with tasks and routes.", currentStatus: "functional", trigger: "County command center", inputs: "slug, type", outputs: "CountyActionPackage", readsFrom: `${CI}county-action-package-builder.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Human executes outreach", deterministicHelperPath: `${CI}county-action-package-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: ["county_action_package_created"], futureAutomationPath: "", testChecklist: ["buildCountyActionPackage pulaski"] }),
  c({ id: "field-manager-county-plan-builder", name: "Field manager county plan builder", purpose: "Daily statewide field plan from weak counties and PO5 gaps.", currentStatus: "functional", trigger: "Field manager copilot", inputs: "—", outputs: "FieldManagerDailyCountyPlan", readsFrom: `${CI}county-copilot-applications.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-copilot-applications.ts`, routesUsingTool: [...ROUTES], observationEvents: ["county_priority_viewed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-lead-daily-plan-builder", name: "County lead daily plan builder", purpose: "County lead goals, weaknesses, outreach plan.", currentStatus: "functional", trigger: "County lead copilot", inputs: "slug?", outputs: "CountyCopilotApplication", readsFrom: `${CI}county-copilot-applications.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-copilot-applications.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "candidate-county-briefing-builder", name: "Candidate county briefing builder", purpose: "Talking/listening points before county events.", currentStatus: "functional", trigger: "Candidate copilot", inputs: "slug", outputs: "CountyIntelligenceSummary", readsFrom: `${CI}county-copilot-applications.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Fatigue protection", deterministicHelperPath: `${CI}county-copilot-applications.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-volunteer-gap-router", name: "County volunteer gap router", purpose: "Route volunteer coordinator to counties needing staff.", currentStatus: "functional", trigger: "Volunteer coordinator copilot", inputs: "statewide", outputs: "guidance[]", readsFrom: `${CI}county-copilot-applications.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "No auto-assign", deterministicHelperPath: `${CI}county-copilot-applications.ts`, routesUsingTool: ["/admin/volunteers", ...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-intern-task-builder", name: "County intern task builder", purpose: "Safe research and profile review tasks per county.", currentStatus: "functional", trigger: "Intern copilot", inputs: "slug?", outputs: "internTaskList", readsFrom: `${CI}county-action-package-builder.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "Supervisor review", deterministicHelperPath: `${CI}county-action-package-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-communications-angle-builder", name: "County communications angle builder", purpose: "County message angles and PO5 copy drafts.", currentStatus: "functional", trigger: "Communications copilot", inputs: "slug", outputs: "communicationsRecommendation", readsFrom: `${CI}county-action-package-builder.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "medium", guardrails: "EMAIL_SEND_ENABLED", deterministicHelperPath: `${CI}county-action-package-builder.ts`, routesUsingTool: ["/admin/communications", ...ROUTES], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-event-purpose-writer", name: "County event purpose writer", purpose: "Why county matters and event accomplishment goals.", currentStatus: "functional", trigger: "Event drilldown planning", inputs: "countyName", outputs: "EventCountyPlanningGuidance", readsFrom: `${CI}county-event-strategy.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-event-strategy.ts`, routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: ["county_event_recommendation_followed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-power-of-five-ask-builder", name: "County Power of 5 ask builder", purpose: "Event PO5 ask script from county gap.", currentStatus: "functional", trigger: "Event planning", inputs: "slug", outputs: "ask text", readsFrom: `${CI}power-of-five-engine.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}power-of-five-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: ["county_power_of_five_plan_created"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-followup-plan-builder", name: "County follow-up plan builder", purpose: "Post-event county follow-up from action package.", currentStatus: "functional", trigger: "Hot wash / post-event", inputs: "slug", outputs: "followUpPlan", readsFrom: `${CI}county-action-package-builder.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-action-package-builder.ts`, routesUsingTool: [...ROUTES], observationEvents: ["county_followup_plan_created"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-training-module-router", name: "County training module router", purpose: "Recommend county V2 training modules by role.", currentStatus: "functional", trigger: "Training hub", inputs: "role", outputs: "module ids", readsFrom: "src/lib/agents/training/training-module-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/training/training-module-registry.ts", routesUsingTool: ["/admin/training", ...ROUTES], observationEvents: ["county_training_started", "county_training_completed"], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-dashboard-module-recommender", name: "County dashboard module recommender", purpose: "Suggest county dashboard blocks for role.", currentStatus: "functional", trigger: "Dashboard builder", inputs: "role", outputs: "DashboardBlockId[]", readsFrom: "src/lib/agents/dashboard-builder/dashboard-component-registry.ts", writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: "src/lib/agents/dashboard-builder/dashboard-component-registry.ts", routesUsingTool: ["/admin/ai-command-center/dashboard-builder"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-strategy-to-event-adapter", name: "County strategy to event adapter", purpose: "Map county strategy into event planning tab.", currentStatus: "functional", trigger: "Drilldown", inputs: "county", outputs: "guidance", readsFrom: `${CI}county-event-strategy.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-event-strategy.ts`, routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-hotwash-next-action-builder", name: "County hot wash next action builder", purpose: "V2 hot wash county impact and next action.", currentStatus: "functional", trigger: "Hot wash complete", inputs: "outcomes", outputs: "CountyHotWashImpactV2", readsFrom: `${CI}county-hotwash-impact.ts`, writesTo: "—", humanApprovalRequired: true, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-hotwash-impact.ts`, routesUsingTool: ["/admin/campaign-events/[recordId]"], observationEvents: [], futureAutomationPath: "", testChecklist: [] }),
  c({ id: "county-priority-shift-detector", name: "County priority shift detector", purpose: "Flag counties crossing critical readiness band.", currentStatus: "functional", trigger: "Statewide load", inputs: "slug", outputs: "shift signal", readsFrom: `${CI}county-intelligence-engine.ts`, writesTo: "—", humanApprovalRequired: false, riskLevel: "low", guardrails: "", deterministicHelperPath: `${CI}county-intelligence-engine.ts`, routesUsingTool: [...ROUTES], observationEvents: ["county_priority_viewed"], futureAutomationPath: "", testChecklist: [] }),
];

export const SPRINT_COUNTY_INTELLIGENCE_V2_TOOL_CONTRACTS = TOOLS;
export const SPRINT_COUNTY_INTELLIGENCE_V2_CATALOG_ENTRIES: AiToolEntry[] = TOOLS.map(contractToCatalogEntry);
