import { contractToCatalogEntry, type CampaignAiToolContract } from "./tool-contract";
import type { AiToolEntry } from "../ai-tools-master-catalog";

const LIFECYCLE = "global_agent_orchestration" as const;
const SPRINT = 0;

function c(partial: Omit<CampaignAiToolContract, "sprint" | "lifecycle" | "version">): CampaignAiToolContract {
  return { sprint: SPRINT, lifecycle: LIFECYCLE, version: "v1", priority: "P0", ...partial };
}

/** V1 global orchestration tools — deterministic context + routing; no autonomous writes. */
export const GLOBAL_AGENT_ORCHESTRATION_TOOL_CONTRACTS: CampaignAiToolContract[] = [
  c({
    id: "global-agent-router",
    name: "Global agent router",
    purpose: "Route operator intent to the correct domain toolchain (events, travel, compliance, Ask Kelly).",
    currentStatus: "partial",
    trigger: "AI command center / future /admin/ai-command-center",
    inputs: "intent string, pathname, role",
    outputs: "recommended domain + tool ids",
    readsFrom: "master-tool-registry/index.ts",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Suggest only; never auto-execute cross-domain writes",
    deterministicHelperPath: "src/lib/agents/master-tool-registry/index.ts",
    routesUsingTool: ["/admin/ai-command-center", "/admin/campaign-events/ai-tools"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "Unified router with policy graph",
    testChecklist: ["Returns domain for sample intents"],
  }),
  c({
    id: "campaign-context-loader",
    name: "Campaign context loader",
    purpose: "Load campaign-wide snapshot: period, dashboards, sprint status docs.",
    currentStatus: "partial",
    trigger: "Agent session start",
    inputs: "period, role",
    outputs: "CampaignContextBundle",
    readsFrom: "BUILD_SPRINT_STATUS.md, loadCampaignEventsDashboard",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only",
    deterministicHelperPath: "src/lib/campaign-events/load-campaign-events-dashboard.ts",
    routesUsingTool: ["/admin/candidate-dashboard", "/admin/campaign-manager-dashboard"],
    observationEvents: [],
    futureAutomationPath: "Cached context pack",
    testChecklist: ["Dashboard snapshot loads"],
  }),
  c({
    id: "event-context-composer",
    name: "Event context composer",
    purpose: "Compose ledger row + fact card + sync + promotion meta for one event.",
    currentStatus: "functional",
    trigger: "Drilldown / promotion / review",
    inputs: "recordId",
    outputs: "EventContextPayload",
    readsFrom: "CampaignEventLedgerRecord, merge-persisted-row",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No GCal write",
    deterministicHelperPath: "src/lib/campaign-events/load-campaign-calendar-events.ts",
    routesUsingTool: ["/admin/campaign-events/[recordId]", "/admin/campaign-events/calendar-promotion"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "LLM summary layer",
    testChecklist: ["Drilldown loads row"],
  }),
  c({
    id: "county-context-composer",
    name: "County context composer",
    purpose: "Attach county profile + dashboard v2 field hints to event/travel context.",
    currentStatus: "partial",
    trigger: "County link from event",
    inputs: "county label",
    outputs: "CountyContextSlice",
    readsFrom: "county-political-profile, countyWorkbench field records (future)",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No cross-lane import without integration packet",
    deterministicHelperPath: "src/lib/campaign-engine/county-political-profile.ts",
    routesUsingTool: ["/admin/campaign-events/workbench", "CountyWorkbenchLink"],
    observationEvents: [],
    futureAutomationPath: "Approved countyWorkbench adapter",
    testChecklist: ["County label resolves"],
  }),
  c({
    id: "travel-context-composer",
    name: "Travel context composer",
    purpose: "Bundle travel lines, reimbursement month status, mileage gaps.",
    currentStatus: "functional",
    trigger: "Travel report / reimbursement open",
    inputs: "period",
    outputs: "TravelContextBundle",
    readsFrom: "travel-report-logic, reimbursement-month-status",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only",
    deterministicHelperPath: "src/lib/campaign-events/travel-report/travel-report-logic.ts",
    routesUsingTool: ["/admin/campaign-events/travel-report", "/admin/campaign-events/reimbursement"],
    observationEvents: [],
    futureAutomationPath: "Link to kelly-travel-reimbursement agent",
    testChecklist: ["March travel totals"],
  }),
  c({
    id: "reimbursement-context-composer",
    name: "Reimbursement context composer",
    purpose: "Official reimbursement request state + print readiness.",
    currentStatus: "functional",
    trigger: "Reimbursement page",
    inputs: "month",
    outputs: "ReimbursementContext",
    readsFrom: "reimbursement-month-status",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No FIN-1 write",
    deterministicHelperPath: "src/lib/campaign-events/travel-reimbursement/",
    routesUsingTool: ["/admin/campaign-events/reimbursement"],
    observationEvents: [],
    futureAutomationPath: "Treasurer handoff packet",
    testChecklist: ["Month status loads"],
  }),
  c({
    id: "approval-context-composer",
    name: "Approval context composer",
    purpose: "Approval package, email log, token status, candidate inbox slice.",
    currentStatus: "functional",
    trigger: "Approval package / Sprint 4 flows",
    inputs: "recordId",
    outputs: "ApprovalContextBundle",
    readsFrom: "approval-package, approval-email-log",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No send without gate",
    deterministicHelperPath: "src/lib/campaign-events/approval-email/",
    routesUsingTool: ["/admin/campaign-calendar/approval-package", "/campaign-events/approval/[token]"],
    observationEvents: ["approval_package_previewed"],
    futureAutomationPath: "Reply-by-email parser (blocked)",
    testChecklist: ["Package builds"],
  }),
  c({
    id: "calendar-truth-context-composer",
    name: "Calendar truth context composer",
    purpose: "Sync truth, lane health, promotion status for calendar decisions.",
    currentStatus: "functional",
    trigger: "Calendar sync / promotion workbench",
    inputs: "period",
    outputs: "CalendarTruthContext",
    readsFrom: "calendar-sync, promotion-meta",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only truth UI separate from write gate",
    deterministicHelperPath: "src/lib/campaign-events/calendar-sync/",
    routesUsingTool: ["/admin/campaign-events/calendar-sync", "/admin/campaign-events/calendar-promotion"],
    observationEvents: ["promotion_attempted"],
    futureAutomationPath: "Live GCal overlap in conflict scanner",
    testChecklist: ["Sync dashboard loads"],
  }),
  c({
    id: "operator-next-action-recommender",
    name: "Operator next-action recommender",
    purpose: "Rank top 5 human actions across queues (approve, promote, travel, intake).",
    currentStatus: "partial",
    trigger: "Dashboard / AI command center",
    inputs: "dashboard snapshot",
    outputs: "ranked actions[]",
    readsFrom: "load-campaign-events-dashboard, buildCommandCenterSnapshot",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "No auto-execute",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools-command-center.ts",
    routesUsingTool: ["/admin/campaign-events/ai-tools", "/admin/ai-command-center"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "Learn from accepted suggestions",
    testChecklist: ["buildNextRecommendations non-empty"],
  }),
  c({
    id: "workflow-bottleneck-detector",
    name: "Workflow bottleneck detector",
    purpose: "Find stages blocking month close (holds, missing geo, failed promotion).",
    currentStatus: "partial",
    trigger: "Month readiness",
    inputs: "period rows",
    outputs: "bottleneck report",
    readsFrom: "month-readiness-score, promotion queues",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Flag only",
    deterministicHelperPath: "src/lib/campaign-events/month-readiness/",
    routesUsingTool: ["/admin/campaign-events/month-readiness"],
    observationEvents: [],
    futureAutomationPath: "Time-in-stage metrics",
    testChecklist: ["Readiness score computes"],
  }),
  c({
    id: "stale-data-risk-detector",
    name: "Stale data risk detector",
    purpose: "JSON freshness, GCal stale rows, old sync timestamps.",
    currentStatus: "functional",
    trigger: "Sync dashboard load",
    inputs: "period",
    outputs: "stale warnings[]",
    readsFrom: "normalized-json-freshness, calendar-sync",
    writesTo: "banner",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Non-blocking",
    deterministicHelperPath: "src/lib/campaign-events/calendar-sync/normalized-json-freshness.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-sync"],
    observationEvents: [],
    futureAutomationPath: "Auto-refresh job (human approved)",
    testChecklist: ["jsonStale flag"],
  }),
  c({
    id: "cross-system-record-linker",
    name: "Cross-system record linker",
    purpose: "Link ledger recordId to CampaignEvent, Google ids, intake sourceKey.",
    currentStatus: "partial",
    trigger: "Drilldown / trace",
    inputs: "recordId",
    outputs: "link graph",
    readsFrom: "ledger + CampaignEvent + GoogleCalendarEventRecord",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Read-only",
    deterministicHelperPath: "src/lib/campaign-events/merge-persisted-row.ts",
    routesUsingTool: ["/admin/campaign-events/[recordId]"],
    observationEvents: [],
    futureAutomationPath: "Master linker table",
    testChecklist: ["recordId resolves"],
  }),
  c({
    id: "duplicate-system-detector",
    name: "Duplicate system detector",
    purpose: "Flag parallel agent stacks (Kelly Agent vs Event OS vs legacy push).",
    currentStatus: "partial",
    trigger: "Architecture audits",
    inputs: "registry inventory",
    outputs: "duplicate pairs[]",
    readsFrom: "GLOBAL_AI_AGENT_TOOL_INVENTORY.md",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Documentation only",
    deterministicHelperPath: "docs/campaign-events/GLOBAL_AI_AGENT_TOOL_INVENTORY.md",
    routesUsingTool: ["/admin/campaign-events/ai-tools"],
    observationEvents: [],
    futureAutomationPath: "CI registry diff",
    testChecklist: ["Inventory lists legacy push"],
  }),
  c({
    id: "human-approval-gate-enforcer",
    name: "Human approval gate enforcer",
    purpose: "Central check: blocks automation on email send, GCal write, compliance certify.",
    currentStatus: "functional",
    trigger: "Any write action",
    inputs: "action type, env",
    outputs: "allowed | blocked + reason",
    readsFrom: "CAMPAIGN_AI_HUMAN_CONTROL_RULES, promotion-config, approval-send-guard",
    writesTo: "audit log",
    humanApprovalRequired: true,
    riskLevel: "blocked",
    guardrails: "Default deny for autonomous writes",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/tool-contract.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion", "/admin/campaign-events/approval-package"],
    observationEvents: ["promotion_blocked", "approval_send_blocked"],
    futureAutomationPath: "Policy engine",
    testChecklist: ["GOOGLE_CALENDAR_WRITE_ENABLED off blocks"],
  }),
  c({
    id: "agent-memory-write-planner",
    name: "Agent memory write planner",
    purpose: "Plan what observations may be persisted to factCard (never PII in tests).",
    currentStatus: "scaffolded",
    trigger: "After AI assist",
    inputs: "observation event",
    outputs: "planned writes[]",
    readsFrom: "observations-persist.ts",
    writesTo: "_aiObservations (planned)",
    humanApprovalRequired: true,
    riskLevel: "medium",
    guardrails: "Append-only; cap length",
    deterministicHelperPath: "src/lib/campaign-events/ai-tools/observations-persist.ts",
    routesUsingTool: ["/admin/campaign-events/ai-tools"],
    observationEvents: ["ai_tool_invoked"],
    futureAutomationPath: "Vector memory store",
    testChecklist: ["Observations append on approval email"],
  }),
  c({
    id: "knowledge-chunk-router",
    name: "Knowledge chunk router",
    purpose: "Route queries to SearchChunk RAG vs deterministic catalogs.",
    currentStatus: "partial",
    trigger: "Ask Kelly / search",
    inputs: "query",
    outputs: "rag | catalog | both",
    readsFrom: "openai/search.ts, SearchChunk",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Public corpus only on site assistant",
    deterministicHelperPath: "src/lib/openai/search.ts",
    routesUsingTool: ["/api/search", "/api/assistant"],
    observationEvents: [],
    futureAutomationPath: "Ops corpus partition",
    testChecklist: ["search API returns hits when indexed"],
  }),
  c({
    id: "observation-pattern-miner",
    name: "Observation pattern miner",
    purpose: "Aggregate _aiObservations into repeated missing-field / failure patterns.",
    currentStatus: "idea",
    trigger: "Weekly ops review",
    inputs: "period observations",
    outputs: "pattern report",
    readsFrom: "_aiObservations across ledger",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No auto policy change",
    deterministicHelperPath: "docs/campaign-events/AI_AGENT_OBSERVATION_AND_LEARNING_ROADMAP.md",
    routesUsingTool: ["/admin/campaign-events/ai-tools"],
    observationEvents: [],
    futureAutomationPath: "Batch miner script",
    testChecklist: ["Doc defines signals"],
  }),
  c({
    id: "sprint-priority-recommender",
    name: "Sprint priority recommender",
    purpose: "Suggest next sprint focus from BUILD_SPRINT_STATUS blockers.",
    currentStatus: "partial",
    trigger: "AI command center",
    inputs: "BUILD_SPRINT_STATUS.md",
    outputs: "ranked sprint ids",
    readsFrom: "docs/campaign-events/BUILD_SPRINT_STATUS.md",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "low",
    guardrails: "Steve decides sprint order",
    deterministicHelperPath: "docs/campaign-events/BUILD_SPRINT_STATUS.md",
    routesUsingTool: ["/admin/campaign-events/ai-tools"],
    observationEvents: [],
    futureAutomationPath: "Live blocker sync",
    testChecklist: ["Sprint 5 marked complete"],
  }),
  c({
    id: "market-polish-gap-detector",
    name: "Market polish gap detector",
    purpose: "Flag UX/demo gaps vs production readiness bars.",
    currentStatus: "scaffolded",
    trigger: "Release review",
    inputs: "readiness scores",
    outputs: "gap list",
    readsFrom: "CAMPAIGN_OS_USABILITY_PASS.md, dashboards",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "No public promises",
    deterministicHelperPath: "docs/campaign-events/CAMPAIGN_OS_USABILITY_PASS.md",
    routesUsingTool: ["/admin/candidate-dashboard"],
    observationEvents: [],
    futureAutomationPath: "Automated demo checklist",
    testChecklist: ["Usability doc exists"],
  }),
  c({
    id: "demo-readiness-scorer",
    name: "Demo readiness scorer",
    purpose: "Score demo-safe surfaces (workbench, promotion dry-run, approval preview).",
    currentStatus: "partial",
    trigger: "Pre-demo",
    inputs: "env flags",
    outputs: "demo score 0-100",
    readsFrom: "promotion-config, EMAIL_SEND_ENABLED",
    writesTo: "—",
    humanApprovalRequired: false,
    riskLevel: "low",
    guardrails: "Dry-run default",
    deterministicHelperPath: "src/lib/campaign-events/calendar-promotion/promotion-config.ts",
    routesUsingTool: ["/admin/campaign-events/calendar-promotion"],
    observationEvents: [],
    futureAutomationPath: "CI demo gate",
    testChecklist: ["Write disabled shows banner"],
  }),
  c({
    id: "production-risk-scorer",
    name: "Production risk scorer",
    purpose: "Score live-write risk: GCal, email, compliance, voter data.",
    currentStatus: "partial",
    trigger: "Launch hardening",
    inputs: "env + registry",
    outputs: "risk tier",
    readsFrom: "GOOGLE_PROMOTION_SAFETY.md, ai-agent-brain-map",
    writesTo: "—",
    humanApprovalRequired: true,
    riskLevel: "high",
    guardrails: "Never auto-enable writes",
    deterministicHelperPath: "docs/campaign-events/GOOGLE_PROMOTION_SAFETY.md",
    routesUsingTool: ["/admin/ai-command-center"],
    observationEvents: [],
    futureAutomationPath: "Netlify env audit",
    testChecklist: ["Inventory lists blockers"],
  }),
];

export const GLOBAL_AGENT_ORCHESTRATION_CATALOG_ENTRIES: AiToolEntry[] =
  GLOBAL_AGENT_ORCHESTRATION_TOOL_CONTRACTS.map(contractToCatalogEntry);
