const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const CALIBRATION_VERSION='1.0';
export const DEFAULT_FEATURES=['momentum5','momentum20','relativeStrength','relativeVolume','realizedVolatility','spreadBps'];
export function confidenceBucket(score){return Math.floor(clamp(Number(score)||0,0,99.999)/10)*10}
export function calibrationReport(labeled=[],horizon='15m'){const buckets=new Map();for(const row of labeled){const outcome=row.outcomes?.[horizon]?.returnPct;if(!Number.isFinite(outcome))continue;const b=confidenceBucket(row.score);const x=buckets.get(b)||{bucket:b,samples:0,positive:0,sumReturn:0};x.samples++;x.positive+=outcome>0?1:0;x.sumReturn+=outcome;buckets.set(b,x)}return[...buckets.values()].sort((a,b)=>a.bucket-b.bucket).map(x=>({...x,observedPositiveRate:x.positive/x.samples,averageReturn:x.sumReturn/x.samples,calibrationGap:(x.positive/x.samples)-((x.bucket+5)/100)}))}
export function brierScore(labeled=[],horizon='15m'){const terms=[];for(const row of labeled){const r=row.outcomes?.[horizon]?.returnPct;if(!Number.isFinite(r))continue;const p=clamp((Number(row.score)||50)/100,0,1),y=r>0?1:0;terms.push((p-y)**2)}return terms.length?terms.reduce((a,b)=>a+b,0)/terms.length:null}
function correlation(xs,ys){if(xs.length<3)return null;const mx=xs.reduce((a,b)=>a+b,0)/xs.length,my=ys.reduce((a,b)=>a+b,0)/ys.length;let n=0,dx=0,dy=0;for(let i=0;i<xs.length;i++){const a=xs[i]-mx,b=ys[i]-my;n+=a*b;dx+=a*a;dy+=b*b}return dx&&dy?n/Math.sqrt(dx*dy):null}
export function featureContribution(labeled=[],feature,horizon='15m'){const xs=[],ys=[];for(const row of labeled){const x=Number(row.features?.[feature]),y=row.outcomes?.[horizon]?.returnPct;if(Number.isFinite(x)&&Number.isFinite(y)){xs.push(x);ys.push(y)}}const corr=correlation(xs,ys);return{feature,samples:xs.length,correlation:corr,absoluteContribution:corr==null?null:Math.abs(corr),direction:corr==null?'UNKNOWN':corr>0?'POSITIVE':'NEGATIVE'}}
export function ablationReport(labeled=[],features=DEFAULT_FEATURES,horizon='15m'){return features.map(f=>featureContribution(labeled,f,horizon)).sort((a,b)=>(b.absoluteContribution??-1)-(a.absoluteContribution??-1))}
export function regimeCalibration(labeled=[],horizon='15m'){const groups={};for(const r of labeled)(groups[r.regime||'UNKNOWN']??=[]).push(r);return Object.fromEntries(Object.entries(groups).map(([regime,rows])=>[regime,{samples:rows.length,brier:brierScore(rows,horizon),buckets:calibrationReport(rows,horizon)}]))}
export function calibrationCycle({labeled=[],horizon='15m',simulationId=`cal-${Date.now()}`}){const report=calibrationReport(labeled,horizon),ablation=ablationReport(labeled,DEFAULT_FEATURES,horizon),brier=brierScore(labeled,horizon);return{id:simulationId,version:CALIBRATION_VERSION,createdAt:new Date().toISOString(),horizon,samples:report.reduce((a,b)=>a+b.samples,0),brier,buckets:report,ablation,regimes:regimeCalibration(labeled,horizon),lessons:deriveCalibrationLessons({report,ablation,brier}),safety:{descriptiveResearchOnly:true,noGuaranteedReturns:true,noLiveOrders:true}}}
export function deriveCalibrationLessons({report=[],ablation=[],brier=null}){const lessons=[];if(Number.isFinite(brier))lessons.push({type:'CALIBRATION',text:`Brier score ${brier.toFixed(4)}; lower is better and must be compared across later held-out samples.`});for(const b of report)if(b.samples>=10&&Math.abs(b.calibrationGap)>.15)lessons.push({type:'CONFIDENCE',text:`${b.bucket}-${b.bucket+9} score bucket differs from observed positive frequency by ${(b.calibrationGap*100).toFixed(1)} percentage points.`});for(const f of ablation)if(f.samples>=20&&Number.isFinite(f.absoluteContribution)&&f.absoluteContribution<.03)lessons.push({type:'FEATURE',text:`${f.feature} showed little linear relationship to the selected forward outcome in this sample; keep it under review rather than assuming value.`});return lessons}
