import registry from '../agents/agent-registry.v1.json' with {type:'json'};import {validateAgentResearchPacket} from './agent-research-packet.js';const IDS=['data-quality','overfitting','cost','risk'];const byId=new Map(registry.agents.map(a=>[a.id,a]));export function controlAgentIds(){return [...IDS]}
const tests={
'data-quality':m=>({blocked:Boolean(m.stale||m.missingCritical||m.conflicting),reasons:[m.stale&&'STALE_DATA',m.missingCritical&&'MISSING_CRITICAL_DATA',m.conflicting&&'CONFLICTING_DATA'].filter(Boolean)}),
'overfitting':m=>({blocked:Boolean((m.sampleSize??0)<30||m.lookaheadLeakage||m.parameterInstability||m.multipleTestingUncontrolled),reasons:[(m.sampleSize??0)<30&&'SMALL_SAMPLE',m.lookaheadLeakage&&'LOOKAHEAD_LEAKAGE',m.parameterInstability&&'PARAMETER_INSTABILITY',m.multipleTestingUncontrolled&&'MULTIPLE_TESTING'].filter(Boolean)}),
'cost':m=>{const total=Number(m.spreadCost||0)+Number(m.slippageCost||0)+Number(m.commissionCost||0)+Number(m.marketImpactCost||0);const edge=Number(m.expectedGrossEdge||0);return{blocked:!Number.isFinite(edge)||edge<=total,reasons:[edge<=total&&'COST_EXCEEDS_OR_EQUALS_GROSS_EDGE'].filter(Boolean),totalCost:total}},
'risk':m=>({blocked:Boolean(m.positionLimitExceeded||m.concentrationLimitExceeded||m.lossLimitExceeded||m.liquidityRiskExceeded),reasons:[m.positionLimitExceeded&&'POSITION_LIMIT',m.concentrationLimitExceeded&&'CONCENTRATION_LIMIT',m.lossLimitExceeded&&'LOSS_LIMIT',m.liquidityRiskExceeded&&'LIQUIDITY_RISK'].filter(Boolean)})};
export function evaluateControl(agentId,metrics={}){if(!IDS.includes(agentId))throw new Error('NOT_CONTROL_AGENT');return tests[agentId](metrics)}
export function runControlAgent(agentId,{symbol='TEST',metrics={},upstreamPacketRefs=[],invokedAt='2026-01-01T00:00:00Z'}={}){const a=byId.get(agentId);if(!a||!IDS.includes(agentId))throw new Error('NOT_CONTROL_AGENT');const ev=evaluateControl(agentId,metrics),missing=[];if(!upstreamPacketRefs.length)missing.push('No upstream evidence packet references.');const state=missing.length?'PARTIAL':'AVAILABLE',blocked=state==='AVAILABLE'&&ev.blocked;const packet={schemaVersion:'1.0.0',packetId:'pkt-'+agentId+'-'+symbol+'-'+String(invokedAt).replace(/\W/g,'').slice(0,17),agent:{id:agentId,version:'1.0.0',mandate:a.mandate},scope:{kind:'SECURITY',symbols:[symbol],universeId:null},timing:{invokedAt:new Date(invokedAt).toISOString(),dataAsOf:null,completedAt:new Date().toISOString()},evidenceState:state,inputs:upstreamPacketRefs.map(refId=>({refId,kind:'PACKET',note:null})),observations:[{claimId:agentId+'-gate',statement:blocked?'Control gate blocks downstream advancement.':'Control gate does not currently block downstream advancement.',status:'DERIVED',evidenceRefs:upstreamPacketRefs}],calculations:Object.hasOwn(ev,'totalCost')?[{name:'total-estimated-cost',method:'sum-explicit-cost-components',value:ev.totalCost,units:'return-fraction',parameters:{}}]:[],hypothesis:null,supportingEvidence:[],contradictingEvidence:blocked?upstreamPacketRefs.map(refId=>({refId,kind:'PACKET',note:'Upstream candidate is challenged by control gate.'})):[],missingEvidence:missing,uncertainty:{level:missing.length?'HIGH':'MEDIUM',reasons:[...missing,...ev.reasons],sampleSize:Number.isFinite(metrics.sampleSize)?metrics.sampleSize:null},methodology:{confidenceKind:'NONE',value:null,description:'Deterministic control gate; not a probability or trade recommendation.',calibrationRef:null},sources:[],versions:{code:'v2.5-08',config:'v1',model:null,dataContract:'control-agent.v1'},decision:{class:blocked?'AVOID':state==='PARTIAL'?'NO_OP':'NEUTRAL',summary:blocked?'Control gate blocks strategy advancement: '+ev.reasons.join(', '):state==='PARTIAL'?'Control review incomplete.':'Control gate passed under supplied inputs.',direction:'NONE'},invalidationConditions:['Control inputs change','Upstream evidence changes'],downstreamPacketRefs:[]};const v=validateAgentResearchPacket(packet);if(!v.ok)throw new Error('INVALID_PACKET:'+v.errors.join(','));return{packet,blocked,reasons:ev.reasons};}
export function runControlDepartment(inputByAgent={}){const reviews=IDS.map(id=>runControlAgent(id,inputByAgent[id]||{}));return{reviews,blocked:reviews.some(r=>r.blocked),blockingAgents:reviews.filter(r=>r.blocked).map(r=>r.packet.agent.id)};}
