import { STRATEGIES } from './strategy-lab.js';
import { backtestStrategy, rollingWalkForward } from './outcome-lab.js';
import { providerTimeMs } from './data/historical.js';
export const LEARNING_VERSION='1.1';
export const PROMOTION_GATES={minClosedTrades:12,minWalkForwardWindows:3,minPositiveTestWindows:2,maxDrawdown:.12,minProfitFactor:1.05,minExpectancy:0};
const finite=v=>Number.isFinite(Number(v));
export function regimeGroups(rows=[]){const groups={};for(const row of rows){const key=row.regime||'UNKNOWN';(groups[key]??=[]).push(row)}return groups}
export function primaryResearchSymbol(rows=[]){const counts={};for(const r of rows)if(r.symbol)counts[r.symbol]=(counts[r.symbol]||0)+1;return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]||null}
export function baselineBuyHold(rows=[],startingCash=500,costs={},symbol=null){const chosen=symbol||primaryResearchSymbol(rows),ordered=rows.filter(r=>(!chosen||r.symbol===chosen)&&Number(r.price)>0).sort((a,b)=>providerTimeMs(a.providerTime)-providerTimeMs(b.providerTime));if(ordered.length<2)return{symbol:chosen,startingCash,endingCash:startingCash,returnPct:0,maxDrawdown:0};const first=Number(ordered[0].price),shares=(startingCash*.8)/first;let peak=startingCash,maxDrawdown=0;for(const r of ordered){const equity=startingCash+(Number(r.price)-first)*shares;peak=Math.max(peak,equity);maxDrawdown=Math.max(maxDrawdown,(peak-equity)/peak)}const last=Number(ordered.at(-1).price),gross=(last-first)*shares,halfSpread=(costs.spreadBps??4)/2,execution=(first*shares+last*shares)*(halfSpread+(costs.slippageBps??2))/10000,fees=(costs.commissionPerOrder??0)*2+last*shares*(costs.secFeePerMillionOnSales??20.6)/1e6+Math.min(shares*(costs.tafPerShareOnSales??.000195),9.79),endingCash=startingCash+gross-execution-fees;return{symbol:chosen,startingCash,endingCash,returnPct:(endingCash-startingCash)/startingCash,maxDrawdown}}
export function evaluateCandidate({strategy,rows,costs={}}){const researchSymbol=primaryResearchSymbol(rows),sample=rows.filter(r=>r.symbol===researchSymbol),overall=backtestStrategy({strategy,rows:sample,symbol:researchSymbol,costs}),windows=rollingWalkForward({strategy,rows:sample,symbol:researchSymbol,trainSize:Math.max(60,Math.floor(sample.length*.45)),testSize:Math.max(20,Math.floor(sample.length*.15)),costs}),positiveTestWindows=windows.filter(w=>w.test.returnPct>0).length,baseline=baselineBuyHold(sample,500,costs,researchSymbol),byRegime={};for(const [regime,items] of Object.entries(regimeGroups(sample)))byRegime[regime]=backtestStrategy({strategy,rows:items,symbol:researchSymbol,costs});const reasons=[];if(overall.trades<PROMOTION_GATES.minClosedTrades)reasons.push(`Needs ${PROMOTION_GATES.minClosedTrades}+ closed trades.`);if(windows.length<PROMOTION_GATES.minWalkForwardWindows)reasons.push(`Needs ${PROMOTION_GATES.minWalkForwardWindows}+ walk-forward windows.`);if(positiveTestWindows<PROMOTION_GATES.minPositiveTestWindows)reasons.push('Too few positive held-out windows.');if(overall.maxDrawdown>PROMOTION_GATES.maxDrawdown)reasons.push('Drawdown exceeds research gate.');if(!finite(overall.profitFactor)||overall.profitFactor<PROMOTION_GATES.minProfitFactor)reasons.push('Profit factor below gate.');if(overall.expectancy<=PROMOTION_GATES.minExpectancy)reasons.push('Expectancy is not positive after modeled costs.');const state=reasons.length?'RESEARCH':'SHADOW_CANDIDATE';return{strategyId:strategy.id,strategyName:strategy.name,researchSymbol,state,reasons,overall,baseline,excessReturn:overall.returnPct-baseline.returnPct,windows,positiveTestWindows,byRegime}}
export function runLearningCycle({rows=[],costs={},strategies=STRATEGIES,simulationId=`sim-${Date.now()}`}){const researchSymbol=primaryResearchSymbol(rows),candidates=strategies.map(strategy=>evaluateCandidate({strategy,rows,costs}));return{id:simulationId,learningVersion:LEARNING_VERSION,createdAt:new Date().toISOString(),observationCount:rows.length,researchSymbol,costModel:{...costs},gates:PROMOTION_GATES,candidates,lessons:deriveLessons(candidates),ethics:{fictionalOnly:true,noLiveOrders:true,noGuaranteedReturns:true,operatorApprovalRequired:true}}}
export function deriveLessons(candidates=[]){const lessons=[];for(const c of candidates){if(c.overall.expectancy<=0)lessons.push({strategyId:c.strategyId,type:'AVOID',lesson:'This version did not produce positive expectancy after modeled costs.'});if(c.overall.maxDrawdown>PROMOTION_GATES.maxDrawdown)lessons.push({strategyId:c.strategyId,type:'RISK',lesson:'Observed drawdown exceeded the research risk gate.'});if(c.excessReturn<=0)lessons.push({strategyId:c.strategyId,type:'BASELINE',lesson:'This version did not outperform the simple baseline over this sample.'});if(c.state==='SHADOW_CANDIDATE')lessons.push({strategyId:c.strategyId,type:'CANDIDATE',lesson:'This version passed current research gates and may be shadow-tested; it is not approved for live-money execution.'})}return lessons}
export function learningSummary(cycle){return{simulationId:cycle.id,observations:cycle.observationCount,researchSymbol:cycle.researchSymbol,candidates:cycle.candidates.length,shadowCandidates:cycle.candidates.filter(c=>c.state==='SHADOW_CANDIDATE').length,lessons:cycle.lessons.length}}
