import registry from '../agents/agent-registry.v1.json' with {type:'json'};import {validateAgentResearchPacket} from './agent-research-packet.js';
const IDS=['lower-price-liquid-mover','breakout-hunter','reversal-hunter','momentum-hunter','oversold-reversion-hunter','relative-strength-hunter','earnings-setup-hunter','volume-anomaly-hunter','sector-rotation-hunter','large-cap-quality-hunter','etf-opportunity-hunter','intraday-opportunity-hunter'];const byId=new Map(registry.agents.map(a=>[a.id,a]));
const rules={
'lower-price-liquid-mover':m=>m.price>0&&m.price<=25&&m.avgDollarVolume>=5e6&&m.relativeVolume>=1.5&&m.momentum>0,
'breakout-hunter':m=>m.breakout===true&&m.relativeVolume>=1.2&&m.avgDollarVolume>=5e6,
'reversal-hunter':m=>Math.abs(m.zScore)>=2&&m.reversalConfirmation===true,
'momentum-hunter':m=>m.momentum>=.03&&m.relativeVolume>=1.1,
'oversold-reversion-hunter':m=>m.zScore<=-2&&m.reversalConfirmation===true,
'relative-strength-hunter':m=>m.relativeStrength>=.02,
'earnings-setup-hunter':m=>m.daysToEarnings!=null&&m.daysToEarnings>=0&&m.daysToEarnings<=7&&m.earningsEvidence===true,
'volume-anomaly-hunter':m=>m.relativeVolume>=2,
'sector-rotation-hunter':m=>m.sectorRelativeStrength>=.02,
'large-cap-quality-hunter':m=>m.marketCap>=1e10&&m.qualityEvidence===true&&m.momentum>0,
'etf-opportunity-hunter':m=>m.isEtf===true&&m.avgDollarVolume>=1e7&&Math.abs(m.relativeStrength)>=.01,
'intraday-opportunity-hunter':m=>m.intraday===true&&m.relativeVolume>=1.5&&m.spreadPct<=.003};
export function opportunityHunterIds(){return [...IDS]}
export function evaluateOpportunity(agentId,metrics={}){if(!IDS.includes(agentId))throw new Error('NOT_OPPORTUNITY_HUNTER');const requiredBase=['price','avgDollarVolume'];const missing=requiredBase.filter(k=>!Number.isFinite(Number(metrics[k])));if(missing.length)return{qualified:false,missing,reason:'INSUFFICIENT_BASE_METRICS'};return{qualified:Boolean(rules[agentId](metrics)),missing:[],reason:'RULE_EVALUATED'};}
export function runOpportunityHunter(agentId,{symbol='TEST',metrics={},upstreamPacketRefs=[],invokedAt='2026-01-01T00:00:00Z',dataAsOf=null}={}){const a=byId.get(agentId);if(!a||!IDS.includes(agentId))throw new Error('NOT_OPPORTUNITY_HUNTER');const ev=evaluateOpportunity(agentId,metrics),missing=[...ev.missing.map(x=>'Missing metric: '+x)];if(!upstreamPacketRefs.length)missing.push('No upstream evidence packet references.');const state=missing.length?'PARTIAL':'AVAILABLE';const qualified=state==='AVAILABLE'&&ev.qualified;const packet={schemaVersion:'1.0.0',packetId:'pkt-'+agentId+'-'+symbol+'-'+String(invokedAt).replace(/\W/g,'').slice(0,17),agent:{id:agentId,version:'1.0.0',mandate:a.mandate},scope:{kind:'SECURITY',symbols:[symbol],universeId:null},timing:{invokedAt:new Date(invokedAt).toISOString(),dataAsOf:dataAsOf?new Date(dataAsOf).toISOString():null,completedAt:new Date().toISOString()},evidenceState:state,inputs:upstreamPacketRefs.map(refId=>({refId,kind:'PACKET',note:null})),observations:[{claimId:agentId+'-screen',statement:qualified?'Candidate satisfies this hunter’s explicit screening rule.':'Candidate does not currently satisfy this hunter’s explicit screening rule.',status:'DERIVED',evidenceRefs:upstreamPacketRefs}],calculations:[{name:'screen-qualified',method:'deterministic-v2.5-06',value:qualified?1:0,units:'boolean',parameters:{...metrics}}],hypothesis:qualified?{statement:'Candidate warrants downstream research under the '+a.name+' mandate.',falsifiable:true,test:'Re-evaluate when inputs change and measure subsequent simulated outcomes.'}:null,supportingEvidence:qualified?upstreamPacketRefs.map(refId=>({refId,kind:'PACKET',note:'Upstream evidence used by deterministic screen.'})):[],contradictingEvidence:[],missingEvidence:missing,uncertainty:{level:missing.length?'HIGH':'MEDIUM',reasons:missing,sampleSize:null},methodology:{confidenceKind:'NONE',value:null,description:'Deterministic candidate screen. Qualification is not probability of profit or investment advice.',calibrationRef:null},sources:[],versions:{code:'v2.5-06',config:'v1',model:null,dataContract:'opportunity-hunter.v1'},decision:{class:qualified?'WATCH':'NO_OP',summary:qualified?'Escalate candidate for downstream adversarial research.':'No escalation under this hunter mandate.',direction:'NONE'},invalidationConditions:['Screen inputs no longer satisfy mandate','Upstream evidence becomes stale or invalid'],downstreamPacketRefs:[]};const v=validateAgentResearchPacket(packet);if(!v.ok)throw new Error('INVALID_PACKET:'+v.errors.join(','));return packet;}
export function scanOpportunityTeam(candidates=[]){return candidates.flatMap(c=>IDS.map(id=>runOpportunityHunter(id,c)));}
