import './v6-product-shell.css';
import {routeFromLocation,v6ShellMarkup,dashboardFirstFrame,placeholderSurface} from './v6-product-shell.js';
import {loadWealthBuilderOverview,overviewForDashboard} from './v6-production-data.js';
const app=document.querySelector('#app');let overview=null,loading=true;
function extractPortfolio(data){const p=data?.sources?.learning?.data?.portfolio||data?.sources?.marketMemory?.data?.portfolio||null;return {portfolioValue:Number(p?.equity||p?.value||100000),returnPct:Number(p?.returnPct||0)};}
function researchSummary(data){const m=data?.sources?.marketMemory?.data||{};const count=Number(m.observations||m.count||0);return count?{title:count+' market observations retained',summary:'Market Memory is accumulating evidence for comparison and research.'}:{title:'Research organization ready',summary:'Evidence-backed findings, disagreements and view changes will surface here.'};}
function content(route){if(route!=='dashboard')return placeholderSurface(route);if(loading)return dashboardFirstFrame({attention:['Connecting Wealth Builder production services…'],research:[{title:'Loading research organization',summary:'Checking market, memory, learning and database health.'}],learning:'Your learning history is loading.',competition:'Competition architecture ready; founding cohort is not active.'});const d=overviewForDashboard(overview);const p=extractPortfolio(overview);return dashboardFirstFrame({...p,attention:d.attention,research:[researchSummary(overview)],learning:d.learning?.nextLesson||d.learning?.recommendation||'Continue building your evidence and risk vocabulary.',competition:'10 humans + one sealed Wealth Builder AI · 90 days · simulated capital.'});}
function tape(){if(loading)return 'Connecting production services…';if(overview?.status==='DEGRADED')return 'DATA HEALTH · Some services are degraded. Wealth Builder will not invent missing evidence.';return 'SYSTEM READY · Market, memory, learning and production data services are responding.';}
function render(){const route=routeFromLocation();app.innerHTML=v6ShellMarkup({route,content:content(route),tape:tape(),status:overview?.status==='DEGRADED'?'DEGRADED · SIMULATION ONLY':'SIMULATION ONLY'});app.querySelector('[data-tape-explain]')?.addEventListener('click',()=>{location.hash='#/research'});}
async function boot(){render();overview=await loadWealthBuilderOverview();loading=false;render();}
addEventListener('hashchange',render);boot();
