import type { MediaClip, MediaResearchSnapshot, MediaTopicId } from "./contracts";
import { MEDIA_RESEARCH_ACCESSED, MEDIA_RESEARCH_VERSION } from "./contracts";
import type { WritingActorId } from "../writing-intelligence/contracts";

const A = MEDIA_RESEARCH_ACCESSED;

function clip(text: string, max = 220): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  return `${cut.slice(0, lastSpace > 80 ? lastSpace : max)}…`;
}

export const MEDIA_CLIPS: MediaClip[] = [
  {
    id: "jones-tb-2025-10-09-launch",
    actorId: "chris-jones-ar02",
    outlet: "Talk Business & Politics",
    title: "Chris Jones officially launches bid for Congress",
    url: "https://talkbusiness.net/2025/10/chris-jones-officially-launches-bid-for-congress/",
    publishedAt: "2025-10-09",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "PREPARED_STATEMENT",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["AFFORDABILITY", "ACCOUNTABILITY"],
    quote: clip(
      "Arkansans are stressed and exhausted because for too long, politicians have played 'photo op bingo' with our communities, dumped today's problems on our future, and left working families trying to make a dollar out of 15 cents.",
    ),
  },
  {
    id: "jones-tb-2025-10-09-builder",
    actorId: "chris-jones-ar02",
    outlet: "Talk Business & Politics",
    title: "Chris Jones officially launches bid for Congress",
    url: "https://talkbusiness.net/2025/10/chris-jones-officially-launches-bid-for-congress/",
    publishedAt: "2025-10-09",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["DEMOCRACY"],
    quote: clip("I'm a builder, a fighter, and a visionary — and I believe in the power of Arkansans to rise together. No one left out. No one left behind."),
  },
  {
    id: "jones-swtimes-2025-10-10-table",
    actorId: "chris-jones-ar02",
    outlet: "Southwest Times Record",
    title: "Democrat Chris Jones formally announces campaign to unseat French Hill",
    url: "https://www.swtimes.com/story/news/2025/10/10/democrat-chris-jones-formally-announces-campaign-to-unseat-french-hill/86621708007/",
    publishedAt: "2025-10-10",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "PREPARED_STATEMENT",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["DEMOCRACY", "EDUCATION"],
    quote: clip(
      "Together, we are building a table that rests on four legs: justice, economy, democracy, and innovation.",
    ),
  },
  {
    id: "jones-thv11-2025-10-townhalls",
    actorId: "chris-jones-ar02",
    outlet: "THV11",
    title: "Chris Jones kicks off campaign against French Hill for Arkansas's 2nd district",
    url: "https://www.thv11.com/article/news/politics/chris-jones-campaign-french-hill-arkansass-2nd-district/91-aaf19ed0-db4b-4a15-ae65-1aa813af5d35",
    publishedAt: "2025-10-09",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["EDUCATION", "HEALTHCARE"],
    quote: clip(
      "We're doing eight town halls in four weeks. We are showing up in every county in the district so that together we can build our vision for Arkansas and the Second District.",
    ),
    notes: "Full page was not re-fetched this pass; quote is from the outlet's public snippet.",
  },
  {
    id: "jones-tb-2025-11-02-hearing",
    actorId: "chris-jones-ar02",
    outlet: "Talk Business & Politics",
    title: "Chris Jones sees path to build on 2nd District vote totals",
    url: "https://talkbusiness.net/2025/11/chris-jones-sees-path-to-build-on-2nd-district-vote-totals/",
    publishedAt: "2025-11-02",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["AFFORDABILITY", "HEALTHCARE", "RURAL_HOSPITALS", "EDUCATION"],
    quote: clip(
      "Affordability. Folks are like, 'I can't afford anything and I thought it was going to be fixed on day one,' but affordability matters. And that's in healthcare. The cost of healthcare is going up like crazy… Rural hospitals are closing.",
    ),
  },
  {
    id: "jones-adg-2026-01-11-systems",
    actorId: "chris-jones-ar02",
    outlet: "Arkansas Democrat-Gazette",
    title: "Jones, Huffman stress affordability in Arkansas' 2nd District Democratic primary",
    url: "https://www.arkansasonline.com/news/2026/jan/11/jones-huffman-stress-affordability-in-arkansas/",
    publishedAt: "2026-01-11",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["AFFORDABILITY", "HOUSING", "HEALTHCARE"],
    quote: clip(
      "For me, looking at the U.S. House of Representatives is really about looking at the systems that impact affordability. People just can't pay for things now.",
    ),
    notes: "Paywalled full text not stored. Public snippet only.",
  },
  {
    id: "jones-adg-2026-01-11-agenda",
    actorId: "chris-jones-ar02",
    outlet: "Arkansas Democrat-Gazette",
    title: "Jones, Huffman stress affordability in Arkansas' 2nd District Democratic primary",
    url: "https://www.arkansasonline.com/news/2026/jan/11/jones-huffman-stress-affordability-in-arkansas/",
    publishedAt: "2026-01-11",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["AFFORDABILITY", "ACCOUNTABILITY"],
    quote: clip("My primary agenda is on issues of affordability and accountability. The things that fall in that bucket, I'm all for it."),
    notes: "Paywalled full text not stored. Public snippet only.",
  },
  {
    id: "jones-katv-2026-02-11-prices",
    actorId: "chris-jones-ar02",
    outlet: "KATV",
    title: "Arkansas' 2nd District Showdown: As March 3rd Nears, Chris Jones Calls for Accountability",
    url: "https://katv.com/news/local/arkansas-2nd-district-showdown-as-march-3rd-nears-chris-jones-calls-for-accountability",
    publishedAt: "2026-02-11",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["HOUSING", "HEALTHCARE", "AFFORDABILITY"],
    quote: clip("The price of housing is too high, that the price of healthcare is way too high and going up, groceries and utilities."),
  },
  {
    id: "jones-katv-2026-02-11-farmers",
    actorId: "chris-jones-ar02",
    outlet: "KATV",
    title: "Arkansas' 2nd District Showdown: As March 3rd Nears, Chris Jones Calls for Accountability",
    url: "https://katv.com/news/local/arkansas-2nd-district-showdown-as-march-3rd-nears-chris-jones-calls-for-accountability",
    publishedAt: "2026-02-11",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["AGRICULTURE", "AFFORDABILITY"],
    quote: clip(
      "When farmers are impacted, our food is impacted. Arkansas is the hungriest state in the nation. It's enormously problematic when we figure out how to feed the world, but can't find out how to feed our own families.",
    ),
  },
  {
    id: "jones-katv-2026-02-11-tariffs",
    actorId: "chris-jones-ar02",
    outlet: "KATV",
    title: "Arkansas' 2nd District Showdown: As March 3rd Nears, Chris Jones Calls for Accountability",
    url: "https://katv.com/news/local/arkansas-2nd-district-showdown-as-march-3rd-nears-chris-jones-calls-for-accountability",
    publishedAt: "2026-02-11",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["TAXES", "AGRICULTURE"],
    quote: clip("Say what you will, color it how you want to — tariffs at the end of the day are taxes. And Arkansans don't like paying taxes to the federal government."),
  },
  {
    id: "jones-katv-2026-02-11-hospitals",
    actorId: "chris-jones-ar02",
    outlet: "KATV",
    title: "Arkansas' 2nd District Showdown: As March 3rd Nears, Chris Jones Calls for Accountability",
    url: "https://katv.com/news/local/arkansas-2nd-district-showdown-as-march-3rd-nears-chris-jones-calls-for-accountability",
    publishedAt: "2026-02-11",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["RURAL_HOSPITALS", "HEALTHCARE"],
    quote: clip(
      "Time matters. We're seeing hospitals closing in areas and it's doubling and tripling the time it takes for folks to get to the hospital. Arkansas also leads the nation in ambulatory deserts.",
    ),
  },
  {
    id: "jones-amp-2026-07-16-focus",
    actorId: "chris-jones-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Will It Be Enough? Chris Jones is Back in the Political Saddle and Feisty as Ever",
    url: "https://armoneyandpolitics.com/chris-jones-back-in-political-saddle/",
    publishedAt: "2026-07-16",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["AFFORDABILITY", "ACCOUNTABILITY"],
    quote: clip("We have been hyperfocused from the beginning on engaging communities all across the district on affordability and accountability. How do we make life more affordable for Arkansans?"),
  },
  {
    id: "jones-amp-2026-07-16-hospitals",
    actorId: "chris-jones-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Will It Be Enough? Chris Jones is Back in the Political Saddle and Feisty as Ever",
    url: "https://armoneyandpolitics.com/chris-jones-back-in-political-saddle/",
    publishedAt: "2026-07-16",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["RURAL_HOSPITALS", "HEALTHCARE", "CONTRAST"],
    quote: clip("We're at risk of losing a lot of rural hospitals because of cuts to Medicaid, so when French Hill voted to cut Medicaid, that caused insurance premiums to go through the roof."),
    notes: "Jones campaign characterization of a Hill vote. Not ingested as a Hill fact.",
  },
  {
    id: "jones-amp-2026-07-16-education",
    actorId: "chris-jones-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Will It Be Enough? Chris Jones is Back in the Political Saddle and Feisty as Ever",
    url: "https://armoneyandpolitics.com/chris-jones-back-in-political-saddle/",
    publishedAt: "2026-07-16",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["EDUCATION"],
    quote: clip(
      "There should be a floor, and right now, we don't have a floor.",
    ),
    notes: "Said in the context of a minimum resource floor for public-school districts.",
  },
  {
    id: "jones-amp-2026-07-16-emergency",
    actorId: "chris-jones-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Will It Be Enough? Chris Jones is Back in the Political Saddle and Feisty as Ever",
    url: "https://armoneyandpolitics.com/chris-jones-back-in-political-saddle/",
    publishedAt: "2026-07-16",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["AFFORDABILITY", "EDUCATION"],
    quote: clip("Right now, we're in an emergency situation. Party affiliation does not matter."),
  },
  {
    id: "jones-axios-2022-09-19-pbj",
    actorId: "chris-jones-ar02",
    outlet: "Axios NW Arkansas",
    title: "Chris Jones wants to walk in Arkansans' shoes during run for governor",
    url: "https://www.axios.com/local/nw-arkansas/2022/09/19/chris-jones-arkansas-governor-democrat-interview",
    publishedAt: "2022-09-19",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "PARAPHRASE",
    sourceState: "INFERRED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["EDUCATION"],
    quote: clip("Jones says he wants to spread PB&J across Arkansas — preschool, broadband and jobs."),
    notes: "2022 gubernatorial frame. Historic background, not a 2026 House vote.",
  },
  {
    id: "jones-advocate-2022-09-22-shoes",
    actorId: "chris-jones-ar02",
    outlet: "Arkansas Advocate",
    title: "ON THE TRAIL: Chris Jones takes walking shoes, 'PB&J' across Arkansas",
    url: "https://arkansasadvocate.com/2022/09/22/on-the-trail-chris-jones-takes-walking-shoes-pbj-across-arkansas/",
    publishedAt: "2022-09-22",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["EDUCATION", "TAXES"],
    quote: clip("If I want to serve as governor for you, I need to know you. So why not walk a mile in your shoes?"),
  },
  {
    id: "jones-tb-2022-10-medicaid",
    actorId: "chris-jones-ar02",
    outlet: "Talk Business & Politics",
    title: "Governor candidate Chris Jones meets with agency directors, says he'll be ready on Day 1",
    url: "https://talkbusiness.net/2022/10/governor-candidate-chris-jones-meets-with-agency-directors-says-hell-be-ready-on-day-1/",
    publishedAt: "2022-10-01",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "PARAPHRASE",
    sourceState: "INFERRED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["HEALTHCARE", "RURAL_HOSPITALS"],
    quote: clip("Jones said the state's Medicaid expansion program, now known as AR Works, is critical to keeping urban and rural hospitals open."),
    notes: "2022 gubernatorial interview. Outlet paraphrase.",
  },
  {
    id: "jones-thv11-2026-aca",
    actorId: "chris-jones-ar02",
    outlet: "THV11",
    title: "How Chris Jones and others hope to defeat Rep. French Hill in 2nd District race",
    url: "https://www.thv11.com/article/news/local/arkansas-congressional-dist-2-candidates-early-voting/91-340b4c15-55a2-409c-b4a8-7cc6af13f47f",
    publishedAt: "2026-01-01",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["HEALTHCARE", "AFFORDABILITY"],
    quote: clip(
      "We know when we support the Affordable Care Act. We know that provides healthcare to millions of people. That's an example of what would make things immediately affordable and SNAP benefits work now.",
    ),
    notes: "Full THV11 page was blocked this pass. Public search snippet only. Date is approximate.",
  },
  {
    id: "hill-amp-2026-08-14-housing",
    actorId: "french-hill-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Experience Matters: Rep. French Hill Touts Track Record, Seniority in Reelection Bid",
    url: "https://armoneyandpolitics.com/experience-matters-rep-french-hill/",
    publishedAt: "2026-08-14",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["HOUSING_SUPPLY", "BANKING", "ACCOUNTABILITY"],
    quote: clip(
      "This is the first major housing bill passed in the Congress in probably two decades. It directly focuses on increasing accessibility for all Americans to housing, both rental housing and housing ownership.",
    ),
  },
  {
    id: "hill-amp-2026-08-14-hud",
    actorId: "french-hill-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Experience Matters: Rep. French Hill Touts Track Record, Seniority in Reelection Bid",
    url: "https://armoneyandpolitics.com/experience-matters-rep-french-hill/",
    publishedAt: "2026-08-14",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["HOUSING_SUPPLY", "ACCOUNTABILITY"],
    quote: clip("My views on what's been happening in Little Rock is that I think HUD has not done a good job in being held accountable. This bill has some new accountability standards for HUD."),
  },
  {
    id: "hill-amp-2026-08-14-campaign",
    actorId: "french-hill-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Experience Matters: Rep. French Hill Touts Track Record, Seniority in Reelection Bid",
    url: "https://armoneyandpolitics.com/experience-matters-rep-french-hill/",
    publishedAt: "2026-08-14",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["TAXES", "BORDER", "HOUSING_SUPPLY", "FED_INFLATION"],
    quote: clip(
      "The messaging is simple: We've stopped a major tax increase. We've reduced regulatory burden. We've secured the border. … We have lowered the cost of housing through our 21st Century Housing Act.",
    ),
  },
  {
    id: "hill-amp-2026-08-14-fed",
    actorId: "french-hill-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Experience Matters: Rep. French Hill Touts Track Record, Seniority in Reelection Bid",
    url: "https://armoneyandpolitics.com/experience-matters-rep-french-hill/",
    publishedAt: "2026-08-14",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["FED_INFLATION", "TAXES"],
    quote: clip("I've advocated for a better job done by the Federal Reserve; my bill, the Price Stability Act that I passed in committee, says the No. 1 thing that the Federal Reserve should do is fight inflation."),
  },
  {
    id: "hill-amp-2026-08-14-veterans",
    actorId: "french-hill-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Experience Matters: Rep. French Hill Touts Track Record, Seniority in Reelection Bid",
    url: "https://armoneyandpolitics.com/experience-matters-rep-french-hill/",
    publishedAt: "2026-08-14",
    accessed: A,
    outletKind: "INTERVIEW",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["VETERANS", "NATIONAL_SECURITY"],
    quote: clip(
      "We've gotten almost $100 million dollars back in earned benefits for veterans just by the persistent work of my great team in Little Rock.",
    ),
    notes: "Campaign/office-stated casework total. Not independently audited here.",
  },
  {
    id: "hill-amp-2026-08-14-banks",
    actorId: "french-hill-ar02",
    outlet: "Arkansas Money & Politics",
    title: "Experience Matters: Rep. French Hill Touts Track Record, Seniority in Reelection Bid",
    url: "https://armoneyandpolitics.com/experience-matters-rep-french-hill/",
    publishedAt: "2026-08-14",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "PREPARED_STATEMENT",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "OFFICIAL_OFFICE",
    retrievalQuality: "FULL_PUBLIC",
    topics: ["BANKING"],
    quote: clip(
      "As a former community banker in central Arkansas, I know how important our Main Street banks are to our local economy. From growing cities like Conway to our smallest rural towns, community banks drive economic growth.",
    ),
  },
  {
    id: "hill-tb-2026-07-11-housing",
    actorId: "french-hill-ar02",
    outlet: "Talk Business & Politics",
    title: "Rep. Hill says President, administration supportive of new housing law",
    url: "https://talkbusiness.net/2026/07/rep-hill-says-president-administration-supportive-of-new-housing-law/",
    publishedAt: "2026-07-11",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["HOUSING_SUPPLY"],
    quote: clip("Getting this bill into law has been anything but [easy]."),
  },
  {
    id: "hill-nwa-2026-07-11-success",
    actorId: "french-hill-ar02",
    outlet: "Northwest Arkansas Democrat-Gazette",
    title: "Housing bill championed by Hill becomes law without Trump's signature",
    url: "https://www.nwaonline.com/news/2026/jul/11/housing-bill-championed-by-hill-becomes-law/",
    publishedAt: "2026-07-11",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["HOUSING_SUPPLY"],
    quote: clip(
      "I believe this bill was a major economic policy success for this Congress and for American families. Across the country, I think it will lead to more housing being constructed.",
    ),
  },
  {
    id: "hill-katv-2026-housing-together",
    actorId: "french-hill-ar02",
    outlet: "KATV",
    title: "French Hill pushed a bipartisan housing bill across the finish line. Trump never signed it",
    url: "https://katv.com/news/local/french-hill-pushed-a-bipartisan-housing-bill-across-the-finish-line-trump-never-signed-it-american-dream-mortgages-homeowners-tax-bracket-senate-house-representatives-republicans-democrats-lawmakers-housing-act",
    publishedAt: "2026-07-11",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "DIRECT_QUOTE",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "ATTRIBUTED",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["HOUSING_SUPPLY"],
    quote: clip("By working together, debating in good faith, and putting the interests of Americans ahead of politics, good policy can become law."),
  },
  {
    id: "hill-fsc-2026-housing-law",
    actorId: "french-hill-ar02",
    outlet: "House Financial Services Committee",
    title: "21st Century ROAD to Housing Act Becomes Law",
    url: "https://financialservices.house.gov/news/documentsingle.aspx?DocumentID=411189",
    publishedAt: "2026-07-11",
    accessed: A,
    outletKind: "OFFICIAL_RELEASE",
    quoteKind: "PREPARED_STATEMENT",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "OFFICIAL_OFFICE",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["HOUSING_SUPPLY", "BANKING"],
    quote: clip(
      "This bill reduces unnecessary barriers to building, strengthens community banks, and ensures families – not institutional investors – have a fair shot at buying a home.",
    ),
  },
  {
    id: "hill-house-2025-05-29-clarity",
    actorId: "french-hill-ar02",
    outlet: "Office of Rep. French Hill",
    title: "REP. French Hill Introduces Bipartisan Digital Asset Market Structure Legislation",
    url: "https://hill.house.gov/news/documentsingle.aspx?DocumentID=9470",
    publishedAt: "2025-05-29",
    accessed: A,
    outletKind: "OFFICIAL_RELEASE",
    quoteKind: "PREPARED_STATEMENT",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "OFFICIAL_OFFICE",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["DIGITAL_ASSETS", "BANKING"],
    quote: clip(
      "Our bill brings long-overdue clarity to the digital asset ecosystem, prioritizes consumer protection and American innovation, and builds off our work in the 118th Congress.",
    ),
  },
  {
    id: "hill-house-2026-main-street",
    actorId: "french-hill-ar02",
    outlet: "Office of Rep. French Hill",
    title: "HOUSE PASSES HILL'S MAIN STREET CAPITAL ACCESS ACT",
    url: "https://hill.house.gov/news/documentsingle.aspx?DocumentID=10266",
    publishedAt: "2026-01-08",
    accessed: A,
    outletKind: "OFFICIAL_RELEASE",
    quoteKind: "PREPARED_STATEMENT",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "OFFICIAL_OFFICE",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["BANKING"],
    quote: clip(
      "This bill fixes that. It right-sizes regulations for our community banks, freeing them up to lend so entrepreneurs can invest, businesses can grow, and families can build wealth.",
    ),
  },
  {
    id: "hill-kark-2025-golden-fleece",
    actorId: "french-hill-ar02",
    outlet: "KARK",
    title: "Arkansas U.S. Rep. French Hill awards Golden Fleece to federal departments charged with veterans' mental health",
    url: "https://www.kark.com/news/state-news/arkansas-u-s-rep-french-hill-awards-golden-fleece-to-federal-departments-charged-with-veterans-mental-health/",
    publishedAt: "2025-06-01",
    accessed: A,
    outletKind: "NEWS_ARTICLE",
    quoteKind: "PREPARED_STATEMENT",
    sourceState: "OBSERVED",
    provenance: "DISCOVERY_ONLY",
    authorshipConfidence: "OFFICIAL_OFFICE",
    retrievalQuality: "PARTIAL_PUBLIC",
    topics: ["VETERANS", "WASTE"],
    quote: clip(
      "challenges in ensuring effective mental health screening for service members and veterans who are transitioning from military to civilian life.",
    ),
    notes: "Golden Fleece is Hill's official-office waste series, quoted by KARK. Date is the news cycle, not independently timestamped beyond 2025.",
  },
];

const MISSING = [
  "Full Arkansas Democrat-Gazette paywall text was not stored.",
  "Broadcast transcripts (KATV YouTube and other stations) were not ingested.",
  "Lexis/Nexis or other paid archives were not used.",
  "THV11 blocked a full-page fetch this pass; some THV11 quotes remain snippet-only.",
];

const UNCERTAINTY = [
  "Media clips are DISCOVERY_ONLY. They are not first-party campaign pages.",
  "A reporter paraphrase is not a quotation.",
  "Jones characterizations of Hill votes stay on the Jones card and are not Hill facts.",
  "Hill casework dollar totals remain office-stated.",
  "This is a first media pass, not a complete historic archive.",
];

export function getMediaClips(actorId?: string): MediaClip[] {
  if (actorId !== "chris-jones-ar02" && actorId !== "french-hill-ar02") return [];
  return MEDIA_CLIPS.filter((item) => item.actorId === actorId);
}

export function getMediaResearchSnapshot(actorId?: string): MediaResearchSnapshot | null {
  if (actorId !== "chris-jones-ar02" && actorId !== "french-hill-ar02") return null;
  const clips = getMediaClips(actorId);
  const topics = [...new Set(clips.flatMap((item) => item.topics))] as MediaTopicId[];
  return {
    version: MEDIA_RESEARCH_VERSION,
    actorId: actorId as WritingActorId,
    accessed: MEDIA_RESEARCH_ACCESSED,
    clipCount: clips.length,
    topics,
    clips,
    missing: MISSING,
    uncertainty: UNCERTAINTY,
  };
}

export function formatMediaResearchPromptLine(actorId?: string): string {
  const snap = getMediaResearchSnapshot(actorId);
  if (!snap) return "";
  const labels = snap.topics.slice(0, 8).join(", ");
  return `Media-backed stances (DISCOVERY_ONLY, ${snap.clipCount} clips): ${labels}. Outlet quotes are not first-party pages and are not generated language.`;
}
