/**
 * Pass 8 — Transcript intelligence (local, non-inventing).
 * Chapters / quotes / claim candidates / do-not-claim from workspace text only.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { TranscriptSegment } from "@/content/media/campaign-media-types";
import type { SpeechEvidenceOverlay } from "@/lib/campaign-media/evidence-types";
import { loadWorkspaceRecord } from "@/lib/media/youtube-transcripts/workspace-store";

export const TRANSCRIPT_INTEL_STORE_REL = "data/campaign-media/transcript-intelligence.json";

export type TranscriptIntelChapter = {
  id: string;
  title: string;
  startSeconds: number;
  endSeconds?: number;
  reason: string;
};

export type TranscriptIntelQuote = {
  text: string;
  startSeconds: number;
  endSeconds: number;
  reason: string;
};

export type TranscriptIntelClaim = {
  text: string;
  startSeconds?: number;
  endSeconds?: number;
  suggestedField: "whatThisProves" | "speakerNotes";
  reason: string;
};

export type TranscriptIntelProposal = {
  id: string;
  youtubeVideoId: string;
  speechId?: string;
  createdAt: string;
  chapters: TranscriptIntelChapter[];
  quotes: TranscriptIntelQuote[];
  claimCandidates: TranscriptIntelClaim[];
  doNotClaim: string[];
  warnings: string[];
  grounding: {
    segmentCount: number;
    hasWorkspaceChapters: boolean;
    status: string;
    source: string;
    isAutoGenerated: boolean;
    charCount: number;
  };
};

export type TranscriptIntelStore = {
  version: 1;
  updatedAt: string;
  purpose: string;
  proposals: TranscriptIntelProposal[];
};

const CLAIM_CUES =
  /\b(arkansas|ballot|election|vote|voting|voter|secretary|county|democracy|integrity|access|poll|clerk|sos|secretary of state)\b/i;
const FIGURE_CUES = /(\d+\s*%|\$[\d,]+|\b\d{1,3}(,\d{3})+\b)/;
const OPPONENT_CUES = /\b(opponent|republican nominee|my opponent|they claim|fake news)\b/i;
const COUNTY_WORD = /\b([A-Z][a-z]+)\s+County\b/g;

function abs(rel: string): string {
  return path.join(process.cwd(), rel);
}

function emptyStore(): TranscriptIntelStore {
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    purpose:
      "Evidence Workbench transcript intelligence proposals (chapters/quotes/claims/do-not-claim). Operator must apply.",
    proposals: [],
  };
}

export function loadTranscriptIntelStore(): TranscriptIntelStore {
  const p = abs(TRANSCRIPT_INTEL_STORE_REL);
  if (!existsSync(p)) return emptyStore();
  try {
    const raw = JSON.parse(readFileSync(p, "utf8")) as Partial<TranscriptIntelStore>;
    return {
      ...emptyStore(),
      ...raw,
      version: 1,
      proposals: Array.isArray(raw.proposals) ? raw.proposals : [],
    };
  } catch {
    return emptyStore();
  }
}

function saveStore(store: TranscriptIntelStore): void {
  const target = abs(TRANSCRIPT_INTEL_STORE_REL);
  mkdirSync(path.dirname(target), { recursive: true });
  const next: TranscriptIntelStore = { ...store, version: 1, updatedAt: new Date().toISOString() };
  const tmp = `${target}.${process.pid}.tmp`;
  writeFileSync(tmp, `${JSON.stringify(next, null, 2)}\n`, "utf8");
  renameSync(tmp, target);
}

function cleanText(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

function segmentWindow(seg: TranscriptSegment): { start: number; end: number; text: string } {
  const text = cleanText(String(seg.text ?? ""));
  const start = typeof seg.startSeconds === "number" ? seg.startSeconds : 0;
  const end =
    typeof seg.endSeconds === "number" && seg.endSeconds > start
      ? seg.endSeconds
      : start + Math.max(3, Math.min(20, text.split(/\s+/).length * 0.35));
  return { start, end, text };
}

function buildChapters(
  segments: TranscriptSegment[],
  workspaceChapters: Array<{ id: string; title: string; startSeconds: number }>,
): TranscriptIntelChapter[] {
  if (workspaceChapters?.length) {
    return workspaceChapters.slice(0, 12).map((c, i) => ({
      id: c.id || `ch-${i}`,
      title: cleanText(c.title).slice(0, 80) || `Chapter ${i + 1}`,
      startSeconds: Math.max(0, Number(c.startSeconds) || 0),
      reason: "From transcript workspace chapters (operator-reviewed source preferred).",
    }));
  }

  // Heuristic: sample roughly every 90s using the first solid sentence in-window.
  const out: TranscriptIntelChapter[] = [];
  let nextBucket = 0;
  for (const seg of segments) {
    const { start, end, text } = segmentWindow(seg);
    if (!text || text.length < 28) continue;
    if (start < nextBucket) continue;
    const title = text.split(/(?<=[.!?])\s+/)[0]?.slice(0, 72) || text.slice(0, 72);
    out.push({
      id: `auto-${out.length + 1}`,
      title: cleanText(title),
      startSeconds: Math.round(start * 10) / 10,
      endSeconds: Math.round(end * 10) / 10,
      reason: "Local heuristic chapter marker from transcript timing (not AI-invented).",
    });
    nextBucket = start + 90;
    if (out.length >= 8) break;
  }
  return out;
}

function buildQuotes(segments: TranscriptSegment[]): TranscriptIntelQuote[] {
  type Cand = TranscriptIntelQuote & { score: number };
  const cands: Cand[] = [];
  for (const seg of segments) {
    const { start, end, text } = segmentWindow(seg);
    if (text.length < 45 || text.length > 240) continue;
    let score = 0.5;
    if (/[.!?]$/.test(text)) score += 0.4;
    if (text.length > 70 && text.length < 180) score += 0.3;
    if (CLAIM_CUES.test(text)) score += 0.4;
    if (FIGURE_CUES.test(text)) score -= 0.2; // figures need verification
    cands.push({
      text,
      startSeconds: Math.round(start * 10) / 10,
      endSeconds: Math.round(end * 10) / 10,
      reason: "Verbatim local transcript segment suitable as a short quote.",
      score,
    });
  }
  cands.sort((a, b) => b.score - a.score || a.startSeconds - b.startSeconds);
  const used = new Set<number>();
  const out: TranscriptIntelQuote[] = [];
  for (const c of cands) {
    const bucket = Math.floor(c.startSeconds / 20);
    if (used.has(bucket)) continue;
    used.add(bucket);
    out.push({
      text: c.text,
      startSeconds: c.startSeconds,
      endSeconds: c.endSeconds,
      reason: c.reason,
    });
    if (out.length >= 6) break;
  }
  return out;
}

function buildClaims(segments: TranscriptSegment[]): TranscriptIntelClaim[] {
  const out: TranscriptIntelClaim[] = [];
  for (const seg of segments) {
    const { start, end, text } = segmentWindow(seg);
    if (!CLAIM_CUES.test(text)) continue;
    if (text.length < 40 || text.length > 280) continue;
    const suggestedField: TranscriptIntelClaim["suggestedField"] =
      text.length < 120 ? "whatThisProves" : "speakerNotes";
    out.push({
      text,
      startSeconds: Math.round(start * 10) / 10,
      endSeconds: Math.round(end * 10) / 10,
      suggestedField,
      reason: `Keyword-grounded claim candidate for ${suggestedField} — operator must confirm before public use.`,
    });
    if (out.length >= 8) break;
  }
  return out;
}

function buildDoNotClaim(input: {
  plainText: string;
  isAutoGenerated: boolean;
  overlay?: SpeechEvidenceOverlay | null;
  quotes: TranscriptIntelQuote[];
}): string[] {
  const list: string[] = [];
  if (input.isAutoGenerated) {
    list.push("Auto-generated captions — verify any public quote before publishing.");
  }
  if (FIGURE_CUES.test(input.plainText)) {
    list.push("Numeric figures or dollar amounts appear in transcript — do not claim exact stats without verification.");
  }
  if (OPPONENT_CUES.test(input.plainText)) {
    list.push("Opponent / partisan framing language detected — do not invent or amplify unsourced opponent claims.");
  }

  const confirmed = new Set(
    (input.overlay?.counties ?? [])
      .map((c) => c.trim().toLowerCase().replace(/\s+county$/, ""))
      .filter((c) => c && c !== "unknown"),
  );
  const mentioned = new Set<string>();
  let m: RegExpExecArray | null;
  const re = new RegExp(COUNTY_WORD);
  while ((m = re.exec(input.plainText)) !== null) {
    mentioned.add(m[1]!.toLowerCase());
  }
  for (const county of mentioned) {
    if (!confirmed.has(county)) {
      list.push(
        `Transcript mentions ${county[0]!.toUpperCase()}${county.slice(1)} County — do not confirm geography until operator verifies.`,
      );
    }
    if (list.length >= 10) break;
  }

  if (!input.quotes.length) {
    list.push("No strong quote candidates found — do not invent spoken lines.");
  }

  list.push("Do not invent counties, cities, venues, or dates not already Confirmed on the speech overlay.");
  return [...new Set(list)].slice(0, 12);
}

export function analyzeTranscriptIntelligence(input: {
  youtubeVideoId: string;
  speechId?: string;
  overlay?: SpeechEvidenceOverlay | null;
  /** Test/smoke: supply segments without a workspace file. */
  segmentsOverride?: TranscriptSegment[];
  plainTextOverride?: string;
  chaptersOverride?: Array<{ id: string; title: string; startSeconds: number }>;
  statusOverride?: string;
  sourceOverride?: string;
  isAutoGeneratedOverride?: boolean;
}): { ok: true; proposal: TranscriptIntelProposal } | { ok: false; error: string } {
  const youtubeVideoId = String(input.youtubeVideoId ?? "").trim();
  if (!youtubeVideoId) return { ok: false, error: "youtubeVideoId required." };

  const ws = loadWorkspaceRecord(youtubeVideoId);
  const segments =
    input.segmentsOverride?.length
      ? input.segmentsOverride
      : Array.isArray(ws?.segments)
        ? ws!.segments
        : [];
  const plainText =
    cleanText(input.plainTextOverride ?? "") ||
    cleanText(ws?.plainText ?? "") ||
    segments.map((s) => cleanText(String(s.text ?? ""))).filter(Boolean).join(" ");

  if (!plainText && !segments.length) {
    return {
      ok: false,
      error: "No local transcript workspace for this YouTube id — pull/review transcript first.",
    };
  }

  const effectiveSegments: TranscriptSegment[] =
    segments.length > 0
      ? segments
      : plainText.split(/(?<=[.!?])\s+/).map((text, i) => ({
          id: `p-${i}`,
          text,
          startSeconds: i * 8,
          endSeconds: i * 8 + 6,
        }));

  const chapters = buildChapters(
    effectiveSegments,
    input.chaptersOverride ?? ws?.chapters ?? [],
  );
  const quotes = buildQuotes(effectiveSegments);
  const claimCandidates = buildClaims(effectiveSegments);
  const isAutoGenerated = input.isAutoGeneratedOverride ?? Boolean(ws?.isAutoGenerated);
  const doNotClaim = buildDoNotClaim({
    plainText,
    isAutoGenerated,
    overlay: input.overlay,
    quotes,
  });
  const warnings: string[] = [];
  if (!ws && !input.segmentsOverride?.length && !input.plainTextOverride) {
    warnings.push("Workspace missing — analysis used overrides only.");
  }
  if (isAutoGenerated) warnings.push("Source captions are auto-generated.");
  if (!chapters.length) warnings.push("No chapter markers produced.");

  const proposal: TranscriptIntelProposal = {
    id: `tintel-${youtubeVideoId}-${Date.now()}`,
    youtubeVideoId,
    speechId: input.speechId,
    createdAt: new Date().toISOString(),
    chapters,
    quotes,
    claimCandidates,
    doNotClaim,
    warnings,
    grounding: {
      segmentCount: effectiveSegments.length,
      hasWorkspaceChapters: Boolean((input.chaptersOverride ?? ws?.chapters)?.length),
      status: String(input.statusOverride ?? ws?.status ?? "UNKNOWN"),
      source: String(input.sourceOverride ?? ws?.source ?? "UNKNOWN"),
      isAutoGenerated,
      charCount: plainText.length,
    },
  };

  const store = loadTranscriptIntelStore();
  store.proposals = [proposal, ...store.proposals].slice(0, 80);
  saveStore(store);
  return { ok: true, proposal };
}

export function getLatestTranscriptIntel(youtubeVideoId: string): TranscriptIntelProposal | null {
  const id = String(youtubeVideoId ?? "").trim();
  if (!id) return null;
  return loadTranscriptIntelStore().proposals.find((p) => p.youtubeVideoId === id) ?? null;
}

export type TranscriptIntelApplyFields =
  | "whatThisProves"
  | "speakerNotes"
  | "keyQuotes"
  | "doNotClaim"
  | "transcriptChapters";

/**
 * Merge selected proposal fields into a speech overlay (does not invent geography).
 */
export function applyTranscriptIntelToOverlay(input: {
  overlay: SpeechEvidenceOverlay;
  proposal: TranscriptIntelProposal;
  applyFields: TranscriptIntelApplyFields[];
  claimIndex?: number;
}): SpeechEvidenceOverlay {
  const fields = new Set(input.applyFields);
  const next: SpeechEvidenceOverlay = { ...input.overlay };
  const claim =
    typeof input.claimIndex === "number"
      ? input.proposal.claimCandidates[input.claimIndex]
      : input.proposal.claimCandidates.find((c) => c.suggestedField === "whatThisProves") ??
        input.proposal.claimCandidates[0];

  if (fields.has("whatThisProves") && claim?.suggestedField === "whatThisProves") {
    next.whatThisProves = claim.text.slice(0, 500);
  } else if (fields.has("whatThisProves") && claim) {
    next.whatThisProves = claim.text.slice(0, 500);
  }

  if (fields.has("speakerNotes")) {
    const notes = input.proposal.claimCandidates
      .filter((c) => c.suggestedField === "speakerNotes")
      .slice(0, 3)
      .map((c) => c.text);
    const fromQuotes = input.proposal.quotes.slice(0, 2).map((q) => q.text);
    next.speakerNotes = [...notes, ...fromQuotes].join("\n\n").slice(0, 2000) || next.speakerNotes;
  }

  if (fields.has("keyQuotes")) {
    next.keyQuotes = input.proposal.quotes.slice(0, 6).map((q) => q.text);
  }

  if (fields.has("doNotClaim")) {
    next.doNotClaim = input.proposal.doNotClaim.slice(0, 12);
  }

  if (fields.has("transcriptChapters")) {
    next.transcriptChapters = input.proposal.chapters.slice(0, 12).map((c) => ({
      title: c.title,
      startSeconds: c.startSeconds,
    }));
  }

  next.transcriptIntelAt = new Date().toISOString();
  next.transcriptIntelPlanId = input.proposal.id;
  next.updatedAt = new Date().toISOString();
  return next;
}
