export type ChapterSourceRecord = {
  chapter: number;
  label: string;
  coverage: string[];
  cautions: string[];
  controlFile: string;
  references?: { label: string; href?: string }[];
};

export const CHAPTER_SOURCES: ChapterSourceRecord[] = [
  { chapter: 1, label: "Major transitions and biological individuality", coverage: ["Major evolutionary transitions", "Biological individuality", "Inference beyond unaided perception"], cautions: ["The intelligent microbe is a thought experiment, not evidence.", "Scale transition in biology is precedent, not a diagnosis of civilization."], controlFile: "86-pub-6y-chapters-1-6-claim-source-resolution-and-core-bibliography.md", references: [{ label: "West et al. — Major evolutionary transitions", href: "https://pubmed.ncbi.nlm.nih.gov/25964342/" }] },
  { chapter: 2, label: "Comparative sensory biology", coverage: ["UV and polarization sensitivity", "Infrared sensing", "Echolocation", "Electroreception", "Magnetoreception"], cautions: ["Behavioral evidence for magnetoreception is stronger than any single proposed receptor mechanism.", "Unseen signals do not validate unsupported hidden phenomena."], controlFile: "86-pub-6y-chapters-1-6-claim-source-resolution-and-core-bibliography.md" },
  { chapter: 3, label: "Timescale, sampling, and biological scaling", coverage: ["Sampling windows", "Time-series inference", "Biological scaling", "Long-timescale physical records"], cautions: ["No universal biological clock is claimed.", "Duration or speed is not evidence of life or agency."], controlFile: "86-pub-6y-chapters-1-6-claim-source-resolution-and-core-bibliography.md" },
  { chapter: 4, label: "Multicellularity, symbiosis, and somatic cooperation", coverage: ["Multicellularity", "Endosymbiosis", "Microbiome nuance", "Cell turnover", "Somatic conflict"], cautions: ["A body is precedent for higher-order individuality, not evidence that every collective is an organism."], controlFile: "86-pub-6y-chapters-1-6-claim-source-resolution-and-core-bibliography.md" },
  { chapter: 5, label: "Major transitions, cooperation, and conflict control", coverage: ["Major transitions", "Conflict suppression", "Bottlenecks", "Germ-soma specialization", "Eusociality and criterion dependence"], cautions: ["Cooperation alone is not individuality.", "Selection at a level does not automatically establish organismhood."], controlFile: "86-pub-6y-chapters-1-6-claim-source-resolution-and-core-bibliography.md", references: [{ label: "Bourke — conflict and major transitions", href: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10565403/" }] },
  { chapter: 6, label: "Plural concepts of biological individuality", coverage: ["Immune identity", "Symbiosis", "Developmental boundaries", "Lineage boundaries", "Ecological boundaries"], cautions: ["No single anatomical or immune boundary is treated as a universal membership oracle."], controlFile: "86-pub-6y-chapters-1-6-claim-source-resolution-and-core-bibliography.md" },
  { chapter: 7, label: "Bioelectricity and membrane physiology", coverage: ["Ion gradients", "Membrane potential", "Gap junctions", "Non-neural bioelectric signaling", "Wound electric fields", "Electrotaxis"], cautions: ["Bioelectricity is ordinary biophysics.", "Frequency is a measurement, not an explanation.", "Broad claims must not depend on one research program."], controlFile: "87-pub-6z-chapters-7-11-claim-source-resolution.md", references: [{ label: "Bioelectricity review — PMC8180260", href: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8180260/" }] },
  { chapter: 8, label: "Morphogenesis and distributed developmental control", coverage: ["Gene regulation", "Cell signaling", "Reaction-diffusion", "Tissue mechanics", "Geometry", "Developmental robustness"], cautions: ["Morphogenesis is not reduced to one mechanism school.", "Reaction-diffusion is a mechanism class, not a universal blueprint."], controlFile: "87-pub-6z-chapters-7-11-claim-source-resolution.md", references: [{ label: "Morphogenesis review — PMC4051191", href: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4051191/" }] },
  { chapter: 9, label: "Regeneration and positional information", coverage: ["Salamander regeneration", "Wound epithelium", "Blastema", "Innervation", "Positional information", "Planarian comparison"], cautions: ["Restored form does not establish a conscious target.", "Target-state and pattern-memory vocabulary is interpretive and must remain operationally defined."], controlFile: "87-pub-6z-chapters-7-11-claim-source-resolution.md", references: [{ label: "Salamander regeneration — PMC4036467", href: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4036467/" }] },
  { chapter: 10, label: "Physical memory outside conscious recollection", coverage: ["Neural memory", "Adaptive immune memory", "Trained immunity", "Persistent developmental state", "Plant stress memory"], cautions: ["Trace, storage, functional memory, and conscious recollection are separate categories.", "A memory claim requires a persistent physical state capable of later causal re-entry."], controlFile: "87-pub-6z-chapters-7-11-claim-source-resolution.md", references: [{ label: "Trained immunity — PMC5087274", href: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5087274/" }] },
  { chapter: 11, label: "Circadian organization and prospective prediction", coverage: ["Circadian systems", "Entrainment", "Endogenous oscillators", "Prospective prediction"], cautions: ["Preparation, prediction, foresight, and prophecy are distinct.", "Retrospective fit alone cannot establish prediction."], controlFile: "87-pub-6z-chapters-7-11-claim-source-resolution.md", references: [{ label: "Circadian review — PMC3378387", href: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3378387/" }] },
  { chapter: 12, label: "Collective intelligence and distributed cognition", coverage: ["Collective intelligence", "Collaborative problem solving", "Decentralized systems", "Distributed cognition", "Relational information"], cautions: ["Collective performance does not establish one cognitive individual.", "Whole-Only Information does not privilege one information-theoretic formalism."], controlFile: "88-pub-7a-chapters-12-16-claim-source-resolution-and-final-scholarly-hardening.md" },
  { chapter: 13, label: "Externalized cognition and infrastructure", coverage: ["Distributed cognition", "Cognitive artifacts", "Global observing systems", "External records", "Networked infrastructure"], cautions: ["Nervous-system language is functional analogy, not biological identity."], controlFile: "88-pub-7a-chapters-12-16-claim-source-resolution-and-final-scholarly-hardening.md", references: [{ label: "Helbing — globally networked risks", href: "https://doi.org/10.1038/nature12047" }] },
  { chapter: 14, label: "Individuality, intervention, and model competition", coverage: ["Biological individuality", "Major transitions", "Conflict suppression", "Information methods", "Higher-level explanation", "Model comparison"], cautions: ["The Eleven Tests are this project's proposed synthesis, not a consensus checklist.", "Higher-level explanatory usefulness does not settle ontology or establish biological individuality."], controlFile: "88-pub-7a-chapters-12-16-claim-source-resolution-and-final-scholarly-hardening.md", references: [{ label: "Franklin-Hall — high-level explanation", href: "https://doi.org/10.1093/bjps/axu040" }] },
  { chapter: 15, label: "Skeptical model prosecution", coverage: ["Prior chapter evidence", "Alternative explanations", "Falsifiability", "Negative results"], cautions: ["The chapter inherits earlier sourcing unless it introduces a new factual burden.", "A theory that cannot lose is not scientific."], controlFile: "88-pub-7a-chapters-12-16-claim-source-resolution-and-final-scholarly-hardening.md" },
  { chapter: 16, label: "Synthesis and research program", coverage: ["Established record", "Macroscopic Life Hypothesis", "Eleven-Test research program", "Model C verdict"], cautions: ["The hypothesis and Eleven Tests are project-specific synthesis.", "Epistemic humility is not positive evidence."], controlFile: "88-pub-7a-chapters-12-16-claim-source-resolution-and-final-scholarly-hardening.md" },
];

export function sourcesForChapter(chapter: number) {
  return CHAPTER_SOURCES.find((record) => record.chapter === chapter);
}
